### ISSUE TITLE
Game crash with Chinese manual translation

### ISSUE THREAD

**Issue by Joccob** [sinkillerj/ProjectE#1006]
I can't open the game if I have my ProjectE mod with the newest zh_CN translation. And I am pretty sure its causing by the guide book translation.
So here is the crash report: http://pastebin.com/VLijU0H2
And here is my translation (only the manual part): http://pastebin.com/thEvQKMS
Hope u guys can tweak it a little bit.

**Comment by williewillus** [comment]
@Lilylicious

**Comment by Lilylicious** [comment]
Seems that it's not stopping the recursive wrapping. Or the string this being wrapped has more than 1024 parts.

**Comment by Joccob** [comment]
Umm is that possible to make it wrap automatically like thuamcraft or tinker's consruct guide book?

**Comment by Lilylicious** [comment]
It already does.

**Comment by Joccob** [comment]
Oh really? Then I'm confused because those books work quite well with Chinese tanslation...
Anyway, thx for your quick reply and hope you guys can figure it out soon

**Comment by Lilylicious** [comment]
Update: The wrapping function is not wrapping properly with chinese. 

Where the length of the wrapping would go something like this normally: "1000, 950, 900, 850", in the chinese translation it goes "1000, 950, 950, 950, 950, 950", meaning after the first run through it doesn't substring properly. I have no idea why, I'll keep digging.

**Comment by Lilylicious** [comment]
Fixed in PR #1012

Encoding needed to be UTF-16 to be handled properly by the fontrenderer.

**Comment by Joccob** [comment]
@Lilylicious 
Umm I just try the newest 1.9.3h version. The game does not crash but it seems like the lang file does not loaded at all...all the items of ProjectE include the book are in English. Not sure what happens...
