### ISSUE TITLE
RM Furnace don't accept relay all mk's

### ISSUE THREAD

**Issue by enzoright** [sinkillerj/ProjectE#1007]
the RM Furnace don't accept relay all mk's
in the Version 1.7.10-PE1.9.2

**Comment by williewillus** [comment]
Potential duplicate of #1002

**Comment by MaPePeR** [comment]
but #1002 is supposed to be fixed by #1003, which is merged into PE1.9.2

**Comment by MaPePeR** [comment]
I think the problem is, that the relays don't implement the 'active push' that is needed.

**Comment by Ian-Luminus** [comment]
Original EE2 behaved like this intentionally. Should just put 5 Collectors around it.
