### ISSUE TITLE
Offensive Abilities from Gem armor don't work

### ISSUE THREAD

**Issue by enzoright** [sinkillerj/ProjectE#1008]
version: 1.7.10-PE1.9.2
You can't use the offensive abilities.

**Comment by williewillus** [comment]
Cannot reproduce. More details?

**Comment by williewillus** [comment]
1. Put armor on
2. Switch to open hand and hit V to ready offensive abilities
3. Press c to boom with chestplate, r to zap with helmet.

**Comment by williewillus** [comment]
inactivity
