### ISSUE TITLE
red katar issue

### ISSUE THREAD

**Issue by Ace199102840** [sinkillerj/ProjectE#1009]
using latest ProjectE-1.7.10-PE1.9.2.jar  ,  red katar does not attack all mobs on slay all hostile mode or slay hostile mode when right clicking around mobs.

red katar sheers sheep, its unclear how to switch the mode of the katar when ive used all hotkeys for project e and even switched them to other hotkeys in case of conflicting bindings. it only toggles between slay hostile mode and slay all mode.

**Comment by williewillus** [comment]
I can't reproduce. Latest code, hitting 'C' kills things as expected

**Comment by Ace199102840** [comment]
G was to change the modes on the katar  so when you right click it would use that ability. so you'd cycle through sheer , attack,  cut down logs , etc.... then you'd right click to use that ability. since when did pressing C make it attack everything in an aoe?  pressing c for me worked.  i now notice that i cant sheer leaves from trees as this was one of the abilities. now it just takes down trees only when i right click.  but yet i can look at the grass and instantly till it.  is there a way to cycle through the abilities by pressing g and using the ability choosing by right click?

**Comment by williewillus** [comment]
It's been like this in PE for ages, and the control scheme was deliberately matched to EE2.
I will revisit it at some point so it reaches full ee2 parity (namely leaf shearing), but for now it's fine as it is
