### ISSUE TITLE
config request

### ISSUE THREAD

**Issue by Ace199102840** [sinkillerj/ProjectE#1011]
would it be possible to have a config for the katar slay all mode turned off for multiplayer? or have an option to have it uncraftable or both.   i cant find such an option in the config , less i missed it.  the slay all mod one shots other players wearing full gem armor and with having extra health with the canisters from tinker's construct. its way too powerful when you can spam C or hold down the key and kill any player near you simply cause they got within 4-6 blocks close. an option to set its strength would also be great too to nerf or buff it,  if an admin so chooses. maybe setting a cooldown could be another option then a player couldnt greif by spawn camping.

**Comment by sinkillerj** [comment]
Recipes can be removed with Minetweaker, further recipe configs may be considered in the future.

**Comment by williewillus** [comment]
I will look at making the damage amount configurable

**Comment by Ace199102840** [comment]
@williewillus  that would be amazing (:
