### ISSUE TITLE
Dimension change bug that prevents you from using stairs? 

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#1018]
I only heard rumors about this(yay twitch chat...), but apparently there is a bug in the latest version that has something to do with not being able to use stairs after changing dimensions...

**Comment by williewillus** [comment]
Found it.
MC is stupid and sets the serverside step height of EntityPlayerMP to 0 since client controls movement instead of just some sane default value

**Comment by MaPePeR** [comment]
Awesome!

**Comment by FPSaddiction** [comment]
I was locked out of my github account yesterday, or I would have created this issue.
