### ISSUE TITLE
thaumcraft emc mapper for infusion crafting and arcane table

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#1020]
simply if possible the thaumcraft aspects will be given EMC value and the emc value of the aspect used in infusion/ arcane crafting will be used when infusion crafting, also you can be smart about it and only give the primal aspect emc value and calculate the rest of aspects value using the addition of the emc of the 2 aspects that originally  made that aspect

for a more clear example let me explain it like this

take the  primal aspects and give them emc like AER aspect can have emc of 25 . AQUA can have 30 emc and IGNIS can have 25 emc and so on

now to get the emc value of the aspect lux. in thaumcraft lux is made by combining AER aspect and IGNIS so in order to get emc for lux you just combine IGNIS+AER emc which is 25+25 which =50 so the emc for lux is 50. and so on you give emc values to the rest of the aspects this way

now for infusion crafting, simply take all the items used in crafting + the amount of aspects used to give the output item an emc

example

item X requires 64 lux + 3 glowstone blocks to craft, now take the emc from lux which as we know is 50 then multiply by 64 because we need 64 of aspect to craft, then the result would 3200 emc.

now add the emc of the items used in crafting (in our case 3 glowstone blocks) and let's assume glowstone has emc of 1000 (forgot the real emc :/) so 3 blocks which means 3x1000= 3000 and add in the emc from aspects which is 3200, so finally we get the emc of item X which is 6200.

the same applies to aspects used from wand in arcane table crafting 

phew hopefully it makes sense in a way

**Comment by blackdragonIV** [comment]
also maybe a plugin that cross over thaumcraft and PE where a table can exchange aspects with emc and emc to aspects in liquid or as a wand charge forum

**Comment by williewillus** [comment]
@Lilylicious has been working on something like this

**Comment by sinkillerj** [comment]
This is the job of a addon and is beyond the scope of ProjectE itself, as willie points out lily is also already working on some thaumcrafty things.
