### ISSUE TITLE
Relays don't push EMC to active Collectors in power flowers

### ISSUE THREAD

**Issue by Ian-Luminus** [sinkillerj/ProjectE#1021]
As title says. I have 5 Relays around a central Collector, and Collectors around the Relays (6t 6w 5d design), and what it USED to do is pull energy from the Relays, which was being pushed by the other Collectors, to speed up the passive upgrade of EMC-fuels in the center Collector.

I mean no offense by this, but it looks like someone new took over the coding side of things.. so, for reference, it was working fine in version 1.5.0. I took a break from Minecraft and that was the last one I'd had installed.

EDIT: Downgraded to version 1.8.0 from 1.9.2 and the issue is resolved. Dunno how many internal versions there were between these, but I hope it helps narrow down the search some.

**Comment by sinkillerj** [comment]
Unless you can confirm this happens in EE2 or Tekkit Classic this was never intended behavior.

**Comment by Ian-Luminus** [comment]
It was a core aspect of EE2? I remember 'cause classic EE2 never did the Redstone/Alchemical/Mobius/Aeternalis blocks in the collector's upgrade process.

**Comment by Ian-Luminus** [comment]
Now that 1.10 packs are rolling out, I've updated to such as well. This is still an ongoing issue - the Collector(s) won't accept energy from the Relay while upgrading fuels. Even in original EE2, you could directly pass energy from one collector to another by setting them side by side, the one upgrading fuels would get an increase in speed. I can make video of such if needed, on request.

Using ProjectE-1.10.2-PE1.1.1B
