### ISSUE TITLE
Gem of Eternal Density does not consume tools (pickaxes, shovels, swords, axes). 

### ISSUE THREAD

**Issue by rewable** [sinkillerj/ProjectE#1025]
Or maybe i am doing something wrong?

**Comment by MaPePeR** [comment]
This is intended.... you don't really want it to eat your tools

**Comment by rewable** [comment]
Can i fix it?

**Comment by MaPePeR** [comment]
no.

**Comment by rewable** [comment]
Thank you for answer.

**Comment by williewillus** [comment]
The condenser and transmutation interfaces take tools
The Gem of Eternal Density is intended for use on a player mainly, and having all of your vital tools eaten and destroyed by the Gem really isn't cool :p
If you need it for automation use a condenser
