### ISSUE TITLE
Transmutation Table mouse wheel dupe glitch

### ISSUE THREAD

**Issue by Nick76e** [sinkillerj/ProjectE#1026]
You can take items out of a transmutation table with your mouse wheel and it takes EMC; But if you try to put an item inside the transmutation table with the wheel, it will add EMC to the table but not take the item. Upon re-entering the table, it refreshes the EMC to before it was increased via wheel. One can simply make their EMC very high by using this, and take out a ton of something very expensive. When you open the table after it views the EMC as 0. You can but that expensive item back into the table for a full refund.

**Comment by sinkillerj** [comment]
Known client side desync, the EMC is never actually added, there is no actual dupe.
