### ISSUE TITLE
Items removed from Table after making Ring

### ISSUE THREAD

**Issue by Majestyc2k1** [sinkillerj/ProjectE#1027]
I used the Table to help create Swiftwolf's Ring (dark matter and such). After I created the Ring, I left the table (and the game) alone for awhile with only a few thousand EMC stored. I went back later to reload more EMC and discovered several of the PE items had been unlearned from the Table, like dark matter, the alchemical coal and fuels, philisopher's stone, etc. The table was able to relearn these items.

Using MC 1.8, Forge 11.14.3.1450 and PE 1.0.1.B

**Comment by williewillus** [comment]
I don't think it unlearned the items, the table just does not show you items you cannot afford.

**Comment by Majestyc2k1** [comment]
When I loaded enough EMC, the items did not reappear. Plus when I put the items on the left side of the Table, the "Learned" text appeared, like it does when it first learns something. I didn't lose anything, the Table just seemed to forget what items had been previously learned.

**Comment by Barhandar** [comment]
I've had the same thing happen. Notably, it's not EMC-level-culling issue as among unlearned things were very cheap ones, but there's a pattern in that it's mostly mod items that disappear.

Like witchwood logs (AM2, 32 EMC) or Elemental Shards (TC4, 64 EMC). Surprisingly not Greatwood Log (TC4, 32 EMC). All of ProjectE's fuels disappeared and so did all matter-related things. 


Speaking of which, where are learned things even _stored_? The issue might be alleviated if I can make backups.

**Comment by williewillus** [comment]
everything is stored in the player.dat

**Comment by MaPePeR** [comment]
maybe we are running into a limitation of how many items can be stored in a nbt list?

**Comment by Barhandar** [comment]
>maybe we are running into a limitation of how many items can be stored in a nbt list?

After culling mine had 137 entries, which isn't the magic value (namely, 128). And according to NBT format specification, NBTList can hold up to 2 billion entires. So it's not a limitation of storage, even if it's a limitation it is of code that works with storage.

**Comment by williewillus** [comment]
Remake if this can be reproduced in 1.10+
