### ISSUE TITLE
Console spam on block breaking check

### ISSUE THREAD

**Issue by LemADEC** [sinkillerj/ProjectE#1030]
Server console gets spammed to the point of lagging it with the following message: "Checked place block passed!".

This appears to come from here: https://github.com/sinkillerj/ProjectE/blob/c2bdfb16d0a8bd99d95fde2b67f7928a09cf9618/src/main/java/moze_intel/projecte/utils/PlayerHelper.java#L58

In the configuration, Debug logging is off, so I'm surprised to see this log:
```
    # Enable a more verbose debug logging [default: false]
    B:debugLogging=false
```

This is ProjectE-1.7.10-PE1.9.2.jar on KCauldron 1.7.10-1492.155

**Comment by LemADEC** [comment]
This is caused by using Philosopher stone to change blocks in the world.
This is reproduced in single player.

**Comment by sinkillerj** [comment]
Looks like a line that was forgotten after the beta, sorry!
