### ISSUE TITLE
Inventory Tweaks Dupe (Not Visual)

### ISSUE THREAD

**Issue by babyblasphemy** [sinkillerj/ProjectE#1032]
I've seen various issues about this, and at first I though it was just visual, but then I noticed something. If you have a single item, and then scroll up with it in the transmutation table, it will increase the amount of that item until you get to a stack. After that, it will start adding the "fake" EMC that disappears once you close the table.
I was able to use these items that filled up the stack to craft a block, place it in the world, and used World Edit to check if it was actually there.
It appears that if the table already has any EMC in it, it it only creates "fake" EMC, as opposed to increasing the amount off the item in the stack you are scrolling up on.

![teh dupe 1](https://cloud.githubusercontent.com/assets/12488365/10241816/0e7931ce-68a1-11e5-9c3e-6101c86b25aa.gif)

**Comment by MaPePeR** [comment]
Fixed with #1016, which was merged and will be in the next release.

**Comment by babyblasphemy** [comment]
Thanks for the speedy response!
