### ISSUE TITLE
Transmutation Table, Tablet dupe

### ISSUE THREAD

**Issue by NicholasOwens** [sinkillerj/ProjectE#1037]
Hello i have found a glitch that with the trans table, tablet which can be used to dupe.Cause of this its now banned on a server i love to play. I play the tekkit legends modpack. i couldn't get it to work for me but heres a video by someone also theres a glitch with the alchemical chest that you can put a item in then open it and have something break it and then you take the item out put it in a dispenser and just keep powering it so heres a vid.https://www.youtube.com/watch?v=-KWbq5dYGtI&ab_channel=Slice

**Comment by sinkillerj** [comment]
Never heard of shift clicking doing this, only the scroll wheel issue. Do you have to do anything else such as shift clicking rapidly or?

**Comment by NicholasOwens** [comment]
i updated it

**Comment by sinkillerj** [comment]
The video you have linked is of EE2 in Tekkit Classic from years ago...

**Comment by NicholasOwens** [comment]
sigh. i am trying to find out how there duping. although i can't find how they will,but they won't answer me.
