### ISSUE TITLE
[Suggestion] AE2 and ProjectE Integration

### ISSUE THREAD

**Issue by MrTestificate1** [sinkillerj/ProjectE#1042]
I have a addon suggestion or built into ProjectE itself but it's basically AE2 integration with the transmutation tablet. It would be a seperate terminal that acts as a transmutation tablet.

**Comment by sinkillerj** [comment]
Please see: http://forum.feed-the-beast.com/threads/1-7-10-equivalent-energistics-autocrafting-with-emc.95847/
