### ISSUE TITLE
Balancing Issue - Repair Talismans and Vanilla Tools / Armour

### ISSUE THREAD

**Issue by Rob5Underscores** [sinkillerj/ProjectE#1043]
Many people on my server are using condensers to create low durability tools, pipe them into a chest full of repair talismans and repair them then pull it into another condenser for massive EMC profit.

Please add a config option for either of the following which I think will fix the issue;
1) Make repair talismans have a (possibly configurable) durability
2) Make it so that the effect of multiple talismans in a chest does not stack (or stacks to a limit).
3) Add balancing options for degraded tools/armour.

Thanks!

**Comment by sinkillerj** [comment]
Thank you for opening this. Currently we are aware of the issue and it will be addressed upon the completion of #891
