### ISSUE TITLE
Hurricane Boots Creative Flight ability stops working after dimension change.

### ISSUE THREAD

**Issue by iHeartZigg** [sinkillerj/ProjectE#1044]
After switching dimensions, hurricane boots will always have its creative flight ability disabled until you un-equip, and re-equip them.

Running newest version of ProjectE - PE1.9.3h (and 1.9.2) (ontop of FTB Infinity+Morph).

There's not a lot of info i can give other than this, reproducing it is simple; Equip Hurricane Boots and enter another dimension.

**Comment by williewillus** [comment]
is this reproducible in 1.9.3 (no h) and 1.9.2?

**Comment by iHeartZigg** [comment]
I don't know about 1.9.3, but the bug occurs in 1.9.2 for sure.

**Comment by iHeartZigg** [comment]
Decided to test it in a 'pure' install so to speak (Only Forge & PE.) and it doesn't happen when switching dimensions, HOWEVER it does stop working if i go from creative mode to survival.

So i'm thinking there's some incompatibility with fly-enabled mods. (Morph?)

**Comment by williewillus** [comment]
The FOV thing is a vanilla bug, not sure if it's fixed in 1.8+
Whenever you have an item equipped that modifies the speed attribute (the boots uses vanilla attributes to boost speed) when you dimension change vanilla doesnt recheck for those and adjust your fov

I'll look into the other one

**Comment by iHeartZigg** [comment]
Yeah, so far it looks like mod incompatibility but i haven't been able to figure out which one.

It happens using recommended FTB Infinity, if you want to go more in-depth.

**Comment by williewillus** [comment]
Closing, redirect to #1067 (same issue)
