### ISSUE TITLE
Duplicate tooltips

### ISSUE THREAD

**Issue by sinkillerj** [sinkillerj/ProjectE#1045]
I've tried running on a newer version of Forge but the duplicate tooltips remain, its as though the event is being called twice and for the life of me I cant find why. You know anything about this @williewillus ?

**Comment by williewillus** [comment]
I think it was either a Forge or NEI bug

**Comment by sinkillerj** [comment]
No NEI in the newer Forge environment I ran so that ones out, do you remember where you found out it was a bug?

**Comment by MaPePeR** [comment]
https://github.com/sinkillerj/ProjectE/blob/MC18/src/main/java/moze_intel/projecte/PECore.java#L98-L103
