### ISSUE TITLE
1.7 Infinite loop crash from all mining tools on server

### ISSUE THREAD

**Issue by nanakisan** [sinkillerj/ProjectE#1052]
Any server that runs anti-grief plugins suffer a crash from a loop.

There is no report but according to Afterwind for MyTown2 he believe it's your guys side of things.

ProjectE's mining tools that have a right click harvest function for ores in protected areas. instead of the expected "no blocks broken" instead the offending tool goes haywire. It then repeatedly keeps breaking the blocks despite being told no by the server. They simply do not stop trying at all. Which in turn causes the server to lock up entirely.

So far tested this against
WorldGuard
GriefPrevention
MyTown2 (this 1 is mod sided so it shows how bad this is)

**Comment by williewillus** [comment]
heya nanakisan!
could you email me an instance of a server with any one of the protection plugins / configs that I could test against?
thanks!

**Comment by nanakisan** [comment]
I can easily invite you to mine actually. We're prepping a tekkit legends server. So i'm literally going over everything before prepping the final ban list.

**Comment by tyler489** [comment]
Also same issue with grief prevention

**Comment by MrWisski** [comment]
http://pastebin.com/nBHJzYHS

FML/KCauldron, Tekkit Legends modpack, running GriefPrevention plugin (among others, but those dont seem to be major contributors). That stack trace, in various mutations, gets spammed to console - seems to be the issue described above. Server gets locked up in this state until the wrapper detects the hang and force-restarts the server. At which point the silly player who was trying to vein mine, tries it again to the same effect T_T

This has killed the server a couple of times now - Hoping for a quick resolution and a fast patch & distribution from the modpack creator. 

Cheers!
MrWisski

**Comment by williewillus** [comment]
yup, I'll get to it asap
A little busy w school right now, I can probably take a look at it around next wednesday, fix pr'ed by maybe that saturday?
thanks for your patience
or if @MaPePeR or @Lilylicious wants to be the bug hunter go ahead :p

**Comment by MaPePeR** [comment]
Problem is, that the World Helper harvest vein method starts a new recursion on blocks it did not break. Moving the recursion call into the if that checks for break permissions might fix it. 

The better option might be to first create a list of blocks in the vein and then iterate through that list breaking the blocks and checking for permissions. (maybe even use the explosion event for that, so we don't generate 1000 events). 

(I'm not going to PR at the moment)

**Comment by MaPePeR** [comment]
Not breaking the blocks in the recursion is a risky thing: at the moment it would turn the code into a depth first search, so extra effort needs to be taken to keep it breath first!

Because the recursion uses the "there is no block anymore" as a stopping condition.

**Comment by MaPePeR** [comment]
Writing a simple test mod that just disallows all block breaking should be fairly easy. Maybe you could use something like that to test it.

**Comment by tyler489** [comment]
#1075

**Comment by shobu9** [comment]
@MaPePeR @williewillus Close this issue ?

**Comment by williewillus** [comment]
yeah it's merged
