### ISSUE TITLE
Java 7

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#1053]
https://imgur.com/a/EWt6X

As you can see, Java 6 is basically nonexistent (<0.2%)

Please? :D

I think we can move to Java 7 finally (I want to use 8 but realistically that's still too many people on 7 to drop them, though the vanilla launcher uses 8 by default).

**Comment by sinkillerj** [comment]
I told you months ago that we could drop 6 for 7.

**Comment by williewillus** [comment]
Wat ok :p
