### ISSUE TITLE
(suggestion) connected texture

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#1054]
adds connected textures on DM, RM blocks and mobius / Aeternalis fuel blocks also you can place transmutation table to have them combine in textures in 1x3 , 2x2 , 3x3 , 2x3 , 1x2... etc essentially all possible combination up to a 3x3

**Comment by sinkillerj** [comment]
Possibly with a resource pack, currently beyond the scope of the mod and adds extra RAM usage.
