### ISSUE TITLE
can't show NEI-recipes/uses while having the transtable/transtablet open

### ISSUE THREAD

**Issue by vincentmet** [sinkillerj/ProjectE#1057]
when pressing 'R' on a item, it doesnt show the item, this only occurs while in the gui of the transmutationtable or the transmutationtablet

**Comment by williewillus** [comment]
@Lilylicious you know anything about how NEI handles these things?

**Comment by MaPePeR** [comment]
I would assume our search bar catches the keyboard event even when it is not focused. Just an assumption, though.

**Comment by williewillus** [comment]
not a problem in JEI
