### ISSUE TITLE
Talisman of Repair in alchemical chest/bag isn't repairing anything.

### ISSUE THREAD

**Issue by Kazekai** [sinkillerj/ProjectE#1058]
Tried both vanilla and modded tools, including tools I know previously worked (the saw from forge multipart for example) and nothing is helping. I even looked in the config to see if it was disabled by default and couldn't find an option.

Running version PE1.9.3h

**Comment by williewillus** [comment]
cannot reproduce, working fine for vanilla tools in both locations

**Comment by Barhandar** [comment]
Diamond Saw isn't working for me either (no repair in normal inventory), but modded regular tools got repaired just fine. I guess it doesn't recognize some things and a list of said things is necessary.

**Comment by Kazekai** [comment]
It used to repair TConstruct tools as well as carpenter's tools and chisel 2 tools but now it doesn't. I mostly only care about repairing the latter 2 though.

**Comment by Barhandar** [comment]
>I mostly only care about repairing the latter 2 though.

Are you attached to them being damageable? Either have an option to disable damage to tools altogether.

**Comment by MaPePeR** [comment]
Chisel was specifically disabled because it caused the tool to bug out and duplicate items. 

I can't remember it repairing thinkers tools...

**Comment by Kazekai** [comment]
Well it seems to repair the hammer but it doesn't repair the magical crops things which is a shame because they lose their EMC value when damaged.

**Comment by williewillus** [comment]
it repairs any item that is overridden to return true for canrepair.
In other words, if you can craft it with itself in the 2x2 grid to repair it, probably a good shot that the talisman can do it

**Comment by shobu9** [comment]
ok i managed to reproduce it, on server at least. Sometimes the Talisman will not detect anything to repair it could be a mod conflict. Anyway ill provide more details on irc.

**Comment by williewillus** [comment]
Could you write it here as well, so i can see
I can't visit irc much rn :p

**Comment by Kazekai** [comment]
I don't visit IRC either so that would be helpful to note in here.

**Comment by shobu9** [comment]
@williewillus  Its seems to be a sync issue ... its something ive noticed a lot with the lastest version of forge too.... also it will not accept certain mod items, ill try to do the code to fix it...
Let me about 2 days

**Comment by williewillus** [comment]
I don't need code fixing something I can't reproduce, I need steps to reproduce first .-.

**Comment by shobu9** [comment]
@williewillus Needs the steps then ?

**Comment by MaPePeR** [comment]
@shobu9 yes

**Comment by Kazekai** [comment]
So it turns out the chalks from witchery no longer repair either and I know for a fact those used to.

**Comment by williewillus** [comment]
We have changed nothing with how this thing works for ages (if ever). That means they stopped returning true for vanilla's "can we repair this in a 2x2 crafting grid" lookup.

**Comment by Eond** [comment]
Encountered the bug on our private server. Items (Industrial craft 2 wrench and vanilla tools tested) repair fine inside player inventory (with EMC drain) and inside the alchemical chest, but inside the alchemical bag it does not work.
Using TCR Reborn from Technicpack.net on a privately owned server.

**Comment by williewillus** [comment]
remove chisel or update PE
