### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by Speiger** [sinkillerj/ProjectE#1060]
Project E has his own EMC generation but it does not handle all possible stuff.
Now the thing is i kind of want to make a support for Project e with my custom recipes but that does not work, because there is no handler that provides a helper function for recipes. (Note the same problem has thaumcraft too but i messaged him already about that)

So my suggestion is: Make a Crafting Recipe Support interface which you ask:
can you support this recipe. If yes give me all the items from that recipe.
Example:

public boolean canSupport(IRecipe recipe);

public List<ItemStack> getRecipeItems(IRecipe recipe)

that would allow to support this mod way easier then register Custom Values to every Block+Meta and would support also changes to all other EMC Changes you do (if you readjust all other EMC values based on what is changed)

**Comment by MaPePeR** [comment]
There is a way to do that in the latest version: https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/api/proxy/IConversionProxy.java

Its currently bugged when there is an itemid change for an item/block in a Conversion. This is going to be fixed with #1046 in the next version. 

For Thaumcraft there is https://github.com/Lilylicious/ThaumicEquivalence, which already makes heavy use of that new API Feature.

**Comment by Speiger** [comment]
I do not want to define EMC values i simply want to support that you can define EMC Values yourself easier. And for base things i can add EMC values but not for everything... (Ores is a example.)

**Comment by Carbon-Ghost** [comment]
omg speiger, what are your evil plans now...

**Comment by Speiger** [comment]
Mod Support... If you call that evil then i do not mind.
(IC2 Has always these problems with his own recipes)

**Comment by MaPePeR** [comment]
The API method you linked is NOT 'define EMC values'. It allows you to specify conversions like "2*x + 3*y turns into 5*z" - or "8 * cobblestone turns into a furnace".

**Comment by Carbon-Ghost** [comment]
Still evil plans, gonna call an exorcist  ( Grag ) .

**Comment by Speiger** [comment]
well ill rather wait for the other implementation because its less work and also saves 1 extra Iteration of the Recipe List... (Machine support is something differend)

**Comment by Speiger** [comment]
@Carbon-Ghost there a player which like to use EMC if they do cool i do not want to stop them...
Everyone else who do not like it can remove the plugin. (Even modpack makers can do that)

**Comment by Carbon-Ghost** [comment]
So you want to keep the items but not EMC ? ... Erm, I.. I am right ?

**Comment by Speiger** [comment]
No i help the Mod to generate EMC for IC2 Items too if people install that mod but i do not decide what i adding and what not...

**Comment by Carbon-Ghost** [comment]
oh kk ^-^''

**Comment by Speiger** [comment]
@MaPePeR @sinkillerj to make a easy suggestion to you guys
https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/emc/mappers/CraftingMapper.java#L130

Merge this interface to theAPI and let the Crafting mapper when he gets inited load from the API class all possible mappers. That should not take very long and also is easy to solve. Also you can easy allow people to register their custom Crafting handlers without taking all recipes they have in a sepeate list...

**Comment by pupnewfster** [comment]
Closing this as I have made significant improvements to allow adding custom mappers, easier (1.14). And to even more improvements in 1.15, towards making it easier to add mappers for custom recipe types. Examples can be seen here: https://github.com/mekanism/Mekanism/tree/1.15x/src/main/java/mekanism/common/integration/projecte (more so in the mappers sub package)
