### ISSUE TITLE
mob heads have no EMC by default

### ISSUE THREAD

**Issue by escman1999** [sinkillerj/ProjectE#1062]
title says it all

**Comment by shobu9** [comment]
I feel this could get really abusive especially with mods that allows to use certain heads to make items with more emc this could be an infinite loop.

**Comment by escman1999** [comment]
maybe they could be worth 1 EMC?

**Comment by shobu9** [comment]
@escman1999 its not that , certain mods allow to use heads to transform it to something better , having emc would break things... also you could just /set emc () for your pack.

**Comment by MaPePeR** [comment]
I'm not sure you can actually use setEMC properly, because heads are separated by NBT - and we don't really support different emc values for different nbt tags.

**Comment by escman1999** [comment]
i know, but it kinda bugs me that every vanilla item has an EMC value by default besides the heads.. even the nether star has a value

**Comment by shobu9** [comment]
@MaPePeR You can which is fine

**Comment by shobu9** [comment]
@escman1999 yeah but its cheaper to double wither skeleton heads then the nether star.
And @MaPePeR is rigth if you set one mob head emc they will have that one emc vaue for every single one of them.

**Comment by williewillus** [comment]
We actually should probably add values for these because they're now obtainable in 1.8+

**Comment by shobu9** [comment]
Yeah but that doesn't fix the current 1.7.10 problem. Maybe we should change how head register ?
So we can set emc for different type of heads.
But at the same time that may cause issues with other mods...

**Comment by shobu9** [comment]
Ok nvm i just tried it doesn't work XD

**Comment by pupnewfster** [comment]
Most mob heads now have an EMC value by default in 1.15
