### ISSUE TITLE
MK2 Condenser breaks when consuming slot contents with EMC > MAX_INT

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#1065]

**Comment by kenzierocks** [comment]
Test case: Make sure you have Extra Utilities, get x64 Octuple Compressed Cobblestone, stick the whole  stack in the Mk2 Condenser.

**Comment by kenzierocks** [comment]
Just tested this: It does not happen with the regular condenser, so it must be related to the Mk2.

**Comment by pupnewfster** [comment]
I think this can be closed, given from what I can tell it is no longer even possible to put items that don't have an EMC value inside of condensers. (And items with EMC values greater than MAX_LONG count as if they don't have an EMC value when queried.
