### ISSUE TITLE
Setable EMC buy/sell values

### ISSUE THREAD

**Issue by bookerthegeek** [sinkillerj/ProjectE#1072]
Related to https://github.com/sinkillerj/ProjectE/issues/784

Would it be able to have a config option that will set the buy/sell to be off from each other for every item? An example for this would be:
 - Stone gives you one EMC but cost two to make. 
 - Either could be set on/off or a whole integer. i.e. 2x or 3x

**Comment by sinkillerj** [comment]
Sell values will be based on a fixed covalence loss ratio.
