### ISSUE TITLE
DM/RM pick ability deadlock crash - Possible fix

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1075]
Ok, so I recently had an issue of the DM/RM pick causing a deadlock on my server, and I think blub's solution works (currently testing this myself)

https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/utils/WorldHelper.java#L538-L544

Move line 543 and 544 into the "if (PlayerHelper.hasBreakPermission" bracket above. That should hopefully fix it, at least it did for me and my deadlock issue. 

Mods that caused it - Nether Ores
No protection in the area, fresh server and world.

I'll update this if the issue returns, or if this wasn't the full cause.

**Comment by williewillus** [comment]
@MaPePeR I got to look at this, and I think moving the recursive call into the if will work (see my commit)

But I don't think numSized++ is supposed to go into the if statement as well. If that happens, it'd just keep searching and searching until it finds an unprotected area and mines that. Right? Keeping it after the recursion also makes no sense, so I moved it above the if block. That way the search area won't weirdly expand depending on permissions.

**Comment by MaPePeR** [comment]
The numMined does not really make sense, wherever you put it, because the numbers of blocks mined from a deeper recursion call are not added to the number of blocks mined in the current recursion call.

**Comment by Tencao** [comment]
Just like to add, server has been running 12 hours without issue after this fix

**Comment by williewillus** [comment]
Fix merged into master and in next release (if you've had more problems after it, let us know)
