### ISSUE TITLE
Custom emc on vanilla items not working?

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#1077]
@MaPePeR 
Was trying to test 1065, but couldn't set the value of vanilla items to 1 billion, didn't work with 1 million either.

Steps:
1. Dirt or wheat seeds in hand
2. /projecte setEMC 1000000[000]
3. Relog or /projecte reloadEMC (both attempted)
4. Item retains default value

On latest master of Halloween night

**Comment by MaPePeR** [comment]
Can not reproduce. Do you have pregenerated EMC enabled?

**Comment by williewillus** [comment]
Ah of course >.>
Strange that reloadEmc it doesn't update the pregen file though
