### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by generalmonky** [sinkillerj/ProjectE#1084]
Whenever I search for something in the table or tablet it won't search. I have to scroll through everything to find what i want. I have 1.9.3h for 1.7.10

**Comment by williewillus** [comment]
mod list please
describe "it won't search" in more detail.
And curious, is it on another language than english?

**Comment by generalmonky** [comment]
![2015-11-02_20 56 18](https://cloud.githubusercontent.com/assets/15621488/10899599/64762b4c-81a4-11e5-8892-c8a5233a064d.png)
![2015-11-02_20 56 24](https://cloud.githubusercontent.com/assets/15621488/10899600/6476e01e-81a4-11e5-93ac-85747c98b184.png)
![2015-11-02_20 56 31](https://cloud.githubusercontent.com/assets/15621488/10899603/6477b034-81a4-11e5-9949-9b62ea8a61ae.png)
![2015-11-02_20 56 34](https://cloud.githubusercontent.com/assets/15621488/10899604/6477e57c-81a4-11e5-8c45-a09ddd3d500b.png)
![2015-11-02_20 56 38](https://cloud.githubusercontent.com/assets/15621488/10899602/64776200-81a4-11e5-933d-1dd237fac743.png)
![2015-11-02_20 56 51](https://cloud.githubusercontent.com/assets/15621488/10899601/64771fe8-81a4-11e5-8d6b-ec8dd59771a7.png)
![2015-11-02_20 56 56](https://cloud.githubusercontent.com/assets/15621488/10899605/647f5a46-81a4-11e5-95d0-77e8f7a3ab3d.png)
![2015-11-02_20 57 00](https://cloud.githubusercontent.com/assets/15621488/10899607/64806454-81a4-11e5-9f77-8970c36e92d6.png)
![2015-11-02_20 57 06](https://cloud.githubusercontent.com/assets/15621488/10899606/64805d56-81a4-11e5-90c7-52f0f42fc158.png)
![2015-11-02_20 57 09](https://cloud.githubusercontent.com/assets/15621488/10899608/64813b68-81a4-11e5-844e-cc9a76e686a8.png)

**Comment by generalmonky** [comment]
Those are the mods I have on.I took all of them out and left Project E and the bar worked. I'm not sure which one is stopping me from using the search bar in the table/tablet though.

**Comment by MaPePeR** [comment]
Are there any exceptions on the console when you try to search something?
Do you have NEI/Waila installed?

**Comment by generalmonky** [comment]
Yes. I have both NEI and WAILA.

**Comment by generalmonky** [comment]
The problem is NEI. Is there any way to fix that?

**Comment by generalmonky** [comment]
anyone????

**Comment by MaPePeR** [comment]
> Are there any exceptions on the console when you try to search something?

**Comment by generalmonky** [comment]
What do you mean? It doesn't matter if i type on the NEI search bar or the table's search bar, nothing in the table comes up.

**Comment by williewillus** [comment]
In your logs, do big red scary looking error messages come up when you type in the bar.

**Comment by generalmonky** [comment]
There are no red erroe messages when i do that.

**Comment by generalmonky** [comment]
*clears throat*

**Comment by williewillus** [comment]
So this happens with just PE and NEI alone?

**Comment by shobu9** [comment]
@williewillus No, NotEnoughItems and Projecte work fine together with any lastest version. 1.8 or 1.7.10

**Comment by generalmonky** [comment]
I have a bunch of mods but ProjectE and NEI are the only ones that require a search bar. And it doesnt work with the new update.

**Comment by williewillus** [comment]
Redir #1137
