### ISSUE TITLE
Crash when opening Transmutation Tablet/Table

### ISSUE THREAD

**Issue by CaptainJala** [sinkillerj/ProjectE#1086]
Whenever I try to open the Transmutation Table/Tablet I get this crash message, but the game doesn't officially 'crash', but instead just kicks me from the game saying "A fatal error has occurred, this connection is terminated". http://pastebin.com/9ya0Mt2S

**Comment by sinkillerj** [comment]
Could you provide a mods list from your main log? Seams like you may have a outdated NEI version, or that part of the API has changed, but without the mod list from the log I have no way of knowing for sure.

**Comment by CaptainJala** [comment]
Main log? Like a crash log? Because there  is none, as it doesn't crash the game

**Comment by Tencao** [comment]
I have a feeling this may be linked to a bag issue I had earlier with a player. To put short, check the ID's in the players knowledge folder in their player.dat with an nbt editor. Check all the id's to see if any doesn't exist on the server. If, after you've removed them all, the error still occurs, try and upload the players.dat somewhere so we can check if it's something not saving properly, or something messing with project e.

**Comment by CaptainJala** [comment]
I'll be honest I'm not very good at coding, or looking through code for that matter. Do you want me to upload the players.dat file so you can look over it?

**Comment by CaptainJala** [comment]
Oh, since I couldn't get an official crash log, I decided to screenshot my mods list. NEI and ChickenCore are both the recommended version for 1.7.10.

**Comment by CaptainJala** [comment]
Any update? I'm trying all I can think of and I want to use the transmutation table

**Comment by CaptainJala** [comment]
Okay! I have found the solution to the problem, I have updated NEI and ChickenCore (to the latest instead of recommended) and also updated WAILA to the latest. This seems to have fixed the problem and I am happily using the Transmutation Table!

**Comment by Morgen-stern** [comment]
I am getting the same problem in SB3
