### ISSUE TITLE
Feature request - Remove non-existant items from alch bags

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1087]
To clarify by what I mean by the title. Lets say I add buildcraft, and I put a quarry in the alch bag with an id of 525. Somehow, that ID got changed, or removed, but the id is still saved and stored inside the alch bag. Everytime the user joins, it will try to load that id, realize it doesn't exist, and kick the client. The only current way around this is to manually open the player data with an nbt editor and manually delete the item. I know forge automatically removes items that doesn't exist, but it doesn't seem the alch bags do yet. Also, just incase it doesn't, this feature would also be nice for the transmute table.

**Comment by williewillus** [comment]
hmm, not sure how this works.
For the bag at least, we defer to vanilla's ItemStack.loadItemStackFromNBT() method, which is the same as what the vanilla chest does.
Does the server crash when that happens or just the client?

**Comment by Tencao** [comment]
Only the client will crash, with a "fatal error has occurred" message.

**Comment by williewillus** [comment]
Is there a stacktrace on the client?

**Comment by Tencao** [comment]
From what I could tell from the client logs at the time, I don't believe so. I've already manually fixed it by removing the mismatch id from alch bags, and was able to login fine.

**Comment by Tencao** [comment]
You can probably force this bug by simply creating or renaming one of the items in the alch bag to an id that doesn't exist in game (pref server)

**Comment by shobu9** [comment]
@williewillus Can't you do an inventory check in the bags and reload items ?

**Comment by williewillus** [comment]
I load items the exact same way vanilla does, so if there's an invalid id it just returns a null stack. Not sure what's happening here and I haven't had time to explicitly check

**Comment by williewillus** [comment]
I don't think this is valid, vanilla methods automatically wipe out any items that have been removed and I use vanilla's methods
