### ISSUE TITLE
Issues with buckets filled with Biomes o' Plenty fluids

### ISSUE THREAD

**Issue by zauberparacelsus** [sinkillerj/ProjectE#1088]
I attempted to run the setEMC command on a bucket filled with the poison fluid from Biomes o' Plenty.  After running the reloadEMC command, I found two issues.

1) It seemed to assign the EMC value to all of the fluid buckets from Biomes o' Plenty (poison, blood, honey)
2) In the transmutation tablet, none of the fluid buckets appear.  Instead, what appears is an empty bucket named "item.bucket.name".
3) As implied by the above, you cannot duplicate Biomes o' Plenty fluid buckets through the transmutation tablet.  Attempting to duplicate them with the Energy Condenser results in the "item.bucket.name" item being produced instead.

**Comment by MaPePeR** [comment]
add the buckets to the nbt whitelist. This will result in all buckets having the same value, but you should be able to transmute them.

This is a limitation with the current system, that it cannot have different emc values for items with different nbt tags.
