### ISSUE TITLE
Item textures misrendering

### ISSUE THREAD

**Issue by Kyxxu** [sinkillerj/ProjectE#1090]
I have been running ProjectE 1.9.3h-2 on forge build #1448 and some of the items' (vanilla or ProjectE) textures are random image segments or just blank (clear).  This happens with or without other mods installed. Deleting the entire .minecraft folder and reinstalling minecraft and forge has no affect on the issue. I have tried using all stable ProjectE builds for 1.7.10 and other forge versions, but they all produce the same problem.

**Comment by sinkillerj** [comment]
This sounds like an issue with your graphic drivers, or one caused by using a graphical mod such as Optifine. We do not modify anything that has to do with vanilla texture rendering.

**Comment by Kyxxu** [comment]
Thank you. I figured it had something to do with my computer's specific software since no one else had reported a problem like this, but I had wanted to be sure.

**Comment by williewillus** [comment]
Is this on a mac? I saw an issue on the MinecraftForge issue tracker a few months back stating that random textures would be applied to item textures.
This is a graphics driver issue i think

**Comment by Kyxxu** [comment]
Yes, this is on a Mac. I have fixed the problem now, it was a conflict between the graphics drivers and forge as you said. I simply disabled the forge splash screen in minecraft/config/splash.properties and it worked fine.
