### ISSUE TITLE
UTF-16 encoding zh_CN lang file doesnt work in game.

### ISSUE THREAD

**Issue by Joccob** [sinkillerj/ProjectE#1092]
The original issue as shown in issue #1006  is the game crash with Chinese manual translation , and  I just try the newest 1.9.3h version. The game does not crash but it seems like the lang file does not loaded at all...all the items of ProjectE include the book are in English. Not sure what happens...

**Comment by williewillus** [comment]
@Lilylicious ?

**Comment by williewillus** [comment]
poke @Lilylicious

**Comment by Alexismachina** [comment]
willie you need to poke her on irc for that to happen.

**Comment by Joccob** [comment]
Outdated issue
