### ISSUE TITLE
Repair Talisman crash

### ISSUE THREAD

**Issue by RealCloudCraft** [sinkillerj/ProjectE#1094]
In the latest version of ProjectE for 1.7.10 there is an issue with mod compatablity with chisel(Specifically the 1.7.10 port of the original chisel mod). This happens because Chisel2 and the original Chisel port have the same modid so ProjectE tries to call a function from Chisel2 that isn't in the Chisel port.

**Comment by sinkillerj** [comment]
There is no real solution to this problem, and by attempting to fix it we caused problems with Chisel2. Disable chisel in your ProjectE config.

**Comment by RealCloudCraft** [comment]
about disabling it. there is no option to disable that in the config.

**Comment by williewillus** [comment]
@MaPePeR I thought we fixed this 0.o

**Comment by sinkillerj** [comment]
@williewillus The fix was causing issues with Chisel detection. 

@RealCloudCraft Start the game once without chisel, because of the crash the config may not be fully generated.

**Comment by MaPePeR** [comment]
@williewillus this was fixed in the emc calculation part, but not the repair talisman, I guess. 

I remember that I wrote a blacklist for that thing some time ago. That would probably be the better fix for the talisman than using Chisel classes.
