### ISSUE TITLE
[NBSP] in the EMC of items

### ISSUE THREAD

**Issue by joelou1** [sinkillerj/ProjectE#1096]
This sounds slightly rediculous, but it so happens that I see NBSP (A character used for Spaces) when EMC reach above 1000

EX: 8[NBSP]192

I find this annoying, but liveable as not a major bug. Any way to fix that for the futur Modpack I'm making? Do I need to enter EMC manually? I think I need a bit of guidance.

Thanks for help.
![nbspbug](https://cloud.githubusercontent.com/assets/1740156/11216119/8e9ef150-8d17-11e5-9601-bffe3287aaff.png)

EDIT: I forgot to mention that this did not occured on a certain Modpack I've played recently because the [NBSP] has been replaced by Comas [,] As shown in this picture.
![nbspbug2](https://cloud.githubusercontent.com/assets/1740156/11218013/2970f986-8d21-11e5-8479-79f448b7bbd0.png)

EDIT2: Using the version "ProjectE-1.7.10-PE1.9.3h"

**Comment by Carbon-Ghost** [comment]
For some reasons, I saw a lot of YTbers have it but I never had this problem...

**Comment by MaPePeR** [comment]
I think this one depends on the localisation of your Operating System/Java.

**Comment by iHeartZigg** [comment]
This issue was fixed for me when i installed a different language on my PC.

**Comment by joelou1** [comment]
[I think this one depends on the localisation of your Operating System/Java.]
Localised into C: and the .technic folder into my J:
You think it could be related? I've been on a server with ProjectE and this situation does NOT happen. This is why I think it's internal...

[This issue was fixed for me when i installed a different language on my PC.
Although i don't recall when or which language it was.]
Well I guess I could try, but I have both French and English installed on my computer. It used to do that even in the early builds of the original mod.

**Comment by MaPePeR** [comment]
@joelou1 with "localisation" i mean: language

**Comment by joelou1** [comment]
@MaPePeR Then MY localisation is English! According to what you showed me I should see Comas.
Also, that still doesn't change that from a modpack to another, I see it and the other not. (Look at first post, it has been edited with another picture for info) The top one being MY modpack(Tested alone without other mods), the second one being Tekkit Reborn. This is why I can't think being a problem from my end.

**Comment by williewillus** [comment]
Our mod doesn't act any differently depending on what modpack its put into.
There's probably a strange interaction issue going on, but you make it sound like the bug is just, like, right *there* and we're choosing not to fix it. Rest assured that's not the case.

**Comment by MaPePeR** [comment]
@joelou1 Do you start your pack and Tekkit Reborn with the same launcher?

I was not saying its your fault. I'm saying that its a bug that occurs in weird circumstances i have not yet figured out. Bugs that have not been figured out cannot be fixed.

**Comment by joelou1** [comment]
@MaPePeR Yes, both are started from Technic Launcher.

**Comment by sinkillerj** [comment]
This weekend I'll try to remember to take a look at the code for our tooltips, see if there is a better way we can insert the separator that is more locale independent.

**Comment by williewillus** [comment]
We use `String.format("%,d", emc)`

**Comment by sinkillerj** [comment]
@williewillus That is likely the issue here then, if I remember correctly there is a way to insert a generic "separator" instead of hardcoding a ",", perhaps in EnumChatFormatting?

**Comment by joelou1** [comment]
I'll keep an eye for an update according to what I've read? I'm glad some action will be taken, but I hope I'm not making you guys working too hard for such a small detail.

**Comment by joelou1** [comment]
Alright, time for an Edit!

After much look within my language files and stuff, I've discoved I was WRONG! My computer's language and keyboard is indeed english. It does seem like my localisation however, was french Canada!. I've changed it to english US for the time being because it actually causes issues with Minecraft Story mode aswell... But I'd still like to point out that it should be a proper space rather than [NBSP]. Keep me fed on the situation.

**Comment by sinkillerj** [comment]
I may make a config for a alternate spacer, or no spacer at all. That is of course after I've look into how other modders got around this issue, which is actually a vanilla limitation.

**Comment by joelou1** [comment]
Alrighty, keep me fed!

**Comment by williewillus** [comment]
vanilla bug with pending fix in forge

https://github.com/MinecraftForge/MinecraftForge/issues/3521
