### ISSUE TITLE
[Resonant Rise] (1.7.10) Pulling out items results in a different item being given

### ISSUE THREAD

**Issue by dfiel** [sinkillerj/ProjectE#1097]
When searching for an item, and trying to select an item, it will put a different item in my inventory.

For example, trying to pull an Xp Drain from OpenBlocks, gives me a Steam Producer (IC2 Steam) from Power Converters. They do not have remotely similar EMC values, nor Item IDs.

Attached is a .gif of the bug.
[![https://gyazo.com/0bc69c53ef933cf9a8b7c2d7de54007c](https://i.gyazo.com/0bc69c53ef933cf9a8b7c2d7de54007c.gif)](https://gyazo.com/0bc69c53ef933cf9a8b7c2d7de54007c)

Any fix for this? This has happened over the course of multiple versions, if my memory serves me correctly.

**Comment by dfiel** [comment]
After doing some more testing, It appears that this doesn't happen in Single Player, only on a server that I run on my local LAN for me and my brother.

**Comment by sinkillerj** [comment]
You will need to manually update ProjectE in the pack in order to fix this issue, no support is provided for Resonant Rise at this time.
