### ISSUE TITLE
ProjectE Logspam

### ISSUE THREAD

**Issue by Trunks9809** [sinkillerj/ProjectE#1099]
Hi there,

Noticing a lot of messages from ProjectE in the server logs for the Vaygrims Chance test server. We're running ProjectE-1.7.10-PE1.9.3h, and getting the following message repeatedly, several times a second:
[Server thread/DEBUG] [ProjectE/]: Clearing offline data cache in preparation to load online data

Full log:
https://gist.github.com/Trunks9809/4111206b3ebb2e0ce239

**Comment by williewillus** [comment]
Probably fakeplayers triggering that, it should only happen when a player logs in (or switches dimensions, due to how that works).

Though I'm interested what kind of mod is making a ton of fakeplayers every second

**Comment by Vaygrim** [comment]
I've got some experts telling me that mods like Forestry use them in their Multifarm. At present we've got wall to wall MFR Harvesters working overtime on various crop mods. We've also got Farming Stations from Ender IO and Ender IO Addons dotted about the server.
