### ISSUE TITLE
Possible mod incompatibility with Et Futurum

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1101]
So, a user of mine recently decided to put some armor on an et futurum armor stand, and when removing the armor or right clicking the stand, it caused a gl crash. Now, the reason I bring this here, is weirdly, after removing the armor from the transmute tablet, they were able to remove it without crashing. I've contacted the dev of Et Futurum already regarding this issue, and he doesn't see anything directly linking to his mod, so I thought on an off chance, it could be something here, specifically something weird going on with the knowledge dat that's causing the issue. 

I'll paste the issue below, but if this has nothing to do with project e, feel free to close it, I'm just posting it here since the solution to it breaking was directly involving project e's knowledge dat.

http://pastebin.com/uhYwg48T

**Comment by shobu9** [comment]
ehhhh... huh... well that's strange...

**Comment by shobu9** [comment]
ArrayIndexOutOfBoundsException ... wat.

**Comment by shobu9** [comment]
You have an id too high in your config.

**Comment by Tencao** [comment]
Ok, after looking into the situation more, I can confirm that this isn't project e related, and was a coincidence, so closing.
