### ISSUE TITLE
Feature Request - EMC Builder's Bag

### ISSUE THREAD

**Issue by Ian-Luminus** [sinkillerj/ProjectE#1102]
I'm currently trying to build the framework of a rather large base, (90x90 blocks for the floor alone, to start) using EMC to create the blocks themselves. But I'm having to run back and forth from a storage medium to where I'm building.

I get the feeling this would be better suited to the add-ons I keep reading about, but I'm not sure where that's being worked on, so I figured I'd post it here and be nudged to where it belongs - is there any way of adding some kind of bag with a single slot (EMC target, like the top-left slot of the Condenser) that keeps a stack of whatever's in that slot in the player's inventory (using the stored EMC of the Transmutation Tablet)?

**Comment by MaPePeR** [comment]
I think you are looking for the Mercurial Eye Feature, which is already implemented(?).
It can create blocks in the world from emc in your inventory, i think.

**Comment by williewillus** [comment]
Yes, you want the mercurial eye. That being said its behavior is kinda crappy (it was pretty crappy in EE2 too). If I have time over the break I'll look at reworking it

**Comment by shobu9** [comment]
@williewillus Can i try to re-write it ? lol

**Comment by williewillus** [comment]
sure but if the code isn't clean I'm gonna rip it apart lol

**Comment by shobu9** [comment]
XD fine.

**Comment by Ian-Luminus** [comment]
I know this has been closed, but I did try the Mercurial Eye. Didn't work with the block I'm using, only seems to accept vanilla blocks with EMC values. In my specific case, I'm trying to use Large Obsidian Brick from MineFactory Reloaded, which comes with a pre-calculated EMC value of 32.

**Comment by williewillus** [comment]
hm, it should work for every block with emc.
