### ISSUE TITLE
Project e step-assist, glide and fly conflicting

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1103]
Ok, so this is three issues in one, as I asked on irc, but it was suggested to also make a ticket. 

So, the first issue is with the step assist. Players find this annoying sometimes, as it works for ops without armor, and sometimes, just normal players in general regardless of armor. If possible, some additional checks may need to be in place, as well as a toggle option.

The second issue is with the Gem glide. Players have frequently complained about it, as some like it, some dont, and the biggest one is it messed with flying in general. I don't want to see this removed, but a toggle option would solve this.

Third is, related to the second, sometimes the Gem armor flying conflicts heavily with the swift wolf rendering gale flying, sometimes fighting each other and canceling each other out, until usually the player drops the ring and picks it back up. This may need some additional checks to make sure only one is active at the time, pref the gem armor overriding the ring, as thats usually the more expensive version.

**Comment by Carbon-Ghost** [comment]
@Gliding the thing is it's not smooth enough, you can't turn properly, pretty sure if you could control it more smoothly it would be better, already requested that feature but seems like due to more important bugs, they don't have time to implement it :/

**Comment by williewillus** [comment]
It's because of what I chose to accelerate by. It's basically an unbounded quadratic increase in speed right now. I need to change it to something logarithmic/cap it at a certain speed.

**Comment by williewillus** [comment]
just need time to play around with formulas. After exams for uni end (a week from next tuesday) I'll have lots of free time :)

**Comment by Carbon-Ghost** [comment]
Kk, good luck btw ;)

Why the hell did you used quadratics functions xD

**Comment by williewillus** [comment]
I multiplied the player's speed by 1.1 or something like that each tick lol, so actually more like exponential xD http://www.wolframalpha.com/input/?i=a%28n%29+%3D+1.1a%28n-1%29

**Comment by Tencao** [comment]
I know from experience with the glide, if you go extremely high up, and glide down, eventually you'll disconnect or break the server, one of the two.

**Comment by Carbon-Ghost** [comment]
why ? Calculation errors ? Aether had a nice gliding code though iirc..

**Comment by williewillus** [comment]
No you just go so fast the server nopes out

**Comment by Carbon-Ghost** [comment]
Can't you just have a constant falling, and a way to be able to move in the x and z axis at the same speed and friction as if you we're walking =
