### ISSUE TITLE
Intended?

### ISSUE THREAD

**Issue by cpaxe97** [sinkillerj/ProjectE#1105]
I wanted to make a EMC Sugarcane farm with the Goddess Band, but it takes the whole thing.  Is this intended? and anyway to make it work like EE2?

**Comment by williewillus** [comment]
What do you mean "takes the whole thing"?
The conventional way was to place it on a pedestal and let it do its thing
If you're talking about harvesting, it should leave the lowest sugarcane untouched so if that doesn't happen it's a bug.

**Comment by cpaxe97** [comment]
Yeah, it's not leaving the lowest sugarcane untouched, I'm not sure why this is.

**Comment by williewillus** [comment]
it's a bug, then. thanks for the report!
Just so I know, what version of PE is this?

**Comment by cpaxe97** [comment]
If I remember it was the recent version off Curse.

**Comment by cpaxe97** [comment]
Also, is it happening to you? just wondering if it's me.

**Comment by shobu9** [comment]
@cpaxe97 i cannot reproduce it , perhaps you can tell us the version number ?

**Comment by Carbon-Ghost** [comment]
I am pretty sure I already reported that one in an "issue bundle" XD It btw doesn't replant plants either..

**Comment by williewillus** [comment]
It never did

**Comment by Alexismachina** [comment]
Why are we talking in an issue that ended a month ago ?

**Comment by williewillus** [comment]
I'm not sure either
