### ISSUE TITLE
Update bug

### ISSUE THREAD

**Issue by NInjaZKIng** [sinkillerj/ProjectE#1108]
when I do the update all my "knowledge" on the transmutation table disappears

**Comment by williewillus** [comment]
which version did you update from and which did you update to?
Need more details whenever you have these kinds of problems

**Comment by NInjaZKIng** [comment]
1.1.0 but it was the agora I could already solve I did the update to 1.4 then to 1.7 and now to the latest version and no bug is ( PS : I am ussando the translator google I am Brazilian , sorry for English errors)

**Comment by sinkillerj** [comment]
Please ensure that you run this version first then properly save the game: http://minecraft.curseforge.com/projects/projecte/files/2256913

Once you have saved with that version you can update to the latest.

**Comment by NInjaZKIng** [comment]
i update my modpack thanks for helping
