### ISSUE TITLE
ProjectE Fuels have no emc

### ISSUE THREAD

**Issue by Happygfish** [sinkillerj/ProjectE#1110]
Im not sure if this is supposed to happen but all the fuels for projectE lie aeternalis and alchemical coal have no emc value so my energy collectors will condense a piece of coal but instead of going all the way and turning that coal into an aeternalis fuel block, it stops at glowstone.

**Comment by williewillus** [comment]
Have you made changes to emc values? Added mods that add or remove recipes, change projecte, or other?

What ProjectE version?

**Comment by Happygfish** [comment]
version 1,7.10-PE1.4.5 We did not alter anything, all we did was update the natural magic server to the most recent version. We did load the world in offline mode though

**Comment by williewillus** [comment]
That version is extremely (4-6 months) old. The latest version is 1.9.4.

I don't remember if we had any issues with the fuel mapper back then (I don't think so). But if that's the case and you haven't made any changes, delete the ProjectE folder in your config folder and let it regenerate, then see what happens

**Comment by sinkillerj** [comment]
The pack may also have included custom EMC values to begin with that removed these for balance, deleting the config folder as wille suggests will revert everything to stock values.

**Comment by Happygfish** [comment]
Just delete it? how does it comeback?

**Comment by MaPePeR** [comment]
it will regenerate with default values. 

if you don't want to delete it - rename it, so you can restore it easily

**Comment by Happygfish** [comment]
okay thanks
