### ISSUE TITLE
PE1.1.1 MCv1.8 - Can't add custom emc through hand.?

### ISSUE THREAD

**Issue by koalalord9999** [sinkillerj/ProjectE#1112]
https://youtu.be/rAIAgQco_B0
Video shows the issue.
I'm not really sure what the problem was, I used TAB to auto fill (at the end, still didn't work)

**Comment by MaPePeR** [comment]
You would need to provide the log that is generated when executing the command. But i think this is a duplicate of #1089 
There is a fix, but i think it has not yet been released.

**Comment by sinkillerj** [comment]
Known issue that will be fixed in the next version.
