### ISSUE TITLE
Dupe: Unlearn not consuming

### ISSUE THREAD

**Issue by djoveryde** [sinkillerj/ProjectE#1114]
Transmutation tables and tablets have the unlearn box. However when removing the item it is not consumed and you get infinite emc from it. Can this be fixed please?

**Comment by williewillus** [comment]
PE version? 
Also, just for info, what item was it and do you have nei installed?

**Comment by djoveryde** [comment]
Place item, click unlearn and shift-click item.

**Comment by djoveryde** [comment]
Latest version I believe (it's tekkit Legends modpack. This is a video of someone actually doing it and showing you how on my server. https://youtu.be/f68lq3tOkG0

**Comment by djoveryde** [comment]
Also yes nei is installed

**Comment by djoveryde** [comment]
PE1.9.3h

**Comment by williewillus** [comment]
Already fixed in #1107 ( @sinkillerj pull pls :p)
