### ISSUE TITLE
Dupe glitch with BluePower Block Breakers

### ISSUE THREAD

**Issue by Robotia** [sinkillerj/ProjectE#1119]
The glitch is as follows:
1. Player opens the inventory of an alchemical chest, condenser, or other ProjectE inventory
2. A modded item (i.e. BlockBreaker from BluePower) destroys the condenser/alchemical chest.
3. The inventory is not closed. The items inside drop but the inventory remains open and doesn't actually close.

Hence items are duplicated.

**Comment by Robotia** [comment]
WOOPS fixed in commit https://github.com/sinkillerj/ProjectE/commit/f5968e570104dfbb8765b5deb9d338c57be63e3e#diff-6e6f6df96979d7e1f3a6393e241341c8

**Comment by sinkillerj** [comment]
Please ensure that you are using the latest version from CurseForge, we are unable to provide support for self compiled builds: http://minecraft.curseforge.com/projects/projecte/files/2268263

**Comment by Robotia** [comment]
@sinkillerj I tested with the latest official builds of ProjectE and BluePower and found that the dupe glitch does not work. **However**, the GUI for any alchemical chest based block does not close once its block is broken. Players who put blocks in after the block has been broken and close the GUI will lose those items.

**Comment by Robotia** [comment]
Seems I was mistaken again...the dupe glitch occurs in 1.9.4 but only in multiplayer instances.

**Comment by williewillus** [comment]
Wait so does it happen or not in the very latest version?
SP or MP?

**Comment by Robotia** [comment]
It does not happen anymore, sorry I keep going back and forth. The problem
is as I mentioned earlier, the GUI does not close, confusing the player (or
duper).

**Comment by williewillus** [comment]
Ok, thanks
