### ISSUE TITLE
1.8 values

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#1121]
New stuff missing proper values.
Quick throw in from irc

\<nmdchiri\> Haha, okay I see. :) For raw mutton and raw rabbit, I assigned them the same values as other raw meats (32 if I recall correctly)
\<nmdchiri\> For the "rare drop" rabbit's foot i assigned it the same value as an iron ingot, since the latter is also a rare drop from zombies.
\<nmdchiri\> As for other items I couldn't get decided since giving a wither skull a low value would get really unbalanced. So maybe a really high EMC value? I'm not sure. 
\<nmdchiri\> Sponge is also kind of a weird one, since it's a boss mob drop! But to be fair, wearing a dark matter armor it's fairly easy to kill them... :/
\<nmdchiri\> Oh and Rabbit's hide, since 4 hides make one leather I just used (leather EMC)/4
\<nmdchiri\> Oh, and also, milk bucket was missing its EMC value for some reason. I just used the old EE2 value (bucket of water+1)
\<nmdchiri\> Those are the only ones I thought about in my little private server
\<nmdchiri\> Thanks for the hard work on the mod, by the way! It works amazingly well!

**Comment by koalalord9999** [comment]
I think wither skeleton skulls should cost 3x less then a nether star cause you need 3 for a star.

**Comment by sinkillerj** [comment]
I dont feel that skulls should have EMC values period unless defined by a recipe or player. Sponge wise I vote 32, its not really useful enough to be considered valuable. I fine with leather/4 as rabbit hide. Milk has special mapping conditions due to being a fluid, Blub may speak further on this.

**Comment by MaPePeR** [comment]
Skulls can not have emc due to technical reasons. 
I will try to look into milk.

**Comment by MaPePeR** [comment]
Milk missing EMC should be fixed when @williewillus merges the fluid-conversion stuff from master. 
Milk never had emc without MFR before, because milk is not an actual fluid when that mod is not present.

**Comment by shobu9** [comment]
Grrr, i still have mixed feelings about this. But anyway we will or get yelled at to add skull emc or players will add emc themselves as alsmost everypack do.

**Comment by sinkillerj** [comment]
Skulls in vanilla are intended as rare trophies, beyond wither skulls they also generally have no use, and the mods that do add a use add enchantments to increase the drop rate to insane levels. If you need skulls and cant get them you are doing it wrong.

**Comment by koalalord9999** [comment]
I wouldn't even want them to have a value to spawn them, I just want to dump my entire inventory into the table, and use it as a everything stored AE system. lol

**Comment by M3DK1T** [comment]
I agree. I think giving skulls EMC would be havoc on a multiplayer server. No matter the amount, it's too easy to mine up to enough EMC to produce an Omega Klein star. Being able to create 2-4 wither bosses with 25 mil EMC seems a little OP.
