### ISSUE TITLE
Can't use custom config to set EMC values of any item with an ore dictionary name starting with "dust"

### ISSUE THREAD

**Issue by solidDoWant** [sinkillerj/ProjectE#1123]
The setEMC command works, but not the config file. Can't set the item's value in the config file with either the OD name or the item's name. Tested against Mekanism, IC2, and a couple of other mods.

**Comment by MaPePeR** [comment]
Disable the blacklisting of dust and ore in the mapping.cfg. It's in the ore dictionary mapper configuration group.

**Comment by solidDoWant** [comment]
Well that was stupid of me. Thanks!
