### ISSUE TITLE
Tick lag with watch of flowing time

### ISSUE THREAD

**Issue by Zaflis** [sinkillerj/ProjectE#1124]
I was recently profiling my MC 1.7.10 server with Opis, and this 1 thing shined out from the rest. Friend had put up roughly 20 activated pedestals with watch of flowing time around a MK3 EMC condenser formation. For sure it made EMC alot faster, literally octuble compressed cobblestone was done quickly. 

Anyway the lag: "/cofh tps" was showing 40ms per tick. When i disabled the pedestals, it dropped to about 10ms. If it were to go above 50ms, tps rate would start to drop down from 20. But also leaving no rest for the CPU core.

So is there anything that can be done to improve it? I realize it's a bit cheaty item, but if put on server scale, if there were more people doing that, it would completely crush the tick rate.

edit: Also there's very little info about this item. I heard the effect shouldn't be stacking for one? Also what range does it affect, 9x9x9?

**Comment by Speiger** [comment]
@Zaflis well the watches of flowing time do not stack each other simply because that would cause a infinite loops crash so that is not a thing, and for your TPS thing.
You should expect that TPS mean time goes high simply because it simulates extra TileEntity Ticks which is mainly causes a longer TPS Mean time... Its the same if you have like 200 solar panels placed...

**Comment by williewillus** [comment]
I don't really know how to help you, that is the purpose of this item - to simulate extra time. Processing that isn't free, you're asking the server to do in 1 second what it took 20+ seconds to do. There are configs to disable this item if you don't want the wrong people abusing it.

They also don't stack, as Spieger said, to avoid infinite loops.

**Comment by MaPePeR** [comment]
using the phrase "they don't stack" might be misleading, because there can be 2 watches affecting the same area of effect. so from the perspective of the tile being accelerated the effect of the 2 watches "stack up".

**Comment by sinkillerj** [comment]
Cant fix wont fix.
