### ISSUE TITLE
Watch of flowing time should speed up all tiles at once

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#1125]
At the moment the watch picks a single tile entity and gives it X extra ticks. Then it selects the next tile and gives that entity more ticks. 

I think it should go through all the tiles once and give every tile entity a single extra ticks, so the tiles that interact with adjacent tiles can work together better. And repeat that X times.

(That would also be more close to how 'time acceleration' "really" works)

So: Swap [those 2 loops](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/items/TimeWatch.java#L201-L209)

**Comment by koalalord9999** [comment]
Uhh, I don't think that's how it works. I've set up progressive automation milk farm. Milks fast, item pipes take out super fast, condenser is faster, emc overall is faster
