### ISSUE TITLE
Is the Watch of flowing time supposed to be this overpowered?

### ISSUE THREAD

**Issue by koalalord9999** [sinkillerj/ProjectE#1127]
In under 14 hours of gameplay, I was able to produce this much Octuple Compressed Cobblestone
![image](http://i.imgur.com/qQSOfvf.jpg)

The setup is this: ![image](http://i.imgur.com/zIQcUpw.jpg)

Thats equal to: 17,864,389,215 EMC.
(I've moved all of it into one chest for less picture spam)

I dunno, but I think machines should only be able to affected by 1 Pedestal'd Watch, instead of finitely many

**Comment by williewillus** [comment]
It's already less than what it used to be with EE2....

**Comment by koalalord9999** [comment]
Wow lol, they were and still are stupid OP xD
