### ISSUE TITLE
ColoredLights Maven Down for Chisel Dependency

### ISSUE THREAD

**Issue by Robotia** [sinkillerj/ProjectE#1131]
The Gradle build task cannot be run because the maven repository for http://coloredlightscore.us.to/maven/chisel-2-dev/ is down.

**Comment by solidDoWant** [comment]
Can confirm, I am having the same issue. For now just download the chisel 2 dev or deob the main file and adjust your build path.

**Comment by Robotia** [comment]
How would you go about doing that? Sorry I'm inexperienced with gradle.

**Comment by MaPePeR** [comment]
We needed to update that chisel dependency anyway... we are using an ancient version.

**Comment by Robotia** [comment]
Could we just put chisel on Maven central?

**Comment by MaPePeR** [comment]
We don't release chisel. We just need to find out whats their current maven repository is. I bet they still have one. The problem is finding the right one.

**Comment by Robotia** [comment]
They have a Jenkins on port 8080 but I couldn't find a reference to another
Maven there though.

**Comment by MaPePeR** [comment]
This does fix it:

```patch
@@ -41,22 +41,22 @@ repositories {
         name 'CB Repo'
         url "http://chickenbones.net/maven/"
     }
     maven {
         name 'Chisel'
-        url "http://coloredlightscore.us.to/maven/chisel-2-dev/"
+        url "http://maven.tterrag.com/"
     }
     ivy {
         name "MineTweaker3"
         artifactPattern "http://minetweaker3.powerofbytes.com/download/[module]-([classifier]-)[revision].[ext]"
     }
 }
  
 dependencies {
     testCompile group: 'junit', name: 'junit', version:'4.11'
 
-    compile "com.cricketcraft.chisel:Chisel2:2.3.10.100:api"
+    compile "com.cricketcraft.chisel:Chisel2:2.5.0.2:api"
 	
     compile "codechicken:CodeChickenCore:1.7.10-1.0.4.29:dev"
     compile "codechicken:CodeChickenLib:1.7.10-1.1.1.110:dev"
     compile "codechicken:NotEnoughItems:1.7.10-1.0.4.83:dev"
 


```

**Comment by Robotia** [comment]
I guess this should be closed now...going to go ahead and do that. Thanks @MaPePeR !
