### ISSUE TITLE
[REQUEST] Differnet Transmutation table/tablet between different worlds

### ISSUE THREAD

**Issue by xXJamieXx** [sinkillerj/ProjectE#1132]
Hi sinkillerj,

Im on the tekkit legends modpack and I have a public server. I was wondering if there was already or if you could add a feature to have your emc and memory in your transmutation table be different? If you could do that and then push it to the Technic Team it would be amazing for them to update the modpack with it.

(BTW you came on my server once m8 :P)
Thanks,

xXJamie_Xx

**Comment by williewillus** [comment]
What do you mean different between different worlds?

Also this is a very very fundamental saving change so it most like ly will be no :/

**Comment by xXJamieXx** [comment]
Basically, have the contents of the table and emc be a different save so they cant take items from one world to another in a transmutation table. for example take red matter from the survival world to the skyblock world

**Comment by sinkillerj** [comment]
This information is already saved to the player, so if a new world uses a new player file it should already be split. That being said our focus is on protection support following forge standards, you are on your own when it comes to other bukkit hackery.
