### ISSUE TITLE
A few issues with the ProjectE-1.8-PE1.1.1 version

### ISSUE THREAD

**Issue by Zeperus** [sinkillerj/ProjectE#1135]
If you have a Ring of Arcana set to Harvest mode and a Void Ring active your inventory you get 2 Bugs to be mentioned:
Cacti fly at you and damage you (get stuck mid-Air).
![2016-01-07_20 59 20](https://cloud.githubusercontent.com/assets/10312583/12181338/de1ecf42-b581-11e5-9692-12ee00340feb.png)
If you fly over a flower it gets duplicated an Infinite amount of times, and the more flowers you add the more this happens (Also applies to mushrooms).
![2016-01-07_20 50 06](https://cloud.githubusercontent.com/assets/10312583/12181299/b25b4764-b581-11e5-854a-00feaa6d0d65.png)
Just a little heads up ;)
Otherwise gj at recreating one of my favorite mods ever :D

**Comment by williewillus** [comment]
Cannot reproduce

**Comment by williewillus** [comment]
No response, comment on how to reproduce and I will reopen
