### ISSUE TITLE
Red Katar AoE Kills instantly

### ISSUE THREAD

**Issue by TheTwitch** [sinkillerj/ProjectE#1138]
The Red Katar and Red Matter Sword ignore armor entirely, even gem armor, and even the quantum armor from Industrial craft classic, which enables invulnerability when wearing the full suit.

**Comment by williewillus** [comment]
>thatsthepoint.gif

**Comment by TheTwitch** [comment]
I am the server owner. I changed the value all the way down to 2 before I posted this. It dealt 1 heart of damage, completely ignoring gem armor.

**Comment by TheTwitch** [comment]
And as a side note, the red matter sword does not have a change damage option.

**Comment by williewillus** [comment]
It's intended to be armor-bypassing damage.

**Comment by TheTwitch** [comment]
Is there a way to disable this feature?

**Comment by williewillus** [comment]
For the katar, set damage to 0, for sword, not yet.

I'm surprised the quantum armor doesn't block armor bypassing damage
It isn't something hacky like Draconic Evolution would do (setting health directly, etc.), so it should be able to be blocked.
