### ISSUE TITLE
[Bug] Swiftwolf Ring stops working on dimension change

### ISSUE THREAD

**Issue by Robotia** [sinkillerj/ProjectE#1141]
When flying around with the swiftwolf ring, if you switch to a different dimension (i.e. teleport to a home in the Nether), it will stop working from time to time. Trying to activate any of the functions does not change it. You have to drop it and pick it back up again, then it seems to reset itself and start working again. No one has reported this issue with the ring of arcana, only the swiftwolf.

**Comment by sinkillerj** [comment]
Are you currently using the latest version? I thought we had knocked this bug out.

**Comment by Robotia** [comment]
@sinkillerj No, but I did cannibalize some files from 1.9.4 and put them into 1.9.3h, thought I had got all the fixes. I will see if I can find the commit and if I missed it.

**Comment by Robotia** [comment]
@sinkillerj This issue was mentioned earlier (#1067 and #1044) but no solution was found. Is there something I missed?

**Comment by blackdragonIV** [comment]
i noticed that the void ring TP function also does not work when crossing dimension , specifically with mystcraft.

**Comment by xvolution** [comment]
I just encountered this bug when teleporting to the Nether using a Mystcraft Linking Book. ProjectE is up to date [v1.10.0 for 1.7.10]

**Comment by williewillus** [comment]
folding to #1152
