### ISSUE TITLE
Lava bucket no EMC value 1.7.10 V:1.9.4

### ISSUE THREAD

**Issue by TheKoopaAlpaca** [sinkillerj/ProjectE#1142]
I made an inifinte energy sorce with an energy collector and energy condensor en a thirdparty mod and it al worked fine but when a some time. It just randomly stopt and I didn't understad why it stoped. but then i saw that the lava buckets didn't had a emc value.

I hope you can fix it because it's one of my favorite mods.

Greetings from TheKoopaAlpaca

**Comment by MaPePeR** [comment]
We did not change any EMC values in your instance.

Maybe your server operator removed the value?
