### ISSUE TITLE
Black Hole Band attracting other DM pedestal items

### ISSUE THREAD

**Issue by LucasRo7** [sinkillerj/ProjectE#1144]
If you place two pedestals close to each other, put a black hole band in one of them and another item in the second pedestal, when you activate the black hole band pedestal, it pulls the item from the other pedestal, it does not pickup the item. [Image(Dropbox)](https://www.dropbox.com/s/g5udg8g4k25ez8v/2016-01-15_13.38.42.png?dl=0&preview=2016-01-15_13.38.42.png)

**Comment by williewillus** [comment]
hehe partially my fault, will fix soon (tm)

**Comment by MaPePeR** [comment]
How the hell did that happen :smile:

**Comment by williewillus** [comment]
In 1.7 the item is rendered by the TESR, in 1.8 the pedestal is a JSON model so I just had the TE spawn a ghost item on top :p

**Comment by williewillus** [comment]
Fixed in dev
