### ISSUE TITLE
Holding Philosophers Stone makes my game crash, had to use invedit to fix the issue but now i can't use the Philosophers Stone what so ever because it continues to crash my game

### ISSUE THREAD

**Issue by ItsMichael02** [sinkillerj/ProjectE#1146]
Here's my crash report:
[crash-2016-01-16_11.45.53-client.txt](https://github.com/sinkillerj/ProjectE/files/92723/crash-2016-01-16_11.45.53-client.txt)

**Comment by williewillus** [comment]
Update forge, you are using an ancient build

**Comment by ItsMichael02** [comment]
Thank you, I installed the new version of Forge and it all works perfectly.
