### ISSUE TITLE
automatic stepup

### ISSUE THREAD

**Issue by Sailren** [sinkillerj/ProjectE#1148]
is it possible to disable the automatic stepup? when i create a new world and run towards some blocks the player automatically goes up one block and that is really annoying in some cases

**Comment by Alexismachina** [comment]
Disable the boots ability.

**Comment by Carbon-Ghost** [comment]
shift f I think

**Comment by ErrorCraftLP** [comment]
Just F, Shift+F toggles the Night Vision.

**Comment by Sailren** [comment]
it was on by default, when u create a new world, boom
