### ISSUE TITLE
Buggy Leaf Transmutation

### ISSUE THREAD

**Issue by sinkillerj** [sinkillerj/ProjectE#1149]
In 1.8.9-PE1.1.3 leaf transmutation is a bit buggy, you can only target certain leaves in the group, and the transmutation often fails to do anything.

**Comment by williewillus** [comment]
This is due to the leaves having different blockstates. This issue is present in 1.7 too, just less noticeably ;) 
I'll take a look later

**Comment by sinkillerj** [comment]
<3
