### ISSUE TITLE
outdated chisel api prevents entering a world (1.8.9)

### ISSUE THREAD

**Issue by Avalonzo** [sinkillerj/ProjectE#1150]
Hello just as the title suggests when I add your latest 1.8.9 version I'm unable to enter an existing world or create a new world it gets as far as building terrain message then goes back to the title screen no crash.

I have the latest log via pastebin - http://pastebin.com/QV5jfc2t

**Comment by williewillus** [comment]
pastebin the fml log, not the vanilla one, which provides almost no information. Did it only happen when you updated PE? Or did you update other mods?

**Comment by Avalonzo** [comment]
Sorry for not relying straight away pastebin wasn't liking the size of the log so I had to copy/paste into wordpad and save it as a txt so I could upload it. I tried multiple time with fresh launches to no avail but when i disables the ProjectE jar it all works again also ProjectE is the last mod I put in my mod folder today.

[latest-fml-log.txt](https://github.com/sinkillerj/ProjectE/files/93609/latest-fml-log.txt)

**Comment by tgtiburon** [comment]
I have the same problem as Avalonzo.  It also does not crash Java, it does not render.  You have to I have to task kill Java to get the Minecraft crash screen to show up.  Below is the relevant pastebin.  It appears to be related to chisel?

http://pastebin.com/Vgud2gCz

**Comment by Avalonzo** [comment]
It's definitely Chisel I just disabled the Chisel.jar and it fires up 1st time without any problem also tried re-enabling it and same problem again.

**Comment by alexbegt** [comment]
@williewillus, please update the Chisel2Mapper, to use the new packages: https://github.com/Chisel-Team/Chisel/tree/1.8/dev/src/main/java/team/chisel/api/carving and, com/cricketcraft/chisel/api/carving/ is the old package.

**Comment by SDUBZ** [comment]
had same issue as the ses other guys

**Comment by MaPePeR** [comment]
Hotfix is to disable the chisel mapper in the mapping.cfg, I guess.

**Comment by MaPePeR** [comment]
So looking at the logs and [this line](https://github.com/sinkillerj/ProjectE/blob/MC18/src/main/java/moze_intel/projecte/emc/EMCMapper.java#L98) i'm really wondering why the exception is not catched.

@sinkillerj are you sure you fetched/pulled the MC1.8 branch from github before building the 1.8.9 release? Because that try catch should catch that exception...

**Comment by williewillus** [comment]
It's an Error, it escapes the catch block

**Comment by MaPePeR** [comment]
Just noticed its not the `ClassNotFoundException`. but `NoClassDefFoundError`.

**Comment by williewillus** [comment]
I don't have much time right now, if someone could go into the 1.8 workspace and replace the old chisel maven with the new one (tterag's) and makes sure it'll compile and map correctly that'd be great :p

**Comment by sinkillerj** [comment]
I intended to do such today, but that didn't work out so well, curse reality.

**Comment by SDUBZ** [comment]
dont need chisel not chisel2 mapper?

**Comment by MaPePeR** [comment]
without the chisel2mapper you will not get EMC values for chisel. 
But chisel works without it.
When you keep it enabled your game will not start, so chisel blocks not having an emc value is your least concern, i guess.

**Comment by SDUBZ** [comment]
yeah i dont think people care if they have no emc on chisel stuff until you guys get it figured out :D

**Comment by SDUBZ** [comment]
so any idea if you guys are gonna push a update with the chiselmapping disabled

**Comment by MaPePeR** [comment]
I don't think so. you can just disable it yourself in the mapping.cfg and the 1.8.9 release is still very early, so bugs are to be expected.

**Comment by MaPePeR** [comment]
If that file does not exist or is empty, because the game crashed before the file was written: Write this into the `mapping.cfg` file inside the `ProjectE`-config directory:

```
enabledmappers {
    B:Chisel2Mapper=false
}
```

**Comment by LlubNek** [comment]
Here's another log for this error:
http://pastebin.com/kchf5Gyc

You're using the API from:
http://minecraft.curseforge.com/projects/chisel-2?gameCategorySlug=mc-mods&projectID=225236
https://github.com/Chisel-2/Chisel-2
... which hasn't updated to 1.8.9.

You should be using the API from:
http://minecraft.curseforge.com/projects/chisel?gameCategorySlug=mc-mods&projectID=235279
https://github.com/Chisel-Team/Chisel
... which is available for 1.7.10 and 1.8.9.

You can find the API code here:
https://github.com/Chisel-Team/Chisel/tree/1.8/dev/src/main/java/team/chisel/api

**Comment by MaPePeR** [comment]
The last time I checked there was no chisel release in the maven that contains the api. Did that change?

**Comment by williewillus** [comment]
Removed for now, if someone feels like getting it back working submit a pr to 1.8 branch

**Comment by Drullkus** [comment]
[API? API. Go wild.](http://ci.tterrag.com/job/Chisel/branch/1.8%252Fdev/)

**Comment by williewillus** [comment]
Is there a maven?

**Comment by MaPePeR** [comment]
http://maven.tterrag.com

**Comment by Drullkus** [comment]
This goes into your list of mavens in repositories { }

 maven {
 name 'Chisel Repo'
 url "http://maven.tterrag.com/"
 }

This goes into your dependencies { }

 compile "team.chisel:Chisel:${chisel_version}:api"

**Comment by williewillus** [comment]
uh which one do I use here? http://maven.tterrag.com/team/chisel/Chisel/
The version on your jenkins isn't visible

**Comment by williewillus** [comment]
Heh, nvm, I got it.

**Comment by MaPePeR** [comment]
`0.0.2.7` is not present in the maven repository.

**Comment by williewillus** [comment]
I might just add the api to src/api/java >.>

**Comment by Drullkus** [comment]
treat accidentally did something with the Maven, he just fixed it. [Tada](http://maven.tterrag.com/team/chisel/Chisel/MC1.8.9-0.0.2.11/)
