### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ezekiel-Zephyr** [sinkillerj/ProjectE#1151]
I'm playing the DW20 pack and added ProjectE. I pulled an iron wand (thaumcraft)  from the table and shift clicked with it still being held by the invisible cursor and then the game crashed and will crash each time I load into the world.

**Comment by Alexismachina** [comment]
@Ezekiel-Zephyr Logs would be EXTREMELY helpful.

**Comment by Ezekiel-Zephyr** [comment]
http://pastebin.com/k8hdRKh4 - Client
http://pastebin.com/2T6nPD0n - Server
Unsure which would be needed.

**Comment by williewillus** [comment]
This is a crash with tainted magic

**Comment by Ezekiel-Zephyr** [comment]
Thanks
