### ISSUE TITLE
Ring of Arcana in bauble slot needs to be re-equipped after dimension transition

### ISSUE THREAD

**Issue by Stalkstalks** [sinkillerj/ProjectE#1152]
I was using a Ring of Arcana as a flight tool. It can be equipped in a bauble ring slot, and works there - however, after going to the nether (or back from the nether) it stopped allowing flight until I opened the bauble interface, pulled it from the slot, and put it back.

**Comment by Robotia** [comment]
@Stalkstalks same problem with the SWRG in #1141

**Comment by cookta2012** [comment]
This is a Baubles issue, it even occurs in the 1.7.10 version of baubles

**Comment by williewillus** [comment]
Can't reproduce

**Comment by pupnewfster** [comment]
Closing this as we no longer use baubles (it isn't updated to 1.15), and I don't believe this is an issue anymore with the Curios integration.
