### ISSUE TITLE
[Request] Klein Stars with Function!

### ISSUE THREAD

**Issue by remsat10** [sinkillerj/ProjectE#1153]
I understand this mod is a revamp of Equivalent Energistics so what I'm about to suggest should be considered an add on but if you're interested, please keep reading.

So as I get into mid-late game, I find myself mining with the Void Ring. It compresses all my junk which is great but what I end up doing is putting my end product into my transmutation table/tablet for raw EMC. 

Here is what I propose, the Klein Star and the Void Ring/Gem of Eternal Density to be combined to make a Klein Star capable of sucking items up into itself for raw EMC. 

Thanks for your consideration

**Comment by sinkillerj** [comment]
This may be considered once the official addon is in development, but will not be implemented at this time.

**Comment by remsat10** [comment]
Wow a official add on?! I look forward to it :)
