### ISSUE TITLE
Thaumcraft Capatibility

### ISSUE THREAD

**Issue by M3DK1T** [sinkillerj/ProjectE#1156]
Currently playing the 1.1.3 version of Project E in 1.8.9 alongside Thaumcraft, and immediately noticed some serious balance issues between both mods.

1. Thaumium, Wands, and Shards, shouldn't have EMC. Being able to create stacks of these items with ease ruins the difficulty of obtaining them in Thaumcraft, and eliminates the purpose of farming them.

2. Certain decorative blocks are used a lot in Thaumcraft as recipe requirements. It would be wise to increase the values of these specific items just a bit, to make them a bit fairer in worth. 

Specifically; Chiseled Stone Bricks, Smooth Stone, Stone Bricks, Chicken Feather, Ender pearl, Reed, Paper, Ink Sac, Leather, Books.

3. A majority of items do not have any EMC value. This creates a large amount of issues, mostly with mining but also with general conversion. A key fix would be to simply give some items EMC value. Namely, Amber, Quicksilver, Silverwood Logs, planks. Greatwood Logs, planks. I recommend that Silverwood logs be on par with Lapis blocks, Great wood logs being on par with iron bars. Quicksilver would be around Gold. Amber would be around Emerald. 

I don't expect the Project E team to actually work on making the two mods more progressively compatible, but I am interested in trying to make some kind of filler or addon mod to make similar changes to improve the experience with both mods. I was even thinking of creating a version of EMC that is specific to Essentia & Magical items, alongside Dark & Red matter smelteries.

**Comment by MaPePeR** [comment]
You realize, that the EMC system is highly configurable by the player/pack author to solve these issues?

**Comment by williewillus** [comment]
PE is not responsible for any values besides vanilla, and a couple oredict ones. It is up to the player and midpacker to create the experience they desire by setting values of their choice.
