### ISSUE TITLE
[ProjectE-1.8.9-PE1.1.3] Dark Matter Pedestal acting weird with chests near of it

### ISSUE THREAD

**Issue by JAWSAWN** [sinkillerj/ProjectE#1158]
Steps to reproduce:
1- Place chests on ground 
2- Place a dark matter pedestal
3- Place an item in the pedestal

Pedestal steals chest's texture and spins it with the item inside.

**Comment by williewillus** [comment]
Wat

Screenshot? Mod list/Forge version?

**Comment by JAWSAWN** [comment]
mod list: https://gyazo.com/5bf06cd8dc657774e48127f738eaebf0
forge: forge-1.8.9-11.15.0.1710

https://gyazo.com/a7529dce301e13e0103abe8c6ebbdd8b
tried to capture a gif but didn't work :S 
so it spins with the item. And if you don't look at the pedestal the chests disappear and appear normally.

**Comment by sinkillerj** [comment]
Could you try without Chameleon? My gut is telling me this may be a issue with it.

**Comment by JAWSAWN** [comment]
Pretty sure tried it before I installed the chameleon

**Comment by mille449** [comment]
I'm seeing the same issue without chameleon.  Dark matter pedestal with life stone on it.  It looks like there is a missing pop on gl state.
