### ISSUE TITLE
Search function in Transmutation table not working

### ISSUE THREAD

**Issue by cedced** [sinkillerj/ProjectE#1162]
Hi when trying to search i get nothing, no errors in the server console or anything.
Here is the list of mods i have, if you could help me pin point what is causing the error i would be forever grateful. Thanks

![b2d54fa41bbf9f81d831b7fb6f17ff77](https://cloud.githubusercontent.com/assets/1075441/12601775/c10f3dfc-c471-11e5-85e0-a0bacd96c22e.png)

![122a895b24d01d5f79386286f68600d4](https://cloud.githubusercontent.com/assets/1075441/12601776/c4be4dc6-c471-11e5-8d5a-978035d5f8a4.png)

**Comment by MaPePeR** [comment]
Are there errors on the client console?

**Comment by cedced** [comment]
`[B#347] 2016/01/27 17:51:50 [INFO]  [17:51:50] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiIngameMenu
[B#347] 2016/01/27 17:52:42 [INFO]  [17:52:42] [Client thread/INFO] [inventorytweaks]: moze_intel.projecte.gameObjs.gui.GUITransmutation
[B#347] 2016/01/27 17:52:42 [INFO]  [17:52:42] [Client thread/INFO] [inventorytweaks]: moze_intel.projecte.gameObjs.container.TransmutationContainer
[B#347] 2016/01/27 17:53:09 [INFO]  [17:53:09] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiIngameMenu
[B#347] 2016/01/27 17:53:50 [INFO]  [17:53:50] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiInventory
[B#347] 2016/01/27 17:53:50 [INFO]  [17:53:50] [Client thread/INFO] [inventorytweaks]: net.minecraft.inventory.ContainerPlayer
[B#347] 2016/01/27 17:55:06 [INFO]  [17:55:06] [Client thread/INFO] [inventorytweaks]: moze_intel.projecte.gameObjs.gui.GUITransmutation
[B#347] 2016/01/27 17:55:06 [INFO]  [17:55:06] [Client thread/INFO] [inventorytweaks]: moze_intel.projecte.gameObjs.container.TransmutationContainer
[B#347] 2016/01/27 17:55:31 [INFO]  [17:55:31] [Client thread/INFO] [inventorytweaks]: moze_intel.projecte.gameObjs.gui.GUITransmutation
[B#347] 2016/01/27 17:55:31 [INFO]  [17:55:31] [Client thread/INFO] [inventorytweaks]: moze_intel.projecte.gameObjs.container.TransmutationContainer
[B#347] 2016/01/27 17:55:36 [INFO]  [17:55:36] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiIngameMenu`

**Comment by cedced** [comment]
Not sure if this helps. Thanks

**Comment by Robotia** [comment]
Instead of copying and pasting, *please* create a pastebin [here](http://pastebin.com).

**Comment by cedced** [comment]
> Instead of copying and pasting, please create a pastebin here and share the link...

Updated it thanks.

**Comment by sinkillerj** [comment]
The log you have posted is only partial, and does not include anything relevant.

**Comment by cedced** [comment]
> The log you have posted is only partial, and does not include anything relevant.

Those were the only logs for the time i was searching, but if you want full logs, here you go.

http://pastebin.com/kPsaYs38

**Comment by williewillus** [comment]
NEI being weird.

Remake if it happens in 1.10+
