### ISSUE TITLE
Achievement ID's are too generic

### ISSUE THREAD

**Issue by sinkillerj** [sinkillerj/ProjectE#1166]
Largely opening this as a reminder to myself, unless someone beats me to the fix. Our achievement ID's are arguably too generic, this can, and as of now has caused conflicts with other mods. The solution in my mind is to affix pe to the beginning.

**Comment by williewillus** [comment]
Changing it will wipe everyone's PE achievements, afaik

**Comment by MaPePeR** [comment]
who cares?

**Comment by Robotia** [comment]
...Maybe you could create a map of old to new achievements.

**Comment by williewillus** [comment]
doesn't work that way @Robotia

**Comment by Robotia** [comment]
Yeah I wouldn't know, never made a mod myself :stuck_out_tongue: 
Achievements aren't all that important to people anyways

**Comment by williewillus** [comment]
i'm on the backwards compat side (if we're going to break something because "no one cares", why do we even have it in the first place?), so meh. whichever mod is newer or smaller in the conflict should change or someone else can do it :P

**Comment by sinkillerj** [comment]
I can always take a vote, but I really dont think anyone goes after all of our achievements, if anything they are more of a guide.

**Comment by williewillus** [comment]
pulling into 1.9
