### ISSUE TITLE
Void Ring blacklist reset

### ISSUE THREAD

**Issue by Ezekiel-Zephyr** [sinkillerj/ProjectE#1167]
Right clicking the ring opens the window where items can be black/white listed though items remain when added changing from blacklist to white list won't stay and will revert to blacklist once the window is closed again.

**Comment by sinkillerj** [comment]
In order to assist you with this issue we will need to know the version of ProjectE that you are currently using.

**Comment by Ezekiel-Zephyr** [comment]
1.9.5
