### ISSUE TITLE
Crash when switching language

### ISSUE THREAD

**Issue by 3TUSK** [sinkillerj/ProjectE#1171]
Trying to switching Minecraft language from English (US) to simplified Chinese （简体中文－中国），then the game will freeze for a while and crash. I have tried removed ProjectE and after that I succeeded switching language.
[The crash-report is here](http://pastebin.com/MDAikdSV), using Forge 10.13.4.1614 and ProjectE 1.7.10-PE1.9.5.
I have no idea why there is a stackoverflow when I switch language, but according to the crash-report I think I need to report here first. 
If anyone need more information please let me know. Also if I make any mistakes please point it out.

**Comment by ShieLian** [comment]
The same thing happened in minecraft 1.8.9 with ProjectE-1.8.9-PE1.1.3.
The log is mostly the same as 3TUSK pasted, StackOverflow at moze_intel.projecte.manual.ManualFontRenderer.wrapFormStringToWidth(ManualFontRenderer.java:42)

**Comment by sinkillerj** [comment]
Ill see if I can find a solution as @Lilylicious is a tad away at the moment. She changed the file format to work around issues like this, but this caused many clients to not load the chinese language file at all.

**Comment by ShieLian** [comment]
@sinkillerj It's caused by a space after the '!' at "恭喜你开始了新的旅程, 我的朋友! 可能你已经......." in the zh_CN.lang.
If add ch==32//space to line 40, the game will not crash again.

**Comment by 3TUSK** [comment]
[Since it's solved in latest version](https://github.com/sinkillerj/ProjectE/pull/1174), I'm gonna close this issue.

**Comment by sinkillerj** [comment]
Reopening for now as that change was only implemented in 1.8

**Comment by williewillus** [comment]
@sinkillerj you can git cherry pick that commit into 1.7

**Comment by williewillus** [comment]
I think tthis was cherry-picked

**Comment by 3TUSK** [comment]
@williewillus Someone told me that he got a very similar crash in [Skyexchange 1.1](https://minecraft.curseforge.com/projects/skyexchange). Is the fix commit cherry-picked?
