### ISSUE TITLE
Dark matter blocks are too expensive

### ISSUE THREAD

**Issue by lesliev** [sinkillerj/ProjectE#1177]
Is there a reason why dark matter blocks cost 4 dark matter and then produce only one block? The original recipe produced 4 blocks for 4 dark matter.

**Comment by sinkillerj** [comment]
Dark Matter may hold interesting properties, but it cant defy the laws of matter.

**Comment by lesliev** [comment]
I beg to differ! Dark matter swords kill multiple mobs without touching them! Dark matter armor is indestructible! Dark matter itself does not interact with electromagnetic radiation and yet accounts for most of the universe's mass! Dark matter appears to be beyond the standard model and thus can and indeed does defy the laws of ordinary matter!

**Comment by Robotia** [comment]
This conversation...XD

**Comment by lesliev** [comment]
Have you seen what happens if you fuse Dark matter with an ordinary pocket watch?
https://github.com/sinkillerj/ProjectE/wiki/Watch-of-Flowing-Time

You can control time itself! But now that I've put one of those on (you guessed it) a Dark matter pedestal next to a power flower, I no longer care how much things cost. :smile:
