### ISSUE TITLE
weird pedestal render issue 

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#1179]
![2016-02-13_01 15 07](https://cloud.githubusercontent.com/assets/7633717/13023200/65e4871c-d1ef-11e5-827e-9d3ec9c03c0b.png)

![2016-02-13_01 12 31](https://cloud.githubusercontent.com/assets/7633717/13023206/6cfac93a-d1ef-11e5-8e7a-4efecaf04f92.png)

the watch and the stone are suppose to be on the pedestal to the right, tested with PE 1.1.3 for mc 1.8.9

**Comment by sinkillerj** [comment]
Duplicate of a known issue.
