### ISSUE TITLE
Transmutation Table Dupe

### ISSUE THREAD

**Issue by DeviousCraker** [sinkillerj/ProjectE#1180]
It is possible to dupe the contents of Alchemical bags in the transmutation table. There isn't really any tricks to it, just put it in the learn slot and add emc. The resulting bag will have the same contents that were in the bag originally. 

This was done on the most recent version of Tekkit Legends.

**Comment by Robotia** [comment]
...Alchemical bags hold the same contents no matter if they are destroyed. It is a universal inventory based upon the bag color. Removing an item in one red alchemical bag for a player affects all red alchemical bags this player opens.

Thus, this is not a dupe.

(Should be closed)
