### ISSUE TITLE
Bug while playing on a server

### ISSUE THREAD

**Issue by baccabacon** [sinkillerj/ProjectE#1181]
While player on a server my transmutation table page was locked, i couldnt turn the page left only right. I don't know if it was because my player data corrupted or it's just a bug with ProjectE

**Comment by sinkillerj** [comment]
Without server logs, save files, etc, theres not much I can do to diagnose the cause of this. You would also need to specify the PE version.

**Comment by baccabacon** [comment]
It is version 1.9.5, i will try to get the server owner to make a copy of those files and see what you can do

**Comment by baccabacon** [comment]
The search bar wouldn't work also. But i know my player files were still there because i used equivalent energistics and i could see the recipes in a ME system

**Comment by baccabacon** [comment]
The owner is going to take a data log when all the players on the server log off

**Comment by williewillus** [comment]
No response, comment with followup and we will reopen
