### ISSUE TITLE
Duplication Bug PE1.9.5 [1.7.10]

### ISSUE THREAD

**Issue by Greg0ry17** [sinkillerj/ProjectE#1183]
If you taught an Alchemical Bag with Stuff (example: red matter blocks) to a Transmutation Tablet, when you get that alchemical bag from the tablet, it'll keep those items.
Well, I don't know much english, so if you didn't understand, here's the portuguese version:

Se você ensinar uma Transmutation Tablet uma Alchemical Bag com itens dentro (Exemplo: Blocos de Matéria Vermelha), se você pegar uma Alchemical Bag daquela Transmutation Tablet virá com os itens que estavam dentro da bag que você tinha ensinado a Transmutation Tablet.

Confusing? Yes. Bug? I think so.

**Comment by MaPePeR** [comment]
All the Bags of the same player with the same color share an inventory. This is intended. If you take it out of one bag it will disappear from the other.

**Comment by Greg0ry17** [comment]
Oh, I didn't noticed that.. It seemed like a really easy duplication bug. Thanks!

**Comment by Robotia** [comment]
Duplicate of closed issue #1180. You should've checked if it was already reported :confused:

**Comment by Greg0ry17** [comment]
Sorry, my bad.

**Comment by Robotia** [comment]
@Greg0ry17 It's ok! You're new to GitHub :smile:
