### ISSUE TITLE
Stop emc values for certain blocks [1.7.10] [PE1.9.5]

### ISSUE THREAD

**Issue by finnbo11** [sinkillerj/ProjectE#1184]
I have a modpack and have projecte in it (projecte is in permissions with credit) and I want people in my pack and on my server create big factories condensing objects from the raw items not crafted items (eg wood to sticks then sticks to ladder through factories) so I want to destroy certain emc values on obejets is there any way I can manual delete emc values for certain items in the config. Any help would be much appreciated!

**Comment by Robotia** [comment]
/projecte removeEmc with the item in hand

(Close this issue)

**Comment by finnbo11** [comment]
Thanks for the help!

**Comment by finnbo11** [comment]
By the way will this edit the config so it works for everyone in my modpack?

**Comment by Robotia** [comment]
Yes it will

**Comment by MaPePeR** [comment]
if you reupload the configuration files and people redownload the modpack, yes.
