### ISSUE TITLE
cant place blocks on server

### ISSUE THREAD

**Issue by 6Grim6Reaper6** [sinkillerj/ProjectE#1185]
i have a 1.8.9 server with a friend and when we try to place any of ProjectE's blocks it doesn't place the block instead it places a glitchy air block that we get stuck when try to go through it, also it consumes the item. the mod works fine in single player and other mods work on the server, items like transmutation tablet and philosophers stone work perfectly fine. please help

**Comment by williewillus** [comment]
Does this server have spawn protection or any sort of protection plugin?

**Comment by 6Grim6Reaper6** [comment]
No I have no plugins installed only a few mods I got through cure client

**Comment by Kolatra** [comment]
I'm noticing this issue as well. I added ProjectE to FTB Unstable, but I don't have any protection mods or anything. I crafted a Transmutation Table and I had the same air block problem.

**Comment by Robotia** [comment]
Are you using pure Forge?

**Comment by Kolatra** [comment]
Yes. Pure Forge 1764.

**Comment by pupnewfster** [comment]
Closing this, feel free to comment if it can be reproduced in 1.15.2
