### ISSUE TITLE
1.8.9 Crash on world load or world create (other mods present) conflict with other mod

### ISSUE THREAD

**Issue by miklander** [sinkillerj/ProjectE#1187]
Game loads fine untill it is time to load world or create new world game just dumps you back to main menu.
here is pastebin on Logs i get when i try to load the world

http://pastebin.com/fvy6Nr0M

Hopefully this helps

**Comment by miklander** [comment]
ok tested more since there was exception between Chisel and ProjectE Disabling Chisel allows the world Load So there is something funky between:
Chisel-mc1.8.9-0.0.2.6 and ProjectE-1.8.9-PE1.1.3

**Comment by MaPePeR** [comment]
Known bug.
