### ISSUE TITLE
Implement IItemHandler Capability 1.8.9

### ISSUE THREAD

**Issue by pauljoda** [sinkillerj/ProjectE#1189]
IItemHandlers have been released with Forge and are the new method of handling inventories. It is suggested you not use IInventory or ISidedInventory and instead use IItemHandler. I know this can be difficult however so if not it would be nice if you would at least implement the Capability for IItemHandler. All you have to do is say your tile has that capability, and then wrap your current IInventory using the forge provided wrapper for IItemHandlers. This will allow other mods (such as mine NeoTech) to interface with your inventories without having direct access to the ItemStacks as they should never be accessed directly. 

This is what Forge has stated to be the future for inventories and modders should update as soon as possible. They are even working on a fluid capability. 

If you need any help or have any questions, I would be glad to help. You can find me in the #neotech irc channel. As some of the first mods into 1.8.9, it is important we set the standard for what Forge expects of mods

**Comment by williewillus** [comment]
This is mostly done (in 1.9)
