### ISSUE TITLE
Problem with spectator mode

### ISSUE THREAD

**Issue by Imnuts7** [sinkillerj/ProjectE#1190]
When I switch to spectator mode from another gamemode, I fall straight through the world and die in the void. I initially thought it was Forge but I tracked the problem down to this. I am using the latest 1.8.9 version of Forge and ProjectE.

**Comment by williewillus** [comment]
Can you give me steps to reproduce?

**Comment by Imnuts7** [comment]
Switch between gamemodes using gamemode 1 and gamemode 3

**Comment by Robotia** [comment]
Wow willie is on an issue fixing marathon!
