### ISSUE TITLE
Constant Console Spam in cause to Condensers

### ISSUE THREAD

**Issue by callous4567** [sinkillerj/ProjectE#1191]
**Hello!**
I've a bug report, or some sort of issue that I have no idea how to fix. 
http://prntscr.com/a4imdh

This screenshot shows you an example; console spam. It seems to keep adding condensers, and it spams even more than Ars Magica (which also has a bug that they've acknowledged and are working on seemingly).  

**What's the problem?**
It keeps "adding" condensers, spamming the console, and I presume causing lag as the server skips ticks roughly around the time of the condenser additions. It appears to spam constantly, quite a few times per minute, and appears to cause some TPS lag. 

**How to reproduce**
Download ResonantRise 3.2.7.2 (ish)
Set up a server with ProjectE 
Run for a while, adding in Ars Magica and some other mods, including removing Chicken Chunks and using Dim. Anchors
Profit

Server files : http://backups.nodecraft.com/services/11a34a80-ba5d-48f9-8fd0-0f18ee67d77c/55f022aa-23a0-4333-afbf-75c4ee26cffe.zip (incase you need them)
Logs : https://dl.dropboxusercontent.com/u/156891738/fml-server-latest2.log

I'd appreciate any help you can offer, whether this actually is a bug or not and whether there is a fix for it. Either ways, it shouldn't be spamming that in the console/log I reckon as we aren't constantly readding the condenser.

**Comment by MaPePeR** [comment]
I think you might be using an ancient version of ProejctE there

**Comment by callous4567** [comment]
It's PE 1.9.5, the latest for 1.7.10 :_:

**Comment by sinkillerj** [comment]
RR3 is trouble as it is, and given the environment its going to be hard for us to find a cause, it could very well be another mod interfering.

**Comment by Robotia** [comment]
His log level is at debug o.o

**Comment by callous4567** [comment]
My logs are always at debug; they're the most buggy logs on earth! I've pooped out probably 4-5 bug reports to AM2, BigReactors, EnderIO, even Mekanism! I'll keep searching to find a cause to the spam; it's probably another chunk loader issue w/ Dim anchors xD

**Comment by Robotia** [comment]
Raise your log level then

**Comment by callous4567** [comment]
What do you mean, raise my log level?

**Comment by Robotia** [comment]
https://www.spigotmc.org/wiki/prevent-debug-messages-in-your-console-logs/

**Comment by callous4567** [comment]
I'm unable to get that file they specified; it's empty, and hastebin doesn't seem to want to let me save it
