### ISSUE TITLE
Add dolly support for the alchemical chest

### ISSUE THREAD

**Issue by Silly511** [sinkillerj/ProjectE#1193]
Allow JABBA's dolly to pick up alchemical chests.

**Comment by sinkillerj** [comment]
I could have sworn they worked already but ill look into this.

**Comment by Anoyomouse** [comment]
Digging on the net (tm), i stumbled on JABBA

Seems the dolly needs the alchemical chest programmed into it (see dolly at https://bitbucket.org/ProfMobius/jabba/src/4c1ccec85db33e4e43e5a68f2983d80da5b96093/src/main/java/mcp/mobius/betterbarrels/common/items/dolly/ItemBarrelMover.java?at=forge_1187&fileviewer=file-view-default)

There is also an issue on Jabba to add this support (https://bitbucket.org/ProfMobius/jabba/issues/157/add-dolly-support-for-project-e-alchemical )

Where i've asked the good question do you have to add it here, or does it have to be added there, now we wait, i think

**Comment by Silly511** [comment]
I know I made that issue, but no one was replying so I reported it here. I was pretty sure sinkillerj would not be able to do anything, but I thought he could contact ProfMobius in a way I couldn't.

**Comment by williewillus** [comment]
they need to do it
