### ISSUE TITLE
Right click not working with both pickaxes

### ISSUE THREAD

**Issue by jjdamstra** [sinkillerj/ProjectE#1195]
The right clicking to mine a vein of ore does not seem to be working. Am I missing something

**Comment by sinkillerj** [comment]
Were gonna need alot more info than this, Minecraft version, PE version, logs, etc.

**Comment by jjdamstra** [comment]
I am using minecraft version 1.8.9, ProjectE-1.8.9-PE1.1.4 and there is no logs that I know.

**Comment by popemichael** [comment]
I too am having this issue. 

Minecraft 1.8.9 using FTB Unstable - Any other logs that are needed, I'm happy to provide.

**Comment by Bersham** [comment]
Just ran into this issue. As stated, right clicking gives out a "FATAL" error in console. This does not cause a crash.

Mincraft 1.8.9
Forge 1.8.9-11.15.1.1902
ProjectE 1.1.4

[Latest Log](https://pastenib.com/v/wXWOlGVpXI36V0WSuSsx)

**Comment by Bersham** [comment]
Just tried downgrading to ProjectE 1.1.3 and it's the same thing.

**Comment by Bersham** [comment]
Happens on a fresh instance with just ProjectE. I tried downgrading Forge since I've had issues with new stuff from them, but that's not the case.

[Latest](https://pastenib.com/v/ZAFM3beYkR24H5YMvWws)

**Comment by williewillus** [comment]
should be working in 1.10+
