### ISSUE TITLE
[QUESTION] Repair pendant is ported to 1.8.9?

### ISSUE THREAD

**Issue by hron84** [sinkillerj/ProjectE#1196]
I crafted a repair pendant, but even if i have only 2 items in my inventory, a pendant and a repairable item it is not repairs it (tested with iron helmet and diamond pickaxe). Is it ported to 1.8 or do i have to do something with the pendant?

Also, I tried to put the pendant to a pedestal (in creative) but it seems like no way to do it. No right click, no sneak-click, no drop worked. 

Please help what I do wrong?

**Comment by williewillus** [comment]
you have to shift click the pedestal

**Comment by hron84** [comment]
@williewillus but it should work in inventory too?

Btw, my log beign spammed about whining NoClassDefFoundError com/cricketcraft/chisel/api/IChiselItem. As I saw, Chisel for 1.8 does not contain this class. Can it cause the pendant not works in inventory?

**Comment by williewillus** [comment]
Empty hand

**Comment by hron84** [comment]
For the pedestal? Will it work regardless of the log spam I mentioned before?

**Comment by killerjerick** [comment]
Shift right click with an empty hand to open a pedestal, otherwise just craft an alchemical bag to store both the talisman and the items that need repairing

**Comment by hron84** [comment]
@killerjerick so the pendant works only in an alchemical bag/chest now? Please let me clear on this, since I still not get a full answer for all my questions. Is this still working regardless it spamming the log with complaining about Chisel API (the log spam is only happens when I'm hold the pendant). Please, please give me answers (an "I don't know" will be enough), because I'm still not know what's happening and what I do wrong.

**Comment by killerjerick** [comment]
I'm not sure about the spamming log, yes it ONLY works in an alchemical bag and pedestal.. Sorry I couldn't be more help, I wish I could make my answers have more substance but alas I cannot, it's a simple answer and I can't add any more onto it, good luck! :)

**Comment by hron84** [comment]
Thanks for clarifying things, it helps me a lot. I was confused because the pendant previously worked in my inventory too.

Don't worry, you were helpful enough, just I was annoyed because nobody clarified me how this thing works now. And I never read this new restriction against the pendant so I definitely had no clue I do something wrong or it is changed.

I will take a look into the bag then. Do you think it will work in the alchemical chest too? I plan re-do some of my previous automation setup with this, I would be really happy if it could work.

**Comment by killerjerick** [comment]
I'm not too sure about the Alchemical chest, sorry, I'm no longer playing on a pack that has project E unfortunately (I broke economy with an OP pigman farm :P Anyway, no problem, I'm glad I could help :)

**Comment by hron84** [comment]
Alchemical chest works, pedestal not. I checked so hard, but nothing getting repaired if i put the pendant to a pedestal. Bag and chest otherwise works as expected.

**Comment by killerjerick** [comment]
Good to know, thanks for telling me :)

Have fun!

**Comment by williewillus** [comment]
I just tried it in inventory and it works.
Can I have more details (version + modlist?)

**Comment by williewillus** [comment]
Works on a pedestal too

**Comment by hron84** [comment]
@williewillus I tried in Baubles slot, in inventory and in hotbar and nothing get repaired, even if i had only two item in my whole inventory: a talisman and a damaged pick. Nothing else.

Same happened on pedestal too.

```
Aroma1997Core-1.8.9-1.0.4.1.jar
Aroma1997s-Dimensional-World-1.8.9-1.1.2.0.jar
Bagginses-1.8.9-2.1.5b.jar
BloodMagic-1.8.9-2.0.0-19.jar
Bookshelf-API-1.8.9-2.3.5.jar
buildcraft-7.2.0-pre12.jar
Chameleon-1.8.9-0.2.1.jar
Chisel-MC1.8.9-0.0.2.7.jar
craftingtweaks-mc1.8.9-3.0.52.jar
craftingtweaksaddons-mc1.8.9-3.0.8.jar
EnderCore-1.8.9-0.3.0.4-beta.jar
ezstorage-1.8.9-1.2.6.jar
Fancy Fluid Storage-1.8.9-1.4.5.7.94.jar
FastLeafDecay-1.8-1.6.jar
Furnus-1.8.9-1.7.jar
graves-1.8.9-b42-universal.jar
Hammerz-1.8.9-0.1.4.13.jar
HydCraft-1.8.9-3.1.65-universal.jar
IGW-Mod-1.8.9-1.2.4-4-universal.jar
intangible-1.8.9-0.0.25.jar
InventoryTweaks-1.60-beta-38.jar
JEIAddons_1.8.9-0.12.0.57.jar
jei_1.8.9-2.28.6.173.jar
journeymap-1.8.8-5.1.3-unlimited.jar
JustEnoughResources-1.8.9-0.4.0.jar
k4lib-1.8.9-1.0.16-universal.jar
magicclover-1.8-0.7.2.jar
magnetic-1.0.jar
MCMultiPart-1.0.7-universal.jar
MmmMmmMmmMmm-1.9b.jar
MoreFurnaces-1.5.0-MC1.8.9.jar
NeoTech-1.8.9-2.4.0a.jar
OpenComputers-MC1.8.9-1.5.22.6.jar
ProgressiveAutomation-1.8.9-1.6.35.jar
ProjectE-1.8.9-PE1.1.4.jar
Psi-beta-19.jar
RandomThings-MC1.8.9-3.6.2.jar
RoguelikeDungeons-1.8.9-1.4.5.jar
Ruins-1.8.8.jar
StorageDrawers-1.8.9-2.4.2.jar
StorageNetwork-1.8.9-1.7.3.jar
Thaumcraft-1.8.9-5.1.6.jar
ThaumicInfusion-1.8.9-4.82.jar
VeinMiner-1.8.9_0.31.4.unknown.jar
VersionChecker-1.2.5.jar
Waila-1.6.0-B3_1.8.8.jar
warpbook-1.8.9_2.0.41.jar
Wawla-1.4.7-1.8+.jar
ZyinsHUD-(1.8.8)-v.1.4.8.jar
```

**Comment by williewillus** [comment]
Fixed in next version
