### ISSUE TITLE
Possibility to turn off step-assist while in creative by default?

### ISSUE THREAD

**Issue by Collserra** [sinkillerj/ProjectE#1197]
Especially with mods like bibliocraft, step-assist can get annoying at times. It'd be really appreciated if you could add a config option, or something similar.

**Comment by MaPePeR** [comment]
I think this has been fixed in the latest version. Or the fix is only committed, but not yet released. I don't know.

**Comment by ErrorCraftLP** [comment]
c8657a16dd65ea0f65f9781b4cae5ef73d5b7afe
It's fixed, but not yet released.

**Comment by jdrox** [comment]
I find this very annoying, but I really want to use ProjectE.
Is there a way for me to build the mod with the fix?  (I don't have much coding experience though.)

**Comment by MaPePeR** [comment]
@jdrox i think @sinkillerj [announced](https://twitter.com/sinkillerj/status/735599351234482176) that he is working on an update that will be released very soon.

**Comment by jdrox** [comment]
@MaPePeR Awesome, thanks for the link.  I try to avoid Twitter whenever possible...
Can't wait!  EE2 was one of my favorite mods of all time, and a remake for 1.7.10... I never thought I'd see it.  Just got my pack set up, so I haven't tried anything yet, but it won't be long.  :)

**Comment by jdrox** [comment]
Perhaps this isn't the best place to comment, but I just wanted to say thanks to sinkillerj for the ProjectE update today.  Can't wait to try it out.  (And not step-assisting constantly! :P )
My base's exterior may or may not be fully comprised of solar flowers.  <3

**Comment by sinkillerj** [comment]
I always appreciate pictures tweeted at me if you feel so inclined, I love seeing peoples setups.
