### ISSUE TITLE
[Bug] Dark Matter Pedistal crash with repair talismen on activation

### ISSUE THREAD

**Issue by SunnyTD** [sinkillerj/ProjectE#1198]
Optifine installed

Minecraft Log: https://gist.github.com/SunnyTD/a041469c881e30aeb151
FML Log: https://gist.github.com/SunnyTD/9f8f1b15718e56ac7c80
Looks like compatibility bug with chisel, since the pedestal works without chisel installed.

**Comment by Drullkus** [comment]
FYI, #1150 is a related issue and both issues can be resolved easily.
