### ISSUE TITLE
Covalescence dust.

### ISSUE THREAD

**Issue by sapioit** [sinkillerj/ProjectE#1200]
Hi!

In ProjectE-1.7.10-PE1.9.3h and ProjectE-1.7.10-PE1.9.5 you needed to craf a diamond with a coal for a high covalescence dust and a redstone with an iron for a medium covalescence dust.
Wouldn't it be better (and more logicly) to have coal with iron for medium covalescence dust and redstone with diamond for high covalescence dust?

Have a good day!

**Comment by MaPePeR** [comment]
Coal has a bigger emc value than Redstone, I think.

**Comment by sapioit** [comment]
But you don't need to get to the lava layer to get one... you can even find it on the ground, or as a random drop...

**Comment by sinkillerj** [comment]
This wont be changed any time soon, if you dont like it minetweak the recipe in your pack.

**Comment by sapioit** [comment]
I will, but my question is why is it not like that by default? Between when I find redstone and when I find a diamond, I don't even leave the cave/mining, so why not actually make the medium covalescence dust useful by actually having it at hand when you need it?

**Comment by MaPePeR** [comment]
This is a historical thing, i think. Also its about EMC values.

You combine a standard item of the tier with a standard fuel of the tier based on emc value.

**Comment by sapioit** [comment]
I understand that, but from a player's perspective, it's off-tuned.
