### ISSUE TITLE
[Suggestion] reintroduce thunder and projectile function to the swiftwolf's rendering gale (SWRG)

### ISSUE THREAD

**Issue by nayfaan** [sinkillerj/ProjectE#1201]
I would really like to see the old functions of SWRG from EE2 to be reimplemented in this mod, 
Quote from the tekkit wiki showing how it used to work in EE2: "Right click while aiming at a mob: Fires a projectile which will launch mobs into the air. This action consumes 64 EMC from a Klein Star or 1 Redstone Dust. If it is raining, instead of shooting a projectile it will instead cause a lightning bolt to hit the area where the player is aiming. This action consumes two Glowstone Dust. If in a thunderstorm, two or three lightning bolts will be shot instead of one, with no change in EMC price."

**Comment by williewillus** [comment]
e27c8f4 :D
