### ISSUE TITLE
Left Side of Transumation Tablet Unfunctional

### ISSUE THREAD

**Issue by stephenmc608** [sinkillerj/ProjectE#1202]
Hello. The left side of the Transmutation Tablet appears to not be functional. When I put a Klein Star (With EMC) on the left side, the Tablet doesn't detect any EMC. Putting regular items also does not work, as it also doesn't detect any EMC. (However, you can still teach the Tablet new items this way)

I am using version 1.10.0 of the (1.7.10) Direwolf20 pack, with version PE1.9.5 of ProjectE.
(I apologize in advance if you are not updating 1.7.10 versions anymore, as I know some modders have moved on to newer versions.)

Below are some images of the issue.

![2016-03-13_21 26 06](https://cloud.githubusercontent.com/assets/8429816/13732940/50bc5786-e962-11e5-8e0f-d5589f6dfee0.png)
![2016-03-13_21 26 24](https://cloud.githubusercontent.com/assets/8429816/13732941/50bd69fa-e962-11e5-91ad-c0f4d5a0825c.png)

**Comment by williewillus** [comment]
Place it in the center of the right

**Comment by stephenmc608** [comment]
Ok. That allows the Tablet to use the EMC of normal items, but when I place the Klein star (With EMC) there, it drains all of the EMC from the Klein Star into the Tablet.

**Comment by williewillus** [comment]
This is the way it's been working for the life of PE. I know it's different from EE2, but it's going to stay like this for the foreseeable future. Put it in the right to drain the emc into the tablet then refill it on the left after finishing

**Comment by stephenmc608** [comment]
Alright. Thank you for taking the time to help me with this.
