### ISSUE TITLE
[Bug] ProjectE Alchemical Bag "Fatal Error has Occurred" Kick (plus possible fix)

### ISSUE THREAD

**Issue by Robotia** [sinkillerj/ProjectE#1203]
I have encountered a strange bug recently concerning Alchemical Bags.

After one of my players used JABBA Dollies to pick up all the chests in their base and stored these dollies in his alchemical bags, everything seemed fine. However, when he relogged, he would lose connection with `A fatal error has occurred, this connection has been terminated`.

I tested this myself a few minutes ago and found that there *is indeed* an error log, but it is only client-side: http://pastebin.com/CVGY4dhg

After looking through the ProjectE code for a bit, I have a hunch that the data packet size is so large it is exceeding the maximum packet size...or some similar error is occuring.

Possible solution:
in `moze_intel/projecte/playerData/AlchemicalBags.java`, change
```java
PacketHandler.sendTo(new SyncBagDataPKT(AlchBagProps.getDataFor(player).saveForPacket()), (EntityPlayerMP) player);
```
to

```java
for(int i = 0; i < 16; i++)
{
    PacketHandler.sendTo(new SyncBagDataPKT(AlchBagProps.getDataFor(player).saveForPartialPacket(i)), (EntityPlayerMP) player);
}
```

If the error was indeed caused by an oversized packet, this would solve the problem.

**Comment by williewillus** [comment]
I doubt that is why
