### ISSUE TITLE
A couple of requests

### ISSUE THREAD

**Issue by The-Silver-Kid** [sinkillerj/ProjectE#1209]
EMC ducts : to be able to transport emc
Energy collectors / Anti mater relay output to transmutation table

**Comment by williewillus** [comment]
Transmutation tables are per player so the second isn't really possible

**Comment by The-Silver-Kid** [comment]
unless you do it sort of like the mekanism teleporters where it is placed and it gets power but only the person that placed it can open its GUI

**Comment by williewillus** [comment]
the table has no info at all, the emc is stored in the player file

**Comment by sinkillerj** [comment]
If you want EMC transfer there is a japanese addon which allows that, but in a very OP and broken way. I have a plan for long distance transfer in the future which solves the problems, but that is on hold for right now as I work on my game.
