### ISSUE TITLE
Quick question about DM Pedestal and Watch of Flowing time

### ISSUE THREAD

**Issue by koalalord9999** [sinkillerj/ProjectE#1211]
I believe I'm using the latest 1.7 build of ProjectE and about 3 months ago or so, I had a EMC generator that was producing 2.7b EMC/h using the watch on a pedestal, with about a dozen more nearby. 

The question I have is this: Was this fixed so only one watch would be in effect per block and if there were multiples, nothing changed?

**Comment by williewillus** [comment]
pedestals do not accelerate each other, but multiple can accelerate the same block

**Comment by koalalord9999** [comment]
The same setup is only producing a little under twice the speed of a normal Star Flower now, maybe a diamond every 4 seconds (3 months ago - was around a stack of diamonds every few seconds)

**Comment by williewillus** [comment]
last update we flipped two for loops to make them distribute ticks more evenly between machines, maybe that might've cuased it.
No idea without further investigation
