### ISSUE TITLE
Limit on EMC Amount?

### ISSUE THREAD

**Issue by JayXsane** [sinkillerj/ProjectE#1214]
I've looked to see if anyone else is having this issue, but no one has said anything thusfar.

Basically, there is a cap on how much EMC the Table/Tablet can hold, and I was wondering if there was a way to change that to make that unlimited, or at least alter the number? I've basically capped it out, and can only have a certain amount of EMC available at any given time, so is there a way to make things easier by changing the default limited value of how much EMC you can have? (No, not setting the EMC Value of an item, but the actual collected EMC Value in the table)

**Comment by MaPePeR** [comment]
No. It's mostly a technical limitation
