### ISSUE TITLE
minetweaker

### ISSUE THREAD

**Issue by mpztilera** [sinkillerj/ProjectE#1217]
i cant add a recepie for the philosopher stone with minetweaker. i have added this: mods.avaritia.ExtremeCrafting.addShapeless(ProjectE:item.pe_philosophers_stone, [ExtraUtilities:unstableingot:2, DraconicEvolution:chaoticCore, ore:ingotBedrockium, Botania:spreader:3, usefulDNS:PStone, baublelicious:entangledRing, RandomThings:ingredient:4, AWWayofTime:transcendentBloodOrb, ore:RotaryCraft:ingotBedrock, <Mimicry:Sparr_Mimic Block>, RArm:ItemMaterials, usefulDNS:UnobtainIngot, RedstoneArsenal:material:32, ExtraUtilities:generator.64:11, ExtraUtilities:mini-soul:3, SolarExpansion:solarPanelUltimate, TardisMod:item.TardisMod.CraftingComponent, TardisMod:item.TardisMod.CraftingComponent:1, GalacticraftCore:item.meteoricIronIngot, rftools:dimensionalShardItem, Mystcraft:BlockCrystal]);

**Comment by MaPePeR** [comment]
i think you might be using the wrong item name. it might be called `ProjectE:philosophers_stone` and not `ProjectE:item.pe_philosophers_stone`. Not sure about that, and did not check, but that might be the case.

**Comment by MineProjectZ** [comment]
no. this dont works

**Comment by MaPePeR** [comment]
Don't you need `<` and `>` around these to make it work properly, too?

**Comment by pupnewfster** [comment]
This should be able to be closed as it is for an old version of minecraft
