### ISSUE TITLE
Zero Ring not disapearing when crafting Ring of Arcana

### ISSUE THREAD

**Issue by Managarmr719** [sinkillerj/ProjectE#1219]
Zero Ring is not removed from the crafting table when crafting the Ring of Arcana.
I'm using ProjectE 1.7.10-PE1.9.5.

**Comment by Managarmr719** [comment]
I'm using ProjectE 1.7.10-PE1.9.5

**Comment by williewillus** [comment]
I think that might be intended, to match EE2

**Comment by Managarmr719** [comment]
Ok, I thought it consumed the ring but if it's intended that's alright. It's been quite a while since I played EE2.
