### ISSUE TITLE
conflict SpmodAPI

### ISSUE THREAD

**Issue by SvEgiiVEteR** [sinkillerj/ProjectE#1221]
SpmodAPI Version 1.0.2.4.jar
ProjectE-1.7.10-PE1.9.5.jar
https://gist.github.com/b64f9a9dc33d4c53974359f04e2a14c2
https://gist.github.com/7e6fdf0287835ab2fa63318d1dba1bc7
create a new world and throws in the game menu
and can not get out, java hung

**Comment by sinkillerj** [comment]
My first instinct is that one of your other mods is doing something very wrong, but ill take a look later and see if I can pull a workaround.

**Comment by SvEgiiVEteR** [comment]
you think the reason is another mod? not SpmodAPI ?

**Comment by Speiger** [comment]
@SvEgiiVEteR @sinkillerj yeah its SpmodAPIs fault because its overriding the Glowstone block. Which is EMC Fuel. Simply set this config to false: "Override Glowstone"
It prevents my mod to override the glowstone.
Little funfact: It does not happen on every computer. Which is weird.
Anyway that should fix your problem. If it is still happening after that its not SpmodAPIs fault anymore because the config dissables the override to 100%

**Comment by SvEgiiVEteR** [comment]
@Speiger thanks, I will try )

**Comment by sinkillerj** [comment]
@Speiger Thanks for the insight into the issue, I'll see if I can make ProjectE more friendly towards that.

**Comment by Speiger** [comment]
@sinkillerj that has nothing todo with ProjectE. It could happen anytime to any mod. Not sure why its happening its also not happening to all modpacks. Thats simply a Computer Specific bug...

To throw it that way: I have made a modpack with Project E and that override enabled and it caused no problems. Others did run fine with it too but i had others crashing constantly with it... Its really weird...
Maybe you should throw that into your knowen bugs: that dissabling that config with that type of crash solves that problem. (If you have a page with bugs that are not easy to fix or not fixable) So people do not have to throw constantly issues at you...

**Comment by Speiger** [comment]
Little note: SpmodAPIs curse page has now a info with that special crash template to catch these problems. (If people read it) so that should prevent major bugreports if the combo will be used again.
(1.9 SpmodAPI will have that feature too so we are fine with that)
