### ISSUE TITLE
Issue with hasValue(ItemStack) API and items that use damage values

### ISSUE THREAD

**Issue by Mordenkainen** [sinkillerj/ProjectE#1222]
If you have a "multi-item" that uses damage values to represent multiple different items, the hasValue(ItemStack) API call can malfunction when the item with damage value 0 does not have an EMC value.

hasValue(ItemStack) appears to delegate to hasValue(stack.getItem()), which causes the item with damage value 0 to be checked instead of the actual item passed.

If the item passed has an EMC value, and the item with damage value 0 does not, the API call returns false.

This can easily be tested with the Thermal Foundation ingots. The item with damage 0 (Pulverized Iron Dust) has no EMC value, but other items with the same item ID but different damage values, like Copper Ingots, do have an EMC value. If you pass a stack of Copper Ingots to the API, it will return false. If you manually set an EMC value on the Pulverized Iron Dust, the API starts returning true when passed the stack of Copper Ingots.

**Comment by MaPePeR** [comment]
In which version does this happen?

**Comment by Mordenkainen** [comment]
I'm not in front of my machine right now, but I was able to recreate it with the latest 1.7.10 build from Curseforge as of last night.
