### ISSUE TITLE
Amulets don't work inside baubles slot

### ISSUE THREAD

**Issue by Managarmr719** [sinkillerj/ProjectE#1224]
Evertide and Vulcanite amulets go inside the baubles amulet slot but you can't use them.

**Comment by escman1999** [comment]
to use them, don't you need to right click or press *insert keybind here*? i think the only reason things like the talisman of repair work in the baubles slot is because they work automatically

**Comment by Managarmr719** [comment]
yes, you have to press a key for them to work but if you can put them there it would make sense for them to work and if not, they should block them from baubles slot.

**Comment by MaPePeR** [comment]
They have a passive effect that should be available from the baubles slot. (Lava walking for Vulcanite)

**Comment by Managarmr719** [comment]
Yes you're right but I think that the rest of it's abilities should still be available without having to unequip the amulet.

**Comment by sinkillerj** [comment]
Baubles for the most part provide strictly passive effects, there's simply no reason for any further keybind trickery and confusion.
