### ISSUE TITLE
Energy Collector not working properly

### ISSUE THREAD

**Issue by dekruger** [sinkillerj/ProjectE#1225]
The Energy Collector is getting stuck at Glowstone blocks and I cannot put in Glowstone blocks or any higher tiers into the collector. 

Ver. 1.7.10-PE1.9.5

**Comment by sinkillerj** [comment]
Did you remove the EMC value of Glowstone Blocks?

**Comment by dekruger** [comment]
No I did not. The higher tiers after glowstone blocks don't have EMC values, if that is correct.
