### ISSUE TITLE
Flans mod guns crash once entered a gun mod table.

### ISSUE THREAD

**Issue by iWireless** [sinkillerj/ProjectE#1228]
I realize this problem might be towards Flans but I saw another github post talking about NBT white listing items and I did following that issue report on github, but I encountered that the issue would FIX itself for me only. When I put a weapon in it would not crash the server but only my client, however when another individual does the same weapon in the table it would crash their client + server. All I did was add the weapon to the NBT whitelist section (to the server + my client) and they have done the same. The following is the latest crash log from our server and done by another individual and not me.

I have been busting my brain over this issue for 5 days and have yet to find a fix. Your NBT whitelist has been the best solution but only works for me. Wondering what else can I do.

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 5/9/16 4:25 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:345)
	at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:396)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:141)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:311)
	at net.minecraft.world.World.func_72866_a(World.java:2655)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:2607)
	at net.minecraft.world.World.func_72939_s(World.java:2423)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:345)
	at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:396)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:141)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:311)
	at net.minecraft.world.World.func_72866_a(World.java:2655)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:2607)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 1490
	Entity Name: Tacorifick
	Entity's Exact location: 892.36, 71.00, 73.67
	Entity's Block location: World: (892,71,73), Chunk: (at 12,4,9 in 55,4; contains blocks 880,0,64 to 895,255,79), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2423)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['iWireless'/239, l='world', x=887.50, y=71.00, z=74.22](iWireless at 887.5027806172301,71.0,74.22499380202521), EntityPlayerMP['Tacorifick'/1490, l='world', x=892.36, y=71.00, z=73.67](Tacorifick at 892.3598535142379,71.0,73.67144279024379)]
	Chunk stats: ServerChunkCache: 635 Drop: 3
	Level seed: -7623340119730675302
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (974,69,289), Chunk: (at 14,4,1 in 60,18; contains blocks 960,0,288 to 975,255,303), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 9081526 game time, 11095696 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 55356 (now: false), thunder time: 3812 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1492.152
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 762514056 bytes (727 MB) / 4429709312 bytes (4224 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 2 total; -Xms1G -Xmx10G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 12, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1492.152.jar) 
	UCHIJAAAA	Forge{10.13.4.1492} [Minecraft Forge] (KCauldron-1.7.10-1492.152.jar) 
	UCHIJAAAA	kimagine{0.1} [KImagine] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.5.37} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJAAAA	ae2stuff{0.5.0.56} [AE2 Stuff] (ae2stuff-0.5.0.56-mc1.7.10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.1} [CoFH Core] (CoFHCore-[1.7.10]3.1.1-324.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.2} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.2-111.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.1-237.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381 (1).jar) 
	UCHIJAAAA	EnderStorage{1.4.7.32} [EnderStorage] (EnderStorage-1.7.10-1.4.7.32-universal.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	extracells{2.3.8} [Extra Cells 2] (ExtraCells-1.7.10-2.3.8b185.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAA	IC2{2.2.999} [Industrial Craft Classic] (IC2.Classic.Version.1.1.3.5.jar) 
	UCHIJAAAA	IC2-Classic-Spmod{0.0.0.0} [IC2 Classic Detection Helper] (IC2.Classic.Version.1.1.3.5.jar) 
	UCHIJAAAA	IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2] (IC2NuclearControl-2.3.3a-Exist.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	mcheli{0.10.8} [MC Helicopter] (mcheli) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
	UCHIJAAAA	modtweaker2{0.9.5} [Mod Tweaker 2] (ModTweaker2-0.9.5.jar) 
	UCHIJAAAA	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	Railcraft{9.10.0.0} [Railcraft] (Railcraft_1.7.10-9.10.0.0.jar) 
	UCHIJAAAA	powersuits{0.11.0.300} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.300.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHIJAAAA	harvestcraft{1.7.10b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10c.jar) 
	UCHIJAAAA	ProjectE{1.7.10-PE1.9.5} [ProjectE] (ProjectE-1.7.10-PE1.9.5.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	SolarExpansion{1.6a} [Solar Expansion] (SolarExpansion-Basic-1.6a.jar) 
	UCHIJAAAA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.1-324
	ThermalFoundation: -[1.7.10]1.2.2-111
	ThermalExpansion: -[1.7.10]4.1.1-237
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	NetherOres: -[1.7.10]2.3.1-22
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.1.0-161
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
		* Baubles|API (1.0.1.10) from ThermalFoundation-[1.7.10]1.2.2-111.jar
		* BuildCraftAPI|blocks (1.0) from Railcraft_1.7.10-9.10.0.0.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.16.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|core (2.0) from Railcraft_1.7.10-9.10.0.0.jar
		* BuildCraftAPI|crops (1.1) from Railcraft_1.7.10-9.10.0.0.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|items (1.1) from Railcraft_1.7.10-9.10.0.0.jar
		* BuildCraftAPI|library (2.0) from Railcraft_1.7.10-9.10.0.0.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.16.jar
		* BuildCraftAPI|recipes (4.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|tablet (1.0) from Railcraft_1.7.10-9.10.0.0.jar
		* BuildCraftAPI|tiles (1.2) from Railcraft_1.7.10-9.10.0.0.jar
		* BuildCraftAPI|tools (1.0) from SolarExpansion-Basic-1.6a.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.1.16.jar
		* CoFHAPI (1.7.10R1.0.2) from Railcraft_1.7.10-9.10.0.0.jar
		* CoFHAPI|block (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|core (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from Railcraft_1.7.10-9.10.0.0.jar
		* CoFHAPI|fluid (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHAPI|inventory (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHAPI|item (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHAPI|items (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|modhelpers (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHAPI|tileentity (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381 (1).jar
		* CoFHAPI|transport (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|world (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|audio (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|gui (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|gui|container (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|gui|element (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|gui|slot (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|inventory (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|render (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|render|particle (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|util (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|util|helpers (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|util|position (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|world (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* CoFHLib|world|feature (1.7.10R1.1.1) from CoFHCore-[1.7.10]3.1.1-324.jar
		* ComputerCraft|API (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|FileSystem (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Lua (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Media (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Peripheral (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Permissions (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Redstone (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Turtle (1.75) from ComputerCraft1.75.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.381 (1).jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.381 (1).jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.381 (1).jar
		* ForgeRelocation|API (0.0.1.4) from ForgeRelocation-1.7.10-0.0.1.4-universal.jar
		* IC2API (1.0) from IC2.Classic.Version.1.1.3.5.jar
		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.3.3a-Exist.jar
		* ProjectEAPI (7) from ProjectE-1.7.10-PE1.9.5.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|carts (1.6.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|core (1.5.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|signals (2.2.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|tracks (2.2.0) from Railcraft_1.7.10-9.10.0.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.10.0.0.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 2 / 100; [EntityPlayerMP['iWireless'/239, l='world', x=887.50, y=71.00, z=74.22](iWireless at 887.5027806172301,71.0,74.22499380202521), EntityPlayerMP['Tacorifick'/1490, l='world', x=892.36, y=71.00, z=73.67](Tacorifick at 892.3598535142379,71.0,73.67144279024379)]
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by williewillus** [comment]
Can you explain why this is a ProjectE bug

**Comment by iWireless** [comment]
As stated I seen another post on Github under ProjectE issues stating Flans and ProjectE have issues with unloaded weapons when they are placed in gun modification tables and the developer of projectE then stated whitelist the items in the NBTwhitelist. Im just further wondering why that solution is not working for me.

**Comment by MaPePeR** [comment]
So you placed an item of another mod in a block of another mod and it crashes and you think it's ProjectE?

**Comment by MaPePeR** [comment]
So I can guess here, but you really should improve on your bug reporting skills. This report is a critical failure. 

You teached a gun to the transmutation table, got it back out again and put it into the gun modification table. This crashed your game. 
This is probably because ProjectE did not apply a standard set of nbt data the gun has, when you craft it normally. 

So the nbt Whitelist would fix this, but only if you reteach it with a newly crafted gun and unlearn the other. 

That would result in you probably being able to duplicate the gun in ways you are not supposed to (duplicate a gun that is fully loaded?) 

So the best fix for this is to remove the emc values from the guns itself.

**Comment by sinkillerj** [comment]
I concur with Blubs theory, this isn't on us, the author likely needs to move where that NBT is registered, or add a failsafe if its found missing. Plus lets be honest here Flans Mod has never been the pinnacle of great code...
