### ISSUE TITLE
Philosopher's stone is used up when crafting in project table 

### ISSUE THREAD

**Issue by SponcoVonDwet** [sinkillerj/ProjectE#1229]
I have found that the philosopher's stone is being consumed when trying to craft items, such as alchemical coal when crafted in ProjectRed: Expansion's Project table. this problem occured multiple times and can likely be reproduced.

**Comment by MaPePeR** [comment]
This is probably a bug in the ProjectRed Project Table.

**Comment by williewillus** [comment]
^
