### ISSUE TITLE
Gem armor protects against armor piercing attacks

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#1231]
i noticed that while wearing gem armor certain attacks from certain mobs specifically thaumcraft bosses and chaos guardians from draconic  evolution are able to kill the player instantly. these attacks are specifically the armor piercing type. it would be nice if the gem armor can protect against this type of attacks.

**Comment by sinkillerj** [comment]
Its been discussed before but IMO it would be best to keep that one flaw in place. Even back during the Tekkit Classic days it wasent perfect armor, a IC2 nano could wreck it.

**Comment by Alexismachina** [comment]
Its a easy one-shot kill with the Red Katar AoE attack :P

**Comment by blackdragonIV** [comment]
maybe make it a config option disabled by default @sinkillerj ?

**Comment by williewillus** [comment]
I think it should be RM/DM don't protect against it, but gem should

**Comment by Alexismachina** [comment]
If you do that you are stepping in ludicrious power creep.

**Comment by Alexismachina** [comment]
Unless you make it only able receive only some protection, else in a couple hours you get a cheap Draconic Evo armor that doesnt require power, or need to be changed ever again.

**Comment by blackdragonIV** [comment]
@Alexismachina a config option would satisfy both sides of the arguments

**Comment by Alexismachina** [comment]
This is Botania passive flowers config all over again.

**Comment by williewillus** [comment]
Not really?

**Comment by Alexismachina** [comment]
But then again if you do so you have an armor that nullifies anything. We've talked about it here once , and on irc a couple of times.

**Comment by Alexismachina** [comment]
Altough i did counter myself in the beginning, one-shot someone with the red katar in one blow from relative medium range (5-10m away) is a bit rediculous.

**Comment by escman1999** [comment]
:P isn't gem armor both end game, and extremely expensive? so wouldn't it be good for it to be the ultimate armor?

**Comment by Alexismachina** [comment]
its not hard to get , 1-2 hour and you can have the entire set

**Comment by escman1999** [comment]
what about with just projecte installed?

**Comment by Heimdell** [comment]
By the way (as I remember), in the time of Good Old EE2 Black/Red matter armor and blocks provided no resistance to explosions - Armor didn't protect from them and blocks just ignored them as if they are air.

Do they work the same way now?

**Comment by Bersham** [comment]
Changing Gem Armour to nullify piercing damage and explosions is kind of pointless. Once QuantumFlux and EnderI/O get their complete 1.9 versions you'll be set. Plus, there will be Draconic Evolution which is over powered in it's own right. I find the game too easy by itself, so I edit monster health and attacks to 2.5 times default.

Also, the new mods BaseMetals, ModernMetals, and NetherMetals add ways to be anti-withered, so there is that.

If it was up to me, I'd say get rid of Gem Armour or change this whole mod into a plugin based mod like Buildcraft has done. I wish I could learn Java, but I'm just a dumb math guy.

**Comment by Bersham** [comment]
@escman1999 Just play in peaceful?

**Comment by MaPePeR** [comment]
I think i will speak for the whole team when i say: No, we are not going to rip this whole mod apart for you.

**Comment by Bersham** [comment]
I wouldn't expect you guys to.
