### ISSUE TITLE
Items being unlearned randomly

### ISSUE THREAD

**Issue by KJP12** [sinkillerj/ProjectE#1232]
Items was disappearing from the transmutation tablets when it should not be. Possibly due to all the mods I have, but it should NOT be deleting items for no reason.

It could also be possible that it is deleting items from the tablet because I am adding EMC to items appropriately, but it is still deleting it though!

Does happen in 1.7.10-Forge10.13.4.1558

**Comment by sinkillerj** [comment]
Duplicate of #1212.
