### ISSUE TITLE
Add Dispenser Behaviors for the Philosopher's Stone (1.7.10 - Present)

### ISSUE THREAD

**Issue by T145** [sinkillerj/ProjectE#1233]
I think it would be a nice feature to have a dispenser behavior for the Philosopher's Stone. If a player is able to use it, I don't see why it can't be automated a little more.

**Comment by sinkillerj** [comment]
The Philosophers Stone cannot act independent of the alchemist as it is their power which is transferred through it. Lore aside there are already blocks that can use held items in TE, ComputerCraft, and others.

**Comment by T145** [comment]
Only it doesn't work in an Autonomous Activator, at least in 1.7.10
