### ISSUE TITLE
Gem Armor Step Assist

### ISSUE THREAD

**Issue by zzApotheosis** [sinkillerj/ProjectE#1234]
Java 1.8.0_77 (64-bit)
Minecraft 1.8.9
MCP 9.19
Forge 11.15.1.1902
OptiFine_1.8.9_HD_U_H5
ProjectE 1.1.4

Seems as though the Gem Boots' Step Assist doesn't work on 1.8! :(

**Comment by williewillus** [comment]
1.8 not supported anymore, I can't reproduce it anymore in 1.9 (but I don't recall explicitly fixing it 0.o)

**Comment by darthvader45** [comment]
It also doesn't work in 1.12.2.  If 1.12.2 is not supported, I understand.  I think I tried it in 1.16.5 and 1.18.2, and neither of those versions had it working either.
