### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by zzApotheosis** [sinkillerj/ProjectE#1237]
Java 1.8.0_92-b14 (64-bit)
Minecraft 1.9.4
MCP 9.28
Forge 12.17.0.1935
OptiFine_1.9.4_HD_U_B4
ProjectE: Compiled version based on current source code in the 1.9 branch (30 May 2016)

I'd like to report a few things.

The Repair Talisman does not repair armor that is worn. It will properly repair items in the inventory but not worn armor (I have not tested baubles slots).

The Red Katar and Red Morningstar both behave strangely when right clicked, as if they're trying to be used as some other type of item. I know the Katar usually blocks like a sword and the Morningstar instantly mines when charged. The instant mine function still works, it's just when right clicking the air, the items behave a little strangely...

And for a suggestion, please consider updating default EMC values for new vanilla items in 1.8 and 1.9.

Also, it seems the Gem Armor Step Assist is functioning properly in 1.9.4... In #1234 I mentioned the step assist did not function at all in 1.8, but seems to be fine now... I'll have to check this out further.

Thanks for reading, and thank you for maintaining this outstanding mod!

**Comment by sinkillerj** [comment]
Not sure if @williewillus is even accepting 1.9 bugs yet, but ill leave this open till he chimes in.

**Comment by williewillus** [comment]
1. intended
2. can't reproduce anymore
3. see the other "new emc value" issue"
