### ISSUE TITLE
MindStone.getStoredXP null Render Crash

### ISSUE THREAD

**Issue by redo6565** [sinkillerj/ProjectE#1239]
[crash-2016-06-05_16.24.29-client.txt](https://github.com/sinkillerj/ProjectE/files/299499/crash-2016-06-05_16.24.29-client.txt)

**Comment by williewillus** [comment]
0d7e357

**Comment by Rumpelstiltskinny** [comment]
mhmm, having an acceptable commit and NOT providing a timely release that allows the client to CONTINUE crashing makes more sense.

**Comment by williewillus** [comment]
Am I going to have to lock all of these?

**Comment by sinkillerj** [comment]
@Rumpelstiltskinny 1.9 is a beta release, you use it at your own risk, when we are confident that major bugs such as this are fixed we will release a stable. Keep it constructive please.

**Comment by williewillus** [comment]
Reopening just for visibility so people will stop making dupes >_<
