### ISSUE TITLE
Divining Rods don't consume EMC

### ISSUE THREAD

**Issue by Azmarok** [sinkillerj/ProjectE#1240]
[According to the Tekkit wiki](http://technicpack.wikia.com/wiki/Divining_Rod), the divining rods in EE2 consumed EMC. 16 EMC per scan in short range, 32 EMC in mid range, and 64 EMC in long range. ProjectE does not have this.

**Comment by sinkillerj** [comment]
Thats the EMC value of the item, they have never consumed fuel, they are a early game item -,-

**Comment by sinkillerj** [comment]
After reading the page more I get what you are saying, but I dont recall that ever being a thing, and even so theres no point implementing it given its early game status.
