### ISSUE TITLE
Dedicated server removes transmutation knowledge if stopped while player is logged in

### ISSUE THREAD

**Issue by Yabdat** [sinkillerj/ProjectE#1242]
Found a bug with the latest 1.9.4 version 
ProjectE-1.9.4-PE1.0.0B with forge-1.9.4-12.17.0.1954-universal

If a player is online on a dedicated server when it restarts, all of the transmutation knowledge that the player has is removed.
The stored EMC is kept.
If the same player is logged of when the server restarts, he keeps the knowledge.

**Comment by sinkillerj** [comment]
Are you performing a proper "stop" command before restart?

**Comment by Yabdat** [comment]
As far as i know yes, im using the AMP Minecraft manager and using the button the restart the server, and according the logs:

[02:26:42] [Server thread/TRACE] [ProjectE/ProjectE]: Sending event FMLServerStoppedEvent to mod ProjectE
[02:26:42] [Server thread/DEBUG] [ProjectE/ProjectE]: Cleared tile entity maps.
[02:26:42] [Server thread/DEBUG] [ProjectE/ProjectE]: Cleared cached tome knowledge
[02:26:42] [Server thread/DEBUG] [ProjectE/ProjectE]: Cleared player check-lists: server stopping.
[02:26:42] [Server thread/INFO] [ProjectE/ProjectE]: Completed server-stop actions.
[02:26:42] [Server thread/TRACE] [ProjectE/ProjectE]: Sent event FMLServerStoppedEvent to mod ProjectE

**Comment by williewillus** [comment]
Cannot reproduce

**Comment by Yabdat** [comment]
Hmm, ok, im running a rather large modpack, could be something else.. 
Dunno if it has something to to with it, but the server is on linux. 

Letme do some testing and come back to you.

**Comment by Yabdat** [comment]
I can reproduce it with just latest JEI and latest ProjectE only. jei_1.9.4-3.4.3.207 and ProjectE-1.9.4-PE1.0.0B

Im using AMP, https://cubecoders.com/AMP on a linux server.

I put down a Transmutation Table, add something to it, log off and restart the server. When i log back in everything is still there.
I put down a Transmutation Table, add something to it, and press restart on the server console. When the server is back up, and i log back in, all the transmutation knowledge is gone, but the EMC is still there.

Server log: http://pastebin.com/nFgjkDtf

**Comment by williewillus** [comment]
got it.
I suspect this may be a forge bug, need to test for  sure

**Comment by williewillus** [comment]
Actually maybe its not a forge bug >.<

**Comment by williewillus** [comment]
Yeah I can't figure this out. Stabs welcome >_<

**Comment by williewillus** [comment]
figured it out. forge bug #3206

**Comment by williewillus** [comment]
948548d
