### ISSUE TITLE
With Dark Matter PickAxe RMB works strange 1.9.4

### ISSUE THREAD

**Issue by ircmaan** [sinkillerj/ProjectE#1246]
Only one block of vein it gets in my inventory. After that I have very big lags (5sec) every 2-4 sec. If I want to "save and close" it hangs up.
P.S. I can not see button "Label" for mark as 1.9
P.PS.Now I cannot have even 1 first block in my inventory - big lags

**Comment by williewillus** [comment]
redirecting to #1257
