### ISSUE TITLE
[1.9.4] Getting NPE when pointing on Mindstone ( I guess)

### ISSUE THREAD

**Issue by Gepett0** [sinkillerj/ProjectE#1247]
ProjectE-1.9.4-PE1.0.0B
MC: 1.9.4
Forge: forge-12.17.0.1937/40/50/54
Java: 1.8.0_25

I get always a CTD no matter what I try. Even on a clean install with only forge and PE.

http://pastebin.com/q09EywmL

**Comment by MaPePeR** [comment]
Duplicate of #1239. Will be fixed in next release.
