### ISSUE TITLE
Missing Vanilla EMC Values

### ISSUE THREAD

**Issue by ircmaan** [sinkillerj/ProjectE#1248]
Beetroot
seed Beetroot
Beetroot soup

Raw mutton
Cooked mutton

Purpur block (it may be quite rich as 1024EMC or even more)
Purpur pillar
Purpur stairs
Purpur slab

Stone Monster Egg
CobbleStone Monster Egg
Stone brick Monster Egg
Mossy Stone brick Monster Egg
Cracked Stone brick Monster Egg
Chiseled Stone brick Monster Egg

End Rod
Chorus Plant
Chorus Flower
Chorus Fruit
Popped Chorus Fruit

Dragon Head
Elytra (must have very big EMC – for two or more players)

Firework star
Firework rocket
Name tag

Chain helmet (can be like Iron EMC)
Chain Chestplate
Chain Leggins
Chain Boots

Rabbits foot

========
Can you make some minimal EMC for all SCULLs?

**Comment by sinkillerj** [comment]
Skulls and the Dragon Head will never have EMC by default. Chainmail will not as it is not legitimately obtainable, same for "monster eggs".

**Comment by williewillus** [comment]
beetroot: sure
mutton: sure
purpur: sure
monster eggs: not obtainable in survival, no
end rod: sure
chorus plant:
chorus flower:
chorus fruit:
popped chorus fruit: inherit from chorus fruit
dragon head: see skulls
elytra: hell no
fireworks: no, it requires NBT sensitivity which we don't have yet
name tag: sure
chain armor:maybe 
rabbit's foot: sure
skulls: probably not

**Comment by sinkillerj** [comment]
I second no EMC on Elytra.

**Comment by Lightwave413** [comment]
What about Dragon's Breath?

**Comment by williewillus** [comment]
Prrrooobably not, we'll see

**Comment by sinkillerj** [comment]
I'm going with no on Breath if for no other reason because we generally dont have potion EMC, then again being a mat it is a odd case...

**Comment by ircmaan** [comment]
Only one Elytra for server? Why? How can my friend obtaine it after me?

**Comment by ircmaan** [comment]
Chain armor is a drop = legitimately obtainable. Am I right?

**Comment by MaPePeR** [comment]
Ircmaan: I thought there are  multiple structures that contain the Elytra...

I think dragon breath should get a value and with the new potion system it should be easier to generate emc values for them.

**Comment by ircmaan** [comment]
Zombie Head, Skeleton Head, Enderman Head is a drop.
Amost all the rest drop has EMC.
For some days we have MANY useless heads without EMS.

**Comment by sinkillerj** [comment]
If you want skull EMC you can use the "/projecte setemc" command.

**Comment by MaPePeR** [comment]
No, you can't, because skulls use NBT data.

**Comment by sinkillerj** [comment]
Even if they do you can add them to the whitelist, just no individual values yet, but thats coming soon.

**Comment by williewillus** [comment]
Only player heads use nbt the mob ones are just damage values

**Comment by williewillus** [comment]
78a0265
