### ISSUE TITLE
NPE in moze_intel.projecte.gameObjs.items.rings.MindStone.getStoredXP

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [sinkillerj/ProjectE#1250]
NPE crash while viewing items in JEI.

[crash-2016-06-06_17.52.45-client.txt](https://github.com/sinkillerj/ProjectE/files/301635/crash-2016-06-06_17.52.45-client.txt)

**Comment by williewillus** [comment]
4th duplicate of this issue

**Comment by Rumpelstiltskinny** [comment]
then provide a release?

**Comment by williewillus** [comment]
Because providing a release for every bug fix makes sense
