### ISSUE TITLE
1.9.4 dark matter pick cant mine ender io fluid tank 

### ISSUE THREAD

**Issue by kamyflouge** [sinkillerj/ProjectE#1252]
(1.9.4 ) you can't mine fluid tank from ender io with a dark matter pick axe

**Comment by sinkillerj** [comment]
I'm not terribly familiar with that tank but it sounds like something that may require a special tool, can a Vanilla diamond pick mine it?

**Comment by kamyflouge** [comment]
it can be mined by any other pick axes

**Comment by pupnewfster** [comment]
Can be closed, as if this ever was really an issue it is no longer an issue in 1.12.2 (tested and it can break the fluid tank just fine)
