### ISSUE TITLE
Trans knowledge, EMC, and bag data lost when leaving the end dimension 1.9.4

### ISSUE THREAD

**Issue by shanesova** [sinkillerj/ProjectE#1255]
I may have lost the save data when entering the end before fighting the dragon and didn't notice until after taking the exit portal, not real sure though.

**Comment by shanesova** [comment]
I did a little more testing and it only looses the data when i leave the end, when i enter the end it seems to be fine.

**Comment by sinkillerj** [comment]
If true this may be a simple fix, I seam to recall us having this issue in the past due to something odd with Vanilla, but Willie should know the specifics.

**Comment by williewillus** [comment]
Hook point for some event changed I'm betting. Will take a look tonight

**Comment by williewillus** [comment]
7065247
