### ISSUE TITLE
Tome of Knowledge Issues

### ISSUE THREAD

**Issue by ircmaan** [sinkillerj/ProjectE#1256]
I can not see any items inside my Transmutation table(t). I can copy them by placing in the circle, I can burn them and EMC more and more. Searching inside can not see anything.
I delete PE1.0.0B and install PE1.0.1B and delete config - nothing happened.

**Comment by williewillus** [comment]
Cannot reproduce

**Comment by williewillus** [comment]
The tablet will only show you things you can afford

**Comment by ircmaan** [comment]
I take Tome Of Knowledge, burn it in the tablet and All items in the table are gone. I take another ToK and unburn it = all items return. 
 # The Tome of Knowledge can be crafted. [default: false]
    B:craftableTome=true
I change B:craftableTome=false = still triuble, nothing happened.

**Comment by sinkillerj** [comment]
That probably would have been an important thing to note initially lol.

**Comment by williewillus** [comment]
The cached tome knowledge list is somehow empty because this line: https://github.com/williewillus/ProjectE/blob/b637c0fef336cab57d858575642f923d61ac12c9/src/main/java/moze_intel/projecte/playerData/Transmutation.java#L37-L37

is failing

**Comment by williewillus** [comment]
342b2ed
