### ISSUE TITLE
1.9.4 dark matter pick right click ores issue

### ISSUE THREAD

**Issue by kamyflouge** [sinkillerj/ProjectE#1257]
when i right click ores with dark matter  the ores disappear but the loot balls won't drop .the game lags and if you mine anything with the dark matter pick in that period you wouldn't get any drops.other tools like the dark matter shovel and vanilla picks work fine and drop blocks after doing the right click function 
the game will not crash and it gets  fixed after restarting the game

and after restarting the game the mined blocks aren't there (i mean it's not  desync or lag )

PS: the game freezes when you click exit but no crash log thats all  i got

**Comment by zzApotheosis** [comment]
Can confirm. This is what happens to the Red Morningstar as well. Haven't tested Red Matter Pickaxe.

**Comment by popemichael** [comment]
I too con confirm on 1.9.4 using v1.0.1. I'm using it with FTB unstable version 4.0.6.

**Comment by Lazarix** [comment]
I have this issue also.
The crash is here:

https://gist.github.com/Lazarix/e596e08dc3dd24d614ce77771ef30a46

Seems to be an issue with moze_intel.projecte.utils.WorldHelper.harvestVein(WorldHelper.java:540)

**Comment by williewillus** [comment]
Yes it hangs now for some reason. I will rewrite it soon :p

**Comment by popemichael** [comment]
I did some testing on the latest version 1.0.3B (1.9.4 on FTB Unstable) and discovered that the Shovel is now working again for both the red and dark matter types.

I also discovered that the darkmatter pickaxe will work on the lowest setting, but will not work on any higher settings. Additionally, the redmatter pickaxe will not work at all.

**Comment by williewillus** [comment]
Yeah the mass digging isn't affected, it hangs/doesnt work only if it's the ore vein mining

**Comment by MaPePeR** [comment]
The problem is, that `word.setBlockToAir` does not set the block to air, which creates an infinite rekursion. (Another problem here is, that our numMined-wall is implemented wrong, because it only counts for 1 recursion depth and not for all the recursions.)

**Comment by Laruae** [comment]
Currently using ProjectE-1.9.4-PE1.0.3B, the Dark Matter pick is working correctly for redstone ore, however I am experiencing the hangup on coal. Not sure if that information is at all helpful :x

**Comment by Trigger225** [comment]
I am having the same problem in ProjectE-1.9.4-PE1.0.4B. I looked at the debug data when i right-clicked some coal and the ram use sky rockets. The game runs out of memory and freezes after that.

**Comment by PhantomPowerful** [comment]
Just like above, in ProjectE-1.9.4-PE1.0.4B, on Forge 1.9.4-forge1.9.4-12.17.0.1976, right clicking with the Dark Matter pickaxe causes extreme lag, and then freezing to the client.
Log: http://pastebin.com/jijb1ysJ

**Comment by williewillus** [comment]
should befixed next build (for 1.10)

**Comment by runescapejon** [comment]
@williewillus  this is the same problem with 1.7.10 but its a server side problem http://pastebin.com/NXrBfhHL
mind fixing it also ?
