### ISSUE TITLE
Feature Request: EMC Builder?

### ISSUE THREAD

**Issue by zauberparacelsus** [sinkillerj/ProjectE#1259]
One thing that would be nice is a way to record structures and then later build them from a blueprint, much like the Builder machine from BuildCraft.  But instead of having to supply all the different blocks that are needed ahead of time, this builder could instead create the structure using EMC.

(Though, it may still need an inventory to supply blocks/objects that don't have an EMC value)

**Comment by escman1999** [comment]
that would be better for an add on, seeing as projecte is supposed to be ee2 but with little quality of life changes, not big ones

**Comment by MaPePeR** [comment]
Did you take a look at the mercurial eye? 
(it's still on the "needs improvement" list, but it should do *something* along the lines of what it was designed to do)

**Comment by zauberparacelsus** [comment]
For walls and floors perhaps, but the mercurial eye isn't very useful for making complex structures.

**Comment by escman1999** [comment]
why not just use the buildcraft builder?

**Comment by sinkillerj** [comment]
I've thought about this for a official addon, but that project is on hold at the moment. Till then any other addon authors are free to make a machine like this. Other then that you can use a builder as suggested, and perhaps pipe from condensers.
