### ISSUE TITLE
Server Crash: Invalid id 11067 - maximum id range exceeded

### ISSUE THREAD

**Issue by chezpaul** [sinkillerj/ProjectE#1260]
Running a 1.7.10 Server. Without ProjectE, it works fine. Trying to add it won't allow me to boot server.
Anything I can do to fix this?
Server crash log below
This is the first time I use ProjectE so no blocks have been used.
Thanks

http://pastebin.com/4DvH9rXF

**Comment by escman1999** [comment]
you have too many mods installed, either remove some mods, or install a mod called notenoughids, which will solve your problem, as well as let you install more mods

**Comment by chezpaul** [comment]
Thanks..
Too bad NotenoughID's breaks old worlds. It only works on new worlds.

Installation
- Make a backup of Minecraft installation folder.
- Install Minecraft Forge (If you still not installed it).
- Download NotEnoughIDs.
- Go to the game folder.
- Drop both .jar files into the mods folder.
- Start a new world. Old worlds will break. You have been warned.

**Comment by williewillus** [comment]
Not a PE issue.
Also be forewarned about hacks like NEIDs, it mucks with internal stuff and can blow up badly
