### ISSUE TITLE
Missing EMC values in latest version (1.0.3B for 1.9.4)

### ISSUE THREAD

**Issue by Partonetrain** [sinkillerj/ProjectE#1261]
There's some missing EMC values in the latest version for modded items, especially modded metals like Copper Ingots. This (obviously) prevents things that are made from them from having EMC values.

**Comment by sinkillerj** [comment]
Looking over the logs it looks like a typo in the OD json, give it a look over @MaPePeR ?

**Comment by williewillus** [comment]
yes, my fault. fml.
