### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by runescapejon** [sinkillerj/ProjectE#1262]
My server keep crashing i am on 1.7.10  ProjectE-1.7.10-PE1.10.0 http://pastebin.com/gTdpiLAx

**Comment by williewillus** [comment]
reinstall

**Comment by runescapejon** [comment]
What could you please explain ?

**Comment by williewillus** [comment]
Reinstall your server (redownload the pack and all libraries)

**Comment by sinkillerj** [comment]
I concur with willie, this definitely looks like a bad server install, in particular one of the libraries being missing.

**Comment by runescapejon** [comment]
When you talk about Libraries are you talking Thermos lib. ?

**Comment by sinkillerj** [comment]
We are refering to the libraries folder in the root of your Minecraft server folder, this is typically created by the Forge server installer but if you downloaded a premade pack it may have came with a libraries folder that was missing a important jar, running the Forge installer on an empty folder on your computer should provide a proper libraries folder you can copy. Beyond that there is nothing more we can do as this is not a ProjectE issue. Beyond this you will need to seek help anywhere that offers basic Forge setup tutorials such as the Minecraft Forums.

**Comment by williewillus** [comment]
you also need the vanilla server jar in the root directory

**Comment by runescapejon** [comment]
I do have the Vanilla server jar in the same root directory next to Thermos
