### ISSUE TITLE
1.9.4, Transmutation Table locks items

### ISSUE THREAD

**Issue by P0ntuZ** [sinkillerj/ProjectE#1264]
I shift clicked an item in the inner circle and  a red zero appeared next to it and now i cant get that item out anymore. It doesn't happen to every item. 

Also it seems that after exiting the table and going back in, the zeros are still there but you can get the items out, again doesn't happen to every item, hmm.

I tested it with latest update (1.0.3b) and in a vanilla world.

**Comment by syednazri** [comment]
Same here, is this a glitch? Can anyone please tell me how to fix this? See photo attached.
![transmutation table-0 coal](https://cloud.githubusercontent.com/assets/17488484/16227076/35df373a-37e1-11e6-86b7-d971b8e963ea.png)

**Comment by popemichael** [comment]
I came to report this issue as well. Minecraft 1.9.4 with version ProjectE 1.0.3b

Alchemical Coal was the thing that locked up for me. 

The fix is to reboot your instance of Minecraft. 

Even though I was able to use  "Alchemical Coal" after a full restart, sadly I was unable to recreate the issue.

**Comment by williewillus** [comment]
So does the 0 still show if you restart?

**Comment by popemichael** [comment]
The 0 no longer shows after a restart. 

Originally it showed up for me when I shift- clicked Alchemical Coal into the transmutation table. When I tried to pull it out again by typing its name into the table, the 0 showed.

I rebooted my client and now the 0 no longer shows for Alchemical Coal

**Comment by Gibil** [comment]
I've restarted my client and server as well, and the zero only temporarily goes away.  My locked item is redstone dust.

**Comment by williewillus** [comment]
i can't reproduce this

**Comment by MaPePeR** [comment]
So you are experiencing this in multiplayer?

**Comment by Wiseacre-Software** [comment]
Reproduces in v1.2.3 with coal and glowstone.

**Comment by JAWSAWN** [comment]
I have the same issue with 1.10.2 6B

Happened to charcoal and redstone, replacing the table doesnt work, changing dimensions and relog fixes it.
