### ISSUE TITLE
No basic crafting recipes. 

### ISSUE THREAD

**Issue by frenople** [sinkillerj/ProjectE#1265]
I've searched all over for a fix for this but no luck. The recipes for all ProjectE items are not appearing in my game. I even tried crafting things like the low covalence dust with the recipes from the wiki and tutorial videos but no item is created. It's the same story for all the ProjectE items. I'm playing SMP with minecraft version 1.7.10 and forgeloader version 10.13.4.1614.  I'm using the Curse client to launch and manage my mods. And I'm playing with the "Unstoppable" modpack. ProjectE is version  1.7.10-PE1.9.5 in the pack. I even tried replacing that one with the most recent 1.7.10-PE1.10.0 with the same issues. 

I might be missing something simple I'm missing but I can't figure it out.

**Comment by sinkillerj** [comment]
This is likely something the pack author is doing through a mod such as Minetweaker.

**Comment by frenople** [comment]
Is there a way that I can fix it?

**Comment by escman1999** [comment]
remove the minetweaker script from the scripts folder in your modpack's file directory

**Comment by sinkillerj** [comment]
The better option would be to edit the script to remove the ProjectE portion, the script likely has other changes which may drastically break the modpack experience if removed.
