### ISSUE TITLE
[1.9.4]java.lang.NoClassDefFoundError when loading world with Chisel 3 installed.

### ISSUE THREAD

**Issue by AlphaKintari** [sinkillerj/ProjectE#1270]
Not sure if it's ProjectE or something with Chisel 3 error log seems to indicate ProjectE.
Happens when you attempt to load or create a new world.
[Log here](http://paste.ee/p/ASWvs)

**Comment by MaPePeR** [comment]
As a workaround disable the ChiselMapper in the `mapping.cfg`

**Comment by AlphaKintari** [comment]
[See here](http://minecraft.curseforge.com/projects/chisel-3-the-cricket-strikes-back?gameCategorySlug=mc-mods&projectID=225236)

New Version of Chisel for 1.9.4

**Comment by AlphaKintari** [comment]
Turning that option off does work.  Closing
