### ISSUE TITLE
Repair Talisman Crash

### ISSUE THREAD

**Issue by 20njackman** [sinkillerj/ProjectE#1272]
Every time I make the repair talisman, my game crashes a few seconds later.  I have tried downloading different versions (ie: ProjectE-1.7.10-PE1.10.0.jar, ProjectE-1.7.10-PE1.9.2.jar, etc.) but it still crashes when i have the repair talisman in my inventory.  When i acted quickly and got the item out of my inventory, it was fine for a little while, then I made the mistake of getting the talisman back into my inventory.  From that point, I haven't been able to get the talisman back out of my inventory.

**Comment by sinkillerj** [comment]
We will need the crash log in order to provide assistance.

**Comment by 20njackman** [comment]
ok

**Comment by 20njackman** [comment]
Would that, by any chance, be in the "crash reports" file in my .minecraft file?

**Comment by 20njackman** [comment]
if so, here is the most recent one:
[crash-2016-03-23_15.03.22-client.txt](https://github.com/sinkillerj/ProjectE/files/329103/crash-2016-03-23_15.03.22-client.txt)

**Comment by 20njackman** [comment]
If not, I will need more information.

**Comment by sinkillerj** [comment]
You will need to get the log from the same location that has the mods folder that you are using with ProjectE, this is a old and likely unrelated log from March.

**Comment by 20njackman** [comment]
Oh. Sorry I have no idea what I'm doing. I will try to figure it out.

**Comment by 20njackman** [comment]
You said the same location that has the mods folder, which is my .minecraft folder.  There are about a dozen different folders there. Any ideas as to what the one I'm looking for might be called?

**Comment by sinkillerj** [comment]
Without the proper logs the best I can do is speculate that it may be due to a known crash when using outdated Chisel builds from 2014. You can try upgrading to the latest 1.7 build from here: http://minecraft.curseforge.com/projects/chisel/files  Alternately you can try disabling Chisel in your ProjectE config.

**Comment by 20njackman** [comment]
Okay thanks, I will try that.

**Comment by 20njackman** [comment]
Thank you so much for your help, my game seems to be doing fine now that I have removed the Chisel mod.  You were a great help, and I hope you have a nice life.
