### ISSUE TITLE
[1.9.4] Dark Matter & Red Matter Helmet and Boot Icons swapped. 

### ISSUE THREAD

**Issue by Laruae** [sinkillerj/ProjectE#1274]
Currently the icons for the Dark Matter Boots and the Dark Matter Helmet are swapped. Same for the Red Matter Boots and Helmet. The Gem Helmet and Gem Boots are correct.

**Comment by Laruae** [comment]
Upon furthur investigation, it appears that the icons are not swapped, instead the names of the items are swapped instead.

**Comment by williewillus** [comment]
fixed in latest build
