### ISSUE TITLE
1.7.10-PE1.10.0 - Archangel's Smite Server Crash (Reproducable)

### ISSUE THREAD

**Issue by Caslomyr** [sinkillerj/ProjectE#1276]
First, thank you **so** much for ProjectE!  I missed EE2 a great deal, but apparently you missed it more. :)

After freshly crafting an Archangel's Smite, I placed it on my hotbar, closed inventory, made it the active item, and right-clicked.  The server immediately crashed.  Attached is the server crash log.

[crash-2016-06-27_09.20.05-server.txt](https://github.com/sinkillerj/ProjectE/files/335381/crash-2016-06-27_09.20.05-server.txt)

**Comment by sinkillerj** [comment]
Likely a bad server install, please see #1262
