### ISSUE TITLE
Gem Armor + Slime Blocks = 1 Billion Block Vertical Bounce

### ISSUE THREAD

**Issue by SoraHjort** [sinkillerj/ProjectE#1278]
MC: 1.9.4
Forge: 12.17.0.1987
ProjectE: 1.0.4B

Found this out by accident. When using the Gem Armor's Gravity Greeve's ability (The quick descent ability by holding shift), and with slime blocks underneath you, you quickly exponentially bounce higher and higher. Third or fourth bounce will have you up in the Millions range, and the next near or into the billions.

The only issue that I've seen come out of this is extreme amounts of lag. I don't know if that carries over to servers, as this was tested in single player. I wouldn't think so since it seemed more rendering than anything else. Which is to be expected when you're moving over a million blocks per frame during the 1 frame per 15 seconds lag.

I was gonna do a little amusing video show casing this, but things kinda fell apart. The reason why was because snow gets a little graphically interesting at higher heights. Just as well, as Youtube's compression would just destroy it. Basically snow became beams of lights. (A image for those curious, includes how high up for it. Unfortunately it's only looking straight up. I should have taken one looking ahead instead. http://imgur.com/hUn92bM )

So yeah, it seems like this is pretty harmless, unless it also affects server performance (untested on my end). I'd almost say leave it alone otherwise. But I think the best way to fix it would put in a max speed to the quick descent. As it is currently, there does not appear to be a limit.

Oddly enough, it never crashed me, which was bizarre. The compiled mods I had been using hadn't really been the most stable and crashed periodically over little tiny things. Though doing this did result in about a 10 minute freeze time while trying to descend, and then forcing a save and quit, since it would freeze as soon as leaving the pause menu.

**Comment by sinkillerj** [comment]
I love brilliant bugs like this. Thanks for the report, god knows how long it would have taken us to find out about it.

**Comment by escman1999** [comment]
i wonder if this bug exists in the 1.7.10 version when projecte is used with et futurum? it also adds a slime block that's identical to vanilla :D

**Comment by williewillus** [comment]
I vote feature not bug lol

Maybe a cap on maximum downward speed, but the stomping on slime bouncing back is completely within intention

**Comment by SoraHjort** [comment]
Oh I agree that I'd like it to stay. As I said, it only becomes problematic when you get 1 Million+ high up. My biggest concern is when it comes to servers if they're able to handle it.
It'd actually be funny if someone were to make a bridge mod between this and galacticraft. "No rocket? No problem! Bounce your way to the moon!" Too bad that mod hasn't updated since 1.7.

**Comment by sinkillerj** [comment]
Not having a cap is def bug territory unless you like setting servers on fire.

**Comment by SoraHjort** [comment]
Mmmm... I think the minimum number for the speed cap should be when you bounce off the slimeblocks, it would take up from bedrock up to the max build height easily. Higher would be nice just for S&Giggles. But I think many of us could settle for being able to have that kind of bounce.

**Comment by williewillus** [comment]
no config creep for something as small as this

**Comment by williewillus** [comment]
it'll be whatever "feels good" ;p

**Comment by williewillus** [comment]
Okay for now I settled on:

Max cap of 8 blocks/tick (roughly double the standard player terminal velocity)
Acceleration applied additively not multiplicatively. 


This has some cool implications and it takes a bit of skill and a few jumps to get up to y 128 and to get higher. You have to know when to shift, when to let go to not hurt your height or die, etc. I think it's nice

**Comment by williewillus** [comment]
The max height I can reach with quite a few jumps is 170, starting at bedrock. I think that feels okay

**Comment by williewillus** [comment]
also fun feature if you're going fast enough and pass through an entity while wearing the legs you'll damage it

**Comment by williewillus** [comment]
okay I reworked it a bit, hope you like it in the next build! :D

**Comment by SoraHjort** [comment]
So much for being able to go from 400,000 blocks up to sea level in half a second. Those were fun times. :P

Looking forward to testing it out.
