### ISSUE TITLE
issues using archangel ring not sure how to fix server host has been helping but isn't sure either

### ISSUE THREAD

**Issue by dragun108** [sinkillerj/ProjectE#1279]
to give small gist when i spawn its fine to grab said ring when right clicked  it crashes entire server
but when i do it single player its fine and for a file i will attached crash log for you. so note tho everything else works fine and this 1.7.10
and itsa custom setup but not many mods i havnt seen in configure with it before so im confounded :)
[crash-2016-07-01_03.47.25-server.txt](https://github.com/sinkillerj/ProjectE/files/342779/crash-2016-07-01_03.47.25-server.txt)

**Comment by sinkillerj** [comment]
#1276 Issue is a missing library on the Thermos side. Unreproducible on a stock Forge server.

**Comment by dragun108** [comment]
well thing is we tried reinstalling library and used  kcauldren and forge
got same effects were not sure what to do  server jars used: kcauldern ,
forge recent owo hmmill have ot try new run again butittake me sometime to
give ita whirl due ot work today =w= jobs in rl xD

**Comment by sinkillerj** [comment]
@dragun108 Fix incoming: CyberdyneCC/Thermos#426

**Comment by dragun108** [comment]
is there a file on that link i'm not seeing or you mean a update is coming out? just asking to beon safe side?

**Comment by sinkillerj** [comment]
An update is coming out on their side.
