### ISSUE TITLE
PhilStone does not transmute

### ISSUE THREAD

**Issue by meriler98** [sinkillerj/ProjectE#1286]
Philosopher stone not transmutes in world and hammers does not destroy ore spot, only single blocks

**Comment by williewillus** [comment]
cannot reproduce the first
fix for second soon

**Comment by popemichael** [comment]
I too am experiencing the issue where the philosopher stone will not transmute "in world"

Minecraft version 1.10 using Project E version 1.0.4B - I added it to the pack "All the mods" version 1.10.2 v0.7

To recreate: 

1. Create the philosopher's stone

2. Use the philosopher's stone on anything transmutable: Stone, cobble, grass, sand etc.

Video of it not working:
http://gph.is/29AP8W8

**Comment by williewillus** [comment]
should be fixed next build
