### ISSUE TITLE
Cannot use items

### ISSUE THREAD

**Issue by DipsWW** [sinkillerj/ProjectE#1287]
I see that alot of other reports have come in for the right-click ability not working for certain items, but I can say that it dosent work for any items in this version. Its a major bug that renders many items useless and needs to be fixed. I suspect that its the left-hand slot that was added to minecraft messing with the function.

**Comment by williewillus** [comment]
This doesn't give us any more info than we already have. Please give details.

**Comment by DipsWW** [comment]
There isnt really any details to give, its quite simple, when you right click with something as for example the destruction catalyst, nothing happens.

**Comment by sinkillerj** [comment]
Logs... does it happen with just ProjectE or when you introduce a particular other mod?... anything?...

**Comment by williewillus** [comment]
http://imgur.com/j99r0sd

working fine,

If you don't give details I can't do anything. "It doesn't work" is not enough.

**Comment by DipsWW** [comment]
hmm, try having an item in the left arm slot, Im using it on a clean version only using ProjectE and forge.

**Comment by williewillus** [comment]
still nothing

**Comment by DipsWW** [comment]
okay then, apparently this is only on my end, so ill close it.
