### ISSUE TITLE
1.10.2 Philosiphers Stone Block Transmutation Not Working

### ISSUE THREAD

**Issue by Evillee03** [sinkillerj/ProjectE#1290]
So have been right clicking blocks with the philosophers stone with a usable type of fuel in my inventory and nothing happens.I am clicking the usable blocks both normally and shift-clicking.While all of the other stone's functions are standard.It even highlights the blocks.So whats going on?

**Comment by escman1999** [comment]
i think the reason it doesn't work is because the offhand slot added in 1.9 changed some things

**Comment by williewillus** [comment]
Yeah it's a 1.10 incompatibility

**Comment by williewillus** [comment]
Should be fixed next build
