### ISSUE TITLE
Condensers vs. Automation

### ISSUE THREAD

**Issue by Chinthor** [sinkillerj/ProjectE#1293]
Both the MK1 and MK2 condensers have some odd issues.

When items are piped into a MK1, it will accept items with no EMC and consume them, even though you cannot put those items into the condenser by hand. There goes all the ore from my quarry. This is using ExtraUtilities2 transfer pipes, or when placed touching a RFTools builder to catch the output. I had hoped to have non-emc items pass by the condenser and land in another chest.

When items are piped into a MK2 (again, pipes or being used as an adjacent inventory) I get the same bug mentioned in another ticket. The items are consumed (EMC and Non-EMC items) with no output. The energy bar doesn't even fill up.

Also, when putting items into the MK2 by hand, it refuses to accept the same item it is condensing to. I tell it to make iron ingots, it will not let me put iron ingots in. Not by manual click or shift click. With the way the UI is arranged, this might be intended. I don't like it, but I'd understand it.

This is all using the latest (and only) ProjectE on Minecraft 1.10: 1.9.4PE1.0.4B
ExtraUtilities2 v. 1.10 alpha 1.0.0
RFTools 1.10 5.00
This is in the pack "Fear the Dark" (not to be confused with "Fear of the Dark")

**Comment by williewillus** [comment]
gg55cd25b
