### ISSUE TITLE
Gem of eternal Density filter option

### ISSUE THREAD

**Issue by HDxZOMBIEXx** [sinkillerj/ProjectE#1294]
I cant change the filter of what the gem will condense into and it is stuck on iron ingot I'm not sure why it defaulted to it though. Any suggestions?

**Comment by williewillus** [comment]
Mc version.

**Comment by Chinthor** [comment]
Also check your keybindings. Many mods want to overlap the keys used by PE. I remapped the change mode key. Hold the gem, hit the key. Your screen might say "Target changed to" and not say what it changed to. But mouse over the gem, and it will have changed to the next item. Iron ingot, gold ingot, diamond, etc.

**Comment by HDxZOMBIEXx** [comment]
1.10.2

**Comment by HDxZOMBIEXx** [comment]
thanks its working now I set it to C and then I got rid of the other key bindings that overlapped with it but for some reason it still didn't work but I just changed it to N and that seemed to work
