### ISSUE TITLE
Trans table loses all learned items but keeps EMC value 

### ISSUE THREAD

**Issue by Blackpinned** [sinkillerj/ProjectE#1296]
After crashing my server even with something not related to ProjectE the tablet gets reset except for it's value that has been stored happened twice now

**Comment by williewillus** [comment]
details please

**Comment by Blackpinned** [comment]
Not sure what exactly you need? To be honest not sure what crashed it anyway a creeper blew up next to me and my server went down and back up again but all items I learned in the table got removed

**Comment by Blackpinned** [comment]
I can give you the crash report but like I said weird enough the crash didn't affect any ProjectE related items at all

**Comment by MaPePeR** [comment]
version? mods?

**Comment by Blackpinned** [comment]
Using version 1.0.4B it's the one the curse launcher gave. And as for mods I use quite a few 
![mods list](https://cloud.githubusercontent.com/assets/20385119/16715086/ef51ef88-46d6-11e6-9915-1d7a6c19f850.jpg)

**Comment by NinjaKap** [comment]
Just had this happen to me about, maybe 5 minutes ago? Log off my Server, walk around the house doing stuff, log back on to mess around with my Power Facility and all my learned Transmutations are gone. Tablet, Table, etc.

**Comment by williewillus** [comment]
dupe #1242
