### ISSUE TITLE
Catalytic Lens, uses fuel, but does not remove blocks.

### ISSUE THREAD

**Issue by Apocalyptias** [sinkillerj/ProjectE#1298]
As the title may suggest, the catalytic lens doesn't work properly. Using the R function it does remove blocks, but the Right-click, and C functions do nothing, but still consume fuel.

**Comment by sinkillerj** [comment]
MC version? logs?

**Comment by Apocalyptias** [comment]
MC Version 1.10. Which logs do you need? There are quite a few.

**Comment by Apocalyptias** [comment]
On further playing, this issue is not exclusive to the Lens. The Dark Matter tools also don't work. I can change the mods, but once again they do nothing.

**Comment by williewillus** [comment]
Known issue, don't use 1.10 right now
@sinkillerj *please* unmark 1.10 on curse :/

**Comment by sinkillerj** [comment]
@williewillus I did like two days ago with an additional warning.
