### ISSUE TITLE
CTD with the watch of flowing time

### ISSUE THREAD

**Issue by adelayde** [sinkillerj/ProjectE#1303]
[crash.txt](https://github.com/sinkillerj/ProjectE/files/372642/crash.txt)

Watch was on a pedestal.  Was breaking a vanilla oak tree next to it.  Happened as I broke the last trunk block... might be related to leaf decay?

**Comment by Zsashas** [comment]
http://pastebin.com/
http://hastebin.com/
https://gist.github.com/

Generally preferred to having to download the log files.

**Comment by Mach12** [comment]
> http://pastebin.com/
> http://hastebin.com/
> https://gist.github.com/
> 
> Generally preferred to having to download the log files.

Github lets you drag'n'drop files into issues without looking up an upload website. Also if you don't want to save the file on your computer, just ask to open and not save the file. Most browsers offer that.

What adelayde did pretty much saves time on both ends if done right.

**Comment by MaPePeR** [comment]
Thats a lot better than just pasting the error into the comment, so i'm happy.

**Comment by Zsashas** [comment]
Mine defaults to saving the file, doesn't even give the option to open it...

**Comment by williewillus** [comment]
fixed-same as #1368
