### ISSUE TITLE
Transmutation table crashes

### ISSUE THREAD

**Issue by Underv8645** [sinkillerj/ProjectE#1306]
When I use the transmutation table after some pages of search, it suddenly crashes

**Comment by williewillus** [comment]
logs

**Comment by Underv8645** [comment]
yeah, in that pages
But also in the search box when I press w

**Comment by williewillus** [comment]
no give me your crash logs

**Comment by Underv8645** [comment]
[crash-2016-07-22_12.53.39-client.txt](https://github.com/sinkillerj/ProjectE/files/378787/crash-2016-07-22_12.53.39-client.txt)

**Comment by williewillus** [comment]
fixed in next forestry
