### ISSUE TITLE
[1.10 - 1.0.9B] Black Alchemical Bag missing dying recipe

### ISSUE THREAD

**Issue by Nova001Sol** [sinkillerj/ProjectE#1308]
![2016-07-22_21 06 18](https://cloud.githubusercontent.com/assets/8030374/17068264/44ce4204-5050-11e6-911d-c84470bcdc8b.png)
White bag + ink =/= black bag. Need more info?

**Comment by williewillus** [comment]
version

**Comment by Nova001Sol** [comment]
1.0.4B on MC 1.10.2. And I forgot to put 1.10 in the title.

**Comment by williewillus** [comment]
classic off by 1

**Comment by Nova001Sol** [comment]
Thanks.
