### ISSUE TITLE
Server crash everytime I start the server

### ISSUE THREAD

**Issue by Rnrn13** [sinkillerj/ProjectE#1309]
Its a custom modpack server ( Not acctually a modpack just an assortment of mods ) here is the pastebin : http://pastebin.com/sGrg6XM3 I also run the server on Thermos (  Cross between bukkit / spigot and forge )

**Comment by williewillus** [comment]
disable the chisel mapper in the config

**Comment by sinkillerj** [comment]
The proper solution is to upgrade your Chisel: http://minecraft.curseforge.com/projects/chisel/files

You are using a version that has been abandoned since 2014.

**Comment by Rnrn13** [comment]
Ty :+1:
