### ISSUE TITLE
Redmatter shovel and redmatter morning star bug

### ISSUE THREAD

**Issue by BadLucKWyvern** [sinkillerj/ProjectE#1310]
While using the right clik with the red matter shovel on a gravel pile underearth it kill a multiplayer server (server frozen)
Can't use the right clik of morning star

Version 1 9 4

**Comment by MaPePeR** [comment]
Known issue

**Comment by BadLucKWyvern** [comment]
when will it be fixed for 1 9 4 ? :)

**Comment by williewillus** [comment]
Due to lack of time, PE is skipping 1.9, we will be releasing on 1.10 next, and the fix is already in for that.
Sorry :/

**Comment by BadLucKWyvern** [comment]
ive lost a server witch had a corrupted save. Me and my friends losts 4 or
5 months with our server 1.8.9
ive attenpted to convince Em to make a more recent server. Half followed
me. Rest left. Dissapointed
I can't make a new server because 3/4 of our mods aren't on 1.10... we
already lost some from 1.8.9 to 1.9.4 like iron backpack halocraft or super
ores... ProjectE is the pillar of our server. If it change, the rest must
change. Late Version will cut the wish to play from my friend and myself.
Ik it dosen't concern you or thats not your problem at all but... we really
need theses patches for 1.9.4 :'(

PS: ive done a another report
PS':sorry for my weak english

**Comment by sinkillerj** [comment]
I may do a 1.9 build once I've recovered a bit more, but it will be the last. We initially wanted a universal build but it proved to be troublesome.

**Comment by BadLucKWyvern** [comment]
THX a lot sir . I will report much as possible bugs from 1.9.4 for this
last patch
Really THX. Youre the best dev :D
