### ISSUE TITLE
Can't seem to search for a learnt item.

### ISSUE THREAD

**Issue by iNightmaree** [sinkillerj/ProjectE#1314]
I've read up on similar issues and noticed that the NEI search bar comes into play, so I've cleared that and tried doing another search for my item, yet it won't appear and a full game restart won't fix it. I'm certain the EMC value isn't too low to be detected and it should be showing, but it's not.

**Comment by Kolatra** [comment]
The tablet has its own search bar.

**Comment by iNightmaree** [comment]
Which is what I'm searching in.

**Comment by iNightmaree** [comment]
A server restart doesn't even seem to fix this.

**Comment by iNightmaree** [comment]
Also, a little sidenote. When I try searching for an item, it shows two silver ingots in the top middle area, and the middle of the tablet.

**Comment by iNightmaree** [comment]
Also, it seems even when I fully uninstall NEI the problems persists. Please can I get some help with this cus it's really annoying me.

**Comment by MaPePeR** [comment]
You have not really explained your problem up to a point where i understand what it is.

You are searching for something that you have learnt and it does not show up in the tablet?
Silver should never be in the inner ring of the table. 

If you put a "silver ingot" into the central slot of the Transmutation Tablet gui you used the "Lock slot" that will make it only show items with the EMC value of "silver ingot" or less. So if the thing you search for has more emc than silver you will not find it. Take the SIlver ingot out there.

**Comment by iNightmaree** [comment]
I'm so stupid..
