### ISSUE TITLE
[Bug] [1.9.4] Dark sword does not honor combat stuff

### ISSUE THREAD

**Issue by hron84** [sinkillerj/ProjectE#1317]
Dark sword is not behaves like how normal Minecraft swords work after the "Combat Update". Does not have AOE swing effect and no "cooldown". It is basically against how newer MC versions handle tools now. 

Affected versions: 

**Minecraft**: 1.9.4
**ProjectE**: 1.0.48

**Comment by escman1999** [comment]
willie hasn't gotten to that yet. either that, or no cooldown might be intended

**Comment by hron84** [comment]
@escman1999 hey, it's ok. I just reported a bug to track.

**Comment by williewillus** [comment]
Resolved in 1.10
