### ISSUE TITLE
Repair Talisman bug?

### ISSUE THREAD

**Issue by Toximisity** [sinkillerj/ProjectE#1320]
So I was playing in my world getting ready to start generating a good amount of EMC using the repair talismans, but when I go to put it into my transmutation table it crashes my game, this is take like 4 and it crashed every time. Something is either wrong in the mod configs or there is something conflicting between the mod list on the modpack. No idea. Ill try an energy condenser but for now I know the transmutation table is not a viable way to obtain multiple repair talismans.

**Comment by Toximisity** [comment]
Correction, I can no longer play my world because it has glitched the world out I will promptly burn it with fire

**Comment by MaPePeR** [comment]
There is nothing we can do to help you if you don't provide crash logs.

**Comment by Toximisity** [comment]
[crash-2016-08-08_12.02.23-server.txt](https://github.com/sinkillerj/ProjectE/files/407381/crash-2016-08-08_12.02.23-server.txt)

**Comment by Toximisity** [comment]
That is the latest crash I went ahead and deleted the item to prevent crashing but I am saddened I cannot use the repair talisman

**Comment by MaPePeR** [comment]
Congratulations you use a ProjectE version that was released Oct 8, **2015**

**Comment by Toximisity** [comment]
So I need to update the version basically?

**Comment by MaPePeR** [comment]
That would be a start, yes...

**Comment by Toximisity** [comment]
You wouldn't happen to have the link to the latest 1.7.10 download would you?

**Comment by MaPePeR** [comment]
https://minecraft.curseforge.com/projects/projecte/files

**Comment by Toximisity** [comment]
Thanks. Hopefully it will work.

**Comment by Toximisity** [comment]
Crashed again. Here's the Crash Logs
[crash-2016-08-08_13.26.34-server.txt](https://github.com/sinkillerj/ProjectE/files/407433/crash-2016-08-08_13.26.34-server.txt)

**Comment by MaPePeR** [comment]
Its an incompatibility with your Chisel version from Sep 16, **2014**.

Use [Chisel 2](https://minecraft.curseforge.com/projects/chisel/files)

**Comment by Toximisity** [comment]
It worked finally thanks a lot.
