### ISSUE TITLE
Crash when using project e 1.9.4 in 1.10.2

### ISSUE THREAD

**Issue by MrEvilCookie** [sinkillerj/ProjectE#1321]
[crash-2016-08-08_22.38.30-server.txt](https://github.com/sinkillerj/ProjectE/files/407600/crash-2016-08-08_22.38.30-server.txt)

**Comment by MaPePeR** [comment]
This crash has no mention of ProjectE

**Comment by sinkillerj** [comment]
Regardless 1.10 is unsupported, please wait for a 1.10 build.
