### ISSUE TITLE
[1.9.4] Unable to use Gem Armor offensive capabilities?

### ISSUE THREAD

**Issue by flamebirde** [sinkillerj/ProjectE#1322]
I've seen elsewhere on the issues page that others have also been unable to utilize the lightning strikes from the Abyss Helmet as well as the explosion from the chestplate. I have no idea how to use them, though - using R while holding nothing in my hand does not summon lightning, nor does pressing c or v do anything. Also, the wiki page for Gem Armor is... very sparse, and has little to no information besides how to craft. So, is it just that I don't understand how to use it, or is the feature in progress?

Incidentally, a tooltip explaining how to use these features would be welcomed. Tested with the 1.9.4-PE1.0.5B jar, running Project E and JEI, and forge 1.9.4-12.17.0.1976.

**Comment by williewillus** [comment]
you have to "ready" it

**Comment by williewillus** [comment]
it's also possibel they're disabled in the config

**Comment by williewillus** [comment]
60c984f
