### ISSUE TITLE
Transmutation Tablet Knoledge Vanishing.

### ISSUE THREAD

**Issue by BlackHoleFox** [sinkillerj/ProjectE#1326]
Hello, Ive recently made a 1.10 Forge server for me and some of my friends, we have the latest version of ProjectE installed and forge mod loader. It seems randomly all the items ive learned in my transmutation table vanishes completly, then i have to relearn it all. Can anyone help me with a possible fix please?

**Comment by sinkillerj** [comment]
1.10 is currently incompatible, if this continues to occur once a proper 1.10 version has been released we will be happy to look into the issue.
