### ISSUE TITLE
1.7.10 ProjectE lag problem

### ISSUE THREAD

**Issue by runescapejon** [sinkillerj/ProjectE#1327]
Hello i am having a lag problem with projectE 
http://pastebin.com/NXrBfhHL
` moze_intel.projecte.utils.WorldHelper.harvestVein`
any fixe's are coming?

**Comment by sinkillerj** [comment]
We are unable to provide support for Cauldron and other Bukkit API projects at this time. Please ensure that you are using one of the updated forks of Cauldron.

**Comment by runescapejon** [comment]
I am using Thermos, i had found out more information it seem when you right click a morning on a  Mar surface Rock click stright down, on the Mar's planet from Galaticraft Mod, it start to lag like sh*t

**Comment by runescapejon** [comment]
I had also tried this in singleplayer and it lag me so hard that i had to force shutdown minecraft

**Comment by artman41** [comment]
@sinkillerj 

> I had also tried this in singleplayer and it lag me so hard that i had to force shutdown minecraft

might want to check galacticraft compatibility if this is the case

**Comment by MaPePeR** [comment]
All it does is break a bunch of blocks at once... (At least in 1.7.10 - in >1.8 its broken)

**Comment by runescapejon** [comment]
yea @MaPePeR  right, It seem that it break a bunch of blocks, when i had right click straight down with a morning star well take a look https://gyazo.com/0392b99476ed92ce2813b6650862020c
i had to add more ram on to client
