### ISSUE TITLE
[1.7.10-PE1.10.0] Archangels's Smite Server Crash

### ISSUE THREAD

**Issue by Eremeir** [sinkillerj/ProjectE#1328]
I've read every issue thread here, adjusted the erroring options, reinstalled Forge from the ground up, disabled old saves, and disabled all other mods. Without fail, using the item will crash the server and disconnect all players. If there's something I'm missing, I can't figure it out.

I'm running on PE1.9.5 now, and the item works fine.

**Comment by sinkillerj** [comment]
Crash logs please, though normally its due to running a Cauldron fork with the missing library problem.

**Comment by Eremeir** [comment]
From Forge 1614

[crash-2016-08-12_16.09.28-server.txt](https://github.com/sinkillerj/ProjectE/files/416924/crash-2016-08-12_16.09.28-server.txt)

**Comment by sinkillerj** [comment]
Yea you def have a missing library, your best bet would be to rerun the Forge server installer to get a clean libraries folder.
