### ISSUE TITLE
<1.7.10>Transmutation table crashes ProjectE-1.7.10-PE1.10.0.jar

### ISSUE THREAD

**Issue by MCwind5542** [sinkillerj/ProjectE#1329]
When I search "v" or "eng" in the transmutation table, it just crash my game
Here is the crash log [crash-2016-08-13_23.52.27-client.txt](https://github.com/sinkillerj/ProjectE/files/416651/crash-2016-08-13_23.52.27-client.txt)
Here is my mod list
![image](https://cloud.githubusercontent.com/assets/21010558/17644275/80edda4a-61b4-11e6-9045-28327e891fb7.png)
![image](https://cloud.githubusercontent.com/assets/21010558/17644287/a5de4308-61b4-11e6-8758-3985f3712a14.png)

**Comment by MaPePeR** [comment]
How the hell can you live with that explorer font?! Did someone troll you with that? I'm not trying to read all that.

Please report the bug also to the creator of "com.builtbroken.mc.core.content.tool.ItemSimpleCraftingTool".

**Comment by Kolatra** [comment]
Yeah, we're working on fixing the ProjectE interaction.
