### ISSUE TITLE
[1.7.10 - PE1.10.0] Archangel smite crash on a forge server

### ISSUE THREAD

**Issue by utsudere** [sinkillerj/ProjectE#1330]
So I've tried installing a fresh forge server from their official site multiple times: latest and recommended versions and on two different PCs. Every time whenever I tried to use Archangel smite it crashed.
[crash-2016-08-15_13.33.46-server.txt](https://github.com/sinkillerj/ProjectE/files/417906/crash-2016-08-15_13.33.46-server.txt)

I know you've seen complaints about this countless times and I know you're going to tell me that it's missing libs, but: what should I do about it? I am running it on a freshly installed forge server and everything should be fine as you said in other threads about this problem. What are the libraries that are missing and where can I get them? Maybe there is an older version of fotge I should try and get libs from?
I should also add that Archangel smite worked perfectly fine on previous versions of PE, it's only happening on 1.10.0

**Comment by utsudere** [comment]
I've noticed that libraries folders for 1.7.10 and higher versions have differences and use different versions of jopt simple, does that have to do anything with the problem? For example 1.7.10 doesn't have java3d and jline folders while all higher versions have them. Already tired adding those in - didn't help.

**Comment by sinkillerj** [comment]
Ill look into this but I'm not sure why this is suddenly affecting vanilla servers.

**Comment by williewillus** [comment]
#1380
