### ISSUE TITLE
Something Wrong with Transmutation Table?

### ISSUE THREAD

**Issue by zzApotheosis** [sinkillerj/ProjectE#1331]
Java 1.8.0_102 64bit
Minecraft 1.10.2
MCP 9.32
Forge 12.18.1.2064
OptiFine_1.10.2_HD_U_C2

I compiled a version of ProjectE for Minecraft 1.10.2 based on the current source code in the repository. I noticed something weird about the Transmutation Table... When I **shift left-click** on the bottom slot of the inner circle in the Transmutation Table, the item count decreases to a red 0 and weird stuff happens to that slot... You can see in detail in this video.

https://drive.google.com/open?id=0B_wljXPJi507bGx2ZHlaSHRQcWs

**Comment by sinkillerj** [comment]
1.10 is currently not supported.

**Comment by zzApotheosis** [comment]
Looks like the new 1.10.2 builds are rolling out! This bug is still present, unfortunately.

ProjectE-1.10.2-PE1.0.6B
