### ISSUE TITLE
Adding new mod to server that uses nbt wipes data in transmutation table

### ISSUE THREAD

**Issue by kdx7214** [sinkillerj/ProjectE#1332]
Have tried on 1.9.4 and on 1.10.2.   Basic setup with only forge + projecte.  Add items to table, exit, and add another mod that uses nbt (I chose the chickenbones mods but have also replicated with botania, ender io, and others).   When you next log in your table is empty and all emc is lost.

**Comment by williewillus** [comment]
what do you mean "uses nbt"?

**Comment by kdx7214** [comment]
Mods that use nbt data and write it to either the play data file (or equivalent in 1.8.9+) or to the world.   So for example, you could add Morpheus after the fact and not lose data, but if you add Ender I/O, CodeChickenCore/ChickenChunks/EnderStorage, and the like you will lose the contents of your transmutation tablet.   Not sure why though - but that seems to be the pattern I've seen.

**Comment by williewillus** [comment]
Cannot reproduce with EnderStorage

**Comment by sinkillerj** [comment]
Logs of this happening wouldn't hurt, could help determine the true problem if there is a glaring error.

**Comment by kdx7214** [comment]
It will take me a couple of days - I'm having surgery in a few hours (in the morning) and will be out for 3-4 days.   I did forget to mention that this is in SMP (on a server).   Will post logs as soon as I get back and can get them for you :)

**Comment by MaPePeR** [comment]
Maybe also get a before and after version of the player.dat file. 
Good luck for your surgery.

**Comment by sinkillerj** [comment]
A 1.10 build will be out soon, and I suspect it will fix this issue, if not please feel free to reply and I will reopen the issue.
