### ISSUE TITLE
Server crash on use of Archangel's Smite

### ISSUE THREAD

**Issue by Lightningwing92** [sinkillerj/ProjectE#1333]
Crash log here: 
[crash-2016-08-15_21.50.37-server.txt](https://github.com/sinkillerj/ProjectE/files/419508/crash-2016-08-15_21.50.37-server.txt)

Minecraft version - 1.7.10
Forge version - 10.13.4.1614
Mod version - PE1.10.0

Things I have tried:
Installing Java 3d, adding a CLASSPATH variable mapping to the jar files included there as that's where the libraries that it's missing are from
Reinstalling Java
Recompiling my forge server and trying that all over again
Testing it with just Project E, no other mods
Downgraded forge to version 10.13.4.1558, same crash report/issue
Using the JAR and EXE installer for forge version 10.13.4.1558 and 10.13.4.1614

**Comment by sinkillerj** [comment]
#1330
