### ISSUE TITLE
[Enhancement] Stop Gem of Density from converting items that haven't been learned

### ISSUE THREAD

**Issue by charlesbevans** [sinkillerj/ProjectE#1335]
My gem of density ate some stuff I hadn't learned yet. I'd rather it either didn't convert unknown items, or added them to the player's knowledge when converting them. One option may be to place a special item in the inventory with the gem to enable learning. This could also be used on condensers.

**Comment by sinkillerj** [comment]
IMO thats more of a addon feature, a mk2 gem if you will.

**Comment by charlesbevans** [comment]
I see your point. The condenser is indiscriminate, so the ring should be too. I'll just make a bunch of whitelist rings and keep them in a bag. Thanks.
