### ISSUE TITLE
Mod not found in curse launcher, can you mark latest download as 1.10.2 compatible

### ISSUE THREAD

**Issue by PrinceOfAmber** [sinkillerj/ProjectE#1337]
I am trying to include this in a 1.10.2 modpack, but it doesnt exist in the launcher, wont let me search or add it.

**Comment by williewillus** [comment]
it isn't 1.10 compatible, some things are super broken in the current public 1.9 build in 1.10.

We're hoping to get a 1.10 build out soon, hang in there.
