### ISSUE TITLE
Intended?

### ISSUE THREAD

**Issue by opum2** [sinkillerj/ProjectE#1338]
In ProjectE 1.8.0 for 1.7.10, the Stored EMC in the Swiftwolf's Rending Gale (Or any stored EMC) had a comma in the stored EMC. In all the new versions it doesn't have a comma and also uses decimals. Is this intended?

If not, I think it looks better with the comma when hovered over.

Thanks!
~opum2

**Comment by williewillus** [comment]
It depends on your locale iirc

**Comment by opum2** [comment]
What do you mean?

**Comment by opum2** [comment]
Oh I see. but it happens on Windows and Mac.

**Comment by williewillus** [comment]
Locale as in Language settings

**Comment by opum2** [comment]
From the ProjectE mod?

**Comment by williewillus** [comment]
Your Minecraft language setting

**Comment by MaPePeR** [comment]
Or your Java/Operating System Language Settings

**Comment by opum2** [comment]
But it was working properly until an update.
