### ISSUE TITLE
Cannot put items on Dark Matter Pedestal

### ISSUE THREAD

**Issue by PrinceOfAmber** [sinkillerj/ProjectE#1339]
Mod version ProjectE-1.10.2-PE1.0.6B

Tried with the Life stone, mind stone, black hole band.  They wont enter the pedestal.  No crash just nothing happens.

**Comment by escman1999** [comment]
can you open the pedestal's gui?

**Comment by williewillus** [comment]
cannot reproduce.

open the gui with shift right click with emtpy hand and then put the thing in the gui.

it's a terrible system I know but it's to be the same as ee2.

I'm probably gonna change it to just be right click the block to insert/withdraw, but that's the future

**Comment by williewillus** [comment]
No more gui so no more problem :D
