### ISSUE TITLE
Right click functionallity on Picks not working [Sorry working]

### ISSUE THREAD

**Issue by MrAmericanMike** [sinkillerj/ProjectE#1340]
From what I see on the configs, it should work, unless I forgetting something

    # If set to true, disables all radius-based mining functionaliy (right click of tools) [default: false]
    B:disableAllRadiusMining=false

But when I try in game, holding a Dark Matter or Red Matter Pick, I right click, but no ore is collected.

Forge 12.18.1.2068
ProjectE-1.10.2-PE1.0.6B

PS: Delete this, I'm derping.

    # Instead of vein mining the ore you right click with your Dark/Red Matter Pick/Star it vein mines all ores in an AOE around you like it did in ProjectE before version 1.4.4. [default: false]
    B:pickaxeAoeVeinMining=true

That made it work.... But I'm confuse what the above config is for then :p Thanks.

**Comment by MaPePeR** [comment]
@MrAmericanMike You can close the issue yourself if you found out its invalid.

**Comment by williewillus** [comment]
If that config is false: The pick vein mines any ore you click directly

If it's true: The pick finds nearby ores for you then veinmines them

**Comment by MaPePeR** [comment]
@williewillus i think he was confused about the `B:disableAllRadiusMining=false`-Option

**Comment by MrAmericanMike** [comment]
Thanks ;) Got it.
