### ISSUE TITLE
[1.7.10] Thaumcraft Saplings and Harvest Goddess Band

### ISSUE THREAD

**Issue by Zsashas** [sinkillerj/ProjectE#1343]
The band works to make Greatwoods grow faster, but doesn't work on Silverwoods. This may be intentional, as Silverwoods can't be bonemealed, but then again, neither can Greatwoods...

The more noticeable issue, however, is when using the Band's feature to plant saplings. With Greatwood Saplings in my inventory, right-clicking on grass with the Band plants as many as it can, all right next to each other. However, with Silverwood Saplings in my inventory, two things:

1: Right-clicking on grass does nothing.

2: Right clicking on a placed Silverwood Sapling itself with the Band places every sapling I have, but turns them into Greatwood Saplings.

**Comment by williewillus** [comment]
For the growing, it just simulates bone meal so that's a silverwood thing.

As for the planting that's probably a bug
