### ISSUE TITLE
Can't create new world [1.7.10]

### ISSUE THREAD

**Issue by Goatzzz** [sinkillerj/ProjectE#1345]
When trying to create a new world, it will kick me to the main menu, and the new world will be unplayable. There is no crash report to be found.

Mod list:
Treecapitator
MB Battlegear 2
applied energistics 2
backpack
Better Builders Wands
Carpenter's Blocks
Chisel
chocolate Quest
Clay Soldiers
Code Chicken Core
CoFHCore
CustomNPCs
Decocraft
dense ores
iron chest
Jabba
journeymap
Loot Bags
Mantle
Modular Powersuits
more armor
Mr Crayfish Furniture
Nether Ores
NEI
Numina
Pam's Harvestcraft
Roguelike Dungeons
SAPManPack
Tinker's Construct
TiC Tooltips
Tinkers Defense
VeinMiner
WeaponMod
ProjectE

I can perfectly create a world if I remove ProjectE, so it must be the issue

**Comment by MaPePeR** [comment]
Version of ProjectE and Chisel?

**Comment by Goatzzz** [comment]
I've tried all 1.7.10 versions of ProjectE and I'm using Chisel 3 version 1.5.7

**Comment by MaPePeR** [comment]
Disable the chisel mapper in the ProjectE mapping.cfg

**Comment by Goatzzz** [comment]
The mapping.cfg file is empty, how do I disable it?

**Comment by MaPePeR** [comment]
Try to remove chisel and start the game without it. 
That should generate the file.

**Comment by sinkillerj** [comment]
Chisel 3 is a joke, your best bet on Chisel for 1.7 is: https://minecraft.curseforge.com/projects/chisel/files
