### ISSUE TITLE
Support for automation

### ISSUE THREAD

**Issue by Mach12** [sinkillerj/ProjectE#1346]
It would seem it is currently impossible to automate extraction of a Condenser's products. I tried multiple things without success:
- Actually Additions' Phantomface does not see a condenser as a valid inventory
- From the same mod, the item laser relays do not transfer things produced by a condenser
- Inductive Automation's item pipes do not connect to the condenser either

Whether this is intended behavior or not is beyond me, but I think it should be a thing the player can do.

**Comment by MaPePeR** [comment]
Try some other item conduits... EnderIO for example...

**Comment by Mach12** [comment]
No dice.

Here's a setup:

![2016-09-07_23 25 51](https://cloud.githubusercontent.com/assets/3253035/18329169/7be9ecee-7552-11e6-925f-c70ab3225595.png)

- Extracting pipe is set to extract and being always active, inserting pipe is set to insert, both are on green channel, no filter installed
- MK3 glowstoned collector, MK2 condensator, gathering redstone dust inside at a steady rate
- Right chest is still empty

**Comment by escman1999** [comment]
you need an antimatter relay between the collector and condenser

**Comment by williewillus** [comment]
That doesn't have to do with item extraction though

**Comment by williewillus** [comment]
You need to use a mod that supports the new capability inventory system and use the right sides (but afaik they shouldn't have changed)

**Comment by Mach12** [comment]
Well I also tried Extra Utils to no avail...

Actually of all the things I tested, the only functional one is the vanilla Hopper. Are you sure there is any mod that uses the new Capability system AND provides item transport? Because restraining access to your stuff to mods that do seems like basically denying access to all mods so far.

**Comment by Mach12** [comment]
Alright, I just got it. You can only extract items from the bottom... All methods work from the bottom. All om them.

But it seriously calls for documentation of some kind. The condenser is no furnace, I'm pretty sure there's only one place in the condenser where input is accepted, same for output. You could just accept both on every side.

**Comment by williewillus** [comment]
The condenser mk2 has two different "inventories". The left one (input) is accessible from all sides, the right one (output) only from the bottom. 

I can't bind multiple inventories to the same side so "accepting both on every side" isn't really viable.

**Comment by williewillus** [comment]
Bottom was chosen for output so vanilla hoppers can extract from the output easily

**Comment by MaPePeR** [comment]
I think both sides should be available from all sides...
And if the new Inventory-Api does not allow that that is very bad...
Can we make it a single inventory, that has access based on slotnumbers/ranges or something like that?

**Comment by Mach12** [comment]
> EDIT: There is this line which indicates there IS a combined version of the inventories? why can't we use it for all the sides?

It actually sounds legit IMO. It seems the condensator is already two-sided if a device pulls from the block but gives `null` for a side.

Assuming it redirects inputs to the left and outputs to the right, that make so much more sense!

**Comment by williewillus** [comment]
If i tell the TE "give me the IItemHandler for side DOWN" I can't return two of them. Sure I could concat the input and output together and return them both for every side but then each individual inv now needs additional validation rules and mods will uselessly try pulling things out of the input on every attempt

**Comment by MaPePeR** [comment]
So what do you do for side == null there, then?
It looks like it creates a mixed/combined  I item handler already....
