### ISSUE TITLE
[1.7.10] World won't load with custom modpack

### ISSUE THREAD

**Issue by spharix** [sinkillerj/ProjectE#1347]
EDIT:I'm completely blind, I managed to miss literally the last issue that had this exact problem and the fix within that issue. Very sorry.

As the title says, the world won't load when trying to create a new world with my custom modpack, which includes quite a few mods. It will start creating it and the log says it's loading in but it looks like a fatal error occurs right before it does so. Pastebin attached below. I'm not tech savvy at all so I don't know where or what to look for. Sorry if this is something simple or a mistake on my part - but I'm pretty certain it's Project E or an incompatibility with Project E as removing it lets me play just fine.

Thanks for any help and your time, it is much appreciated.

http://pastebin.com/9d1MsqJw

**Comment by MaPePeR** [comment]
Update your chisel to a version that is not 2 years old.

**Comment by MaPePeR** [comment]
We really should revisit that and prevent this from happening, though. I fear we will still get reports for this incompatibility in 10 years.

**Comment by spharix** [comment]
Haha, that would be a pain. I appreciate you not being snappy, it must be hard hearing the same complaint all the time. Thanks for the help :)

**Comment by sinkillerj** [comment]
Its on the todo list before 1.7 is completely killed off.
