### ISSUE TITLE
Unable to put targeted item in a condenser

### ISSUE THREAD

**Issue by jaz3001** [sinkillerj/ProjectE#1349]
in my current 1.10.2 world, i have come across an issue where i am unable to place items into the storage area of a condenser, i am however, able to take items out and change the condenser target. This issue applies to importing/exporting items by hand, pipes and hoppers. I am running Forge 12.18.1.2076 and ProjectE-1.10.2-PE1.0.6B

**Comment by williewillus** [comment]
Mk1 or 2

**Comment by jaz3001** [comment]
so far, only tested mk1

**Comment by Mach12** [comment]
This is intended behavior.
The condenser is not a storage device, and its inventory will only store its own output.

If you want a big storage device, use an alchemical chest.

**Comment by MaPePeR** [comment]
you just cannot put stuff without an EMC value in... items with emc value should be inserted just fine.

**Comment by jaz3001** [comment]
Mach12, i'm not trying to store stuff, i'm trying to condense stuff
MaPePeR i'm not trying to put stuff in that don't have EMC values
Williewillus, i just tested, Mk2 doesn't have the issue

**Comment by jaz3001** [comment]
After further testing, it seems i cannot place items that are the same as the tageted item in a condenser, as i said in my last comment, if this is intended, a config to change this functionality would be nice

**Comment by MaPePeR** [comment]
stating that in the first comment would have made this a lot easier, you know...

**Comment by jaz3001** [comment]
well i just noticed this now :/

**Comment by williewillus** [comment]
this is intended

**Comment by MaPePeR** [comment]
There is no real reason for this though... and apparently its only restricting and confusing. So i would say we might remove that. (And it wasn't always the case for EE2)

**Comment by williewillus** [comment]
Okay, I don't mind. makes the code simpler :P

**Comment by MaPePeR** [comment]
Exactly :D

**Comment by williewillus** [comment]
actually, hm

people have used that rejection before in useful ways though. Like if you have a pipe line running past a bunch of condensers you wouldn't want a diamond to go into a condenser that's already targeting diamond wouldn't you?

**Comment by MaPePeR** [comment]
Hmm... agreed :/

**Comment by williewillus** [comment]
The existing behaviour will be retained

**Comment by MaPePeR** [comment]
I don't know if it was mentioned before, but another way would be to allow it with the gui, but disallow it with automation. But that might be even more confusing 🙁
