### ISSUE TITLE
not able to assign emc values in game 

### ISSUE THREAD

**Issue by goodmangammering** [sinkillerj/ProjectE#1351]
so i have been working on a modpack and somehow came across a problem where the "/projectE setemc #" results in saying this in the log https://gyazo.com/a4bebc4106c22de2fdc8efb97a4922c4 any advise or help would be greatly apreciated (also this is in 1.10.2)

**Comment by Mach12** [comment]
Are you holding the item of interest in you main hand? You need to or ProjectE won't understand.

On a side not I do believe the mod has trouble doing his thing if the item is already registered and only has different NBT data, but it doesn't sound like it's that.

**Comment by goodmangammering** [comment]
yeah i do have the item in my hand and ive looked through the custom_emc.cfg and custon_emc.jason to look for if it was already there and turned up nothing

**Comment by goodmangammering** [comment]
https://gyazo.com/581d4a23ee74b4603fada1b150dc0791

**Comment by Mach12** [comment]
Alright, I got two things I can think of: Either PE doesn't like you trying to register a Forge bucket (they *are* dissociated by NBT only iirc, and fluids are not exactly a stable thing at the moment), or I'd need to investigate what broke in the code.

Speaking of the latter, is your ProjectE up-to-date?

**Comment by MaPePeR** [comment]
this might be caused by an item in your custom-emc file that is not present anymore, because you removed a mod or something like this. I don't know anything about that code, though.

**Comment by Mach12** [comment]
My guess is your PE is at least not up-to-date, because the code line shown in your stacktrace can't possibly give off that error according to the code on github. (It points line 150 of CustomEMCParser which is literally just a curly bracket at the moment).

Try updating?

**Comment by MaPePeR** [comment]
@Mach12 You are checking the wrong branch. This error is with 1.10.x: https://github.com/sinkillerj/ProjectE/blob/c021719/src/main/java/moze_intel/projecte/config/CustomEMCParser.java#L150

And this line can NPE if `entry.nss` is `null`

**Comment by goodmangammering** [comment]
ok so first ... it errors with everything i try to assign emc to ... im on the latest 1.10 version and i checked through for emc values assigned no longer exsisting items and i had removed those when i removed the mod

**Comment by goodmangammering** [comment]
ok so i figured out that the reason for its problem was that apperently immersive engineering borked the whole thing ...
its fixed now that ive diasbled the mod

**Comment by sinkillerj** [comment]
We are going to need logs to provide proper assistance, they contain the actual error. The screenshots just show that there was an error, but with no information we can use to determine the true cause.
