### ISSUE TITLE
[1.10] Archangel Smite auto aiming does not hit the ender dragon

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#1352]
Maybe not use the Bounding box, but the actual hitbox for calculating the "where to hit"?

**Comment by Mach12** [comment]
This might be harder than it sounds.

The ender dragon is the mob that displays an annoying phenomenon the most: a huge difference between the recorded bounding box and where you can hit him from. The actual hitbox you can hit the dragon in is rather arbitrary it seems, some people even complain about arrows bouncing off the dragon like he has godmode.

**Comment by williewillus** [comment]
the arrows just aim for posX/posY/posZ

but the dragon is actually made of several Entity objects grafted together into one superentity so idk how it interacts with that

**Comment by MaPePeR** [comment]
The problem is, that the entity bounding box is empty at the position the arrows aim for.
So the arrows just follow the dragon around

**Comment by Mach12** [comment]
I guess aiming for the center of the bounding box is kind of a good deal?

Or maybe use the new NoGravity tag to make the arrows go straight? I don't know if the latter is actually a thing tbh.

**Comment by williewillus** [comment]
it just needs to filter out entities with unhittable boxes

**Comment by MaPePeR** [comment]
This is the code we use for the target location:

```
Vector3d targetLoc = new Vector3d(target.posX, target.getEntityBoundingBox().minY + target.height, target.posZ);
```

If posY is not centered in the box, we should only add half the height of the entity to hit the head. 
(or add nothing to hit the center) 

I actually doubt that the pos is centered. I would guess it's one of the lower corners of the model, but I have nothing to back up that claim.

**Comment by williewillus** [comment]
Oh, yeah. The posY is the bottom

**Comment by williewillus** [comment]
b5c35b4
