### ISSUE TITLE
Ender IO not working with Energy Condenser MK2

### ISSUE THREAD

**Issue by Zettt** [sinkillerj/ProjectE#1353]
Extracting items (and I think inserting) is not working with Ender IO. Minecraft version 1.10.2. Playing on FTB Unstable.

**Comment by MaPePeR** [comment]
I think in the 1.10 version you have to use the bottom and top side to input/extract.

This is a duplicate of #1346 

Still don't know why we cannot support this anymore, though. :/

**Comment by Zettt** [comment]
Yes, possibly related. Tested, and confirmed. Extracting from the bottom works. And inserting from side and top. Thank you!
