### ISSUE TITLE
Philosopher's Stone Bug

### ISSUE THREAD

**Issue by Alaziel** [sinkillerj/ProjectE#1356]
I'm playing a custom private 1.7.10 mod pack I made that includes Project E. When I go to craft anything with the Philosopher's Stone, it is consumed when I craft the item. I'm finding it really annoying to have to re-craft the stone each and every time. I'm not quite sure what else to put here, so if someone could help me, I would be very grateful.

**Comment by sinkillerj** [comment]
It sounds like one of your mods is modifying crafting behaviour. I would like to see a log which includes you crafting something with the stone to see if anything is glaring.

**Comment by Alaziel** [comment]
Where do I find these logs? I'm not quite sure.

**Comment by sinkillerj** [comment]
These would be in your packs folder under "logs", this can be found in the same place you find the mods folder.

**Comment by Alaziel** [comment]
Ok. I'll get right on it.

**Comment by Alaziel** [comment]
Will this work?
[Log 10-4-16.txt](https://github.com/sinkillerj/ProjectE/files/509905/Log.10-4-16.txt)

**Comment by williewillus** [comment]
Whatever crafting table you're using does not handle container items properly (can it craft cake properly and give you back the bucket from the milk bucket?)
