### ISSUE TITLE
Almos lost every thing in transmutation table

### ISSUE THREAD

**Issue by Nitrof1er** [sinkillerj/ProjectE#1359]
I'm on a single player map on FTB infnity modpack. I add projectE and thaumic exchage. 

Sometime, my game crash and when I reload, almost every things in my transmutation table, exept EMC and some items such energy condenser, anti-matter relay and thaumcraft shards. The differents fuels and majority of items from mods disapear.

**Comment by sinkillerj** [comment]
Sounds to me like it crashed during a save, not much we can really do.

**Comment by Nitrof1er** [comment]
There is something I can do?

**Comment by sinkillerj** [comment]
Relearn the items using creative, restore a backup if you have one, or use the tome to learn everything in the game.
