### ISSUE TITLE
Wiki for compiling the mod

### ISSUE THREAD

**Issue by djoey123** [sinkillerj/ProjectE#1361]
Can someone tell me how to build the source to a .jar file

can find it anyhwere how i can do it

**Comment by MaPePeR** [comment]
its juts compiled like every other ForgeGradle based mod...

you clone the repository and then run `gradle setupDecompworkspace` and then `gradle build` (these are from my head, so they might be not quite right... but close)

**Comment by sinkillerj** [comment]
Please see Pahimars Lets Mod series on YouTube if you need help with modding.
