### ISSUE TITLE
EMC values as longs rather than ints

### ISSUE THREAD

**Issue by Sciencentistguy** [sinkillerj/ProjectE#1364]
Currently, when you have over 2.147 billion EMC in a stack the values do not show. In some late-game worlds,  2 billion EMC is not that much, whereas if the values were longs rather than ints the cap would be over 9 quintillion, which would be much harder to reach.

**Comment by williewillus** [comment]
Not happening anytime soon

**Comment by MaPePeR** [comment]
I think it is still something we should aim for. Getting rid of the doubles, especially.

**Comment by sinkillerj** [comment]
Closing as we dont need another 500 discussions about this. We are aware of EMC cap problems and may fix them in the future, but this will require a major overhaul.
