### ISSUE TITLE
Crash When Breaking Grass/Leaves via Harvest Goddess Band

### ISSUE THREAD

**Issue by Iyasenu** [sinkillerj/ProjectE#1368]
Well, the title's just a guess on my part as to the reason.
I was running around an NPC village, and I was at using the HGB's auto-harvesting effect on the planted crops, as well as running around the outskirts having the band break the grass for me.

I then approached a tree to find out that the HGB also breaks leaves, so I went on to do that to a second tree, when the game crashed, and now crashes upon trying to re-enter the world.

In my hotbar I had an activated Watch of Flowing Time (fully charged) and an activated HGB, along wtih some Aeternalis Fuel Blocks and Diamond tools, if that's worth mentioning.

**Crash Log:** http://pastebin.com/5nu49iuF

**Comment by williewillus** [comment]
925bcd1
