### ISSUE TITLE
[1.7.10] Watch of Flowing Time and EnderIO

### ISSUE THREAD

**Issue by djoey123** [sinkillerj/ProjectE#1369]
The watch of Flowing Time on a pedestal doesnt boost machines of the mod EnderIO

**Comment by MaPePeR** [comment]
EnderIO introduced a config to allow the acceleration of Machines. Its probably turned off?

**Comment by djoey123** [comment]
It is enabled what i see.

Config:

misc {
    # Allows machines to run faster if another mod speeds up the tickrate. Running at higher tickrates is unsupported. Disable this if you run into any kind of problem.
    B:allowExternalTickSpeedup=true

    # If true, quite clear glass will connect textures with fused quartz. [default: false]
    B:clearGlassConnectToFusedQuartz=false

    # If true, quite clear glass will use the fused quartz border texture for the block instead of the white border. [default: false]
    B:clearGlassSameTexture=false

    # Enables emptying vanilla water bottles without breaking the bottle. In combination with a water source block this allows duping of water without cost.
    B:enableWaterFromBottles=true

    # Maximum level of XP the killer joe can contain.
    I:killerJoeMaxXpLevel=2147483647

    # Separates wither and normal skeletons into different entities, enables the powered spawner to treat them differently [EXPERIMENTAL - MAY CAUSE ISSUES WITH OTHER MODS]
    B:replaceWitherSkeletons=true

    # Id of liquid XP fluid (WARNING: only for users who know what they are doing - changing this id can break worlds) - this should match with OpenBlocks when installed [default: xpjuice]
    S:xpJuiceName=xpjuice

    # Maximum level of XP the xp obelisk can contain.
    I:xpObeliskMaxXpLevel=2147483647
}

**Comment by MaPePeR** [comment]
Did you enable the pedestal?

**Comment by djoey123** [comment]
Ofcourse I have enabled the pedestal lol

**Comment by MaPePeR** [comment]
So it has burning flame particles around it?

**Comment by djoey123** [comment]
Yeps

**Comment by djoey123** [comment]
It doesnt work on inscribers too the mod Applied Energistics 2, do I need too make a new issue for it?

**Comment by sinkillerj** [comment]
No need for a second issue.

**Comment by djoey123** [comment]
Okey :)

U know why it isnt working?

**Comment by williewillus** [comment]
Make a new report if this happens in 1.10+
