### ISSUE TITLE
(Suggestion) linked klein stars

### ISSUE THREAD

**Issue by killmetohell** [sinkillerj/ProjectE#1370]
Just like title says linked klein stars to have or to add an item that have klein stars that are linked to each other it would make so less annoying going back to where ever have your emc generation located just to get emc and less need to add collectors and/or recharge klein stars for items/blocks that require emc.
My question is that why no one even bother to add this as a add-on oh well.

**Comment by sinkillerj** [comment]
I cant see this as a mainline feature, you will need to contact a addon author or make an addon yourself.
