### ISSUE TITLE
[1.10.2] Repair Talisman blacklist config

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [sinkillerj/ProjectE#1375]
The **projecte:item.pe_repair_talisman** breaks the functionality of the canteen from the Tough as Nails mod, [https://minecraft.curseforge.com/projects/tough-as-nails]. That mod item uses durability to track charges remaining, the talisman resets the durability. Please implement blacklist config for talisman to ignore items.

**Comment by sinkillerj** [comment]
They need to set norepair on their item so repair mods dont touch it.

**Comment by Rumpelstiltskinny** [comment]
Thanks, referenced here: https://github.com/Glitchfiend/ToughAsNails/issues/131
