### ISSUE TITLE
Server Sync Issue

### ISSUE THREAD

**Issue by Medusalem** [sinkillerj/ProjectE#1376]
When Playing with Project E on our Server if Logging in after restart of the server one have to relog again to get learned Recipes in the Table! It's not crashing or something, it's just that one has to relog before getting acces to his learned items!

Testing in Singelplayer i was not able To reproduce it, so i think it has to be something with syncing betwen Server and Client...

**Comment by williewillus** [comment]
can't reproduce

**Comment by sinkillerj** [comment]
We need alot more info then this, your MC version, server logs, etc. Please note that we only support plain forge servers, if you are using something such as cauldron we cant help you.

**Comment by Medusalem** [comment]
It's a normal Forge Server, We have the Mod itself added in with some Other mods, You can find the Modpack on Curse, its caled Dionysos, Mod version is 1.10.2-PE1.0.6B runing on minecraft 1.10.2 and forge 12.18.2.2170 Reading server console of forge it does not seam to do something different from loging and reloging, they just apear!

**Comment by KindarConrath** [comment]
I'm experiencing something similar, seems if I wander around for quite some time then update the table (by teaching it anything) it syncs, but when I load in, I often have a blank tablet. No errors on the log or anything.

**Comment by AlphaKintari** [comment]
Also experiencing this - seems to desync when the chunk gets loaded or unloaded.  I'll try and get logs, but since I started keeping that area checkloaded it occurs much less frequently.  Also, if you unlearn and then relearn the same item, it resyncs without issue.

**Comment by williewillus** [comment]
can someone reproduce it in single player or is it just on a server?

**Comment by KindarConrath** [comment]
I'll copy my server world into single player and test in a bit

**Comment by williewillus** [comment]
Found it.
EMC data was being sent after knowledge, which causes the client to think all of the knowledge is invalid since it doesnt have a value

**Comment by williewillus** [comment]
25ea8ee

**Comment by sandalle** [comment]
Confirmed fixed in ProjectE 1.10.2-PE1.1.0B, thank you!

**Comment by goreae** [comment]
I've been having this problem in 1.1.0B actually. Whenever I change dimensions, modded or no, my EMC data is wiped for a little bit. Seems like learning something I didn't previously know (or unlearning something and relearning it) refreshes it.

**Comment by williewillus** [comment]
Fixed, thanks

**Comment by AcksomMatheus** [comment]
ProjectE ProjectE-1.20.1-PE1.0.1.jar. Server Forge. I have the same problem, when I disconnect from the server and log in again, the transmutation table resets.

**Comment by AcksomMatheus** [comment]
Problem found.
A plugin "Skin Restorer" was causing the issue.
I got an idea that maybe the initial logging in onto the server loaded my EMC stuff, but when the SkinRestorer kicked in to load my skin it desynced, and was only fixable by killing myself.
Dunno if thats what actually happened but the problem was found.
Just remove the plugin.

**Comment by sinkillerj** [comment]
This issue is years old, and we do not support cracks. Buy the damn game.
