### ISSUE TITLE
Dark matter pickaxe bug

### ISSUE THREAD

**Issue by cepajev** [sinkillerj/ProjectE#1378]
Hi, so i played a game and recently I got dark matter pickaxe and decided to try it out.I remember shift right clicking using pickaxe on ores acts as veinminer, so I tried it on redstone ore I found underground.Game suddenly froze, minecraft ate all my game memory (3 gigs) and after like 5 minutes it unfroze, I saw like few hundreds stacks of redstone laying on the ground.I don't know what happened but I think this was caused by mod not having lootballs as I had no such a problem in the past.Unfortunately after that game kept frozing and then crashing making impossible to get screen shot or anything.I really like this mod , and I would like to play it without any game breaking bugs like described above...
Also I tried that on superflat world and same thing happened.
I have no other mods installed than forge and projecte.

**Comment by sinkillerj** [comment]
Minecraft version, PE version, logs, etc please.

**Comment by cepajev** [comment]
Nevermind, I tried 1.10 version and it works perfectly without anything similar to 1.9, I guess I had to upgrade to 1.10 lol
