### ISSUE TITLE
1.7.10 Server

### ISSUE THREAD

**Issue by Rectorian** [sinkillerj/ProjectE#1380]
so, playing on a modded server with latest version of projecte for 1.7.10, and whenever you try to use archangels smite, it crashes. Here's the crash log. Easily reproducable and happens every time. Also, when in singleplayer survival, it works just fine. Hope this helps. It seems to be missing a class. If you could fix it or just help in general, that'd be awesome. Thanks!
Here's the log:
[crash-2016-10-17_22.08.39-server.txt](https://github.com/sinkillerj/ProjectE/files/535193/crash-2016-10-17_22.08.39-server.txt)

**Comment by zzApotheosis** [comment]
Can confirm with this crash:
https://drive.google.com/open?id=0B_wljXPJi507c3VONWx0U21COHM

From the looks of it, PE can't import/find the class javax.vecmath.Tuple3d on a Forge server, but works fine on Single Player.

**Comment by williewillus** [comment]
Are you using cauldron/thermos/some other non-usual server?

**Comment by Rectorian** [comment]
This is a Regular minecraft 1.7.10 server from the legitament minecraft website. Thanks for the help so far!

**Comment by williewillus** [comment]
When you run the forge server, is the vanilla server jar in the same folder as well?

**Comment by Rectorian** [comment]
Yes, it is.

**Comment by Rectorian** [comment]
The vanilla forge jar is within the same folder as the forge server jar.

**Comment by williewillus** [comment]
there are libraries missing that should be part of a standard forge install. try reinstalling and ensuring vanilla jar is there

**Comment by Rectorian** [comment]
So, its been a while, but i finally got around to reinstalling it, and it still doesn't work, also the fact that someone can recreate it means that he's using libraries that aren't in this forge version, or they removed these libraries. I do still need to test to see if an update version that he just released will fix this yet. Thanks for the help so far.

**Comment by Rectorian** [comment]
One last thing, I have been running it using an external custom launcher to allocate more ram to the server. could this cause any issues? Any help is Appreciated. Thanks!

**Comment by williewillus** [comment]
that launcher is not downloading the correct libraries properly. Use the forge installer
