### ISSUE TITLE
project e "light"

### ISSUE THREAD

**Issue by ImelchorI** [sinkillerj/ProjectE#1384]
i wonder if it was possible to add a config to disable larger portions of the mod.

for example for certain modpacks, it might be useful to disable everything but 

- the philosophers stone 
- transmutation table
- emc batteries
- energy condensers
- alchemical chests
- alchemical bags

project e has the tendency to completely overpower progression systems of other mods, due to its powerful items and its own mechanisms for emc farms (like energy collectors).

however in certain modpacks, especially skyblock packs, the basic funtions of this mod could be very great and fun in combination with other mods progression and automation mechanisms.

the idea is basically that project e can serve as a way to gain basic resources similar to ex nihilo in worlds, where they are only possible to aquire by generation, without its items and mechanics completely breaking and overpowering other mods at the same time.

so it would be great if there was a "project e light" config, that basically turned everything off but the very basic blocks and items for transmutaion, and disable all additional functions like dark/red matter tools, pedestals etc.

**Comment by MaPePeR** [comment]
did you take a look at the config options already present in ProjectE?
Did you try to disable Items with MineTweaker?

**Comment by ImelchorI** [comment]
there are some configs to disable a couple of blocks, but most of the really overpowered stuff cant be directly disabled.

yes, minetweaker would be a possibility, but having to write a minetweaker script to disable almost every recipe in the mod would be a bit excessive imo.

**Comment by MaPePeR** [comment]
Its not that hard. It will be one of your easiest challenges when creating a modpack.

Having a "project e light"-config option, that basically disables everything would be a bit excessive imo.

**Comment by ImelchorI** [comment]
its really just a config and not that excessive. a lot of mods have th feature to pretty much disable every single one of their blocks and items, or individual larger portions of it. considering that even with the most basic items and blocks, youd still have the most important thematic function of the mod, i dont think its crazy to ask for a config like that.

**Comment by williewillus** [comment]
There are configs for lots of things already. As someone who absolutely hates adding configs, what exact thing are you trying to disable that you can't already?

**Comment by ImelchorI** [comment]
everything except the things listed and the couple of blockjs you can disable.

its really a lot. the armor, weapons and tools for starters, the rings, a lot of the utility items. there are only a couple of blocks you can straight up disable in the configs.

**Comment by williewillus** [comment]
Remove the recipes with minetweaker
