### ISSUE TITLE
Thaumcraft world transmutation

### ISSUE THREAD

**Issue by jem991** [sinkillerj/ProjectE#1385]
I try to add inworld tranmutation greatwood sapling to silverwood sapling but not works. try to transmute greatwood to greatwood 

---

`PhiloStone.addWorldTransmutation(<Thaumcraft:blockCustomPlant>, <Thaumcraft:blockCustomPlant:1>, <Thaumcraft:blockCustomPlant>);`

---

**Mod version**
ModTweaker2-0.9.6
CraftTweaker-1.7.10-3.0.11
ProjectE-1.7.10-PE1.10.0
Thaumcraft-1.7.10-4.2.3.5

Script File

```
import mods.projecte.PhiloStone;
print("Adding 'projecte.zs'...");

PhiloStone.addWorldTransmutation(<minecraft:glowstone>, <minecraft:redstone_block>, <minecraft:redstone_block>);
PhiloStone.addWorldTransmutation(<minecraft:redstone_block>, <minecraft:glowstone>, <minecraft:glowstone>);
PhiloStone.addWorldTransmutation(<Thaumcraft:blockCustomPlant>, <Thaumcraft:blockCustomPlant:1>, <Thaumcraft:blockCustomPlant>);


print("Add 'projecte.zs'");
```

**Comment by pupnewfster** [comment]
Can be closed, as world transmutation works properly in 1.12 including with changing thaumcraft sapplings
