### ISSUE TITLE
Crash with ProjectE + Super Circuit Maker

### ISSUE THREAD

**Issue by HellishINC** [sinkillerj/ProjectE#1390]
https://github.com/amadornes/SCM-Localization-Issues/issues/189 Thread on SCM's tracker.

Crash log: https://gist.githubusercontent.com/HellishINC/b25726f9f7e26f49581598fb66c82e6e/raw/180f6376adb0f25d8c102044906d4203c2b534fb/crashlog

When teaching the table/tablet the recipe for SCM's blueprint, hovering the item in tablet/table causes a crash.

SCM's author has fixed this though they state that the issue lies with ProjectE itself.

> Also, this is ProjectE's fault for trying to get the name of a stack with either a null or invalid NBT tag, though I've taken care of it in SCM directly.

**Comment by pupnewfster** [comment]
Claims it is fixed, so I am closing this especially as the crash log is just giving a 404 error.

**Comment by HellishINC** [comment]
I cleaned out most of the content on my account quite some time ago. Sorry for not closing it myself.
