### ISSUE TITLE
Alchemical Chest won't break

### ISSUE THREAD

**Issue by DarkPhoenix86** [sinkillerj/ProjectE#1391]
I accidentally placed an alchemical chest in the wrong place, and when I went to pick it up it wouldn't break. I even tried using  a Diamond axe on it.  I can't seem to find anything on the internet that tells me how to pick it up.

**Comment by Bigpower2012** [comment]
Why were you using a diamond axe? Your supposed to use a pickaxe

**Comment by DarkPhoenix86** [comment]
Oh... Well I thought, it's a chest let me use an axe.  Thanks a lot!

**Comment by Bigpower2012** [comment]
No worrys
