### ISSUE TITLE
Crashes the server when I right Clicked Archangel's Smite

### ISSUE THREAD

**Issue by Bigpower2012** [sinkillerj/ProjectE#1392]
[crash-2016-11-03_18.16.57-server.txt](https://github.com/sinkillerj/ProjectE/files/587334/crash-2016-11-03_18.16.57-server.txt)

This is the crash report is says, hope it helps to resolve this!

(1.7.10 Version of ProjectE, or this version : ProjectE-1.7.10-PE1.10.1)

THANKS!

**Comment by williewillus** [comment]
#1380

**Comment by Bigpower2012** [comment]
So are the developers going to try and work on this, thank you btw, helped me understand abit more about the crash.
