### ISSUE TITLE
Dark Matter Pedestal Duplication Glitch

### ISSUE THREAD

**Issue by sonicbrandyn** [sinkillerj/ProjectE#1393]
In multiplayer with ProjectE, if you put an item in the dark matter pedestal and u and someone else look in it, you can both take the item out, and get 2, no it is not a ghost item. I would record a video of it but i dont have any friends to record it with lol :(

**Comment by williewillus** [comment]
if you don't have someone to record it how did you get it to happen in the first place? :P 

also game and PE version pls

**Comment by sonicbrandyn** [comment]
Because at the time i was playing with my friend who doesnt like modded minecraft anymore, 1.7.10, ProjectE-1.7.10-PE1.10.0

**Comment by sinkillerj** [comment]
1.7 support has been dropped. Can you reproduce this in 1.10?

**Comment by sonicbrandyn** [comment]
1. I dont have friends
2. I dont like anything past 1.7.10
