### ISSUE TITLE
[1.10.2] Swiftwolf's Rending Gale isn't working!!

### ISSUE THREAD

**Issue by diogo580** [sinkillerj/ProjectE#1394]
I gave a double jump as always and it didn't fly (it had fuel so... not my fault) ,can someone help me?
(sorry for my english)

**Comment by Bigpower2012** [comment]
I have not tried 1.10, only 1.7.10 version, but I pretty sure you need a Klein star, charged up, not fuel, and the ring must be in your inventory, and so does the Klein star

**Comment by HellishINC** [comment]
Doesn't work with the Klein star either and the KS itself is barely functional.

**Comment by Bigpower2012** [comment]
I don't really know then, unless you didn't charge your Klein star up in the right of a relay, you could try and do some deep research to try and find how too or ask someone who works for ProjectE

**Comment by HellishINC** [comment]
Again, the Klein Star is barely functional. Currently, it doesn't properly "absorb" table EMC.  You also can not pull items out of the table using the KS' charge unless you burn the KS itself.

I understand you wanting to help however if you have no experience with the 1.10.x version perhaps leave it to those that do.

**Comment by Bigpower2012** [comment]
Ok 

Good luck trying to find it !

**Comment by peregrinus11** [comment]
In my case, it stops working after I change dimension, eg. from Overworld to Nether or to End (had rather unpleasant death after I went to the End, jumped twice and... fall down like a brick). Just reequip it, then it starts working again...

**Comment by HellishINC** [comment]
Is that with the version that came out a day or so ago?

**Comment by williewillus** [comment]
redirecting to  #1152
