### ISSUE TITLE
Can't place items in the top left slot of energy condenser

### ISSUE THREAD

**Issue by Apathyy** [sinkillerj/ProjectE#1396]
So as the title says, Can't place items in the top left slot of energy condenser. It places but puts another in my hand, which then the other disspears if i place it in my inv.

**Comment by sinkillerj** [comment]
Its a ghost slot... the item is not actually placed there, you are just setting a target...

**Comment by Apathyy** [comment]
Well that makes me feel incredible stupid. Only thought it was a bug as i moved from tekkit classic to tekkit legends which obviously has changed without my knowledge.
Thanks
