### ISSUE TITLE
[1.10.2] Pedestal Item Suggestion

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1398]
So upon playing around with the pedestal in creative, I've noticed it's next to impossible to get the item out of the pedestal without breaking it (left click will break the block, but is currently the method to get an item). As a suggestion, I suggest adding shift+right click to retrieve the item back from the pedestal, as currently that has no function with it, and shouldn't cause any conflicts.

**Comment by pupnewfster** [comment]
Fixed in 1.14+ (properly supports the left clicking while in creative)
