### ISSUE TITLE
[Suggestion] Modding API

### ISSUE THREAD

**Issue by Aeyos** [sinkillerj/ProjectE#1410]
Is there a modding API for ProjectE? I don't like how OP it is in early game, I'd like to tinker with the mod to make it a little more end-game.

**Comment by williewillus** [comment]
what do you mean? we have an API available (see the api package). it's not on a maven though but it should be usable for addons

**Comment by sinkillerj** [comment]
We have both an API for other mods, as well as Minetweaker support.
