### ISSUE TITLE
[Request] Renewel of the MC1.2.5 Forestry EE2 Omega Bee Branch

### ISSUE THREAD

**Issue by TheSledgeHammer** [sinkillerj/ProjectE#1412]
Hey,
I would like to suggest a renewal of the old EE2 & Forestry Omega Bee Branch. 
As a config option instead of the current in-game command method. 

Thanks

**Comment by MaPePeR** [comment]
Which current ingame command method?

**Comment by TheSledgeHammer** [comment]
The one i meant was the "/forestry give bee"command but it appears the omega and that branch isn't even included anymore.
But it would be nice if it was, even as a optional configuration.

**Comment by MaPePeR** [comment]
That is probably something that needs to happen in forestry.

**Comment by sinkillerj** [comment]
Yea its out of scope for us. Your best bet would be to speak to one of the bee adding addon authors.
