### ISSUE TITLE
RE: try to reproduce this please

### ISSUE THREAD

**Issue by BadLucKWyvern** [sinkillerj/ProjectE#1415]
ive left a report due to a emc setting and you said it was perfectly good
ive tottaly reseted my configfile and put emc back one by one, and ive discovered the emc setting error bug:
ive set minecraft items emc, and it worked, but when i set a emc from a item from a another mod, THERE is the error

let me show a exemple:

/projecte setEMC halocraft:SpartaniumIngot 3000
success
/projecte reloadEMC
success
/projecte setEMC halocraft:GreenPlasmaIngot 5000
success
/projecte reloadEMC
success
/projecte setEMC halocraft:PurplePlasmaIngot 10000
success
/projecte reloadEMC
success
/projecte setEMC enderzoo:enderFragment 200
success
/projecte reloadEMC
ERROR

is it the same for you ?
i have to restart the server to put mods items emc one by one...

PS: and each time we die, our knowledge is lost, i put a tome of knowledge and remove it to get my EMC + my knowledge back

**Comment by williewillus** [comment]
can you post the error at least? :P

**Comment by BadLucKWyvern** [comment]
thye error can't make the server crash... it only says error with the command in RED

**Comment by BadLucKWyvern** [comment]
ive got a new supposition... if i create a emc for a non existing item by accident like:
/projecte setEMC halocraft:PurplePlasmaingot 10000 istead of
/projecte setEMC halocraft:PurplePlasmaIngot 10000 (the I)
it maybe create a chain error...?

**Comment by williewillus** [comment]
there should be an error in the log

**Comment by BadLucKWyvern** [comment]
if we don't know how clearly reproduce it, you will not be able to fix it... what should we do ?

**Comment by williewillus** [comment]
eb9cd63
