### ISSUE TITLE
Player knowledge resets upon changing dimensions.

### ISSUE THREAD

**Issue by Dawgie3000** [sinkillerj/ProjectE#1416]
Using ProjectE-1.10.2-PE1.1.0B
On my server, the player's emc knowledge disappears if you change dimensions say to Aroma1997's mining dimension or to one of the RFtools dimensions.  Relogging fixes it, It seems to be similar to the bug that caused the desync on connecting that was "fixed" in this version.

**Comment by sinkillerj** [comment]
Known bug which will be resolved in the next version.
