### ISSUE TITLE
[1.10.2] changing diminsions looses all transmute knowlage and emc in table

### ISSUE THREAD

**Issue by mralext20** [sinkillerj/ProjectE#1417]
version: ProjectE@1.10.2-PE1.1.0B 

steps to reproduce:

learn knowlage
travel to the nether
check on transmutive knowlage
find nothing in table

this seems to be a client server desync, as reloading the world returns all knowledge and emc in table

**Comment by mralext20** [comment]
forgot to mention: does not occur on version projectE@1010.2-PE1.0.6B

**Comment by williewillus** [comment]
duplicate #1416
