### ISSUE TITLE
Energy Condenser only exports to hoppers

### ISSUE THREAD

**Issue by LousyLynx** [sinkillerj/ProjectE#1422]
I am playing a modified version of SkyExchange right now and found that when I try to get items out of the energy condenser, using the item conduits, from Ender IO, transfer nodes, from Extra Utils, and Translocators, from... well translocators, none of them actually pull the items. Only the hopper works. I am not sure if it is only an error on my client or what, because I think I saw Wyld pulling items, using Ender IO conduits...

**Comment by sinkillerj** [comment]
They must be attached to the bottom for now, please ensure that you are doing so.

**Comment by LousyLynx** [comment]
That is probably why only the hopper worked :P I am going to test that right now.

**Comment by LousyLynx** [comment]
Works with Ender IO conduits, but not with Translocators

**Comment by Malkierian** [comment]
Also doesn't work with Logistical Transporters from Mekanism.  Having a hard time finding out what else in my modpack (All the Mods) actually transports items to test with.
