### ISSUE TITLE
[1.10.2] Known EMC lost on dimension change.

### ISSUE THREAD

**Issue by MrSkyFire** [sinkillerj/ProjectE#1424]
Its not "LOST" but psuedo "forgotten", this happens upon death and dimension changes.  
After one of those events occur the "known" recipes are "forgotten". 
I use quotes because it still exists but you have to reconnect in order to retrieve it. 
Stored EMC is still stored even if it says 0, klein star will still retrieve it. But will "relearn" the KS, reconnecting still fixes the tablet afterwards.

Ive enabled the tome of knowledge as a "workaround" for now but I feel mingy having all the recipes known when theres a lot I dont want.

I notice that known emc values are sent on player login, possible fix to have that event happen on dimension change?

ProjectE-1.10.2-PE1.1.0B

**Comment by MrSkyFire** [comment]
Bump: I notice that known emc values are sent on player login, possible fix to have that event happen on dimension change?

**Comment by williewillus** [comment]
duplicate
