### ISSUE TITLE
Another something for nothing bug...

### ISSUE THREAD

**Issue by jakbruce2012** [sinkillerj/ProjectE#1425]
The energy condenser can produce damaged items for low EMC, a chest full of repair talismans can then repair these damaged items for free, then the repaired items can be pumped into another energy condenser for more EMC.  Done quickly enough using AE2 or similarly powerful item transfer systems can generate 1 red matter per second or more when using diamond picks as a damaged item.

It would be nice to have a config option to not allow damaged items to have an EMC value.

**Comment by sinkillerj** [comment]
Duplicate issue, we are working on rebalancing dust.
