### ISSUE TITLE
DMPedestal placed and the world blew up.

### ISSUE THREAD

**Issue by drbissonnette** [sinkillerj/ProjectE#1426]
I made an ubuntu forge server for my sons with a few mods.  One of my sons placed a DMpedistal and the server crashed.  See the attached crash log.  Thanks for any help.
[Crash.txt](https://github.com/sinkillerj/ProjectE/files/632319/Crash.txt)

**Comment by williewillus** [comment]
update forge

**Comment by sinkillerj** [comment]
@williewillus Do we know which version fixes the issue? It may be wise to bump up the required version.

**Comment by williewillus** [comment]
explosion event was added in build 1254, this crash is on build 1230.

It's to note that both of these 1.7 builds are mind bogglingly old (like...approaching 3 years or more). Update to the last 1.7 forge build (1614)

**Comment by drbissonnette** [comment]
Worked like a charm. I used forge:1.7.10-10.13.4.1558-1.7.10Thanks.On December 5, 2016 at 4:31 PM Vincent Lee <notifications@github.com> wrote:update forge—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sinkillerj** [comment]
I should have read the log better, assumed it was a 1.10 issue. Closing as a solution has been reached and 1.7 is dropped anyway.
