### ISSUE TITLE
Transmutaion table data wiped when teleporting between dimensions

### ISSUE THREAD

**Issue by Zhaulus** [sinkillerj/ProjectE#1430]
Whenever I go through a Nether portal or teleport from the Nether using the Ender IO Advanced Charged Porter, any EMC in the table/tablet goes to 0 and all items are unlearned. I am wearing full Gem Armor and carrying an EMC tablet on my hotbar, also at least 1 alchemical bag. Version ProjectE-1.10.2-PE1.1.0B

**Comment by williewillus** [comment]
please search before reporting
