### ISSUE TITLE
EMC disappears after changing DIMs

### ISSUE THREAD

**Issue by jgeekw** [sinkillerj/ProjectE#1432]
I am running the SkyExchange[https://minecraft.curseforge.com/projects/skyexchange](url) modpack by JasonAnaminus. Downloaded the pack from the Curse client. I also downloaded the server files and have it hosted. The problem we are facing is when you change dimensions (e.g. the Nether), all the EMC stored in the table or tablets vanish. The only way to get it to reappear is to log off the server (or save/quit the client) and log back in while in that dimension. Each time you change DIMs you must relog to get your EMC back. I also tried a new instance of Forge (latest version) and ran that with just ProjectE installed and it still happens.

**Comment by williewillus** [comment]
dupe

**Comment by jgeekw** [comment]
which issue is this a dupe of so I can read the thread

**Comment by williewillus** [comment]
do a search because this has been reported 10+ times already

**Comment by Heimdell** [comment]
You'd better link to where is the main discussion of this bug is, its hard to dig through all this dupes.

**Comment by williewillus** [comment]
1. it's fixed in the next version
2. relog to get rid of it
