### ISSUE TITLE
[1.10.2]Null pointer when stored value contains a null item

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1434]
This error came up with a recent change, and I feel a null check would solve this

Error:
http://paste.ee/r/eOOhr

Code:
https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/config/CustomEMCParser.java#L153

Additionally, maybe adding this before the for code may help too
`if (!currentEntries.entries.isEmpty())`

**Comment by Tencao** [comment]
Ok, after trying to debug this issue myself, it seems somehow it stored a null value in the custom emc, which I found out by outputting the entire list in debug mode.

http://paste.ee/r/fIfs8

**Comment by Tencao** [comment]
My fix probably isn't the best one, but the one that solved this for me was this

http://paste.ee/r/hTx07

**Comment by williewillus** [comment]
can you come up with a case that gets a null nss in there? that should never happen

**Comment by Tencao** [comment]
I don't know how to reproduce, unless it was caused by a mod item being removed and it getting set to null.

**Comment by Tencao** [comment]
#1447 Has confirmed the cause. Having a custom emc for an item that no longer exists causes a null item. 

As a fix, I suggest putting this line just above this code

https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/config/CustomEMCParser.java#L150

`currentEntries.entries.stream().filter(e -> e.nss == null).forEach(e -> currentEntries.entries.remove(e));`

**Comment by williewillus** [comment]
thanks for investigating.

you do know that line exactly won't work though right? you'll get a CME from changing something you're streaming over :P

**Comment by Tencao** [comment]
It worked fine my end when changing all those null values, but I guess it has the potential to CME. Either way I'll most likely wait for you to do a better version and learn from that
