### ISSUE TITLE
Problems about the transmutation table.

### ISSUE THREAD

**Issue by MockingLOL** [sinkillerj/ProjectE#1436]
Whenever I die,my learn items are all gone in the table and the EMC value is 0.However,whenever I pull out items,I can grab back the original amount of EMC.This problem occurs too when I am back from the nether and other dimensions.Is this a bug or an in-game setting?

MC 1.10.2 
ProjectE version:ProjectE-1.10.2-PE1.1.0B.jar

**Comment by williewillus** [comment]
Known issue fixed in next release
Please search before reporting
