### ISSUE TITLE
[1.10.2] New diving rod doesn't show max EMC for divining rod (high)

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1439]
https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/items/DiviningRod.java#L159-L167

Right here, you have a check for this == ObjHandler.dRod2, when it should also have || this == ObjHandler.dRod3

**Comment by williewillus** [comment]
if you have code solutions just PR them :P

**Comment by Tencao** [comment]
Still need to learn how to do that :P
