### ISSUE TITLE
Maybe Bug?

### ISSUE THREAD

**Issue by Rithenar** [sinkillerj/ProjectE#1440]
I have assigned custom EMC values to many items, but items crafted from them do not calculate the total EMC value.  For example, I assigned 64 EMC to sky stone from AA2, but the sky chest which is made with 8 of them and should register EMC 512 does not register anything. Another example is with Mekanism where I assigned EMC 384 to a Glowstone Ingot, but the armor (i.e. chest with 8 ingots = 3072) does not register any EMC values.

Two questions:
1- Is this intended behavior? - If so, is there a reason for it or a way around it
2- If it is not, is it a bug and/or what can I do (cfg, etc.) to correct it client-side

I am using 1.10.2 with Forge 12.18.3.2185

**Comment by MaPePeR** [comment]
AE2 used to use a different type of crafting recipes which ProjectE cannot parse in 1.7.10. Maybe they keep doing that in 1.10

**Comment by sinkillerj** [comment]
Nothing we can do about custom crafting handlers beyond custom mappers for each mod that uses them.

**Comment by Rithenar** [comment]
Gotcha, thanks sinkillerj and MaPePeR.
