### ISSUE TITLE
[1.10.2][Suggestion] Config option to make enchants non-duplicable

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1441]
So this is something I personally wanted to do and by the response I got from players, something they wanted too. I would like a config option where enchants are not duplicable, both by having their emc removed, and also make it so enchanted tools only duplicate into normal tools. This way enchants maintain their value because it's more down to luck than getting the best enchant once and reproducing it over and over.

**Comment by MaPePeR** [comment]
I don't even think that needs a configuration option. I consider duping enchantments a bug.

**Comment by sinkillerj** [comment]
There are some situations where it could be needed, but those items are rare and would be easily corrected with a enchantment whitelist much like the nbt whitelist.

**Comment by MaPePeR** [comment]
If I remember correctly enchantments ARE nbt... Or did that change?

**Comment by Starwort** [comment]
they are nbt, but they may be on the whitelist

**Comment by charlesbevans** [comment]
When you place an enchanted book in the tablet, it registers as an enchanted book but has no enchantment.

**Comment by sinkillerj** [comment]
@charlesbevans This is intentional behaviour.

**Comment by creepersbane** [comment]
Enchanted items lose their enchantments when placed into a Transmutation Tablet/Table.

**Comment by pupnewfster** [comment]
1.14+ one of the NBTProcessor settings allows for disabling, both the calculation of EMC from enchantments, as well as the ability to duplicate said enchantment.
