### ISSUE TITLE
[1.10.2][Suggestion] Format EMC on Condensers and Collectors

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1442]
Currently the collectors and condensers display their emc as a raw int, making it hard to figure out how much it is when it gets to higher numbers (100000+). As a suggestion, I suggest changing the 
`Integer.toString(toDisplay)`
to
`String.format("%,d", toDisplay)`

To give you a view of just how much of a difference it makes. 
Current - http://image.prntscr.com/image/b48221d680654ff1bb9bb297f99197e5.png
Formatted -  http://image.prntscr.com/image/7f403973885848508f0a873f387a463d.png

**Comment by sinkillerj** [comment]
Ill see what i can do, unless willie beats me to it.

**Comment by williewillus** [comment]
lol just saw that

**Comment by sinkillerj** [comment]
Welp...
