### ISSUE TITLE
[1.10.2] Desync when death occurs

### ISSUE THREAD

**Issue by addrever** [sinkillerj/ProjectE#1443]
When I die my player EMC value becomes desynced ( shows as zero ).  If I leave the server and come back all is good.

Player Logs ( debugging turned on ):
[2016-12-17-6.log.gz](https://github.com/sinkillerj/ProjectE/files/659116/2016-12-17-6.log.gz)
Server Logs:
[Server Logs.zip](https://github.com/sinkillerj/ProjectE/files/659117/Server.Logs.zip)

This also happens in single player.  Same thing.  I exit the world and load it up again all is fine.

Let me know if you need any other information.

**Comment by williewillus** [comment]
fixed in next release
