### ISSUE TITLE
[1.10.2][Suggestion][ClientSide] Link DM tool abilities to Minecraft weapon cooldown

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1452]
I thought it was odd now that most minecraft tools have a cooldown that the DM tool abilities don't link to it, so as a minor suggestion I'd like the abilities to at the very least display the minecraft weapon cooldown when used.

**Comment by williewillus** [comment]
they do, it's just done server side so the client can't see it and I was too lazy at the time to make it sync :P
