### ISSUE TITLE
[1.10.2] Magma Block EMC Incorrect

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1453]
Currently the Magma Block costs 128 emc, while the Magma Cream costs 800 emc. Either the magma block should be increased to 3200 to match the recipe, or Magma Cream should be brought down to match the magma block

**Comment by williewillus** [comment]
Nerfed on purpose. They're too common naturally to be worth 3k

**Comment by Tencao** [comment]
What about nerfing the magma cream then to better reflect the nerf on magma block?

**Comment by williewillus** [comment]
Those are actually rarer though and deserve the 800 value since it's used for brewing. Also magma blocks can't be reversed into magma cream so I think it's fine as is.
