### ISSUE TITLE
Red Matter Morningstar right-click collects 'uncollectable' blocks

### ISSUE THREAD

**Issue by charlesbevans** [sinkillerj/ProjectE#1457]
PE 1.1.1B, WTF's Expedition 1.2. When right-clicking a fully powered morningstar, I collected a bunch of dense ore and fractured stone that wasn't supposed to be collectable. (Fractured stone is supposed to convert to cobble and cause a chain reaction resulting in a cave-in. Dense ores yield ore on each mine until depleated.)
Reported in https://github.com/WhiskyTangoFawks/Expedition/issues/50

**Comment by WhiskyTangoFawks** [comment]
I can probably fix this fairly easily, I just need to know what code this is using to get the blocks (because whatever method is being used, I've not implemented correctly in my blocks).

**Comment by williewillus** [comment]
we are using the standard `Block.getDrops()` method to collect all of a block's drops, then setting the position to air

**Comment by WhiskyTangoFawks** [comment]
Alright, I'll fix it on my end then.

**Comment by WhiskyTangoFawks** [comment]
Should be sorted, you can go ahead and close this, there shouldn't be anything you need to do on your end.

**Comment by williewillus** [comment]
Cool thanks
