### ISSUE TITLE
Philosopher's Stone shows all recipes in JEI

### ISSUE THREAD

**Issue by charlesbevans** [sinkillerj/ProjectE#1458]
When viewing the uses of a philosopher's stone in JEI, it doesn't just show recipes that the stone is used in, it shows every recipe you can craft using the philosopher's stone as a crafting table.

**Comment by williewillus** [comment]
That's a JEI thing, since the Philstone is registered as a "Crafting Table" so U shows its usages as a crafting table too. Not much in my control I don't think.
