### ISSUE TITLE
Can't set Custom EMC Values

### ISSUE THREAD

**Issue by ProxyPlayerHD** [sinkillerj/ProjectE#1460]
not sure why but any kind of Changes to the EMC Values does nothing.
The File itself looks like this currently:
http://pastebin.com/5WrJQNY2
Really no idea what could be wrong with it.

**Comment by sinkillerj** [comment]
Please ensure that you are using the latest version of ProjectE and only making changes using the "/projecte setEMC" command in game. It would also be wise to delete the current custom emc file before attempting this.

**Comment by ProxyPlayerHD** [comment]
i used the Curse Client to make the Pack, whic hmakes it Download the Newest Version Automatically.
also when i tried it with the command it would just promp an Error every time i would reload the EMC Values.

**Comment by creepersbane** [comment]
Try loading ProjectE by itself in another world, then try to set an EMC value there.

When I say by itself I mean using the standard Minecraft Launcher and Forge (will I get into trouble if I use those names?)  and copying the latest Project E jarfile to the mods folder.

**Comment by pupnewfster** [comment]
Unable to reproduce in 1.15

**Comment by ProxyPlayerHD** [comment]
This was 2 years ago mate, i completely forgot this even existed.

**Comment by pupnewfster** [comment]
Ya I was going through and closing various issues (and leaving a comment as to why for reference of people who end up finding the issue)
