### ISSUE TITLE
EMC doesn't change

### ISSUE THREAD

**Issue by LordHarkon** [sinkillerj/ProjectE#1461]
Hi. I'm playing on Projecte Ozone 2 modpack, and i tried to change the emc value for a few items with 
"/projecte setEMC", i've done that, in chat says that it's done but when i type /projecte reloadEMC, or restart the game the item still does not have EMC. The modpack has the latest version available on Curse.

**Comment by sinkillerj** [comment]
Support for Minecraft 1.7 has been dropped at this time. That being said it sounds like another mod in the pack is causing issues, or that there is an issue writing to the config file. Your logs may provide you with more information if there is a error when you use the commands.
