### ISSUE TITLE
Crash on right click with ArchangelSmite (different environment than 1380)

### ISSUE THREAD

**Issue by LincT** [sinkillerj/ProjectE#1462]
#1380 
Read through the previous error, it mentioned this happens due to libraries not being present. Is there a listing of what libraries are needed to prevent crashing. This is running in Debian Linux, so opening as a new issue since different environment. Right clicking causes "Exception in server tick loop", crashes the server. 
[crash-2016-12-27_17.30.57-server.txt](https://github.com/sinkillerj/ProjectE/files/674842/crash-2016-12-27_17.30.57-server.txt)

**Comment by williewillus** [comment]
The missing library is vecmath, which should be present on all properly installed forge systems. Forge uses it itself in 1.8+ too. I have no idea what's going on

**Comment by sinkillerj** [comment]
I have been unable to reproduce the issue on any proper install. That said 1.7 is now a legacy build and is no longer supported.
