### ISSUE TITLE
Pictures missing from the wiki

### ISSUE THREAD

**Issue by tprk77** [sinkillerj/ProjectE#1463]
I've noticed a few images are missing from the wiki. Not a big deal, but I wonder what they are? In particular, I've been going through the **Alchemy** section.

From: https://github.com/sinkillerj/ProjectE/wiki/Energy-Collectors

> ![](http://i.imgur.com/Ka9NhN2.png)

Maybe you still have the images on disk somewhere?

Instead of using Imgur, you could just use Github for hosting. (For example, make a small repo just to host images on the wiki.)

**Comment by sinkillerj** [comment]
The wiki is purely community sourced and not officially supported. Feel free to correct the issue.
