### ISSUE TITLE
[1.10.2]  Dark Matter pickaxe/hammer and destruction catalyst 

### ISSUE THREAD

**Issue by Calonsus** [sinkillerj/ProjectE#1468]
The  modes of the dark matter pickaxe, the right-click of the dark matter hammer, and the function of the destruction catalyst are not functioning properly.

The pickaxe is mining a 2x2 panel or a 2x2x2 cube in long mode.

the hammer mines in a way I can't even describe. 

the catalyst mines 2x2 instead of 3x3 as before.

**Comment by sinkillerj** [comment]
Duplicate of #1446 and #1449. Resolved in the next build.
