### ISSUE TITLE
[1.10.2] Divination Rod issue, and DM pickaxe on redstone ore

### ISSUE THREAD

**Issue by EverlightHelios** [sinkillerj/ProjectE#1469]
Hey there, 1.1.1B user here, noticed that much like all the dark matter tools and the like, the divination rod also has the same problem where it only checks a 2x2 area, no clue how deep it goes either. But since the 64x3x3 check gets a max of 252 blocks, my guess it's actually 63x2x2. Don't know if this has to do with the same code as the tools, but I just thought I'd point this little bug out as well!
Also, don't know if you noticed in the previous 1.1.0B and 1.0.6B build, but the DM pickaxe only gets out one block instead of the whole vein on a right-click on redstone ore. Hope this helps! Also, really love the mod!

**Comment by williewillus** [comment]
this should be fixed
