### ISSUE TITLE
[1.10.2] Transmutation Tablet breaks IE Conveyor Belts 

### ISSUE THREAD

**Issue by JAWSAWN** [sinkillerj/ProjectE#1470]
Also vertical and splitting conveyor belts cannot be gained from the transmutation tablet

I think because the 4 items has the same id but have different tags to identify between.

latest both

**Comment by JAWSAWN** [comment]
Does ProjectE accepts NBT spesific recipes?

**Comment by MaPePeR** [comment]
no
