### ISSUE TITLE
[1.10.2][Suggestion] Make the DM furnace have a 50% chance to double

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1473]
So this is one thing that I believe is a little op right now and can certainly help balance parts of the early game. In the original EE2, the DM furnace only had a 50% chance to double it's output, however currently it always doubles it's output, which indirectly also puts less value on the RM furnace as a viable upgrade outside of more storage and faster speed.

**Comment by williewillus** [comment]
Pretty sure this is a bug
