### ISSUE TITLE
[1.10.2][Suggestion]Allow Gem armor offensive abilities to be used with held item

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1474]
Basically, allow the gem armor offensive abilities to be toggled if the held item isn't an instance of IItemCharge, additionally let the gem armor abilities be fired if the held item isn't an instance of IExtraFunction or IProjectileShooter

I know there's a config to enable bypass, but it's default disabled, and most new players would be confused why their abilities aren't working. At the very least, if you're not going to enable it by default, send an ingame message to the player warning them their hand must be empty, as well as provide an ingame override/switch for the function.

**Comment by sinkillerj** [comment]
"I know there's a config to enable bypass" And if a player enables that they accept that they may blow up their house. Removing the safety should take 5 seconds of research.

**Comment by MaPePeR** [comment]
Do you REALLY think anyone invests 5 seconds of research into something that he/she thinks is impossible?

**Comment by Tencao** [comment]
5 seconds of research plus the time it takes to close and relaunch the client. Plus there is no easy method in game of enabling/disabling this or letting the player even know there's such an option.

Also, I'm not doing this to be rude or anything, but a quick google search regarding this issue does not have any mention of such a config option, as an example:
https://www.google.co.uk/search?q=gem+armor+abilities+dont+work&oq=gem+armor+abilities+dont+work
