### ISSUE TITLE
[1.7.10] Support for Treecapitator

### ISSUE THREAD

**Issue by dimitriy0810** [sinkillerj/ProjectE#1476]
How to add support for mod Treecapitator? (I want to cut trees with tools (red matter katar) of mod ProjectE). Versions of mods: Forge 10.13.4.1614, ProjectE 1.7.10-PE1.10.1, Treecapitator universal-2.0.4. Version of minecraft: 1.7.10. When I change config file of Treecapitator, in config directory appears file with name Treecapitator_date and time_errored. With red matter axe, wich added to config file Treecapitator.cfg, treecapitator is works; with red matter katar, don't work. I have no log or crashlog

**Comment by sinkillerj** [comment]
1.7 support has ended. There are also no plans to add support for this on the ProjectE side.
