### ISSUE TITLE
Can't set EMC for certain mods

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [sinkillerj/ProjectE#1477]
I know how to set EMC values in game, and have done so for some of my mods, like Actually Additions.  However the command fails to work for items from certain mods, like Mekanism or Ashenwheat.  All I get is "An unknown error occurred while attempting to perform this command", which really isn't the most enlightening error report.  I've even tried editing the config file directly, with no success.  Any ideas of what's going wrong and how to fix it?

**Comment by sinkillerj** [comment]
Please ensure that you are using the latest 1.10 version. 1.7 and other MC versions are no longer supported.

**Comment by 7OOTnegaTerces** [comment]
That fixed it, really sorry for bothering you!!!
