### ISSUE TITLE
[Suggestion] Add untransmutable EMC to ores and in general 

### ISSUE THREAD

**Issue by JAWSAWN** [sinkillerj/ProjectE#1478]
1.7.10 EE3 has a really great ability. Now I understand how important it was. Basicaly I suggest the unlearnable emc to some stuff. Like ores for example. Iron ore does not have emc because it means easy dupe bug with a pulverizer. My suggestion is that ores have the equal emc as their ingots. This means 1 iron ore has 256 emc. And you can put it in your transmutation table to get the emc. BUT YOU CANNOT TRANSMITE THE BLOCK ITSELF. This fixes so many dupe bugs and eases the ProjectE mining. 
Also add support for the custom emc for this. 

~~Sincerely from Skyexchange Developer Jason.

**Comment by sinkillerj** [comment]
Inequivalent exchange will come eventually and this feature will likely be part of it. That being said I dont have a estimate on when ill have time for the overhaul,

**Comment by MaPePeR** [comment]
If you now support the idea of separate buy/sell values for emc i could try to update my PR from 2015.

**Comment by sinkillerj** [comment]
@MaPePeR I've made my thoughts clear on split values multiple times, its a overcomplicated system.

**Comment by MaPePeR** [comment]
To me it looked like you changed your mind. Because

> Inequivalent exchange will come eventually and this feature will likely be part of it.

and inequivalent exchange + "this feature" is separate buy/sell.

**Comment by Keaft** [comment]
Following along with #1015 and #1036 and this thread, I would just like to add that I would appreciate such a system. 

I'm trying to create a modpack which encourages exploring some of the other mods more so than they do now. As a player I find that I get stuck in a rut following ProjectE to the endgame whilst neglecting other mods. It would be nice to be able to set an EMC value for other mod's blocks and items, but keep them from being learn-able. This would mean that players could more easily explore without losing EMC and without "redirecting" entirely back to ProjectE. 

And perhaps that is why I feel like I fall into a rut. I don't feel like my progress is "saved."

Anywho, Thank you so much for the work that you are doing with this mod. It's been a great source of nostalgia and straight up fun!

**Comment by Keaft** [comment]
Following along with #1015 and #1036 and this thread, I would just like to add that I would appreciate such a system.

I'm trying to create a modpack which encourages exploring some of the other mods more so than they do now. As a player I find that I get stuck in a rut following ProjectE to the endgame whilst neglecting other mods. It would be nice to be able to set an EMC value for other mod's blocks and items, but keep them from being learn-able. This would mean that players could more easily explore without losing EMC and without "redirecting" entirely back to ProjectE.

And perhaps that is why I feel like I fall into a rut. I don't feel like my progress is "saved."

Anywho, Thank you so much for the work that you are doing with this mod. It's been a great source of nostalgia and straight up fun!
