### ISSUE TITLE
World transmutation script not working.

### ISSUE THREAD

**Issue by Natey214** [sinkillerj/ProjectE#1480]
Hello, I am having an issue with the transmute from projecte. Everything was working great and then suddenly I loaded a game and I can no longer transmute anything from the script. I have a recipes script that works perfectly just not the transmute.

What happens:

For example: it's set to transmute ice from glass, when aiming philosophers stone at glass nothing happens.

What you expected to happen:

Right clicking should transmute glass into ice

Script used

http://pastebin.com/dZfGwvtQ

Minetweaker.log file

http://pastebin.com/g039Wf5i

Affected Versions (Do not use "latest"):

Minecraft:1.10.2
Forge:12.18.3.2221
Crafttweaker: 1.10-2.3.0.20
Projecte version: 1.10.2-PE1.2.0.jar
Your most recent log file where the issue was present:

[pastebin/gist/etc link here]
http://pastebin.com/93dZkCGv

**Comment by sinkillerj** [comment]
You added a one way transmuation.

**Comment by Natey214** [comment]
If you mean the glass to ice one then it's meant to be one way. Can there not be a one way transmutation?

**Comment by williewillus** [comment]
that's not what your original report said. 

what I think your report said: "I added a ice to glass transmutation. I am trying to click glass and get ice. Why doesn't it work?"

**Comment by williewillus** [comment]
your script only has ice -> glass, it doesn't have a glass -> ice.

**Comment by Natey214** [comment]
Sorry that was badly written on my part that's ice FROM glass not ice to glass. But neither work. I cannot transmute glass into ice with that script

**Comment by Natey214** [comment]
So any ideas on how to fix it? I've also added the lines 

PhiloStone.removeWorldTransmutation(<minecraft:grass>, <minecraft:cobblestone>, <minecraft:stone:0>);
PhiloStone.removeWorldTransmutation(<minecraft:grass>, <minecraft:cobblestone>, <minecraft:sand>);
PhiloStone.removeWorldTransmutation(<minecraft:grass>, <minecraft:stone:0>, <minecraft:cobblestone>);

in preparation for finding a solution, none of the transmutations in the config file work.

**Comment by williewillus** [comment]
will take a look soon (tm)

**Comment by pupnewfster** [comment]
I think this can be closed as the 1.10 branch isn't being updated any more, and editing world transmutation with CrT works(/is implemented again) in 1.12
