### ISSUE TITLE
Energy condensers not using item durability.

### ISSUE THREAD

**Issue by definablefan4** [sinkillerj/ProjectE#1482]
I was using an EMC farm for a while (condensing low durability gold swords and repairing them) and when I upgraded the condenser from mk1 to mk2 the condenser seems to not be realising the durability of the items.

**Comment by MaPePeR** [comment]
the bug that allowed condensers to create damaged items was fixed. Maybe it was not switching vom mk1 to mk2, but upgrading your ProjectE?

**Comment by definablefan4** [comment]
Oh so it was a bug. Would be nice to make this optional in the config. And yes ProjectE was recently updated in the pack I use.

**Comment by sinkillerj** [comment]
There are no plans to add a config at the current time.
