### ISSUE TITLE
In-world transmutation not working properly

### ISSUE THREAD

**Issue by WeslyAdvanceSP** [sinkillerj/ProjectE#1483]
I have a really weird issue when using the philosophers stone. Instead of transmutating a block, it picks the block itself up. This is only when playing in survival, in creative the stone works as intended. Any idea what this could be?

**Comment by sinkillerj** [comment]
We are going to need more info on this. ProjectE version? Minecraft version? Any log messages show when the issue occurs?

**Comment by WeslyAdvanceSP** [comment]
The minecraft version is 1.7.10, mod version is 1.10.1. I can't see anything in the logs, even when I enable verbose logging in the projectE config.

**Comment by sinkillerj** [comment]
The 1.7 build is no longer officially supported, that said this is probably a conflict with another mod which modifies right click behaviour.

**Comment by WeslyAdvanceSP** [comment]
Oh okay, thx your help anyway. I still have a question, do you know how I can find out which mod does that? Like is there a log that shows me which mod does that? I have a little experience in mod development, so that can help me out in a way.

**Comment by WeslyAdvanceSP** [comment]
Update: I found out it was factorization, version 1.7.10-0.8.100. It was this mod that bugged in world transmutation. I thought it could be useful to put it out here, if any one else has the same problem.

**Comment by sinkillerj** [comment]
Thanks for reporting back Wesly, should indeed help if this comes up again.
