### ISSUE TITLE
EMC Dupe bug

### ISSUE THREAD

**Issue by GreatGameGuy** [sinkillerj/ProjectE#1485]
This is a problem I encountered while trying to scroll items into the transmutation tablet, I'm assuming it would also apply with the table though haven't tested it, I am gaining the EMC that the item would give me, though I am not loosing the item from my inventory. This may be the fault of inventory tweaks as I don't remember if scrolling items is a vanilla feature or a inventory tweaks feature but you might want to look into this issue.

Edit: Upon further inspection it seems to be ghost EMC.

**Comment by sinkillerj** [comment]
Duplicate issue.
