### ISSUE TITLE
1.10 Dark Matter/Red Matter Furnace Aeternalis fuel block issue

### ISSUE THREAD

**Issue by TheClaus** [sinkillerj/ProjectE#1486]
When using an aeternalis fuel block inside a Dark Matter/Red Matter furnace to smelt/cook items if left without something to smelt/cook after awhile it will cause the furnace to not cook anything else and changing fuel sources doesn't fix it.

Only breaking and placing the furnace back down will allow the furnace to function.  This only happens with the aeternalis fuel block as a fuel source.

**Comment by williewillus** [comment]
can't reproduce..can you make a video of the issue?
