### ISSUE TITLE
1.10 Damaged Tools Config?

### ISSUE THREAD

**Issue by Kryptic01** [sinkillerj/ProjectE#1490]
would it be possible to ad a config option for damaged tools in the condensor?

**Comment by MaPePeR** [comment]
I'd vote: no

**Comment by sinkillerj** [comment]
There are no plans to add this functionality, the change is intended a long overdue.

**Comment by Zettt** [comment]
Sad. That was the best feature. It made the whole thing so superbly unbalanced and overpowered that it was a joy to play.
