### ISSUE TITLE
[1.10.2] Cannot use CraftTweaker to add/remove recipes

### ISSUE THREAD

**Issue by Compegen** [sinkillerj/ProjectE#1492]
Using version `PE1.2.0` and CraftTweaker version `3.0.24` both for Minecraft 1.10.2

Trying to use CraftTweaker to adjust some of the recipes in a modpack but for some reason ProjectE recipes cannot be added or removed by the mod.

CraftTweaker has been reloaded and game restarted

I was however able to do this when using ProjectE and CraftTweaker in 1.7.10

![ct_projecte](https://cloud.githubusercontent.com/assets/8009507/24334913/39343010-1239-11e7-874e-1967ab770053.PNG)

**Comment by rockbanddude** [comment]
The mod ID is projectE, not projecte.

**Comment by Compegen** [comment]
It is infact project**e** and not project**E** as show by what happened when I reloaded the script with projectE instead: 
![couldnot](https://cloud.githubusercontent.com/assets/8009507/24820756/53dd1582-1bb0-11e7-8188-2036628f91f7.PNG)

**Comment by Compegen** [comment]
CraftTweaker seems to be working now, but not entirely sure why. Nothing has changed on my end other than time.

**Comment by rockbanddude** [comment]
I could have sworn it was projectE on 1.7.10. Maybe they changed to lowercase.
