### ISSUE TITLE
Energy condenser, and energy condenser mkII not working

### ISSUE THREAD

**Issue by CrazedMiner76** [sinkillerj/ProjectE#1494]
I tried adding ProjectE to skyfactory 3 and the energy condensers will not absorb any items.

**Comment by sinkillerj** [comment]
Did you set a target?

**Comment by CrazedMiner76** [comment]
if you mean the top left item then yes, i did that and i tried the solar things on the side it wont build up emc

**Comment by tyler489** [comment]
The solarcollector needs to be connected to relays

**Comment by williewillus** [comment]
needs more infio
