### ISSUE TITLE
Setting Values for a Collecter removes Emc values

### ISSUE THREAD

**Issue by tyler489** [sinkillerj/ProjectE#1495]
So i changed my collector recipy to this https://gyazo.com/b1d17bf1033ff8aac5f7b0a444202f73

i used the command projectE RemoveEmc while holding it and to my supprise all the items used in this recipies emc values were removed So red matter,darkmatter,all the project e fuels and all previous collectors lost there emc values

**Comment by sinkillerj** [comment]
Minecraft version?

**Comment by tyler489** [comment]
Sorry 1.10.2
