### ISSUE TITLE
ModTweaker Integration

### ISSUE THREAD

**Issue by NicosaurusRex99** [sinkillerj/ProjectE#1497]
Issue Description:

Note: When changing scripts projecte doesnt automatically update EMC to support the new recipe

What happens: EMC stays the same

What you expected to happen: ProjectE EMC values change to support the new recipe

Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue): recipes.remove(stuffz);

recipes.addShapeless(stuffz, [bit more stuffz]);

Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue): https://pastebin.com/R1jGYTVK

Affected Versions (Do not use "latest"):

Minecraft: 1.10.2
Forge:12.18.3.2272
Crafttweaker: 1.10.2.3.0.24
ModTweaker:2.0.11
MTLib:1.0.2
ProjectE:1.10.2PE1.2.0
Your most recent log file where the issue was present:

http://cryptb.in/Me3q

**Comment by sinkillerj** [comment]
I may take a look but I'm hesitant to accept that there is a issue on our end, the mod in question is likely either removing the recipe at a very late stage, or removing it in a atypical way.

**Comment by NicosaurusRex99** [comment]
I just think that ProjectE is loading EMC Values before ModTweaker loads.

**Comment by bookerthegeek** [comment]
Quick question for someone in the know.... What is the non minetweaker way to modify emc values?

**Comment by williewillus** [comment]
ingame commands to modify the `custom_emc.json`

**Comment by bookerthegeek** [comment]
@williewillus couple quick questions...
- Is it ok to edit that outside of the game?
- Does it sync from server to client?

Thank you for taking the time to respond.

**Comment by williewillus** [comment]
yes to both

**Comment by NicosaurusRex99** [comment]
@bookerthegeek its simple, hold the item and type /projecte setEMC <value>

**Comment by bookerthegeek** [comment]
@NicosaurusRex99 More so that we can fix EMC loops on our server. Will have to test to see if other EMC values readjust after manually setting some.

**Comment by MaPePeR** [comment]
If you change emc values other values readjust accordingly. (IF the recipe is known to the emc mapper - so it will not work for sag mills, pulverizers and alloy smelters or stuff like this.)

You can teach offending Recipes to the mapper by using custom conversions and it should change the emc value according to the new cheaper recipe.

**Comment by pupnewfster** [comment]
Should be able to be closed as 1.10 is no longer being updated. My guess is that if I remember correctly, in 1.10 recipes from CraftTweaker could be reloaded... so that means it might have been happening after the initial connection.
