### ISSUE TITLE
Ingredients have values but end result doesnt

### ISSUE THREAD

**Issue by cyris69** [sinkillerj/ProjectE#1498]
I was wondering if this is just an error/bug? So for explanation purposes I'm going to use a fake item.

Say the item "magic machine" has no EMC value but all ingredients needed to create it do. Is there a way without having to manual add up and use setEMC for every item that has an issue like this? I wasn't sure if there was a tool that could be used to create calculated EMC values for mods not working/support or even some that are but not all is calculated.

Not sure if that makes sense but would love to figure out how to fix it or something to simplify the process manually.

**Comment by sinkillerj** [comment]
Normally ProjectE will map values based on the recipe, however we are not able to do that with mods which use custom crafting handlers. For such mods custom mappers have to be created on a per mod basis, typically through a addon.

**Comment by MaPePeR** [comment]
You can use custom conversions to teach the recipe to the emc mapper.
