### ISSUE TITLE
Thermal Expansion 2-Transmutation Tablet

### ISSUE THREAD

**Issue by Dom063** [sinkillerj/ProjectE#1499]
Hello, I was playing my single player world and decided to add machines from thermal expansion to my tablet knowledge, when I noticed something. After I added the blocks, there seemed to be two of the same machine in the knowledge. Does anyone know why this is happening? Thanks.[
![2017-04-09_21 21 43](https://cloud.githubusercontent.com/assets/18494394/24843716/09b0526e-1d6b-11e7-92d2-56fba3166820.png)
![2017-04-09_21 21 44](https://cloud.githubusercontent.com/assets/18494394/24843718/09b11ff0-1d6b-11e7-8c80-6d7ec64e3b86.png)
![2017-04-09_21 23 20](https://cloud.githubusercontent.com/assets/18494394/24843717/09b0ba38-1d6b-11e7-999d-97f9cbe080af.png)
![2017-04-09_21 23 21](https://cloud.githubusercontent.com/assets/18494394/24843719/09b172b6-1d6b-11e7-9960-da8e94e47e27.png)

](url)

The first two screenshots are the duped knowledge, the last two are when i re-logged.

**Comment by sinkillerj** [comment]
This is under 1.10 correct? Currently looking in this as its not the first I've heard of it.

**Comment by williewillus** [comment]
yeah, there's prismarine/purpur in the JEI pane

**Comment by Dom063** [comment]
Yeah, sorry for not including the version. It's 1.10.2

**Comment by pupnewfster** [comment]
This got fixed a while ago in 1.12 don't remember exactly when.
