### ISSUE TITLE
[1.10.2] Alchemical Chest doesn't work with AE2 storage buses

### ISSUE THREAD

**Issue by TheUnderTaker11** [sinkillerj/ProjectE#1500]
The most recent file released January doesn't work with storage buses. After making a report on AE they said they made the buses support the new 1.10 inventory system. I see on the master branch you are using the capability inventory system, is ProjectE version PE1.2.0 using the capability system, or is it a change made after that version?

**Comment by sinkillerj** [comment]
You will likely need to attach them to the bottom of the condenser.

**Comment by TheUnderTaker11** [comment]
It wasn't a condenser, just the plain alchemical chest. And I know from using it that there are a decent amount of other things that work with normal chest and other mods chest that don't work with the alchemical chest, such as the mekanism auto-output. Are you saying that type of stuff will only really work right if it is interacting with the bottom of the alchemical chest?

**Comment by williewillus** [comment]
hmmm for a plain alch chest all sides should work just fine

**Comment by TheUnderTaker11** [comment]
You can test it, if you put a storage bus on a chest and start taking stuff out and putting stuff in weirrrrd stuff starts happening, [this for example](https://imgur.com/a/F4XM3). Also you can get mekanism and try to make it auto-output the the chest, and it simply won't work.

**Comment by williewillus** [comment]
I have no idea what's up with this, but I'm pretty sure it's not PE. The chest has a dead simple inventory exposed: https://github.com/sinkillerj/ProjectE/blob/c58e6ee2d3aac41d9d4557b9cf5be1fd17a3038a/src/main/java/moze_intel/projecte/gameObjs/tiles/AlchChestTile.java#L24-L39
