### ISSUE TITLE
[1.7.10] Says javax/vecmath/Tuple3d is missing even though it's not.

### ISSUE THREAD

**Issue by CameronSas** [sinkillerj/ProjectE#1502]
In my [crash report](http://www.sasser.xyz/crash-2017-04-21_19.06.49-server.txt) it says it's missing the class, Tuple3d, even though I have it.

![2017-04-21-191837_1280x1024_scrot](https://cloud.githubusercontent.com/assets/27872875/25299003/c416cbfe-26c8-11e7-9132-06f6963605aa.png)

**Comment by sinkillerj** [comment]
1.7 is no longer supported. Please ensure that you are using a official and up to date version of Forge.
