### ISSUE TITLE
Unable to filter for EMC values in JEI

### ISSUE THREAD

**Issue by ZeWolfTah** [sinkillerj/ProjectE#1503]
MC Version: 1.10.2
Forge Version: forge-1.10.2-12.18.3.2281-installer
JEI Version: jei_1.10.2-3.14.7.417
Project E Version: ProjectE-1.10.2-PE1.2.0

Bug:
When using # (filter by tooltip) or just flat out enabling tooltip search to always be on in JEI, I am unable to filter and find all the items that have EMC values. This only happens when searching in JEI, as items inside of a Refined Storage system or AE system are able to be properly filtered and find any items that have the EMC tooltip.

**Comment by williewillus** [comment]
iirc this is because JEI caches tooltips before EMC values are calculated, so it doesn't know about them and can't search them

**Comment by ZeWolfTah** [comment]
Is there a way to change when JEI caches tooltips? Back in 1.7.10 with NEI I was able to filter it which helped greatly when setting custom EMC values. JEI is unable to filter it even when I tried the NEI 1.8.+ addon with it.

**Comment by williewillus** [comment]
even if the values were initialized before jei caches tooltips, the values are subject to change any time in game via the /projecte commands, so your search would turn up incorrect values

**Comment by williewillus** [comment]
^, maybe open suggestions with JEI to allow you to regenerate the tooltip cache while playing, but there is not much PE can do here

**Comment by Firesparq** [comment]
I know this was closed ages ago, but I had an idea for this. If PE added a "transmutable" tag that JEI can detect, the EMC count wouldn't matter. This would allow for a full EMC list search. I know it's not allowing you to do exact EMC searches, but it'd allow you to check for transmutable items

**Comment by williewillus** [comment]
well "transmutable" is basically "is the emc value not zero" which still depends on the emc value, which still means it can't be cached at startup.

**Comment by Firesparq** [comment]
Touche. I suppose you'd need a persistent external cache. Whilst it'd mean an initial load would be required before emc values could be searched for, it would provide at least a partial solution.
