### ISSUE TITLE
[1.10.2] Collector fuel upgrades stop at Redstone Block

### ISSUE THREAD

**Issue by kitsu** [sinkillerj/ProjectE#1505]
Last time I used ProjectE (1.7.10) I had problems with collectors and fuel conversion, so I wasn't surprised to run into similar issues in 1.10. This time I spent some time digging into the problem.

At first I thought the problem was that blaze powder didn't have an EMC value assigned, but setting it to the default had no effect. Then I noticed both redstone blocks and blocks of coal both have an EMC of 576.
After setting block of coal to 9x128 my collectors seem to be working properly.

I didn't really see where having identical values would break the `FuelMapper` logic. Maybe you could do a check for equivalent values in the `FUEL_MAP` though and just dump one of the duplicates?

BTW I am enjoying the new in-equivalent exchange setting. A low rate of return makes resource collection meaningful again.

**Comment by kitsu** [comment]
I think I found it.
In CollectorMK1Tile in the updateEmc method:

``` java
ItemStack result = getLock() == null ? FuelMapper.getFuelUpgrade(getUpgrading()) : getLock().copy();
int upgradeCost = EMCHelper.getEmcValue(result) - EMCHelper.getEmcValue(getUpgrading());
if (upgradeCost > 0 && this.getStoredEmc() >= upgradeCost)
{
    ...
}
```

When fuel1 EMC == fuel2 EMC upgradeCost = 0 and the whole block is skipped.

The else block says to forward to accepting blocks, but instead my collectors just held there charge, presumably because they had valid fuel items.

**Comment by piisawheel** [comment]
**Version 1.12.2**
I Second this bug on 1.12.2.  Another mod added a recipe to give me 4 blaze powders from 1 rod lowering the cost of blaze powder to be equal to glowstone dust.  The glowstone dust just sat there with the white _done_ arrow stuck at 100.  Lowing glowstone (so I could get the blaze, fix the glowstone, and set the blaze manually) fixed the issue.
