### ISSUE TITLE
setEMC not changing emc value

### ISSUE THREAD

**Issue by groger12** [sinkillerj/ProjectE#1507]
I'm currently playing the modpack project ozone 2 from the curse launcher, using minecraft 1.7.10.
I wanted to add an emc value to the gaia spirit, so I used the command 'projecte setEMC #' followed by 'projecte reloadEMC' and both commands give confirmation messages without any errors, but the gaia spirit still doesn't have an emc value. 
I then tried to change the emc value of other items like dirt, transfer pipes and mana diamond. Every time it tells me that the value was successfully changed, but nothing happens. 
I have also tried changing the emc values manually by editing the custom-emc config file, but that does nothing as well

**Comment by MaPePeR** [comment]
There probably is a "pregenerated emc file". You need to make your changes inside that file. (or you can delete it, but that might overwrite changes the pack author made in that file)

**Comment by groger12** [comment]
That worked, thanks!
