### ISSUE TITLE
Transmutation table accepting items with no EMC

### ISSUE THREAD

**Issue by Evill98** [sinkillerj/ProjectE#1508]
So I am playing my own custom pack with the latest version of ProjectE and forge and I can shift-click items with no EMC into the transmutation table. They sometimes appear in there but I cannot take them out. It's really annoying and I've lost a couple of ores because of this.

**Comment by rockbanddude** [comment]
The ores have a one-way exchange i tgink.

**Comment by SummitSummit** [comment]
Yes, this is bad.  I've lost my Tinker's tools more than once because of this.

**Comment by CyberAxis** [comment]
Having the same problem.

**Comment by CyberZxis** [comment]
It only happens in version 1.3.0

**Comment by williewillus** [comment]
@sinkillerj you broke it :P

**Comment by sinkillerj** [comment]
¯\_(ツ)_/¯
