### ISSUE TITLE
[1.7.10] Can't open world

### ISSUE THREAD

**Issue by mendel3** [sinkillerj/ProjectE#1509]
When I try to make a new world, or join an existing one, it boots me back to the start screen. 
Using forge version 10.13.4.1614, newest version of ProjectE for 1.7.10. I am on a mac OSX Sierra
Crashlog 1 (fml-client-latest.log): [https://paste.ee/p/cCeaM](https://paste.ee/p/cCeaM)
Crashlog 2 (2017-05-10-2.log):[https://paste.ee/p/XcuF4](https://paste.ee/p/XcuF4)
Let me know if you need any more info
I have tried my modpack without ProjectE, and it works just fine.

**Comment by MaPePeR** [comment]
Update Chisel
