### ISSUE TITLE
Gem of Eternal Density does not condese custom ores

### ISSUE THREAD

**Issue by ferrelas** [sinkillerj/ProjectE#1511]
I've set custom values for some ores, and the configs for blacklisting ores and some oredict names to false, but it still won't condense ores.

Versions:
Minecraft: 1.7.10
Forge: 10.13.4.1614
ProjectE: 1.7.10-PE1.10.1

**Comment by sinkillerj** [comment]
Support for Minecraft 1.7 has been dropped.
