### ISSUE TITLE
Disabling energy collectors from the config doesn't work

### ISSUE THREAD

**Issue by th4umiel** [sinkillerj/ProjectE#1515]
As the title says :) Currently running ProjectE-1.10.2-PE1.3.0

**Comment by sinkillerj** [comment]
I take it you are using a old config file? I recommend regenerating it. Those options were removed quite awhile back now, all they did was remove the recipe. Minetweaker among other mods provide this functionality if you require it.

**Comment by th4umiel** [comment]
Thanks, that's exactly what I did :)
