### ISSUE TITLE
Speed increase?

### ISSUE THREAD

**Issue by PyroSyndicate** [sinkillerj/ProjectE#1517]
Is there a way I can increase the speed of which items are broken down? I understand that the MK2 breaks items down a tonne quicker than the usual condenser, yet I am having issues using Item Conduits to pull out any items.

**Comment by sinkillerj** [comment]
A feature like this is not planned at this time, this could cause increased server lag and overall balance issues. That said the MK2 is not even faster, it just has a separate inventory.

**Comment by MaPePeR** [comment]
sinkillerj: MK2 is (alot) faster if you are able to fill its first slot with a stack every tick.

**Comment by williewillus** [comment]
MK2 is indeed faster. It goes by stacks, and also outputs as much as possible each tick

**Comment by sinkillerj** [comment]
TIL I dont know my own mod...
