### ISSUE TITLE
Archangel Bane arrows do lowest damage possible.

### ISSUE THREAD

**Issue by Heimdell** [sinkillerj/ProjectE#1518]
Looks like arrows shot from AB behave like they were shot by fast-clicking a bow.

It takes a long to kill even a squid. Thats not how this Weapon of Bane behaved in past times.

And some graphical issues. Arrows shot will rotate and land with they side, if enough flight lenght provided. Then they rearrange themselves properly.

I was amazed that homing works - that is my old piece of code, after all.

**Comment by BadLucKWyvern** [comment]
Possible to set a arrow limit on ground like cavernic skeleton ? (10 arrows a second with no lag because arrows are deleted fastly)
need a damage setup option due to low damages
