### ISSUE TITLE
[1.10.2] ProjectE dont recognize 2 items with just different NBT tag

### ISSUE THREAD

**Issue by Liinche** [sinkillerj/ProjectE#1522]
Hi everybody i was trying to make EMC for Industrial Craft when i encouter a problem the cable from IC2 have the same ID so ProjectE can't make the 2 items have a differente Emc value
See the tooltips of the 2 items
![2017-06-11_17 51 59](https://user-images.githubusercontent.com/25283037/27012400-433c56f0-4ecf-11e7-9ae0-b857dde2a3cd.png)
![2017-06-11_17 52 07](https://user-images.githubusercontent.com/25283037/27012401-433fdab4-4ecf-11e7-8ee4-1fe9aa620e97.png)
So i ask if is it possible for ProjectE to recognize this tag.

**Comment by MaPePeR** [comment]
No, it is not possible.

**Comment by Liinche** [comment]
that clear :DDD
