### ISSUE TITLE
Energy condenser broken.

### ISSUE THREAD

**Issue by john-sp** [sinkillerj/ProjectE#1524]
I put a item in the top left corner of the energy condenser and i close and reopen it and it is not there, i put an item back in the top left and one in the middle and nothing happens. can I have help please

ps - I have restarted my game to try to fix it and it did not work

**Comment by sinkillerj** [comment]
We need more information here. Minecraft version, PE version, any errors in the log, etc.

**Comment by john-sp** [comment]
I have edition 1.10.2, java, and no errors

**Comment by john-sp** [comment]
I have fixed it by restarting EMC with the command /projecte reloadEMC, and making sure to left click to put the item in. (left click does not work)
