### ISSUE TITLE
Sending game back to title screen on startup

### ISSUE THREAD

**Issue by NatalCarcass** [sinkillerj/ProjectE#1525]
I have a bunch of forge mods installed and it worked fine, as soon as ProjectE was installed the game would return to the title screen when trying to load or create a world.

**Comment by williewillus** [comment]
logs?

**Comment by JustARegularUser** [comment]
NatalCarcass: Same thing happens to me.
\/Logs\/
[latest.txt](https://github.com/sinkillerj/ProjectE/files/1186618/latest.txt)

**Comment by williewillus** [comment]
use an updated version without the chisel integration
