### ISSUE TITLE
[Version][Request] 1.11 Port

### ISSUE THREAD

**Issue by quixQuery** [sinkillerj/ProjectE#1529]
Requesting port of mod to 1.11.

**Comment by williewillus** [comment]
It's been done for weeks now (and the 1.12 one is done too as of yesterday). Bother @sinkillerj to make a release :P

**Comment by sinkillerj** [comment]
I mean, if you had told me you were ready for one... lol

**Comment by carstorm** [comment]
I consider this a must have mod so would also appreciate the release of the updated versions!

**Comment by sinkillerj** [comment]
A build will be released soon.
