### ISSUE TITLE
Sending game back to title screen on startup

### ISSUE THREAD

**Issue by Goldenshadow86** [sinkillerj/ProjectE#1530]
When I try to load/ make a new world It will just send me back to the main menu. 
Keep in mind im try this on ATLancher hermitcraft modsauce 1 and also on 1.7.10
This is the Logs:
https://pastebin.com/3CXKfkS2

**Comment by williewillus** [comment]
the log has nothing helpful so no idea what the issue is

**Comment by Goldenshadow86** [comment]
What could I send you so you would maybe have an idea?

**Comment by sinkillerj** [comment]
I recommend a full reinstall, something is very very wrong with your setup. 1.7 is also a unsupported minecraft version.
