### ISSUE TITLE
[1.10.2] Blocks in some mods have all the same EMC

### ISSUE THREAD

**Issue by Madcock83** [sinkillerj/ProjectE#1531]
Ive noticed the change since 1.7.10.  Its happened before in other versions.  For example, in extra utilities all the generators have the same EMC value.   IF you craft one of the generators and put it a trans table you get 336 and one of the crafting items it take to make all the generators.  its like this with a few mods.  I tried to look around to see if anyone else said this, but havent seen anything.  

Didnt know if this was a change in 1.10 Minecraft or the way the mod author does there blocks, or a change in projecte that this happens on purpose.  

Just wondering,  I dont see it as an issues on projecte end.  Just wish it was like it was.

**Comment by MaPePeR** [comment]
It's probably related to NBT data.

**Comment by Madcock83** [comment]
Im sure it is.  is there a way i can fix it.  other then setting value for each thing, or is that the only way for now

**Comment by MaPePeR** [comment]
there is no way to fix it and you cannot set a value for "each thing", because EMC-wise they are considered the same thing.

**Comment by Madcock83** [comment]
ok.  was that a minecraft change with 1.10 or projecte?  it makes alot of farms not work anymore.

**Comment by williewillus** [comment]
this was never implement/supported. the mod in question probably changed from meta to NBT

**Comment by pupnewfster** [comment]
1.14+ Has proper support for handling NBT when mapping recipes.
