### ISSUE TITLE
Archangel's Smite crashes when used

### ISSUE THREAD

**Issue by DashGit** [sinkillerj/ProjectE#1532]
_To preface this issue: I've tried reinstalling the Forge server multiple times using the recommended 1.7.10 build. In addition, I'm using the latest build of Project E available. I am aware that apparently this has to do with a library not being present, however since I've tried reinstalling the server multiple times using the latest build (as recommended in other issues) I have no clue what to do._ 

Whenever a player uses an Archangel's Smite, it immediately crashes my Forge server. This also occurs during singleplayer with the client. Both errors are the same, however, and are as follows:

https://pastebin.com/z6p5ixzb

Again, I have tried pretty much everything avaliable about this issue that I've seen to fix it, so I'm at a loss for what to do.

**Comment by sinkillerj** [comment]
1.7.10 is no longer actively supported.
