### ISSUE TITLE
[1.10.2] You can put non-EMC items in the transmutation table

### ISSUE THREAD

**Issue by TheUnderTaker11** [sinkillerj/ProjectE#1533]
I am able to shift click any item into the tablet/table and it promptly tells me it is learned, and deletes the item. It does this for all items, if they have EMC or not. The ones that do have emc are just upright deleted, never to be found again.
Picking up items with my mouse and trying to place them in works exactly like it should though.
ProjectE-1.10.2-PE1.3.0
MC 1.10.2
Forge 12.18.3.2281

**Comment by TheUnderTaker11** [comment]
Upon further testing I am able to confirm it is a bug introduced in the newest version, as downgrading my ProjectE version fixed the problem.

**Comment by sinkillerj** [comment]
Already patched and will be fixed in the next build.

**Comment by TheUnderTaker11** [comment]
Cool thanks, sorry if it would already reported, in hind site I never went to check the closed tickets, only the open ones.
