### ISSUE TITLE
[1.11.2] Industrial Craft cables not supported.

### ISSUE THREAD

**Issue by nicuch** [sinkillerj/ProjectE#1536]
I made ic2 cables have EMC via /projecte setEMC <value> and burned them in a Transmutation Table. The problem is all cables (gold, tin, etc) has the same EMC as copper cable (because is the same item with the same data). When I search for 'cable' in Transmutation Table it gives me 6 types of Copper Cable with different data, but the same item (and I can't craft anyting with it).

**Comment by sinkillerj** [comment]
NBT is not supported at this time.
