### ISSUE TITLE
transforming wool with philosopher stone is cheating

### ISSUE THREAD

**Issue by gendalv** [sinkillerj/ProjectE#1537]
white wool: 48emc, blue wool: 912, philosopher stone rightclick is free all other wool has different emc values too

**Comment by sinkillerj** [comment]
You can change the EMC values if you feel this is too cheaty.

**Comment by gendalv** [comment]
the same is true for villager trading - infinite emc from the emeralds by taking from the table things like wheat, potatos etc.., I'm just not sure it should be this way in the mod by default
