### ISSUE TITLE
[Suggestion] Destruction EMC or Unlearnable EMC or Split buy and sell

### ISSUE THREAD

**Issue by Keaft** [sinkillerj/ProjectE#1539]
Following along with #1015, #1036, and #1478, I would just like to add that I would appreciate such a system.

I'm trying to create a [modpack](https://www.technicpack.net/modpack/tekkhex.1046441) which encourages exploring some of the other mods more so than it does now. As a player I find that I get stuck in a rut following ProjectE to the endgame whilst neglecting other mods. It would be nice to be able to set an EMC value for other mod's blocks and items, but keep them from being learn-able. This would mean that players could more easily explore without losing EMC and without "redirecting" entirely back to ProjectE.

And perhaps that is why I feel like I fall into a rut. I don't feel like the progress in other mods is "saved" in the same way that it is through ProjectE's EMC.

Anywho, Thank you so much for the work that you are doing with this mod. It's been a great source of nostalgia and straight up fun!

**Comment by sinkillerj** [comment]
This is still on the todo list.
