### ISSUE TITLE
Transmutation Table stuck with 64 EMC

### ISSUE THREAD

**Issue by WitnessMyWrath** [sinkillerj/ProjectE#1540]
I´m playing on a 1.1.1 Tekkit Legends Pack and after some Time my Transmutation Table is stuck with the 64 and lower EMC value Items. Clearing all EMC in the Pool and unlearning/learning the Stuff again, doesn't work.

**Comment by sinkillerj** [comment]
Tekkit Legends uses a very outdated version at this point, in addition 1.7 is no longer supported.

**Comment by MaPePeR** [comment]
You probably have an item in the center lock slot?
