### ISSUE TITLE
How can I tell, wich mod/block is crashing my transmutation tablet?

### ISSUE THREAD

**Issue by Norrypt** [sinkillerj/ProjectE#1542]
Recently, I've been searching through my transmutation tablet, when on a specific page, It crashes. I've tried searchin in my crash log, but I couldnt find anything. Help?

[crash-2017-07-12_08.41.47-client.txt](https://github.com/sinkillerj/ProjectE/files/1141122/crash-2017-07-12_08.41.47-client.txt)

**Comment by sinkillerj** [comment]
"forestry.arboriculture.items.ItemGermlingGE" is freaking out because its NBT data is stripped by the tablet. You may be able to solve the problem by putting one in the unlearn slot. As for NBT the NBT whitelist may be an option.

**Comment by Norrypt** [comment]
Where and what do i have to do with NBT whitelist? Im really bad with computer stuff.

**Comment by Norrypt** [comment]
Acctually, wich block is that?
