### ISSUE TITLE
Transmutation table forgetting learned stuff

### ISSUE THREAD

**Issue by RayanR** [sinkillerj/ProjectE#1543]
Hy, when i reinstalled my pc, I lost my old Tekkit Legends world. After a few months, (last week) I reinstalled it. everything went fine until there was a problem with the filesize. I restarted the game and since then i cannot find everything learned from my table. I have over 900K of EMC and i cannot even find my diamonds anymore. i have tried relearning it, but it would not learn. When i unlearned and relearned it again, i couldn't find it. Hope someone can help me.

Greetz
RayanR

**Comment by williewillus** [comment]
tekkit legends is using 1.7.10 ProjectE (and not even the latest one at that). these issues have been fixed in the 1.8+ versions for over a year now, not much I can do besides say "update"
