### ISSUE TITLE
I can't craft the morning star and the katar.

### ISSUE THREAD

**Issue by ORANGEMAGIC** [sinkillerj/ProjectE#1546]
![minecraft report](https://user-images.githubusercontent.com/30281476/28351046-f4d317b8-6c12-11e7-9bba-bbe3b7b68025.png)
![2017-07-18_23 44 36](https://user-images.githubusercontent.com/30281476/28351081-41dbbc04-6c13-11e7-857e-a445d5471563.png)

No matter How I put the recipe nothing comes up to craft, but it seems like other people don't have this issue...

**Comment by ORANGEMAGIC** [comment]
![minecraft report](https://user-images.githubusercontent.com/30281476/28351001-a23dfc16-6c12-11e7-8244-c9c048ad3315.png)

**Comment by sinkillerj** [comment]
Just checked this out in 1.10 and it seams the recipe is not shapeless as it should be. Check JEI for the correct pattern.

**Comment by ORANGEMAGIC** [comment]
![2017-07-19_01 07 43](https://user-images.githubusercontent.com/30281476/28352981-0e1517f6-6c1f-11e7-9cd2-0e1c7f9e75a8.png)
![2017-07-19_01 07 02](https://user-images.githubusercontent.com/30281476/28352984-100e2ffc-6c1f-11e7-9bef-ab48c4441d50.png)
Here's the recipes if any one else need them. P.S. Thanks sinkillerj for the quick response
