### ISSUE TITLE
Game Crashes when in Transmutation Table

### ISSUE THREAD

**Issue by flies12** [sinkillerj/ProjectE#1548]
Every time I go onto the next page in the Transmutation Table my game crashes. Please fix it. Thank you. Here is a YouTube link to the game crashing:
https://youtu.be/mtpWhm68wxw

**Comment by AlexIIL** [comment]
Please can you upload the crash report to [gist](https://gist.github.com/) and post a link to it here? There's probably very little that the devs can do about this without that.

**Comment by sinkillerj** [comment]
Yea pretty much what this guy said ^

**Comment by flies12** [comment]
Someone sent me to upload it here

**Comment by AlexIIL** [comment]
Yes, previously you reported this to the [BC repository](https://github.com/BuildCraft/BuildCraft/issues/3749), however the projectE devs need a bit more information to find out what caused it, so that they can fix it. Some more detail will be in the crash report file, which will usually be in the folder that the game saves world data, configs, and resource packs in.

**Comment by sinkillerj** [comment]
If I had to take a wild guess they learned an item which has render code that crashes if the item lacks a NBT tag. This issue can be worked around by adding it to the NBT whitelist or removing its EMC value altogether. As for the current save the item can be dropped in the unlearn slot to fix it. But thats just a wild guess based on prior issues of this type, and I couldn't even say what the item is without a log.

**Comment by flies12** [comment]
Hi, I just figured out what the problem was, the item that was causing it to crash were the saplings.

**Comment by pupnewfster** [comment]
Closing this, 1.14+ has proper mapping support for NBT so I find it unlikely that an item will be learned and put into a state that has "invalid" NBT

**Comment by flies12** [comment]
That was from 3 years ago.

**Comment by pupnewfster** [comment]
Yes it was, and I am going through and cleaning up issues, so put a comment so that people can see *why* it was closed.

**Comment by flies12** [comment]
I don't know how to find it
