### ISSUE TITLE
Missing EMC and Recipes

### ISSUE THREAD

**Issue by TheGoldenProof** [sinkillerj/ProjectE#1549]
I noticed that some common items are missing their EMC values, like buckets, and other items don't have crafting recipes. The ProjectE items I've found to be missing crafting recipes are the Philosopher's Stone, the MK1 Energy Condenser, each upgraded version of the Klein Star, and the Transmutation Table. The items I have found to just be missing their emc values are due to simple custom crafting recipes with items that don't have EMC, which i fixed with custom emc's, but I lack the knowledge to make custom crafting recipes, and preferable do not want to.

**Comment by sinkillerj** [comment]
We need more info to help you with this issue, such as your MC version, your PE version, and if you are running a particular pack.

**Comment by williewillus** [comment]
if this is for 1.12, fixed in next version
