### ISSUE TITLE
Unequipping evertide amulet from hotbar while standing on water doesn't deactivate it.

### ISSUE THREAD

**Issue by SuperFanatic** [sinkillerj/ProjectE#1552]
When walking onto water with the evertide amulet in your hotbar, it makes you move faster and makes your FOV higher. When walking off the water, the effects go away. If you walk onto water, activating the effects, and then move the amulet into your main inventory and out of your hotbar, the effects stay, even when leaving the water. reequipping the amulet fixes this.

*Versions:*
Minecraft: 1.11.2
Forge: 1.11.2-13.20.0.2253
ProjectE: 1.0.0B

EDIT: Upon entering and exiting a dimension in mystcraft (Which I did NOT have when this problem started), The problem just... disappeared. I... guess that works. 
EDIT 2: Upon playing around, I have found the problem. If you take the evertide amulet out of your hotbar while standing on water, it's effects don't leave like they should. It had nothing to do with the gem boots. Title/desc changed to fit.

**Comment by williewillus** [comment]
not sure what's up. the armor just uses attributes to give the boost, which can be done using nbt on any armor. either another mod or vanilla bug
