### ISSUE TITLE
(1.12) Server Crashes Exception in Server Tick loop

### ISSUE THREAD

**Issue by revdave33** [sinkillerj/ProjectE#1556]
Forge 14.21.1.2442
MC 1.12
ProjectE-1.12-PE1.0.0.B

When I disable ProjectE the server runs fine.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-104.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b98.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 8/7/17 9:56 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(Ljava/lang/Class;Ljava/lang/Object;[Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
	at moze_intel.projecte.utils.ReflectionHelper.<clinit>(ReflectionHelper.java:56)
	at moze_intel.projecte.utils.PlayerHelper.updateScore(PlayerHelper.java:185)
	at moze_intel.projecte.events.PlayerEvents.playerConnect(PlayerEvents.java:101)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_PlayerEvents_playerConnect_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:573)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:258)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:74)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:207)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 881505472 bytes (840 MB) / 3201302528 bytes (3053 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAA	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAA	aroma1997core{1.3.0.0.b98} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b98.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	uncraftingtable{1.8-beta4} [Uncrafting Table] ([1.12]UncraftingTable-1.8-beta4.jar) 
	UCHIJAAAA	actuallyadditions{1.12-r117} [Actually Additions] (ActuallyAdditions-1.12-r117.jar) 
	UCHIJAAAA	aroma1997corehelper{1.3.0.0.b98} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b98.jar) 
	UCHIJAAAA	aromabackup{2.1.0.0.b71} [AromaBackup] (AromaBackup-1.12-2.1.0.0.b71.jar) 
	UCHIJAAAA	aromabackuprecovery{2.1.0.0.b71} [AromaBackuprecovery] (AromaBackup-1.12-2.1.0.0.b71.jar) 
	UCHIJAAAA	autoender{1.0.5.1} [AutoEnderChests] (autoender-1.0.5.1.jar) 
	UCHIJAAAA	quark{r1.2-104} [Quark] (Quark-r1.2-104.jar) 
	UCHIJAAAA	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCHIJAAAA	baubles{1.5.1} [Baubles] (Baubles-1.12-1.5.1.jar) 
	UCHIJAAAA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.12-1.0.1.jar) 
	UCHIJAAAA	cavern{1.9.8} [Cavern] (Cavern_1.12-v1.9.8.jar) 
	UCHIJAAAA	jei{4.7.5.84} [Just Enough Items] (jei_1.12-4.7.5.84.jar) 
	UCHIJAAAA	cyclicmagic{1.7.5} [Cyclic] (Cyclic-1.12-1.7.5.jar) 
	UCHIJAAAA	enderore{1.12-b1} [Ender Ore] (Ender Ore-1.12-b2.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.5.1.jar) 
	UCHIJAAAA	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCHIJAAAA	bigreactors{1.12-0.4.5.34} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.34.jar) 
	UCHIJAAAA	limelib{1.7.5} [LimeLib] (limelib-1.12-1.7.5.jar) 
	UCHIJAAAA	flexibletools{1.2.4} [Flexible Tools] (flexibletools-1.12-1.2.4.jar) 
	UCHIJAAAA	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCHIJAAAA	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCHIJAAAA	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	justenoughbuttons{1.12-1.2.1} [Just Enough Buttons] (justenoughbuttons-1.12-1.2.1.jar) 
	UCHIJAAAA	jeresources{0.8.3.23} [Just Enough Resources] (JustEnoughResources-1.12-0.8.3.23.jar) 
	UCHIJAAAA	mantle{1.12-1.3.1.18} [Mantle] (Mantle-1.12-1.3.1.18.jar) 
	UCHIJAAAA	megaquarry{1.3} [Mega Quarry] (MegaQuarry-1.3-1.12.jar) 
	UCHIJAAAA	moreoverlays{1.12} [MoreOverlays] (moreoverlays-1.12-mc1.12.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.12.jar) 
	UCHIJAAAA	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCHIJAAAA	harvestcraft{1.12c} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12c.jar) 
	UCHIJAAAA	projecte{1.12-PE1.0.0B} [ProjectE] (ProjectE-1.12-PE1.0.0B.jar) 
	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHIJAAAA	reccomplex{1.4.5} [Recurrent Complex] (RecurrentComplex-1.4.5.jar) 
	UCHIJAAAA	rftools{6.12} [RFTools] (rftools-1.12-6.12.jar) 
	UCHIJAAAA	roguelike{1.7.1} [Roguelike Dungeons] (RoguelikeDungeons-1.12-1.7.1.jar) 
	UCHIJAAAA	storagenetwork{1.0.0} [Simple Storage Network] (SimpleStorageNetwork-1.12-1.0.13.jar) 
	UCHIJAAAA	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UCHIJAAAA	stellarapi{0.7.4.1.1} [Stellar API] (Stellar API-0.7.4.1.1.jar) 
	UCHIJAAAA	stellarsky{0.7.5.1.2} [Stellar Sky] (Stellar Sky-0.7.5.1.2.jar) 
	UCHIJAAAA	tconstruct{1.12-2.7.2.15} [Tinkers' Construct] (TConstruct-1.12-2.7.2.15.jar) 
	UCHIJAAAA	theoneprobe{1.4.15} [The One Probe] (theoneprobe-1.12-1.4.15.jar) 
	UCHIJAAAA	thutcore{5.10.1} [Thut Core] (thutcore-5.10.1.jar) 
	UCHIJAAAA	thuttech{6.0.2} [Thut's Tech] (thuttech-6.0.2.jar) 
	UCHIJAAAA	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCHIJAAAA	xnet{1.3.5} [XNet] (xnet-1.12-1.3.5.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-104.jar)
  vazkii.quark.base.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.5.1.jar)
  
CoreMod (Aroma1997Core-1.12-1.3.0.0.b98.jar)
  
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Revdave33'/175, l='August 7', x=-198.50, y=66.00, z=5.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by sinkillerj** [comment]
#1555
