### ISSUE TITLE
[1.12] Loading World crashes with Exception in server tick loop

### ISSUE THREAD

**Issue by Knito58** [sinkillerj/ProjectE#1557]
MC 1.12, Forge 14.21.1.2443, ProjectE-1.12-PE1.0.0B.jar, SSP

Starting up MC works fine but loading a single player world gives an Exception. The file list in cursforge tells "1.12" and "1.12.1". Maybe it is already a 1.121-only mod as it does not find a method? Or is there a dependency to a library which I didn't load?

https://www.dropbox.com/s/rou7jyr6uwqvlwp/crash-2017-08-08_07.00.50-server.txt?dl=1

**Comment by seba745** [comment]
i have this same problem


---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppEngCore (appliedenergistics2-rv5-alpha-2.jar)
  CXLibraryCore (cxlibrary-1.12-1.5.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 8/8/17 12:08 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findMethod(Ljava/lang/Class;Ljava/lang/Object;[Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
	at moze_intel.projecte.utils.ReflectionHelper.<clinit>(ReflectionHelper.java:56)
	at moze_intel.projecte.utils.PlayerHelper.updateScore(PlayerHelper.java:185)
	at moze_intel.projecte.events.PlayerEvents.playerConnect(PlayerEvents.java:101)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_39_PlayerEvents_playerConnect_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:573)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:258)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:74)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:207)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 445503608 bytes (424 MB) / 1108201472 bytes (1056 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 14, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 Optifine OptiFine_1.12_HD_U_C4 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAA	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv5-alpha-2} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv5-alpha-2} [Applied Energistics 2] (appliedenergistics2-rv5-alpha-2.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCHIJAAAA	chesttransporter{2.8.7} [Chest Transporter] (ChestTransporter-1.12-2.8.7.jar) 
	UCHIJAAAA	customnpcs{1.12} [CustomNPCs] (CustomNPCs_1.12.0(22jul17)beta.jar) 
	UCHIJAAAA	cxlibrary{1.5.1} [CXLibrary] (cxlibrary-1.12-1.5.1.jar) 
	UCHIJAAAA	mininglib{1.0.0} [MiningLib] (mininglib-1.12-1.0.0.jar) 
	UCHIJAAAA	dimensionalores{1.12-1.0.1} [Dimensional Ores] (dimensionalores-1.12-1.0.1.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.5.1.jar) 
	UCHIJAAAA	ic2{2.8.14-ex112} [IndustrialCraft 2] (industrialcraft-2-2.8.14-ex112.jar) 
	UCHIJAAAA	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCHIJAAAA	jei{4.7.5.83} [Just Enough Items] (jei_1.12-4.7.5.83.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	lunatriuscore{1.2.0.40} [LunatriusCore] (LunatriusCore-1.12-1.2.0.40-universal.jar) 
	UCHIJAAAA	laserlevel{2.1.0.17} [Laser Level] (LaserLevel-1.12-2.1.0.17-universal.jar) 
	UCHIJAAAA	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.1.3-1.12.jar) 
	UCHIJAAAA	llor{1.1.4-mc1.12} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.4-mc1.12.jar) 
	UCHIJAAAA	mantle{1.12-1.3.1.18} [Mantle] (Mantle-1.12-1.3.1.18.jar) 
	UCHIJAAAA	morefurnaces{1.10.1} [More Furnaces] (MoreFurnaces-1.12-1.10.1.jar) 
	UCHIJAAAA	moreloottables{0.1.0} [More Loot Tables] (moreloottables-1.12.0-0.1.0.jar) 
	UCHIJAAAA	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCHIJAAAA	projecte{1.12-PE1.0.0B} [ProjectE] (ProjectE-1.12-PE1.0.0B.jar) 
	UCHIJAAAA	thutcore{5.10.1} [Thut Core] (thutcore-5.10.1.jar) 
	UCHIJAAAA	thuttech{6.0.2} [Thut's Tech] (thuttech-6.0.2.jar) 
	Loaded coremods (and transformers): 
AppEngCore (appliedenergistics2-rv5-alpha-2.jar)
  appeng.coremod.transformer.ASMIntegration
CXLibraryCore (cxlibrary-1.12-1.5.1.jar)
  cubex2.cxlibrary.CoreModTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv5-alpha-2 for Forge 14.21.1.2412
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['sebia745'/192, l='45', x=0.50, y=239.00, z=-0.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.3408
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by williewillus** [comment]
#1555
