### ISSUE TITLE
Custom EMC Values Issue

### ISSUE THREAD

**Issue by jrdiver** [sinkillerj/ProjectE#1558]
With version "ProjectE-1.10.2-PE1.3.1.jar" there is an issue with transferring the custom emc values between server and clients.  the client side errors if you have a "{" at the beginning of the file server side errors if you do not have it.  I just updated my mod pack and ran into this when trying to copy files around.    See Line 14501 of the attached log file for the specific error.  I also attached the 2 custom emc values files needed to make things work.

PS - Yes i know i have a lot of mods in this pack.

PSS - I did have to re-add a value to the philosophers stone because i changed the recipe to make this mod a bit harder to get into early game.

[ProjectE Bug Files.zip](https://github.com/sinkillerj/ProjectE/files/1207087/ProjectE.Bug.Files.zip)

**Comment by williewillus** [comment]
use this to validate your json files
http://www.jsonlint.xyz/

**Comment by williewillus** [comment]
there should be no difference between whether the json is used client or server side
