### ISSUE TITLE
crash at creating a new world 1.12.1

### ISSUE THREAD

**Issue by JasonKillsUs** [sinkillerj/ProjectE#1560]
"https://pastebin.com/WA1TFHLq"
thanks for looking into it

**Comment by JasonKillsUs** [comment]
upps, forgot 1.12.1 forge 2446

**Comment by jmbjorndalen** [comment]
Getting the same crash here. 

I Added ProjectE and WorldEdit to All The Mods 3 v. 2.8. Forge 1.12, build 2443. 

Client crash (trying in single player): 
https://pastebin.com/cSqV0KuC

Connecting to a running server causes the server to crash, but the client doesn't crash: 
https://pastebin.com/YCUQpHrr

**Comment by sinkillerj** [comment]
#1555
