### ISSUE TITLE
1.12 Some vanilla items doesnt have EMC Value

### ISSUE THREAD

**Issue by MadRatSRP** [sinkillerj/ProjectE#1565]
For example, furnace, chest, glass panels, all types of buckets,ladder.

**Comment by williewillus** [comment]
@MaPePeR probably need your help on this one.
`IRecipe` now stores `Ingredient` instances, which all have an array of possible matching stacks in vanilla.
I tried guessing the correct adaptation for this here https://github.com/sinkillerj/ProjectE/commit/5d05b78bd08775ab4c7e1c00298042d68961662c but obviously something went wrong :P

**Comment by MaPePeR** [comment]
From looking at it i can't see anything wrong with that code. But maybe i'm missing something.

**Comment by Fundryi** [comment]
I think the mapping is not working right.
Vanilla Sample: https://imgur.com/pQ23CVj
Modded Sample: https://imgur.com/IVDZweX
Looks like there is something not working right.

**Comment by Knito58** [comment]
1.12: The vanilla comparator has no EMC value. But the repeater does.

**Comment by Geogiepoegie** [comment]
Looks like most tools are missing values. Armor, buckets, and odd things like signs and wooden stairs also have no value. Strangely, some tools have value, like shovels and swords.

**Comment by Mocha2007** [comment]
I wonder if this has to do with items now being able to be smelted back into nuggets?

**Comment by Knito58** [comment]
Maybe it has something to do with ore-dict entries when ie any wood or any stone could be taken or the recipe has an odd flag....

**Comment by williewillus** [comment]
I figured it out. Due to the internal recipe changes in 1.12, any recipe with partially filled rows broke.
As for the glass panes, those aren't supposed to have values since glass is already worth only 1 emc

**Comment by piotrb** [comment]
Can you release an update for 1.12? seems like a few issues were fixed in the last week, would be good to have a version with those fixes
