### ISSUE TITLE
Some ideas about ProjectE.

### ISSUE THREAD

**Issue by MadRatSRP** [sinkillerj/ProjectE#1567]
Hello, i got 2 questions for you.
1)What about machine/item/multiblock structure that will allow u to convert animal/enemy/other into EMC?
2)Can u add settings in config or addon that will make ProjectE much more harder? For example, armor from black matter/red matter will need coal or something else to prevent breaking just like normal armor.

**Comment by sinkillerj** [comment]
Gonna leave this one up to an addon author.
