### ISSUE TITLE
1.12 Energy Collector Recipe incorrect

### ISSUE THREAD

**Issue by Jczion** [sinkillerj/ProjectE#1569]
Can't make an Energy Collector using the 6 Glowstone 1 Diamond block 1 Glass 1 Furnace recipe.

**Comment by Jczion** [comment]
Never mind, after looking into it with JEI, the recipe has changed to glowstone dust not the block itself.

**Comment by williewillus** [comment]
Actually a bug, I migrated them incorrectly
