### ISSUE TITLE
Game crashes when trying to move through pages in the transmutation table

### ISSUE THREAD

**Issue by TrueDakkon** [sinkillerj/ProjectE#1570]
[crash-2017-08-16_23.15.18-client.txt](https://github.com/sinkillerj/ProjectE/files/1230277/crash-2017-08-16_23.15.18-client.txt)

**Comment by sinkillerj** [comment]
You have learned an item from Forestry which crashes if it does not have its NBT tag. You will need to put another of that item in the unlearn slot.
