### ISSUE TITLE
reloadEMC takes more than 3 minutes and kicks me from server (all the mods 3, 1.12.1)

### ISSUE THREAD

**Issue by jmbjorndalen** [sinkillerj/ProjectE#1573]
I'm trying out ProjectE with All The Mods 3. Reloading the EMC values lags me out of the server both in the 2.8 (1.12) and 3.0 (1.12.1) versions. The culprit seems to be addMappings in CraftingMapper which alone takes well over 3 minutes. The rest is fairly quick (a second or less).

To start to get an idea about the issue (this is the first time I'm looking at the code), I added a few trace counters to the code and added them to the print statements in the method. A dump of the server log from an attempted reloadEMC  is at: 

https://pastebin.ca/3856748

I did it from the server console at the time, with no connected players, but the behaviour is the same with connected players. 

Here's the modified code to show you where the counters were added: 

https://pastebin.ca/3856755

The compiled code was up to date with commit e0b9e6213eab39ccfb3e98d21b9209eb8dca1576. I'm also experiencing this with the latest released versions from curseforge. 

Thanks for a nice mod. I'm enjoying it :-)

**Comment by williewillus** [comment]
79607b6
