### ISSUE TITLE
[1.12] Some of the Rings of Arcana do not have a recipe

### ISSUE THREAD

**Issue by PrinceOfAmber** [sinkillerj/ProjectE#1574]
The blue one has a working recipe, the one with metadata zero, but the red, green, and yellow do not have recipes.

Version ProjectE-1.12-PE1.0.1B

**Comment by williewillus** [comment]
intended, you just use the mode change keybind to switch to the other ones.

**Comment by PrinceOfAmber** [comment]
Okay im just dumb, well thanks for responding so fast!
