### ISSUE TITLE
when u die you Trans tablet is blank

### ISSUE THREAD

**Issue by codydbgt** [sinkillerj/ProjectE#1579]
if u die u cant access your tablet until relog in to the server

**Comment by williewillus** [comment]
version?

**Comment by codydbgt** [comment]
1.11 latest

**Comment by williewillus** [comment]
cannot reproduce with PE alone

**Comment by codydbgt** [comment]
im using bungeecord and sponge try that?

**Comment by codydbgt** [comment]
im almost shure its sponge 

im using 
  Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-c4a7afd
    SpongeForge: 1.11.2-2393-6.1.0-BETA-2549
    Minecraft Forge: 13.20.1.2386

**Comment by TomTheHero** [comment]
It is a visual bug that still exists and requires a relog

**Comment by pupnewfster** [comment]
Unable to reproduce in 1.15
