### ISSUE TITLE
No EMC for chest or furnace

### ISSUE THREAD

**Issue by BlierNicolas** [sinkillerj/ProjectE#1580]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12-PE1.0.1B

Exact Forge version: forge-14.21.1.2443 1.12 (modded)

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): No crash occurred

Steps to reproduce:

1. Start a new Minecraft world
2. Get some wood
3. Get some cobble
4. Craft a chest
5. Craft a furnace
6. Look at the tooltip of the chest and furnace

What I expected to happen: I don't see any EMC for the chest or furnace.

What happened instead: I'm supposed to see the EMC for the chest to be 64 and for the furnace, the EMC is supposed to be 8.

**Comment by williewillus** [comment]
fixed in the next version

**Comment by BlierNicolas** [comment]
Cool! Hope it'll come soon! :) Thank you
