### ISSUE TITLE
Automatic EMC generation for items with all EMC values listed and using normal crafting not being created?

### ISSUE THREAD

**Issue by Darkmega18** [sinkillerj/ProjectE#1581]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
 ProjectE-1.12-PE1.0.1B.jar

Exact Forge version:
14.22.0.2460

There is no crash.

Steps to reproduce:

1. it's literally everywhere.

What I expected to happen: EMC values for most if not all things to be automatically generated, and just having to go through and add emc for new resources from abyssalcraft, voidcraft etc and stuff like mob drops.

What happened instead: Simple things like even droppers and shears are missing values currently until I added them. Where-as some things actually worked, like reliquary standard shots and unenchanted mags. Or some steve carts things are working, but things built with stuff after them, which the could be worked out since all values are present for the parts aren't auto acquired.

Is there still work being done on the automatic generation of emc in the latest 1.12 or is this considered a bug? I am using a fairly large amount of mods. Heres a log file anyway. latest and client latest is in there. I am using a decently large amount of mods.

[logs.zip](https://github.com/sinkillerj/ProjectE/files/1243113/logs.zip)

**Comment by Darkmega18** [comment]
oh. I see there was something closed and there was a fix that you recently made. if thats the one. just reply and let me know then lock this down and I'll just have to wait on it for a bit. Thanks anyway. :)

**Comment by williewillus** [comment]
yeah the really glaring missing values have been fixed

**Comment by Darkmega18** [comment]
Roger. Hope you release it soon then.

**Comment by Darkmega18** [comment]
Will this fix automatic generation of other recipes up and down the line and in mods? I'm mostly waiting on this to be fixed before I continue tinkering and testing my pack that I'm making to play with friends come next month so I know what I need to add values to to get them to mostly all chain react and apply values to each other. Since I don't want to manual fix everything when it hopefully should be fine next version. (so yes, I'm blatantly asking for a new version. only cause it's not an issue I can easily turn aside meanwhile or ignore when I'm going through giving values to stuff. Sorry in advanced. :V)

**Comment by MaPePeR** [comment]
Yes, the fix will affect other emc values.

**Comment by williewillus** [comment]
as far as I know there haven't been any other major issues in 1.12 with ~7k downloads on curse, maybe we can release for 1.12? (@sinkillerj)

**Comment by Darkmega18** [comment]
:D oh! also, one last thing. Chisel support. was that just brought down by this same glitch? since it was supported I think 1.10.2 when i last used projectE just personally, but just now I saw that all the equivalent chisel blocks aren't auto gathering aswell, since I'm on the subject of different things and auto values.

**Comment by sinkillerj** [comment]
Yea ill get a release build out monday or tuesday if I dont get a chance sooner. Things have been a little hectic on my end.

**Comment by Darkmega18** [comment]
All seems to be working great. Thanks guys. :D
