### ISSUE TITLE
Alchemical Bags and Repair Talismans

### ISSUE THREAD

**Issue by LPTogehter** [sinkillerj/ProjectE#1582]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.7.10-PE1.9.3

Exact Forge version: 10.13.4.1492

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): (i cannot show the crash log because the server owner doesnt gives the rights to see that ...)

Steps to reproduce:

1.

What I expected to happen: Repair Talismans shouldnt affect the player while being in the Alchemical Bag

What happened instead: Repair Talismans affect the player and ever let a server to crash from them being in the Alchemical Bag (being them shown as active)

**Comment by williewillus** [comment]
1. 1.7 is no longer supported
2. the talisman affects the bag
