### ISSUE TITLE
[1.12] Klein Stars past Ein are uncraftable. Cheated in stars don't absorb EMC.

### ISSUE THREAD

**Issue by Succubism** [sinkillerj/ProjectE#1583]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.12-PE1.0.1B

Exact Forge version:
1.12-14.21.1.2443

Klein Stars post Ein have no recipe in JEI, are [uncraftable](http://i.imgur.com/YmQSPiO.png) and [don't possess an EMC value](http://i.imgur.com/LOcrh1t.png). They also do not intake EMC from a Transmutation Table.

**Comment by Bass2style** [comment]
semi-reported here (only for the upper tiers ) : https://github.com/sinkillerj/ProjectE/issues/1575
