### ISSUE TITLE
Watch of flowing time needs to be rethought 

### ISSUE THREAD

**Issue by codydbgt** [sinkillerj/ProjectE#1584]
im sure the version doesn't matter in this case but iv tested WOFT on a pedestal and put a tone of them around a flower and takes the server to 10 tps sometime 7 tps ever considered to just allow it to only affect projecte so it doesn't lag the hole server?

**Comment by williewillus** [comment]
that's why you don't do things like that :P 
I'm sure many people find use for it on non-ProjectE machines, so this isn't going to happen
