### ISSUE TITLE
Cant Create klein star zwei

### ISSUE THREAD

**Issue by Junghunlee1** [sinkillerj/ProjectE#1585]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12 beta (ProjectE-1.12-PE1.0.1B.jar)

Exact Forge version: 1.12-forge1.12-14.21.1.2443

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen:
I tried to crafting a klein star zwei with 4 klein star ein
What happened instead:
the recipe didnt show up and i wasnt able to craft the klein star zwei. later i found out there was no recipe to make a klein star zwei or any tier above. i also found out they have no emc value.
![buf](https://user-images.githubusercontent.com/31359995/29736723-07f97e9a-89d2-11e7-93b6-5fdc5834cfb7.JPG)

**Comment by williewillus** [comment]
fixed in next version
