### ISSUE TITLE
Project E Crash while "Starting to collect Mappings" On Server

### ISSUE THREAD

**Issue by FrostboundGamin** [sinkillerj/ProjectE#1586]
Exact ProjectE version:ProjectE-1.7.10-PE1.10.1.jar (Have tried multiple other versions of 1.7.10)

Exact Forge version: forge1.7.10universal.jar (All it says from server hosted website)

Crash Log: https://pastebin.com/nW9GupGm

Everything worked before adding the mod and I have tried other versions of the mod and all crash the game when "Starting to collect Mappings". Text of when crash happens in server boot - https://pastebin.com/eUp5LWRa

**Comment by williewillus** [comment]
if this is a big pack and there's lots of items the mapping might take too long, causing the server management software to kill it. Unfortunately this is 1.7 and is thus unsupported. Try removing some mods
