### ISSUE TITLE
Gem of eternal Density NBT tag limit

### ISSUE THREAD

**Issue by NightPhoenixGH** [sinkillerj/ProjectE#1587]
Exact ProjectE version: ProjectE-1.10.2-PE1.3.1
Exact Forge version: forge-1.10.2-12.18.3.2422-universal

I play on a private server with a modified modpack based on the DNS from ATL, note: this doesn't happen in singleplayer, in fact, i used singleplayer to fix this.

when we returned from the mining dimension to the overworld both of us where kicked from the server and couldn't relog, the error was:
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT that was too big: tires to allocate: (around 2MB)bytes
Where max is (a little less)bytes

**LONG STORY SHORT DOWN BELOW**

there isn't a crash log because the server didn't crash, this was an issue related to the player.
also, for one time when the server kicked me i got an error regarding the netty handler, but i can't find it anymore and it didn't say anything about minecraft so i had no clue what happened.

going into the dimension really far away from home worked, so it wasn't a dimension-wide problem, or a whole server because we could enter all other dimensions.

setting the view distance to 2 we where able to get up to 180 meters from the center of our home, so the issue was in the center of the home, we tried replacing everything that was suspect, but we didn't succeed.

almost out of hope and out of clue i converted the server world to a singleplayer one and i could get into the house, so this is a server-related issue.

**LONG STORY SHORT HERE**

the problem was the 3 gem of eternal density inside the alchemical chest, they exceeded the nbt tag limit of 2 MB because they keep track af all the items that are absorbed, one had more than 22000 characters in the NBT tag (the gem was set to red matter, and we where giving it blocks of 1 to 8 EMC)
i've seen the way the gem keeps the data stored, i'm not really an expert about NBT tags, but why didn't you use Integers or other types of numbers instead of the bytes and limiting every number record to 64?

for anyone that doesn't know the gem of eternal density keeps all the items inside it by writing the name of the block/item and then the number of that object that was absorbed so that SHIFT+right click gives you back all the items, but that number is limited to 64, 1 stack of items, so if you are giving it thousands of low-EMC items it will quickly reach the 2 MB limit.

do you think there is a way to resolve this?

sorry for eventual mistakes/typos

**Comment by Cloudftw** [comment]
go into mcedit and delete the alchemical chest

**Comment by TrueNightPhoenix** [comment]
i didn't really mean that...
mcedit isn't really an option here because of all the modded things, i can just use worldedit, or the singleplayer as i did, i meant resolving this by changing the way the gem is coded.

**Comment by Cloudftw** [comment]
mcedit has the ability to use forge and not delete your modded stuff. also you might be able to remove the gems yourself if you know about nbt editing and how to edit the level.dat

**Comment by williewillus** [comment]
this is a valid issue still, I can get to it soon hopefully

**Comment by TrueNightPhoenix** [comment]
ok, if you really want i could try fixing this, maybe a rought idea

**Comment by pupnewfster** [comment]
A workaround exists in 1.14+ to not send the extra data to the client, as it does not need to see it.
