### ISSUE TITLE
|1.12| one bug, and one suspected bug ?

### ISSUE THREAD

**Issue by Bass2style** [sinkillerj/ProjectE#1588]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12-PE1.0.1B

Exact Forge version: 14.21.1.2443

Modpack and Version : RagnaMod 4, all builds with PE1.01.B, not tested a older version.
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): no crashlog, but a vid. (actually traited by Youtube, should be ready rapidly : https://www.youtube.com/watch?v=v7ZnIyg-VQc

Steps to reproduce:
bug one : weapons are attacking from 2 sides, but not the two others (i dont know how to explain properly, but vidéo should more revelant.), attack any mob in any mode (offensive or all mobs mode), and two of the 4 positions doesn't deal damages.

"suspected bug" : the second thing, is related to "void damages" with the Gem Armor. in 1.10.2, when we have the gem armor, we are not taking void damage, but, in 1.12 we get damages, and die. i dont know if this whas expected or not, so i report it here.

What I expected to happen:
bug 1 : reach the mobs from all sides. xD
"bug 2" : survive when falling into the void.

What happened instead:
bug 1 : only 2 sides are reachable.
"bug 2" : RIP !

i'm going to update the mod to 1.1.0 to see if the bug is persistent, editing this if it's the case or not. xD

edit : mob reach with the weapons is fixed in 1.1.0, nevermind then. :D is void damages expected ?

**Comment by williewillus** [comment]
771995c fixes the first one

the PE armor were never meant to block void damage, so if they did in 1.10 then that's a bug
