### ISSUE TITLE
BodyStone.updateInPedestal crash 

### ISSUE THREAD

**Issue by codydbgt** [sinkillerj/ProjectE#1589]
ProjectE-1.11.2-PE1.0.0B.jar

    Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-c4a7afd
    SpongeForge: 1.11.2-2393-6.1.0-BETA-2549
    Minecraft Forge: 13.20.1.2386

http://public.ntgclan.com/temp/crash-2017-08-30_17.14.46-server.txt

**Comment by williewillus** [comment]
2b682092
