### ISSUE TITLE
Covalence loss not available in the API

### ISSUE THREAD

**Issue by raoulvdberge** [sinkillerj/ProjectE#1593]
I'm using the API to "sell" or "burn" items to get the energy value, however, I can't calculate the covalance loss since it's not in the API.

https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/utils/EMCHelper.java#L272-L282

Thanks.

**Comment by sinkillerj** [comment]
Sorry about this, oversight on my part. I'll try to have it addressed in the next release.

**Comment by Morpheus1101** [comment]
Any further information on this issue?

**Comment by pupnewfster** [comment]
Closed by https://github.com/sinkillerj/ProjectE/commit/d48a3e14073bf8bc1c30dae904af1e14d299d783
