### ISSUE TITLE
(Feature Request?) Auto calculate EMC?

### ISSUE THREAD

**Issue by Templarfreak** [sinkillerj/ProjectE#1595]
I looked through the Wiki documentation and all of the config files and I didn't really see a feature like this. Even the Custom Conversions you still have to apply a conversion to every single item manually. Considering you are able to change EMC on the fly I figured this would be the next-best thing, to automatically calculate what EMC values an item should have. Basically what I mean is:

You change the value to Wood Logs. Project E then automatically, without you having to do so, changes the EMC of Planks, Sticks, and all recipes involving Logs, Planks, and Sticks. There undoubtedly would be conflict and it certainly could not be used to automatically adjust _everything_ but it would still be useful to get 100-150+ items that could be easily calculated to automatically change so that's 100-150 out of 100s of items you don't have to change manually, saving hours of work calculating those EMC values and then setting them. It would probably have to be a toggle in config files or perhaps as a command in-game (Or maybe both).

Just look at Lapis for example. I'm playing on some modpack and one mod uses Lapis in just about 100 different recipes. So if I want to change the EMC value of Lapis, I then have to change the EMC value for every single one of those items manually. They are all just simple crafting recipes that all would really need to be done is subtract the old Lapis value then add the new one.

**Comment by williewillus** [comment]
> So if I want to change the EMC value of Lapis, I then have to change the EMC value for every single one of those items manually.

That's false, automatic value propagation is already done. When giving a new mod values, you should just set values for the base materials of the mod, and they should automatically propagate through crafting table recipes and furnace recipes.
Some mods use their own recipe classes that our mapper cannot read, and that is when the conversion specifications are needed.

**Comment by Templarfreak** [comment]
I doesn't seem to be working on my end then, as I change the value of Wood Logs or Iron or Diamonds and nothing else is affected (Not Sticks or Planks, not Iron or Diamond tools). Everything seems to be enabled in the mapping.cfg already (Perhaps for this modpack, I don't know if that's on by default normally) yet even vanilla Minecraft recipes seem to not be changing.

ProjectE Version: PE1.10.4 for Minecraft 1.7.10
Forge Version: 10.13.4.1614

I am playing a fresh, unaltered copy of Tekkit Classic Reborn on the Technic Launcher. That's the best steps to reproduce I can give unfortunately.

**Comment by sinkillerj** [comment]
TCR uses a modified version of ProjectE in addition to custom scripts, please contact Tencao and the rest of the team for support as directed in the pack itself.
