### ISSUE TITLE
[Suggestion] JEI support for Energy Collectors' transmutations

### ISSUE THREAD

**Issue by Lykrast** [sinkillerj/ProjectE#1596]
Having a JEI page displaying the transmutations made by Energy Collectors (the _Charcoal -> Redstone -> Coal -> Gunpowder -> ... -> Aeternalis Fuel Block_ process) would be a nice addition.

**Comment by pupnewfster** [comment]
This can be closed now. Lily added it and in the next version I fixed it so it actually gets called.
