### ISSUE TITLE
the link for the mod dosent work

### ISSUE THREAD

**Issue by KuraiHasu** [sinkillerj/ProjectE#1599]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.the link dose not work

What I expected to happen: the link to work

What happened instead: the link did not work

**Comment by williewillus** [comment]
which link

**Comment by sinkillerj** [comment]
Older links sometimes work and sometimes dont, no rhyme or reason to it, Curse just being weird. If you are referring to the link in the update notice in game in older versions not much I can do, its hard coded.
