### ISSUE TITLE
[1.12.1] Error on Sapling Transmutation

### ISSUE THREAD

**Issue by ThexXTURBOXx** [sinkillerj/ProjectE#1600]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.12-PE1.1.0.jar

Exact Forge version:
1.12.1-14.22.0.2469

Link to error log:
https://pastebin.com/VYfaReER

Steps to reproduce:
1. Right click any sapling with the Philosopher's Stone

What I expected to happen:
It should at first display the "white square" and transform on right click

What happened instead:
It doesn't display the "white square" and logs the error, which I sent, when I right click the sapling

**Comment by rongineering** [comment]
I also experienced a sapling related error. When trying to condense a forestry teak sapling in the energy condenser, it yielded a different kind of sapling. When that sapling was dropped into the world, upon trying to pick it up, it caused a Failed to handle packet error with an NBT has no genome error. The full log can be seen here: https://www.reddit.com/r/FeedTheBeastCrashes/comments/71yf1v/crashed_out_of_custom_server_and_cant_log_back_in/
ProjectE version 1.12-1.1.0
