### ISSUE TITLE
Mod incompatibility?

### ISSUE THREAD

**Issue by grimmlinix** [sinkillerj/ProjectE#1602]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.7.10-PE1.10.1.jar

Exact Forge version:10.13.2.1298

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/7eMrm7hz

Steps to reproduce:

1.

What I expected to happen: Load up the world with the blightfall modpack with this mod installed as well.

What happened instead: Crash to main menu anytime I try to load the world.

**Comment by williewillus** [comment]
There is no useful error information in the log so not sure what it is. Make sure you posted the fml log not the vanilla latest.log

**Comment by sinkillerj** [comment]
Regardless, 1.7 support has been dropped.
