### ISSUE TITLE
Klein Star + SWRG doesn't empty Klein Star

### ISSUE THREAD

**Issue by braddr** [sinkillerj/ProjectE#1603]
While flying, the ring sips away energy from the Klein Star.  When the star gets to having less than the 64 emc that the ring sips, it won't take the last little bit.

I suspect the problem is here:
https://github.com/sinkillerj/ProjectE/blob/0569ca43649ba1260fe8595691f901496bb6a114/src/main/java/moze_intel/projecte/gameObjs/items/ItemPE.java#L81

Shouldn't that be 
  double consume = EMCHelper.consumePlayerFuel(player, current);
?  Of course, that leads to questioning the removeEmc call later on line 93.

There may be some subtleties that I haven't seen due to mostly just quickly scanning through the code, but would a code flow like this work:

if (amount <= 0) return true;
double current = getEmc(stack);
if (amount > current) amount = current;
double consume = EMCHelper.consumePlayerFuel(player, amount);
if (consume == -1) return false;
addEmcToStack(stack, consume);
if (shouldRemove) removeEmc(stack, consume);
return true;

**Comment by pupnewfster** [comment]
I tested it and in the latest 1.12 version this is working properly now. (Not sure when it got fixed, but this can be closed)
