### ISSUE TITLE
[1.12] PE 1.1.0 Condenser forget settings

### ISSUE THREAD

**Issue by Alcalyne** [sinkillerj/ProjectE#1606]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): PE 1.1.0 for MC 1.12.1

Exact Forge version: Forge 14.22.1.2485 for MC 1.12.1
(i added PE 1.1.0 to "All the mods 3" modpack v3.3)

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): not a crash issue, but when logging in to the world i get this error on the console (referred to almost every mod in the pack):
`[15:14:38] [Server thread/ERROR]: Skipping event FMLServerStoppedEvent and marking errored mod projecte since required dependency forge has errored
`

Steps to reproduce:

1. set up a condenser (insert something in the top left slot)
2. close minecraft
3. re-open minecraft and re-open the world

What I expected to happen:
the condenser remember its settings

What happened instead:
it forgets what is used for, the top left slot is empty and i need to re-set it

**Comment by sinkillerj** [comment]
Thats not a full log, and it sounds to me like minecraft did not close naturally, you should always close all guis then save and quit.

**Comment by Alcalyne** [comment]
that was an error re-opening the world after an usual "save and quit to title"
if you want, i could upload the full log, but i didn't see any error that could refer to my problem
