### ISSUE TITLE
Unable to craft Energy Collector MK1

### ISSUE THREAD

**Issue by delorean1** [sinkillerj/ProjectE#1609]
Exact ProjectE version: 
1.12-PE1.1.o
Exact Forge version:
1.12.2-14.23.0.2491
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
Not related to crash
Steps to reproduce:

1.Energy Collector MK1 not created with proper craft.

What I expected to happen:
Attempted to craft MK1 Energy Collector with Furnace, Diamond Block, Glass Block, and Glowstone, and also attempted to use glowstone powder 
What happened instead: Unable to craft MK1 Energy Collector

**Comment by sinkillerj** [comment]
Have you verified that you are using the correct recipe via JEI? Are you playing as part of a pack which may have changed the recipe?

**Comment by delorean1** [comment]
Installed JEI mod and found the recipe calls for a single diamond and not a diamond block. Thanks for the recommendation, I feel dumb not checking that myself. Original EE2 was a diamond block, and I just assumed. THANKS SO MUCH!!!

**Comment by williewillus** [comment]
single diamond is actually a bug, it should be a diamond block
it'll be fixed in the next version.
