### ISSUE TITLE
Ore dictionary equivalent ingots have separate EMC values

### ISSUE THREAD

**Issue by Mawootad** [sinkillerj/ProjectE#1610]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.10.2-PE1.3.1

Exact Forge version:
12.18.3.2488

Modpack:
DNS Techpack v10.3.0.4

Steps to reproduce:
1. Open inventory for NEI screen
2. Create a Mekanism and Thermal Expansion steel ingot
3. Note that the Mekanism ingot has an EMC value of 512 and the Thermal Expansion ingot has an EMC value of 256
4. Verify that putting the ingots into a transmutation table gives the listed EMC value and that running the ingots through an ore dictionary converter changes the EMC value of the ingots

What I expected to happen:
Ingots that are equivalent according to ore dictionary have different EMC values

What happened instead:
Ingots that are equivalent do not necessarily have equivalent EMC values. This can lead to extremely early and powerful infinite EMC generation loops when certain mods are enabled.

Suggested fix:
When generating EMC values check if there are any ore dictionary aliases with lower EMC values. If there are, use the lower EMC value instead of the EMC value computed from the sum of the parts.

**Comment by pupnewfster** [comment]
Closing as I don't believe this is an issue anymore after the rewrite in 1.14 to handling tags (vanilla's equivalent of the oredictionary).
