### ISSUE TITLE
1.11.2-PE1.0.0B Crash while Ore Excavating on Dedicated Server

### ISSUE THREAD

**Issue by kreezxil** [sinkillerj/ProjectE#1612]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.11.2-PE1.0.0B

Exact Forge version:
13.20.1.2530

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
crash report:
https://gist.github.com/dc75bdc07b2c483b6d233410fe10d6c3

fml server latest:
https://gist.github.com/f95a544eef8112c66e111520771cc82c

Steps to reproduce:

1. Make sure Forestry is installed
1. Equip the Red Katar
1. Chop any Forestry leaf block
1. Dedicated server will crash.

What I expected to happen:
I assume they were "vein mining" using the Ore Excavator mod and something just went haywaire.

What happened instead:
Dedicated Server Crash

Notes:
I'll reference Ore Excavation as it is also implicated the crash report.

**Comment by kreezxil** [comment]
The player that caused the crash got on and I updated the open bug report steps to reproduce. It is very reproduceable.

**Comment by BenjaminUrquhart** [comment]
I think the red katar also has its own vein mining ability which is conflicting with ore excavator. I could be wrong.

**Comment by pupnewfster** [comment]
Unable to reproduce this in 1.15. My guess is the internal rewrite to tools I did in 1.14 fixed this.
