### ISSUE TITLE
Move to update jsons/forge update checker

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#1613]
The "add a new file each major mc version" thing is not going to last

Also I want to get rid of master branch and just have default versioned branches like Forge and Twilight Forest

Also I want to get rid of the parsing logic and just have forge do it for us.

Doc: https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/

Basically, the changelog will just go into a different file each update. Examples linked on the doc page above.

**Comment by sinkillerj** [comment]
While it would be great to be on a standardized system the formatting of this file is frankly a mess. It kills human legibility and forces restrictions like having to \n for a new line.

**Comment by williewillus** [comment]
I would just put a link to the curse page where the real changelog is

Or maybe I can PR to Forge to let it support arrays of strings for the changelog

**Comment by sinkillerj** [comment]
Hmm, yea that would work, we dont really need the changelog in game when they can just click the link.

**Comment by williewillus** [comment]
Cool here's what's happened:

* Moved to update JSON format
* Made build.gradle automatically update the update.json every build (this will need to be committed and pushed)
* The update checker ingame only runs on the client now (when was the last time a server owner actually reads their logs when not crashing?), and no longer provides the changelog, just a link to curse
* The update.json links now point to the 1.12 branch, whenever we port we'll have to update these URL's

So now, what'd be nice is if the default branch of the repo is set to 1.12 and we can just forget about the master branch (we can leave it up so the old update checker doesn't error or we can just delete it). And from now on we use branches named after mc versions instead of trying to dump everything into master.

**Comment by williewillus** [comment]
all we have to do now is set 1.12.x as the default branch on github then we'll be good
