### ISSUE TITLE
ProjectE allows machinery to pull from ghost slots in the Energy Condenser(Produced with XNet)

### ISSUE THREAD

**Issue by moonheart08** [sinkillerj/ProjectE#1614]
Exact ProjectE version: 1.10.2-PE1.3.1

Exact Forge version: 12.18.3.2422

Steps to reproduce:

1. Attempt to pull items from a Energy Condenser via XNet cables.
2. Realize XNet unset the target by trying to remove it.

What I expected to happen: Red Matter be pulled out without removing the ghost item (target)

What happened instead: the ghost item (target) gets removed.

**Comment by sinkillerj** [comment]
Mod is not obeying canTakeStack, take it up with them.

**Comment by williewillus** [comment]
Does this happen in 1.12?
The lock slot is not exposed to automation at all so I don't know how xnet can get to it
