### ISSUE TITLE
Dark Matter has no EMC value

### ISSUE THREAD

**Issue by Willco2** [sinkillerj/ProjectE#1615]
Exact ProjectE version: ProjectE-1.10.2-PE1.3.1

Exact Forge version: 12.18.3.2185

Link to crash log: Not a crash, [explanation image](https://imgur.com/a/Z4RNX)

Steps to reproduce:

1. Open up any world in creative
2. Give yourself dark matter through the creative inventory
3. Look at tooltip of dark matter
4. See that dark matter has no EMC value

What I expected to happen: Dark matter should have had an EMC value of 139,264

What happened instead: Dark matter has no EMC value and cannot be obtained in any way other than by cheating

**Comment by pupnewfster** [comment]
I believe this can be closed now
