### ISSUE TITLE
[Request] Auto focus on search when using the tablet

### ISSUE THREAD

**Issue by MichaelHillcox** [sinkillerj/ProjectE#1616]
Small request for the mod. It would be great if when you have a search field on a Gui it would auto focus on that search field to reduce the amout of clicking you have to do. Just a suggestion :D A quality of life sorta thing.

I did a quick search and couldn't find any related issues so hopfully it hasn't been suggested before.

**Comment by sinkillerj** [comment]
While it would be convenient in some circumstances this change would cause more annoyance than good. For example what happens if you accidentally interact with the tablet and want to quickly exit instead?

**Comment by MichaelHillcox** [comment]
In that instance you'd still have to press esc which would exit the table and the field in the same way that you'd always have to? I understand your point but I don't think it would affect it that much. It's a lot like AE if you've ever played it. When you click on the interface you are instantly focused on the input so you can find items as quickly as possible.

**Comment by sinkillerj** [comment]
That works if you press ESC, but its much faster to just press E.

**Comment by williewillus** [comment]
I hate gameplay config creep but this is a QOL thing so I'm fine with this being a config option :P

**Comment by MaPePeR** [comment]
sinkiller: but pressing E is not reliable, if you focused the search bar before. So easy to mess up in a panic situation.

**Comment by MichaelHillcox** [comment]
Personally I use esc on almost all interfaces because it's a sure fire way to get out of the Gui. I'm sure some people use E but if you're already on the search input then you'll have to use Esc no matter what :D
