### ISSUE TITLE
Dark Matter and Red Matter Tridents (Enhancement Suggestion)

### ISSUE THREAD

**Issue by GlitchReaper** [sinkillerj/ProjectE#1621]
With news of Tridents from Minecon Earth it may be time to consider Dark Matter and Red Matter versions for them. I think they would gain further reach (and damage) when charged and would have the ability to return to their thrower built in (since you couldn't enchant them due to ProjectE rules).

**Comment by RazeSoldier12** [comment]
Just for record you actually can't enchant red/dark matter tools. LOL -_-. So I don't think that this will happen to tridents :( sadly.

**Comment by pupnewfster** [comment]
Closing this as it was decided this does not fit into ProjectE's goals of replicating EE2, but is included in an addon I made that adds Dark and Red Matter Tridents and Shields. https://www.curseforge.com/minecraft/mc-mods/projectextended
