### ISSUE TITLE
[1.12.2] OreDict error on clearOldAoE

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#1622]
Exact ProjectE version: 1.12-PE1.1.0
Exact Forge version: 14.23.1.2554
https://paste.ee/r/Ujtfe

Steps to reproduce:
1. Use red katar on wood

What I expected to happen: cut trees
What happened instead: error

Since the log doesn't link exactly to the right line of code (might be something after being compiled), I think it's referring to this line, https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/items/tools/PEToolBase.java#L129

**Comment by pupnewfster** [comment]
I think this can be closed. I believe this has been fixed at some point as I am unable to reproduce with the latest 1.12 version, and the crash report is no longer displaying so it is hard/impossible to track down now.
