### ISSUE TITLE
CTD on mouseover of bucket in transmutation table

### ISSUE THREAD

**Issue by trevorjd** [sinkillerj/ProjectE#1624]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12-PE1.1.0

Exact Forge version: forge-1.12.2-14.23.1.2555

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/3jfK37WF

Steps to reproduce:
I put three buckets into the table. One empty, one "clay bucket" and one of Thermal Expansion's "Energised Glowstone".
1. Search "bu" or "buc"
2. Three buckets appear. One clay, two metal.
3. Mouseover the clay bucket, no problem. Tooltip renders correctly.
4. Mouseover one of the metal buckets, CTD.

As a related aside, the lava bucket doesn't have an EMC value. Don't know if that's an oversight on your part or a slip-up from our back author. We're running Wikipack-3 on the official FTB wiki server.

edit: From the crashlog, it looks like it could be an xmod issue with "mist". I'll pull that and see if I can replicate it soon(TM).

**Comment by Hubry** [comment]
The second mod in question is [Misty World](https://minecraft.curseforge.com/projects/misty-world), by the way. (And the modpack used is [this one](https://minecraft.curseforge.com/projects/wikipack-3).) Probably worth posting on that issue tracker as well?

**Comment by sinkillerj** [comment]
One of the items is missing a NBT tag that Misty World expects, I assume the Clay Bucket belongs to that mod, or that it overrides the vanilla bucket. Whatever item is the issue you will need to add to the ProjectE NBT whitelist or remove its value so it cannot be placed in the table. A alternative would be Misty World adding code to handle NBT tags being missing when rendering.

**Comment by Liahim85** [comment]
Hi! It's already fixed in MistWorld_1.12.1_alpha_b_02.jar
