### ISSUE TITLE
Volcanite Amulet has no EMC value

### ISSUE THREAD

**Issue by trevorjd** [sinkillerj/ProjectE#1625]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  ProjectE-1.12-PE1.1.0

Exact Forge version: forge-1.12.2-14.23.1.2555

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. Mouseover volcanite amulet
2. Observe lack of tooltip indicating EMC value

What I expected to happen:

What happened instead:

**Comment by sinkillerj** [comment]
This one should be fixed once I push out a new update. If its not feel free to comment.
