### ISSUE TITLE
Philosopher's Stone smelting recipes do not use Ore Dictionary

### ISSUE THREAD

**Issue by Zsashas** [sinkillerj/ProjectE#1630]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.1.0

Exact Forge version: 2565

There are separate recipes for each individual type of wood log, which both creates an unnecessarily large number of recipes, but also skips any not specifically added. Just use logWood.

**Comment by williewillus** [comment]
I don't want to make this more complicated than it needs to be.

the philstone "smelting crafting" recipes simply iterate through the smelting recipe list and add a crafting recipe per furnace recipe found, I don't see the benefit of trying to hunt around and unify the recipes, which will bloat the complexity of the code for miniscule gain

**Comment by Zsashas** [comment]
Makes sense. I guess the Twilight Forest logs don't have a smelting recipe for whatever reason, then. If I were to add one with CraftTweaker, would it then get added to the stone's recipes?

**Comment by Zsashas** [comment]
Ok, so apparently it's deeper than that. There are only two types of recipes for charcoal using the Stone. One uses all of the vanilla logs interchangeably, and then there's EVERY SINGLE ONE of the log types added by Misty World. That's like 20 pages of recipes right there. However...not a single other modded block is supported by this. Not one.
