### ISSUE TITLE
IItemEmc assumptions

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#1632]
IItemEmc assumes klein star in many cases

**Comment by williewillus** [comment]
@Mordenkainen what did you mean by this on IRC? I just looked through everything and all usages of IItemEmc strictly use the interface and don't cast to klein stars blindly

**Comment by Mordenkainen** [comment]
I'm working on a PR now.

**Comment by williewillus** [comment]
#1634
