### ISSUE TITLE
Transmutation Table's EMC saved as a BigInteger

### ISSUE THREAD

**Issue by thefnitalian** [sinkillerj/ProjectE#1636]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen:

What happened instead:

**Comment by williewillus** [comment]
> Tickets that do not conform to this template will be closed without comment

Please update the ticket body to have some details and I will reopen
