### ISSUE TITLE
Black hole band doesn't work as intended

### ISSUE THREAD

**Issue by CedKilleur** [sinkillerj/ProjectE#1639]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version : ProjectE-1.12-PE1.2.0 

Exact Forge version: 14.23.1.2590

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): no crash log

Steps to reproduce:

1.

What I expected to happen: Black hole band sucks item in alchemical bag

What happened instead: Black hole band doesn't do anything when in alchemical bag

**Comment by TeamSpen210** [comment]
This would be fixed by 800a9edc913a29e7e4499c14d72c06dda8b4773d.
