### ISSUE TITLE
How to set EMC value..?

### ISSUE THREAD

**Issue by SupremeHo** [sinkillerj/ProjectE#1640]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.10.2-PE1.3.1

Exact Forge version: 12.18.3.2422

![base profile screenshot 2018 01 22 - 10 07 24 60](https://user-images.githubusercontent.com/35357925/35201196-c233b0fa-ff5c-11e7-8449-83f543eb6dcc.png)

I'm modpack player and I'm from S.Korea (not N.Korea). I play well with your mod. But.... Do you know how to set EMC values to Steel Ingot (from Thermal Foundation)? I cannot see steel ingot's EMC values. Can you help me?

**Comment by sinkillerj** [comment]
Example with the item in your hand:
/projecte setemc 256
/projecte reloademc

**Comment by SupremeHo** [comment]
Thanks for your help.

**Comment by Tntdruid** [comment]
/projecte setEMC or you get a error msg

**Comment by TrueMainer** [comment]
It doesn't work for me if I use the ID and I'm having trouble with anything with 2 words in it. I'm also on 1.7.10

**Comment by Hyalus** [comment]
> It doesn't work for me if I use the ID and I'm having trouble with anything with 2 words in it. I'm also on 1.7.10

If you hit F3 + H it shows the game name of it so glass would be minecraft:glass

**Comment by Nabtheman** [comment]
Does this work on servers? or is it only client sided?

**Comment by OrderlyMess** [comment]
> 

This is a vanilla minecraft thing. I think it's called Advanced Tooltips

> Does this work on servers? or is it only client sided?
