### ISSUE TITLE
Harvest Goddess Band harvests sugar cane with too low height

### ISSUE THREAD

**Issue by liquid600pgm** [sinkillerj/ProjectE#1641]
Exact ProjectE version: 1.10.2-PE1.3.1

Exact Forge version: 12.18.3.2511

Link to crash log: [Not a crash]

Steps to reproduce:

1. Place the band on a DM Pedestal.

2. Place sugar cane around it.

3. Activate the band.

What I expected to happen:

I expected that my sugar cane would grow up to 5 blocks up.

What happened instead:

The sugar cane grew up to 3 blocks.

My suggestion is to add a line in the config that allows to configure the checking height.

**Comment by williewillus** [comment]
it grows up to the height sugarcane naturally grows up to, which is 3.
5-high sugarcane is rare and only occurs during worldgen

**Comment by liquid600pgm** [comment]
@williewillus but, if you played the original Equivalent Exchange 2, the band allowed sugar cane to grow up to 5 blocks.

**Comment by sinkillerj** [comment]
That was more than likely a bug at the time. IMO a sketchy implementation is not worth sugar cane growing a little taller.
