### ISSUE TITLE
Increase max EMC for Transmutation Table?

### ISSUE THREAD

**Issue by chimericdream** [sinkillerj/ProjectE#1645]
Exact ProjectE version: applicable to all 1.12.x versions
Exact Forge version: n/a

I came here looking for info about the max EMC in the transmutation table, because I thought it was surprisingly low at ~1 billion. I see that the value is hard-coded in the [Constants.java file here](https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/utils/Constants.java#L16), and I also saw #1594, in which it was mentioned that changing the max value would require a major refactor.

In my brief looking around at where the constants are used and how the object dependencies are structured, it looks to me like it would be a simple matter of changing the constant to use `Integer.MAX_VALUE`, which would double the amount of EMC available. That said, I am certainly not familiar with the code base, so I'm curious what other refactoring would be necessary to change the limit.

**Comment by TomTheHero** [comment]
Id prefer a config to set a custom amount as i'd prefer only a couple millions

**Comment by cjburkey01** [comment]
The issue is that above a billion is beyond Java's capabilities with 32 bit ints, switching to a 64 bit long would fix the problem but would require a good amount of changes, I imagine.

**Comment by TomTheHero** [comment]
I really need the ability to drop the value

**Comment by thefnitalian** [comment]
You have to go into the actual jar file and within that there is a file that determines the max emc the table can take and you can set that lower.

**Comment by thefnitalian** [comment]
Also, how much refractoring would it require to change to a Long?

**Comment by cjburkey01** [comment]
It would require rewriting the NBT system, it only supports integers and floats, not longs or doubles.

**Comment by TomTheHero** [comment]
@thefnitalian Would you mind giving me the path to that file as i cannot find it

**Comment by TomTheHero** [comment]
I very badly need to know this ^^
Either someone tells me it or i am forced to ban the transmutation table

**Comment by chimericdream** [comment]
@TomTheHero the specific spot where the max EMC is set is [here](https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/utils/Constants.java#L16), but you'd have to recompile the mod yourself. And if you have a public modpack through Curse (or some other launcher), you'll probably have to remove ProjectE from the official pack and direct your users to a _private_ location where they could download the patched mod to manually add to the pack.

It might almost be simpler to write a second mod that replaces the transmutation table with a custom version that allows you to control the EMC value.

**Comment by williewillus** [comment]
That specific constant will be lifted when I get around to it (so soon)
As for going to lungs and doubles, not happening.

**Comment by thefnitalian** [comment]
So, to be clear, @williewillus , the max emc value for the table will not be raised because it, as @cjburkey01 put it, would require rewriting the NBT system which only accepts integers and floats. This raises the question of what is the biggest integer or float that it could be without causeing too much of a coding headache?

**Comment by cjburkey01** [comment]
`2,147,483,647` ((2^31)-1) is the largest value an `int` may take, which is still larger than the current constant.

**Comment by TomTheHero** [comment]
@chimericdream I cannot compile it myself but only my server should need it so could you by any chance change the max stored EMC in a transmutation table to 1 million and compile it for me?

**Comment by BenjaminUrquhart** [comment]
@TomTheHero replace Integer.MAX_VALUE by your number (must be less than 2,147,483,648)

**Comment by TomTheHero** [comment]
It turns out that the edited version is also required on the client which would require a re-upload on curse or a a new config to be added

**Comment by fan87** [comment]
to write into NBT System just save it as string and every time it loads just toString...
its not a big problem
and I know this thread is outdated

**Comment by BenjaminUrquhart** [comment]
@fan87 ok but why comment on a closed issue from 3 years ago
