### ISSUE TITLE
Worlds not loading with edited config 1.12.2

### ISSUE THREAD

**Issue by TomTheHero** [sinkillerj/ProjectE#1647]
ProjectE-1.12-PE1.2.0.jar

forge-14.23.2.2611

https://www.dropbox.com/s/v3ivwndcgfuxdv4/latest.log?dl=0 

Worlds refuse to load.

Steps to reproduce:

1. Use this config https://www.dropbox.com/sh/q0cwhpqm8qqna4o/AACHQ-_vcxZ03-Cx7BvOGZNra?dl=0

**Comment by sinkillerj** [comment]
Firstly I see you are using a premade modpack, so this may be a conflict with one of their crafttweaker scripts as I see its putting out several errors. Beyond that what is it you changed from the packs default config?

**Comment by TomTheHero** [comment]
Idk anymore what i exactly changed but it is my own pack and there are currently no crafttweaker scripts yet

**Comment by TomTheHero** [comment]
Other crash with a the default config: https://pastebin.com/JGvYffjY

**Comment by TomTheHero** [comment]
Here is yet another one https://pastebin.com/43iw8tfj

**Comment by TomTheHero** [comment]
I am not trying to be rude but are you gonna do something to fix all of those issues or not because i cannot include this in the modpack and server right now because it is simply too unstable

**Comment by williewillus** [comment]
Something in your pack is still interfering.
Everything looks fine here with just Forge+PE: https://imgur.com/a/GOynD

**Comment by TomTheHero** [comment]
All of those issues do not always occur, but at random and once a world has been generated successfully that part is fine

**Comment by sinkillerj** [comment]
I'm gonna have to peg this on one of the obscure mods in your pack doing asm tweaks, I simply cannot reproduce the issues you are experiencing. Beyond this your initial log is over 300 megs which put simply should not happen, you have much bigger issues than the occasional ProjectE crash.

**Comment by TomTheHero** [comment]
Only projecte runs into issues for as far as i am aware and if you want i can give you a download for the pack

**Comment by TomTheHero** [comment]
@sinkillerj If i do not get helped with this i will have to leave projecte out of my modpack and server for many many crashes ontop of the already MANY existing issues and for breaking singleplayer world creation.

**Comment by TomTheHero** [comment]
And only your mod runs into all those issues
