### ISSUE TITLE
Volcanite / Evertide amulets won't work outside the hotbar.

### ISSUE THREAD

**Issue by Lion4K** [sinkillerj/ProjectE#1648]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  1.12-PE1.2.0

Exact Forge version: 12.23.2.2611

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): no crash

Steps to reproduce:

1. place volcanite or evertide amulet on inventory

What I expected to happen: work (walk on lava / water)

What happened instead: don't work. only if I put on hotbar.

This is more like a feature request.
To make the amulets work even outside the hotbar, thou idk if they were meant to work or not.

Sorry if this is a bad place to ask.

**Comment by sinkillerj** [comment]
This is a intentional limitation.

**Comment by Lion4K** [comment]
And is there plans to add support to multiple hotbars?
![image](https://user-images.githubusercontent.com/10391955/36214865-aa6aded4-1191-11e8-9b83-1aba01a27872.png)

**Comment by sinkillerj** [comment]
What mod are you using for that 2nd hotbar? I can look into supporting it.

**Comment by Lion4K** [comment]
Theres 2 mods you can possible support.

This one i'm using on the pic is just aesthetics as it just shows whats on the 3rd row and you can press a key to flip bars, so you would basically have to enable amulets on the inventory to support it.
Its a lite loader mod.
http://www.liteloader.com/mod/exthotbar

And theres this other one that I tried too that adds an actual 2nd hotbar. (i stopped using bc I went to try the liteloader one, and since neither affected the amulets I just left that one since it was already there).
https://minecraft.curseforge.com/projects/multi-hotbar
https://minecraft.curseforge.com/projects/multi-hotbar-core

**Comment by Lion4K** [comment]
Hmm, i Just figured out that both mods only render whats on the inventory. It doesn't actually make hotbars, i mean, extend the inventory capacity.

Well, seems both mods you would be needing to enable amulets to be used of inventory for this to work.
