### ISSUE TITLE
ProjectE Commands do not work

### ISSUE THREAD

**Issue by tbearminer** [sinkillerj/ProjectE#1653]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version: forge-1.12.2-14.23.2.2618-universal

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): No Crash

Steps to reproduce:

1. Type /ProjectE

What I expected to happen: Subcommands to come up

What happened instead: 0 Subcommands exist

**Comment by williewillus** [comment]
the command is `/projecte`
