### ISSUE TITLE
1.7.10 ProjectE-1.7.10-PE1.10.1 Pedestal+Watch of time Crash (mod interaction)

### ISSUE THREAD

**Issue by Reginald-Halifrax** [sinkillerj/ProjectE#1655]
In interaction with Architecture craft from Greg Ewing, a pedestal with a time watch crashes (and infact hardlocks the save) when interacting with shape blocks, in this case it was a cobblestone sphere.

this was fixed by removing architecture craft and reloading the save, but if someone else builds a house with AC and locks the server, the damages could be severe.

I kinda doubt I'll get a fix to this seeing as it is 1.7.10, so if I have to just disable the "Time pedestal" I will. But a reports a report.

https://www.dropbox.com/s/t8ajlmbai41v099/crash-2018-03-04_15.19.17-server.txt?dl=0

**Comment by MaPePeR** [comment]
This bug is probably better fixed on architecture craft's side, because there are other mods beside ProjectE that speed up tile ticking like the watch does.

**Comment by Reginald-Halifrax** [comment]
Wish i could get ahold of him, but last time he did anything was already nearly half a year ago iirc

**Comment by sinkillerj** [comment]
I agree with Blub, this sounds a bit strange and unlikely to be on the ProjectE side. Unfortunately the mod in question also seams closed source which makes investigation difficult.
