### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by evernife** [sinkillerj/ProjectE#1658]
ProjectE version : `ProjectE-1.10.2-PE1.3.1.jar`
Exact Forge version: `Forge 12.18.3.2477`
Link to crash log: **https://pastebin.com/J7MDdTes**

Steps to reproduce:
1. Start the server

What I expected to happen:
The server to start

What happened instead:
The server crash

-----

I need to point out that the server at some point get to start.

So, the crash happens like 4 to 5 times, and then, the server start. Everytime i restart the server, it happens again, "startup, crash a few times, and then really starts"

**Comment by MaPePeR** [comment]
Disable watchdog or increase timeout.

**Comment by williewillus** [comment]
^ do that in server.properties

This specific issue should be fixed in later versions of PE for 1.12

**Comment by evernife** [comment]
> Disable watchdog or increase timeout.

On the mod config
