### ISSUE TITLE
[Request] Configurable conversion efficiency

### ISSUE THREAD

**Issue by BenGoldberg1** [sinkillerj/ProjectE#1661]
At present, transmutation is 100% efficient.  If you put ten diamonds into your transmutation table, you can pull ten diamonds out.  Allow the mod to be configured so that some percentage of EMC is lost when items are put are put into the table.  So if my server is configured to be 90% efficient, and I put in ten diamonds, I'll only be able to pull nine out.

Making the efficiency lower obviously makes ProjectE less powerful, **but** since many see it as _overpowered_ at present, this would make it more attractive to include in modpacks.

Also, you might allow different efficiencies on the table, the tablet, the condenser, and the condenser mk2.

**Comment by williewillus** [comment]
this already exists, does it not? see the "covalenceLoss" option in the configs
