### ISSUE TITLE
ProjectE and spongeforge luckperms

### ISSUE THREAD

**Issue by cyris69** [sinkillerj/ProjectE#1662]
Exact ProjectE version: ProjectE-1.12-PE1.2.0
Exact Forge version: forge-1.12.2-14.23.2.2611-universal
SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2970
LuckPerms version: LuckPerms-Sponge-4.1.44

I'm trying to update EMC values for things that don't have any, however, with LuckPerms if I was to type this while item is in hand /projecte setEMC 32 I would get "You don't have permissions to use this command"

I can't find the mods permissions listed anywhere so I assumed and gave my group this "projecte.*" but that doesn't help. Also, opping a user doesn't supercede LuckPerms so I can't do it that way either. I'd prefer to avoid file editing etc as it gets complicated whereas in hand is wonderful.

So any assistance would be greatly appreciated.

**Comment by williewillus** [comment]
I don't know how Sponge permissions plugins interact with commands coded to vanilla, you'll have to consult your the devs who wrote the plugin.

In a pure forge/vanilla setup, only ops can use the /projecte emc commands

**Comment by cyris69** [comment]
Thanks, I have posted over there and waiting for a response.

**Comment by sinkillerj** [comment]
Not much we can really do to fix this, but if something off is found on our side I'd be happy to reopen the ticket.

**Comment by MaPePeR** [comment]
You can always create a the configuration file in single player and copy it to the server afterwards.
