### ISSUE TITLE
1.12 (Mod version 1.20.) issue, Black Hole Band does not suck items into Alchemical Bags

### ISSUE THREAD

**Issue by fhlox** [sinkillerj/ProjectE#1666]
Exact ProjectE version: ProjectE-1.12-PE1.2.0

Exact Forge version:  14.23.2.2611

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): N/A, There was no crash

Steps to reproduce:

1. Put an (on) black hole band in an alchemical bag.
2. Be near dropped items.

What I expected to happen:
The items should have gone directly into the alchemical bag, as they do in EE2.

What happened instead:
The items are sucked into my inventory, and even when my inventory is full the items will not be sucked into the bag.

**Comment by Flexico** [comment]
I came to report this as well! This is an important feature to me.

**Comment by pupnewfster** [comment]
This can be closed, was fixed by #1650 (The reason that pull's date is before this issues date is that the release containing that pull was not made until April 30, 2018
