### ISSUE TITLE
Allow wildcard metadata in the setEMC command

### ISSUE THREAD

**Issue by BrisingrAerowing** [sinkillerj/ProjectE#1668]
(I didn't think the template was needed for a feature request / enhancement)

As per the title, allowing a wildcard metadata in the setEMC command would be useful for bulk setting EMC values (e.g. for the gems from Silent's Gems). I have things from a number of mods where this would be a real time saver. Other than that, this is a very cool mod.

**Comment by pupnewfster** [comment]
I think you might be able to use wildcard metadata via the config, but either way I am closing this as metadata no longer exists in 1.15
