### ISSUE TITLE
Table taking EMC, but not giving items

### ISSUE THREAD

**Issue by nimzamona** [sinkillerj/ProjectE#1672]
The table is accepting the EMC from items put into it, but it only gives back very very basic Minecraft vanilla blocks such as dirt, planks, iron ingots. The EMC system works fine for the 12 basic blocks it gives, but I put over 80 items into the table, and it accepted all of the EMC, but the items just aren't showing up. I opened/close the server to make sure it wasn't that, and the other person on the server has their table working fine.

**Comment by sinkillerj** [comment]
Are you sure you have enough EMC to actually obtain the other items? Beyond this we will need to know your minecraft version, projecte version, and any additional information such as logs that could provide details on why this is happeneing.

**Comment by nimzamona** [comment]
There are no logs that it created. I am 100% sure I have enough EMC because there was over 80,000, and when I put a torch in the table it disappears and adds to the EMC, but is uncreatable. The Minecraft version is 1.7.10, and the Project E file suffix is 1.7.10-PE1.10.0.

**Comment by sinkillerj** [comment]
May have been some sort of file permissions issue. Regardless glad to hear you got this resolved.
