### ISSUE TITLE
Dark/Red Matter Axe Not Working

### ISSUE THREAD

**Issue by Flexico** [sinkillerj/ProjectE#1675]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12-PE1.2.0

Exact Forge version: 1.12.2-14.23.3.2659

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/LAgktd2C

Steps to reproduce:

1. Hold Dark Matter or Red Matter Axe; right-click on tree

What I expected to happen: Large patch of forest chopped down

What happened instead: Nothing happens in-game, and the server spits out the above error (does not crash)

**Comment by Normal69** [comment]
I was in the same situation, axe won't work, error looked like exactly yours.
Those tools need EMC energy in your inventory.
I've retried it with a stack of charcoal in my inventory, and:
IT WORKS ;)
