### ISSUE TITLE
Higher emc cap 

### ISSUE THREAD

**Issue by VladoCC** [sinkillerj/ProjectE#1683]
Are you interested in version of ProjectE, in which items can have EMC up to Long. Max_Value.
Condensers and table caps changed too.
I can send pull request. 

+I'd found and fixed your bug wuth Nova Catalist and Cataclism. In my build you can break it without crash (NotNull is a bad guy)

**Comment by BenjaminUrquhart** [comment]
32-bit systems don't support the long data type because a long is a 64-bit data type

**Comment by williewillus** [comment]
that's not true, 32-bit VM's will load and store the two halves transparently for you.

as for the main ticket's proposal, we have plans that will be realized in due time
