### ISSUE TITLE
Open Alchimie Bag

### ISSUE THREAD

**Issue by c-louis** [sinkillerj/ProjectE#1685]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12-PE1.2.0

Exact Forge version: Forge-14.23.2.2640

Hello,

I was looking for a way to open player alchemical bag, i found an issue about a command to do it. But the command didn't seem to work on this version of the mod. Maybe the command just changed but i didn't find anything about this in the changelog or in the cfg of the mod. 

Is there still a command to do it ?

**Comment by williewillus** [comment]
Not right now,  but I'd like to add this feature back (at least for signed in players)

**Comment by Brycey92** [comment]
+1 for this to become a thing again! This is critical for administrating servers.

**Comment by williewillus** [comment]
this is now back in the next build, for online players. Offline player support coming soon.

**Comment by Brycey92** [comment]
Thank you!
