### ISSUE TITLE
ProjectE Transmuation Tablet / Table Crash

### ISSUE THREAD

**Issue by Rithsagea** [sinkillerj/ProjectE#1686]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.10.2-PE1.3.1

Exact Forge version: 12.18.3.2511

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

https://hastebin.com/avolirefut.scala

Steps to reproduce:

1. Open up a transmutation table/tablet and have a search specific enough so that there are 3 or less items.

2. Hover mouse over missing texture

What I expected to happen: I don't know, maybe the game not crashing or the texture not appearing at all

What happened instead: The game crashed

This is a picture of the transmutation tablet:

<img width="471" alt="screen shot 2018-05-07 at 5 10 09 pm" src="https://user-images.githubusercontent.com/17864218/39725766-e6811e5a-521a-11e8-960e-a3e14950d6f6.png">

**Comment by williewillus** [comment]
This is a bug with industrial wires not handling missing nbt data properly.
