### ISSUE TITLE
Covalence Dust not repairing TOOLS in crafting window.

### ISSUE THREAD

**Issue by woodyafortunato** [sinkillerj/ProjectE#1688]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12.2 (DW20 Pack)

Exact Forge version: 14.23.2.2618

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce: Not a crashing issue

1.

What I expected to happen: Covalence Dust does not repair items as intended.

What happened instead: Covalence Dust does not repair items as intended.

**Comment by artman41** [comment]
???
how is this a bug if what happened is what you expected?
How do you reproduce?
should it repair the tools or not? you've made this really confusing

**Comment by woodyafortunato** [comment]
Forget it man don't need your snark.
