### ISSUE TITLE
Getting wrong item from the transmutation tablet

### ISSUE THREAD

**Issue by Belgabor** [sinkillerj/ProjectE#169]
Unfortunately I cannot give an exact hot to replicate, but sometimes I get the wrong item out of the transmutation tablet (probably the table as well). The incident I remember was when I searched something and saplings were in the bottom left slot and apples in the bottom right slot. I tried to take out saplings but got apples instead.
I had this happen only once or twice, but I have reports of people on the server having the same issue. It seems to be rare though.

**Comment by deathglow** [comment]
I am getting the same issue but it so far only happens when i search for iron.  Top items seem to work fine but the bottom half switch to the next item in the list and the last item just dissapears from existence.

**Comment by MaPePeR** [comment]
What version of ProjectE?

**Comment by deathglow** [comment]
PROJECTE-1.7.10-PE1.7.2

**Comment by MaPePeR** [comment]
Then you should consider updating ProjectE. The most recent version is [ProjectE-1.7.10-PE1.9.3h](http://minecraft.curseforge.com/projects/projecte/files/2261474)
