### ISSUE TITLE
Block Swap

### ISSUE THREAD

**Issue by FrostStormRage** [sinkillerj/ProjectE#1691]
This section about bug with Project E, Mekanism and Croparia.

How to make the bug: 

1) Create world with modded MC and play for a bit, place down some Project E blocks. Then close MC

2) Load MC in vanilla client, and play the world but don't let that world to load. Terminate MC before loading of that world. 

3) Open MC with modded client again, Project E blocks are swapped with red/dark matter furnaces or with reactor glass(Mekanism) or with ritual helper(Croparia).

Alchemical coal will swap to dark matter furnace, alchemical chests will swap to reactor glass/ritual helper.  

MC and mods version is 1.12.2 

mod list:

- Mekanism

- Mekanism tools

- Mekanism generators

- Project E

- Croparia

- Not enough items

- Toro Health indicator

- Traverse

- JEI

- Progressive bosses

- More Furnace

- Ore Drop

- Hammer+Time

- Better Builders wands

- Iron backpack

- Journeymap

- Classic combat

- Chicken Chunks

- Bonsai trees

- Biome tweaker

- Better Magnets

Plus all the core-mods that are required for their corresponding mods

**Comment by williewillus** [comment]
I don't think this is a bug unique to these three mods. FML gets really finicky if you don't let it cleanly start and shut down worlds properly. Making backups is a necessity.

**Comment by FrostStormRage** [comment]
okay then.

**Comment by pupnewfster** [comment]
Closing as this doesn't even seem to have to do with ProjectE as much as just forced world corruption by terminating the world before it has a chance to finish loading. (A forge/vanilla thing)
