### ISSUE TITLE
Dupe bug with alchemical chest

### ISSUE THREAD

**Issue by triffman33** [sinkillerj/ProjectE#1694]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  ProjectE-1.12-PE1.3.0

Exact Forge version: forge-14.23.3.2673

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):

Steps to reproduce:

1. Place an Alchemical Chest.

2. Place a block breaker to break the block when an item is placed in it (like using a comparitor signal).

3. Place item in and then the alchemical chest will break, the item will pop out but you also are kept in the GUI so you can also take it out of the chest thats no longer there, thus duping.

What I expected to happen: The GUI should be force closed when the alchemical chest is broken.

What happened instead: GUI stayed open and was able to interact with items that werent really there.

**Comment by sinkillerj** [comment]
Thanks for the report, we have have to investigate if this is poor handling on our side or theirs.
