### ISSUE TITLE
EMC values don't go high enough

### ISSUE THREAD

**Issue by GigaOtomia** [sinkillerj/ProjectE#1695]
Exact ProjectE version: 1.12-PE1.30

Exact Forge version: 14.23.3.2668

Link to crash log: There is no crash, just bad behavior.

Steps to reproduce:

1. Use /projecte setEMC 2147483647 on an item. For example, dirt. I did this with Infinity Catalysts from Avaritia, because my only other choice was to not give them an EMC value at all.
2. Put other items in the transmutation table, to increase the EMC stored, then the dirt, or the Infinity Catalyst, or whatever else you set to be 2147483647 EMC.

What I expected to happen: Now, I understand that this is the maximum value for a single integer. I understand that numbers simply do not go higher than this in the programming language. I also understand that most people aren't going to use ProjectE and Avaritia at the same time, considering that Avaritia is a joke mod. Still, I wanted to believe that the amount of stored EMC could go higher than two billion.

What happened instead: If you drop an item with 2147483648 EMC into the transmutation table while it still has EMC in it, you lose the previously stored EMC. The value for stored EMC raises up to 2147483647, and stops there. You cannot drop more items into the destruction slot, you can only take things out of the table.

A possible solution: When your stored EMC hits 1 billion, subtract 1 billion from it, and add 1 to a new variable for stored EMC, leaving the remainder in the old variable. Additionally, add a check before doing this calculation to make sure that none gets lost in translation.

Thank you for reading my selfish request. I'm a fan of big numbers in games - I do play Disgaea, after all - so if this gets implemented, I will be overjoyed. Even more so if there's a third variable that does the same thing if the second variable hits 1 billion.

**Comment by VladoCC** [comment]
Hey, I created version that is not limited by integer
I can give it for you if you want

Official authors of ProjectE do not want to change this limits, but they can

**Comment by GigaOtomia** [comment]
I would appreciate that. Do you need my e-mail, or some other form of communication, or can you just pop a link in here?

**Comment by VladoCC** [comment]
@GigaOtomia I do not think that link here is a good idea without permission of ProjectE authors
Give me you email address, please

**Comment by VladoCC** [comment]
And.. If someone of ProjectE developers will read this, then, please, think about changing limits in our mod
I can pull code for you

**Comment by GigaOtomia** [comment]
Send the mail to lol.gigaemail.olo@gmail.com then, please.

**Comment by MaPePeR** [comment]
@VladoCC You can provide a pull request.

**Comment by MaPePeR** [comment]
The code is using Rationals right now, I think. Not sure if there is a long rational available, but then it should only needed to exchange the class... Should....

**Comment by VladoCC** [comment]
@MaPePeR ok, I did it. 
Commit this changes if you want.

**Comment by pupnewfster** [comment]
This can be closed as of https://github.com/sinkillerj/ProjectE/commit/47e331c5241f3b1b288b14279f24d12e66b57b2c
