### ISSUE TITLE
the mods is not showing up on the mods list thought ive put it in the folder

### ISSUE THREAD

**Issue by StarEnvelope145** [sinkillerj/ProjectE#1697]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen:

What happened instead:

**Comment by sinkillerj** [comment]
There are a few possible reasons for this.
A. You put it in the wrong mods folder, make sure you are in the subfolder for your current modpack, you can find where that is using the resource pack button in game.
B. You have attempted to use a jar for a different version of Minecraft, please check your logs for any failures.
