### ISSUE TITLE
Falling star Crashes games/makes some worlds unplayable

### ISSUE THREAD

**Issue by PudSomper** [sinkillerj/ProjectE#1699]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12-PE1.3.0

Exact Forge version: 14.23.3.2655

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): i don"t know how to 

Steps to reproduce:

1.wait for falling star

What I expected to happen: I don't know

What happened instead: crashed the game and mad one world unplayable due to crashing the second it opens.

**Comment by williewillus** [comment]
PE does not have falling stars, look at the crash log to find the actual mod that is crashing
