### ISSUE TITLE
Red Matter Furnace

### ISSUE THREAD

**Issue by Lunar-Rose** [sinkillerj/ProjectE#1702]
**Tickets that do not conform to this template will be closed without comment**

ProjectE-1.12-PE1.3.0.jar
Forge-14.23.4.2703
---No crash log, as there was no crash---
Steps to reproduce:

1.Make a Red Matter Furnace and place it down
2. Place any chest next to the Red Matter Furnace
3. Place fuel and ore/clay (cookable item) into furnace

What I expected to happen:
items will be cooked and transferred into the chest next to it
What happened instead:
the items cook and build up in the Red Matter furnace's inventory and do not transfer

**Comment by Hessin87** [comment]
I have my red matter furnace sitting on top of a hopper connected to a chest with a Gem of Eternal Density in it, it works pretty well. the output box on the RM Furnace definitely should be twice as big as the input though

**Comment by pupnewfster** [comment]
Closing as 1.14 finished implementing auto ejecting from matter furnaces. (I believe they auto eject to the bottom not the side though)
