### ISSUE TITLE
PStone crafting table missing the recipe + button

### ISSUE THREAD

**Issue by DreamSmith** [sinkillerj/ProjectE#1703]
ProjectE: 1.12.2 PE 1.3.0

Forge: 14.23.3.2691

Steps to reproduce:
Use C to open PStone crafting table.
Examine recipe with JEI (1.12.2-4.9.1.179).
No + button to move recipe to crafting table.

+ button is usable on basic crafting table.

**Comment by williewillus** [comment]
should be fixed
