### ISSUE TITLE
[1.12.2]Crafttweaker/Modtweaker can't add world transmutation

### ISSUE THREAD

**Issue by PiscesdanAT** [sinkillerj/ProjectE#1704]
Exact ProjectE version: 1.12-PE1.3.0

Exact Forge version: 14.23.4.2707

Exact AutoRegLib version: 1.3-17

Exact Crafttweaker version: 1.12-4.1.8

Exact Modtweaker version: 4.0.12

Link to crash log: n/a

Steps to reproduce:

1. Put a .zs file in the scripts folder:
  import mods.projecte.PhiloStone;
  import mods.projectE.KleinStar;
  import crafttweaker.item.IItemStack;
 
  PhiloStone.addWorldTransmutation(<minecraft:ice>, <minecraft:glass>); //Note: example

2. Run the game and open world

3. Try to transmute glass into ice

What I expected to happen: Glass block to be transmuted into ice block

What happened instead:
-On entering the world, the following message appears in chat:
ERROR example.zs:1 > No such member: projecte
ERROR example.zs:1 > Not a valid type
ERROR example.zs:2 > No such member: projecte
ERROR example.zs:2 > Not a valid type
ERROR example.zs:5 > could not find PhiloStone

-Glass -> Ice does not work

Note: I have successfully added recipes for other mods, so I assume it must be a problem with ProjectE.

**Comment by SihenZhang** [comment]
I have the same problem about it. 
When I use CraftTweaker to add world transmutation, the error will happen and it is said "No such member: projecte". 
I find that CraftTweaker support has been removed since January in 2017. And JSON can't edit World Transmutation. So is there a way to edit World Transmutation?

**Comment by Saereth** [comment]
I'm haivng the same issue here, need someway to edit the in world transmutations

**Comment by pupnewfster** [comment]
Fixed https://github.com/sinkillerj/ProjectE/commit/1ebe3ca7a2a089935464f3525e9f9e817da4f495 will be in next released version.
