### ISSUE TITLE
Almost no item have EMC value, cant use the transmutation table because of that

### ISSUE THREAD

**Issue by nodrek** [sinkillerj/ProjectE#1708]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  1.3.0

Exact Forge version: 14.23.2.2637

No crash or error code

What I expected to happen: Being able to put item into the transmutation table/tablet to use and get EMC

What happened instead: Item have no EMC (happen only on server, single player work fine) Even ProjectE iten doesnt have EMC, only a few have.

I use Twitch and its a custom modpack I use. I cant find help on internet with that problem, the closer I found was a problem in minecraft 1.7 with Forge Essential installed, we Use Minecraft 1.12 and Forge essential isnt in the mod list.

**Comment by sinkillerj** [comment]
What pack exactly are you playing?

**Comment by nodrek** [comment]
Homemade, but the base is direwolf20 and I added more mod:

AgriCraft 
BiblioCraft 
Guide-API 
Blood Magic 
Embers 
Hats 
Inventory Pets 
MrCrayfish's Furniture Mod
Natura 
ProjectE 
Thaumcraft 
CraftStudio API 
Animania

**Comment by pupnewfster** [comment]
My guess is that this may have to do with https://github.com/sinkillerj/ProjectE/issues/1713 assuming that Direwolf 20 has modified recipes. I would suggest waiting for the next version and seeing if this is still a problem.

**Comment by Unerismy** [comment]
I have the same problem. works just fine in single player tho

**Comment by pupnewfster** [comment]
Closing due to a lack of response of if this has been fixed after CrT recipe mapping got fixed.
