### ISSUE TITLE
Mods with annoying blocks that always have the same EMC

### ISSUE THREAD

**Issue by TheGoldenProof** [sinkillerj/ProjectE#1710]
Exact ProjectE version: 1.12.-PE1.3.0

Exact Forge version: 14.23.4.2708

Steps to reproduce:

1. Install Extra Utilities or Mekanism (two examples off the top of my head)

What I expected to happen:
EMC should auto-calculate for all of the generators from extrautils and energy cubes from mekanism (again, two examples off the top of my head) and they should all have their own EMC value.

What happened instead:
They are given the same EMC. The furnace generator from extrautils gets assigned 355 EMC and then all of the generators from extrautils have 355 emc regardless of what they should be, and if you change one, they all change. Same thing happens with a large number of blocks from Mekanism.

Also, does this have anything to do with the NBT whitelist (nbt_whitelist.json)? I added the registry names of those items (i think) and nothing seemed to change, so what does the NBT whitelist do?

**Comment by sinkillerj** [comment]
NBT separation is something we are currently looking at as it will likely be required for 1.13, stay tuned.

**Comment by TheGoldenProof** [comment]
Cool, and I heard that 1.13 is going to be annoying with the no NBT/metadata thing.

**Comment by Chinthor** [comment]
Ran into the same problem Adding another to the list: Thermal Expansion. When you apply upgrades to a machine, the upgraded machine has the same EMC value, even though the upgrade kit used on it has its own valid EMC value.

**Comment by pupnewfster** [comment]
Closing as 1.14+ has proper mapping support for items and I know for a fact that at least Mekanism no longer uses NBT to determine the type of block something is.
