### ISSUE TITLE
BUG strings --> wool

### ISSUE THREAD

**Issue by CuberCZ** [sinkillerj/ProjectE#1715]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
PE1.1.0
Exact Forge version:
1.7.10
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen:
wool made from 4 strings has 64 EMC, but 1 string has only 12 EMC, so it is not simillar 
What happened instead:
I am getting EMC, when I am crafting wools from strings

**Comment by williewillus** [comment]
not everything will be perfectly equivalent, because if there are loopholes or multiple ways to calculate a value PE will always pick the lower value.
