### ISSUE TITLE
Flan's mod guns zoom

### ISSUE THREAD

**Issue by Ezzocorbi** [sinkillerj/ProjectE#1717]
Version: ProjectE-1.7.10-PE1.10.1

Exact Forge version: 10.13.4.1614

Steps to reproduce:

1. equip gem boots in the feet armor slot
2. equip a flan's mod weapon

What I expected to happen:
Nothing

What happened instead:
The FOV decreased drastically and it's annoying. (I was not aiming down the sight)
(also it doesn't happen in 1.12)

**Comment by sinkillerj** [comment]
This is a mod conflict with a mod that is already known to not play nice with others. In addition 1.7 support has been long since dropped.
