### ISSUE TITLE
(CRASH)  1.12-PE1.3.1B breaks Refined Storage use of PE API

### ISSUE THREAD

**Issue by Vaygrim** [sinkillerj/ProjectE#1718]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE 1.12-PE1.3.1B (Beta)

Exact Forge version:
2705

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
[https://gist.github.com/Vaygrim/df152513d67f2dae532659fdf2d0d3b8](https://gist.github.com/Vaygrim/df152513d67f2dae532659fdf2d0d3b8)

Steps to reproduce:

1. Have a pre-existing Refined Storage setup with PE Transmutation Table hooked up via external storage
2. Update server to ProjectE-1.12-PE1.3.1B
3. Start up server
4. Try to log in.
5. Watch server fall over and start crying.

What I expected to happen:
For all of the above to not happened.

What happened instead:
See "Steps to reproduce"

**Comment by pupnewfster** [comment]
Refined Storage needs an update to support the latest beta, as the ProjectE api changed to support Longs.

**Comment by sinkillerj** [comment]
Refined Storage has removed support for ProjectE.

**Comment by Vaygrim** [comment]
It should be noted that Raoul stated he would be spinning off the Refined Storage support for Project E into a its own stand alone mod. I just don't know when that will happen.
