### ISSUE TITLE
Crash between Project E and Chisel and Bits

### ISSUE THREAD

**Issue by scalda** [sinkillerj/ProjectE#1719]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.12-PE1.3.1B
chiselsandbits-14.18
MCMultiPart-2.5.1

Exact Forge version:
forge-1.12.2-14.23.4.2705

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://pastebin.com/kkubZEaw

Steps to reproduce:

1. I am testing FC 1.4.3 and I am using both the latest files available to me as you can see above but on existing worlds, I am getting a server only crash whereas it works fine client side with an existing world

load an existing world with projecte and chisel and bits

What I expected to happen:
it to not crash on world load

What happened instead:

the server crashes with the report above

I am also reporting this to the Chisel and bit's team https://github.com/AlgorithmX2/Chisels-and-Bits/issues/402

**Comment by scalda** [comment]
there is a solution for this here https://github.com/AlgorithmX2/Chisels-and-Bits/issues/402

**Comment by MaPePeR** [comment]
You can also decrease the startup time by enabling pregenerated emc in ProjectE. That allows you to distribute a list of emc values with your pack and reenable that watchdog-timer after doing emc calculation once.

**Comment by scalda** [comment]
@MaPePeR How do i enable that as i can't seem to find an option in the config folder?

**Comment by scalda** [comment]
sweet thank you
