### ISSUE TITLE
...I transcended Minecraft tick speed using Torcherino...

### ISSUE THREAD

**Issue by Knightcoreframe** [sinkillerj/ProjectE#1727]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12-PE1.3.1B

Exact Forge version: 8.0.99.99

(Exact Torcherino version: 7.1)

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): [https://paste.dimdev.org/onetuwekuf.mccrash](https://paste.dimdev.org/onetuwekuf.mccrash) (provided by VanillaFix)

Steps to reproduce:

1. Double Compressed Torcherino, on maximum tick overclock...
2. Watch of Flowing Time...on a dark matter pedestal...being sure to overlap its area with that of the Torcherino...
3. Activate the pedestal

What I expected to happen: ...Honestly I was almost certain it would crash, but I was praying it might work.
(To give an approximation of what I was hoping to have happen, the expected tick speed from the Watch (400 ticks per second, if i read it right) and a double compressed torcherino at maximum (+32400%) would be in the region of 130,000 ticks per second (if my math is correct). That would be a hair above 1.8 hours per second.)

What happened instead: It broke...instantly. Further testing shows the world will begin to load but will immediately shut down after a few seconds. Last error log from testing:
https://paste.dimdev.org/yakimoruwu.mccrash

**Comment by sinkillerj** [comment]
You can try to remove erroring tiles in your forge config, or to remove the offending chunk with a world editor.

**Comment by williewillus** [comment]
our pedestals should blacklist torcherino though so this is still a bug maybe

**Comment by sinkillerj** [comment]
Ill reopen for now, that would be a good idea if we can find a reliable way to do it. It would be nice if we could prevent stacking with other tick enhancers overall though rather than just the worst offender.

**Comment by Knightcoreframe** [comment]
I used MCEdit 2 Beta to change the pedestal to air, thankfully I found a way around a few of the bugs of the beta. World (and house) salvaged :) if there was a way to mix other tick boosters with the Watch, that would be pretty awesome. But I don't know how Minecraft would handle it...

**Comment by NinjaPhenix** [comment]
So I've been looking into this issue and it seems to be caused by an infinite loop of update ticks caused by the watch of flowing time updating the torcherino which then updates the watch of flowing time. The easiest solution to this problem would to be to simply blacklist the darkmatter pedestal from torcherino updates, This would allow the watch of flowing time to still update the torcherinos allowing them to update blocks/tiles faster than they normally can, 30780 updates/second rather than 1620. This could also cause issues with lag but would be less likely to make your game crash. If you would like this solution an update can be posted pretty much immediately.

**Comment by Knightcoreframe** [comment]
Lag is lag, it'll happen with enough entities/mods/whatever anyway. That seems like a good solution to me, though a test before releasing the update may be in order. From the sounds of it, the pedestals should have had some interaction with a blacklist when it came to torcherino already. If there's some problem with the blacklist on either side, it may need a little more assistance.

...and by "less likely", do you mean a lot less or a little less? Or are you just uncertain? This is certainly a weird situation so I would understand if it's just an unknown. Thanks for the help, regardless! Even though I really can't think of a situation in which I would need 30k+ ticks per second, it's an intriguing challenge for me to try and find a use for it besides absolutely massive smelting operations condensed into a one furnace setup.

**Comment by williewillus** [comment]
@NinjaPhenix the torcherino should already have been blacklisted from projecte, but the blacklist probably broke since it was added several years ago.

I can fix it on my side, what's the registry name of the torch block/TE?

**Comment by NinjaPhenix** [comment]
Sorry for a very late reply.

Registry
torcherino:blocktorcherino
torcherino:blockcompressedtorcherino
torcherino:blockdoublecompressedtorcherino
torcherino:blocklanterino
torcherino:blockcompressedlanterino
torcherino:blockdoublecompressedlanterino

Classes:
com.sci.torcherino.blocks.tiles.TileTorcherino
com.sci.torcherino.blocks.tiles.TileCompressedTorcherino
com.sci.torcherino.blocks.tiles.TileDoubleCompressedTorcherino

**Comment by williewillus** [comment]
this is configurable now  71b79a5
