### ISSUE TITLE
Crash with Botania and Project E

### ISSUE THREAD

**Issue by NanoHeart** [sinkillerj/ProjectE#1729]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.12-PE1.3.0

Botania version: r1.10-354

Exact Forge version:
14.23.2744

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://pastebin.com/G7A2TbSk
Steps to reproduce:

1. Make Terasteel from Botania

What I expected to happen:
Work as normal

What happened instead:
Got this weird crash from Project E seemingly

**Comment by williewillus** [comment]
see botania issue
