### ISSUE TITLE
Can't set individual emc values for tiered items

### ISSUE THREAD

**Issue by SpikeVanHellsing** [sinkillerj/ProjectE#1731]
I am trying to set individual emc values for tiered item from mekanism and not having any luck. All tiered items default to the basic item when added into the transmutation table. Is there any way to set the values manually without all other tiers of the item changing too? EX: all fluid tank from mekanism are 1280 but i would like them to increase based on the item used to craft each tier.

**Comment by sinkillerj** [comment]
NBT based separation is on the map for MC 1.13 out of necessity and a backport may be possible.

**Comment by williewillus** [comment]
as a side note, NBT mapping is not really a necessity in 1.13 more due to the flattening. I likely won't have time to work on it besides the base port to 1.13 itself, so it'll be up to what contributors and blub do

**Comment by pupnewfster** [comment]
Closing as 1.14+ has proper mapping support for items and I know for a fact that at least Mekanism no longer uses NBT to determine the type of block something is.
