### ISSUE TITLE
Overlaied Watch of Flowing Time

### ISSUE THREAD

**Issue by Diluka** [sinkillerj/ProjectE#1738]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen:
It should not be overlaid

What happened instead:
It overlaid and lags the whole game
collectors been extremely accelerated

**Comment by williewillus** [comment]
not sure what you mean by overlaid. it's intended for two individual watch holders to be able to accelerate the same times. yes, this can be laggy, that's why there's an option for the item to be disabled.
