### ISSUE TITLE
[Suggestion] Auto focus of the search file into the transmutation table

### ISSUE THREAD

**Issue by ExDomino** [sinkillerj/ProjectE#1739]
**Exact ProjectE version (do not say "latest", "latest on Curse", or similar):** 1.12-PE1.3.0

**Exact Forge version:** 14.23.4.2732

**Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):** N/A

**Steps to reproduce:** There is no step to reproduce since this is not a bug nor a crash.

**What I expected to happen:**

When I open the transmutation table, I would like to be able to write the item that I want to search without having to click with my mouse on the search field in order to begin to type. Clicking on the prev and next button should refocus the search field as well.

**What happened instead:**

The search field is not auto focused. I have to use my mouse each time to search an item and it's almost irritating. The focus is also lost when I use the prev and next button.

Thank in advance.

**Comment by sinkillerj** [comment]
This is an intentional design decision. While it may seam convenient for you there are other inconveniences that would come as a result.

**Comment by ExDomino** [comment]
Can you add a config option then? Disabled by default.
