### ISSUE TITLE
Hardened Stone from Environmental tech

### ISSUE THREAD

**Issue by BadLucKWyvern** [sinkillerj/ProjectE#1742]
That stone isn't harvested by TNT Catalysts, like bedrock, after the explosion, the stone is still here
This stone is close from bedrock and can be harvested by pickeaxes, but not by TNT catalysts
(1.11.2)

**Comment by sinkillerj** [comment]
That sounds like its working as intended, Hardened Stone has an intentionally high blast resistance.

**Comment by williewillus** [comment]
use the power tools instead, the nova catalyst/cataclysm are simply stronger tnt but not strong enough for this block
