### ISSUE TITLE
[1.12.2] Crash on game loading (step 6/7 ModIdMapping)

### ISSUE THREAD

**Issue by BadLucKWyvern** [sinkillerj/ProjectE#1743]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  ProjectE-1.12-PE1.3.0

Exact Forge version: 1.12.2-14.23.4.2757      

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/L70rrTJy

Posted it on minecraft forge github and silentchaos512 profile (asked his help) and both answered me:
"at moze_intel.projecte.events.ToolTipEvent.tTipEvent(ToolTipEvent.java:57)
ProjectE issue?"

**Comment by BadLucKWyvern** [comment]
switched with ProjectE-1.12-PE1.3.1B and its working again

**Comment by pupnewfster** [comment]
If this is working with newer versions, this should be able to be closed now.
