### ISSUE TITLE
Transmutation Table Crashing With Spawn Eggs

### ISSUE THREAD

**Issue by logy003** [sinkillerj/ProjectE#1744]
**Tickets that do not conform to this template will be closed without comment**

Project E Version:
1.12-PE1.3.0

Exact Forge version:
1.12.2-14.23.4.2705

Link to crash log:
https://justpaste.it/66b4g

Steps to reproduce: Ok Some Quick Background. I Used Inventory Pets (The Illuminati One) To Receive A Random Ite And I Got The Book That Unlocks Everything (dumb luck)

1. So Then I Put It In The Transmutation Table For Some Quick EMC And When I Went To The Page With  What I Learned From Testing Was Spawn Eggs The Game Crashes.

What I expected to happen: To Have Everything Unlocked And Useable Including Spawn Eggs

What happened instead: My Game Crashes When I Get On A Page With Spawn Eggs

I Use A Lot Of Mods So I Don't Know If This Will Help But Here Is A List (All In 1.12.2)
Baubles
BiblioCraft
BuildCraft
Camera Obscura
Carbonado
Crayfish Furniture
Crayfish Gun
Chameleon Library
Collectibles
Earth Stones
Elevator Mod
Exotic Bird Mod
Fast Leaf Decay
Galacticraft Core
Galacticraft Planets
Gislbaers Durability Viewer
Harvest Craft
I Chun Util
Inventory Pets
Inventory Tweaks
Iron Chest
JEI
Journey Map
LLibrary
LLlibrary Core
Loyalty Medals
Micdoodlecore
MoCreatures
Morphing Mod
Neat Mod
Obfuscate
Optifine
Orecore
Project E (Duh) (Version Above)
PTR Lib
Spectrite Storage
Drawers
Teletubbies Mod
Eight Fabled Blades
Time HUD
Twilight Forest
Uncrafted
Mr Crayfish Vehicle Mod
Weirding Gadget
World Edit
XP Holder

I Get Your Probably Very Busy But If Its Something Im Doing Please Message Me At
fishfromnepal@gmail.com
Or On Discord At LogyTheCommunistPanda#2134

**Comment by williewillus** [comment]
crash in this mod:
```
at com.samuel.spectrite.init.ModItems.lambda$createItems$0(ModItems.java:119)
```
