### ISSUE TITLE
[Suggestion] Default Transmutation Recipes

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [sinkillerj/ProjectE#1749]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.3.0
Exact Forge version:
12.23.4.2757

Suggestion to add ability to add default recipes to transmutation tablet for modpack purposes
Sorry if this already exists and I didn't notice it in the config

**Comment by sinkillerj** [comment]
This could be accomplished by a mod that sets default NBT values for a new player, I don't know of one off the top of my head but I'm sure it exists.

**Comment by pupnewfster** [comment]
I am pretty sure Vanilla CraftTweaker can be used to set NBT of a player when they first join. You can ask in the CraftTweaker discord how to set player NBT on join.
