### ISSUE TITLE
Swiftwolf's Rending Gale - No Sound - 1.11.2

### ISSUE THREAD

**Issue by Craymozoid** [sinkillerj/ProjectE#1750]
ProjectE Build: ProjectE-1.11.2-PE1.0.0B.jar

Forge Build: forge1.11.2-13.20.0.2253

Crash Log: n/a

Steps to reproduce:

1. Activate flight with "Swiftwolf's Rending Gale" in-game
2. Deactivate flight with "Swiftwolf's Rending Gale" in-game

What I expected to happen: peheal.ogg play over headset upon activation - peuncharge.ogg play over headset upon deactivation

What happened instead: No sound played.

**Comment by pupnewfster** [comment]
Can be closed now
