### ISSUE TITLE
Invalid blocks placement

### ISSUE THREAD

**Issue by LemADEC** [sinkillerj/ProjectE#1751]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.3.1B

Exact Forge version: 1.12.2-14.23.4.2758

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): n/a

Steps to reproduce:

1. Go in a plain
2. Use ring of Arcana, switch to ignition, activate
3. Observe how fire is placed around

What I expected to happen:
Fire replace tall grass
Fire is only placed in valid blocks

What happened instead:
Fire is placed everywhere, including on top of non-solid blocks like tallgrass

Related code is here: https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/utils/PlayerHelper.java#L56
We're missing something like this:
```
		World world = player.getEntityWorld();
		if (!state.getBlock().canPlaceBlockAt(world, pos)) {
			return false;
		}
```

**Comment by williewillus** [comment]
tall grass can be ignited with fire (use flint and steel to see)

while it's true the ring places fire in pretty much every air space it can find, fire immediately goes out if it can't stay there. so this isn't a bug
