### ISSUE TITLE
[1.7.10] blood magic incompatibility??

### ISSUE THREAD

**Issue by PloupFx420** [sinkillerj/ProjectE#1752]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.7.10-PE1.10.1

Exact Forge version: 10.13.4.1558

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):
1st issue doesn't crash me
2nd issue kind of did (i dont have the log i only got it to happen once)

Steps to reproduce:

1.

What I expected to happen: i expected simply installing ProjectE and being able to hop into my single player world and play around with the mod.

What happened instead: When i tried to run my 100% clean and not corrupted single player world with projectE, all of the sudden every time i would try to join any of my single player worlds its would do this weird bug where it wouldn't crash me but not let me load in any of my definitely not corrupted single player worlds neither create one, it would just set me back to the games main menu(not launcher)every time i would try it, so then i decided to track down the problem myself as i found the mod worked perfectly fine on his own (w no other mods) and let me load up any world with no problem. which brought me to the conclusion that it was definitely when it was in there with blood magic. projectE would work fine with any of the other mods i had on there, so when added blood magic back in it started crashing on launch. to fix that i had to remove projectE, add back bloodmagic and now whenever i put projectE in there it gives me the same issues i ad at first with the main menu. would be really awesome if i could get this to work ive been waiting for ee2 forever and just found out about it sadly i cant even play it along side my other favorite mod

**Comment by williewillus** [comment]
1.7.10 is not supported, and we can't solve anything without a crash report
