### ISSUE TITLE
Can not map Crafting Recipes with Type: (...)

### ISSUE THREAD

**Issue by BenjaminZimbal** [sinkillerj/ProjectE#1753]
ProjectE Version: 1.12-PE1.3.0

Exact Forge version: MinecraftForge v14.23.4.2739

Link to **error** log: https://pastebin.com/avfNmXxJ

Steps to reproduce:

I do not know how to reproduce this error, because it shows every time I start up my server.

What I expected to happen: The crafting recipe should be mapped right, i guess?

What happened instead: It is not mapped correctly / not mapped at all.

**Comment by MaPePeR** [comment]
This is just a information-message, that there is no implementation to read the special crafting types of another mod.

**Comment by Kasia1403** [comment]
I have similar issue.
[latest.log](https://github.com/sinkillerj/ProjectE/files/13464041/latest.log)
Should I wait until it loads or kill a javaw.exe process ? If I should wait, so how many time it can take ( minimum - maximum ) ?
