### ISSUE TITLE
EMC for Modders?

### ISSUE THREAD

**Issue by saismee** [sinkillerj/ProjectE#1754]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): N/A but PE1.10.0

Exact Forge version: N/A

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): N/A

How would I add support for this mod inside of my mod? I'm working on a mod named BronzeAddon which adds more uses for Tin and Copper (Which with a lot of mods piles up quick)

I would like to add EMC values for my CPU and IHS items

**Comment by sinkillerj** [comment]
You can find our API here: https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/api/proxy/IEMCProxy.java
