### ISSUE TITLE
Archangel's smite crash 1.7.10

### ISSUE THREAD

**Issue by KrauzeBartek** [sinkillerj/ProjectE#1755]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  - ProjectE-1.7.10-PE1.10.1.jar

Exact Forge version: 1.7.10 10.13.4.1614 

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): - 
https://ibb.co/cPR32U

Steps to reproduce:

1.

What I expected to happen: I try use archangel's smite on server.

What happened instead: I have crash, server was stopped.

**Comment by sinkillerj** [comment]
Please ensure that you are using the latest official Forge installer. We do not provide support for any Bukkit based forks. Please note that support has also been dropped for 1.7.10 and we are no longer actively providing updates for it.
