### ISSUE TITLE
1.12 Transmutation tablet Error

### ISSUE THREAD

**Issue by Colton-Slayden** [sinkillerj/ProjectE#1756]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12-PE1.3.0

Exact Forge version:14.23.4.2760

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. Place klien star in transumation tablet. Shows 2 of the same same with redmatter pickaxe

What I expected to happen: only show one

What happened instead: only show one of each in tablet

**Comment by mog01** [comment]
I notice the transmutation tablet does a similar thing (shows it twice) with the philosopher's stone.
