### ISSUE TITLE
[Suggestion] EMC Container Config Option

### ISSUE THREAD

**Issue by Katapow99** [sinkillerj/ProjectE#1758]
Hi there, just looked through the changelog of version 1.3.0 and read "More EMC can be stored in places such as the Transmutation Table (but you will still ask for an increase)", then I thought why not just make a config option to let people set the max EMC values for blocks? Would really help with server administrators, people can stop whining for more storage, it's a win/win for almost everyone. It is just a thought and I wouldn't know how complicated it would really be, just wanting to help out.

**Comment by sinkillerj** [comment]
Its not quite that simple, the limit is defined by the medium used to store EMC. Adding a config to make it lower would be easy, adding a config to make it higher doesn't work.

**Comment by pupnewfster** [comment]
The other thing @Katapow99 is that in 1.3.1B EMC was changed from ints to longs. 2,147,483,647 max -> 9,223,372,036,854,775,807 so if you update to that I highly doubt that people will be "whining for more storage"
