### ISSUE TITLE
Watch of flowing time missing from mod

### ISSUE THREAD

**Issue by KeyMasterX294** [sinkillerj/ProjectE#1759]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. install latest mod

What I expected to happen: watch of flowing time to be in mod upon instalation

What happened instead: no watch of flowing time

has it been removed?

**Comment by sinkillerj** [comment]
In the modpack you are playing it has likely been disabled, or removed via a script, check your configs.

**Comment by KeyMasterX294** [comment]
1. I locally installed this mod into my minecraft mod folder.
2. Im using the config that was already in my config folder from before updating the mods in my folder and it was there before I updated to the latest version of the mod.
    
         # Enable Watch of Flowing Time
        B:enableTimeWatch=true

**Comment by williewillus** [comment]
please update the ticket to have *all* the information requested.

**Comment by KeyMasterX294** [comment]
?

**Comment by XayCraft** [comment]
@Aromatico I already looked and couldnt find it
