### ISSUE TITLE
Attempt to load any PE version of 1.12.2 cause noveau "doublefree"s, kref assertions or global hanging

### ISSUE THREAD

**Issue by Heimdell** [sinkillerj/ProjectE#1761]
OS: Ubuntu 18.04

Video driver: noveau

Exact ProjectE version: 1.12.2-PE-1.3.0-1B

Exact Forge version:1.12.2-14.23.4.2765

Link to crash log: 
https://gist.github.com/Heimdell/51bb3544e00cf4987cf9273b107c5935

Steps to reproduce:
1. Install forge of given version
2. Put ProjectE-1.12-PE1.3.0.jar into `./mods`
3. Run game

What I expected to happen:
Nice experience

What happened instead:
Game crashed

**Comment by Heimdell** [comment]
This happens on resource-making phase of loading.

> [13:39:06] [main/INFO] [FML]: Max texture size: 16384
> [13:39:06] [main/INFO] [minecraft/TextureMap]: Created: 512x512 textures-atlas
> java: ../../nouveau/pushbuf.c:727: nouveau_pushbuf_data: Assertion `kref' failed.

Maybe, something is "wrong" with textures, however, "Assertion `kref` failed" clearly blames noveau.

**Comment by sinkillerj** [comment]
Ill take a look but I'm skeptical the ProjectE itself could cause this issue. Do you have an actual graphics card or are you relying on your CPU's builtin graphics? If CPU I'd like to know which one if possible, if you have a graphics card on the other hand you should really install native drivers.

**Comment by williewillus** [comment]
yeah, i highly doubt PE is the issue, since PE is a much smaller and simpler mod than many of the big mods in packs these days.

**Comment by Heimdell** [comment]
```
$ lspci | grep VGA  
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
01:00.0 VGA compatible controller: NVIDIA Corporation GF108 [GeForce GT 440] (rev a1)
```
I believe I use videocard, since otherwise performance would be much worse.

**Comment by sinkillerj** [comment]
Yea you will need to install the Nvidia drivers for your version of Ubuntu, esp since you have a card on the older side that Noveau likely does not have proper support for.
