### ISSUE TITLE
[Request] Make watch of flowing time not interact with certain blocks.

### ISSUE THREAD

**Issue by DemonfangArun** [sinkillerj/ProjectE#1763]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12-PE1.3.1B

Exact Forge version: 14.23.4.2766

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): n/a

Steps to reproduce: n/a

I would like to request a configuration to disable the watch of flowing time from interacting with certain blocks. It basically breaks roost and makes it so you might as well just play in creative mode. I'd still like to keep it enabled for other things like speeding up machines (since they use more power as a result, and thusly balance out). I'm sure I'll find other things that it shouldn't interact with.

**Comment by DemonfangArun** [comment]
They do? Ouch! People usually build those into their base, that would be a bad day.

**Comment by williewillus** [comment]
what are the block or tile entity IDs you want to disable?
I can add them manually for now. In 1.13 I'll define a tag or something so people can exclude things themselves

**Comment by DemonfangArun** [comment]
roost:roost and roost:breeder

and for extra utilities: extrautils2:quarryproxy and extrautils2:quarry

Would it be possible to backport that change to 1.12? I'd like to be able to still update to newer 1.12 versions, and I don't want to make someone maintain multiple versions.

**Comment by DemonfangArun** [comment]
Yay! Thank you very much :)

**Comment by DemonfangArun** [comment]
Is there any update on when this is going to make it to a version?
