### ISSUE TITLE
For Whatever Reason giving a BC Cool Oil Bucket emc, and placing it in the transmutation table voids the item

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [sinkillerj/ProjectE#1768]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.3.1

Exact Forge version:
2770

Exact BC Version:
7.99.18

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
n/a

Steps to reproduce:

1. Install the mods
2. Give oil cool emc
3. Teach to table
4. try to search it

What I expected to happen:
Pull out the Bucket

What happened instead:
it doesnt show

**Comment by CrankySupertoon01** [comment]
https://github.com/BuildCraft/BuildCraft/issues/4298
https://github.com/CrankySupertoon01/Pyramid-Challenge-Reborn/issues/13

**Comment by pupnewfster** [comment]
This is because the oil bucket is a forge bucket using NBT to express the type of fluid it holds. It is unlikely that NBT will end up being supported as the need for it will likely be removed in 1.13 as can be seen in #1577

**Comment by pupnewfster** [comment]
Closing as 1.14+ has proper NBT support
