### ISSUE TITLE
1.12.2 Server crash

### ISSUE THREAD

**Issue by ElSaam** [sinkillerj/ProjectE#1769]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12-PE1.3.1B

Exact Forge version: forge-1.12.2-14.23.5.2768-installer

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): [https://pastebin.com/qE9puwpM](url)

Steps to reproduce:

1. Make a forge server with with forge-1.12.2-14.23.5.2768-installer.
2. Install ProjectE-1.12-PE1.3.1B to the server.

What I expected to happen: I expected for the server to turn on without crashing

What happened instead: The server crashed and worked again when I switched back to ProjectE-1.12-PE1.3.1B

**Comment by Lilylicious** [comment]
#1771 should fix this.

**Comment by pupnewfster** [comment]
Can be closed
