### ISSUE TITLE
Client Crash When loging into Server (1.12.2)

### ISSUE THREAD

**Issue by chunkedelement** [sinkillerj/ProjectE#1770]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12-PE1.3.2.jar

Exact Forge version: client and server forge-14.23.5.2784 (1.12.2)

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://paste.dimdev.org/devabaduyu.mccrash
https://paste.dimdev.org/lugivebesu.mccrash

Steps to reproduce:
1. Using ProjectE 1.12-PE1.3.2 on client and server with JEI 1.12.2-4.13.1.225. When logging into server the client crashes with the error above. In single player worlds the client does not crash, multiplayer only.
2. Downgraded ProjectE to version PE1.3.1B.jar on client and server, client doesn't crash on multiplayer when connecting/logging into server world.
3. Tried to downgrade JEI to jei_1.12.2-4.13.1.222.jar on client and server to see if this would effect the issue and it would still crash the client on this version as well when connecting to the server. Wasnt sure if JEI was causing a issue so tried to downgrade this mod as well.
4. Also tried deleted configs for ProjectE on both client and server so ProjectE would generate new config files but still the same crash occurs when connecting to server.

What I expected to happen:
When logging in with client on multiplayer server not to crash the client upon connection.

What happened instead:
Using ProjectE 1.12-PE1.3.2 on client and server with JEI 1.12.2-4.13.1.225. When logging into server the client crashes with the error above. Error in ProjectE JEI integration plugin. In single player worlds the client does not crash, multiplayer only.
Thanks

**Comment by williewillus** [comment]
@Lilylicious ?

**Comment by sinkillerj** [comment]
Sorry about this and #1769, I knew I should have been more through with testing... I'll be looking into the issue in the coming days.

**Comment by Lilylicious** [comment]
Aw shite. I thought I'd tested it properly.

**Comment by Lilylicious** [comment]
#1771 should hopefully maybe fix this. Since I can't reproduce the crash locally, I had to go on my best guess for a fix. It also fixes an unrelated bug with the same feature, where the final item in the map would show a wrapping recipe to the first item.
