### ISSUE TITLE
[SUGGESTION] Add Watch of Flowing Time TileEntity blacklist to config

### ISSUE THREAD

**Issue by MasterEric** [sinkillerj/ProjectE#1772]
https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/api/proxy/IBlacklistProxy.java#L27 contains the quote:

> Modders: Use this only to prevent things from breaking badly - leave balance to the modpacker and player

However, no functionality currently exists for the modpacker or the player to add to the blacklist without creating a separate mod which calls the blacklistTimeWatch function with the desired classes.

The suggestion is to create a configuration option that allows the modpacker or the player to add to the Watch of Flowing Time blacklist, and preferably the other blacklists (Interdiction and Swiftwolf) as well.

**Comment by williewillus** [comment]
71b79a5

**Comment by MasterEric** [comment]
👍
