### ISSUE TITLE
1.3.2 crash in eclipse

### ISSUE THREAD

**Issue by Colton-Slayden** [sinkillerj/ProjectE#1774]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12-PE1.3.2.jar 

Exact Forge version:14.23.5.2768 

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. Install default forge MDK and add projecte to buildpath

What I expected to happen: Run minecraft through eclipse to test mod

What happened instead: https://pastebin.com/xyDJbTfr

**Comment by williewillus** [comment]
set up your dependencies properly

**Comment by Colton-Slayden** [comment]
dependencies are properly set up and i ran it in a default forge environment i have 4 people test it on different computers before posting
