### ISSUE TITLE
ProjectE 1.3.2 Crash

### ISSUE THREAD

**Issue by Colton-Slayden** [sinkillerj/ProjectE#1776]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12-PE1.3.2.jar

Exact Forge version: forge-1.12.2-14.23.5.2768.jar

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://pastebin.com/HmsKrGhk

Steps to reproduce:

1. Install Forge 14.23.5.2768
2. Install ProjectE-1.12-PE1.3.2.jar to mods folder
3. Launch Minecraft
4. Game Crash

What I expected to happen: Minecraft launch normal and not crash

What happened instead: minecraft crashes

Fix: When jei is installed does not crash without game crashes
Make JEI a required dependency
Also Fixes #1774 
So next time please dont tell me i dont know what i am talking about unless you 100% know your code is fine

**Comment by sinkillerj** [comment]
Or, alternative you could cut your crap and look at the fact that this is a known issue before you open a ticket.
