### ISSUE TITLE
[Suggestion] Add an option to disable Philostone entity randomizer projectile 

### ISSUE THREAD

**Issue by Saereth** [sinkillerj/ProjectE#1777]
I'm Working on developing a pack for FTB that uses projecte tied in with progression but the philostone currently enables access to mobs from other dimension such as ghasts and blazes far before the player could ever get to those mobs. This becomes a pretty big issue for gating certain progression steps as it also bypasses gamestages/mobstaging. My only two options currently are disable the philostone entirely (Which we dont want to do as we're utilizing the inworld transmutations extensively) or use a hacky ASM override approach like this mod does:
https://minecraft.curseforge.com/projects/ceds-unleashed-control

I figured requesting an official config option would be best if you're open to it to avoid that sorta hackery. Thanks!

**Comment by sinkillerj** [comment]
Ill look into this for the next version, I can certainly agree that this is a much needed balance tweak in some packs.

**Comment by pupnewfster** [comment]
I think at some point when I get the chance I will look into adding support to the CraftTweaker integration to modify the peaceful and mob lists of the randomizer projectile. That way modpack makers will also be able to add mobs from other mods to be able to be randomized, in addition to removing/clearing the existing lists.

For quicker lookup when I get around to implementing this, the two lists are in WorldHelper.java and are called `peacefuls` and `mobs`

**Comment by Saereth** [comment]
oh now thats very exciting

**Comment by pupnewfster** [comment]
https://crafttweaker.readthedocs.io/en/latest/#Mods/ProjectE/EntityRandomizer/
