### ISSUE TITLE
Direwolf20 Importation 

### ISSUE THREAD

**Issue by DeatlhyDiamond** [sinkillerj/ProjectE#1778]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version: 1.3.2h

Exact Forge version: 1.12.2 Dirwolf20 Modpack

No crash log at the time, I will get one as soon as i can

Description: ProjectE when imported to the Direwolf20 1.12.2 modpack will fail to run. It will crash the game upon startup

Somethings to note:
I have imported to following mods (all the latest versions):
Mystical Agriculture
Mystical Addgrations
AE2 Stuff
Tiny Progressions
Decocraft 2
Lootbags
Worldedit

Steps to reproduce:

1. Download modpack
2. Import mods

What I expected to happen:
ProjectE imports successfully
What happened instead:
It crashes on startup

**Comment by sinkillerj** [comment]
Ill keep this open for now, but we really do need that log in order to help you.
