### ISSUE TITLE
Dark Matter Platform Can't Open

### ISSUE THREAD

**Issue by TopFormula** [sinkillerj/ProjectE#1785]
I can't open the Dark Matter Platform on Minecraft1.12.2,Forge:14.23.5.2772;Mod only Jei ,VeinMiner,and map

**Comment by Hessin87** [comment]
if your talking about the "Dark Matter Pedistal" it doesn't have a UI to "open" you right click it while holding whatever your trying to put on it and then right click with an empty hand to activate it.
