### ISSUE TITLE
crash on start up ShapelessKleinStar

### ISSUE THREAD

**Issue by hazerddex** [sinkillerj/ProjectE#1794]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE: ProjectE-1.12-PE1.3.2h.jar

Exact Forge version: 1.12.2 - 14.23.5.2796

Link to crash log:https://justpaste.it/7ovox

Steps to reproduce:

1. start minecraft. with this mode EquivalentAdditions-1.12.2-2r and ThaumicEquivalence-1.12.2-1.0.5 installed along with all required the dependencies. 

2. also happens when i start up with just ProjectE-1.12-PE1.3.2h.jar installed/

What I expected to happen: the game to start without crashing

What happened instead: game crashes

**Comment by williewillus** [comment]
fixed in next release, as a temporary workaround install JEI
