### ISSUE TITLE
crash on loadup. invaled recipie no class found. shapeless klein star. 

### ISSUE THREAD

**Issue by kain184** [sinkillerj/ProjectE#1797]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12-PE1.3.2h

Exact Forge version:forge-1.12.2-14.23.5.2796

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/91pYiWjm

Steps to reproduce:

1 install proper forge version. 
2 install project e version. 
3 load game

What I expected to happen:
game should load through mods and start
What happened instead:
game crashed during load of recipies with no class error causing crash due to klein star recipie.

**Comment by williewillus** [comment]
fixed in next version. for now, install JEI to work around it
