### ISSUE TITLE
Philosopher stone not listed as catalyst to JEI integration for World Transmutation

### ISSUE THREAD

**Issue by TeamDman** [sinkillerj/ProjectE#1798]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.12-PE1.3.2h
Exact Forge version:
14.23.5.2782
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
n/a
Steps to reproduce:

1. View usage of philosopher stone
2. It only shows crafting recipes
3. View recipe for Obsidian
4. It shows in world transmutation

What I expected to happen:
Showing usages of the phil. stone in JEI should show in world transmutation
What happened instead:
Showing usages of the phil. stone only showed crafting recipes

![image](https://user-images.githubusercontent.com/9356891/50552843-0b782280-0c6a-11e9-8b18-7ea4c4a9df68.png)
![image](https://user-images.githubusercontent.com/9356891/50552846-1e8af280-0c6a-11e9-9f7c-1f9e085a112e.png)

**Comment by pupnewfster** [comment]
Already added in dev. https://github.com/sinkillerj/ProjectE/commit/9d4282098a41ff7164f8ba3300e608c20e47543e
