### ISSUE TITLE
ProjectE armor doesn't respect max armor from AttributeFix

### ISSUE THREAD

**Issue by Conga0** [sinkillerj/ProjectE#1799]
Exact ProjectE version: PE1.3.2h

Exact Forge version: ProjectE-1.12-PE1.3.2h

Link to crash log: NA

Steps to reproduce:
1. Install AttributeFix; setting max armor/toughness in configs below ProjectE's armor values (fe. 17)
(https://minecraft.curseforge.com/projects/attributefix)
2. Equip any ProjectE armor in full

What I expected to happen: I expected ProjectE's armor to respect the max armor & toughness values set by AttributeFix or at the very least vanilla minecraft

What happened instead: ProjectE armor surpassed both vanilla and AttributeFix's max armor/toughness settings; this is a big problem since i've lowered the max armor/toughness settings below vanilla's max for balance

**Comment by sinkillerj** [comment]
ProjectE armor does not work like basic vanilla armor, there are no plans to change this. You will find that other special armors give the same issue.
