### ISSUE TITLE
[Feature Request] or does it already exist

### ISSUE THREAD

**Issue by kamrantekkit** [sinkillerj/ProjectE#1803]
a file that contains every item with their emc value in the game

**Comment by MaPePeR** [comment]
Does already exist. There is a config option for a "pregenerated emc file" somewhere. When you enable it the file will be generated and used for future game loads. (So need to delete it in order to calculate new emc values)

**Comment by kamrantekkit** [comment]
i mean is there a file that contains each item with thier emc value in somesort of list

**Comment by williewillus** [comment]
yes, as blub just said, enabled pregenerated emc and run the launch once and the file pregenerated_emc.json will appear in PE's config folder.

**Comment by kamrantekkit** [comment]
how do i enable pregenerated emc

**Comment by MaPePeR** [comment]
It's in the mapping.conf or something like that.

**Comment by kamrantekkit** [comment]
ok thx
