### ISSUE TITLE
No EMC Values (Multiplayer)

### ISSUE THREAD

**Issue by system-operator** [sinkillerj/ProjectE#1806]
ProjectE-1.12-PE1.3.2h
Spongeforge-1.12.2-2768-7.1.5-RC3515 (Removed all Plugins to Test, but Kept SpongeForge)
Spongeforge-1.12.2-2705-8.0.0-BETA-3474.jar (also tried this one)
forge-1.12.2-14.23.5.2807-universal
forge-1.12.2-14.23.5.2768-universal (also tried)

EMC values do NOT show in JEI on mod pack/server. 

Values DO show in JEI on Singleplayer. 

/projecte reloadEMc throws error:
https://paste.dimdev.org/noqufakove.mccrash

Running with just Spongeforge, JEI, CodeChickenLIB and ProjectE it works fine...

Perhaps one of my mods? >> https://github.com/resist-network/resist-mod-pack

**Comment by sinkillerj** [comment]
Closing following Discord discussion.
