### ISSUE TITLE
EMC mapper ceased functioning in PE 1.4.0

### ISSUE THREAD

**Issue by Hessin87** [sinkillerj/ProjectE#1814]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.4.0 / minecraft version 1.12.2

Exact Forge version:14.23.5.2768

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): does not cause crash or throw any readable errors

Steps to reproduce:

1.get any mod that adds a recipe and a new item

What I expected to happen: if all recipe ingredients have emc values then the result should have an emc value

What happened instead:all recipe ingredients have emc values however the resulting item does not

Pregenerate is set to false, all mappers are set to true

**Comment by MaPePeR** [comment]
So if it is just this one specific item that does not work its probably related to custom crafting recipes that do more than just crafting. The EMC Mapper is not aware to read those, because they don't follow a lot of rules and could do whatever.

**Comment by Hessin87** [comment]
Yeah sorry I shouldn't submit bug reports while sleep deprived I didn't notice just how weird the recipe was until after I had posted this, I'll close this now.
