### ISSUE TITLE
Some items doesnt have emc. These items you can put it table but not pull out.

### ISSUE THREAD

**Issue by 123Kappa** [sinkillerj/ProjectE#1815]
Exact ProjectE version: ProjectE-1.12.2-PE1.4.0.
Exact Forge version: 28.0.8 

Some items doesnt have emc. These items you can put it table but not pull out. I have a public server and we are using sponge. It works fine in single player. Any thoughts? 
Edit: Tome of knowledge doesnt work too

**Comment by sinkillerj** [comment]
We provide no support for third party forks. We are only able to provide support for an unmodified and up to date Forge install at this time.
