### ISSUE TITLE
infinitely detonating nova cataclysm/catalyst

### ISSUE THREAD

**Issue by Hessin87** [sinkillerj/ProjectE#1816]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12.2 PE 1.4.0

Exact Forge version: 14.23.5.2768

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): N/A

Steps to reproduce:

1.Place "1" Nova Cataclysm or "1" Nova Catalyst

2,Detonate either one with either Hyperkinetic or Catalytic Lens

What I expected to happen: "1" big KABOOM and lots of resources dropped

What happened instead: Approximately 216 strangely directed kabooms and lots of resources dropped as well as 216 Nova Cataclysms/Catalysts depending on what you detonated. note, they only stopped because I went up and punched the box, this can keep going on forever. I'll add a complete list of all my mods in a comment.

**Comment by Hessin87** [comment]
![2019-02-07_20 37 58](https://user-images.githubusercontent.com/47364305/52454962-f1a8e580-2b1b-11e9-94f0-a94710205248.png)
![2019-02-07_20 40 27](https://user-images.githubusercontent.com/47364305/52454963-f2417c00-2b1b-11e9-9788-3059da4cba1e.png)

this is what I mean by strangely directed

**Comment by Hessin87** [comment]
AbyssalCraft-1.12.2-1.9.4.15
AdvancedXP-1.0.1
aether_legacy-1.12.2-v3.2
Aroma1997Core-1.12.2-2.0.0.0.b162
Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b87
AutoRegLib-1.3-24
AutoSwitch-v5.6.2-mc1.12.2
Backups-1.12.2-1.4.4
base-1.12.2-3.11.0
Baubles-1.12-1.5.2
BetterBedrockGen-Mod-1.12.1
bettermagnets-mc1.12-v1.06
Clumps-Mod-1.12
compactmachines3-1.12.2-3.0.13-b236
CyclopsCore-1.12.2-1.0.2
daflight-5.2.2-mc1.12.2-minimal
davincisvessels-1.12-6.340-full
Dynamic-Trees-Mod-1.12.2
EquivalentIntegrations-0.1.9-PE1.3.1B
EverlastingAbilities-1.12.2-1.4.0
exnihilocreatio-1.12-0.3.5.1
ExpandedEquivalence-1.12.2-11b
Forgelin-1.8.2
gravestone-1.10.2
HammerCore-1.12.2-2.0.4.1
HelpFixer-1.12.1-1.5.18
Hwyla-1.8.26-B41_1.12.2
InventoryTweaks-1.64-dev
jei_1.12.2-4.13.1.225
JustEnoughIDs-1.0.2-26
LibEx-1.12.2-1.0.8
LingeringLoot-1.12.2-4.3
movingworld-1.12-6.342-full
NetherEx-1.12.2-2.0.8
OptiFine_1.12.2_HD_U_E2
ProjectE-1.12.2-PE1.4.0
SimpleInventoryStarter-0.3-1.12.2
StackUp-0.2.3
ThebombzenAPI-v2.9.2-mc1.12.2
VeinMiner-1.12-0.38.2.647+b31535a
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist
Xaeros_Minimap_1.16_Forge_1.12
XaerosWorldMap_1.3.3_Forge_1.12

**Comment by williewillus** [comment]
is there a world protection plugin active on this world?

**Comment by Hessin87** [comment]
Nope it's SSP I wouldn't even know how to get a "plugin" to work
