### ISSUE TITLE
Superior Shields crash

### ISSUE THREAD

**Issue by jackrtades** [sinkillerj/ProjectE#1820]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  1.12.2-PE1.4.0

Exact Forge version: 14.23.5.2815

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://paste.dimdev.org/balutumaxa.mccrash
Steps to reproduce:
Placed End Steel Energy Shield from Superior Shields into the table
1.

What I expected to happen:
To learn the item
What happened instead:
It crashed

**Comment by sinkillerj** [comment]
Typically this is caused by a mod not having an edge case for its NBT data being missing. The dev will need to add this edge case or you will need to add the item to your NBT whitelist.
