### ISSUE TITLE
ProjectE crashing

### ISSUE THREAD

**Issue by santaclaws01** [sinkillerj/ProjectE#1821]
Exact ProjectE version: 1.12.2-PE1.4.0

Exact Forge version:14.23.5.2815

Link to crash log : https://pastebin.com/KZS6adJH

Steps to reproduce:

1. Have a philosopher's stone in quickbar

What I expected to happen:
To have a philosopher's stone
What happened instead: Game crashing

**Comment by pupnewfster** [comment]
Install JEI, apparently I missed one of the spots when I was fixing it crashing without JEI installed.
