### ISSUE TITLE
Game crashed with Philosopher's Stone in my hand and Mobius Fuel in my inventory

### ISSUE THREAD

**Issue by 71Hurricane17** [sinkillerj/ProjectE#1841]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
	ProjectE-1.12.2-PE1.4.0
	(No other mod installed, just the ProjectE)

Exact Forge version:
	forge-1.12.2-14.23.5.2768

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://github.com/71Hurricane17/Misc/issues/1
  
  
  
  
  
 
Steps to reproduce:

1. I was trying to create an Aeternalis Fuel to make Dark Matters
2. First, I created an Alchemical Coal
3. Then, I placed it at the Transmutation Table
4. That way I made 4 Alchemical Coal
5. When I tried to make a Mobius Fuel, it showed me its image in the crafting table output
6. Then when I removed it from the crafting table and placed at my inventory the game crashed
7. The save now always crashes when I try to open the game

- That wasn't the first bug that happend, and I think this other bug is related:

1. When I created the Philosopher's Stone I placed it in my hand. But not direcly at the slot I was holding.
2. Then, with my mouse weel, I scrolled towards the Philosopher's Stone
3. Before reaching it, the game crashed
4. Every time I tried to hold it (after the first time the bug happened) the game kept crashing
5. For this bug, I was able to load back my save and keep playing (the Mobius Fuel bug in the other hand corrupted the save and I no longer was able to play)

- The log report that I pasted above is related to the Philosopher's Stone bug, not the Mobius Fuel one...
Here it's why:
 After the Aeternalis Fuel bug happend (and I wasn't able to play my save anymore), I decided then to use the "Universal Minecraft Editor" software to edit my inventory:

1. First I tried to delete the Mobius Fuel and play the game
2. That didn't solve...
3. Then I removed the Philosopher's Stone and I was able to play!!!
	 
	 
	 
	 
	 

What I expected to happen:
1. I was expecting to make some Dark Matters
2. I was trying to place the Philosopher's Stone in my hand to use the "C key" crafting grid

What happened instead:
1. The game crashed when I placed the Mobius Fuel in my inventory
2. The game crashed when I scrolled towards the Philosopher's Stone
	 
	 
	 
	 
	 

What I did to ""solve"" this issue:
1. After using the "Universal Minecraft Editor" to remove the Mobius Fuel and Philosopher's Stone, I changed my game to creative mode and give myself a Philosopher's Stone and a Mobius Fuel.
2. I was able to place the Mobius Fuel in my inventory and the Philosopher's Stone in my hand while in creative mode and use the "C key" crafting grid!
3. But when I change the mode to survival mode and I was no longer able to place it in my hand (the game crashed)
4. Then, I changed again to creative and the game crashed when I tried to place it in my hand
5. So I deleted the Philosopher's Stone (in creative mode) and give myself another one
6. That didn't helped... The game crashed again
6. The log report (that I pasted above) is related to this crash.

- It wasn't trully solved, but at least I was able to keep playing the game and, for a moment, I was able to have a Mobius Fuel in my inventary and hold and use the "C key" of the Philosopher's Stone

**Comment by williewillus** [comment]
fixed in next version, as a workaround install JEI for now
