### ISSUE TITLE
Massive Duplication/Lag Bug with Nova Catalyst

### ISSUE THREAD

**Issue by Big-Cheung** [sinkillerj/ProjectE#1843]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  ProjectE 1.4.0 for MC1.12.2

Exact Forge version: 14.23.5.2768

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
None

Steps to reproduce:

1. Place a Nova Catalyst next to another Nova Catalyst
2. Light it up underground.

What I expected to happen:
Two explosions.

What happened instead:
Infinite loop of explosions that creates repeating drops of Nova Catalysts. There is a strange crosshatch pattern created from this interaction when placed underground. The Nova Catalyst will continue to explode because the actual catalyst blocks are never removed by the explosion. The drop is created, the explosion is created, but the block is never removed, which repeats the cycle.

**Comment by williewillus** [comment]
fixed in next version
