### ISSUE TITLE
Alchemical bag able to exceed maximum NBT data byte size

### ISSUE THREAD

**Issue by Artitus** [sinkillerj/ProjectE#1844]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12.2-PE1.4.0

Exact Forge version: 14.24.5.2781

_**This crash log is from me clicking the join button to me disconnecting with an error.**_
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://paste.ee/p/RH6za

Steps to reproduce:

1. Get 60 16384k me storage drives from ExtraCells2, fill them up with a couple million items of different variety
2. Put them all in an alchemical bag to transport them
3. Change dimensions
4. Crash with the message "A fatal error has occurred, this connection is terminated"

What I expected to happen: I wanted to switch worlds just fine

What happened instead: I crashed

**Comment by williewillus** [comment]
not much to do here, this problem appears in any kind of nested item transport (like putting your drives in shulker boxes then putting those in your ender chest)

the solutions are either:
1. crash so the user can recover with an nbt editor manually
2. silently delete items to prevent a crash

1 is preferable in this case

**Comment by Artitus** [comment]
I'm trying to use an NBT editor. How would I access the inside of the alchemical bag with it though? I 100% need to save the contents inside of the bag. It is literally ALL of my ME Drives. Tens of millions of items

**Comment by Artitus** [comment]
nvm
