### ISSUE TITLE
Overloaded armour crashes client/server

### ISSUE THREAD

**Issue by krisjenner** [sinkillerj/ProjectE#1847]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version: 2815 - 1.12.2

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://gist.github.com/krisjenner/c5d4d2a7deea82156f1b4876c157c44c
Steps to reproduce:

1.Overloaded multi-chestplate in Transmutation Table = boom

What I expected to happen:
learned item
What happened instead:
server boom

**Comment by sinkillerj** [comment]
The mods rendering code does not know how to handle a edge case where its EMC is missing, this is something only they can fix. Beyond contacting them you can try adding it to your NBT whitelist.

**Comment by sinkillerj** [comment]
The mods render code does not know how to handle an edge case where its NBT is missing. Contact the mod author or add it to your NBT whitelist.
