### ISSUE TITLE
FTB Sky Odyssey

### ISSUE THREAD

**Issue by L3Chuuck** [sinkillerj/ProjectE#1848]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version: ProjectE-1.12.2-PE1.4.0, ForgeMultipart-1.12.2-2.6.1.81-universal, FTB Sky Odyssey

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. Cant insert any items to the transmutations table/tablet, maybe because the stored value already to high?

What I expected to happen:
Should get the EMC value that the item has.
What happened instead:
Cant insert the item to get the EMC value.

**Comment by Slowpoke101** [comment]
Came to mention this as well, Our latest modpack allows extreme amounts of EMC possible. When the amount of EMC stored gets too big then the EMC breaks down and you can no longer insert items and when you withdraw items, then it no longer removes the emc cost from the total.

**Comment by L3Chuuck** [comment]
There is a workaround use a personal EMC link from ProjectEX then items can be inserted but like you said probably not adding it to the stored value.

**Comment by pupnewfster** [comment]
This isn't a bug in ProjectE. It is the fact that Project EX hacks it to allow for values past max long. Which also has the side effect of "small" values of EMC don't get used or added due to precision loss which is exactly why ProjectE does not support it itself.
