### ISSUE TITLE
Server Error Upon Use Of The Red Matter Axe

### ISSUE THREAD

**Issue by Cyranos** [sinkillerj/ProjectE#1850]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12.2-PE1.4.0

Exact Forge version:14.23.5.2823

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/HvgJR9Ax

Steps to reproduce:

1.On the server I would walk into a forest (For me a birch forest) and did the use item click (default is right click) 
What I expected to happen:
Whole chunks of a forest to be gone

What happened instead:
Random logs of the entire tree but not the leaves would disappear and I would not get anything, sometimes it would do nothing, other times it would work but very very rarely I got it to work like twice in an hour and a half

**Comment by pupnewfster** [comment]
Closing as this should be fixed with the rewrite I did to the internals of tools in 1.14+
