### ISSUE TITLE
Unable to craft Transmutation table

### ISSUE THREAD

**Issue by 12InchFinch** [sinkillerj/ProjectE#1851]
ProjectE version: 1.7.10-PE1.10.0

Forge version: 10.13.4.1614

I was trying to make a transmutation table I have the exact recipe even tried with the philosophers stone on different power levels but it wouldn't craft

**Comment by sinkillerj** [comment]
1.7 is no longer supported. That said it sounds like you are playing on a server where you have no installed the mod.
