### ISSUE TITLE
ShowBag Command Can't Find LightBlue

### ISSUE THREAD

**Issue by Aiidoneus** [sinkillerj/ProjectE#1855]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.12.2-PE1.4.0.jar

Exact Forge version:
forge-14.23.5.2795

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. Type command /projecte showBag lightBlue `<user>`
(Note: You can also tab complete to show all colors, and I auto-fill lightBlue and still get the error)
![image](https://i.imgur.com/tCwfaxq.png)

What I expected to happen:
I expect that I should be able to select the lightblue bag but it doesn't exist.

What happened instead:
I get an error saying the color doesn't exist

SideNote: I also noticed that the Light Gray bag is labeled under silver when using the command? Not sure if it is really important, but worth noting.

**Comment by williewillus** [comment]
try light_blue instead

**Comment by Aiidoneus** [comment]
> try light_blue instead

That did work. It is just misleading that tab auto-fill for the colors shows lightBlue rather than light_blue.

**Comment by pupnewfster** [comment]
Closing as with the rewrite of commands to match vanilla's new system in 1.14+ tab complete properly suggests the correct value.
