### ISSUE TITLE
Pink Matter Relay not showing in Transmutation Table

### ISSUE THREAD

**Issue by Reaper9802** [sinkillerj/ProjectE#1857]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12.2-PE1.4.0

Exact Forge version: Minecraft Forge: 14.23.5.2815, Forge Mod Loader: 8.0.99.99

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): No crash log

Steps to reproduce:

1. Place Pink Matter Relay into Transmutation table.
2. Remove from center of Transmutation table (if you placed it there to learn the recipe)
3. Search for Pink matter Relay in Transmutation table. Won't find the item
4. Scroll through all items in Transmutation table. Won't find the item

What I expected to happen: Find the Pink Matter Relay in the Transmutation table

What happened instead: Item doesn't show

**Comment by williewillus** [comment]
what is a pink matter relay?

**Comment by triffman33** [comment]
I also don't know of any pink matter relay xD but you need to have enough EMC to get the item in order to see it.

**Comment by Nova001Sol** [comment]
The pink matter relay is from the Project EX addon. And Triffman33 is correct, you need enough EMC for it to show up in the standard transmutation table and tablet.
