### ISSUE TITLE
ProjectE Multiplying my transmutation "icons" in the table, causing extreme navigation issues, lag, and crashing

### ISSUE THREAD

**Issue by InQuognito** [sinkillerj/ProjectE#1860]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
- 1.4.0

Exact Forge version:
- 14.23.5.2815

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
- https://paste.ee/p/kUV30

Steps to reproduce:

1. Not quite sure, it just 'happened', not sure when because I just opened my tablet and everything (including vanilla items and items from other mods) was multiplying. It makes it extremely hard to navigate. Oh, and it also crashed my game I'm pretty sure. From all the lag.
2. **NOTE** This happened around the time I put Matter Overdrive items in my tablet. If that's important.

Update: There are now multiple pages of every item. :\

What I expected to happen:
- For it to not multiply my item icons by 10397473x

What happened instead:
- This ^^

**READ COMMENTS**

**Comment by InQuognito** [comment]
<img width="357" alt="Screen Shot 2019-04-06 at 11 25 16 AM" src="https://user-images.githubusercontent.com/44120299/55672631-de3ba180-5862-11e9-9c59-1c34d8b1f3a5.png">

**Comment by InQuognito** [comment]
Restarting the game fixed the issue, but leaving the issue open unless the devs want to close it in case it happens to anyone else and they want to fix it in future updates.

**Comment by InQuognito** [comment]
> Restarting the game fixed the issue, but leaving the issue open unless the devs want to close it in case it happens to anyone else and they want to fix it in future updates.

Scratch that, it happened again. Crashed me... again. I think I'm done with ProjectE until this is resolved. This is on Sky Odyssey, by the way.

**Comment by lemoncool375** [comment]
This issues happened to me as well, but only after I start playing with MatterOverdrive.

**Comment by pupnewfster** [comment]
Closing as I believe this was fixed in PE 1.4.1
