### ISSUE TITLE
Projecte not letting emc change luckperms

### ISSUE THREAD

**Issue by nacjm** [sinkillerj/ProjectE#1863]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.4.0

Exact Forge version:2824

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://hastebin.com/dohavufazu.md

Steps to reproduce:

1.Install sponge 7.1.6-RC3616
2.Install luckperms
3.give perms to project e command
4. try to add emc to item
5. "You do not have permission to use this command." 
What I expected to happen: be able to alter emc of item

What happened instead:"You do not have permission to use this command." 

P.S: seems to be duplicate of #1662 
Hopefully I gave you more info this time though

**Comment by pupnewfster** [comment]
Closing as I believe this is an issue with the permission mod as we are not doing anything special (other than saying it is an "op" command the same way `/gamemode` is set to being an "op" command).
