### ISSUE TITLE
Specific interaction between ProjectE, ProjectEX, Applied Energistics 2 causing server crash.

### ISSUE THREAD

**Issue by jarquafelmu** [sinkillerj/ProjectE#1864]
There seems to be a negative interaction happening with AE2 and ProjectE when AE2 tries to craft. I am posting this here in addition to the ProjectEX and AE2 repositories in hopes that a solution can be found.

### Other referenced tickets:
https://github.com/LatvianModder/Project-EX/issues/32
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3994

### Exact ProjectE version: 
1.12.2-PE1.4.0

### Exact Forge version:
14.23.5.2815

### Link to crash log: 
The server locks up but then crashes when trying to exit so I wasn't able to find any generated crash log. However, I do have the logs from around the time and hopefully they show something.
https://drive.google.com/drive/folders/1d9ZfUnn427XJi6Q3tpGXFm_1pnjmjkNm?usp=sharing

### Steps to reproduce:
1. Hook Applied Energistics 2 network to ProjectE network using ProjectEX Compressed Refined Personal EMC Link and AE2's storage buses.
2. Add crafting capability to AE2 network.
3. Order something to be crafted from the AE2 network.

### What I expected to happen:
For there to be no hiccup and for items to be pulled from the ProjectE network as needed.

### What happened instead:
The server will lock up saying "Waiting for server" and will not allow any more interactions to still happen. Users can still move around but are unable to interact with anything else.

### Save file:
https://drive.google.com/open?id=1OTk-dHXTrurOgF2_N1ntOtyz75Xx7L6d

### Other Versions:
**Minecraft:** 1.12.2
**Forge:** 14.23.5.2815
**FTB Sky Odyssey:** 1.0.0
**Applied Energistics 2:** rv6-stable-6
**ProjectE:** 1.12.2-PE1.4.0
**Project EX:** 1.1.0.14

**Comment by d4julian** [comment]
[Stall Report](https://hastebin.com/iwabihojox) if needed to investigate.

**Comment by ouroborus** [comment]
Same thing here with Stoneblock 2 (FTBPresentsStoneblock2-1.16.0-1.12.2.zip, appliedenergistics2-rv6-stable-7.jar, ProjectE-1.12-PE1.3.2h.jar, ProjectEX-1.0.0.10.jar), when trying to use AE2 auto-crafting with ingredients coming from a Personal EMC Link block.

https://gist.github.com/ouroborus/c06c9f9910521412baf75c44af62c030

**Comment by pupnewfster** [comment]
1. That is a rather out of date version of ProjectE
2. ProjectE doesn't add the "Personal EMC Link", so this is probably a bug with Project EX not providing/handling the data that AE2 is asking of it properly.
