### ISSUE TITLE
Crash when initializing

### ISSUE THREAD

**Issue by FiliboyYT** [sinkillerj/ProjectE#1867]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version ProjectE-1.12.2-PE1.4.0.jar

Exact Forge version: Newest 1.12.2-14.23.5.2836

Link to crash log https://pastebin.com/nGmEqNLA

Steps to reproduce:

1.

What I expected to happen: load the game normally

What happened instead: Crash when initalizing the game

**Comment by sinkillerj** [comment]
This is not a ProjectE issue, you have too many mods in your pack and there are no further item ID's that Forge can assign.
