### ISSUE TITLE
Error with minecraft:wheat item when joining server

### ISSUE THREAD

**Issue by gerry1128** [sinkillerj/ProjectE#1868]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.12.2-PE1.4.0.jar

Exact Forge version:
forge-1.12.2-14.23.5.2824-universal

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://www.dropbox.com/s/nbl05pzjhc86w5k/mc%20error.PNG?dl=0
Steps to reproduce:
The server I am running is Tekxit 3 and works fine. Then when all i add is ProjectE to the server mod file and my game file this, this error shows up after I get disconnected from the server. Singleplayer works fine but connecting to a server gets disconnected.

My Technic modpack is 
http://api.technicpack.net/modpack/tekxit-3-1
My server files are https://www.dropbox.com/sh/kxkv4xwt6z1cohu/AACUHRilzDMKyvVKwavrgc58a?dl=0

What I expected to happen:
I was hoping

 I could join the server
What happened instead:
The error popped up

If you need more info let me know

**Comment by pupnewfster** [comment]
Closing as I do not believe this has to do with projecte (nor can I reproduce it in 1.15). If memory serves this was a forge bug that appeared when registries failed to sync properly.
