### ISSUE TITLE
Issues with buckets filled with Thermal Foundation Liquids

### ISSUE THREAD

**Issue by TH3GOD88** [sinkillerj/ProjectE#1871]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12-PE1.3.2h

Exact Forge version: forge-14.23.5.2796

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): N/A

Steps to reproduce: Fill a bucket with Thermal Foundation liquids

What I expected to happen: To learn it in knowledge.

What happened instead: Doesn't accept it even when it has an EMC value

**Comment by pupnewfster** [comment]
Closing as 1.14+ has proper support for handling items with NBT

**Comment by TH3GOD88** [comment]
How does that help me with 1.12?
