### ISSUE TITLE
ProjectE and IC2 Clash

### ISSUE THREAD

**Issue by partridge420x** [sinkillerj/ProjectE#1874]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version: 1.12.2-PE1.4.1

Exact Forge version: 2825

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): no logs to show for the problem

Steps to reproduce:

1. give emc to insulated/un-insulated copper cables, and be able to reproduce to use with crafting recipies

What I expected to happen:  see steps to reproduce

What happened instead: Both insulated and un-insulated coper cabling shares emc vlaue.

a. When learning a insulated copper cable, it will not appear
b. if pulling un-insulated copper cable it will not work with crafting recipies
if its crafted, or spawned in. it will work

**Comment by PitchBlackLaser** [comment]
also a funny clash between the 2 mods if you use the copper cables from the transmutation tablet for IC2 Coil recipies (or maybe even other recipies) it won't work...

**Comment by pupnewfster** [comment]
Closing this as I hope in 1.15 IC2 will not still be using NBT to determine items (due to the flattening of 1.13), but even if it does ProjectE for 1.14+ has proper support for handling items by NBT.
