### ISSUE TITLE
[Suggestion] Philosopher's Stone Recipe Change

### ISSUE THREAD

**Issue by Furious2014** [sinkillerj/ProjectE#1875]
I would suggest changing the recipe of the Philosopher's Stone to require a Netherstar instead of a Diamond. Because it would balance the mod a bit more since the Transmutation Tablet would be locked behind a Witherfight. DM and RM would just be a bit more difficult to get since you need the Collector at least to get Aeternalis Fuel.

It would result in the mod becoming more endgame in nature and so lock the transmutation behind the Wither would be a good point. Also, it might be in more modpacks, because it doesn't take the early fun and grind away and after the Wither you are far enough, that the Transmutation Table wouldn't hurt further gameplay in modpacks.

**Comment by sinkillerj** [comment]
Minetweaker or Crafttweaker will allow you to edit recipes.
