### ISSUE TITLE
Negative or wrong EMC values with Practicalities tools / Overflow in EMC calculation with high values

### ISSUE THREAD

**Issue by chris54721** [sinkillerj/ProjectE#188]
Imbued Sword and Imbued Tool from Practicalities have wrong EMC values. I don't know if this is a ProjectE or Practicalities bug. 
![Imbued Sword EMC](https://cloud.githubusercontent.com/assets/3685659/4918344/07bb12ae-64f0-11e4-9c24-a1b8bfdd6eb6.png)
In the image, Imbued Sword has a negative EMC value, but the sum of EMC values of its crafting components is 6,352,784. The same happens with the Imbued Tool, which has an EMC value of 213,879 and is made up of items which have a total EMC value of 12,688,384.
Apparently this also allows for infinite EMC, as if you learn Imbued Sword trasmutation, you GET 90,000 EMC every time you pick one. Burning one removes EMC from the table.

Running latest version of ProjectE (0.2c).

I think this could be a bug in EMC calculation from crafting recipes. ~~Which Java type is used for storing (and calculating) EMC? By default if a number overflows the MAX_VALUE of its type it goes back to its min value and continues from there. However apparently no types have a MAX_VALUE between 2 million (the maximum not bugged EMC value I've seen) and 2 billion (Integer.MAX_VALUE is ~ 2,1 billion).~~
**EDIT**: apparently you are using the **double** type to store EMC. Doubles are bad for handling big numbers, they were made to handle long decimal values. Since EMC values are integers, I suggest you to switch to the **long** type for storing them. If you want more precision when calculating EMC values from crafting recipes, I suggest using the **float** type.

**Comment by SammieBanks** [comment]
When Shift clicking the Soul Sand or the Wither Skulls out of the Wither killer it duplicates the items.
