### ISSUE TITLE
EMC total is in the negative.

### ISSUE THREAD

**Issue by Furious1964** [sinkillerj/ProjectE#1880]
Playing FTB Stoneblock 2 (Latest Version)

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.2.2 PE1.4.1

Exact Forge version: 14.23.5.2836

Steps to reproduce:

1. Almost got the MAX EMC Level and it flipped into the negative

What I expected to happen: Hit the Max Level and complete a Quest.

What happened instead: Flipped into the Negative. I now have -9,060,231,479,767,642,112 EMC.

Any help would be appreciated.

**Comment by RealPwned** [comment]
any solutions?

**Comment by Furious1964** [comment]
I tried to reset the counter, but that didn't work. The only thing that did was to cheat in some of the Tier 15 Power Flowers and wait til it flipped back to the positive. It seems that the mod can't handle a very fast surge of EMC points being generated and when it reaches the MAX limit, it goes negative.

**Comment by RealPwned** [comment]
thank you very much!.

**Comment by RealPwned** [comment]
do you know the maximum emc?

thats my emc right now
http://prntscr.com/nzjl5n

**Comment by Furious1964** [comment]
9,223,372,036,854,775,807 should be the MAX limit and it flips before reaching it.

**Comment by RealPwned** [comment]
when do you think you will be the emc again in the positive area?

0 ?

**Comment by Furious1964** [comment]
Just flipped mine back into the negative and testing it out. My conclusion so far is that it'll have to accumulate the point back to zero before you will see any EMC being generated. I'm testing that out now.

**Comment by Furious1964** [comment]
IMHO, the Power Flowers and Tome of Knowledge are VERY OP, they allowed me to basically win the game in over 400 days.

**Comment by Furious1964** [comment]
Yes, after it reaches zero, you restart generating EMC over again from scratch.

**Comment by RealPwned** [comment]
that will take days :o

**Comment by RealPwned** [comment]
if my emc reached 0

**Comment by Furious1964** [comment]
Are you generating into the positive now?

**Comment by RealPwned** [comment]
nope first to 0 

o.O

**Comment by Furious1964** [comment]
Put something into the transmutation table or whatever you have to see if you get positive EMC.

**Comment by RealPwned** [comment]
im not able to put items in it or out..
Thats my EMC right now: http://prntscr.com/nzk3nl

**Comment by RealPwned** [comment]
i think i have to wait until the emc is 0

**Comment by Furious1964** [comment]
Yes, it has to count back up to zero. Just go into Creative mode and spawn in a ton of the tier 15 power flowers and break them when you're over zero.

**Comment by RealPwned** [comment]
already done
http://prntscr.com/nzk5d4

**Comment by Furious1964** [comment]
If you sneak, you should see the counter ticking to zero.

**Comment by RealPwned** [comment]
not anymone.. its bugged.
but i can see the emc value in the emc tablet.
yeasterday it worked with sneak
i think thats why i reached the maximum / negativ emc value

**Comment by Furious1964** [comment]
How far are you into the game? You might have to ask the Mod Author for help as I've never encountered it not being able to generate emc after reaching zero.

**Comment by RealPwned** [comment]
only the chaos guardian is left.
-4,2 Quint. left and them we will see what will happen

________________________________
Von: Furious1964 <notifications@github.com>
Gesendet: Sonntag, 9. Juni 2019 16:51
An: sinkillerj/ProjectE
Cc: RealPwned; Comment
Betreff: Re: [sinkillerj/ProjectE] EMC total is in the negative. (#1880)


How far are you into the game? You might have to ask the Mod Author for help as I've never encountered it not being able to generate emc after reaching zero.

**Comment by RealPwned** [comment]
Now is the EMC Positive. Thank you!

**Comment by RealPwned** [comment]
//close
