### ISSUE TITLE
classcastexception with entityhomingarrow

### ISSUE THREAD

**Issue by kreezxil** [sinkillerj/ProjectE#1881]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  1.12.2-PE1.4.1

Exact Forge version: 14.23.5.2836

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):
https://pastebin.com/gwv7gZcj 

Steps to reproduce:

1. flying while attacking a dragon from Ice and Fire with zoo and wild animals nearby
2. was using the Archangel's Smite which launches homing arrows.

What I expected to happen:
client not to crash

What happened instead:
client crashed.

**Comment by 0SoggyMustache0** [comment]
I (zawa dev) am aware of the issue and have just fixed it, there was an unchecked cast. It is fixed in the next zawa version to be released.
