### ISSUE TITLE
API Request: Add register events to FuelMapper

### ISSUE THREAD

**Issue by Zeitheron** [sinkillerj/ProjectE#1883]
Exact ProjectE version: 1.12.2-PE1.4.1

Exact Forge version: 14.23.4.2707

## Preface:
I am developing an addon [Equivalent Additions](https://minecraft.curseforge.com/projects/303583), that adds additional fuel, that should be obtainable either using philosopher's stone, or  EMC Collector. The way it currently registers this fuel upgrade is... a little bit hacky, and I'd like to get rid of such code, since it causes various lags in rare cases.

## The Request:
I would love a new event, that will allow developers to register custom fuel types into [FuelMapper](https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/emc/FuelMapper.java). The event would either hold a list of SimpleStack with fuel, or a new list that will be registered after the event is dispatched.

## Use Cases:
This event would allow me to implement custom fuel into collectors without using any reflections, while loops and more sorting of the list

**Comment by pupnewfster** [comment]
This probably won't get resolved in 1.12, given 1.12 is basically in a feature freeze currently. But in 1.14 I have resolved this by adding a tag that mods can add their items to so that they get registered into fuel mapping list if they have an EMC value.

**Comment by pupnewfster** [comment]
Adding any items to the item tag `collector_fuel` in 1.14+ will make it so that the item gets added to the list of items that can be upgraded in the collector.
