### ISSUE TITLE
Adding repair support for Tinkers Weapons/Tools/Armor

### ISSUE THREAD

**Issue by jusitnboggs** [sinkillerj/ProjectE#1888]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.12.2 PE1.4.0
Exact Forge version:
14.23.52838

Can you add support for Tic to the repair talisman?

**Comment by pupnewfster** [comment]
No, we obey mods that their tools are not repairable, as ignoring that could cause the other mod to break.
