### ISSUE TITLE
Mekanica support

### ISSUE THREAD

**Issue by Nukeer9578** [sinkillerj/ProjectE#1891]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.41
Exact Forge version:
14.23.5.2836
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
-blank-
Steps to reproduce:
play with Mekanica instead of Mekanism
What I expected to happen:
The game to launch.
What happened instead:
The Game didn't launch. (it asked for Mekanica (Mekanism) 1.2.0)

**Comment by sinkillerj** [comment]
Blank is not a log.

**Comment by Nukeer9578** [comment]
This is the error message from the log:

net.minecraftforge.fml.common.MissingModsException: Mod projecteintegration (ProjectE Integration) requires [mekanism@[1.12.2-9.7.0.369,)]
23:21:47
FML
Client thread
error
An exception was thrown, the game will display an error screen and halt. Missing Mods: unknown : need [1.12.2-9.7.0.369,): have 1.12.2-1.2.0 net.minecraftforge.fml.common.MissingModsException: Mod projecteintegration (ProjectE Integration) requires [mekanism@[1.12.2-9.7.0.369,)] at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264) at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570) at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) at net.minecraft.client.Minecraft.init(Minecraft.java:467) at net.minecraft.client.Minecraft.run(Minecraft.java:3931) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by sinkillerj** [comment]
This is an issue with another mod, we are not responsible for ProjectE Integration.

"(ProjectE Integration) requires [mekanism@[1.12.2-9.7.0.369,)]"

**Comment by Nukeer9578** [comment]
Oh, sorry to waste your time. Thanks anyways!
