### ISSUE TITLE
Server crash upon updating from version 1.4.0 to 1.4.1

### ISSUE THREAD

**Issue by themaster402** [sinkillerj/ProjectE#1895]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12.2-PE1.4.1

Exact Forge version: 1.12.2 - 14.23.5.2838

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/zDCiD561

Steps to reproduce:

1. Update ProjectE on server from 1.4.0 to 1.4.1
2. Launch a 1.12.2 Forge server with a preexisting world that used 1.4.0.

What I expected to happen: Server loads normally and boots into the world.

What happened instead: Server abruptly crashes amidst ProjectE loading.

**Comment by dedmen** [comment]
https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/utils/EMCHelper.java#L327

Related
#1884

**Comment by sinkillerj** [comment]
Duplicate issue.
