### ISSUE TITLE
[Compatibility/Suggestion] Remove capitalization requirement for commands

### ISSUE THREAD

**Issue by DefinitelyNotFred** [sinkillerj/ProjectE#1897]
ProjectE commands are impossible to use when the NoMoreCapsLockCommands mod is also installed. NMCLC makes it so any command entered with capitalization will be interpreted as being all lowercase so an accidental usage of the caps lock doesn't mean you need to retype commands. ProjectE commands require the use of both capitalized and uncapitalized letters.
Regardless of the NMCLC mod issue, it would be more user friendly if this feature was implemented. Interestingly, the vanilla subcommands for /gamerule already have this feature without the use of NMCLC, maybe you can use that to your advantage somehow.

**Comment by pupnewfster** [comment]
Closing as 1.14+ I believe all commands are lower case (though I don't remember for certain if you can instead use upper case characters. If you can't and you want them for 1.15 feel free to comment and I will reopen this issue.
