### ISSUE TITLE
Project E causing a 'severe problem' during mod loading

### ISSUE THREAD

**Issue by Windmilz** [sinkillerj/ProjectE#1899]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12.2-PE1.4.1

Exact Forge version: 1.12.2-14.23.4.2766

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/s63ppdJC

Steps to reproduce:

1. Run forge with ProjectE in the mods folder

What I expected to happen: the game launches into the minecraft menu

What happened instead: The game crashes, stating "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ProjectE (projecte)"

**Comment by sinkillerj** [comment]
Your NBT whitelist file is corrupt, delete it and the game should load normally.
