### ISSUE TITLE
EMC stays at one value and resets back to that value

### ISSUE THREAD

**Issue by PitchBlackLaser** [sinkillerj/ProjectE#1900]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): PE1.4.1

Exact Forge version: forge-1.12.2-14.23.5.2838

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): not a crash... it's a bug...

Steps to reproduce:

1. have a MK4 Power Flower from from Equivalent Additions
2. let it feed into a EMC Proxy from the same mod while already in posession of about 147Billion - 149 Billion EMC

What I expected to happen:
My EMC should permanently increase unless I take something out of the Transmutation tablet
What happened instead:
My EMC increased only until I went to the nether or some other dimension or until I closed the game and re-opened it... the EMC value was once again at 147 Billion - 149 Billion

**Comment by pupnewfster** [comment]
Closing as neither the MK4 power flower or the EMC Proxy are parts of ProjectE, so I find it likely it is a bug in the other mod.
