### ISSUE TITLE
Can't place star in condenser without generating a fake item

### ISSUE THREAD

**Issue by Charismara** [sinkillerj/ProjectE#1901]
Exact ProjectE version: 1.12.2-PE1.4.1

Exact Forge version: 14.23.5.2838

Steps to reproduce:

1. place a condenser mk1
2. insert a klein star into the emc storage slot
3. now you will have the star on your mouse and in the slot.

What I expected to happen:
the star should be placed in the slot.
What happened instead:
the star was placed in the slot and on my mouse.

Here is a Gif to show what i mean:
![show](https://user-images.githubusercontent.com/14293974/60684849-4456b580-9ea0-11e9-8368-9cc1eb013f37.gif)

the star in the condenser is not the real item. It just shows up there.
We're playing on a Server. Maybe it's a syncbug? i don't know xD

**Comment by sinkillerj** [comment]
Thats how its supposed to work....
