### ISSUE TITLE
Repeated items on Transmutation Table&Tablet

### ISSUE THREAD

**Issue by 1170300104** [sinkillerj/ProjectE#1902]
Exact ProjectE version: 1.12-PE1.3.2h

Exact Forge version: 14.23.5.2796

Link to crash log: This bug won't cause crash.

Steps to reproduce:
1. Get a transmutation tablet/table.
2. Learn an item like Philosopher's Stone(or items of other mods).
3. After several operations of learning and unlearning(don't know exactly what I've done,it's like a random).
4. Repeated icons will appear.
![图片](https://user-images.githubusercontent.com/30775647/60715109-e03efa80-9f4e-11e9-99a4-8ff059669269.png)
![图片](https://user-images.githubusercontent.com/30775647/60715130-eaf98f80-9f4e-11e9-9fb4-ec8c23441ec8.png)
![图片](https://user-images.githubusercontent.com/30775647/60715147-f8af1500-9f4e-11e9-84a4-3333e7ab5439.png)
Both of two icons are totally the same item(with the same description).
And after unlearning,one of the two icons will still be there.

What I expected to happen:
Only one icon for each item learned.

What happened instead:
Two icons of the same item.

**Comment by sinkillerj** [comment]
Please update to the latest version of ProjectE and this issue should be resolved.
