### ISSUE TITLE
after updating emc values can no longer load saved games or create new saved games

### ISSUE THREAD

**Issue by raziel23x** [sinkillerj/ProjectE#1905]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.4.1

Exact Forge version: 14.23.5.2838

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
Crash Report
https://paste.dimdev.org/ebogeyucid.rb

Steps to reproduce:

1.

What I expected to happen: load saved games or create new ones

What happened instead:
crash report are generated and the game just stuck at loading world Building terrain screen

CUSTOM_EMC.JSON
https://paste.dimdev.org/urowuqufut.json

PROJECTE.CFG
https://paste.dimdev.org/egijipaqoq.coffeescript 

mapping.cfg
https://paste.dimdev.org/culepariru.bash

Before all this happened I just used the following commands on the applied energistics 2 plates and the logic boards...
/projecte setEMC
/projecte reloadEMC

**Comment by sinkillerj** [comment]
Please take this over to the Equivalent Energetic page, as the crash seams to be from that addon. Before doing so ensure that you are using a up to date version with a compatible build of Applied Energistics.
