### ISSUE TITLE
Crash with the 1.4.1 1.12.2 release

### ISSUE THREAD

**Issue by therealpwnguy1** [sinkillerj/ProjectE#1913]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.12.2-1.4.1

Exact Forge version:
forge-14.23.5.2838

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://paste.dimdev.org/ofusemoxij.mccrash

Steps to reproduce:

1. Launch the game

What I expected to happen:
The Game to Load

What happened instead:
The Game Crashed

**Comment by sinkillerj** [comment]
Your NBT whitelist config is corrupt, likely due to a malformed manual edit. Delete it.

**Comment by therealpwnguy1** [comment]
I deleted the nbt_whitelist.json file and got the same crash.

https://paste.dimdev.org/vihidanawi.mccrash
