### ISSUE TITLE
[FEATURE] add the ability to view EMC with The One Probe

### ISSUE THREAD

**Issue by Hyperrite** [sinkillerj/ProjectE#1916]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.4.1
Exact Forge version:
1.12.2 14.23.5.2838
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
N/A
Steps to reproduce:

1. Open Minecraft
2. Run a random world
3. view for example a stone block

What I expected to happen:
view EMc
What happened instead:
I don't view EMC

I have installed The One Probe Because it has a better GUI, but I can't view EMC values :(
I

**Comment by pupnewfster** [comment]
ProjectE for 1.14+ has compat with the one probe and HWYLA
