### ISSUE TITLE
Repair Talisman can't repair TC tools

### ISSUE THREAD

**Issue by CorneliusCornbread** [sinkillerj/ProjectE#1917]
ProjectE Ver: 1.12.2-PE1.4.1

Forge version: 14.23.5.2844

(no crash)

Steps to reproduce:

1. Damage Tinker's Construct tool
2. Place in alchemical chest with repair talisman

What I expected to happen:
My TC tool to be repaired

What happened instead:
Nothing

**Comment by sinkillerj** [comment]
The talisman respects the norepair flag, this is by design.

**Comment by Razielous** [comment]
> The talisman respects the norepair flag, this is by design.

Would you be willing to make this a setting in the config file?

**Comment by pupnewfster** [comment]
In my opinion this should not be a config option as it could hardcore break the intended mechanics of another mod if we ignore the wishes for them to not be repairable. If tinkers added a config to allow their weapons and stuff to not say it is not repairable then it would work from us with that option set. But if they do not think it would break their mod too much they could add a config,

**Comment by sinkillerj** [comment]
I agree with this, looking at it from a dev perspective so many things would just break. So many mods use the system for things that aren't damage, and by not respecting the flag you could say, take an empty diamond pouch, PE would attempt to "repair" it, but in reality it would be filling up that pouch, would you want that? There's mods I can think of now that fail to set norepair and have this issue.
