### ISSUE TITLE
Some items from the Avaritia mod dont have any emc value

### ISSUE THREAD

**Issue by AC77Games** [sinkillerj/ProjectE#1919]
The title is pretty self-explanatory, but i dont know if thats a bug or a feature. Those items that havent any emc value are the Infinity Catalyst, the Infinity Ingot and some Singularities.

**Comment by sinkillerj** [comment]
ProjectE will attempt to map EMC for recipes where all the ingredients have EMC values, unless said recipe uses a custom crafting handler. The /projecte setEMC command can be used while holding an item to set a value for it.
