### ISSUE TITLE
Interaction with Botania

### ISSUE THREAD

**Issue by PaulUParadox** [sinkillerj/ProjectE#1922]
ProjectE-1.12.2-PE1.4.1.jar

 forge-14.23.5.2838

There was no crash, So i believe such a log is not applicable.

I took a Pure Daisy from Botania r1.10-362.jar (note that botaniatweaks-1.8.6.jar and BotanicAdditions-1.12.2-3r.jar were also installed) and taught it to the Transmutation Table. I expected the Pure daisy to be properly registered, and to be able to pull copies out, provided I had the appropriate amount of EMC.

Instead the Pure Daisy registered as a "Botania Flower: Miscellaneous Flower" which had a tool tip informing me that it appears when a glitch occurs and should be reported. 

I was later informed that this error is most likely caused by a lack of NBT support in your mod. If this is true, then i request that you add support for this. In any case i hope this helps you develope and fix ProjectE.

**Comment by sinkillerj** [comment]
Closing as this because they do in fact use NBT, which makes this a duplicate issue. NBT is a tricky beast but its being investigated.
