### ISSUE TITLE
Error: java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by RedstoneFrog** [sinkillerj/ProjectE#1923]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.12.2-PE1.4.1
Exact Forge version:
1.12.2-forge1.12.2-14.23.5.2847
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 10/3/19 10:13 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at furgl.stupidThings.util.TooltipHelper.addTooltipRecipe(TooltipHelper.java:76)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_444_TooltipHelper_addTooltipRecipe_PostText.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:409)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:252)
	at net.minecraft.client.gui.GuiScreen.drawHoveringText(GuiScreen.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at moze_intel.projecte.gameObjs.gui.GUITransmutation.func_191948_b(GUITransmutation.java:197)
	at moze_intel.projecte.gameObjs.gui.GUITransmutation.func_73863_a(GUITransmutation.java:43)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at furgl.stupidThings.util.TooltipHelper.addTooltipRecipe(TooltipHelper.java:76)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_444_TooltipHelper_addTooltipRecipe_PostText.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:409)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:252)
	at net.minecraft.client.gui.GuiScreen.drawHoveringText(GuiScreen.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at moze_intel.projecte.gameObjs.gui.GUITransmutation.func_191948_b(GUITransmutation.java:197)
	at moze_intel.projecte.gameObjs.gui.GUITransmutation.func_73863_a(GUITransmutation.java:43)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: moze_intel.projecte.gameObjs.gui.GUITransmutation
	Mouse location: Scaled: (298, 81). Absolute: (597, 316)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RedstoneFrog'/836, l='MpServer', x=24.70, y=20.00, z=221.64]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-12,64,256), Chunk: (at 4,4,0 in -1,16; contains blocks -16,0,256 to -1,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 174505 game time, 180238 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 74 total; [EntityPlayerSP['RedstoneFrog'/836, l='MpServer', x=24.70, y=20.00, z=221.64], EntityZombie['Zombie'/770, l='MpServer', x=64.46, y=21.00, z=190.77], EntityKobold['Baby Kobold'/771, l='MpServer', x=66.13, y=26.52, z=218.50], EntityKobold['Verdant Kobold'/772, l='MpServer', x=67.27, y=26.02, z=217.27], EntityKobold['Kobold'/773, l='MpServer', x=69.73, y=26.01, z=217.27], EntityZombie['Zombie'/774, l='MpServer', x=64.50, y=35.00, z=216.50], EntityKobold['Kobold'/775, l='MpServer', x=72.35, y=55.00, z=277.75], EntitySilex['Silex'/776, l='MpServer', x=76.45, y=61.19, z=294.16], EntityCreeper['Creeper'/784, l='MpServer', x=90.50, y=44.00, z=156.50], EntityCreeper['Creeper'/785, l='MpServer', x=86.50, y=25.00, z=226.50], EntityCow['Kuh'/659, l='MpServer', x=-29.81, y=76.00, z=154.50], EntityKobold['Kobold'/787, l='MpServer', x=92.26, y=34.00, z=240.48], EntityChupacabra['Violet Chupacabra'/660, l='MpServer', x=-32.91, y=26.28, z=208.48], EntitySquid['Tintenfisch'/788, l='MpServer', x=86.65, y=57.37, z=281.64], EntityChupacabra['Chupacabra'/661, l='MpServer', x=-35.26, y=26.00, z=211.37], EntitySilex['Silex'/789, l='MpServer', x=81.23, y=61.98, z=299.10], EntityChicken['Huhn'/662, l='MpServer', x=-33.81, y=67.00, z=280.58], EntitySpider['Spinne'/663, l='MpServer', x=-39.50, y=39.00, z=292.50], EntityKobold['Kobold'/793, l='MpServer', x=96.69, y=34.00, z=240.97], EntityBat['Fledermaus'/794, l='MpServer', x=103.25, y=37.01, z=256.68], EntityBat['Fledermaus'/672, l='MpServer', x=-22.25, y=52.00, z=143.25], EntityItem['item.item.egg'/674, l='MpServer', x=-18.88, y=65.00, z=188.03], EntityChicken['Huhn'/675, l='MpServer', x=-22.50, y=69.00, z=200.42], EntityChupacabra['Chupacabra'/676, l='MpServer', x=-17.34, y=23.00, z=260.49], EntityChupacabra['Chupacabra'/677, l='MpServer', x=-16.38, y=32.00, z=257.42], EntityKobold['Ashen Kobold'/683, l='MpServer', x=-6.73, y=34.24, z=176.73], EntityBat['Fledermaus'/684, l='MpServer', x=-3.50, y=15.10, z=241.38], EntityChupacabra['Chupacabra'/685, l='MpServer', x=-13.50, y=32.14, z=259.38], EntityBat['Fledermaus'/686, l='MpServer', x=-5.91, y=14.00, z=263.25], EntityBat['Fledermaus'/687, l='MpServer', x=-18.67, y=14.47, z=273.16], EntityKobold['Kobold'/688, l='MpServer', x=-11.49, y=27.00, z=270.70], EntityChupacabra['Chupacabra'/689, l='MpServer', x=-11.80, y=37.00, z=263.52], EntityChupacabra['Chupacabra'/690, l='MpServer', x=-13.46, y=49.00, z=288.50], EntityBat['Fledermaus'/696, l='MpServer', x=9.91, y=31.13, z=144.43], EntityAfrit['Afrit'/697, l='MpServer', x=12.76, y=7.02, z=247.54], EntityChupacabra['Chupacabra'/703, l='MpServer', x=18.91, y=43.00, z=178.22], EntityChupacabra['Chupacabra'/704, l='MpServer', x=28.49, y=33.00, z=190.62], EntityVolcan['Volcan'/705, l='MpServer', x=30.61, y=8.42, z=247.39], EntityCephignis['Golden Cephignis'/706, l='MpServer', x=27.92, y=7.78, z=248.24], EntityCephignis['Scarlet Cephignis'/707, l='MpServer', x=21.07, y=8.99, z=245.80], EntitySheep['Schaf'/708, l='MpServer', x=31.25, y=64.00, z=296.57], EntitySheep['Schaf'/709, l='MpServer', x=23.23, y=64.00, z=299.52], EntityCephignis['Cephignis'/723, l='MpServer', x=48.11, y=4.12, z=187.97], EntityChupacabra['Violet Chupacabra'/724, l='MpServer', x=38.25, y=43.00, z=178.69], EntityCephignis['Cephignis'/725, l='MpServer', x=48.83, y=5.00, z=188.83], EntityArix['Arix'/726, l='MpServer', x=48.36, y=21.14, z=204.64], EntityArix['Arix'/727, l='MpServer', x=46.03, y=21.00, z=208.56], EntityArix['Arix'/728, l='MpServer', x=44.50, y=21.00, z=213.50], EntityChupacabra['Chupacabra'/729, l='MpServer', x=44.64, y=36.00, z=225.55], EntityAfrit['Afrit'/730, l='MpServer', x=34.50, y=6.00, z=241.50], EntityChupacabra['Chupacabra'/731, l='MpServer', x=41.32, y=16.00, z=254.38], EntitySilex['Silex'/732, l='MpServer', x=43.65, y=61.69, z=283.63], EntitySilex['Silex'/744, l='MpServer', x=61.64, y=62.01, z=143.97], EntityCreeper['Creeper'/745, l='MpServer', x=48.50, y=14.00, z=145.50], EntityBasicHunter['Vampir Jäger'/746, l='MpServer', x=51.52, y=64.00, z=175.40], EntityCephignis['Cephignis'/747, l='MpServer', x=52.20, y=5.00, z=187.80], EntitySpectre['Spectre'/1003, l='MpServer', x=60.48, y=17.00, z=237.48], EntityCephignis['Cephignis'/748, l='MpServer', x=59.19, y=5.23, z=192.60], EntityKobold['Kobold'/749, l='MpServer', x=50.49, y=28.00, z=191.31], EntityChupacabra['Chupacabra'/750, l='MpServer', x=57.95, y=39.00, z=181.95], EntityBasicHunter['Vampir Jäger'/751, l='MpServer', x=61.29, y=64.00, z=179.84], EntityBasicHunter['Vampir Jäger'/752, l='MpServer', x=55.86, y=65.00, z=190.53], EntityBasicHunter['Vampir Jäger'/753, l='MpServer', x=54.43, y=64.00, z=177.18], EntityAfrit['Afrit'/754, l='MpServer', x=52.62, y=-3.49, z=199.50], EntityCephignis['Cephignis'/755, l='MpServer', x=48.02, y=4.05, z=189.86], EntityArix['Arix'/756, l='MpServer', x=49.42, y=23.12, z=205.00], EntityWendigo['Keppel Wendigo'/757, l='MpServer', x=51.50, y=20.00, z=211.50], EntityArix['Arix'/758, l='MpServer', x=53.64, y=21.00, z=212.64], EntitySerpix['Baby Serpix'/759, l='MpServer', x=48.10, y=21.00, z=207.98], EntityZombie['Zombie'/760, l='MpServer', x=63.50, y=35.00, z=218.50], EntityChupacabra['Chupacabra'/761, l='MpServer', x=61.30, y=31.00, z=267.53], EntityChupacabra['Chupacabra'/762, l='MpServer', x=51.44, y=34.00, z=258.35], EntityChupacabra['Chupacabra'/763, l='MpServer', x=53.76, y=36.00, z=264.50], EntityJengu['Jengu'/767, l='MpServer', x=73.64, y=36.02, z=153.35]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1003446800 bytes (956 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 47 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                  | Source                                             | Signature                                |
	|:------ |:------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                 | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHIJA | forge               | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHIJA | opencomputers|core  | 1.7.4.153                | minecraft.jar                                      | None                                     |
	| LCHIJA | aether_legacy       | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                    | None                                     |
	| LCHIJA | arcademod           | 2.1.5                    | arcademod-2.1.5-1.12.2.jar                         | None                                     |
	| LCHIJA | battletowers        | 1.6.5                    | BattleTowers-1.12.2.jar                            | None                                     |
	| LCHIJA | bdlib               | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
	| LCHIJA | bibliocraft         | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCHIJA | bloodmoon           | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bookshelf           | 2.3.585                  | Bookshelf-1.12.2-2.3.585.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | codechickenlib      | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux        | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | brandonscore        | 2.4.17                   | BrandonsCore-1.12.2-2.4.17.208-universal.jar       | None                                     |
	| LCHIJA | buildcraftlib       | 7.99.24.3                | buildcraft-all-7.99.24.3.jar                       | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.24.3                | buildcraft-all-7.99.24.3.jar                       | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.24.3                | buildcraft-all-7.99.24.3.jar                       | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.24.3                | buildcraft-all-7.99.24.3.jar                       | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.24.3                | buildcraft-all-7.99.24.3.jar                       | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.24.3                | buildcraft-all-7.99.24.3.jar                       | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.24.3                | buildcraft-all-7.99.24.3.jar                       | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.24.3                | buildcraft-all-7.99.24.3.jar                       | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.24.3                | buildcraft-all-7.99.24.3.jar                       | None                                     |
	| LCHIJA | chiselsandbits      | 14.33                    | chiselsandbits-14.33.jar                           | None                                     |
	| LCHIJA | chococraft          | 0.9.8.0                  | chococraft_1.12.2-0.9.8.0.jar                      | None                                     |
	| LCHIJA | draconicevolution   | 2.3.24                   | Draconic-Evolution-1.12.2-2.3.24.349-universal.jar | None                                     |
	| LCHIJA | eplus               | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderstorage        | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ic2                 | 2.8.170-ex112            | industrialcraft-2-2.8.170-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | advgenerators       | 0.9.20.12                | generators-0.9.20.12-mc1.12.2.jar                  | None                                     |
	| LCHIJA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCHIJA | jei                 | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.5.5             | journeymap-1.12.2-5.5.5.jar                        | None                                     |
	| LCHIJA | lycanitesmobs       | 2.0.0.9 - MC 1.12.2      | lycanitesmobs-1.12.2-2.0.0.9.jar                   | None                                     |
	| LCHIJA | llibrary            | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs         | 1.5.4                    | mowziesmobs-1.5.4.jar                              | None                                     |
	| LCHIJA | mychunkloader       | 1.12.2-01                | MyChunkloader-1.12.2-01.jar                        | None                                     |
	| LCHIJA | opencomputers       | 1.7.4.153                | OpenComputers-MC1.12.2-1.7.4.153.jar               | None                                     |
	| LCHIJA | overlord            | 2.4.14                   | Overlord-1.12.2-2.4.14.jar                         | None                                     |
	| LCHIJA | projecte            | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LCHIJA | stupidthings        | 1.1.5                    | Stupid+Things-1.12.X-1.1.5.jar                     | None                                     |
	| LCHIJA | vampirism           | 1.5.4                    | Vampirism-1.12.2-1.5.4.jar                         | None                                     |
	| LCHIJA | teamlapen-lib       | 1.5.4                    | Vampirism-1.12.2-1.5.4.jar                         | None                                     |
	| LCHIJA | veinminer           | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a (1).jar          | None                                     |
	| LCHIJA | veinminermodsupport | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a (1).jar          | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.77' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	List of loaded APIs: 
		* AetherAPI (v1.0.0) from aether_legacy-1.12.2-v1.4.4.jar
		* buildcraftapi_blocks (1.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_boards (2.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_core (2.2) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_crops (1.1) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_enums (1.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_events (2.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_facades (1.1) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_filler (5.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_fuels (2.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_gates (4.1) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_items (1.1) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_library (2.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_lists (1.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_power (1.3) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_recipes (3.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_robotics (3.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_statements (1.1) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_tiles (1.2) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_tools (1.0) from buildcraft-all-7.99.24.3.jar
		* buildcraftapi_transport (5.0) from buildcraft-all-7.99.24.3.jar
		* ChiselsAndBitsAPI (14.25.0) from chiselsandbits-14.33.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.24.349-universal.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.5.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.5.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.5.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.5.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.5.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.268.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.4.153.jar
		* projecteapi (1.12.2-1.2.0) from ProjectE-1.12.2-PE1.4.1.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* VampirismAPI (1.4) from Vampirism-1.12.2-1.5.4.jar
		* veinminerApi (0.3) from VeinMiner-1.12-0.38.2.647+b31535a (1).jar
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.77, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
Steps to reproduce:

1. install buildcraft-all-7.99.24.3
2. take oil (cool) Bucket and put it in the Transmutation table
3. hover over the Bucket (the oil Bucket is shown as normal Bucket)
4. then the game crash because it can't show the name 

What I expected to happen:
that it show me the name and that i can extrakt it
What happened instead:
the game crash when i hover over it

**Comment by Monniasza** [comment]
Please pastę the log elsewhere and link it.

**Comment by pupnewfster** [comment]
`at furgl.stupidThings.util.TooltipHelper.addTooltipRecipe(TooltipHelper.java:76)` doesn't seem to be projecte
