### ISSUE TITLE
Dark and red matter shears cannot be used in the EnderIO splice'n'slice

### ISSUE THREAD

**Issue by Rupert16** [sinkillerj/ProjectE#1929]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12.2-PE1.4.1

Exact Forge version: 14.23.5.2847

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
The game doesn't crash

Steps to reproduce:
1. Try to add shear (dark matter or red matter) to splice'n'slice (from EnderIO)
2. Notice how it will not be inserted

What I expected to happen:
Should go into the shear box

What happened instead:
Stays in inventory

(All these shears need is a tag so the machine will recognize it as a shear item. Either by adding and extend (ItemShears) or by giving it the oreDict toolShears.)

**Comment by pupnewfster** [comment]
1.12 of projecte is sort of at a stand still at the moment (locally in 1.14 I do have shears extending the vanilla class), but this will not make it to 1.12. These are your best two options right now I think:
- Use something like CraftTweaker to add the oredict entry yourself to the shears.
- Ask the EnderIO devs to also check the "shears" toolClass/type of items. <https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkShears.java#L26>

**Comment by Rupert16** [comment]
Thanks, it took me a while as a noob in programming to understand how CraftTweaker works.
But I got it working and the dm and rm shears are now able to be used like vanilla Minecraft shears after spending like 2 hours learning how everything works. Totally worth it.

I'll include the script down below. All y'all gotta do (if you got the same issue) is install CraftTweakers for 1.12.2 and after booting it up close it down and add this .zip file to the newly created scripts folder (it is created by the mod upon loading the game).

[dm&rm shears are actual shears (oreDict fix).zip](https://github.com/sinkillerj/ProjectE/files/3802788/dm.rm.shears.are.actual.shears.oreDict.fix.zip)
