### ISSUE TITLE
lag with projecte emc generator

### ISSUE THREAD

**Issue by Ivar418** [sinkillerj/ProjectE#1934]
Exact ProjectE version: ProjectE-1.12.2-PE1.4.1

Exact Forge version: forge-1.12.2-14.23.5.2847

Hi. im using projecte to make an EMC farm using ic2classic and blaze rods. i have a gtx 1080 and an i5-9600k wich a pretty overkill for minecraft. but when i build a large emc farm my frames begin to drop tremendously. there is no problem with stuff lying on the ground. only with the emc farm up and running. i think the pipes need to be optimized. 

if you still need a log. please let me know. i did not upload since there is no crash

to be specific. i used energy condensor. filter importer. item importer. macerator. pressure tubes. red alloy wire.

here is a picture. in the top left u can see my usages. if i use shaders the lag becomes even worse ( https://imgur.com/a/ijlcZmq ) 
Steps to reproduce:

1. build a "lagre" blaze emc farm. and look at it

What I expected to happen: to not cause so much lag. 

What happened instead: a lot of lag was produced ( and low frames)

**Comment by pupnewfster** [comment]
Given you are having FPS lag (and not TPS lag), my guess is it has to do with the rendering of the items in the transparent pipes you are using and can't really be optimized by us at all as they are not part of ProjectE. There unfortunately isn't really a good way to be rendering a large amount of items in pipes at once, but I would recommend reporting the "issue" to whoever's pipes those are, or to use some mods pipes that don't render the items when transferring them.

**Comment by Ivar418** [comment]
> Given you are having FPS lag (and not TPS lag), my guess is it has to do with the rendering of the items in the transparent pipes you are using and can't really be optimized by us at all as they are not part of ProjectE. There unfortunately isn't really a good way to be rendering a large amount of items in pipes at once, but I would recommend reporting the "issue" to whoever's pipes those are, or to use some mods pipes that don't render the items when transferring them.

oh my bad. i thought the pipes where from projecte. but they re form project red 🥇 . thanks for your time.
