### ISSUE TITLE
Transmutation Table Rotation

### ISSUE THREAD

**Issue by teamaonn** [sinkillerj/ProjectE#1936]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 2.0.0 (1.14.4)

Okay, this is just a suggestion, instead of some issue. I was wondering if you could add rotation to the table so it sits flush against any side of a block. I showed this in the discord, and Pupnewfster suggested that I put it here.

**Comment by sinkillerj** [comment]
Following on from the conversation @pupnewfster had in the Discord this would be fine by me.
