### ISSUE TITLE
EMC resets to 0 after leaving chunk

### ISSUE THREAD

**Issue by SyndicateServers** [sinkillerj/ProjectE#1942]
My Admin messaged me saying that the transmutation tables keep resetting to 0, I had him test a few things like just letting it sit for a while and eventually I went to spawn and he went to the nether only to go back and see that he lost his EMC again. I tried recreating the issue but I couldn't get it to work. These are logs of my admin recreating the issue.
https://pastebin.com/RQBV3K6H
Since I couldn't recreate the issue, im wondering if its clientside for some people which would mean bigger problems for me.

**Comment by pupnewfster** [comment]
Based on the log you linked it looks like sponge is throwing some sort of error so my guess would be see if it happens without sponge.

**Comment by sinkillerj** [comment]
We only accept issue reports from official Forge builds, unless this can be reproduced on a stock server this issue will remain closed.
