### ISSUE TITLE
Transmutation table knowledge, EMC, and alchemical bag contents wiped when leaving the end (1.14)

### ISSUE THREAD

**Issue by Alpaca53382** [sinkillerj/ProjectE#1943]
Exact ProjectE version: PE1.0.0B

Exact Forge version: 28.1.103

Steps to reproduce:
1. Learn things in the transmutation table, put items in to turn into EMC, or put items in an alchemical bag
2. Leave the end through the portal

What I expected to happen: Keep the learned items, EMC, and bag contents

What happened instead: All three are wiped

Additional note: This is the same thing that happened in #1255 which was fixed in the 1.12.x branch, but it's happening again in 1.14.x.

**Comment by pupnewfster** [comment]
I will try to look at this sometime this weekend, was this in single player it happened or was it on a server? (If a server can you reproduce it in single player)

**Comment by Alpaca53382** [comment]
It originally happened on a server, but I tested just now and it happens on single player too.

**Comment by pupnewfster** [comment]
Closing as the latest version https://www.curseforge.com/minecraft/mc-mods/projecte/files/2855942 now requires the forge version that has a fix
