### ISSUE TITLE
Dark Matter Furnace does not drop items on break (1.14.4)

### ISSUE THREAD

**Issue by jhollowe** [sinkillerj/ProjectE#1945]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  1.14.4-PE1.0.0B

Exact Forge version:  28.1.107

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): none

Steps to reproduce:

1. place dark matter furnace
2. place items to smelt and fule int the furnace
3. break the furnace block

What I expected to happen:
the furnace block item drops along with all the items that where in the inventory slots of the furnace

What happened instead:
only drops furnace item

**Comment by pupnewfster** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/projecte/files/2855942
