### ISSUE TITLE
[1.14.4-PE1.0.0B] Philosopher stone can't craft and looses items in crafting grid

### ISSUE THREAD

**Issue by Heimdell** [sinkillerj/ProjectE#1947]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.14.4-PE1.0.0B

Exact Forge version: forge/1.14.4-28.1.109

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): none

Steps to reproduce:

1. Take Philosopher Stone in hand
2. Attempt crafting

What I expected to happen:

1. Crafting is successful

What happened instead:

1. Cannot craft at all
2. Any items remain in crafting grid are lost upon closing the crafting interface, including the P-Stone itself.

**Comment by pupnewfster** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/projecte/files/2855942
