### ISSUE TITLE
1.14.4 PE1.0.1b Emc transmutation table/tablet won't open GUI

### ISSUE THREAD

**Issue by skytheraiders** [sinkillerj/ProjectE#1955]
Whenever I try to use the transmutation table or tablet, it won't open the GUI.

**Comment by pupnewfster** [comment]
Please don't delete the template....

What version of forge are you using, is this on a server or client, and is there any errors printed the the log/can you please upload your log to gist or pastebin.

**Comment by skytheraiders** [comment]
Just updated the forge version from 113 to 114 and everything works now. Thank you for the help :)
