### ISSUE TITLE
1.14.4 Mercurial Eyes share data

### ISSUE THREAD

**Issue by Baythan** [sinkillerj/ProjectE#1956]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.14.4-PE1.0.1B

Exact Forge version: forge-1.14.4-28.1.114

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): no crash

Steps to reproduce:

1. Have two mercurial eyes in inventory
2. Place a block and/or charged Klein star inside one mercurial eye
3. Open second mercurial eye and it has the same block and klein star in it

What I expected to happen: two separate mercurial eye configurations

What happened instead: both mercurial eyes are identical and changing one changes the other

**Comment by pupnewfster** [comment]
This is fixed in 1.15.2, I doubt it will ever make it back to 1.14.4 unless someone submits a PR backporting the various fixes I have made to the 1.15 branch as currently no one on the team has time to maintain *multiple* versions of MC.
