### ISSUE TITLE
Port to another game

### ISSUE THREAD

**Issue by tehrelt** [sinkillerj/ProjectE#1959]
Hello! 
I wanna port project E to another game

Can I do it?

**Comment by sinkillerj** [comment]
I don't personally have an issue with it, though as far as the art assets are concerned you may wanna reach out to x3n0.

What game are you porting to?

**Comment by tehrelt** [comment]
Forager

**Comment by sinkillerj** [comment]
Closing, but feel free to reach out if you have any further questions.
