### ISSUE TITLE
[bug] Lost /projecte setemc 

### ISSUE THREAD

**Issue by DaveRainbowin** [sinkillerj/ProjectE#1960]
Exact ProjectE version: 1.14 1.0.0 

Exact Forge version: 28.1.113

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): Not crash

Steps to reproduce:

1. Open MC
2. Start setting EMC values with /projecte setemc (bc mods couldn't calculate recipe emc)
3. Game crash
4. Lose the setemc command (along with everything but showbag)
5. Report bug

What I expected to happen: Not lose setemc because I have cheats enabled in this world and didn't disable them

What happened instead: Lost setemc and 2 of the emc values i set
Note: I didn't update to 1.0.1 of projecte because when I did, all of the items lost their EMC values. (or at least they no longer showed up on hover)

**Comment by pupnewfster** [comment]
Could you give us the latest log file (ideally via gist or pastebin), for when you are on 1.0.1? My guess is some mod is breaking the EMC calculations, and looking at the log we probably will be able to tell you which one. I wouldn't be surprised if it is also breaking things for 1.0.0 but just breaking a bit differently. Also could you provide us with the crash report for when you said the game crashed?

**Comment by DaveRainbowin** [comment]
I would like to but updating to 1.0.1 resets all of my items in the transmutation table...
I'll still do it anyway, but later tommorow

**Comment by DaveRainbowin** [comment]
Looking at the crash report myself, I think it crashed because I ran out of RAM. Only 8GB apparently isn't enough for everything...

**Comment by DaveRainbowin** [comment]
* oops closed it instead of just commenting

**Comment by DaveRainbowin** [comment]
Also wdym log file? I don't think it crashed on 1.0.1...

**Comment by pupnewfster** [comment]
`latest.log` in the logs folder

**Comment by DaveRainbowin** [comment]
oh

**Comment by DaveRainbowin** [comment]
Ok then, I guess 1.0.1 decided to work...
Here's the latest.log: https://gist.github.com/DaveRainbowin/904a0a9dcc02288fc8144903a75217a8

**Comment by DaveRainbowin** [comment]
But now that i'm on 1.0.1, the original problem got worse, unless you changed the commands.
Now when I type /projecte _, nothing appears, not even showbag.
Also just a note about something that might be interfering: I have 110 mods according to forge.

**Comment by pupnewfster** [comment]
1.0.1 fixes the fact that showbags did not require op to use, so if you have some permission managing mod it may be causing issues, I know someone on discord couldn't use any commands due to a bug in a mod called "server utilities".

Also are you sure that is the full latest.log given it seems to cutoff in the middle of a stack trace.

**Comment by DaveRainbowin** [comment]
According to the popup on github, you should just have to click on some button to view the raw version

**Comment by DaveRainbowin** [comment]
And I was in a singleplayer server with cheats on

**Comment by pupnewfster** [comment]
Yes, the mod server utilities breaks op commands from working in singleplayer even with cheats. That is why I asked if you have any permission modifying mods installed.

Also I didn't realize gist truncates the logs, but from what I can tell in the log it seems EMC values generated fine?

**Comment by DaveRainbowin** [comment]
Well, I'll just close this issue and edit custom_emc.json instead, since I can work with JSON.

**Comment by DaveRainbowin** [comment]
Sorry if I kind of made you lose time on other things.

**Comment by DaveRainbowin** [comment]
And I also do believe I do not have the server util mod.

**Comment by DaveRainbowin** [comment]
Apparently, I can no longer /reload...
I mean, I could just exit the world and re-enter...
but that takes a lot longer than a /reload, and frankly, I don't want to do that every time I reload.
Not only did I lose /reload, but Diamond's EMC was set to like 36 or something, and there's no recipes from any mods that would change it. It's not custom_emc.json, and I can't just reset it.

**Comment by pupnewfster** [comment]
If you don't have access to reload that just further implies you have some mod or other screwing with your permissions/removed your "cheats"/"op" access in single player. Which further shows the commands are not and issue due to ProjectE. No idea about the EMC value if it isn't something you accidentally set/some other mod is doing recipe wise.

**Comment by DaveRainbowin** [comment]
Ok i'll check it out
