### ISSUE TITLE
[1.12.2] Fluid Buckets From Other Mods Cause Crashes When Transmuting

### ISSUE THREAD

**Issue by Brittank88** [sinkillerj/ProjectE#1962]
### **Tickets that do not conform to this template will be closed without comment**

**Exact ProjectE version (do not say "latest", "latest on Curse", or similar):**
`ProjectE-1.12.2-PE1.4.1`

**Exact Forge version:**
`forge-1.12.2-14.23.5.2847`

**Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):**
[Snippet of latest.log](https://hatebin.com/hchqcrwuig)

**Steps to reproduce:**

1. Learn a fluid bucket from another mod in the Transmutation Table / Tablet (E.g. Sewage Bucket from Industrial Foregoing, or Dark Water Bucket from Midnight - these are what have caused crashes so far for me during my playthrough).
2. Attempt to even hover over the item in the Transmutation Table / Tablet, and experience an immediate crash.

**What I expected to happen:**
Should be able to hover over these items without issue, and take them out of the Transmutation Table / Tablet without issue too.

**What happened instead:**
Instant shutdown of the internal server and crash to main menu (VanillaFix being the reason it only crashes to the main menu).

**Comment by pupnewfster** [comment]
Closing as 1.14+ has proper support for NBT, and the issue has to do with some mods not gracefully handling rendering of their items if they don't have any NBT data, which ProjectE could not handle in 1.12.
