### ISSUE TITLE
1.15.2 Initializing game render water projectile

### ISSUE THREAD

**Issue by frostfire50** [sinkillerj/ProjectE#1968]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.15.2-PE1.0.2B.JAR
Exact Forge version:
Forge-31.1.11
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://hastebin.com/opecikoqij.rb(couldn't put it as link because it messed up the template)
Steps to reproduce:

1.load Minecraft

What I expected to happen:I didn't expect a crash

What happened instead:I crashed

**Comment by pupnewfster** [comment]
As I mentioned here: https://github.com/sinkillerj/ProjectE/issues/1967#issuecomment-586721534 This is not a ProjectE bug. It is a bug with optifine not being compatible with forge yet and breaking a forge patch that allows for modded entities to exist at all.
