### ISSUE TITLE
DM & RM furnaces not putting items into adjacent inventories

### ISSUE THREAD

**Issue by shugnk** [sinkillerj/ProjectE#1970]
Exact ProjectE version: projecte-1-12-2-pe1-4-1-jar

Exact Forge version: 1.12.2

Dark Matter and Red Matter furnaces are not placing items into alchemical chest on any side, even the bottom side. They do take items from the top side out of an alchemical chest. In the old versions of EE this used to work flawlessly. They also are not working with Buildcraft transport pipes anymore as well. The hopper on the bottom does work though, albeit remarkably slow.

**Comment by pupnewfster** [comment]
Firstly that is not the exact forge version as there are *many* versions of forge for 1.12.2. But either way, ProjectE in 1.12.2 had a TODO to finish implementing the auto eject feature from the furnaces, which I addressed and implemented in the port to 1.14. While 1.12 won't get updated as we do not have the time to be supporting multiple versions of MC at once, the auto eject feature should be working properly in both the 1.14 and 1.15 branches.
