### ISSUE TITLE
Custom EMC can't go above 1Mil

### ISSUE THREAD

**Issue by congueror** [sinkillerj/ProjectE#1973]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): PE1.0.2B

Exact Forge version: 31.1.18 (1.15.2)

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): Didn't Crash

Steps to reproduce:

1. Navigate to path: (MC Directory)> config> ProjectE> custom_emc.json
2. Add a custom entry
3. Set the emc value of the entry above 1,000,000 (without the comma and no spaces)
4. Launch Minecraft and check the emc value of the item.

What I expected to happen: Expect to have an emc value above 1Mil of an item which does not currently have an emc value

What happened instead: I have many entries in the custom_emc.json file, when I added the entry with above 1Mil emc all other custom entries stopped having emc.

**Comment by congueror** [comment]
Note: I've checked the file of another 1.12.2 modpack in that version it looked like there were 1Mil+ entries. Also the custom emc works fine until I add the 1mil emc so it's not a problem on my end.

**Comment by SDUBZ** [comment]
im using the 1.15 version and i got emc values way above 1mill

**Comment by congueror** [comment]
> im using the 1.15 version and i got emc values way above 1mill

Can you send me your config file?

**Comment by pupnewfster** [comment]
Could you show the config you are setting to above 1 million emc that is not working? That way I can:
a. see if I can reproduce it
b. See if maybe the format is incorrect as I think the format might have changed *slightly* since 1.12

**Comment by congueror** [comment]
This bug is fixed in the newest forge update(31.1.18), thanks for everyone who tried to help. Here is the custom_emc.json file if you want to check for any mistakes you might have done https://pastebin.com/9ETb9vXu
