### ISSUE TITLE
Mekanism universal cables, which all have the same ID but different NBT Tags I guess, are all converted into the basic version

### ISSUE THREAD

**Issue by TheAnachronism** [sinkillerj/ProjectE#1974]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.12.2-PE1.4.1
Exact Forge version:
14.23.5.28.38

What I expected to happen:
Crafting a higher tier universal cable from mekanism and saving it in the transmutation tablet.

What happened instead:
Saved as a basic universal cable.

Also projectE gives all cables the same EMC value.

**Comment by pupnewfster** [comment]
This has to do with NBT not being able to be parsed by the 1.12 version of ProjectE. It now is able to handle NBT (and has an API for modders to define how NBT is parsed), in the 1.14+ versions.
