### ISSUE TITLE
How can I get the Watch of Flowing Time to affect crops?

### ISSUE THREAD

**Issue by Kasera3983** [sinkillerj/ProjectE#1975]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  ProjectE-1.7.10-PE1.10.1

Exact Forge version: forge-1.7.10-10.13.4.1448-1.7.10

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): didn't crash

Steps to reproduce:
1.Plant either Magical Crops or Vanilla Crops
2. Place down Dark Matter Pedestal
3. Place Watch of Flowing Time in Pedestal
4. Right Click to activate Dark Matter Pedestal

What I expected to happen: Watch of Flowing Time makes the crops grow faster

What happened instead: Watch of Flowing Time does not affect the growth speed.

**Comment by sinkillerj** [comment]
Please check for any config or keybind issues, and for errors or mod conflicts within your log. Beyond this support for 1.7 was dropped a long time ago.
