### ISSUE TITLE
[forge-1.15.2-31.1.16] ProjectE-1.15.2-PE1.0.2B no emc values on server side

### ISSUE THREAD

**Issue by SDUBZ** [sinkillerj/ProjectE#1976]
this version was working perfectly single player 
but server side no values get set 🤔

**Comment by pupnewfster** [comment]
Could you provide your server's latest.log. Most likely some mod is breaking the mapper by using some client side only method on a server.

**Comment by SDUBZ** [comment]
umm i got this when testing with singleplayer just a few seconds ago
Exception during Mapping Collection from Mapper moze_intel.projecte.emc.mappers.recipe.CraftingMapper. PLEASE REPORT THIS! EMC VALUES MIGHT BE INCONSISTENT!

[latest.log](https://github.com/sinkillerj/ProjectE/files/4285204/latest.log)

**Comment by pupnewfster** [comment]
Something is very wrong with your instance, given it is pointing at Mekanism's combiner recipe as that it would output air. Given I am having to release an update tomorrow anyways to mekanism to fix a crash on servers... I will add an extra check to validate the output is not empty, as looking over the code briefly it seems that it allows setting air as the output of a recipe. Though that does imply that either you or the pack dev who made the pack you are playing added faulty jsons to the data pack. Though after I add some safety checking in Mekanism it will be a bit more clear what recipes are faulty.

**Comment by SDUBZ** [comment]
i made the pack but i havent added any datapacks at all so thats why im trying to work out whats going wrong, maybe another mod is interfering somehow would be my only guess

**Comment by SDUBZ** [comment]
[debug.log](https://github.com/sinkillerj/ProjectE/files/4285508/debug.log)
[latest.log](https://github.com/sinkillerj/ProjectE/files/4285509/latest.log)
well heres the latest logs from the update im working on server side
but emc is still showing singleplayer but not server side for some reason 🤔

**Comment by pupnewfster** [comment]
Interesting, not sure then. I will add safety checks for the first log you posted given that shouldn't be happening, but the second log does not actually show any errors calculating EMC values which is odd.

**Comment by pupnewfster** [comment]
The error from the first log should no longer be possible with Mekanism 9.9.14. No idea why things are not working on the server, unless something is making recipes not load properly at all on the server. Are you able to craft items properly on the server?

**Comment by SDUBZ** [comment]
yes i can still craft things

**Comment by SDUBZ** [comment]
ok new thing aswell it wont let me setemc too server side
also i did some tweaking and still not emc values server side

**Comment by pupnewfster** [comment]
Are you sure you are loading projecte on the server side? Also could you please grab the latest server side log again.

**Comment by SDUBZ** [comment]
[debug.log](https://github.com/sinkillerj/ProjectE/files/4301647/debug.log)
[latest.log](https://github.com/sinkillerj/ProjectE/files/4301649/latest.log)

**Comment by SDUBZ** [comment]
ok i got it working i found out the 2 mods that were causing datapacks to not load correctly server side one has already been fixed and the other i reported :)
[latest.log](https://github.com/sinkillerj/ProjectE/files/4303677/latest.log)

if you have anyone that has same issue 
tell them to check if they have the flux mod or interior mod

**Comment by pupnewfster** [comment]
Thanks for letting us know you were able to track it down
