### ISSUE TITLE
"Stack's Tag Compound is null" in console

### ISSUE THREAD

**Issue by m-vlad** [sinkillerj/ProjectE#1977]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version:  1.0.2B

Exact Forge version: 1.15.2 - 31.1.18

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://github.com/CJ-MC-Mods/Overloaded/issues/96
Steps to reproduce:

1. Use Overloaded
2. Add the Overloaded Multi armour set to the transmutation table
3. Check console log

What I expected to happen:
To display the Multi Tool armour correctly without erroring in the console.

What happened instead:
https://github.com/CJ-MC-Mods/Overloaded/issues/96

**Comment by pupnewfster** [comment]
Fixed in 1.0.3B
