### ISSUE TITLE
[1.15.2] Feature request- ability to disable version checking.

### ISSUE THREAD

**Issue by ProsperCraft** [sinkillerj/ProjectE#1978]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.15.2-PE1.0.3B

Exact Forge version:
forge-1.15.2-31.1.19

In my modpacks I always disable version checking as it speeds up the load and decreases errors down the line when the modpack is super old and the mod website the update is checking is gone.

# Enable forge global version checking
versionCheck = false

I have fml version checking off the fml.toml  and I don't see any version checking options in your configs.

**Comment by sinkillerj** [comment]
We already switched to the Forge version checking system several versions ago, have you received an update notifications after disabling it?

**Comment by ProsperCraft** [comment]
yes - [08:53:33] [ProjectE Update Checker Notifier/INFO]: Update check failed.

**Comment by sinkillerj** [comment]
That sounds like a derp on our side where it thinks its failing to connect when It's actually not even trying to begin with. I'll take a look at whats going on before the next version.
