### ISSUE TITLE
1.12.2 PE 1.4.1 Crash on boot

### ISSUE THREAD

**Issue by blace2121** [sinkillerj/ProjectE#1979]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.4.1

Exact Forge version:1.12.2-14.23.5.2821

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://paste.ee/p/9s1MV

Steps to reproduce:

1.Install ProjectE 
2.boot client
3.cry

What I expected to happen: game boot, Avaritia becomes sane

What happened instead:during mod load 2, launcher crashes and disappears

**Comment by pupnewfster** [comment]
`java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.` You exceeded the id limit. Your options are as follows:
- Update to 1.14+ where there is no more id limit
- Remove some mods
- Install a mod like NotEnoughIDs or JustEnoughIDs (I would read both of their mod pages and decide which of those you want to use, as they have difference in how they work which I don't remember, and I believe once you install one, then your world will continue to require it.

**Comment by blace2121** [comment]
Thank you so much! I read that a dozen times and couldn't decipher it! Will fix asap
