### ISSUE TITLE
NBT tags removed in Energy Condenser

### ISSUE THREAD

**Issue by Owy32** [sinkillerj/ProjectE#1981]
Exact ProjectE version: ProjectE-1.12.2-PE1.4.1

Exact Forge version: 8.0.99.99

Link to crash log: None

Steps to reproduce:

1.Put items (from other mods) that have NBT data into Energy Condenser (MK1 or MK2) and both transmutation tablets (handheld and placeable)  then input emc to make copies of the item. Doing this removes NBT tags.

What I expected to happen: To get insulated copper cables/ To get usable uninsulated copper cables

What happened instead: generating uninsulated copper cables instead of insulated. The uninsulated copper cable that is generated is unusable (cant be used in recipes) and cant be stacked with items that have the NBT tags.

2 links to showcase this in action:
https://imgur.com/uPKsFjk  (insulated becomes uninsulated + NBT tags removed)
https://imgur.com/XTwcsbI  (uninsulated lose NBT tags )

**Comment by pupnewfster** [comment]
If you want proper support for NBT in items update to 1.14+ as it was only added to ProjectE when I was working on finishing up the 1.14 port, as we have a system in place for handling them there. Additionally mods shouldn't be using NBT hacks for item variants in 1.13+ so it should be less of a problem.

And before you ask, no we are not going to backport this to 1.12, as we do not have the free time to do so.
