### ISSUE TITLE
setEMC doesnt work on server.

### ISSUE THREAD

**Issue by LittleMoon215** [sinkillerj/ProjectE#1983]
Exact ProjectE version: 1.12.2-PE1.4.1

Exact Forge version:14.23.5.2847
Forge mod loader: 8.0.99.99

Playing Project Ozone 3

Im using setEMC amount with item in hand. Then using reloadEMC updated config files. Config update information about my changes but there is no effect ingame. Restart server also not helping

**Comment by sinkillerj** [comment]
Your pack is likely using a pregenerated emc file, disable this in the ProjectE config.
