### ISSUE TITLE
Watch of Flowing Time doesn't place on Pedestal

### ISSUE THREAD

**Issue by R3alRezentiX** [sinkillerj/ProjectE#1984]
Exact ProjectE version: 1.7.10-PE1.10.1

Exact Forge version: Minecraft Forge 10.13.4.1614

Steps to reproduce:

Try to place (with right-click) Watch of Flowing Time on a Pedestal

What I expected to happen: I thought that the Watch will place on a pedestal and boost machines (Energy Infuser, Generators, etc.)

What happened instead: Watch hasn't placed
![2020-03-27_10 17 26](https://user-images.githubusercontent.com/62739850/77731653-57a04700-7014-11ea-9658-39d55632aab6.png)
![2020-03-27_10 18 11](https://user-images.githubusercontent.com/62739850/77731656-5a9b3780-7014-11ea-93fe-df64f2105e17.png)

**Comment by sinkillerj** [comment]
You must open the GUI and place the item into the slot. Regardless 1.7 is unsupported.
