### ISSUE TITLE
[Question] Transmutation table for more players

### ISSUE THREAD

**Issue by solumath** [sinkillerj/ProjectE#1987]
Hello,
I was just curious and after 2 hours of not finding anything here I'm. Was there an update that would enable players share EMC in transmutation table? I saw it was mention here [#283](https://github.com/sinkillerj/ProjectE/issues/283).  I know that we can share klein stars and transfer emc still i rather learn the table once then having to let friends do it also. Not sure if it's even possible with few lines of code. 
If theres some way please let me know.
Thanks in advance.

**Comment by sinkillerj** [comment]
The feature is a consideration, but would be experimental and unsupported.

**Comment by Blazier1** [comment]
I know this is like 2 years late but why dont you do it like the GP of the extra utilities mod? in that mod you have to type /XU_powersharing in order to share GP with a friend, could this not work under the same type of system?
