### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by eloe79** [sinkillerj/ProjectE#1989]
Minecraft Version: 1.15.2
Operating System: Windows 10
Java Version: 1.8.0_241, Oracle Corporation
Forge: net.minecraftforge:31.1.30
ProjectE-1.15.2-PE1.0.3B.jar

https://pastebin.pl/view/0063eb4b

Steps to reproduce:

1. trying to reload after seting custom EMC - /projecte seteemc /reload

What I expected to happen: reloading emc custom jason

What happened instead:crash, back desktop

ps. also mod is missing EMC for most of basic vanilla items
also reported to CrafTweker - https://github.com/CraftTweaker/CraftTweaker/issues/953

**Comment by pupnewfster** [comment]
I don't think this has anything to do with us, it is crashing with `silentchaos512` and not even showing us in the stack trace.
