### ISSUE TITLE
[Feature Request] Better Transmutation GUI

### ISSUE THREAD

**Issue by drewc5131** [sinkillerj/ProjectE#1991]
Exact ProjectE version:
1.12.2-PE1.41
Exact Forge version:
14.23.5.2847

The current transmutation tablet GUI, while cool, proves to be quite annoying and inefficient. It would be great to have atleast a togglable option to switch it to a more intuitive scroll list with multiple ways to sort (EMC Value, Name, Learned, Last Used, etc).

The current GUI is cool and all, but when you have a ton of items, the main portion of the GUI ends up just becoming pretty useless since you would always just search for items, especially if you are constantly using them, in which a "Last Used" sort option would be amazing.

Obviously if this were to be implemented, I think it would be best to include the option for the original GUI as options for users are always something I personally like to include when thinking about software, and since many users will probably prefer the original, the option to switch between them would make the best sense.

**Comment by sinkillerj** [comment]
We tend to not deviate too far from the original vision, what you are looking for is an addon.
