### ISSUE TITLE
Harvest Goddess Band bug.

### ISSUE THREAD

**Issue by KXIIIS** [sinkillerj/ProjectE#1993]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version: 1.15.2-PE1.0.3B

Exact Forge version: 1.15.2 - 31.1.41

Link to crash log: It's not a bug that involves a crash.

Steps to reproduce: N/A

What I expected to happen: The band to harvest crops from the pedestal.

What happened instead: It breaks the earth in front and around it instead.
![Snip20200408_1](https://user-images.githubusercontent.com/62857357/78855324-90b3c080-79f1-11ea-8088-45df065e089a.png)

**Comment by pupnewfster** [comment]
I believe this likely is similar to #1986 though I have not had a chance to look into it yet.

**Comment by KXIIIS** [comment]
Ah, I think it's similar in that the ring is breaking things that aren't crops.

**Comment by pupnewfster** [comment]
Ah interesting (not sure why the torches are breaking yet), but at least this issue seems to be that it isn't breaking the dirt around it per say but is breaking the dirt under the crop it is trying to break instead of breaking the crop itself.
