### ISSUE TITLE
clay balls should give less emc

### ISSUE THREAD

**Issue by IchigoGames** [sinkillerj/ProjectE#1995]
Minecraft 1.15.2
forge 31.1.43
ProjectE-1.15.2-PE1.0.3B

issue clay blocks have a emc of 1 thats fine but clay balls have a emc of 16 not ok you can get clay blocks from emc and turn them into balls giving you more emc then you used to make it then can be automated emc farm.

**Comment by pupnewfster** [comment]
Clay blocks have an emc value of 64. Something in your pack is probably adding a recipe that makes it possible to get clay blocks for 1 emc.
