### ISSUE TITLE
1.14.4 Ferroustry Incombatible

### ISSUE THREAD

**Issue by XiNaru** [sinkillerj/ProjectE#1996]
Hey,

I found out that projectE is not compatible with Ferroustry. I noticed this through a diamond that normally has over 8,000 EMC. But if I install Ferroustry on it, the diamond will only have 32 EMC. I do not know if something has to be programmed in the mod here, or in the mod ferroustry. I just wanted to report it.

**Comment by pupnewfster** [comment]
This is a side effect of a bug that the 1.14 version of projecte has that recipes could overwrite emc values of things rather than just displaying a warning in the console for specific things like vanilla materials. This has been fixed in the 1.15 version of projecte.

**Comment by XiNaru** [comment]
Unfortunately, the 1.15 variant does not bring me anything, since I started 1.14 for the Create mod :) And so far there is unfortunately only for 1.14 :) A bug fix for 1.14 would also be great :)

**Comment by pupnewfster** [comment]
Unfortunately I think it is unlikely to happen, as I am very busy working on school stuff, and for the most part the free time I spend modding I do so working on Mekanism. So I barely have time to spend working on the 1.15 version of ProjectE, let alone on trying to backport various things to 1.14.

**Comment by XiNaru** [comment]
that is really a shame :( but good, realklife and so of course has priority. maybe someday there will be an opportunity.

Nonetheless, the mod is pretty well made and I like to use it.

Have a nice evening otherwise.
