### ISSUE TITLE
Gem Armor/Gem Helmet Offensive abilities not working

### ISSUE THREAD

**Issue by shawnoverlord** [sinkillerj/ProjectE#1997]
Exact ProjectE version: ProjectE-1.15.2-PE1.0.3B

Exact Forge version: forge-1.15.2-31.1.41

I have tried single player, multiplayer, and alternate keybinds. The armor is in fact activated. Pressing EXTRA FUNCTION and FIRE PROJECTILE bind do not work for the offensive abilities but work for all other items, even when holding nothing in hand. I have seen threads before mention this bug and seemingly having been fixed since then but even with no other mods installed they do not work. I guess the bug came back? If you can't recreate this bug, I don't know what the hell is wrong.

**Comment by jmleejobs** [comment]
Exact ProjectE version: ProjectE-1.15.2-PE1.0.3B

Exact Forge version: forge-1.15.2-31.1.41

In addition to the Gem Armor offensive abilities not working, there are some other issues regarding the Gem Armor. The ability to toggle the Abyss Helmet's Night Vision does not work. Neither does the Hurricane Boots' Step Assist toggle. 

Lastly, none of the Gem Armor pieces can be enchanted.

**Comment by shawnoverlord** [comment]
> Exact ProjectE version: ProjectE-1.15.2-PE1.0.3B
> 
> Exact Forge version: forge-1.15.2-31.1.41
> 
> In addition to the Gem Armor offensive abilities not working, there are some other issues regarding the Gem Armor. The ability to toggle the Abyss Helmet's Night Vision does not work. Neither does the Hurricane Boots' Step Assist toggle.
> 
> Lastly, none of the Gem Armor pieces can be enchanted.

I actually have a workaround for the gem armor abilities for those last two you mentioned: Rebind them to keys that aren't used and they work. The same workaround doesnt work for the other abilities unfortunately

**Comment by pupnewfster** [comment]
Unable to reproduce. To toggle offensive abilities on, you have to have the config option for offensive abilities on, and either have your main hand empty or have the unsafe key binds config option set to true. Using the "charge" key toggles offensive abilities to being enabled which must be done before being able to use the extra function/fire projectile keybinds.

In regards to not being able to be enchanted, it is intended that none of projecte's items can be enchanted.
