### ISSUE TITLE
setEMC

### ISSUE THREAD

**Issue by Spontini** [sinkillerj/ProjectE#1998]
When ever i do `/projecte setEMC <value>` then `/projecte reloadEMC` while holding a item i see in chat that the command is working, it even changes my config files however the EMC values still stays exactly the  same, how can i fix that, am i doing something wrong? (I've started to restart my game entirely and it's the same result.)

Minecraft Version: 1.12.2
Modpack: Project Ozone 3
Mod Version: ProjectE-1.12.2-PE1.4.1

Proof: https://streamable.com/lvw3uo

**Comment by MaPePeR** [comment]
That modpack probably uses a "pregenerated emc file". You need to disable that config or delete/change that file in order for your changes to take effect over that file.
