### ISSUE TITLE
EMC not auto calculating

### ISSUE THREAD

**Issue by TheParsley** [sinkillerj/ProjectE#2000]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "the latest on Curse", or similar): ProjectE-1.7.10-PE1.9.3h.jar

Exact Forge version: Please do not auto deny. I have no idea how to check, I am on Tekkit legends (1.7.10) and I kind of just put ProjectE in it

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):  No crash

Steps to reproduce: None

What I expected to happen: Calculate EMC

What happened instead: It's not calculating EMC

**Comment by sinkillerj** [comment]
1.7 is a very reason for auto deny, It's been unsupported for a very very long time.
