### ISSUE TITLE
My ProjectE Items dont have EMC because of changing the the recipes.

### ISSUE THREAD

**Issue by Kanubbel** [sinkillerj/ProjectE#2003]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version: ProjectE-1.12.2-PE1.4.1

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): There is no crash log for this issue.

Steps to reproduce:

1. Create aa new Profile in the Twitch launcher. (Version 1.12.2 with forge-14.23.5.2854)
2. Copy the "Mods" and "Scripts" folder in /Minecraft/Instances
( https://drive.google.com/file/d/1ZAot4cMetyLLmHQZ-uyWYsbObvvyJtbq/view?usp=sharing )
3. Start and create a new world and look up the EMC in JEI.

What I expected to happen:
The ProjectE items itself should have EMC values.

What happened instead:
The ProjectE items itself dont have EMC values.

What the problem is:
The script i use is the problem. But it only should change the crafting recipes.
So i am completly new to this modding thing. Is there a way to add the EMC back to the game? I wanted to make the mod items harder to archive.

**Comment by OhWowAPug** [comment]
/projecte setEMC *value* then type /projecte reloadEMC.
