### ISSUE TITLE
Unable to Change Modes for Red Morningstar

### ISSUE THREAD

**Issue by Gushousekai195** [sinkillerj/ProjectE#2004]
ProjectE-1.15.2-PE1.0.3B

forge-31.1.44

Game does not crash.  No crash log.

Steps to reproduce:

1. Press 'c' key.

I expected the mode to change from "Standard" to something else.

But, nothing happened.

**Comment by Gushousekai195** [comment]
Thank you @pupnewfster  Now how do I download and update the mod?  The latest version on CurseForge is still from March.

**Comment by pupnewfster** [comment]
If you really want the fix you are going to have to compile the mod yourself. There are still a few other things I need to fix before I tell sin that it is ready for another update to be released.

**Comment by Gushousekai195** [comment]
@pupnewfster Tried compiling it myself using Gradle 4.9.  Didn't work:

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/
4.9/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 3145728KB object heap


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

This goes much further over my head than I thought.  I have basically zero experience with this.

**Comment by pupnewfster** [comment]
No idea seems you don't have enough ram allocated, but at this point as I fixed the other things I wanted to address, the easiest solution may just be to wait until @sinkillerj has a chance to release a new update.
