### ISSUE TITLE
ProjectE step assist overrides step assist from other mods.

### ISSUE THREAD

**Issue by Eldresh** [sinkillerj/ProjectE#2006]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12.2-PE1.4.1

Exact Forge version: forge-1.12.2-14.23.5.2847

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): no crash

Steps to reproduce:

1. Have ProjectE installed and attempt to use step assist from mods like Astral Sorcery or Genetics Reborn.
2. Give yourself step assist through either of the mentioned mods, but don't wear the ProjectE gem boots.
3. Attempt to walk up a block with step assist and fail.

What I expected to happen: Step assist to work in other mods as normal, even when ProjectE is installed.

What happened instead: ProjectE appears to be overriding step assist granted from other mods. Related conversation [here](https://github.com/TheUnderTaker11/GeneticsReborn/issues/126) on the Genetics Reborn github (last post by clubpetey has the relevant info). As it was confirmed to be a ProjectE issue and not an issue with the other mods (and I've also checked this with just ProjectE and Genetics Reborn or Astral Sorcery installed) I've gone ahead and reported it here since it seems it has not been.

**Comment by pupnewfster** [comment]
Thank you for the detailed report, while I doubt this will end up getting fixed in the 1.12 branch mostly due to time constraints, from what I can tell this issue probably still exists in the 1.15 version so I will look into fixing it there.

**Comment by Eldresh** [comment]
I understand if it doesn't end up fixed for the 1.12 version, but I figured the least I could do was make sure you were aware of it.

**Comment by leo152004** [comment]
How to repair this? Where is internal abilities? I play on 1.7.10 if that changes something

**Comment by pupnewfster** [comment]
If you want to fix this on anything other than 1.15 you are going to have to figure out how to back port the commit yourself and compile the jar for your own use. For 1.15, we just need to wait until @sinkillerj has a chance to release the next update.
