### ISSUE TITLE
Error Mapping EMC when using large Modpack (All the Mods 5)

### ISSUE THREAD

**Issue by cj3636** [sinkillerj/ProjectE#2007]
Possible CraftTweaker issue, but I am very unsure.

### Forge Version: **forge-1.15.2-31.1.63**

_Sincere appologies for this terrible log:_
### Not a Crash, but an EMC Mapping issue: [GitHub](https://raw.githubusercontent.com/cj3636/temperror/master/README.md)
(Full MC log, error is at **Line 11584**)

### Steps to reproduce:

1. Add ProjectE to the Modpack (any version) [ATM5](https://www.curseforge.com/minecraft/modpacks/all-the-mods-5)

### What I expected to happen:
EMC to map to all applicable vanilla items correctly.

### What happened instead:
EMC does not get mapped correctly. 
Many Vanilla and ProjectE items do not have EMC and almost all crafted items are lacking EMC.
Items with damage values or NBT do not get EMC automatically. 

I.E. A diamond pick is manually given 1000 EMC, but once used it loses all EMC. Or when enchanted all EMC is removed.

**Comment by dani8738** [comment]
i have the same problem on a custom modpack. it also seems thay every time i relog or the server restarts it gives random items the emc while the rest has none.

**Comment by James103** [comment]
@dani8738 What mods are you using and can you upload the logs corresponding to the error?

**Comment by dani8738** [comment]
@James103 there is no log that im aware of. this is something i found out when joining the server/game. cant seem to narrow down what is to blame. but if i try it on 1.12.2 with the same or even more mods there is no problem at all.

**Comment by pupnewfster** [comment]
I am going ahead and closing this, if you update to ProjectE 1.0.4 and provide your latest.log we should be able to read the log and tell you what mod is breaking the EMC calculations, as PE 1.0.4 added some extra error logging.
