### ISSUE TITLE
Stone Slabs and Window Panes have no EMC

### ISSUE THREAD

**Issue by Gushousekai195** [sinkillerj/ProjectE#2009]
ProjectE-1.15.2-PE1.0.3B

1.15.2-forge-31.1.62

Steps to reproduce:

1. Craft Stone Slabs or Glass Panes

I expected both Stone Slabs and Glass Panes to be worth 3 EMC and 6 EMC respectively based on the materials they are made from.

Both have no EMC and cannot be transmuted.

Is this intentional?

**Comment by MaPePeR** [comment]
Yes, this is intentional. You are missing, that you get more than one stone slab and glass pane per craft, which results in the EMC per item being less than one.
