### ISSUE TITLE
Can't set recipes specifying tiers (specifically Mekanism's Energy Cube)

### ISSUE THREAD

**Issue by elisionducoeur** [sinkillerj/ProjectE#2013]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
12.2.2-PE1.4.1

Exact Forge version:
14.23.5.2838

What I expected to happen:
Crafting higher tiers

It seems like this is a problem with NBT tags? And its been fixed in the latest version? Just want to confirm and ask if there's a workaround. (I'm playing SF4 and don't know how many mods I would need to upgrade to get PE to work with Mekanism or how much I might break the game by upgrading different mods)
#1974 #1731

**Comment by pupnewfster** [comment]
You are correct that this is no longer an issue in modern MC versions and that there is no workaround in 1.12.
