### ISSUE TITLE
bug(at least i think it is) related to using avaritia together with project E in 1.7.10

### ISSUE THREAD

**Issue by xtremesword** [sinkillerj/ProjectE#2016]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): version 1.7.10

Exact Forge version: also 1.7.10

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):  do not have
because it doesnt crash or anything
Steps to reproduce:

1.just log in game and in a world

What I expected to happen:  the blocks in avaritia to be all ok

What happened instead: most of the blocks do not have EMC so i cant multiply them

**Comment by xtremesword** [comment]
is it fixed in later versions because if it is i cant change my version because im using other mods that are only in 1.7.10

**Comment by pupnewfster** [comment]
Firstly exact versions do not mean 1.7.10... they mean the version of the thing they ask for. Secondly this is because the max EMC limit back in 1.7.10 used to be a lot lower than it is now so most avaritia items would have EMC values greater than ProjectE can handle.
