### ISSUE TITLE
Hopping bonsai pots from "Bonsai Trees" mod sometimes get broken with more than 2 horvest goddess bands on pedestals

### ISSUE THREAD

**Issue by KatouMegumi-osu** [sinkillerj/ProjectE#2017]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12.2-PE1.4.0

Exact Forge version: 14.23.5.2808

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. Place a field of hopping bonsai pots, fill them some kind of tree to grow
2. Place a pedestal in the center with "Harvest Goddess Band" and activate it
3. Do the second step again and again.

What I expected to happen: Trees in bonsai pots to grow faster, which they d. But...

What happened instead: Bonsai pots get broken once they reach full growth stage, no items dropped.

**Comment by sinkillerj** [comment]
A new version has been released with makes changes to the Harvest Goddess band. Should this issue still persist after updating there is a new blacklist.
