### ISSUE TITLE
reload emc problem

### ISSUE THREAD

**Issue by TheNimbleNinja** [sinkillerj/ProjectE#2018]
**Tickets that do not conform to this template will be closed without comment**

ProjectE-1.15.2-PE1.0.3B.jar

Exact Forge version: forge-31.1.99

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen:

the commands to set and reload emc are not working

What happened instead:

**Comment by pupnewfster** [comment]
You are going to have to give more information than "not working". Also in 1.14+ we add into `/reload` rather than having `/project reloadEMC`.
