### ISSUE TITLE
Transmutation Table compatablilty bug with other mods.

### ISSUE THREAD

**Issue by Weymouth87** [sinkillerj/ProjectE#2019]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12.2 PE 1.4.1

Exact Forge version: 14.23.5.2854

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): No crash caused.

Steps to reproduce:

1. Place a backpack from Iron Backpacks into the transmutation table. 
2. Retrieve it from the transmutation table. 
3. Recieve an unusable, untextured item (shown here: https://prntscr.com/so2d3i) 

What I expected to happen:
Given the backpack is shown to have an EMC value i expected it to be taken out of the table and be useable as the original item. 

Im hoping that it is this mod I report the bug to, apologies if not. However with the mod being distributed in 1.12.2 packs still I was hoping this may receive a fix or suggestions to help.

What happened instead:
An untextured and unusable item was received.

**Comment by sinkillerj** [comment]
This is due to the table stripping the NBT tag, you will need to add the item to the NBT whitelist but even then you will only be able to learn one variant.
