### ISSUE TITLE
EMC values above 1 billion are displayed as 1,000 times more than actual value

### ISSUE THREAD

**Issue by James103** [sinkillerj/ProjectE#2021]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.15.2-PE1.0.3B

Exact Forge version: 31.2.0

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): No crash

Steps to reproduce:

1. `/projecte setEMC 1000000000 bedrock` then `/reload`
2. `/give @p bedrock`
3. `/give @p projecte:transmutation_tablet`
4. Open the transmutation tablet and burn the bedrock for EMC.
5. Your EMC value displays as "1 Trillion" when it should be "1,000,000,000" or "1 Billion".
6. `/give @p stone`
7. Burn the stone for EMC.
8. Take out multiple pieces of stone.
9. Your EMC value correctly displays as some value less than a billion, e.g. "999,999,990".
10. `/give @p bedrock 1000`
11. Burn all 1,000 pieces of bedrock for EMC.
12. Your EMC value displays as "1 Quadrillion", which expands into long form as something like "EMC: 1,000,000,000,000".

What I expected to happen:
* The postfixes that describe the order of magnitude of your EMC are correctly positioned, so 10^9 EMC is "1 Billion", 10^12 EMC is "1 Trillion", and so on and so forth.

What happened instead:
* The postfixes that describe the order of magnitude of your EMC are shifted by one compared to the actual numbers, so "1 Trillion" corresponds to 10^9 EMC, "1 Quadrillion" corresponds to 10^12 EMC, and so on and so forth.
* Also, Full EMC display isn't available when you have between 1,000,000,000 and 999,999,999,999 EMC inclusive.

**Comment by pupnewfster** [comment]
Thank you for your detailed report, it seems when I rewrote the postfix code to be more verbose I was off by one and shrinking it to 1 trillion at 1 billion. The reason hovering over it wasn't working was due to it not expecting it to be postfixed before 1 trillion.
