### ISSUE TITLE
Custom EMC for a name

### ISSUE THREAD

**Issue by omerbadawy11** [sinkillerj/ProjectE#2023]
Exact ProjectE version: ProjectE-1.12.2-PE1.4.1

Exact Forge version: Forge-14.23.5.2847

Hello,
This isn't a bug exactly I just keep causing issues on the server trying to figure it out on my own.
I have a question if you don't mind helping me, I need to make all items with a specific name in their id get 0 EMC, for example, blacklist all "Oak" items
How would i do that in a simplified way?
Your help is appreciated, 
Have a great day

**Comment by pupnewfster** [comment]
There isn't a way in ProjectE to do this. I believe with CraftTweaker you can use regex to select items and you could loop over all of them adding them to a new oredict entry such as `oakItems` and then add an emc value to that oredict entry. I don't remember offhand how to select items in CraftTweaker via regex though.
