### ISSUE TITLE
Suggestion: A way to query, set or change a player's EMC using commands

### ISSUE THREAD

**Issue by James103** [sinkillerj/ProjectE#2024]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.15.2-PE1.0.3B
(Note: This also applies for 1.12.2 as well)

Exact Forge version: 31.2.0

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): No crash

Steps to reproduce:

1. `/projecte setPlayerEMC <player> <integer>`
2. `/projecte addPlayerEMC <player> <integer>`
3. `/projecte queryPlayerEMC <player> [divisor]`

What I expected to happen:
The first command sets the EMC value for the specified player to the given value, and the second command changes the EMC value for the specified player by the given value (can be positive or negative). In both cases, the player's EMC value is bounded to between 0 and either `Long.MAX_VALUE` or `Double.MAX_VALUE`. For example, assuming you start with 1,000 EMC, running the command `/projecte setPlayerEMC @p 1100` is the same as running `/projecte addPlayerEMC @p 100`, with both setting your EMC to 1,100. Similarly, if you start with 1,000 EMC, running the command `/projecte addPlayerEMC @p -100` will deduct 100 EMC from you, leaving you with 900 EMC.

The third command queries the EMC value for the specified player. For example, if you have 1,000 EMC and you run `/projecte queryPlayerEMC @p` on yourself, it will return 1,000. Note that if you have more than 2,147,473,647 EMC when you run the `/projecte queryPlayerEMC @p` command, it will just return 2147483647, unless you specify a power of 10 to divide the return value by using the `[divisor]` argument. For example `/projecte queryPlayerEMC @p 3` returns 1,234 if you have 1,234,567 EMC, while  `/projecte queryPlayerEMC @p 18` returns 602,000 if you have 602 sextillion EMC.

What happened instead:
All of the three above commands don't exist yet.

Example use cases:
* To give the player a penalty to their EMC when he/she dies or takes damage
* To allow for various features that use EMC to heal/feed yourself
* To allow for you to summon entities using your EMC without using spawn eggs
* To allow for various things to give you bonus EMC
* To allow players to start with a specified amount of EMC without having them start with a Transmutation Table/Tablet and/or transmutable items

**Comment by sinkillerj** [comment]
While all this is exposed in the API for more advanced use I suppose adding commands wouldn't hurt. I'll look into adding this for the next release.

**Comment by James103** [comment]
Will the commands that I proposed be added into ProjectE for 1.12.2, or will they only be added for 1.15? Backporting those commands to 1.12.2 would allow them to be used in CraftTweaker scripts to modify player's EMC on more events, like taking damage.

**Comment by sinkillerj** [comment]
It is very unlikely that the change would be backported.

**Comment by James103** [comment]
This is implemented in version 1.1.0 for Minecraft 1.19.2: https://www.curseforge.com/minecraft/mc-mods/projecte/files/4860858
