### ISSUE TITLE
Very large EMC values (≥1e12) on items are always displayed in full

### ISSUE THREAD

**Issue by James103** [sinkillerj/ProjectE#2025]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.15.2-PE1.0.3B

Exact Forge version: 31.2.0

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): No crash

Steps to reproduce:

1. Create a custom 1.15.2 Forge modpack with just the ProjectE mod.
2. Launch the custom modpack.
3. `/projecte setEMC 12345678987654321 bedrock` then `/reload`
4. Take a look at the EMC value displayed for bedrock.
5. Burn the bedrock for EMC.
6. Take a look at your EMC value displayed in the tablet.
7. Create a custom 1.12.2 Forge modpack with the latest versions of ProjectE and ProjectEX.
8. Take a look at the EMC value for a Final Star.

What I expected to happen:
Step 4 returns a value of `12.35P` or `1.235e16` as the displayed EMC value for bedrock, unless you hold Shift, in which case the full value of `12,345,678,987,654,321` is displayed.

What happened instead:
Step 3 succeeds, setting the correct EMC value for bedrock.
Step 4 returns a value of `12,345,678,987,654,321` for the EMC value, which is obviously way more than a trillion EMC.
Step 6 returns the correct displayed value of `12.3 Quadrillion` in the transmutation tablet.
Step 8 returns the correct value of, for example `600P` (where the `P` stands for quadrillion).

**Comment by pupnewfster** [comment]
Isn't this basically a duplicate of your issue #2021 or am I missing some minor difference?

**Comment by James103** [comment]
This is a separate issue since it only affects the EMC display on items, rather than on the transmutation tablet. This is what applies for #2025:
![image](https://user-images.githubusercontent.com/37945304/83645674-5b9e9700-a578-11ea-8ead-b6fedcbf498f.png)

And this is what applies for #2021:
![image](https://user-images.githubusercontent.com/37945304/83645763-78d36580-a578-11ea-8c7c-6e4bd0314c11.png)

**Comment by pupnewfster** [comment]
I will let @sinkillerj decide on if this change should be made (personally I don't see much of a point); this is not actually a bug, in fact the main reason that the abbreviation system even exists for the condenser and transmutation table is to make it so that it is readable and doesn't overflow past the GUI.

**Comment by sinkillerj** [comment]
If anything the fix may be to bring back the "too damn much" text obfuscation.

**Comment by James103** [comment]
I will close this for now, as it is not completely relevant. Even an EMC value of 9 quintillion for a single item and in the sextillions in Refined Storage will still fit within the tooltip on a reasonably sized display.
![image](https://user-images.githubusercontent.com/1203288/53687117-945d1a00-3cfe-11e9-91da-821e1a720a22.png)
