### ISSUE TITLE
Right-clicking grass block does not make a path block

### ISSUE THREAD

**Issue by darthvader45** [sinkillerj/ProjectE#2029]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): PE1.4.1 for 1.12.2

Exact Forge version: 14.23.5.2854

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. Make dark matter shovel/Red Matter Shovel/Red Morningstar
2. Right-click grass block.
3. Profit.

What I expected to happen: When uncharged, will turn grass into grass path

What happened instead:  Nothing.

**Comment by pupnewfster** [comment]
I believe this got fixed in my rewrite of tools during the 1.14 port. Currently there are no plans to backport any of the newer changes to 1.12.
