### ISSUE TITLE
Items dont stay in the table

### ISSUE THREAD

**Issue by Burnout25** [sinkillerj/ProjectE#2030]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version: 1.12.2-PE1.4.1

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen:

What happened instead: If I put certain items in the transmutation table and try to take multiple back out it just takes out the item and it disappears from the transmutation table.(the items I've noticed so far have been dark matter, diamond blocks, and dark matter relays)

**Comment by sinkillerj** [comment]
Are you sure you have enough EMC? Items you cannot afford are not displayed.

**Comment by Burnout25** [comment]
Oh I didnt know that, thank you, sorry

**Comment by sinkillerj** [comment]
Are you sure you have enough EMC? Items you cannot afford are not displayed.
