### ISSUE TITLE
Forge removes Watch of Flowing Time when placed on a Dark Matter Pedestal

### ISSUE THREAD

**Issue by asyagelski** [sinkillerj/ProjectE#2031]
**Exact ProjectE Version:** 1.12.2-PE1.4.1

**Exact Forge Version:** 14.23.5.2847

**Link to crash log:** https://pastebin.com/qMur2WEY

**Steps to reproduce:**
  1. EMC generation is implemented with the collectors from the mod _Project Ex_.
  2. Place Dark Matter Pedestal(s) next to collectors.
  3. Place Watch of Flowing Time on the pedestal(s).

**What I expected to happen:**
Correct increase in EMC generation.

**What happened instead:**
  1. EMC generation increases for a second then returns to normal, and any additional pedestal activation will lag for a second (implying that the previously activated pedestal is crashing and Forge is removing the Watch of Flowing Time from it to prevent a hard crash).
  2. Watch of Flowing Time "remains" on the pedestal graphically until a block update, in which it's removed promptly.

**Comment by sinkillerj** [comment]
Our stance with Project EX is use it if you want, but bugs are to be expected. We have no affiliation with the project.

**Comment by asyagelski** [comment]
Oops, should've tested it without that. However, the issue still persists. Same errors in the log as well. 4 Mk3 Collectors surrounding a Condenser.

**Comment by James103** [comment]
Maybe the Dark Matter pedestals are speeding up each other infinitely by each pedestal ticking the others, which ticks the original, which ticks the others, which ticks the original (and so on and so forth) causing infinite stack growth? That could be the case given the following portion of the stack trace is repeated dozens of times:
```
...
	at moze_intel.projecte.gameObjs.tiles.DMPedestalTile.func_73660_a(DMPedestalTile.java:45)
	at moze_intel.projecte.gameObjs.items.TimeWatch.speedUpTileEntities(TimeWatch.java:213)
	at moze_intel.projecte.gameObjs.items.TimeWatch.updateInPedestal(TimeWatch.java:355)
...
```
