### ISSUE TITLE
[ProjectE 1.15.2-PE1.0.4 - Forge 31.2.20] Bug Vulcanite Amulet

### ISSUE THREAD

**Issue by Hazorback** [sinkillerj/ProjectE#2033]
Tickets that do not conform to this template will be closed without comment

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): PE1.0.4

Exact Forge version: 31.2.20

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):none

Hello sinkillerj, I really like your ProjectE mod, I've been using it for a long time, and in this version for minecraft 1.15.2 I found a bug in the vulcanite amulet, when I use it to dry an area visually it removes the water but when it enters the place it looks like if you were in the water until you start to suffocate and die, it is as if only the visual part has changed and not the water itself of the place and when I leave the game and come back the water is there again. What I believe should be without water as before in the other versions worked. If you can check for me I would be very grateful.
I did a test with version 1.15.2 of minecraft with the mod projectE 1.15.2-PE1.0.4 and forge 31.2.20 only, to see if the bug was due to some kind of interaction between other mods, but no. As attached the image you can see what happens.
![bug](https://user-images.githubusercontent.com/67071408/84937334-f5eef680-b0b1-11ea-8f9d-2b691ecf2d6d.jpg)

**Comment by James103** [comment]
@Hazorback 
1. Have you tried giving yourself a charged Klein Star and putting it in the hotbar, and then using the Vulcanite Amulet? It could be set to cost EMC for each operation.
2. Have you tried using the Evertide Amulet (both with and without a Klein Star)?

**Comment by Hazorback** [comment]
@James103

Hello, yes I did the test also with the star Klein charged in the hotbar. Having an EMC source such as the star or coal in the inventory, the vulcanite amulet will release a lava cube on the projectile, if there is no EMC source it would only dry the place which is not happening in either situation. Only lava becomes obsidian but you still get drown damage even though it appears that the area no longer has water. And when you leave the save and return again the water is there where it used to be.
The Evertide Amulet is an inexhaustible source of water that can put water in an area without the need for an EMC source.

![teste 1](https://user-images.githubusercontent.com/67071408/85322025-0af5cc00-b49c-11ea-97b2-5e188c6b95e6.jpg)
![teste 2](https://user-images.githubusercontent.com/67071408/85322137-31b40280-b49c-11ea-88cb-a7532c04fdf6.jpg)
![teste 3](https://user-images.githubusercontent.com/67071408/85322174-3f698800-b49c-11ea-87b5-b433d59ce257.jpg)

**Comment by James103** [comment]
In other words, there is a desync when using the Vulcanite Amulet that causes it to think that it has removed some water on the client side, even though it did not remove any water on the server side. Does movement while being in such air pockets seem consistent with you being out of water or you being in water?

Also, I've tested it with ProjectE-1.15.2-PE1.0.4 and Forge 31.2.**0** with the Vulcanite Amulet. With an EMC source (such as a Klein Star), the projectile fires, then stops in its place. A Drowned comes out of the side of the water and into the air pocket created by the amulet's projectile, but still behaves as it is still in the water. I then summoned a Bee in this phantom air pocket, and according to the death message produced by the DeathFinder mod, it drowned.

**Comment by pupnewfster** [comment]
I believe it has to do with the fact that I ported the feature before I had a better grasp of how the in world fluid system in 1.13+ works (so it actually requires some changes rather than just getting the code to compile). I vaguely know what is needed to fix this but it probably will be a while before I get the chance to work on it as the two summer courses I am taking started today, and what little free time I will have over the next few weeks is going to be spent on porting Mekanism to 1.16 once that releases.
