### ISSUE TITLE
Set no EMC Value

### ISSUE THREAD

**Issue by StarGalaxianVoid** [sinkillerj/ProjectE#2034]
Hello, I am a fellow modpack developer! My modpack name is UltraCraft / Adventure & Tech you can check out the beta https://www.curseforge.com/minecraft/modpacks/ultracraft-adventure-tech

I have the projects mod in my mod pack, but I have op items that require endgame items like nether stars and dragon eggs. Can I configure the EMC value of those 2 items to not have any value? I have read some other issues of this and it used in-game command. I want it to stay configured when I share it. Please answer to this issue

**Comment by Brittank88** [comment]
Hello! Just a friendly passerby - you can use `/projecte removeEMC` whilst holding the desired item if you want it to have no EMC value, however if you want to set it to an EMC value of 0 (such that recipes using these items still have an autocalculated EMC) I don't think this is possible. There is always a chance I am incorrect on that point though.

**Comment by sinkillerj** [comment]
Resolved on Discord as well. But to answer the question, in order to map a recipe all ingredients must have at least 1 EMC.

**Comment by MaPePeR** [comment]
>  in order to map a recipe all ingredients must have at least 1 EMC.

Its more like "in order to map a recipe all ingredients have to have a calculable EMC value. Slabs and panes have a value less than 1, but will not cause the output of a recipe to not have an emc value.

If i remember correctly you can also mark an item as "free" In the customConversions File.

**Comment by sinkillerj** [comment]
What Blub said lol
