### ISSUE TITLE
[Feature, MC versions from 1.12.x to 1.15.x] Introduce tiered condensers

### ISSUE THREAD

**Issue by Monniasza** [sinkillerj/ProjectE#2035]
What to add?
---
Tiered condensers, with limits of 1, 8, 64, 512, 4096, etc. EMC

How it will work?
---
Tiered condensers would have limited EMC capacity, They would also have cheaper recipes than standard condensers.
Suggested recipe for Tier 1:
[furnace, low covalence dust]

How it will be used?
---
Modpack creators can specify limits. I also plan to use it in my new modpack
Tiered condensers would gradually introduce new players to more advanced machines in ProjectE

**Comment by pupnewfster** [comment]
We are not planning on implementing this as ProjectE is meant to recreate EE2. I do recall there was an addon that someone made that I think has a similar concept: https://www.curseforge.com/minecraft/mc-mods/progressive-alchemy
