### ISSUE TITLE
[1.12.2] Swiftwolf's Rending Gale sounds are reversed

### ISSUE THREAD

**Issue by supershadow64ds** [sinkillerj/ProjectE#2044]
Exact ProjectE version: 1.12.2-PE1.4.1
Exact Forge version: 14.23.5.2854
Steps to reproduce: 
1. Activate/Deactivate Swiftwolf's Rending Gale

What I expected to happen: Swiftwolf Activation sound upon activating flight, EE2 deactivation sound upon deactivation

What happened instead: EE2 deactivation sound upon activating flight, activation sound upon deactivating ring.

**Comment by HNGamingUK** [comment]
+1

**Comment by xJon** [comment]
Fixing this would be great!

**Comment by pupnewfster** [comment]
This was fixed for 1.18 as part of https://github.com/sinkillerj/ProjectE/commit/d389189917cf8b611680d05dd09af8eab7aeac2c

**Comment by xJon** [comment]
Fixing it in 1.12 would still be great, but thanks for the response nonetheless :)

**Comment by xJon** [comment]
1.12 fork & fix for this is available by @ACGaming over https://github.com/ACGaming/ProjectE/releases/tag/PE1.4.2
