### ISSUE TITLE
In ProjectE (1.7.10) the transmutation table when i click it, it just kick my from my game

### ISSUE THREAD

**Issue by zoldmaki** [sinkillerj/ProjectE#2049]
Exact Forge version: 1.7.10-PE1.10.0
Can any one told me why is this hapening or what mod is having conflict with the transmutation table?
I don't have any addons for it.
But i only put ProjectE in the there is no problem
my modlist:
![image](https://user-images.githubusercontent.com/63256863/90018105-b822de80-dcac-11ea-922c-aa44d6814fb7.png)
The error:
![image](https://user-images.githubusercontent.com/63256863/90018420-2c5d8200-dcad-11ea-9b38-04cfde63935c.png)

**Comment by sinkillerj** [comment]
No log was provided, and we do not provide support for 1.7.
