### ISSUE TITLE
Change to archive, resulting in forced exit.

### ISSUE THREAD

**Issue by lp20010415** [sinkillerj/ProjectE#2051]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.12.2-PE1.4.1

Exact Forge version:14.23.5.2854

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://paste.ubuntu.com/p/7JvKxDqszX/

Steps to reproduce:

1.

What I expected to happen:That is I quit a world ,and enter other world。Later,forced return。

What happened instead:Every play minecarft ,only enter a world.

Please tell me what happened,Thank you and best wishes

**Comment by pupnewfster** [comment]
Seems like the crash is happening in equivalentenergistics

**Comment by lp20010415** [comment]
> 似乎碰撞发生在同等能量中

You mean is EquivalentEnergistics mod conficts with projectE?

**Comment by pupnewfster** [comment]
No, I am saying the crash is something in their code, and I am not familiar with their code. It could be that they don't support the latest ProjectE version for 1.12 (I don't know if they ever updated to it) or it could just be some other random thing broke.

**Comment by lp20010415** [comment]
All right,So I should ask them over there?Maybe is their code problem?

**Comment by lp20010415** [comment]
> 不，我是说崩溃是他们代码中的问题，我对他们的代码不熟悉。可能是他们不支持1.12的最新ProjectE版本（我不知道他们是否曾对其进行过更新），或者可能是其他一些随机事件中断了。

I want solve this problem . So please tell me what should I do

**Comment by lp20010415** [comment]
> No, I am saying the crash is something in their code, and I am not familiar with their code. It could be that they don't support the latest ProjectE version for 1.12 (I don't know if they ever updated to it) or it could just be some other random thing broke.

Do you have time ?

**Comment by lp20010415** [comment]
I think I know what you mean. You should mean that equivalentenergistics depends on projectE . So I should go and ask them, right?I suddenly understand these days, ha ha. I'm a little slow.
