### ISSUE TITLE
[Request] Update mod for 1.16.1

### ISSUE THREAD

**Issue by MiguelArenasVillalobos** [sinkillerj/ProjectE#2052]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version: forge-1.16.1-32.0.108-installer.jar

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen: Update mod for 1.16.1

What happened instead: :c

**Comment by pupnewfster** [comment]
Not going to happen, when I get a bit more time I will be updating ProjectE directly to 1.16.2

**Comment by Werner1201** [comment]
Better Yet directly to 1.16.4 since I is the latest and the Direwolf20 New Pack is for this version of Minecraft that will stay for a while.
