### ISSUE TITLE
Walking or staying still on water costs 1 food point every few seconds.

### ISSUE THREAD

**Issue by James103** [sinkillerj/ProjectE#2054]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.15.2-PE1.0.4
Exact Forge version: 31.2.36

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): No log entries related to the issue from a quick look at the recent log, but [here is the log](https://gist.github.com/James103/a8a2900c46194bc5eeb621d99a7d1129).

Steps to reproduce:
1. Install the above mods.
2. Get yourself a full set of Gem armor, minus the chestplate.
3. Walk on water.
4. Depending on the depth of the water, you will lose a lot of hunger just from staying on the top of the water.
5. Check your statistics. "Distance Walked under Water" is increasing in the tens of meters per second.

What I expected to happen:
* No hunger loss from staying still on water, the "Distance Walked under Water" stat does not increase from standing still.

What happened instead:
* Even when staying still on top of the water, you gain several meters per second in "Distance Walked under Water" stat and you lose 1 food point every few seconds.

**Comment by pupnewfster** [comment]
Tried reproducing this on the 1.16 branch, and was unable to. My best guess is either one of the other mods you have installed was doing weird things or it is something mojang fixed with the logic of how they increment stats and the like in 1.16.

**Comment by James103** [comment]
Closing, as this issue is (I think) no longer reproducible in newer versions.
