### ISSUE TITLE
crashing when putting universal remote in transmutation table

### ISSUE THREAD

**Issue by inbguy** [sinkillerj/ProjectE#2056]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.12.2-PE1.4.1.jar

Exact Forge version:
14.23.5.2854

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://pastebin.com/LNtf2Qcz

Steps to reproduce:

1. download the projecte and the [universal remote](https://www.curseforge.com/minecraft/mc-mods/universal-remote) mods
2. try to insert the remote into the transmutation table

What I expected to happen:
the table to learn the remote and be able to duplicate it
What happened instead:
the game crashed, and crashed again any time I opened the table

**Comment by sinkillerj** [comment]
By default the transmutation table strips NBT values, this mod is crashing because it does not know how to handle the NBT being missing. You will need to add this item to your NBT whitelist.

**Comment by inbguy** [comment]
It crashes when I try to open minecraft: https://pastebin.com/ri4KqypY

**Comment by inbguy** [comment]
It crashes when I try to open minecraft: https://pastebin.com/ri4KqypY

**Comment by inbguy** [comment]
@sinkillerj It crashes when I try to open minecraft: https://pastebin.com/ri4KqypY

**Comment by inbguy** [comment]
turns out I needed to put a ";" at the end of something, but now it just crashes while rendering screen after putting the remote in transmutation again: https://pastebin.com/eWeicGSL

**Comment by sinkillerj** [comment]
The item which lacks NBT is still in your inventory, you can remove this from your player file with an NBT Editor.

**Comment by inbguy** [comment]
I cleared knowledge, and I also tried opening a new world, that's not it

**Comment by inbguy** [comment]
@sinkillerj I need your help
