### ISSUE TITLE
Testing 1.16.3 - September 14th Source

### ISSUE THREAD

**Issue by peekpeekpeekpeek** [sinkillerj/ProjectE#2057]
ProjectE 1.16.x github branch Sept 14th Source

Forge 1.16.3-34.0.7
Minecraft 1.16.3

I downloaded the new 1.16.3 source for ProjectE, and built it.
I used gradlew build to build it, and copied projecte-1.0.4.jar from 
ProjectE-mc1.16.x\build\libs

Same problems as build from last month, no blocks have EMC.
Transmutation table won't accept any items, so no EMC, no transmutation.

Am I building the jar incorrectly?

**Comment by sinkillerj** [comment]
1.16 is not ready for use, and we do not provide support for self compiled builds.
