### ISSUE TITLE
Mekanism/NBT-Seperated Blocks/Items cannot have the correct EMC Value

### ISSUE THREAD

**Issue by jadenquinn** [sinkillerj/ProjectE#2069]
Hi, this is Jaden and I was told (and found out myself) that ProjectE doesn't work with NBT at all, which completely messes with some mods I use and I consider this to be a bug so I'm posting it here.

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.12.2-PE1.4.1
Exact Forge version:
1.12.2-14.23.5.2854
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
N/A - Not a crash.
Steps to reproduce:

1. Install ProjectE with Mekanism.
2. Try to set an EMC Value to an Energy Cube that isn't the basic one.
3. See that it doesn't work as it should, as Mekanism's machine blocks are done by NBT Data and ProjectE doesn't do with that.
4. Make a bug report.

What I expected to happen:
I expected the Mekanism machine blocks to have the value I set for that one machine block (Elite), not all of them at once (Basic, Advanced, Elite, Ultimate).
What happened instead:
4 of them have the value that I set for 1 of them, so they aren't separate.

**Comment by pupnewfster** [comment]
1.12 doesn't have support for NBT, if you update to 1.14+ we have handling for some NBT but also Mek doesn't use NBT in that for determining items apart anymore.

**Comment by jadenquinn** [comment]
I don't have the option of updating the mods in the packs I have to 1.14+. Most mods have not moved on yet, and it's laggy-er than I think it should be.
