### ISSUE TITLE
EMC Values Missing

### ISSUE THREAD

**Issue by monyarm** [sinkillerj/ProjectE#2074]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.0.4 (I compiled the 1.16.x  branch for 1.16.4)

Exact Forge version: 35.1.13

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://paste.ee/p/jrhbh

Steps to reproduce:

1. run ProjectE
2. check EMC values

What I expected to happen:

Items having EMC values.

What happened instead:

No EMC values anywhere to be seen.

the exact part that causes the issue is:
```
[26Dec2020 17:15:54.914] [Render thread/ERROR] [projecte/]: Error calculating EMC values
java.lang.NoClassDefFoundError: org/apache/commons/math3/fraction/BigFraction
```

**Comment by pupnewfster** [comment]
Sounds like you are using the wrong jar/didn't compile it properly
