### ISSUE TITLE
1.12.2 ProjectE-1.12-PE1.3.2h  How to make EMC energy common in the transmutation table

### ISSUE THREAD

**Issue by OrixoN** [sinkillerj/ProjectE#2075]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12-PE1.3.2h.jar

Exact Forge version: 31.2.47

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): no crash

Steps to reproduce:

1.

What I expected to happen: 
EMC energy will be shared in the transmutation table

What happened instead: a friend has it, but I don't

**Comment by yuminstalljoe** [comment]
It is intended for the Transmutation Table to not share EMC or knowledge. You can view https://github.com/sinkillerj/ProjectE/wiki/Transmutation-Table to see that it describes binding to the soul of individually using it.

**Comment by OrixoN** [comment]
Thank you Yuminstalljoe
