### ISSUE TITLE
How to set emc value

### ISSUE THREAD

**Issue by EyuphanMandiraci** [sinkillerj/ProjectE#2076]
How can i add emc values on my mod.

**Comment by 003nicky** [comment]
Under the assumption that you are already playing with your mod. You must be an OP on a server or enable cheat mode in Single. If cheat mode is not enabled on your single player world you then switch it to lan, then switch it to lan there is an option to enable cheat mode. Now that you have command permissions you must have the item in your hand and you type /projecte setEMC (number without the brackets) then followed by /projecte realoadEMC. This will update the item to have emc and following recipes crafted with said item that didn't have emc will also be updated as long as the recipe isn't blocked by another item that doesn't have emc.

Make sure to add the total of emc when giving the item it, also make sure to divide the emc if the crafted item makes more than one item. 

Now under the assumption that you want projecte to recognize your mod all the time to give it emc values on its own, I'm sorry I don't know how to help you there.
