### ISSUE TITLE
1.16. status

### ISSUE THREAD

**Issue by LuciusV** [sinkillerj/ProjectE#2077]
Could you please comment current status of 1.16 port and close this issue only after release to avoid people asking for upgrade many times?

**Comment by poobarfoob** [comment]
They have a branch titled 1.16.x, and at the time of writing this the last commit was 4 hours ago. From what it seems, we'll be getting a 1.16 port sometime soon.

**Comment by poobarfoob** [comment]
> Could you please comment current status of 1.16 port and close this issue only after release to avoid people asking for upgrade many times?

They have a branch titled 1.16.x, and at the time of writing this the last commit was 4 hours ago. From what it seems, we'll be getting a 1.16 port sometime soon. (recommented because i forgot to quote reply)

**Comment by sinkillerj** [comment]
When it's done.
