### ISSUE TITLE
1.16.5 unlimited lilac (potentially other plants)

### ISSUE THREAD

**Issue by nayfaan** [sinkillerj/ProjectE#2080]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.16.5-PE1.0.0B

Exact Forge version: forge-1.16.5-36.0.14

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. Hold a Harvest Goddess Band (both active and non active) in hotbar (any slot)
2. Go near a planted minecraft:lilac

What I expected to happen: 
1. Nothing to happen when band non active
2. Lilac will break and drop when band active

What happened instead:
1. Either way, lilac items just keep on showing up from the lilac plant without breaking the plant. Happens when band is on hotbar, even when not in active spot, but not when in inventory

**Comment by pupnewfster** [comment]
Out of curiosity for when I get a chance to look into what is causing this is there any chunk protection mods potentially in play here?

**Comment by nayfaan** [comment]
unlikely. I have a bunch of mods installed but I dont think I have a chunk protector installed. Also Band breaks leaves and some other plants without problem at the same location so shouldn't have anything to do with protection i think

**Comment by nayfaan** [comment]
also while we are on this topic, would like to request that the harvest band to work with plants from other mods if possible, at least plants included by BOP, which is commonly used

**Comment by pupnewfster** [comment]
The harvest band works on any plants that implement the proper vanilla/forge interfaces/methods, if it doesn't work with BOP then they probably aren't implementing the corresponding things on their blocks.
