### ISSUE TITLE
1.16.5 - Breaking energy collector with pickaxe doesn't cause it to drop.

### ISSUE THREAD

**Issue by dev-harvey** [sinkillerj/ProjectE#2081]
ProjectE version: ProjectE-1.16.5-PE1.0.0B

Forge version: 36.0.14

Steps to reproduce:

1. Breaking an energy collector with a pickaxe and it disappears instead of dropping the collector.

Recreated with: 
Diamond pickaxe enchanted with Fortune III, Efficiency IV and Unbreaking III
Netherite Pickaxe enchanted with Silk Touch, Efficiency V, Unbreaking III and Mending
Dark Matter Pickaxe

Happened for a MK1, MK2 and MK3 collector.

**Comment by LuciusV** [comment]
Could you please release dev build on curseforge now for the sake of collectors already placed in our worlds?
