### ISSUE TITLE
1.16.5 Items not showing up after being put in to the transmutation table.

### ISSUE THREAD

**Issue by zz4163** [sinkillerj/ProjectE#2083]
ProjectE version: ProjectE-1.16.5-PE1.0.0B

Forge version: 36.0.13

Steps to reproduce:

1. Put a few different types of item in the transmutation table.
2. Those items disappearing and not showing up after being inserted in to the table.

What I expected to happen: The items I Put in the table will show up at the right side of the interface and I can take the items out.

What happened instead: None of the items I put in the table were shown at the interface.

**Comment by pupnewfster** [comment]
I can't reproduce this so going to need more information such as if this is on a server or single player and if it is a server that both sides do actually have the mod installed.

**Comment by sinkillerj** [comment]
Are you sure you have enough EMC for them to display?

**Comment by kotakotik22** [comment]
Don't know if it's the same bug, but I did get a bug where I learned a diamond, but it didn't show up. I definitely had enough EMC to display it because I just learnt it, but the bug disappeared after a minute

**Comment by Astro-OS** [comment]
I have a similar bug, I am playing on a modified version of Valhelsia 3. When I save my world and close the game, the next time I join some of the stuff I have learned disappears and I can no longer learn them. They have no EMC value. The weird thing is that if i create a new world the unlearned items now have an emc value again. When I copy-pasted the world file they showed up as well. Any clues?

**Comment by pupnewfster** [comment]
Pretty sure this is just related to #2082 then and the fact that another mod is breaking EMC mapping so then no items have EMC values and they get unlearned as they don't have an EMC value. Reloading then enabling the pregen values probably will work in the meantime or look at your log and find out which mod is breaking EMC calculations.
