### ISSUE TITLE
allow tag support within custom emc values

### ISSUE THREAD

**Issue by Warbringer12** [sinkillerj/ProjectE#2084]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
Project e: 1.16.5-PE1.0.0B
Exact Forge version:
36.0.14

I would like the ability to within the config of customemc.json to put in tags for items instead of doing one item at a time.

**Comment by pupnewfster** [comment]
You already can do this just put a `#` in front of the resource location to make it represent a tag instead of an item.
