### ISSUE TITLE
Feature request: More log types from Philosopher stone

### ISSUE THREAD

**Issue by nayfaan** [sinkillerj/ProjectE#2086]
Exact ProjectE version: ProjectE-1.16.5-PE1.0.0B

Exact Forge version: forge-1.16.5-36.0.14

Feature request:
Currently, using the philosopher stone on vanilla logs cycle between the few vanilla minecraft logs. If possible, can it be made to cycle around more logs, possibly utilizing the #minecraft:logs tag?

**Comment by pupnewfster** [comment]
The system is not at all setup for that, you can use CraftTweaker to add/remove conversions though. https://github.com/sinkillerj/ProjectE/blob/mc1.16.x/src/main/java/moze_intel/projecte/integration/crafttweaker/WorldTransmutation.java
