### ISSUE TITLE
1.16.5 Philosopher stone mixing peaceful and passive mobs

### ISSUE THREAD

**Issue by nayfaan** [sinkillerj/ProjectE#2087]
Exact ProjectE version: ProjectE-1.16.5-PE1.0.0B

Exact Forge version: forge-1.16.5-36.0.14

Description: There are 3 types of mobs in minecraft: hostile (e.g. zombie, skeleton, creeper), peaceful (e.g. cow, sheep, chicken), and passive mobs (e.g. spider, enderman, pufferfish). When using the philosopher stone to cycle between mobs, peaceful and passive mobs are grouped as 1 type, causing peaceful mobs to change to passive mobs and vice versa

Steps to reproduce: shoot philosopher stone projectile at peaceful / passive mobs

What I expected to happen: If this is not a bug, I suggest that either group passive mobs with hostile mobs, or make passive mobs their own group

What happened instead: passive mobs can change to peaceful mobs and vice versa

**Comment by pupnewfster** [comment]
https://github.com/sinkillerj/ProjectE/blob/mc1.16.x/src/datagen/generated/data/projecte/tags/entity_types/randomizer/peaceful.json
https://github.com/sinkillerj/ProjectE/blob/mc1.16.x/src/datagen/generated/data/projecte/tags/entity_types/randomizer/hostile.json
the "passive" mobs change with other hostile mobs not peaceful ones?

**Comment by nayfaan** [comment]
an enderman changed into a horse. That was weird. Not sure if its re-reproduceable

**Comment by nayfaan** [comment]
From my testing, hostile mobs are occasionally changing into peaceful mobs with the philosopher stone, but not the other way around

**Comment by nayfaan** [comment]
further test: one consistent case is 
hostile mob --> killer bunny --> peaceful mob
whenever it changes into the killer bunny, it is not recognized as hostile and further conversion will go to peaceful mobs

**Comment by pupnewfster** [comment]
Ah thanks for the further investigation, I can probably add in special casing to force the killer bunny to be properly recognized as hostile for what it turns into.

**Comment by nayfaan** [comment]
killer bunny is just one of the cases, sometimes the conversion doesnt go through the killer bunny, but everytime it goes through the killer bunny it changes
