### ISSUE TITLE
Energy collector recipe is very strange

### ISSUE THREAD

**Issue by PairedDragoon** [sinkillerj/ProjectE#2094]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
1.12.2 PE 1.4.1

Exact Forge version:
 14.23.5.2796

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):
N/A

Steps to reproduce:

1. Find the recipe of the mk.1 energy collector on the FTB sky adventures pack.

What I expected to happen: Craft a mk1 energy collector using a piece of glass, 6 glowstone, a furnace, and a block of diamond.

What happened instead: The recipe required a terrasteel block from botania, a hardened signalium glass from thermal, and a red matter furnace (see attached)

![Base Profile Screenshot 2021 02 20 - 21 54 14 14](https://user-images.githubusercontent.com/79382544/108609687-827f5080-73c7-11eb-9c7a-6733d0e9a48f.png)

**Comment by raziel23x** [comment]
its a modpack they use this thing called craft tweaker and changed many recipes for almost all mods to make them harder or easier not a bug.....

**Comment by PairedDragoon** [comment]
ah ok, thank you
