### ISSUE TITLE
1.16.5 3 problems with Project E 

### ISSUE THREAD

**Issue by BMLoneWolf** [sinkillerj/ProjectE#2095]
Hello, I encounter some problems on my solo modded part with Project E in 1.16.5. (I added it in the Valhelsia 3 modpack)

Forge version : 36.0.15
 
1. When I go to collect an energy collector with a pickaxe, it disappears. 
2. Not all EMCs are visible when loading a game, I have to restart it each time.
3. The items I save in the transmutation table disappear for some when I open the game.

Thank you for everything you can do to solve these problems and good luck !

BMLoneWolf

**Comment by pupnewfster** [comment]
1. #2081
2. #2082
3. This would be because of 2, which causes the EMC to not be present so it unlearns items with no EMC value.
