### ISSUE TITLE
Mk1 can not pick up

### ISSUE THREAD

**Issue by kinagace** [sinkillerj/ProjectE#2097]
**Tickets that do not conform to this template will be closed without comment**

ProjectE-1.16.5-PE1.0.0B.jar

Forge version: 36.0.42

Steps to reproduce:

1.

What I expected to happen: can harvest with Pick

What happened instead: it breaks
![Energey Collector](https://user-images.githubusercontent.com/79542525/108902997-cd2ce280-75ea-11eb-8c6e-e57e738e9ed7.png)

**Comment by pupnewfster** [comment]
#2081
