### ISSUE TITLE
[1.16.5] Tome of Knowledge recipe does not load when enabled

### ISSUE THREAD

**Issue by SDPhantom** [sinkillerj/ProjectE#2099]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.16.5-PE1.0.0B

Exact Forge version: forge-36.0.42

Steps to reproduce:

1. Set **craftableTome = true** in **server.toml**.
2. Start game world.

What I expected to happen: Tome of Knowledge becomes craftable and recipe(s) appear in JEI.

What happened instead: Recipe(s) are not loaded.
The following lines appeared in **latest.log**.
```
[Render thread/INFO]: Skipping loading recipe projecte:tome as it's serializer returned null
[Render thread/INFO]: Skipping loading recipe projecte:tome_alt as it's serializer returned null
```

**Comment by pupnewfster** [comment]
Using `/reload` should work as a workaround for now, the config wasn't loaded in time for the first loading of recipes.
