### ISSUE TITLE
ProjectE commands not working

### ISSUE THREAD

**Issue by Pigrider112233** [sinkillerj/ProjectE#2106]
Exact Forge version: **ProjectE-1.16.5-PE1.0.1B.jar** (the newest for 1.16.5 at the time of writing this)

Steps to reproduce: 
1. type "/projecte (any command)"
2. hit enter

What I expected to happen: A list of commands would pop up, or at least the command I entered would work. (I checked to make sure the syntax was correct, and even beyond that I waited for the suggested commands to pop up.)

What happened instead: "/projecte" is listed as a suggested command, but after that Minecraft does not recognize anything else as a valid command, and typing "/projecte setEMC (value)" does not work, even after trying multiple different numbers and capitalizations. Am I missing something or did I type something wrong?

**Comment by pupnewfster** [comment]
Do you have cheats enabled/are op on a server?

**Comment by Pigrider112233** [comment]
> Do you have cheats enabled/are op on a server?

You know, that is an incredible point and also was the issue. I am sorry for not noticing that before writing this report.
