### ISSUE TITLE
Many vanilla items missing emc values

### ISSUE THREAD

**Issue by sindri829** [sinkillerj/ProjectE#2107]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.16.5-PE1.0.1B.jar

Exact Forge version: 36.0.48

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

"please report this" log: https://pastebin.com/MmDMMBEF

entire server log far too large for pastebin, but that part of the log did specifically ask me to report it to you.
Log is saved in case anyone needs it, but its slightly over 1mb.

What I expected to happen: the ability to put energy collectors into the transmutation tablet

What happened instead: many vanilla items, in this case it was glowstone blocks, have no emc values. Glowstone dust does have an emc value. Another example, diamond pick has no value, but diamonds and sticks have values.

**Comment by Rubyz67** [comment]
same here
