### ISSUE TITLE
Transmutation Tablet Memory

### ISSUE THREAD

**Issue by Lankoran** [sinkillerj/ProjectE#211]
Hi, I'm sorry if this question comes across as being slightly stupid, but i've been unable to find documentation to explain the mechanics of the machine properly and i have no previous experience of the EE mods to compare, so sorry in advance, 

I have a few issues on my multiplayers server with the block, the two main issues i have are to do with the blocks memory, is it intended for the block to have a player-based memory, rather that a memory of its own? i.e. if a friend of mine learns the recipe for diamonds with a tablet, and i learn the recipie for gold should we not both see the both recipes rather than my only seeing hold, and her only seeing diamond?

the second issue i have is that the tablet seems to have a short memory, it only seems to remember a select few items its not a short list, but its not infinite at least. I've often got to "re-learn" items and in some certain circumstances, re-acquiring those items is a pain. Is this also intended?

(The last minor issue i have is to do with sharing the device, and the player who didn't place the item sometimes being unable to remove items while there is spare EMC in there, the blocks disappear once they are placed in the inventory of the player, this only seems to effect the person who didn't place the tablet itself,)

**Comment by illusive817** [comment]
Tablet still loosing learned Recipes
almost on a daily basis i have to re teach it items i have learned several times over.
not sure how or why 
but i will loose random items.

**Comment by MaPePeR** [comment]
@illusive817 are you sure the tablet is not hiding them because you don't have enough emc?

**Comment by illusive817** [comment]
@MaPePeR im fairly certain , i have 100 million emc stored and when i search there gone, so i make a new one and put it in, says Learned.

**Comment by sinkillerj** [comment]
We are aware of a issue regarding the transmutation table forgetting items when new ones are added and are investigating possible solutions at this time.
