### ISSUE TITLE
add a way to disable update msg ?

### ISSUE THREAD

**Issue by IchigoGames** [sinkillerj/ProjectE#2111]
a way to turn off update msg its wrong anyway
![image](https://user-images.githubusercontent.com/11888162/113494101-02123c00-94ab-11eb-9ef9-7a4470b6ab06.png)
![image](https://user-images.githubusercontent.com/11888162/113494106-09d1e080-94ab-11eb-9620-800de02b7a60.png)

**Comment by pupnewfster** [comment]
Just disable forge's update checking in one of forge's conifgs I forget which one but all we do is use forge's system

**Comment by IchigoGames** [comment]
that is No longer a Option in forge

**Comment by IchigoGames** [comment]
idk why they would remove it but they did

**Comment by IchigoGames** [comment]
also why would forge's system say your mod is updated when its not true?
