### ISSUE TITLE
How to increase the emc limit

### ISSUE THREAD

**Issue by Gpiovesana** [sinkillerj/ProjectE#2113]
ProjectE-1.12.2-PE1.4.1 (applicable to all 1.12.x versions)
Exact Forge version: 14.23.5.2854 (My version)

I am playing a public modpack and would like to increase the EMC limit on the transmutation table. My limit is one billion, but I have seen that in other modpacks the limit can exceed 200
![Max_EMC](https://user-images.githubusercontent.com/81973386/113583982-b4a7e300-9600-11eb-8713-059c4b5bd83b.png)
 trillion. How can I change this maximum value?

**Comment by MCSuperplayer** [comment]
ProjectEX (The Addon made by Latvian) increases the Limit by Far
it also allows you to fully Automate stuff with the EMC Links
