### ISSUE TITLE
Update Checked Bug 1.16.5

### ISSUE THREAD

**Issue by IchigoGames** [sinkillerj/ProjectE#2114]
Exact ProjectE version : ProjectE-1.16.5-PE1.0.1B

Exact Forge version: 36.1.4

Minecraft 1.16.5

Steps to reproduce: 

1. Install forge

2. install mod ProjectE-1.16.5-PE1.0.1B

What I expected to happen: if shown that a update is out for it to be true

What happened instead: shows update is out but is the same version that is in use

> Just disable forge's update checking in one of forge's conifgs I forget which one but all we do is use forge's system

this is no longer a option in forge idk forge would remove this but they have. also showing a msg that there is a new version of a mod when its not true is a bug  

adding in a option to turn off update check is a suggetion.

![image](https://user-images.githubusercontent.com/11888162/113929652-eca45700-97b5-11eb-92f1-ea651a5c9a34.png)

**Comment by IchigoGames** [comment]
also yes it happens when no other mods install of course

**Comment by pupnewfster** [comment]
Forge still has the option they just moved it it seems from the forge config to the fml config. Though I will look into why it thinks the version doesn't match when I get the chance.

**Comment by pupnewfster** [comment]
I believe this may now be fixed (I haven't tested yet and not sure when I will get a chance) but in theory I think it should now properly be able to match the version against our update json (without needing a new version of ProjectE to do so.

**Comment by IchigoGames** [comment]
ok thank you :)

**Comment by pupnewfster** [comment]
Got a chance to look at this again and actually test it, and it is now fixed (including in released versions as it was an issue with the json file it queried), so I am going ahead and closing this.
