### ISSUE TITLE
Low Covalence Dust has no EMC

### ISSUE THREAD

**Issue by fleamclow** [sinkillerj/ProjectE#2115]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.16.5-PE1.0.1B.jar

Exact Forge version: 1.16.5-forge-36.1.2

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): no crashes yet

Steps to reproduce: Look at Low Covalence Dust

1.

What I expected to happen: That the Low Covalence Dust would have EMC as it is part of the mod

What happened instead: it does not have it

![Jre1 8 0_271 Screenshot 2021 04 08 - 16 04 23 98](https://user-images.githubusercontent.com/53278887/114050396-22177600-9884-11eb-9fc5-122e13731ddf.png)

**Comment by fleamclow** [comment]
Charcoal also has no EMC value

**Comment by teamaonn** [comment]
That would probably be the problem right there. Charcoal not having it. There could be a couple reasons why. Reason 1: Another mod may be conflicting with project e and have eliminated the value (had that a couple times with other mods). Reason 2: You set emc for charcoal to Zero.

**Comment by fleamclow** [comment]
So can I set the values manually ?
If that helps Im playing on All the Mods 6 for MC 1.16.5

**Comment by teamaonn** [comment]
yes you can

**Comment by teamaonn** [comment]
And yes, I had the same problem with the "All the Mods" setup. I dropped it down to just projecte.

**Comment by pupnewfster** [comment]
In config/ProjectE/mapping.toml disable Mekanism's pressurized reaction recipe mapper (which is now the new default as of Mekanism 10.1 anyway. I had not initially noticed it caused charcoal to lose its EMC value and thus had it on my default)
