### ISSUE TITLE
i can't find the 1.16.5 version on forge

### ISSUE THREAD

**Issue by Nessuno6** [sinkillerj/ProjectE#2116]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen:

What happened instead:

**Comment by pupnewfster** [comment]
https://www.curseforge.com/minecraft/mc-mods/projecte/files/3223221
