### ISSUE TITLE
Crashing My Game

### ISSUE THREAD

**Issue by RandomWeirdoThatGames** [sinkillerj/ProjectE#2117]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.16.5

Exact Forge version:1.16.5-36.1.4

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://pastebin.com/kAPAwKLN (it are 9 total crash logs)
Steps to reproduce:i installed a mod yesterday and it worked fine, today i installed 8 other mods and sinse it has been crashing my game, i reinstalled forge and the mod and it is still crashing my game, i forgot to add that it also crashes when it is the only mod i load

1.

What I expected to happen:that i could load my world without crashing

What happened instead:it crashed

**Comment by geek2002** [comment]
I'm having the same issue, any help would be appreciated

**Comment by Linguardium** [comment]
Failure message: Mod alexsmobs requires citadel 1.6.0 or above
		Currently, citadel is not installed

	Failure message: Mod minecolonies requires structurize 0.13.166-ALPHA
		Currently, structurize is not installed

Looks like user error. Check your mod requirements for the mods you are using
