### ISSUE TITLE
Crashing while starting up (NullPointerException at ToolTipEvent error)

### ISSUE THREAD

**Issue by Hoenn-Otaku** [sinkillerj/ProjectE#2118]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.12.2-PE1.4.1

Exact Forge version: 
forge-14.23.5.2854

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://pastebin.com/svCPX6uG

Steps to reproduce:

Exact steps unclear. Best understanding is as follows:
1) Nuclearcraft, GregTech Community Edition, Gregicality, ProjectE, ProjectE Integrations were present and functioning together. These seem to be the most relevant mods from the various crash logs.
2) Nuclearcraft and ProjectE Integrations removed, NC: Overhauled and QMD added. Game kept spitting out Gregicality as the issue.
3) After disabling and reenabling mods, ProjectE appeared to be the problematic mod.
4) Unknown steps occurred, pack functioned without PE. When PE was re-added, VanillaFix said it was PE. All PE addons disabled.

What I expected to happen:
I expected Minecraft to load

What happened instead:
Trying to load this modpack with PE enabled gives an error during the startup. Attached pastebin link suggests a NullPointerException wrt ToopTipEvent.

**Comment by Hoenn-Otaku** [comment]
ADDENDUM: All the mods being used were reinstalled on a new instance, including ProjectE. After disabling and re-enabling most of the mods that I imagine could have interfered, I set all the tooltip settings in the config file to false. It worked. Set all the tooltip configs to true, restarted Minecraft, didn't work.

**Comment by warjort** [comment]
The actual error appears to be some block implementing BlockFluidBase but returning null from getFluid()

````
		if (ProjectEConfig.misc.odToolTips)
		{
			for (int id : OreDictionary.getOreIDs(current))
			{
				event.getToolTip().add("OD: " + OreDictionary.getOreName(id));
			}
			if (currentBlock instanceof BlockFluidBase) {
// This is line 67:
				event.getToolTip().add("Fluid: " + ((BlockFluidBase) currentBlock).getFluid().getName());
			}
		}
````

The odToopTips flag is for the "ore dictionary" tooltips, so just setting that to false should fix your problem?

**Comment by Hoenn-Otaku** [comment]
Yep, setting the PE oredict tooltop to false fixed it. It seems to be conflicting with another mod that adds oredict tooltips.
