### ISSUE TITLE
EMC duplication 

### ISSUE THREAD

**Issue by RoHarV** [sinkillerj/ProjectE#2124]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version: Release 1.16.5-forge-36.1.4

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.take an item, like a diamond, and insert it into the burn slot

2.with an item sorting mod, press the sort button

3.item will appear in the left circle of the gui 

4.take item and insert into burn slot

What I expected to happen: nothing

What happened instead: the duplication of an item that wasn't supposed to happen

**Comment by pupnewfster** [comment]
Report to what ever mod is doing the sorting it isn't calling all the methods that are normally called when moving items from one slot to another.
