### ISSUE TITLE
Compatibility: /sethome & /home cease to exist after /reload

### ISSUE THREAD

**Issue by AngleWyrm10** [sinkillerj/ProjectE#2128]
ProjectE version:  1.16.5-PE1.0.1B
Forge version: 36.1.31

Steps to reproduce:
1. /reload
2. /home or /sethome

What I expected to happen: That /home would teleport me to my /sethome point
What happened instead: chat box declared both commands don't exist.

Exiting Minecraft and restarting returns the commands until the next use of /reload

This was using [QuickHomes](https://www.curseforge.com/minecraft/mc-mods/quickhomes) mod.

**Comment by pupnewfster** [comment]
Report to the QuickHomes mod it is an issue between them and vanilla/forge not us. If I had to guess they are using the `FMLServerStartingEvent` or whatever the pre 1.16 way/place was to register commands instead of the `RegisterCommandsEvent` so they don't register it again after reloading.
