### ISSUE TITLE
Ingame command for custom EMC guide

### ISSUE THREAD

**Issue by Lankoran** [sinkillerj/ProjectE#213]
Hi, i'm running a server for the ATLauncher pack Natural Magic, and there are a few modded items/blocks i'd like to add to the custom EMC list however my own coding skills are terrible, and i have no idea what information this code requires in order to sucseed. I was hoping someone wouldn't mind either pointing me to a guide, or putting some examples here for me to copy or work from? I'd really appreciate it. Its mainly Thaumcraft and Ars Magica i'm looking to add items for, but it would obviously be useful for multiple mods to know how to have them have EMC values. Thanks in advance for any assistance offered.

**Comment by theaigcaman** [comment]
what about something that is only UN not OD
