### ISSUE TITLE
Incorrectly announces New Update Available

### ISSUE THREAD

**Issue by AngleWyrm10** [sinkillerj/ProjectE#2132]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.16.5-PE1.0.1B

Exact Forge version: 36.1.7

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): N/A

Steps to reproduce:

1. Start a new single player world with version 1.16.5-PE1.0.1B loaded

What I expected to happen: World starts normally.

What happened instead: Chat announcement FROM v1.16.5-PE1.0.1B that a new ProjectE update is available: version 1.16.5-PE1.0.1B
![newversion](https://user-images.githubusercontent.com/55937426/123547829-2df23600-d717-11eb-9170-dc14be7a7045.png)

**Comment by Shibeoth-Ur** [comment]
Experiencing the same on Forge 36.1.32

**Comment by muqsit-0010** [comment]
Is there a config option to disable update announcement?
