### ISSUE TITLE
1.16.5-PE1.0.1B not full mod file

### ISSUE THREAD

**Issue by alemonplays** [sinkillerj/ProjectE#2134]
ProjectE version 1.16.5-PE1.0.1B: 

Exact Forge version: any

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): none

Steps to reproduce:

1. Download 1.16.5-PE1.0.1B and install it.

What I expected to happen:
Version 1.16.5-PE1.0.1B was installed and usable.

What happened instead:
Attached version is only an API and doesn't not contain full mod. 

Workaround was to extract version 1.16.5-PE1.0.1B and 1.16.5-PE1.0.0B, merging the newer into the old one and compacting it as a .jar again and the installing.

**Comment by pupnewfster** [comment]
Download the main jar not the API..? https://www.curseforge.com/minecraft/mc-mods/projecte/files/3223221

**Comment by alemonplays** [comment]
Yeah...now I saw that I downloaded the file from "additional files". (Facepalm) Sorry man. My bad.
