### ISSUE TITLE
creating dark matter armor in constructs armory forge crashes my game

### ISSUE THREAD

**Issue by dablade11577** [sinkillerj/ProjectE#2140]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version: 14.23.5.2855

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://paste.ee/p/a2i72

Steps to reproduce:

1. just create any kind of armor using dark matter in constructs armory

What I expected to happen: create an armor piece like chest plate

What happened instead: crashed my game only with dark matter

**Comment by pupnewfster** [comment]
Report to Constructs armory or whatever mod is adding dark matter as a material to tinkers. We are not the ones who add that, it is some other mod adding compat between the mods.
