### ISSUE TITLE
removeing EMC for ingot removes EMC from multiple recipes

### ISSUE THREAD

**Issue by ShadowFox414** [sinkillerj/ProjectE#2148]
MC: 1.12.2

mod ver: least

so im kinda having a issue its not a bug but i removed EMC for iron and all the other ingots because it was to op for what i wanted to do but all the other recipes for example iron sword would remove EMC so anything that had iron in its crafting recipe would have no EMC 

so my question is can i make it so only iron ingot and not the other recipes would have no EMC i tried looking in the config but no luck

**Comment by pupnewfster** [comment]
I think you would need to start by enabling pregenerated EMC (with ingots having EMC) so that everything generates with a value, and then remove the values for the ingots from the pregen file
