### ISSUE TITLE
1.16 Evertide speed boost after removal

### ISSUE THREAD

**Issue by SegaManX** [sinkillerj/ProjectE#2149]
On version ProjectE-1.16.5-PE1.0.0B 
I know that this is not the newest version but i didn't see it in the changelog so i thought i would report it anyways 
so discovered that when you have the evertide amulet in your offhand and step on water you can walk on it and have a speed boost but if you take it off while on water you can't walk on water anymore but the speed boost persists.

**Comment by EnderGamingFilms** [comment]
This works whenever the amulet is active and you move it to your inventory slots. Then you can just leave the water and have an infinite speed boost. You can even put the amulet in a chest and still have the speed buff.
