### ISSUE TITLE
ProjectE Quark Dupe Glitch

### ISSUE THREAD

**Issue by Gest511** [sinkillerj/ProjectE#2151]
Exact ProjectE version: ProjectE-1.16.5-PE1.0.1B

Exact Forge version: 36.2.0

Link to crash log: No crash log.

Steps to reproduce:
1. Take 2 of an item of your choice.
2. Place them into the Transmutation Table.
3. Take 1 out.
4. Click the extract button which is provided by Quark.
5. It will give you the item you put in without consuming any EMC.

What I expected to happen: For it to give me the previous item while consuming EMC.

What happened instead: It duplicated the item for free.

**Comment by pupnewfster** [comment]
Report this to quark they bypass calling some of the methods that are assumed to have been called for extraction based on what vanilla does.
