### ISSUE TITLE
ProjectE 1.16.5 non-functional alongside ModColonies 0.10.4 modpack. 

### ISSUE THREAD

**Issue by TheDeinonychus** [sinkillerj/ProjectE#2155]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.16.5-PE1.0.1B.jar

Exact Forge version:36.1.31

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): No crash, seemingly an incompatibility. 

Steps to reproduce: Install ProjectE into the ModColonies 0.10.4 modpack. projectex-1605.2.0-build.3.jar and projecte-integration-1.16.5-4.1.6.jar also installed. 

1.

What I expected to happen: Items to have EMC values and function in the Transmutation table. 

What happened instead: No items in game (even vanilla blocks) have an EMC value, and can not be placed into the Transmutation Table. Collectors do not collect EMC. Basically the mod does not function despite it's blocks and items showing up. 

ProjectE-1.16.5-PE1.0.1B.jar functions normally in a vanilla install of Minecraft 1.16.5 with just the required Forge version and the two previously mentioned mods, so I know it's not a problem with ProjectE itself. However, there are no listed incompatibilities, so I have no idea where to start to narrow down what could possibly be causing it to not function at all once installed in the modpack. 
[latest.log](https://github.com/sinkillerj/ProjectE/files/7360951/latest.log)

**Comment by pupnewfster** [comment]
Looks like a bug in ProjectE Integration, report it to them
```
java.lang.NoSuchFieldError: DEPLOYING
	at com.tagnumelite.projecteintegration.addons.CreateAddon$CreateDeployerApplicationMapper.canHandle(CreateAddon.java:370) ~[?:4.1.6]
```
