### ISSUE TITLE
[1.16.5] Repair Talisman does not repair Tinkers construct items

### ISSUE THREAD

**Issue by LuciusV** [sinkillerj/ProjectE#2160]
Exact ProjectE version: 1.16.5-PE1.0.1B

Exact Forge version: 36.2.8
Tinkers Construct: 3.1.3.271
Mantle: 1.6.127

Steps to reproduce:

1. Equip repair talisman and get some damaged TC tool

What I expected to happen:

Tinker's item slowly repaired as usual

What happened instead:

It is unaffected

**Comment by pupnewfster** [comment]
This isn't a bug, we respect the "is repairable" flag that mods can specify on items. See #1917 for slightly more info (and probably a variety of other closed issues about this as this "issue" has been reported many times).
