### ISSUE TITLE
1.16.5 watch of flowing time doesn't work on crops

### ISSUE THREAD

**Issue by Oniisancon** [sinkillerj/ProjectE#2165]
both PE1.0.1B and PE1.0.0B. watch of flowing time doesn't work on crops. I tried using the mod alone, still doesn't work. I tried putting on pedestal and activating it, tried normally putting in hotbar, still doesn't work. note: i know how to properly use watch, have been using it since 1.12
what i expected to happen : crops grow faster
what happened : nothing happens

**Comment by pupnewfster** [comment]
Plant growth gets [sped up](https://github.com/sinkillerj/ProjectE/blob/mc1.16.x/src/main/java/moze_intel/projecte/gameObjs/items/rings/TimeWatch.java#L153) by the harvest goddess band in the pedestal, not the watch of flowing time. From what I can tell this was also [the case](https://github.com/sinkillerj/ProjectE/blob/mc1.12.x/src/main/java/moze_intel/projecte/gameObjs/items/TimeWatch.java#L238) in 1.12.

**Comment by Oniisancon** [comment]
I remembered how I used to speed up plants in minecraft 1.12.2, I was using the watch to speed up sprinkler in cyclic, sorry for bothering.
