### ISSUE TITLE
Crafting recipe doesn't show

### ISSUE THREAD

**Issue by DaanSprinkhaan** [sinkillerj/ProjectE#2166]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  ProjectE-1.15.2-PE1.0.4.jar

Exact Forge version: 0.188.3.1

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): It doesnt crash

Steps to reproduce:

1.

What I expected to happen: For it to show crafting recipes

What happened instead: It doesnt show it because minecrafts craft gui is the bedrock one.

**Comment by sinkillerj** [comment]
Unclear issue and unsupported version. Please use JEI for recipe lookups.
