### ISSUE TITLE
 (1.12.2) ProjectE "Unfamiliar item" "You dont know how to use this yet"

### ISSUE THREAD

**Issue by vxpxx** [sinkillerj/ProjectE#2167]
Exact ProjectE version: version is a PE1.4.1

Exact Forge version: Forge - 14.23.5.2860

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): Unfortunately, i cannot get the crash log here because all the paste websites cant handle how big the file is. But i can assure you i launched Sky Factory 4 and put projecte inside the mods folder with the other Sky Factory 4 mods, there might be some mods in there that just break project e but i just want to know what breaks it. 

Steps to reproduce:

1.All i did was download the curseforge application and overwolf, i downloaded Sky Factory 4, then i launched SF 4 then i made a world with the mod pack and played on it for a little while, then i downloaded ProjectE version PE1.4.1 for mc version 1.12.2 and added it into the sky factory 4 mods folder with all the other sky factory 4 mods then i got met with the issue.

What I expected to happen: ProjectE would work perfectly fine with almost every item having an emc value and projecte items working

What happened instead: ProjectE loaded in the mods list but i cannot use or interact with the items project e had into it, plus no items had an emc value. But commands for projecte still worked but adding emc to an item did not. 
![Screenshot_1](https://user-images.githubusercontent.com/96914197/147826756-7d293ff6-5436-4619-a96e-e059a5090fc8.png)

**Comment by pupnewfster** [comment]
Skyfactory stages projecte to be the second playthrough I believe, take it up with them or try and use commands to give yourself that gamestage.

**Comment by vxpxx** [comment]
yeah but what is the command to give me that gamestage if you mind me asking?

**Comment by vxpxx** [comment]
> Skyfactory stages projecte to be the second playthrough I believe, take it up with them or try and use commands to give yourself that gamestage.

yeah but what is the command to give me that gamestage if you dont mind me asking?

**Comment by pupnewfster** [comment]
No idea I haven't used gamestages before, best bet is looking on gamestage's curseforge page or wiki. There is a slight chance it is `/gamestage grant <player> project_e` but I wouldn't count on it

**Comment by vxpxx** [comment]
> No idea I haven't used gamestages before, best bet is looking on gamestage's curseforge page or wiki. There is a slight chance it is `/gamestage grant <player> project_e` but I wouldn't count on it

Ok thanks i will look into it

**Comment by vxpxx** [comment]
> No idea I haven't used gamestages before, best bet is looking on gamestage's curseforge page or wiki. There is a slight chance it is `/gamestage grant <player> project_e` but I wouldn't count on it

hey i fixed it, all i had to do is type in a command as /gamestage add <my username> project_e and it works :D

**Comment by vxpxx** [comment]
> No idea I haven't used gamestages before, best bet is looking on gamestage's curseforge page or wiki. There is a slight chance it is `/gamestage grant <player> project_e` but I wouldn't count on it

hey i fixed it, all i did was use a command as /gamestage add "my username" project_e and it works :D
