### ISSUE TITLE
Enchantments

### ISSUE THREAD

**Issue by lovelypython** [sinkillerj/ProjectE#2174]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:1.16.5

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): none

Steps to reproduce:

1.

What I expected to happen:bow(or maybe somethings else)with enchantment EMC wasn't same with no enchantment

What happened instead:EMC was the same

**Comment by pupnewfster** [comment]
`config/ProjectE/processing.toml`

**Comment by pupnewfster** [comment]
If you are on a server you will need to edit it on the server. Also if not you need it to generate (which either for a server is start the server or for single player join a single player world).
