### ISSUE TITLE
Cant set EMC value over a certain number

### ISSUE THREAD

**Issue by XayCraft** [sinkillerj/ProjectE#2175]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.12.2-PE1.4.1.jar

Exact Forge version: Forge - 14.23.5.2859

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): (No recent crash log)

Steps to reproduce:

1. 

What I expected to happen: To set the EMC value to the one I put down

What happened instead: errored out

![image](https://user-images.githubusercontent.com/82598295/153766673-8f89edd3-807f-48e0-addf-caa2b132f488.png)

**Comment by pupnewfster** [comment]
Max EMC value is `9,223,372,036,854,775,807`
