### ISSUE TITLE
Suggestion: EMC Erasor (Smiting table upgrade), and a Link in Curseforge for Github

### ISSUE THREAD

**Issue by Thunder-Nova** [sinkillerj/ProjectE#2176]
Would it be possible to have an item when used in a smiting table it removes the EMC. (Somehow I had in mind the name: "EMCrasor")

This is basically giving a way for players to not accidently deposit items such as portable storage, tools, and such with enchantments or contents, to not get dumped into the alchemy table.

--------

Plus went to curseforge, yet there is no link to github. Unless that was intentional, but just letting you guys know.

**Comment by sinkillerj** [comment]
We typically do not add new content, this is left to addon authors. Regarding a GitHub link this already exists.
