### ISSUE TITLE
How to set EMC via tags (such as forge:fruits for Pam's Harvestcraft 2)?

### ISSUE THREAD

**Issue by darthvader45** [sinkillerj/ProjectE#2177]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version: PE1.0.1B

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): N/A

Steps to reproduce:

1. N/A

What I expected to happen: /projecte setemc forge:fruits 128 sets any item with that tag to 128 EMC

What happened instead: Sets minecraft:air with this tag to 128 EMC, which does nothing.

**Comment by pupnewfster** [comment]
You are missing a `#` at the start of the tag. The standard that Mojang has set for how to reference tags is `#<location>` so in your case it would be `#forge:fruits`

**Comment by darthvader45** [comment]
Thanks.  Now it works, I'll remember to set all the tags up as they were back when OreDictionary was a thing.
