### ISSUE TITLE
NBT Overload with Alchemical Bags

### ISSUE THREAD

**Issue by dankada** [sinkillerj/ProjectE#2178]
Exact ProjectE version: 1.7.10-PE1.10.1

Exact Forge version: 10.13.4.1614

Link to crash log : [justpaste.it/9gzv9](justpaste.it/9gzv9) 

Steps to reproduce:

1. Get or make an item with alot of NBT tags, in this case, a fully sharpened rapier (quartz) with looting 3 (lapis) from tinkers construct (TConstruct-1.7.10-1.8.8.build991) made with a Manyullyn blade, obsidian crossbar, and a Thaumium tool rod from Thaumcraft (1.7.10_4.2.3.5), a pickaxe with cobalt head, obsidian base and a thaumium tool rod, with auto-repair (ball of moss), fortune 3 (lapis) and full haste (redstone) using all three slot upgrades (nether star, enchanted golden apple and a block of diamond, and a diamond with a block of gold).
2. Put them in an alchemical bag, I placed mine in the white one.
3. Disconnect, then reconnect to the server, as this was in multiplayer.

What I expected to happen: For the game to keep working

What happened instead: Upon joining, in less than a second, get disconnected with text on the screen saying "Fatal error ocurred, this connection is terminated"

**Comment by sinkillerj** [comment]
The 1.7 version of the mod is no longer supported and will not receive further updates.
