### ISSUE TITLE
Transmutaion Table forget all my learned items after leave the game

### ISSUE THREAD

**Issue by DibluzziAlamanno** [sinkillerj/ProjectE#2180]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.18.2-PE1.0.0

Exact Forge version: Forge-40.0.31

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce: 

1. Learn something on transmuation table
2. Leave the game
3. Rejoin the game
4. Watch the transmutation table

What I expected to happen: See my learned items

What happened instead: See nothing on the transmutation table, it forget all learned items

**Comment by ashvn** [comment]
Same issue forge version 40.0.19 though

**Comment by BulletDave** [comment]
I'm also experiencing this issue

ProjectE: 1.18.2-PE1.0.0
Forge: 40.0.32

This is happening in my single player world.
If it is worth mentioning, I recently migrated my account from Mojang to Microsoft.

**Comment by pupnewfster** [comment]
Fixed in 1.0.1
