### ISSUE TITLE
[1.18.2] Incompatible with SurvivalPlus

### ISSUE THREAD

**Issue by Baggytrousers27** [sinkillerj/ProjectE#2181]
ProjectE-1.18.2-PE1.0.0
SurvivalPlus-1.18.2-0.1.6c
Forge 40.0.32

[Crash log](https://pastebin.com/Nm8gkunM)

Something changed about raw tin?

**Comment by coolsimulations** [comment]
Fixed with https://github.com/coolsimulations/SurvivalPlus/commit/79ee1d854bbe4082c08948bbf9cdcaaeb1e249e9. Version 0.1.6d is on CurseForge.
