### ISSUE TITLE
all emc values gone 1.18.2

### ISSUE THREAD

**Issue by x8407** [sinkillerj/ProjectE#2182]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.18.2-PE1.0.0.jar (Initial 1.18.2 rlease)

Exact Forge version: 40.0.32

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): its not a crash log but a bug

Steps to reproduce: I have no clue

What I expected to happen: All items were normal with emc values

What happened instead: Literally nothing has an emc value

**Comment by x8407** [comment]
https://pastebin.com/Um2i44S3 here is the latest log

**Comment by jkwphysics** [comment]
I'm also seeing no EMC values, but only for server. I don't see the entries in the log posted above though.  Client single player seems to be fine. Values are missing from tooltip, and after cheating in a trans table, it accepts none of the vanilla items that should have values.

**Comment by x8407** [comment]
Is there anyway to fix it?

**Comment by jkwphysics** [comment]
> Is there anyway to fix it?

not on our end. it's fixed in an upcoming release though

**Comment by pupnewfster** [comment]
Fixed in 1.0.1
