### ISSUE TITLE
Mekanism EMC Values Missing

### ISSUE THREAD

**Issue by LazarusCaine** [sinkillerj/ProjectE#2194]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.18.2-PE1.0.1

Exact Forge version:1.18.2-40.1.0

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. I installed both mods on my server.

What I expected to happen: I expected to find emc values on items from the Mekanism mod (Version: 1.18.2-10.2.0.459).

What happened instead: Mekanism items do not have an emc value

**Comment by pupnewfster** [comment]
This is due to a bug on Mekanism's end from when I was rewriting some stuff there and will be fixed whenever Mekanism 10.2.1 is released
