### ISSUE TITLE
I was using the Heroes Expansion Mod by Lucraft. And whenever I put in the LV Capacitor into the Transmutation Table. My game would crash. Do you know how to fix this?

### ISSUE THREAD

**Issue by Anbrew437** [sinkillerj/ProjectE#2196]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen:

What happened instead:

**Comment by sinkillerj** [comment]
Invalid issue, required template information not provided. 

Please contact the creator of the mod with a log, it is likely that they do not properly handle missing NBT data.
