### ISSUE TITLE
dark matter pedestal cant be picked up

### ISSUE THREAD

**Issue by OsirisKing** [sinkillerj/ProjectE#2198]
All The Mods 7 1.18.2 on the curse launcher.

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  [ProjectE-1.18.2-PE1.0.1.jar
Mar 28, 2022

Exact Forge version: 40.1.20

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):  No crash

Steps to reproduce:

1. placed it down, added flowing time, removed flowing time to move the setup and couldnt remove the pedestal.

What I expected to happen: mined it with a pickaxe, with my hand, shift right/left clicked, left and right clicked.

What happened instead: nothing happened, it wouldnt move from 0%

**Comment by pupnewfster** [comment]
In 1.18 it was changed to be similar to other dark matter and red matter blocks and require being mined with a matter tool (dark matter or red matter)
