### ISSUE TITLE
Not loading EMC value

### ISSUE THREAD

**Issue by pagodera** [sinkillerj/ProjectE#2211]
Create a modpack similar to all the mods 1.18.2 and put Projecte mod, but the value is not working...

**Comment by pagodera** [comment]
trying to see if some mod is causing this... if anyone knows tell me

**Comment by Adam022695** [comment]
I am having the same issue

**Comment by pupnewfster** [comment]
Not much we can do without the latest log of the server (or single player log, whatever it is having issues on). Odds are some other mod is breaking the recipe mappers, if I had to guess based on reports others have given lately ProjectE Integration or whatever the mod is called has some broken mappers related to PNC

**Comment by pagodera** [comment]
I'll try remove pneumatic craft, if don´t work I will send the log

**Comment by pagodera** [comment]
@Adam022695 was pnemuaticcraft... i´m using the previous version and it-s normal

Ty @pupnewfster

**Comment by Angelus022695** [comment]
@pagodera which previous version are you using?
