### ISSUE TITLE
emc commands to set values to items that don't have emc are broken

### ISSUE THREAD

**Issue by dragontuar** [sinkillerj/ProjectE#2219]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): projectE-1.18.2-PE1.0.1.jar

Exact Forge version:

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): not a crash as commands are missing

Steps to reproduce:

1.

What I expected to happen: use the commands to set custom values for items that do not have values

What happened instead: not accessible commands 

i would like to suggest adding an example structure into the configuring emc to show how to structure the entry for the custom_emc.json file

**Comment by pupnewfster** [comment]
What exactly are you using for the command as it is case sensitive. And if you are in single player do you have cheats enabled? If you are on a server are you an op?
