### ISSUE TITLE
Stone Transmutation Table crashes server

### ISSUE THREAD

**Issue by celias8199** [sinkillerj/ProjectE#2223]
https://pastebin.com/KS7q44RJ

running ProjectE-1.16.5-PE1.0.2
Forge v36.2.39

Please help, anytime someone on my server opens a transmutation table there is an instant crash.

**Comment by celias8199** [comment]
After poking around a bit I found out that the normal transmutation table works, but the Stone Transmutation Table crashes the server still.

**Comment by pupnewfster** [comment]
That is not part of this mod
