### ISSUE TITLE
Can't break Dark Matter Pedestal

### ISSUE THREAD

**Issue by HappyHippoEaters** [sinkillerj/ProjectE#2224]
**Tickets that do not conform to this template will be closed without comment**

ProjectE-1.18.2-PE1.0.1

Forge-40.1.68

No associated Crash log (game did not crash)

Steps to reproduce:

1. I Placed on Pedestal on Glowstone
2. I put in Watch of Flowing time
3. I Activated It
4. I left it for a few minutes
5. I tried to use a pickaxe to pick it up

What I expected to happen:
it to break and I would get the Pedestal back
What happened instead:
I sat for about 5 minutes (with a Supremium Tinkers Pick, and haste II) wondering why it wasn't breaking

I am leaving this link here, since it won't accept Video
https://youtu.be/1UgoFcr_MC0

**Comment by pupnewfster** [comment]
You need to use a matter pick to break matter based blocks.

**Comment by HappyHippoEaters** [comment]
I guess that makes sense, kinda wish there was a config to make it so any pick could work, at least other people can see this thread now, and not feel like an idiot like me.
