### ISSUE TITLE
1.19.1戴上深渊头盔就会崩溃

### ISSUE THREAD

**Issue by ALone1Soul** [sinkillerj/ProjectE#2230]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:
[错误报告-2022-8-29_16.38.39.zip](https://github.com/sinkillerj/ProjectE/files/9443009/-2022-8-29_16.38.39.zip)

1.

What I expected to happen:

What happened instead:

**Comment by pupnewfster** [comment]
stepsword.mahoutsukai.handlers.ServerHandler.potionFinish looks to be some mod likely called mahoutsukai or something
