### ISSUE TITLE
Unable to join discord?

### ISSUE THREAD

**Issue by CobaltWuffs** [sinkillerj/ProjectE#2240]
I just tried to connect to the discord as I wanted to ask a question, I was able to connect but upon trying to click the reaction specified at the bottom of the rules it did nothing, I left and rejoined which then allowed me to view the channels after clicking the same reaction again, but then I was kicked for some reason, and now I am unable to connect again.

**Comment by sinkillerj** [comment]
Maybe next time you will actually read those rules before you click.
