### ISSUE TITLE
[main/ERROR] [projecte/]: Error calculating EMC values

### ISSUE THREAD

**Issue by xXjojojXx** [sinkillerj/ProjectE#2241]
I put a modpack as soon as the server starts I get the error message see link would be cool if you could help me

forge-1.18.2-40.1.80

Patchouli-1.18.2-71.1

https://logpaste.com/K5S3xuty

https://www.curseforge.com/minecraft/modpacks/xx-unlimited-sky-xx

I linked the modpack to reproduce the error

**Comment by pupnewfster** [comment]
looks to be a bug in `projecte integration`
