### ISSUE TITLE
The mod makes minecraft not respond

### ISSUE THREAD

**Issue by Mastercraft2018** [sinkillerj/ProjectE#2243]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.16.5 (All the different files)

Exact Forge version: 36.2.39

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): don't know how to access crash log (Exit code -805306369 in case it helps)

Steps to reproduce:
1. open launcher
2. start the game with the mod installed
3. create a new world

What I expected to happen: to enter the world and start playing.

What happened instead: while entering the world Minecraft stopped responding and I had to close it.

**Comment by sinkillerj** [comment]
Without logs, we cant help you.
