### ISSUE TITLE
mk5 crashing with mk3

### ISSUE THREAD

**Issue by SpeedRider** [sinkillerj/ProjectE#2244]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.4.1

Exact Forge version:forge-14.23.5.2855

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://pastebin.com/gsjDcX0b
Steps to reproduce:

1.
![image](https://user-images.githubusercontent.com/17522328/194547932-81ab5c4d-7fe4-4050-8790-df801043906a.png)
I placed a mk5 inside 5 mk3
What I expected to happen:
I would get more emc 
What happened instead:
crahsed

**Comment by pupnewfster** [comment]
Report to whatever mod is adding the mk5
