### ISSUE TITLE
Transmutation table and tablet crash my game every time i open it

### ISSUE THREAD

**Issue by korearts** [sinkillerj/ProjectE#2246]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.18.2-PE1.0.1.jar

Exact Forge version: 40.1.84

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):  
[crash-2022-10-28_11.13.18-client.txt](https://github.com/sinkillerj/ProjectE/files/9890965/crash-2022-10-28_11.13.18-client.txt)

Steps to reproduce:

1.  open the transmutation table
2. game crashes

What I expected to happen: was for it to allow me access to my contents

What happened instead: my game crashed

**Comment by pupnewfster** [comment]
Looks like some bug in geckolib or something, no idea as we don't use that, though maybe some other mod you have is using it for rendering their item or something?
