### ISSUE TITLE
Unable to learn items in transmutation table

### ISSUE THREAD

**Issue by pchoiniere** [sinkillerj/ProjectE#2250]
**Tickets that do not conform to this template will be closed without comment**

ProjectE version: 1.18.2-PE1.0.1

Exact Forge version: 40.1.73

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline):  no crash log

Steps to reproduce:

1. Downloaded Mechanical Mastery (tried deleting mod pack and reinstalled also)
2. Created a new world.
3. Opened transmutation table and can not learn/store wood, saplings or dirt.
Note: on another friend's computer the above steps work fine.

What I expected to happen: Expected that the table would learn and store the EMC of wood, saplings and dirt.

What happened instead: Opened the table and table does not responded to anything I try.

**Comment by BratrilliantG7** [comment]
It sounds like it may be an issue with your modpack installation. I'm playing the very same one and everything works fine.

When you hover over the items, do they list an EMC value under their name?
If so, does holding shift and clicking them with the table open not EMC/learn them?
Have you altered your modpack installation at all (such as installing extra mods like Optifine)?

You can also try doing a fresh install of the modpack to see if that fixes the issue.

**Comment by pchoiniere** [comment]
Turns out it Microsoft updated the launcher and it broke it.  Curse fixed their launcher and it works fine now.
