### ISSUE TITLE
Missing EMC values from ProjectE items

### ISSUE THREAD

**Issue by Taissir-FB** [sinkillerj/ProjectE#2263]
I play on minecraft 1.18.2 and the version of projectE is 1.0.1 and I have problem with EMC values their are missing and the transmitation table is empty and I can't put any item on it I don't know the problem I triede to play in other worlds the same problem happend I use the command /projecte dumpmissingemc in minecraft and it show that I have more than 20000 item are missing EMC values and it said printing to server log and nothink happend please help me

**Comment by pupnewfster** [comment]
Please provide your latest log (you can skip running dumpmissingemc). My guess is some mod you have installed is breaking mapping of emc values.

**Comment by Taissir-FB** [comment]
Yah maybe I guess but I'm playing with many mods please if you know any mods can break mapping of emc values tell me and here is the log file [2023-01-02-2.log.gz](https://github.com/sinkillerj/ProjectE/files/10351528/2023-01-02-2.log.gz)

**Comment by pupnewfster** [comment]
Well that's a new one...  actually is night config that occasionally corrupts the config files happening to corrupt the `config/ProjectE/mapping.toml` file. Deleting it/resetting it to the default the modpack ships if it ships one should hopefully fix the issue,

**Comment by Taissir-FB** [comment]
Thank you so much for helping me I fix it I don't know how but I change the version I was played with it and I remark that I was playing with 40.1.76 (not the latest) I update it to the latest version 40.2.0 and maybe the config/ProjectE/mapping.toml got updated maybe it was helpful or the reason of it and the issue has been fixed. And finally thank you again for your services and have a good day.

**Comment by LarryBOSS** [comment]
i have the same issue. i dont have any EMC for ores or other items and i dont know why. i play with the create mod, modpackname: Project Architect 2
latest log here:
[latest.log](https://github.com/user-attachments/files/16738020/latest.log)

its says roundabout 4,5k items with no EMC

pls Help

**Comment by littleseapickle** [comment]
had the same issue, what worked for me is going into the modpacks folder > config > ProjectE > custom_emc and deleting the first entry where it said emc = 0
hope this helps
