### ISSUE TITLE
World transmutations involving fluids are broken in 1.18

### ISSUE THREAD

**Issue by loldev69** [sinkillerj/ProjectE#2273]
Exact ProjectE version : ProjectE-1.18.2-PE1.0.1

Exact Forge version: 40.2.0

Relevant portion of error log: 

> [me.je.co.gu.re.la.RecipeLayout/]: Error caught from Recipe Category: projecte:world_transmutation
>java.lang.NoSuchFieldError: FLUID
>	at moze_intel.projecte.integration.jei.world_transmute.WorldTransmuteRecipeCategory.lambda$setRecipe$1(WorldTransmuteRecipeCategory.java:93) ~[ProjectE-1.18.2-PE1.0.1.jar%23137!/:1.0.1] {re:classloading}
>	at com.mojang.datafixers.util.Either$Right.ifRight(Either.java:109) ~[datafixerupper-4.1.27.jar%2323!/:?] {}
>	at moze_intel.projecte.integration.jei.world_transmute.WorldTransmuteRecipeCategory.lambda$setRecipe$2(WorldTransmuteRecipeCategory.java:93) ~[ProjectE-1.18.2-PE1.0.1.jar%23137!/:1.0.1] {re:classloading}
>	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}

Steps to reproduce:

1. Launch the game with ProjectE and JEI installed.
2. Check the world transmutation recipes for the philosopher's stone.

What I expected to happen: all four world transmutation recipes involving fluids (water from/to ice, and lava from/to obsidian) are displayed correctly in JEI.

What happened instead: all four world transmutation recipes involving fluids fail to display correctly in JEI, with empty spots in place of the relevant block icons.
However, the transmutations themselves still function properly.

**Comment by pupnewfster** [comment]
Use the latest version of JEI 9 instead of JEI 10 as JEI 10 made breaking API changes

**Comment by loldev69** [comment]
If we're talking workarounds, disabling the affected transmutations is much less hassle than having to deal with all the bugs JEI fixed in the 10.x versions.
The crafttweaker interface is good enough for that, but #2221 would be nice to have.
