### ISSUE TITLE
Create 1.18.2-0.5.1b makes item's emc values null/undefined.

### ISSUE THREAD

**Issue by clcment446** [sinkillerj/ProjectE#2281]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version: forge 40.2.4
Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
    https://paste.md-5.net/upetaseway.sql
Steps to reproduce: 

1.install latest create version.

What I expected to happen: create items to get emc values. Already present custom emc values to work fine.

What happened instead: Items that had emc before now have undefined emc, even vanilla items.

**Comment by pupnewfster** [comment]
Report to projecte integration
