### ISSUE TITLE
Project Integrations mod removes all emc values

### ISSUE THREAD

**Issue by PlasmaShotGaming** [sinkillerj/ProjectE#2286]
When i boot up minecraft with the projectE integrations mod all the emc values from project E dissapear but when i remove the mod every thing works normally btw im using minecraft 1.18.2 
how do i solve the issue without removing the mod

**Comment by PlasmaShotGaming** [comment]
im using version 1.18.2-5.4.6

**Comment by sinkillerj** [comment]
Talk to the author, not us.
