### ISSUE TITLE
All items have disappeared from Transmutation table. EMC value remains

### ISSUE THREAD

**Issue by DJDrWright** [sinkillerj/ProjectE#2288]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  ProjectE-1.16.5-PE1.0.2

Exact Forge version: 36.2.34

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): There was not a crash

Steps to reproduce:

1. Playing as normal
2. Save my game
3. Come back, load save
4. All items in table gone but EMC value retained.

What I expected to happen: All items to still be in table.

What happened instead: All learned items disappeared from table.

I can reinsert items to learn them again. This is in the modpack Mystical Block 2.4.1

**Comment by notedigi** [comment]
Any fix for this? i have this bug but i cant insert anything in the table, all items are gone as well but i still have 96Q emc

**Comment by sinkillerj** [comment]
Mystical Block is not supported at this time. If the modpack author believes that this issue our fault, please have them reach out with clarification on why.
