### ISSUE TITLE
EMC values on items are lost when relogging a world loosing all my transmutation table progress after relaunching minecraft. It happend in a modpack and many people are having it and the modpack owner says it's a modside issue. the version is 1.16.5

### ISSUE THREAD

**Issue by piersonDenning** [sinkillerj/ProjectE#2293]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen:

What happened instead:

**Comment by sinkillerj** [comment]
Follow the template next time.
