### ISSUE TITLE
EMC values on items are lost when relogging a world loosing all my transmutation table progress after relaunching minecraft.

### ISSUE THREAD

**Issue by PepeSchmidt** [sinkillerj/ProjectE#2294]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.16.5-PE1.0.2

Exact Forge version: 36.2.34

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): the game doesn't crash

Steps to reproduce:
1. install mystical block version 2.5
2. make a new world
3. try to place an item into the transmutation table

What I expected to happen:
item being learned

What happened instead:
no item seems to have an emc value and no item cant be inserted into the transmutation table

4 days ago I started a new world and there it worked until today
on my older world I can insert items into the table and everything works but if I reconnect to my world all the items I've learned are gone

Edit:
Now I can't insert any items into the transmutation table

**Comment by sinkillerj** [comment]
Mystical Block is not supported at this time. If the modpack author believes that this issue our fault, please have them reach out with clarification on why.
