### ISSUE TITLE
Seems to be incompatible with the "Mekanism mod" and there will be no EMC value

### ISSUE THREAD

**Issue by dqpzero** [sinkillerj/ProjectE#2304]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.20.1-PE1.0.0B

Exact Forge version:1.20.1-forge47.1.43

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/qbXQ3UJY

Can't get more than 512kb, I can only take a screenshot of the wrong part

There is no EMC value, and it is not possible to add an EMC value via a directive

**Comment by pupnewfster** [comment]
Oops, I will try to get to fixing it sometime in the next few days. Mekanism has to update to the changed api. In the meantime you should be able to disable the mappers related to Mekanism in config/ProjectE/mappers.toml or something along those lines.

**Comment by dqpzero** [comment]
> 哎呀，我会在接下来的几天内尝试修复它。Mekanism 必须更新到更改后的 api。同时，您应该能够在 config/ProjectE/mappers.toml 或类似的东西中禁用与 Mekanism 相关的映射器。

ok,I`m looking forward to it

**Comment by tsargoth** [comment]
> Oops, I will try to get to fixing it sometime in the next few days. Mekanism has to update to the changed api. In the meantime you should be able to disable the mappers related to Mekanism in config/ProjectE/mappers.toml or something along those lines.

What is the syntax for this file. Mine is blank.

**Comment by tsargoth** [comment]
Got the file on Discord. Thank you so much!

**Comment by Staegrin** [comment]
> Got the file on Discord. Thank you so much!

Could you post it here?
Having the same problem with there being no EMC values.
![2023-11-12_18 59 04](https://github.com/sinkillerj/ProjectE/assets/8494635/4c3ccb49-5db4-4c1a-8573-bc3f764f21c0)

![2023-11-12_18 59 07](https://github.com/sinkillerj/ProjectE/assets/8494635/36100014-6922-4bf7-b89f-3db46e1d3076)

**Comment by tsargoth** [comment]
> Could you post it here?
> Having the same problem with there being no EMC values.
[mapping.zip](https://github.com/sinkillerj/ProjectE/files/13329432/mapping.zip)

**Comment by pupnewfster** [comment]
Should be fixed in Mekanism 10.4.4+
