### ISSUE TITLE
[1.20.1] Search field don't work Transmutation Table/Tablet

### ISSUE THREAD

**Issue by SickElmo-GH** [sinkillerj/ProjectE#2306]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):
ProjectE-1.20.1-PE1.0.0B

Exact Forge version:
47.2.5 (older version too)

Steps to reproduce:

1. Open Transmutation Table / Tablet
2. Try to enter the search field

What I expected to happen:
You can enter the search field in the Transmutation Table/Tablet and search for something

What happened instead:
Nothing

**Comment by lucasbr2405** [comment]
This is not working the EMC version and the Tablet

**Comment by Jim3535** [comment]
Having the same issue here, as well as others on discord

**Comment by ridivagyokcso** [comment]
main/java/moze_intel/projecte/gameObjs/gui/GUITransmutation
line: 157 (mouseClicked Function)
 - missing  this.textBoxFilter.setFocused(true);

I wrote here for information only.
Based on this, this problem can be easily fixed.

**Comment by lucasbr2405** [comment]
> main/java/moze_intel/projecte/gameObjs/gui/GUITransmutation line: 157 (mouseClicked Function)
> 
> * missing  this.textBoxFilter.setFocused(true);
> 
> I wrote here for information only. Based on this, this problem can be easily fixed.

How do you make this correction? where to enter?

**Comment by aqua-air** [comment]
Same issue, how to resolve?

**Comment by ridivagyokcso** [comment]
@lucasbr2405
@fourthhouse 

This bug has been fixed. As I looked at websites, it has not been published yet. So right now you can compile the mod for yourself. And it should be like this:
For the sake of simplicity, I will use the C:/Project-mc1.20.x folder in the example.

- Download source code
- Download JDK17
- Unzip the ProjectE-mc1.20.x folder to the C:/ drive (this is how we get access to C:/Project-mc1.20.x)
- Open the command prompt and use the cd command to go to the downloaded source code folder. (example: cd C:/Project-mc1.20.x)
- Then type this: gradlew build
- If the build is successful, you should see: BUILD SUCCESSFUL in Xs
- You can find the finished jar file here: C:\Project-mc1.20.x\build\reobfShadowJar\output.jar

**Comment by lucasbr2405** [comment]
> @lucasbr2405 @fourthhouse
> 
> Este bug foi corrigido. Conforme olhei nos sites, ainda não foi publicado. Então agora você pode compilar o mod você mesmo. E deveria ser assim: Para simplificar, usarei a pasta C:/Project-mc1.20.x no exemplo.
> 
> * Baixe o código-fonte
> * Baixar JDK17
> * Descompacte a pasta ProjectE-mc1.20.x na unidade C:/ (é assim que obtemos acesso a C:/Project-mc1.20.x)
> * Abra o prompt de comando e use o comando cd para ir para a pasta do código-fonte baixado. (exemplo: cd C:/Projeto-mc1.20.x)
> * Então digite isto: gradlew build
> * Se a compilação for bem-sucedida, você deverá ver: BUILD SUCCESSFUL em Xs
> * Você pode encontrar o arquivo jar finalizado aqui: C:\Project-mc1.20.x\build\reobfShadowJar\output.jar

Você consegue mandar o arquivo por aqui ,tentei isto mas não deu ,devo estar fazendo algo errado pq sou leigo no assunto

**Comment by ridivagyokcso** [comment]
[ProjectE-1.20.1-PE1.0.0B - Unofficial build.zip](https://github.com/sinkillerj/ProjectE/files/13431989/ProjectE-1.20.1-PE1.0.0B.-.Unofficial.build.zip)

I uploaded it. Due to limitations, I could only upload it in a zip file, so unpack it first.

**Comment by lucasbr2405** [comment]
man you are very good, thank you so much

> [ProjectE-1.20.1-PE1.0.0B - Unofficial build.zip](https://github.com/sinkillerj/ProjectE/files/13431989/ProjectE-1.20.1-PE1.0.0B.-.Unofficial.build.zip)
> 
> I uploaded it. Due to limitations, I could only upload it in a zip file, so unpack it first.

man you are very good, thank you so much

**Comment by aqua-air** [comment]
Yeah but is curseforge going to allow a third party download into my modpack? why not just release it on forge

**Comment by barkerm1031** [comment]
> [ProjectE-1.20.1-PE1.0.0B - Unofficial build.zip](https://github.com/sinkillerj/ProjectE/files/13431989/ProjectE-1.20.1-PE1.0.0B.-.Unofficial.build.zip)
> 
> I uploaded it. Due to limitations, I could only upload it in a zip file, so unpack it first.

MY SAVIOUR!! this issue was getting annoying lol and im not the greatest with coding so even just compiling this wouldve been a pain for me!



> Yeah but is curseforge going to allow a third party download into my modpack? why not just release it on forge

Can confirm it works just fine. just make sure that you remove the "broken" mod and rename the unofficial mod to be the same as the old one. it wont show up in curseforge but it will still load without issues.

**Comment by pupnewfster** [comment]
Should be fixed in 1.0.1
