### ISSUE TITLE
1.20.1 This is not working the EMC version and the Tablet

### ISSUE THREAD

**Issue by lucasbr2405** [sinkillerj/ProjectE#2307]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 

Exact Forge version:

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1.

What I expected to happen:

What happened instead:

**Comment by sinkillerj** [comment]
Zero details provided, invalid issue.
