### ISSUE TITLE
[1.20.1] EMC values not registering with Mekanism installed

### ISSUE THREAD

**Issue by Andronomos** [sinkillerj/ProjectE#2308]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar):  ProjectE-1.20.1-PE1.0.0B

Exact Forge version: 47.2.1

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/HGafkQ9x

Steps to reproduce:

1. Install ProjectE and Mekanism

What I expected to happen: Majority of items to have an EMC value.

What happened instead: Nothing has an EMC value.

To save time, here's the relevant error from the log

> [22:31:00] [Render thread/ERROR]: Error calculating EMC values
> java.lang.AbstractMethodError: Receiver class mekanism.common.integration.projecte.mappers.ItemStackToItemStackRecipeMapper does not define or inherit an implementation of the resolved method 'abstract boolean handleRecipe(moze_intel.projecte.api.mapper.collector.IMappingCollector, net.minecraft.world.item.crafting.Recipe, net.minecraft.core.RegistryAccess, moze_intel.projecte.api.mapper.recipe.INSSFakeGroupManager)' of interface moze_intel.projecte.api.mapper.recipe.IRecipeTypeMapper.

**Comment by ridivagyokcso** [comment]
Update mekanism. :)

Your version: 10.4.2.16
Use 10.4.4.18 +


> **Tickets that do not conform to this template will be closed without comment**
> 
> Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.20.1-PE1.0.0B
> 
> Exact Forge version: 47.2.1
> 
> Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://pastebin.com/HGafkQ9x
> 
> Steps to reproduce:
> 
> 1. Install ProjectE and Mekanism
> 
> What I expected to happen: Majority of items to have an EMC value.
> 
> What happened instead: Nothing has an EMC value.
> 
> To save time, here's the relevant error from the log
> 
> > [22:31:00] [Render thread/ERROR]: Error calculating EMC values
> > java.lang.AbstractMethodError: Receiver class mekanism.common.integration.projecte.mappers.ItemStackToItemStackRecipeMapper does not define or inherit an implementation of the resolved method 'abstract boolean handleRecipe(moze_intel.projecte.api.mapper.collector.IMappingCollector, net.minecraft.world.item.crafting.Recipe, net.minecraft.core.RegistryAccess, moze_intel.projecte.api.mapper.recipe.INSSFakeGroupManager)' of interface moze_intel.projecte.api.mapper.recipe.IRecipeTypeMapper.

**Comment by Andronomos** [comment]
There wasn't an update available when I first encountered the problem yesterday night. Updating to it solved the problem.
