### ISSUE TITLE
ProjectE EMC Values break with Mekanism

### ISSUE THREAD

**Issue by Jase1456** [sinkillerj/ProjectE#2309]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.20.1-PE1.0.0B.jar

Exact Forge version: 47.1.46

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:

1. Install Mekanism, emc values dont appear, and cant use the transmutation table or the energy condenser.

What I expected to happen: To be able to use the transmutation table and energy condenser with Mekanism installed.

What happened instead: All EMC values disappeared and not able to use either transmutation table nor energy condenser

**Comment by Jupitor87** [comment]
update mekanism
