### ISSUE TITLE
Cannot use the search bar in the transmutation table. Will not let you enter text or click on it to activate.

### ISSUE THREAD

**Issue by dave252life** [sinkillerj/ProjectE#2310]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.20.1

Exact Forge version:  47.1.3

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): there is no crash log.

Steps to reproduce:

1.Click on transmutation table search bar
2. Try to type anything.
3. Nothing happens.

What I expected to happen: To be able to search in the search bar or activate it with the mouse button click.

What happened instead: Nothing at all. No activation of the search bar or anything.

**Comment by Jupitor87** [comment]
look at previous bugs first this has already been fixed in dev version
