### ISSUE TITLE
mek and project e calculation error  

### ISSUE THREAD

**Issue by Jupitor87** [sinkillerj/ProjectE#2311]
Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 1.0.0B (latest on github)

Exact Forge version: 47.2.0

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): https://mclo.gs/qLvLtNL

Steps to reproduce:

1.trying to put anything in the table with the latest  mek version dose not work as any item has no value 

What I expected to happen: for item to have emc values 

What happened instead: nothing did and I received calculation error in logs

**Comment by pupnewfster** [comment]
This has nothing to do with Mekanism you are using the wrong projecte jar

**Comment by Jupitor87** [comment]
> This has nothing to do with Mekanism you are using the wrong projecte jar

is it the universal?
