### ISSUE TITLE
Suggested Features

### ISSUE THREAD

**Issue by aqua-air** [sinkillerj/ProjectE#2312]
Dark + Red matter armor give invincibility with a full set. Dark matter armor even makes you untouchable. 
Also condensers are easily abused with automation mods. 
Suggestion: 
-- Allow a config option to disable the full set buff for all armor. I don't want that at all in my pack. 
-- Allow a config option to disable input/output from a condenser.  Like make it so pipes can't connect to it or items cant be pulled from it. If possible. 
Thanks, just some suggestions. Otherwise i have to keep all ProjectE recipes disabled and no armor allowed at all from the mod. I make them buy transmutation tables from the server shop.

**Comment by sinkillerj** [comment]
This mod is EE2, if you want to tweak it use CraftTweaker.
