### ISSUE TITLE
itens are missing an emc value ,printing to client log 1.20.1PE1.0.1 error due to old version of mekanism

### ISSUE THREAD

**Issue by lucasbr2405** [sinkillerj/ProjectE#2315]
itens are missing an emc value ,printing to client log

error due to old version of mekanism

**Comment by Usaksport** [comment]
Same issue on server

**Comment by Usaksport** [comment]
I've deleted Project Integration on my server and now works fine maybe others have the same issue.

**Comment by lucasbr2405** [comment]
> Excluí o Project Integration do meu servidor e agora funciona bem, talvez outros tenham o mesmo problema.

but is the EMC of the items working? mine isn't even on the server, and I don't have this other mod

**Comment by lucasbr2405** [comment]
error due to old version of mekanism
