### ISSUE TITLE
Texture license?

### ISSUE THREAD

**Issue by ThePython10110** [sinkillerj/ProjectE#2325]
I made [a clone of this mod](https://content.minetest.net/packages/ThePython/exchangeclone) for [Minetest](https://minetest.net), and it would be great if I could use the textures from this mod.

I'm aware that the textures are originally from EE2, but as far as I can tell, the license is never specified. So would I be allowed to use ProjectE's textures?

**Comment by sinkillerj** [comment]
While I am not personally opposed, It is not really up to me. You will want to ask the original EE2 author Xeno for permission.

**Comment by ThePython10110** [comment]
Well, [this tweet](https://twitter.com/MercuriusXeno/status/1662203934713212932) suggests that it's fine.
