### ISSUE TITLE
PSA: DO NOT USE THIS MOD

### ISSUE THREAD

**Issue by Fireball5939** [sinkillerj/ProjectE#2327]
**Why not use the mod?**
Well first off, the mod itself is fine. Despite a minor bug here or there the mod is completely ok. The problem resides in the developers.
If you look in the discord then you will find several occasions of someone going there to look for help or see if an issue has been reported there. The developers are often times snarky and rude to people asking for help and recently (As of writing) banned someone simply because they could not figure out what the filter was. After I saw this I commented on how they had just banned someone who was looking for help and then promptly got banned myself. The developers also refuse to do anything besides make sure the mod isn't broken, or updating it to a new version. Despite having a new name, it is simply EE2 for modern minecraft. I get that the devs are just volunteers but that isn't an excuse to be rude to people who are looking for help. I already know that this issue will get closed within a day or two of posting for "Not following the issue template" so please if you have any inquiries DM me on discord at femboyfireball. In short, the devs are snarky, rude, and as sensitive as someone taken from twitter, along with doing next to no work.

**Comment by Fireball5939** [comment]
Now, I wish to be clear here. I am not mad because of the fact I got banned, I'm mad because of *why* I got banned. The fact that I am unable to criticize a decision that the mod author made without getting banned is why I am mad. If I had gotten banned for breaking one of the rules, I would not be mad. I was already on the edge of making a post like this when I saw the other person get banned, as I had already developed a dislike for the mod authors for their attitude, but this pushed me over the edge. I am not going to support a group of people who act like they are above everyone else simply because they made a big thing and know everything about it. And if this *does* get closed, it will only prove my point that the mod authors are a couple sensitive sissies who got their fee fees hurt.

**Comment by Fireball5939** [comment]
I also want to make it clear I did not post this to attempt to advertise something I am making, but rather to inform you of what the mod authors are like. However if you are interested please DM me, again at femboyfireball. I do not wish any harm to come to the developers, as they are just volunteers. But I again state that this is no excuse to be rude to a playerbase.

**Comment by sinkillerj** [comment]
Being in the Discord is a privilege, not a right. There are many factors behind your ban that you seam to (perhaps intentionally) not realize, this is not the only issue we had from you. Regardless since you want to go on a 50 mile tirade instead of accepting your faults and appealing the ban... this is now locked in. Bye.
