### ISSUE TITLE
The EMC stored value is not abbreviated, only the income is

### ISSUE THREAD

**Issue by Lucifer4224** [sinkillerj/ProjectE#2362]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): ProjectE-1.18.2-PE1.0.2.jar

Exact Forge version: I am not sure of this. I am running ProjectE in the FTB Stoneblock 3 modpack (v 1.10.0)

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 

Steps to reproduce:
I dont have exact reproduction steps but here is what i think i might have done
1. Set up some EMC farms (power flower/items)
2. Accumulate a lot of EMC
3. Wait for it to be a sufficient big number

What I expected to happen:
Values are abbreviated at all times

What happened instead:
![image](https://github.com/user-attachments/assets/16e3ca83-623f-43b4-af46-ba90b623ff5c)
At first the stored value was abbreviated and after a few hours of farming EMC the value transitioned to full number. At the moment only the income value is abbreviated

**Comment by Lucifer4224** [comment]
Worth to mention that I did not tampered with any mod configs

**Comment by Lucifer4224** [comment]
Tested it out and it seems whatever value gets over 9.00E it will not be abbreviated anymore

**Comment by pupnewfster** [comment]
projecte is not adding that overlay
