### ISSUE TITLE
0.2d-dev10 - Step Assist not working on Gem Armor

### ISSUE THREAD

**Issue by psychofad** [sinkillerj/ProjectE#241]
on 0.2c the Step Assist was working great.  Then after upgrading to 0.2d-dev10 the step assist no longer works.  Tried toggling it on and off, tried removing the boots and putting them back on...still does not work.  No error messages to speak of just a lack of functionality.

**Comment by sinkillerj** [comment]
Issue should be fixed in latest versions, closing.
