### ISSUE TITLE
Hello! - Repost Of My DEV-11 Issues >.>

### ISSUE THREAD

**Issue by Lanse505** [sinkillerj/ProjectE#300]
Hello!

These are the issues i have with Dev-11 that got closed:

1. Some items don't register their properly for whatever reason, this is using 1. Dev-11 and 2. Clean Configs tested 3 times to make sure. The items i've found are as follows: IC2 Copper Ingots, IC2 Tin Ingots, ThermalFoundation Ferrous and Metallurgy Fertalizer. These three just wont accept an EMC change over their default amount.

2. Mod Suggestion that was suggested seeing as it wasn't part of Dev-11: The addition of "Buy" and "Sell" values for items, this enabled pack devs and server owners to disable blocks "selling" for EMC but still keeps them "buyable" for EMC. 

3. Mod Suggestion that was supposte to be added in Dev-11 but was forgotten about, a blacklist by ModId option so instead of having to disable every single Magical Crops item one by one, one can simply Disable Magical Crops by using a wildcard.

 For example
 /projecte_removeEMC MagicalCrops:*
 /projecte_removeEMC Forestry:*
 /projecte_removeEMC FluxedCrops:*

All of these have been tested against Dev-11 and all of these are still valid Issues.

Thank You for any help that you could provide.

//Best Regards
Lanse505

**Comment by williewillus** [comment]
Simply ancient, closing
1. Mod items no longer have default value
2. another ticket with this suggestion is open
3. I believe another ticket is open or this is implemented
