### ISSUE TITLE
List of issues + 2 extra

### ISSUE THREAD

**Issue by Claycorp** [sinkillerj/ProjectE#310]
Tested and confirmed bugs:
#221 
#294 
#274 
#253 
#245 
#241 

Unimplemented/Active Ideas:
#296 
#291 
#284 
#283 
#279 
#266 
#264 
#263 
#225 

Holding both amulets when walking on water removes the speed boost
Hold both amulets walk on water and you walk at normal pace.

MK2/3 Relay GUI's don't scale properly
MK2 http://i.imgur.com/4vKOE3C.png
MK3 http://i.imgur.com/FbLD1rO.png

I already had did the work might as well pass it on as it was sitting there to be copy pasted. Im not happy, your not happy. We can go our different ways but i'm still posing these as it still affects people beyond our little shell of stupid.

Hope you understand. ~Claycorp

**Comment by Chinthor** [comment]
Won't make a new issue. The feature I'm looking for is referenced here. Was it ever worked on? #284 Klien Star slot automation. Pipes, ducts, and even SFM inventory cables cannot pull from the star slot. Having perfected my "flower garden" I'd like to create a star charging system. Any thoughts?

**Comment by williewillus** [comment]
There were quite a few inv changes in the latest 1.10., try it out there (I can't remember exactly Rn)

**Comment by Chinthor** [comment]
Thanks. I will. But I guess that means it wasn't included in 1.7x, 1.8x, or 1.9? Playing a 1.7 pack at the moment. But new good ones are in the works for 1.10. May move on to them soon.
