### ISSUE TITLE
Feature request: Unified commands

### ISSUE THREAD

**Issue by Brycey92** [sinkillerj/ProjectE#311]
I believe it would be helpful to have all commands unified under /projecte <command> instead of each being their own separate command. Additionally, /projecte and /projecte help should display a list of commands, their parameters, and their usages.

**Comment by Nova001Sol** [comment]
Is this still going to happen? Or has this plan been cancelled?

**Comment by williewillus** [comment]
If I have time on the side I'll look at this

**Comment by sinkillerj** [comment]
I'll take care of this @williewillus

**Comment by williewillus** [comment]
kk

**Comment by sinkillerj** [comment]
#ValveTime
