### ISSUE TITLE
Table/Tablet forgets if not save/quit

### ISSUE THREAD

**Issue by ti07shadow** [sinkillerj/ProjectE#316]
I dont know how if this could be fixed. But I have noticed and can replicate, if the game crashes at all. OR the game is closed any other way other than ESC -> Save & Quit (ALT+F4 seems to not cause the issue either. Seems to only be crashes). The tablet or table will forget anything taught to it, since logged in. But this of course only seems to happen with crashes. Another instance was going to the nether and the game locked up and had to force close the game (note there was no memory issues, it wasnt maxed) But does seem to be an issue if MC runs out of memory. All and all this issue seems to be isolated wiith game crashes and notably may not the mod itself but a general issue in regards to any kind of crash effecting it.. But still wiling to put this support ticket out there for those with the issue. 

Im still testiing this with issue and see what causes it other than just crashes.

Issues this is caused by and confirmed to be repeatable by myself and possibly others.
+ Out of Memory issue (allocate more memory to fix this)
+ A mod causes some sort of crash that rolls back mine craft
+ Force closing java using task manager (obviously don't do this, but if java crashes its the same thing as doing so)
+ ... Still working on what else causes it.

but this does prove its not the mods fault at all. But is a issue. (can close this support ticket if need be, but still sharing this information.)

When I tested the force closing (NOT alt+f4) the emc gained was lossed and so was any item added since logged in till force closed but means of opening chat and clicking the [X].

im checking see if mods like worldstateCheckpoints and/or YABM helps recify this even by a little. Also reccomend some sort of auto save for the tablets memory to combat it if possible

I have noticed with WorldStateCheckpoints it saves the knowledge file and the bag data so this may help against the issue.

**Comment by bendersalt** [comment]
I have been experiencing this issue on a server as well. We had a power outage, the server went down, and no one's transmutation tablets remembered their recipes.

**Comment by SkepticalTech** [comment]
Having the issue as well, but not on a crash. I had some lag to the server, so I logged off, and back on. The table had forgotten all the items. My friend who was hosting the lan session had no issues.

**Comment by MaPePeR** [comment]
Which version of ProjectE?

**Comment by williewillus** [comment]
Maybe we should save two files like MC does with level.dat and read from the backup if the main one is corrupted.

**Comment by SkepticalTech** [comment]
I'm using the latest version, 1.4.2.
