### ISSUE TITLE
[Suggestion] Audio for items?

### ISSUE THREAD

**Issue by KR1dude** [sinkillerj/ProjectE#329]
Hi. I'm really glad that this mod exists and like it a lot, but it's missing one thing: audio. One of my favorite parts from EE2 was how each item made a sound when activated or deactivated. Could audio be implemented later on? Thanks for reading.

**Comment by CubeWrench202** [comment]
You can't do it by yourself?Like, you are the main dev..

**Comment by sinkillerj** [comment]
...yes, which means I manage the project and write code, it does not mean I am a expert sound designer.

**Comment by Brycey92** [comment]
Wait, I thought we had permission to use the assets from EE2? Or was that just textures?

**Comment by williewillus** [comment]
We have sound and texture permissions, and sounds are reimplemented. (though some are missing I think....)
