### ISSUE TITLE
impl oreDictionary *(wildcard) metadata

### ISSUE THREAD

**Issue by skaviouz** [sinkillerj/ProjectE#336]
### REPLICATE

/projecte_setEMC saplingTree 32
/projecte_setEMC treeSapling 32

:christmas_tree: Natura saplings have both oreDictionary names. you can type either.
:evergreen_tree: Natura:florasapling:0 has an EMC of 32, but Natura:florasapling:1-7 (meta data) does not have EMC.
:palm_tree: Natura:Rare Sapling:0 has an EMC of 32, but Natura: Rare Sapling:1-4 (meta data) does not have EMC.
### Conclusion:

You should be checking all the metadata items and checking if they have OD names that match and setting their EMC. Also having the ability to apply EMC to a wildcard on metadata would be cool. So for example: groupings that don't have an oreDictionary name, but share itemID space.
### Other thoughts

Would be cool if you could apply a wildcard to unlocalized names, or **support regex LOL???** the bold is more of a joke though, I think that would be over complicating it.
### Another Example:

:fish: Minecraft:_fish_:0 has EMC of 64, but Minecraft:_fish_:1-3 has EMC 0, and this is a vanilla items, but they don't share oreDictionary names.
:tulip: BiomeOPlenty flowers all share 2 ItemIDs, setting a wildcard for metadata for the two items would be nice.
:rainbow: Colored dye from botania and other mods are usually in one itemID space.

**Comment by pupnewfster** [comment]
I believe this can be closed? At the very least via `custom_emc.json` I remember using ore dictionary, and wildcard. (Not positive if the commands support it, but I don't see why they wouldn't)

**Comment by williewillus** [comment]
the file supports wildcards/oredict, the command doesn't. not worth implementing with 1.13+ on the horizon.
