### ISSUE TITLE
CataliticLens.java/DestructionCatalyst.java looks copy pasted

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#349]

**Comment by japherwocky** [comment]
I'm sure he would appreciate a pull request with a refactoring of the code, but this is neither a bug nor helpful?

**Comment by MaPePeR** [comment]
It might be not an issue or helpful, but its an 'issue' with the code, that i wanted list here.

**Comment by williewillus** [comment]
Resolved by refactor #620
