### ISSUE TITLE
Using Catalytic Lens in alternative mode may be creating unrelated blocks

### ISSUE THREAD

**Issue by cluckinator** [sinkillerj/ProjectE#351]
I am using the catalytic lens in the 'fire projectile' mode and I am receiving blocks that are not available. For example, I received Galacticraft blocks with a meta value of 9. It is causing client crashes when I receive blocks with a meta of 9 where there are no blocks/items for the mod with a meta of 9.

http://pastebin.com/vWbSg5rP 

The server admin deleted the items in my bag with a damage of 9, but when I logged in, loot balls flew to my character and a similar block issue occurred with a different mod:

http://pastebin.com/D33yQqnX

**Comment by Heimdell** [comment]
Uusing hyperkinetic lens on mesa biome surface in projectile mode givens me some strange sand (12:10, 12:11)
