### ISSUE TITLE
Philosopher Stone Weirdness

### ISSUE THREAD

**Issue by Shad0wB1ade** [sinkillerj/ProjectE#353]
Tested with both dev 11 and 12 on forge 1277
It basically does the block next to the block your pointing at while pressing shift and not looking at the center
See the quick youtube video:
https://www.youtube.com/watch?v=HfprUN9CHCk

**Comment by MaPePeR** [comment]
Actually this IS a vanilla bug: the Philosophers Stone uses the `getMovingObjectPositionFromPlayer`-Method to find the targeted block. (This Method is also used in CataliticLens,DestructionCatalyst,DiviningRod*,MercurialEye and i could recreate this with the destruction catalyst as well).
In Vanilla this method is used by the Bucket: 
Create a 1x1 Hole and place a bucket of water in it. Now go to the very border of the water source block and right click it with a bucket: you will see the watersource disappearing for a very short moment, but instantly reappearing, without filling your bucket.

**Comment by Shad0wB1ade** [comment]
So I was actually right? YEY I apparently know what I am talking about...

**Comment by Kolatra** [comment]
Fixed by https://github.com/sinkillerj/ProjectE/commit/7632d8c8ebb93dba917029fff4cfed8627f808b7.
