### ISSUE TITLE
Using Alchemical Tome to unlock all items causes unlearn of Klein star recipes. (Alpha 0.2b)

### ISSUE THREAD

**Issue by Hurons** [sinkillerj/ProjectE#361]
I have Alpha 0.2b installed on a SMP server.
When I use the Alchemical Tome to unlock all items that have an EMC value, the recipes for the Klein stars (all versions) are no longer known.

Haven't found any other recipes gone "missing" after using the Alchemical Tome yet.

Many thanks,

Hurons.

**Comment by ViolentNinjaD** [comment]
Maybe that has been fixed in a newer version, alpha 0.2b is quite old now.

**Comment by Hurons** [comment]
Just testedin 0.2c, and my bad, it's fixed already.
