### ISSUE TITLE
Unable to fly after crossing dimensions

### ISSUE THREAD

**Issue by therealericbj** [sinkillerj/ProjectE#365]
Since I updated to ProjectE-1.7.10-0.2d-dev12.jar I have found that I can not fly until I take off my Gem armour boots and put them back on.  Then everything works normally, as far as I can tell.

I've watched the console for any messages and I can't find any.

All I know is it just doesn't work until I take them off and put them back on.

I know this is vague, sorry...

**Comment by sinkillerj** [comment]
This is a known issue and will be addressed in the future. May I ask which version you were using prior?

**Comment by therealericbj** [comment]
First version on the server was ProjectE-Alpha 0.2d-dev11.jar.  Then updated to "dev12" on the 29th.

**Comment by Kolatra** [comment]
This is fixed as of recent versions.
