### ISSUE TITLE
Paint Brush Project E issue

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [sinkillerj/ProjectE#366]
Not sure if this is either a bug on the part of Electrical age, or Project E, so I'l post on both githubs.

As of currently, when using ProjectE tablets, a good deal of the time, no matter what you search for, you get Electrical Age brushes, as seen here: 
http://i.imgur.com/SWr39Wb.png
http://i.imgur.com/rfsMkwi.png
http://i.imgur.com/ubkhOiP.png

Not quite sure why this is happening, but it doesn't seem to have any need.

Mod Versions used:
ELECTRICALAGE_BETA-1.9_R44
PROJECTE-ALPHA 0.2D-DEV11

**Comment by Lanse505** [comment]
Good thing to keep in-mind is that the ProjectE tablets uses the same search function as NEI, so it might be an issue with El-Age NEI inputs of the rollers?

**Comment by TheCricket** [comment]
I think its pretty funny

**Comment by williewillus** [comment]
Resolved by the newly added pages in the transmutation gui
