### ISSUE TITLE
Suggestion:Delete Items from tablet

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [sinkillerj/ProjectE#368]
Would be nice if it was possible to delete items from the Tablets

**Comment by Shad0wB1ade** [comment]
Why?

**Comment by IAA-ShRaPNeL** [comment]
For example, I don't really need a wood sword, wood hoe, stone hoe, leather armor, ect ect ect. It'd be nice to remove unneeded items from the tablet so they don't clutter and push other items off the tablet view.

**Comment by Shad0wB1ade** [comment]
Yes but you have the slot in the middle to sort that issue out and of course NEI search... I think thats enough... and there might always be some stupid recipe that requires wooden, stone tools.

**Comment by IAA-ShRaPNeL** [comment]
Well, yes. But sometimes I don't have the item on hand i'm looking for. In that case, the middle slot means nothing to me. And NEI searching for it doesn't show it because the table is filled with other things I don't need. 

It's still something nice to add. Will everyone use it? Maybe not. Still something nice to consider.

**Comment by MaPePeR** [comment]
you don't need to place the exact same item you are looking for in the center slot. The center slot will put an upper limit on the emc for the items the tablet is showing.

**Comment by IAA-ShRaPNeL** [comment]
While those are all valid alternatives, it's still not the feature I suggested.

**Comment by williewillus** [comment]
Req close feature implemented
