### ISSUE TITLE
[Lag] Saving transmutation tablet and alchemical bag

### ISSUE THREAD

**Issue by KR1dude** [sinkillerj/ProjectE#371]
Hi. When I check on my modded server's log, it shows a lot of instances of saving transmutation and alchemical data. Because of this, my server suffers from a lot of lag and causes my players and I to time out quite frequently (Minimum 10 times an hour). Is there a fix for the lag?

**Comment by Kolatra** [comment]
I doubt it's from that, the save is quick and not constant.

**Comment by Kolatra** [comment]
Can you post a log?

**Comment by Tommsy64** [comment]
This used to happen on my cauldron server. After updating ProjectE to the latest version it stopped happening.

**Comment by sinkillerj** [comment]
10 times a hour is not often and shouldn't cause issues, other mods and even Vanilla itself saves NBT data far more often.

**Comment by matthew-goodman** [comment]
i can confirm this happens on my server also, each time the bags save, all players get timed out. I can provide logs if required

**Comment by matthew-goodman** [comment]
Thank you sinkillerj for reopening the ticket. As described in IRC, 

Server details: - 
Players - 20-45 at any time

When any more than 25 or so players join, we get timeouts after the following message 

Saved Transmution and alchemical bag data

i have tried removing the /world/projecte folder with the same issue. 

I can provide console (SSH access) or any other files required to help troubleshoot this issue

**Comment by matthew-goodman** [comment]
Any update on this one please? our player base is having real problems now

**Comment by matthew-goodman** [comment]
just another update. CPU runs to 100% when saving the bag data. this seems to be the issue?

**Comment by sinkillerj** [comment]
If anyone wants to take a look at this and open a pull, or at least provide some insight, I cant seam to find the cause of this.

**Comment by matthew-goodman** [comment]
I can provide full access to my server if anyone wishes to investagte. Give me a shout

**Comment by matthew-goodman** [comment]
Hi, Any one had any time to look at this? issue is still there

Thanks

**Comment by williewillus** [comment]
If it all possible can we see what kinds of items are in the bags on average? We're using vanilla minecraft methods to save the bags so there shouldn't be any lag... perhaps someone has an item that has lots of nbt data?

**Comment by matthew-goodman** [comment]
Im sure i could export the datafile and put names beside the items. Would that help?





        Sent by Outlook for Android




On Wed, Mar 25, 2015 at 11:09 PM -0700, "Vincent Lee" <notifications@github.com> wrote:
If it all possible can we see what kinds of items are in the bags on average? We're using vanilla minecraft methods to save the bags so there shouldn't be any lag... perhaps someone has an item that has lots of nbt data?

---
