### ISSUE TITLE
Suggestion: Enhance the NEI Search for Transmutation tablet

### ISSUE THREAD

**Issue by Xaw4** [sinkillerj/ProjectE#374]
It would be very nice to be able to search for other things than just the item name, with the NEI text - like you can with the "real" NEI.

e.g
    search per unlocalized name
    search per itemID

maybe even the 
@mod.mod thingie

why would this be really helpfull?

For instance, where you have "eaten" the alchemical tome, you have so much items you know. its virtually impossible to get vanilla smooth stone... because Extra Utilities adds all those Colored Stones.

**Comment by MaPePeR** [comment]
The @mod thingy is a feature of Waila, i think.The PR #377 should add support for all registered `ISearchProvider` in NEI
