### ISSUE TITLE
Discrepancy: Loot Ball doesn't work with /dev/null (OpenBlocks)

### ISSUE THREAD

**Issue by Xaw4** [sinkillerj/ProjectE#375]
OpenBlocks has this item called "/dev/null". it's is like a portable trashcan. you specifie one type of item (usually cobblestone), and it will keep up to a stack of this item in it's internal inventory, and if you pick up another item after that, it will instantly be voided.
so this item is awesome for tons of mining... BUT when i use the tools from ProjectE that drop those Loot Balls, the /dev/null is worthless, because the "blacklisted" item will still land in my inventory and take up tons of space.

i havent checked this issue on the OpenBlocks' side of things, but my guts tell me, the this is an issue with the Loot Balls "hard coded" detecting if there's enough space, and just placing it in my inventory (and not calling whatever event the /dev/null is catching).

(btw. unlocalized name of that item is "OpenBlocks:devnull")

**Comment by sinkillerj** [comment]
I'm not sure I can resolve this, however loot balls are under evaluation to see if they are even needed.

**Comment by MaPePeR** [comment]
I removed the Loot balls from the Catalitic lens some time ago to try it out:
It did not crash or lag my game, but it drastically reduced the render distance for items on the ground. (So you could only see the items on the ground, that are close to you)

The OpenBlocks [/dev/null uses the onItemPickup Event](https://github.com/OpenMods/OpenBlocks/blob/100d9d812e74c8c9cbbf93d6075a1567813081ea/src/main/java/openblocks/common/item/ItemDevNull.java#L89-L116), so it should be as easy as triggering that event.

When this is implemented i would even extend the loot balls in a way that they 'merge' into eachother, when they are close on the ground (Or do they do that already?)

**Comment by IAA-ShRaPNeL** [comment]
The loot balls also do not work with Forestry backpacks. I assume it's the same issue.

**Comment by DigitalLunacy** [comment]
hopefully the loot balls will at least get the option to turn of for people that can handle the FPS hit, if you have played botania the terra shatterer (ee2 RM pick rippoff) drops a shit ton of items and i get 0 FPS hit, i do have a beefy pc but this should at least be a option for people like me/us.

**Comment by MaPePeR** [comment]
Sadly the code for spawning the loot balls is scattered throughout the entire code and needs to be changed for everything that drops them.

**Comment by williewillus** [comment]
4d58572
