### ISSUE TITLE
[Suggestion] Make items respect Griefprevention claims

### ISSUE THREAD

**Issue by whitepyros** [sinkillerj/ProjectE#380]
Hi i love the mod and am planning on using it in a modpack if i have your permission (credit would be given if allowed) so on a test version of the pack on a server i found out that all of the items that can break multiple blocks at one time, the Nova cataclysm and the water and volcanite amulets completely ignore claims by griefprevention. Now i know this mod is still in development but are there any plans to make said items respect claims soon and if so how long as an estimate before it will be implemented (im not asking for exact dates just a rough guide for example a couple of weeks, months or its not planned)

**Comment by sinkillerj** [comment]
Cauldron is kinda a hack and I am unable to support it at this time, I have no idea how this is implemented within it. You do not need permission to use this in a modpack, please see the readme on the main page of this git for more info.

**Comment by MaPePeR** [comment]
I think VeinMiner might give a very good hint how one can implement such checks:  https://github.com/portablejim/VeinMiner/blob/1.7/src/main/java/portablejim/veinminer/core/MinerInstance.java#L186-L202

Especially the `boolean success = player.theItemInWorldManager.tryHarvestBlock(x, y, z);` might be a first start to check if a player should be allowed to destroy/change a specific block.

so this would need to be implemented for:

- [ ] Destruction Catalyst/Catalitic Lens
- [ ] Pickaxe/Shovel Tools
- [ ] Philosophers Stone
- [ ] ...

I think this should be reopened.

**Comment by MaPePeR** [comment]
overlord said, that this is the solution buildcraft is using to  overcome this issue: (From IRC)

```
<overload> The mod needs to be compiled with Bukkit as a referenced library so that you have the BlockPlaceEvent and BlockBreakEvent. Whenever you wish to break a block for example, you'd create a new BlockBreakEvent (org.bukkit.event.block.BlockBreakEvent), like so:
<overload> BlockBreakEvent event = new BlockBreakEvent(blockToBreak, playerBreakingBlock);
<overload> Then call this event so that plugins can do whatever they want to it:
<overload> Bukkit.getServer().getPluginManager().callEvent(event);
<overload> Then check whether the event has been cancelled:
<overload> if (!event.isCancelled())
<overload> {
<overload>     // Do your usual block break event
<overload> }
```

**Comment by sinkillerj** [comment]
In the future this may be addressed, but for now the issue will remain closed. Cauldron/Bukkit are a dieing standard which will likely be replaced in 1.8.
