### ISSUE TITLE
Code Paste Detection with PMD/CPD

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#382]
I tried the "Copy Paste Detector" from [PMD](http://pmd.sourceforge.net/pmd-4.3.0/cpd.html)

and it finds A LOT of copy pasted Code Regions that are bigger than 100 tokens. 

`RedPick.java` and `DarkPickaxe.java` being the biggest with 113 lines of code in common

[Download for PMD](http://sourceforge.net/projects/pmd/files/pmd/5.2.3/) contains `/bin/cpdgui.bat`

[full result](https://gist.github.com/MaPePeR/d134ecb8af47af3a1be8)
[shortened table](https://gist.github.com/MaPePeR/d7e9d1c0ffbbc3d0b774)

**Comment by williewillus** [comment]
Resolved by refactor #620
