### ISSUE TITLE
Suggestion: make the left side of the transmutation table(t) like the ae2 crafting

### ISSUE THREAD

**Issue by Mindavi** [sinkillerj/ProjectE#383]
It would be really nice if the (unused) space on the left side of the transmutation table(t) would be a crafting screen, so the tablet can pull from the items it already has learned into the crafting grid, while also learning the recipe, if it has emc atleast. Hopefully this can be implemented. The way ae2 handles this would be the nicest way, because in normal crafting grids it doesn't work with some non-stackable items, and in the crafting terminal it does. But either way would be really awesome if possible.

**Comment by Kolatra** [comment]
It's a nice idea, however the left side is used as a "target" selection kind of. It'll show items with equal or less EMC.

**Comment by Mindavi** [comment]
The middle can also be used for that, but the left side is for charging klein stars iirc. Might be possible to make an apart slot for that then, if this will be implemented.

**Comment by Belgabor** [comment]
I agree, that would be one more true evolution beyond EE2.

**Comment by Phyn** [comment]
There is no reason to not make this idea into something along the lines of an Alchemical Crafting Table similar to what Ars Magica had.

**Comment by Mindavi** [comment]
I don't think this is still or has ever been considered. Closing.
