### ISSUE TITLE
Using NEI to search items in the tablet

### ISSUE THREAD

**Issue by misterfixit** [sinkillerj/ProjectE#385]
http://puu.sh/elyLb/863e6bfbe2.txt

I crash to desktop when searching for items in the transmutation table and tablet

**Comment by misterfixit** [comment]
The version I am using is dev11 btw

**Comment by misterfixit** [comment]
tested in dev13 as well still exists

**Comment by Kolatra** [comment]
Version of NEI and CCC?

**Comment by misterfixit** [comment]
NEI-1.7.10-1.0.3.74-Universal
CCC-1.7.10-1.0.4.29-Universal

**Comment by Kolatra** [comment]
I can't reproduce this. Haven't had this issue for a few versions now.

**Comment by misterfixit** [comment]
im using forge version 10.13.2.1277 if that helps

**Comment by misterfixit** [comment]
Well this issue is present in the RR3 pack. I'm one of the pack devs, so continuing to troubleshoot could it be one of the nei addon mods?

**Comment by Kolatra** [comment]
Try updating to dev13 and let me know what happens.

**Comment by misterfixit** [comment]
It still exists in dev13

**Comment by MaPePeR** [comment]
I think this is the "unlocalized name = null" bug. This *might*  be fixed by my NEI - search pull request. #377
