### ISSUE TITLE
disappearing items with transmutation tablet

### ISSUE THREAD

**Issue by aldra2012** [sinkillerj/ProjectE#387]
when playing on my private server every time i get items out of the tablet they disappear when i exit it but doesn't do it all the time i believe its tick lag but i just wanted to see if it could be a bug of some sort

**Comment by Kolatra** [comment]
What version of ProjectE and Forge?

**Comment by aldra2012** [comment]
dev 13 and forge 1284

**Comment by sinkillerj** [comment]
If you click the slot in your inventory where the item should be does it come back?

**Comment by aldra2012** [comment]
no nothing is there

**Comment by aldra2012** [comment]
after breaking and replacing it the tablet works fine.
