### ISSUE TITLE
change in energy condenser GUI

### ISSUE THREAD

**Issue by nayfaan** [sinkillerj/ProjectE#389]
so I figured out the recent update changed how the energy condenser worked. Before, we would input one item into the slot in the condenser, and it takes one of the items from our inventory in order for it to condense emc, but in the new version, we only need to use the item, and the energy condenser will automatically register the item there and it doesnt deduct any item in our inventory.
The problem is, since it is only registered there, when we take it out, it automatically disappears. (i KNOW THIS IS MEANT TO BE SO), what bothers me is when we update from older versions.

so before the update, I put a red matter into one of my energy condenser's slot, I used one red matter from my inventory. Now i update the mod, when I take the red matter out, it simply disappears, that is to say, I lost one red matter, and 1 of each item in each and every emc condenser i have.

I personally prefer the old way of working, it is less confusing. I guess a lot of players would prefer sticking to the old version of emc condenser?

**Comment by sinkillerj** [comment]
A public vote to revert this was taken on Twitter as well as IRC, the majority vote was to keep the ghost target.

**Comment by Mattabase** [comment]
How about a config option.
