### ISSUE TITLE
[REQUEST] Make DM Pickaxe right-click support more ores

### ISSUE THREAD

**Issue by Nova001Sol** [sinkillerj/ProjectE#391]
Hi. I've been playing around with the right-click, break-all-the-ores! function of the DM pickaxe, and I've noticed one thing. It no break dense ores! So here I am to request support for the Dense Ores mod. The OreDict entries are denseore*, where * is the material's name.
EDIT: Some more playing revealed that Tinkers' Construct ores do not work either, nor does the one ore from Draconic Evolution. How do you even add ores anyway? Is it dynamic or do you need to manually add them? Anyway, I've changed the title of the request to better describe the content.

**Comment by MaPePeR** [comment]
@sinkillerj this can be closed as well now

**Comment by sinkillerj** [comment]
Dense ores should be taken care of as of the latest version, the others you have listed as of a few versions back, if you continue to have issues with one of these I will reopen the issue.
