### ISSUE TITLE
klein star with transmutation emc multiplayer 

### ISSUE THREAD

**Issue by aldra2012** [sinkillerj/ProjectE#392]
while i was doing some testing i noticed that when filling any klein star and then putting it back in for emc it takes the emc value of the klein star plus the emc value of what emc value its currently holding and multiplies it, thus adding more emc for the player.

**Comment by MaPePeR** [comment]
Duplicate of #378. Fixed with PR #381

**Comment by aldra2012** [comment]
ok thank you, now just waiting for an update
