### ISSUE TITLE
RM/DM slot check

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [sinkillerj/ProjectE#393]
Currently when a Red Matter/ Dark Matter furnace eject items to an adjacent inventory, they don't check if the inventory can accept the item. I noticed this with the Furnace ejecting items into a Forestry Apiarist Chest. 

Using Dev13

**Comment by williewillus** [comment]
Resolved a long time ago, idk exactly when (RMFurnaceTile Line 418)
