### ISSUE TITLE
Free EMC with Inv Tweaks

### ISSUE THREAD

**Issue by Zenith-One** [sinkillerj/ProjectE#394]
While in the transmutation tablet GUI, if I mouse over a stack of items and mouse wheel as I would to put items into a chest, the EMC increases in the table, but the item stack remains unchanged.  Not sure if it's a problem on the part of ProjectE or if it's Inventory Tweaks's fault.

Edit: this is using alpha 0.2d-dev11 (the one in the current version of the Vaygrim's Chance modpack on the ATLauncher)

**Comment by Nova001Sol** [comment]
I've noticed this as well, but when I try to make an item out of my free "EMC" it vanishes. Are you sure the EMC is real?

**Comment by sinkillerj** [comment]
This is a common issue with alot of mods and is typically client side only thus the EMC shouldn't actually be usable. Beyond seeing if InvTweaks has some sort of blacklist in its api I'm not sure of a way to solve this. If you can confirm that the EMC is real however I'll look into this further.

**Comment by MaPePeR** [comment]
Possible Duplicate: #379 #318 #120 #152

**Comment by Zaflis** [comment]
Still happening in ProjectE-1.7.10-PE1.2.0. I can confirm it's a visual bug for client only. Mousewheeling something really valuable emc, like most compressed cobble you can make, and then try extract a stack of it from table will refresh the client with what he actually has gained; nothing.

**Comment by Kolatra** [comment]
Closing as this is a duplicate issue.
