### ISSUE TITLE
Visual "unlimited emc"

### ISSUE THREAD

**Issue by TechGnome57** [sinkillerj/ProjectE#395]
So, basically if you scroll up with a life stone in your inventory while using a transmutation tablet you get EMC, though, I think it may be visual http://gyazo.com/8c81dbbf43f2b4572799cfc10fafe329

**Comment by jaredlll08** [comment]
This only happens with invtweaks as it moves items when you use the scroll bar

**Comment by MaPePeR** [comment]
I don't think this is Inventory Tweaks, but a vanilla feature... anyway:

Duplicate: #394 #379 #318 #120 #152

**Comment by jaredlll08** [comment]
-_- nearly all of those include Inventory Tweaks...
