### ISSUE TITLE
this thing crashed to maincraft multiplayer menu

### ISSUE THREAD

**Issue by Sailren** [sinkillerj/ProjectE#396]
this thing happened when i placed a alchemial tome in a mobile transmutation tablet in the fuel slot;

http://paste.ubuntu.com/9763739/

**Comment by Kolatra** [comment]
Version of the mod?

**Comment by Sailren** [comment]
dev13

**Comment by Sailren** [comment]
my client didnt crash, the only thing that happened is the thing in the paste, odd behaviour in fuel slot

**Comment by MaPePeR** [comment]
So this boils down to `return new GUITransmuteTablet(player.inventory, new TransmuteTabletInventory(player.getHeldItem(), player));` that then fails in `new TransmuteTabletInventory` because `player.getHeldItem()` is `null`?

**Comment by Sailren** [comment]
i tried to right click the mobile transmutation tablet when the alchemial tome was already in fuel slot, my plan was to use the alchemial tome to fuel up the the tablet and use this emc to charge an omega klein star

**Comment by Sailren** [comment]
any ideas why this thing crash to multiplayer menu? can some1 reproduce this? place alchemical tome in a mobile transmutation tablet into fuel slot and w8 or do something i which i cant specify

**Comment by Kolatra** [comment]
I can't reproduce this unfortunately.

**Comment by Sailren** [comment]
mhm, than something is screwing up the fuel handler, or whatever this thing is called

**Comment by williewillus** [comment]
Transmutation Inventory crash - should be resolved after unification of interfaces
