### ISSUE TITLE
EMC added after 1.073.741.824 disappears in transmutation table

### ISSUE THREAD

**Issue by drakola** [sinkillerj/ProjectE#397]
For example if you have 1.050.000.000 EMC in your transmutation table and add a stack of items worth 50 million EMC you will have 1.073.741.824 EMC, you can not add any more EMC until you take EMC out.
It is not a visual bug as taking out 50 million EMC worth of items leaves you with 1.023.741.824
I am guessing it is purposely limited, EE2's transmutation table was limited to 2.147.483.647
But losing the EMC should not be intended behavior, it should not let you add items that cause it to reach that limit at all.
Version Alpha 0.2c

**Comment by Kolatra** [comment]
Try updating. That version is quite old.

**Comment by drakola** [comment]
Same issue in version 1.0

**Comment by Kolatra** [comment]
Yes, nothing can be done about that. That is the max 32-bit integer in Java.

**Comment by MaPePeR** [comment]
I think there actually is code to handle that, but at the moment it does not block putting items in the table. If there would be no special code we would see an integer overflow.

**Comment by Kolatra** [comment]
This is the max EMC as defined in our Constants file. It may change, but it is not planned.

**Comment by MaPePeR** [comment]
I think the issue is still valid: the max EMC can stay, but then it should stop to accept items.

**Comment by Kolatra** [comment]
I've noticed recently that having more than the max just makes it unable to accept items, I will have to test again though.

**Comment by MaPePeR** [comment]
If that's the case, this is indeed fixed. (have you checked both table and tablet?)

**Comment by cjburkey01** [comment]
Would you consider switching to longs instead of ints?
