### ISSUE TITLE
Philosopher's stone smelting bug with ars magica

### ISSUE THREAD

**Issue by Roadcrosser** [sinkillerj/ProjectE#399]
![image](https://cloud.githubusercontent.com/assets/7963090/5791719/6ad46430-9f24-11e4-8b2b-5b219aef39d7.png)

Ars magica resource blocks can be smelted with the philo stone to make 7 vinteum dust.

That doesn't look right.

**Comment by Kolatra** [comment]
Closing for now as I don't think it's a bug on ProjectE's side.

**Comment by MaPePeR** [comment]
@Roadcrosser can you elaborate, what you think is wrong with that?

**Comment by Kolatra** [comment]
Any of the Ars Magica 2 blocks such as Sunstone and Topaz etc that can be smelted into Vinteum.
