### ISSUE TITLE
NullPointerException in EMCMapper.loadEmcFromOD

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#402]
http://pastebin.com/MtZ6a5LN

caused by [this line](https://github.com/sinkillerj/ProjectE/blob/9c45583a2d6a982572820b0cb55878a7f9494a23/src/main/java/moze_intel/projecte/emc/EMCMapper.java#L639)(???)

**Comment by sinkillerj** [comment]
Can you track this down to happening when a particular mod is added?

**Comment by MaPePeR** [comment]
Apparently it disappeared again after deleting some logfiles/closing a dangling java process and stuff... weird...

**Comment by sinkillerj** [comment]
Still a very strange crash. Well if the issue comes up again in some reproduceable form I'm quite interested in it.
