### ISSUE TITLE
[Enhancement] Add config setting to disable recipe EMC calculation

### ISSUE THREAD

**Issue by heatseeker0** [sinkillerj/ProjectE#407]
What I mean by this is all raw materials can have EMC values but with this setting turned on these aren't carried over to crafted items.

So even if I have set an EMC value to a diamond and a wood log, by default a diamond pickaxe would have an EMC of 0. Same EMC of 0 would go for wood planks and sticks. This would allow players to use ProjectE to transmute between various raw materials but not bypass crafting completely and simply pull complex machinery out of the transmutation table instantly, thus removing the need to progress through the tech tree with speed upgrades, more machines, etc. for faster processing.

I'm using this in a server environment and manually set EMC of 0 to most machines. Having such setting would help a lot in such cases.

**Comment by sinkillerj** [comment]
This is likely to be introduced after #376

**Comment by sinkillerj** [comment]
Closing as this issue is related to the old mapper, it has now been replaced with the GraphMapper.
