### ISSUE TITLE
Shift click in relay

### ISSUE THREAD

**Issue by girlygamer2k8r2** [sinkillerj/ProjectE#411]
In neither of the relay's (mk1,mk2,mk3) shift click in or out of it works 
version ProjectE-1.7.10-0.2d-dev14.jar

**Comment by Nova001Sol** [comment]
I don't think it should. You can use a hopper with it, but I think that, given the speed at which they operate, shift-clicking items into the Relay is somewhat risky to do.

**Comment by girlygamer2k8r2** [comment]
I just think it is werid that it is the only one that you can't shift-click items into, you can with the condenser, and collector, so i don't se why you souldn't be able to with the relay.

**Comment by williewillus** [comment]
implemented in #827
