### ISSUE TITLE
nei search glitch ( ProjectE-1.7.10-0.2d-dev14 ) 

### ISSUE THREAD

**Issue by Ace199102840** [sinkillerj/ProjectE#413]
if you use NEI to search for an item while in the transmutation tablet or table , you can pull out an alchemy tome or any other high value item ( even though  you cant see the item in the ui you can still click where it would be as if you didnt type in anything in search, ex. klein star omega would be on left of the UI if you had enough emc)  for the price of the item you search and put it in the burn slot for its full emc value , cheating loads of emc. so if i type in lapis , it would show in the ui and able to click on it , but the tablet will give me the tome instead. if you craft the item you want that has emc value and put it in target slow ( filter) then it will give you that item as normal.   this only happens on multiplayer.  version 1.7.10-0.2d-dev14

**Comment by Kolatra** [comment]
I found the part of the code that is causing this, however I don't know what to do about it. Any help is greatly appreciated.

**Comment by sinkillerj** [comment]
I'm having trouble reproducing this, are you able to record a video?

**Comment by sinkillerj** [comment]
We have tracked this down to a desync between the client and server due to the NEI integration having a issue on the server side, the EMC dupe is client side only.

**Comment by Ace199102840** [comment]
wouldnt it had been better to integrate a search bar in the transmutation table so you wouldnt need to use nei ?  what if some people didnt use nei at all , thought it wouldnt fix the dupe glitch with nei , it would still be a very nice feature. sometimes i find even then typing " diamond " into nei to get a diamond sometimes doesnt even show the diamond. it will show a diamond block and any other item that might have the name "diamond" in it. which is no big deal seeing as i can turn the diamond block back into diamonds. its still sometimes annoying...

**Comment by sinkillerj** [comment]
NEI filtering has been included so that any filter you can use in NEI, and any filter another mod adds to NEI, can be used in the table, this gives much greater control over your search results as you can specify that you only want diamond results for minecraft, or only diamond results for another mod.

**Comment by Ace199102840** [comment]
what i meant is that maybe some people dont use nei or dont want to use it , and they use only project e , there could be a search bar in the UI for the transmutation table/tablet , and if said person is using NEI , that search bar could disable itself in the UI when it sees that NEI is installed.   

another suggestion i was think about was if you typed with quotes the item you wanted so that way it only showed the item that has that exact name. so instead of typing diamond and items with the name diamond showing up (ex. diamond chestplate , diamond pickaxe)  , you can type in " diamond " and only the diamond would show up.  it would eliminate having to keep 1 of every item to put in the target filter, or having to take out a diamond block to turn into diamonds.       

also i cant figure out the built in commands.  from what i understand your able to set custom emc for items ,  does this work for modded items or vanilla items only , and if theres an item that has no emc value , can you set a value for that item?

**Comment by MaPePeR** [comment]
@sinkillerj this one as well as #454 can probably be closed.
