### ISSUE TITLE
[Suggestion] Gem of Eternal Density shouldn't consume any Project-E crafted blocks, or any tools, or any utility items (beds).

### ISSUE THREAD

**Issue by Heimdell** [sinkillerj/ProjectE#414]
I had a transmutation table in my inventory converted to diamonds. Its not funny, since I can't make it back now (2 km from base).

**Comment by Kolatra** [comment]
There is a blacklist on it. Right-click to open the GUI and place items so that they aren't consumed, or you can whitelist items as well.

**Comment by Heimdell** [comment]
That is good, but the count of while/blacklist options is too small. And I cant blacklist more than 9 types, since many GoED will not take the intersection of untouchable types.
