### ISSUE TITLE
[Suggestion] [New feature] Teleportation

### ISSUE THREAD

**Issue by Heimdell** [sinkillerj/ProjectE#417]
I'd like to see some, like, block to stand on & teleport to other block. 

Because the mod is the EE rewrite, arrival gate must have at least the same amount of EMC as the object teleported - so, no actual mass/energy teleportation is done, just something is converted to EMC on the input side & emerged from EMC on the other side.

The teleportation is reversible - leaving & reentering will bring you back.

----
I have some thoughts to discuss:

Teleporter block recipe should require at least DM, I think.

Should it load the other side all the time?

Teleport block should be connected to the other one by giving it a key from unique-marked pair (Keys, craftable in pairs? No emc cost to deny from "give me a stack of keys, Transmutation Table"?).

It also should have a slot (slots?) for klein star. Due to the fact, that full Gem Armor costs around 330M EMC, and the Omega klein star could contain only 51M, it should be charged as the Transmutation Table does - by consuming energy from one slot and giving it back from the other.

For live entites, the cost could be approximated as 2 diamond per heart, and the partial teleportation will incur not only damage (without damage reduction), but nausea, slowness & other bad effects (or kill on arrival, if no energy left in output side).

If the inventory cell contains bag A, and the bag A contains bag B, their content is added up. If, in the next step, the bag B contains bag A (looping bags), it is ignored.

If the contents of player's alchemical bag of certain color are shared between all instances of that player's alchemical bags of that color (they were!), then this could be a problem - since alchemical bags are pretty cheap. One could just put a pile of all-colored bags near the each his teleport output & jump naked (but we can keep this in secret, can't we?).

(optional, subfeature) Partial teleportation mode may be possible. In that mode, the first thing teleported is the body, if its fully telepoted, and it has belt - all the items from belt, then inventory. Things not yet teleported due to not fitting into budget are staying in the teleport block inventory (if it has one), or in any inventory around, or thrown on the floor. "Body parts", exceding the budget are destroyed without producing EMC to prevent teleport-heal-teleport-again 

Modes could be designated by different partilce colors/ambient sound.

**Comment by sinkillerj** [comment]
There are enough mods that add teleporters, and there are even very nice standalone mods such as TF2 teleporters, I cant see any reason to implement this in the near future.
