### ISSUE TITLE
Mercurial eye's problems.

### ISSUE THREAD

**Issue by Heimdell** [sinkillerj/ProjectE#418]
Mercurial eye now transmutes (in front of block clicked) as seen here
before:
![2015-01-23_20 56 29](https://cloud.githubusercontent.com/assets/1784505/5878696/f509f69c-a339-11e4-9496-b797e34da235.png)
after:
![2015-01-23_20 56 32](https://cloud.githubusercontent.com/assets/1784505/5878695/f5095dd6-a339-11e4-9e86-d391e6fa2153.png)

It works not as it worked before: the old MA would change the block you click and blocks nearby in selected plane.

The extension mode is unexistent, so one cannot build a long bridge. 

If current transmutation mode focus (start point) could be moved, then that mode could be used to build long continius surface bands w/o help of flight.

**Comment by Heimdell** [comment]
The patch is here: https://github.com/sinkillerj/ProjectE/pull/429

**Comment by sinkillerj** [comment]
Pull merged, closing issue.
