### ISSUE TITLE
Error between the client and the server for the transmutation

### ISSUE THREAD

**Issue by Au2laDeNosReves** [sinkillerj/ProjectE#419]
When I play with the client there have any problems when I play out on a server, for example, I wanted to take the wood. And it gives me an enchanted golden apple. Like I want to take the Coal it gives me a stone sword.

I have this problem only when I log on to the server otherwise if I play locally I do not have that worry.

Best Regards.
Au2laDeNosReves

Original =>
Erreur entre le client et le serveur pour la transmutation

Quand je joue avec le client il n'y as aucun problème hors quand je joue sur un serveur, par exemple j'ai voulu prendre du Bois. Et il me donne une pomme d'or enchanté. Pareil je veux prendre du Coal il me donne une épée en pierre.

J'ai ce problème uniquement quand je me connecte sur le serveur sinon si je joue en local je n'ai pas ce soucis.

Cordialement.
Au2laDeNosReves

**Comment by MaPePeR** [comment]
Duplicate of #413

**Comment by sinkillerj** [comment]
Duplicate of a known issue, closing.

**Comment by Au2laDeNosReves** [comment]
Sorry I have trouble with English I had not seen.
