### ISSUE TITLE
Alchemica Bags losing Inventory.

### ISSUE THREAD

**Issue by squirrelkiller** [sinkillerj/ProjectE#420]
So a small issue, the Alchemical bags seem to be deleting their inventories. More specifically my white and black bags. I store all my tools in my white, and all the materials I need for complex builds for my let's play in black. However for some reason both of them got wiped. I have a brown bag that has got along fine without issue that I keep a black hole band in and the gem of eternal density for mining. Could this be related? Since I did not have this issue until I had that third unaffected bag. I can also tell you that in the white bag around the same time I started storying a transmutation tablet, a destruction catalyst, and a red matter pick.

I wouldn't mind this as much, but trying to cheat in the more expensive items and resupplying myself seems to just lead to another bag wipe. The brown has never been wiped however.

**Comment by sinkillerj** [comment]
Do you use Cauldron? Is this on Single Player or Multiplayer?

We have had other reports of this but thus far have been unable to find a way to reproduce the wipe.

**Comment by squirrelkiller** [comment]
SSP, no Cauldron. I could offer you the MultiMC instance I use if that may help.

**Comment by MaPePeR** [comment]
@sinkillerj fixed?

**Comment by sinkillerj** [comment]
Closing as this issue was reported before the overhaul.
