### ISSUE TITLE
[Suggestion] Unconstructable Items/Blocks

### ISSUE THREAD

**Issue by ewsmith** [sinkillerj/ProjectE#421]
Can you make certain items/blocks have emc but not be able to be created from emc?
Monster Spawners could have 8192 emc but you wouldn't be able to turn a diamond into one, or you could turn a primal pearl into dark matter but not vice versa.

**Comment by artman41** [comment]
I guess this could be possible by adding in a default "Add to Table" option when burning items and manually disabling it for certain items. However, it sort of beats the purpose of "Dirt <-> Diamond" idea

**Comment by sinkillerj** [comment]
Buy and sell values have been suggested in the past, however in the immediate future this is not planned.
