### ISSUE TITLE
Alchemical Tome lag [Bug]

### ISSUE THREAD

**Issue by DeathKnight1** [sinkillerj/ProjectE#430]
I have recently come across a new issues where every time I open the table(t) I get immense lag after I recently learned the Alchemical Tome. I don't know if there would be a way to stop this. I just wanted to make you aware. Thanks :)

**Comment by williewillus** [comment]
Does this still happen?

**Comment by DeathKnight1** [comment]
No Idea this was old and I hardly play anymore. Sorry!
