### ISSUE TITLE
Null transmutation tile reference [Bug][Server only]

### ISSUE THREAD

**Issue by heatseeker0** [sinkillerj/ProjectE#432]
Every time someone on the server uses their transmutation table, everyone else except the person using it receive 2 messages in their client logs:

16:02:26 PM] [16:02:26] [Client thread/FATAL] [ProjectE]: NULL transmutation-tile reference! Please report to dev!
[26/1/2015 16:02:26 PM] [16:02:26] [Client thread/FATAL] [ProjectE]: Coords: 183:56:614

The coordinates match those of the transmutation table used.

There is nothing showing up in the server logs. Everything works fine but with a few players online at the same time this could get very spammy.

Upon further investigation I've got some more information that would hopefully help locate the issue:

I am next to player A on the server and next to their transmutation table. They open their table and pull out some items. I receive no error messages in my client log.

I move about 1000 blocks away from player A. Again they open their table and pull out some items. For every item they pull out, I see those 2 error messages popping up on my client log. Nothing shows up in server logs and the operation is successful.

This happens for anyone on the server, so it's not related to a specific player or a specific table. We've tried moving them around, crafting new ones, the problem still shows up (with new coordinates obviously). If there are 20 players online, every time one of them uses their table all other 19 players get these messages in their local logs. As you can imagine if all 20 use their tables a lot everyone's logs get spammed over and over again.

My guess is each time someone performs a transmutation, server sends to all players online some data regarding that transmutation no matter where they are (even other dimensions). The client then sees the coordinates of the table involved are outside player range and print those errors.

This was tested and happens in both 0.2d-dev14 and 0.2d-dev13.

**Comment by williewillus** [comment]
This is because the server Tile Entity is sending updates to all clients, instead of only the ones near the TE. I don't know if this still happens.

**Comment by Tencao** [comment]
Just to remind you, this still happens, and I've found a pattern. If it's ontop of a crafting table (vanilla, project table, etc), it seems to trigger it to all players. I'm not sure if this is part of the reason, but thats some of the stuff I've noticed, as well as if it's floating in the air

**Comment by williewillus** [comment]
it's probably because it's sending to [players when the chunk in question is unloaded. I'll get this fixed.
