### ISSUE TITLE
Server crash loop on Archangel's Smite usage

### ISSUE THREAD

**Issue by Brycey92** [sinkillerj/ProjectE#433]
Upon using the Archangel's Smite to fire a homing arrow on a server (with ProjectE dev14), the server crashes. If the server is set to auto-restart, it restarts and crashes repeatedly until manually stopped from doing so. Clients on the server are disconnected and do not crash. I have not tested the homing arrow in singleplayer. MCEdit was unable to remove the homing arrow from the world, so a rollback was necessary. (Don't feel bad, it was a new map anyway.)

Crash report: http://pastebin.com/Z50kayZJ

**Comment by sinkillerj** [comment]
While not a solution, if you ever experience such corruption with any mod in the future go into your servers config folder, open the Forge config, and enable both remove erroring options, in most cases this will remove the erroring entity.

**Comment by Brycey92** [comment]
Thanks for the advice!

**Comment by williewillus** [comment]
this shouldn't happen anymore, but the arrows still aren't done :p
