### ISSUE TITLE
Compatibility with towny

### ISSUE THREAD

**Issue by david1104** [sinkillerj/ProjectE#435]
Hi, as i know, everyone that has used towny with the old EE2 had problems with items like rm and dm tools ecc...but a fix was made to solve this problem (mostly grief), is it possible with project-e too? :(
maybe calling block break events when using those items

**Comment by sinkillerj** [comment]
At this time Cauldron issues are not being addressed, the reason for this being that Cauldron has been dropped by its creators, when Forge is ready and the mod moves to 1.8 plugin issues will be addressed as we should have the new Sponge standard. I've also heard that fans of ProjectE have been working on forks that play nicer with Cauldron, but I do not have any information on where those can be found.
