### ISSUE TITLE
[Request] Klein star Bauble

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [sinkillerj/ProjectE#438]
Asking for the feature that Klein stars can be equipped in the Bauble slots. Preferably the Ring/Amulet slot.

**Comment by williewillus** [comment]
What benefit would they serve by being there?

**Comment by IAA-ShRaPNeL** [comment]
Being able to provide EMC to items without having to have it in your inventory.

**Comment by williewillus** [comment]
It would take up a Bauble slot (much rarer to come by) and perform the exact some functionality it has in a vanilla slot (of which there are 36)? Doesn't make much sense to me.

**Comment by MaPePeR** [comment]
The Bauble slot would be optional, so people who want to wear it in a bauble slot are free to do so.
People who don't don't have to.

**Comment by shobu9** [comment]
@IAA-ShRaPNeL Where do you want the bauble to be?

Ring? Head, Belt? All?

**Comment by williewillus** [comment]
I'd say amulet would make sense

**Comment by IAA-ShRaPNeL** [comment]
I suggested Belt, as currently there's noting in ProjectE that uses the Belt slot. All items either use ring or amulet.

**Comment by Mohron** [comment]
I'd like to see this implemented as well. As an Item that you generally want to be kept on your person the majority of the time, being able to have it tucked away would be fantastic.

**Comment by pupnewfster** [comment]
Closing as 1.14 and 1.15 have support for this (via Curios not baubles given baubles has not been updated)
