### ISSUE TITLE
Default Texture Community Vote

### ISSUE THREAD

**Issue by sinkillerj** [sinkillerj/ProjectE#439]
I have received x3n0ph0b3x's blessing to use EE2 resources in ProjectE, what would you prefer as the default?: http://strawpoll.me/3520259

**Comment by CubeWrench202** [comment]
EE2 Textures :D!

**Comment by Xee1** [comment]
EE2 texture! Also I have ported all EE2 32x Faithful textures to work for ProjectE, i Push those in official Faithful32-1.7.10 repository in the next days.

**Comment by Nova001Sol** [comment]
Original. Definitely the originals! No offense to you, but many of your textures... I don't know, I guess EE2 players are just far too used to the old ones. Consider using a config for those that prefer your newer textures.

**Comment by Brycey92** [comment]
Yeah, I'm way too used to and attached to the old EE2 textures. They provide a certain nostalgia as well. Someone should port the EE2 Sphax textures too. (I had a partial conversion started on the BDcraft site, but could not finish it.)

**Comment by Ace199102840** [comment]
yes , the current textures are poo.... xD  when i first saw the textures i nearly cried at how blah it looked.

**Comment by CubeWrench202** [comment]
Hey hey, magic_banana did an awesome job, but all the people that have played ee2 before probably didn't like the texture change.I love magic_banana work but i keep with EE2 textures.

**Comment by Parker8283** [comment]
I would ship both, and have a config option for people who want the original ones,

**Comment by FloeyGH** [comment]
EE2 :D

**Comment by CubeWrench202** [comment]
Yey, ee2 wins
