### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by PiggyWhiskey** [sinkillerj/ProjectE#440]
While in the Transmutation Tablet, I accidentally press 3 (where the tablet was) moving an Emerald to that slot and kicking out the transmutation tablet.
On reloading the world the tablet appeared to perform as normal MC function (Move to another slot)

Repeatable every time.

**Comment by williewillus** [comment]
Cannot reproduce - transmutation gui doesn't let number keys move items

**Comment by PiggyWhiskey** [comment]
This is 3 Months old....I don't even play that modpack anymore. However in the interest of testing and finding this issue, I'm loading up the pack again.

Will be testing with ProjectE-1.7.10-PE1.3.0

**Comment by PiggyWhiskey** [comment]
Project E has changed a bit since I last played with it (That had the bug) including the search bar.

The bug doesn't exist any more.

Still a little peeved it took 3 months for a reply....
