### ISSUE TITLE
Charging sound

### ISSUE THREAD

**Issue by Xee1** [sinkillerj/ProjectE#442]
The charging sound is different from old EE2, instead the discharging sound is perfect.
I tested with latest commit, I compiled the mod myself.

**Comment by sinkillerj** [comment]
This is due to a number of factors in both how sound was handled in 1.2.5, and how it was calculated by EE2. After extensive testing the current code provided the best result.

**Comment by Xee1** [comment]
Oh perfect, thank you for the answer!
