### ISSUE TITLE
Request: Disable EMC for Coloured blocks from Extra Utilities by default.

### ISSUE THREAD

**Issue by PiggyWhiskey** [sinkillerj/ProjectE#446]
Extra Utilities adds coloured versions of alot of things:
Stone, Bricks, Glowstone, Cobble, Planks, Lapis Blocks, Obsidian, Redstone etc.

When searching for any of these items (or lower items i.e. Lapis Lazuli) it is impossible as there are 16 of each colour (plus the base "uncoloured" item)
With only 12 search slots, it makes getting base items incredibly difficult and makes the Alchemical Tome useless.

The alternative would be changing the look of the Transmutation Table/Tablet to allow more than 16 slots for items.

Edit:
Another alternative would be an item that removes the recipes. So even though you have used the Alchemical Tome (or added an item you dont want in there) you can "reset" yourself should you chose.

**Comment by thejereman13** [comment]
I wouldn't mind having more slots in the transmutation table, but I agree, it is incredibly hard to find what you are looking for, especially with cobblestone.

**Comment by Carbon-Ghost** [comment]
Why not having another modern upgrade to Project E by adding a searching list that will work with the searching bar ( similar to NEI or AE2 ).

**Comment by williewillus** [comment]
We could have an "exact mode" where searches with double quotes are matched exactly only

**Comment by PiggyWhiskey** [comment]
I agree with @Carbon-Ghost 
Its all fine and well to re-imagine EE2. But you'll need to keep up with the times.
Search bar other than NEI (Which I use for the recipe I'm currently working on etc.)
Or a grid like a chest instead of the standard slots.

**Comment by Carbon-Ghost** [comment]
I just wanted to give some ideas for improving ^.^
