### ISSUE TITLE
[SUGGESTION] Block Recipes Phil's Stone

### ISSUE THREAD

**Issue by Nova001Sol** [sinkillerj/ProjectE#448]
Hi, I'd like to request the addition of a few simple recipes for the Philosopher's Stone. To keep it simple, I'd like to be able to transmute blocks of material A into blocks of material B. So eight blocks of iron to a block of gold and four blocks of coal to a block of alchemical coal. Stuff like that. Trust me, transmuting around thirty stacks of iron blocks into diamonds gets terribly annoying if you need to do it in ingots. Transmuting stacks of blocks would make it far easier.

**Comment by MaPePeR** [comment]
Why not use the transmutation table?

**Comment by sinkillerj** [comment]
This can be done using the transmutation table, or by adding the recipe with another mod.
