### ISSUE TITLE
[Request] Dark Matter Pedestal

### ISSUE THREAD

**Issue by Imperum** [sinkillerj/ProjectE#449]
If there is even the slightest change, I would love to see the Dark Matter Pedestal make it's comeback! It has great functions that would add some real nice features to this already great mod!
http://tekkitclassic.wikia.com/wiki/DM_Pedestal

**Comment by CubeWrench202** [comment]
I'd like to place the watch of flowing time there like in the past.

**Comment by sinkillerj** [comment]
This is planned however a estimate on implementation is currently not available.

**Comment by williewillus** [comment]
I've started a bit of work on this (see the fork on my repo), doesn't look to be too bad.
No eta because of school though.
I need to do a little research on TESRs on how to render it :p
