### ISSUE TITLE
[Feature] Protection plugin compatible block breaking/placing/interaction

### ISSUE THREAD

**Issue by Brycey92** [sinkillerj/ProjectE#450]
I'm not sure if this is possible in Cauldron, but if ProjectE had cancellable block interactions using something like a fake player, griefing could be prevented by Bukkit plugins such as WorldGuard, Towny, Griefprevention, etc.

**Comment by MaPePeR** [comment]
#380

**Comment by Brycey92** [comment]
Right, forgot to check closed issues. My apologies.
