### ISSUE TITLE
Weird issue with Gem Of Eternal Density consuming everything in Alchemical Bag

### ISSUE THREAD

**Issue by Kilobyte22** [sinkillerj/ProjectE#453]
Earlier today i encountered an issue: I had a full Alchemical Bag with a black hole band and a Gem Of Eternal Density. At some point when i checked the bag, it was empty. I didn't try reproducing it before upgrading Forge (i was running build 1208), but could not reproduce it after the upgrade. I am running version 0.2d-dev14 of ProjectE. No mods besides Forge and ProjectE are installed. [Here is a debug crash log](https://gist.github.com/Kilobyte22/2930db460b170780073a)

**Comment by MaPePeR** [comment]
@sinkillerj also fixed: one of the old bag wipes... (0.2d-dev14 is not supported anymore anyway...)
