### ISSUE TITLE
Request: Allow Comparator to detect contents of Energy Condenser

### ISSUE THREAD

**Issue by PiggyWhiskey** [sinkillerj/ProjectE#455]
The idea behind this is to allow automation with AE2.

Concept: Rows of Energy Condensers (MK I or II) with storage bus. Comparators out the back to item conduits.
It will try to put a Diamond Block (or other medium EMC item) into the energy condenser which then converts to the items and activating the Comparator.

**Comment by williewillus** [comment]
Req close feature implemented (#709)
