### ISSUE TITLE
NEI is no longer necessary ?

### ISSUE THREAD

**Issue by Au2laDeNosReves** [sinkillerj/ProjectE#456]
Hello,

Following the last update, you put that NIS is not necessary when I search for seeds I still do not see those minecraft because there is too much with all the mods how should we do to display them in through the search engine?

I tried Seeds and 295 seeds

Yet I search the internet without meers

thank you

Original Message :

Bonjour,

Suite à la dernière mise à jour, vous avez mis que NEI n'est plus nécessaire, quand je recherche des seeds je ne vois toujours pas ceux de minecraft car il y en a trop avec tous les mods comment doit on faire pour les afficher dans le moteur de rechercher ?

J'ai essayé Seeds et seeds 295

J'ai pourtant chercher sur internet sans succé

Merci

**Comment by Nova001Sol** [comment]
If you put an item in the middle with a value of 16 EMC you will only see items with 16 EMC or less, like seeds. If you then search seeds you will probably find them.

**Comment by Au2laDeNosReves** [comment]
Thank you this trick works for seeds but not for all. For example I want a Auto Workbench (160 EMC) BC Factory which has the same EMC a book (160 EMC)

Normally if I put the book I should see the workbench and the book off the workbench not it does not work.

I'm on the Rise modpack Resonant 3.

Original Message :

Merci cette astuce fonctionne pour les seeds mais pas pour tout. Par exemple je recherche une Auto Workbench (160 EMC) de BC Factory qui a le même EMC qu'un livre (160 EMC)

Normalement si je met le livre je devrais voir le workbench et avec le workbench le livre hors non cela ne fonctionne pas.

Je suis sur le modpack Resonant Rise 3.

**Comment by Nova001Sol** [comment]
Have you taught the auto workbench to the transmutation table? If so, just use the search bar.

**Comment by Au2laDeNosReves** [comment]
Yes, I use the search bar and used the Alchmical tome, so I all objects with EMC.

When I open the transmutation table, I put a book (EMC 16) to display the Auto Workbench (EMC 16) but does not work here.

Original Message :

Oui, et j'ai utilisé le Alchmical tome, j'ai donc tous les objets avec de EMC.

Quand j'ouvre la transmutation table,  je met un livre (EMC 16) pour afficher le Auto Workbench (EMC 16) mais çà ne fonctionne pas.

**Comment by Nova001Sol** [comment]
Strange. Try making one yourself, then teaching it to the table. Perhaps the table forgot the auto workbench.

**Comment by Au2laDeNosReves** [comment]
I restarted my Minecraft and retried the experiment. And oddly this now works I understand nothing. Sorry for the inconvenience. If the trouble I would look again cause a problem before posting.

Original Message :

J'ai redémarré mon Minecraft et retenté l'expérience. Et bizarement çà fonctionne maintenant je comprend plus rien. Désolé pour le dérangement. Si le soucis recommence je rechercherais la cause avant de poster un problème.
