### ISSUE TITLE
username change = lose all emc and knowledge

### ISSUE THREAD

**Issue by tekman123** [sinkillerj/ProjectE#457]
With this new username change thing mojang has implemented chins a new problem.  If u do a username change you lose all emc and knowledge of anything taught to the tablet.

**Comment by sinkillerj** [comment]
This can be restored by editing the ProjectE subfolder of your world with a NBT editor.

Unfortunately I discovered that Moze used usernames very recently, and I haven't had time to implement a fix.

**Comment by MaPePeR** [comment]
@sinkillerj i think this is fixed by the alchbag-refactor
