### ISSUE TITLE
Crash when transmutation table searching

### ISSUE THREAD

**Issue by thejereman13** [sinkillerj/ProjectE#458]
Any time I search using more than 3 characters, I crash (the server doesn't) with is error: http://pastebin.com/a4zWpcke
I am using the latest version (PE1.1.0) as of typing this.

**Comment by sinkillerj** [comment]
"java.lang.ArrayIndexOutOfBoundsException: 15
        at mekanism.client.render.item.ItemRenderingHandler.renderItem(ItemRenderingHandler.java:420)"

Your client is having trouble rendering a Mekanism item, find out which it is and send them a report.

**Comment by thejereman13** [comment]
Well Project-E was the only mod I updated, and the exact same search term worked through NEI on the dev14 build
