### ISSUE TITLE
Remove the 'Another user is using this Transmutation Tablet'-Lock

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#461]

**Comment by williewillus** [comment]
Should we decouple the transmutation gui from the tileentity/block that activates it? (Make it like the vanilla crafting table -- per player GUIs) or should players be able to see other players' changes live?

**Comment by MaPePeR** [comment]
in the recent version the emc and knowledge is stored per player and not in the table, so there should be no problem to make it a multi-user table like crafting table (So in the way they work at the moment it is not possible to make other players see the changes anyway)

The problem with this locking mechanic is, that the Submod-Notification close the GUI in a way, that locks the table even in singleplayer and one has to reload the world/break the table to use it again. So i think the easiest fix for this is to just remove that locking because we don't need it anyway.

**Comment by MaPePeR** [comment]
@sinkillerj implemented
