### ISSUE TITLE
Texture Bug

### ISSUE THREAD

**Issue by Xen1290** [sinkillerj/ProjectE#466]
It seems when you put a stack on collector the arrow has a strange texture, see this:
Latest version of ProjectE
![s](https://cloud.githubusercontent.com/assets/8685029/6076925/c9bed948-ade9-11e4-819d-f69177ab4f92.png)
And the RM furnace need a fix:
![fd](https://cloud.githubusercontent.com/assets/8685029/6076955/4bc9d550-adea-11e4-8848-c76bd74b32a8.png)

**Comment by Xee1** [comment]
Hello? Why Pull request #482 isn't merged?

**Comment by williewillus** [comment]
fix was merged
