### ISSUE TITLE
creeper head unlock dupe

### ISSUE THREAD

**Issue by BloodyError** [sinkillerj/ProjectE#468]
Hey there.
I'm playing the 'Madpack 2' mod pack at the ATlancher, I don't know what version of 'ProjectE' I'm playing but the pack is in the last update.

Most of the time I can't put the Magical crops stuff inside the Transmutation table, but once i killed a creeper and got his head, I logoff and move into a creative world to test stuff and when I came back into my world I found out that the creaper head is giving 1,438,580,736EMC.
That's right, 1,438,580,736 EMC! and after that I also found out i can put magical crops stuff in the table and alot of new stuff.
after you close the game the bug "fix" itself, but when you leave you world, move to creative and comeback to your world (while holding a creeper head) the bug unlock the table and you can dupe what you want.

BTW, when this happen and you 'unlock' the table, the chances that your world will crush are much bigger.
I had to reset my knowledge file so i can login back to my world.

**Comment by BloodyError** [comment]
![head](https://cloud.githubusercontent.com/assets/10886409/6084801/dd174284-ae3c-11e4-8235-b07143053385.PNG)

**Comment by MaPePeR** [comment]
this sounds like it might be the same issue as #467, but with an old version of ProjectE. 
I think the Madpack 2 with the updated ProjectE is not yet public.

**Comment by BloodyError** [comment]
You're right.
The current version in the pack is 'Alpha 0.2c" and from what i see that are 7 new version...

Well, I'll try to update it myself and check if it still happen...

**Comment by MaPePeR** [comment]
That is indeed very interesting...

**Comment by Kolatra** [comment]
This should be fixed by the GraphMapper.
