### ISSUE TITLE
gem of eternal density dupe bug

### ISSUE THREAD

**Issue by Sailren** [sinkillerj/ProjectE#469]
when u target red matter in the gem and activate it and then use right click to set the white/black list it just dupes free red matter w/o any work, also works for dark matter

http://abload.de/img/2015-02-06_23.08.35ucalv.png

http://abload.de/img/2015-02-06_23.13.05udldh.png

http://abload.de/img/2015-02-06_23.13.1274ata.png

version i use is the current one on curse forge

**Comment by Sailren** [comment]
most of them are fake items, but i can still dupe them with some time

**Comment by Kolatra** [comment]
I can't reproduce this, do you know if this still happens on our latest versions?

**Comment by williewillus** [comment]
I can't reproduce on latest master

**Comment by therpluma7** [comment]
i can say i was able to dupe items just buy changing modes with gem on

**Comment by therpluma7** [comment]
and upon farther testing i can narrow it even farther in the transmute from gold to diamond
your getting more than the 2048 emc your supposed to get resulting in emc gain in large quantities over time it may also be happing with iron this only seems to be an issue with the gem of eternal density though

**Comment by therpluma7** [comment]
let me provide more info i just tossed a stack of gold in and cycled going from red matter mode to iron mode i got 466k emc worth of iron even though there was only 130k in the gem

**Comment by williewillus** [comment]
can't repro anymore
