### ISSUE TITLE
QED bugging on transmutation table

### ISSUE THREAD

**Issue by Zaflis** [sinkillerj/ProjectE#474]
QED is another block from Extra Utilities. It has a nasty habit of changing its item name constantly. Such as Quantum Enrichment Device, Quark/Electron Director etc...

This causes a big fuss on the transmutation table, such that trying to take one out puts it right back and refunds the EMC value. Server and client aren't in sync in this either, so if i search for "tra" for "trash can", it might pick up QED when it happens to go that slot. Just that my client doesn't see QED on the table itself. So it's actually changing its search name with that, and happens to include "tra" in its modname! exTRA utilities. I can often times pick items out from the empty slots too, so definitely something is not in sync with what is on table actually.

ProjectE-1.7.10-PE1.1.0

**Comment by MaPePeR** [comment]
This can be closed now... hopefully... finally :heart:
