### ISSUE TITLE
transmutation tablet glitch

### ISSUE THREAD

**Issue by mexicansuperdubi** [sinkillerj/ProjectE#479]
when taking out some obsidian it turns into and enderpearl, when i take anything out of the tablet that isnt in the center 4 slots its randomly changes into a different item can you help me get rid of this using resonant rise 3 at the moment

**Comment by mexicansuperdubi** [comment]
also my friend and i are on a server he is hosting

**Comment by MaPePeR** [comment]
Duplicate #444, #413 and #419 and #423

**Comment by sinkillerj** [comment]
Please ensure that you are using the latest version.
