### ISSUE TITLE
Crash When trying to shift click a Klien Star Omega into Mercurial Eye

### ISSUE THREAD

**Issue by anexusarchon** [sinkillerj/ProjectE#481]
[Crash Log](http://pastebin.com/ZbQ1pyMA)

**Comment by anexusarchon** [comment]
It appears to also happen when attempting to shift click a Klien Star Omega Out of the Mercurial Eye

**Comment by shobu9** [comment]
hum.. the star errored so tge Mecurial eye spams until crash... i've never seen that XD
