### ISSUE TITLE
Morningstar Glitch

### ISSUE THREAD

**Issue by spAnser** [sinkillerj/ProjectE#484]
There is no crash log because the game didn't crash but the morningstar went a little overboard today.

I had it charged up twice so 5x5 was the area i was trying to dig some dirt out and then all of a sudden i was below my base and there was a ton of mobs that were frozen in place. I rebooted my save because I wasn't sure what happened and then I logged back in to see this.

http://puu.sh/fMUIt/550e60fa65.jpg

It kind of mined all of the gravel about 6 blocks below my base in roughly a 3x3 chunk area it not more.

I am using "Realistic World Gen" so most of that empty space was gravel maybe the morning star glitches a little with gravel and how it falls? That gravel on the right was placed back there because i need the water to not be flowing into the shaft on the far right.

**Comment by spAnser** [comment]
Did some more testing created a superflat gravel world that was 60 gravel deep and it digs way to much gravel.

I am still trying to get the world to load for a screenshot but from the quick look at the minimap it mined up 14 chunks of gravel all the way to the bedrock. It just lags out when trying to get it to load.

**Comment by sinkillerj** [comment]
This is intended functionality: http://tekkitclassic.wikia.com/wiki/Red_Morning_Star

**Comment by spAnser** [comment]
I might agree with you if I right click which is not the case
