### ISSUE TITLE
Transmutation table, not transmute item

### ISSUE THREAD

**Issue by DangerousDan996** [sinkillerj/ProjectE#486]
I have Learned all the current item, I have in my would. It works when I burn up a item but not when I put a item on the left. Here are some picture and mods, I am used in the client.
![2015-02-11_22 11 31](https://cloud.githubusercontent.com/assets/3757569/6160637/0cdfd924-b23c-11e4-94ba-e91276c07ee5.png)
![2015-02-11_22 17 00](https://cloud.githubusercontent.com/assets/3757569/6160636/0cddf19a-b23c-11e4-8aa1-de4a0f24effd.png)
![2015-02-11_22 17 04](https://cloud.githubusercontent.com/assets/3757569/6160640/0ce08d4c-b23c-11e4-8ff9-679254690a04.png)
![2015-02-11_22 17 16](https://cloud.githubusercontent.com/assets/3757569/6160639/0ce070b4-b23c-11e4-9632-7045c33e0070.png)
![2015-02-11_22 17 28](https://cloud.githubusercontent.com/assets/3757569/6160638/0ce06f42-b23c-11e4-9ca5-69cdff3dee3a.png)

Here the mod list for the client.
 Minecraft Forge 
Buildcraft
Mystcraft
Thaumcraft 4
Waila
Secret Room!
Tinker'sConstuct
Tinkers' Mechworks
Iron Chest
Bibiolacraft
TF2 Teleport
Player API
Smart moving mod
Factorization
Thermal Expansion
CoFH Core
Thermal Foundation
Forestry
Binnie Mods
Chisel
open block
Railcraft
Carpenter's Blocks
AromaBackup
Aroma1997Core
Logistics Pipes
Natura
Steve Carts 2
ChickenBones Core
ChickenBones NEI
ChickenBones Ender Storage
ChickenBones Wireless Redstone
Chicken Chunck 
Translocator
Forge Mircoblock
Applied Energistics 2
Project: Red
Numina
Better Title Screen
Jabba
Hats mod
Hats Stand
ichun until
EnderIO
Ender Zoo
Machinemuse's Modular Powersuits
Project E
Inventory Tweaks
Obisdiplates
Extra Utilites

Minecraft Version 1.7.10, Minecraft forge Version 1.7.10-10.13.2.1291, Project E version 1.7.10-PE1.1.0

**Comment by sinkillerj** [comment]
ProjectE does not support this feature, if you wish to use EMC from a item you will need to burn it.
