### ISSUE TITLE
Suggestion: Add config options to disable everything

### ISSUE THREAD

**Issue by gluff95** [sinkillerj/ProjectE#487]
After having just fixed my server from a Project E related crater incident, I strongly support a feature where in the config file, server operators can disable absolutely everything. Bukkit plugins are not foolproof at this time and the destruction of my spawn occurred using an item that had been banned.

**Comment by williewillus** [comment]
Do you mean separate config options for everything or a single config that disables "anything"

**Comment by ScarecrowKrone** [comment]
In the ProjectE.cfg file, there should be options to disable everything that could possibly destroy/break shit.

**Comment by IAA-ShRaPNeL** [comment]
I believe he means something like a Item.Cfg, in which it lists out every ProjectE item/block = True/false, setting one of the items to False effectively removes it from the game.

**Comment by williewillus** [comment]
use MT to remove the recipes for items
