### ISSUE TITLE
EMC Calculations off?

### ISSUE THREAD

**Issue by iHeartZigg** [sinkillerj/ProjectE#490]
I noticed that with some Iron recipes, the EMC calculations are a bit off.

Iron Chest gets a value of 64 EMC and there's a few others that i noticed too but unfortunately i can't remember them.

Sorry there's not a lot of information i can give you about this issue, haven't looked at the code and there isn't much else to say about it.

**Comment by MaPePeR** [comment]
Yea, there is something off with the IronChests. I have no clue what, though. Its really weird.

For now i would recommend to set the value manually for these.

**Comment by iHeartZigg** [comment]
It's not just IronChests, i saw it on a few other items but i couldn't remember them while i wrote this.

I'll try to find them when i have free time, maybe that'll help narrow this thing down :)

**Comment by MaPePeR** [comment]
Yes, there are tons of them, but the iron chest one is kind of different, because it does not involve smelting like most of the others and is not fixed by the new mapping code I'm going to introduce.

**Comment by MaPePeR** [comment]
@sinkillerj this should also be fixed with graphmapper
