### ISSUE TITLE
Red Matter Morning Star functionality

### ISSUE THREAD

**Issue by Cobbs3** [sinkillerj/ProjectE#496]
In EE2 the morning star would act as a multitool capable of breaking almost everything instantly.

In project-E on any power level higher than no charge it will act like the old morning star does on a right click, personally I preferred the old version of it, as it was more useful for me. Perhaps you could add a config option so that people can have either function?

I just find it quite annoying as my hotbar is now filled with red matter tools, whereas back with EE2 I would have only two on my hotbar now I have four.

I hope you consider this as I would love to see the old functions return.

**Comment by carlobon** [comment]
yes, it's true it was better in the old ee2

**Comment by williewillus** [comment]
Morning star is now functionally very similar to ee2 after the refactor #620

**Comment by Cobbs3** [comment]
Nice that is good to hear, I will close this now then I guess seeing as it has been forfilled
