### ISSUE TITLE
Dark matter axe causing NullPointerException

### ISSUE THREAD

**Issue by Anoyomouse** [sinkillerj/ProjectE#497]
I've been playing on a server with the FTB Insanity Reloaded pack: http://forum.feed-the-beast.com/threads/1-7-10-ftb-insanitys-return-v-2-0-0.59727/
I updated ProjectE to the latest build from your download link, as the version it comes with is incredibly unstable.

We built an "old-school" tree farm with a deployer and a dark matter axe, you click the button to eat the trees and then the server throws some massive errors (https://gist.github.com/Anoyomouse/6b33191c3bec308e8959) which seems to be a network issue that the axe is trying to use a player reference or something which doesn't exist in a deployer.

After these errors if you use the search function on the transmutation table it errors out on the client and kicks you back to the main menu where you just have to log back in.

I can try and trap the client errors as well if you think they'll help

Thanks

**Comment by Anoyomouse** [comment]
Just an update, after searching BluePower's repo, i found they use a FakePlayer to right click the axe, which causes this line https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/items/tools/DarkAxe.java#L118 pass through a MinecraftForge.FakePlayer, which might have problems with the PacketHandler

Not sure why this causes the next packet sent to crash out the client, but it does

**Comment by williewillus** [comment]
This should no longer happen - Packets are no longer sent to fakeplayers

**Comment by Kolatra** [comment]
Closing this one, if it happens again, I will reopen it.
