### ISSUE TITLE
Please update the files

### ISSUE THREAD

**Issue by rhyssean** [sinkillerj/ProjectE#499]
I have had a few problems, all of which already posted on the issue forums, so I would like to ask if you could either update the current patch with the files and code presented in issue #459, because it seems I'm not able to do it myself.

**Comment by sinkillerj** [comment]
Version 1.2.0 can be found at: http://minecraft.curseforge.com/mc-mods/226410-projecte/files

**Comment by rhyssean** [comment]
The update did not seem to work. I go onto my server, and search glowstone. I get to type the "g", but then I type "l" and it crashes my client
