### ISSUE TITLE
NullPointerError with Dark Matter Axe

### ISSUE THREAD

**Issue by Kolatra** [sinkillerj/ProjectE#501]
http://pastebin.com/bUwnwkrW

Using 1.2.0.

getCharge and getMode return null when using an item without pressing 'V' first.

This is also with any item that has a charge.

**Comment by sinkillerj** [comment]
This shouldn't be possible, how do you obtain the item? Can you reproduce this in a environment with just ProjectE?

**Comment by Kolatra** [comment]
I crafted the item legitimately, however I cannot reproduce it, trust me I tried. I honestly have no idea what's going on.

**Comment by williewillus** [comment]
assuming fluke or fixed
