### ISSUE TITLE
(suggestion, ideas ) 

### ISSUE THREAD

**Issue by Ace199102840** [sinkillerj/ProjectE#504]
while crafting gem armor , i come to realize how much it pretty much puts you in creative , with the night vision and flying ....  EE2  used to have a cost to these things via klein star to keep flying and seeing in the dark.  why is that not the case anymore?  there should be an option to have these costs for servers in the config file. having the option would be nice. 

 have it on false as default

gem armor abilities cost EMC = true/ false

also i could be right or wrong , its been a long time since i played tekkit ,  didnt you used to have to fill up the omega star to its max to use it in the crafting of any of the gem armor parts? now you can just craft it with an empty star.   could there be an option for having a star filled or empty  in the configs as well for difficulty? 

( omega star has to be filled to max with EMC to craft gem, default is false)

omega star filled = false

and if someone on their server wanted their friends to try harder for that gem armor they could change it to true. 

there also used to be a feature that would push mobs away from you while wearing the gem armor that you could turn on and off. this also used EMC from a klein star. like a TON  of emc. it worked like as if there was an interdiction torch inside.  could this feature also be implemented?  

also do you plan on putting in the dark matter pedestal?

**Comment by williewillus** [comment]
1. Gem armor was always free. config may come later
2. Once someone figures it out, that recipe will be fixed (there is another ticket for it)
3. Pedestal is in ;)
