### ISSUE TITLE
electric age mod and tome

### ISSUE THREAD

**Issue by epicbastion** [sinkillerj/ProjectE#505]
i enabled the tome in the config on my server using the latest version.  no recipe comes up for the tome in nei and the old recipe does not seem to work.  i switched to creative gave myself a tome and then the real problem started.

i had electric age, latest version from solitary craft installed, after i installed the tome when ever i searched for anything when i would put a space in after a word or a search would return anything of lesser value i would get a full list of unnamed paint rollers from electric age.  so if i searched for hardened glass at emc 192 it would give me a full circle of unnamed which were just paint rollers from electric age.

i removed electric age at this point and the search function seems to be working again.

although when using nei on my server an nei search does not return anything in the tablet or table is there a config option that needs to be set a particular way so nei will control the tablet/table search?

**Comment by sinkillerj** [comment]
NEI no longer has any integration with the table, the gui now has its own filter box.
