### ISSUE TITLE
Firing a water projectile from the Evertide Amulet causes a crash

### ISSUE THREAD

**Issue by mccoole** [sinkillerj/ProjectE#507]
Given the crash file it seems to be a problem in Sanguine Utilities and I'll file an issue there but thought I would still bring it up as a possible compatibility issue.  The crash is at: http://pastebin.com/Mrf81GER  Thanks!

**Comment by sinkillerj** [comment]
Looking over the crash I dont think theres anything I can do on my end, but if they discover something i need to change feel free to report back.

**Comment by mccoole** [comment]
It didn't look like it was on Project E's end to me either when I read the crash but I thought I'd send it along just in case there was something less obvious I wasn't seeing. Thanks for taking a look and thanks for Project E. I'm having a blast playing it as part of a home grown mod pack.
