### ISSUE TITLE
projecte bypassing protections

### ISSUE THREAD

**Issue by landlife** [sinkillerj/ProjectE#508]
Hi there.  it's too easy to grief using Projecte tools and the damage is bad because it can't be rolled back by  plugins. i thinks this comes cus  tools don't route block break events through server, so server has no idea any blocks are even being destroyed when someone right clicks your marble building with their Projecte tools.

I know this was an issue with ee2 aswell and you were able to download a patch for this so it did get logged with griefprevention and rollback plugins like core protect is there any chance project e can support plugins like Griefprevention in a later stadium ?  Thanks

**Comment by sinkillerj** [comment]
Cauldron has been abandoned by its creators and there are no plans to add special code to support it at this time. Plugins will likely be supported in 1.8 as there is a new standard which will be builtin to Forge.
