### ISSUE TITLE
bug alchemical bag

### ISSUE THREAD

**Issue by nitsuga5124** [sinkillerj/ProjectE#511]
my alchemical bag (red) lose al his inventory. i lose a lot of emc, i was 8 klein star omega full D:

**Comment by MaPePeR** [comment]
Which version of the mod?

**Comment by nitsuga5124** [comment]
ProjectE-1.7.10-PE1.2.0

**Comment by nitsuga5124** [comment]
and my black bag too

**Comment by rmallo** [comment]
I can confirm that this is not an isolated incident - it's been happening to me, too. It happens at absoloute random, sometimes without even logging in or out - I left a Solar Flower to run for two hours while I was out, and came back to find my bag had been voided.

**Comment by rmallo** [comment]
Further information on this from further testing - Deleting my bag data fixes it for a while, but eventually it happened again. It happens during gameplay as well. When reading the MultiMC console window, there's nothing that indicates when and why it happens. It seems to trigger at total random, but part of me is thinking it may be due to the repeated saving of alchemical bag data. Is there any way to reduce the amount of times the bag data saves to minimise this bug until there's a more concrete soloution for it?

**Comment by carlobon** [comment]
it happened also to me

**Comment by nitsuga5124** [comment]
in PrejectExchenge 1.3.0 still losing items

**Comment by nitsuga5124** [comment]
Try to put the alchemical bag info in the level.dat archive

**Comment by PhoenicsThePhoenix** [comment]
Still getting this bug, I dropped the latest ProjectE into Direwolf20 and my Alchemical Bag vaporized all my thaumcraft gear. it seems to be completely random. this really needs to be fixed asap, as it basically renders Alchemical Bags completely useless.

**Comment by PhoenicsThePhoenix** [comment]
Tested again with just ProjectE and Not Enough Items, single player, and i tried putting the bagdata on the same level as level.dat, still no luck.  it completely wipes any and all contents of all alchemical bags, even ones in saved inventories in NEI, randomly dumps all data. very frustrating. it must be something to do with the files, as i filled the bags with a random assortment of items from vanilla and PE and a tried other mods too, same result. hope this can get fixed soon!

**Comment by williewillus** [comment]
@PhoenicsThePhoenix can I get a copy of logs/fml-server-latest.log from the serverisde/ssp? Or whichever log it was at the time this happened

**Comment by PhoenicsThePhoenix** [comment]
@williewillus as far as I can tell, nothing shows up in the log, and I didnt get a copy of the log. not sure how to either to be honest.. like a crash log? or a .gz?

**Comment by williewillus** [comment]
yeah the .gz's are just compressed old logs so if you can find the one from the time you lost data then it'd be great in helping me narrow down where exactly in code this happens

**Comment by PhoenicsThePhoenix** [comment]
I have about 7 different .gz logs from that day, and as far as i am aware its probably in all 7, because i hadn't played until I dropped in the mod. any suggestions/preference  for a site for uploading?
