### ISSUE TITLE
Tome crash

### ISSUE THREAD

**Issue by Neil5043** [sinkillerj/ProjectE#512]
When I put them tome in the burn slot I crashed. Whenever I use the transmutation table I crash now here is the report.

https://gist.githubusercontent.com/anonymous/131c627930ba27c92ff5/raw/gistfile1.txt

**Comment by Nova001Sol** [comment]
I recommend posting the crash log next time, not the regular one. The crash log can be found in crash-reports, a folder located in the same place your mods folder is. Also, your Botania is outdated, as are several other mods.

**Comment by MaPePeR** [comment]
I have not checked this, but I assume, that this is the npe, that is supposed to be fixed in the recent version? (there should be a few duplicates of the bug I'm talking about)

**Comment by Neil5043** [comment]
It is fixed in the latest version because it disables putting the tome in the tablet. But sadly my player still crashes whenever I search. Also a crash log is a condensed version of this most people dont like them.

**Comment by Kolatra** [comment]
I looked at this, and don't believe it's an issue on our side. Some other mod is causing some display-name to return null, and we try-catch for that here. https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/container/inventory/TransmuteTabletInventory.java#L185

**Comment by williewillus** [comment]
display name null was ExU, issue was solved
