### ISSUE TITLE
Transmutation tablet crash

### ISSUE THREAD

**Issue by chese61** [sinkillerj/ProjectE#514]
Been talking with Kolatra to try and solve the issue, been redirected to sinkillerj.
The crash is caused by something, we can't find the exact source, but It seems to happen when 
it is used on a block with an inventory.
http://pastebin.com/h2aX1EvJ

**Comment by Kolatra** [comment]
Just looked through this again, you're using an old version that had some broken NEI integration. Try updating the mod.
