### ISSUE TITLE
Water Bucket EMC value is off 

### ISSUE THREAD

**Issue by WTFFFS** [sinkillerj/ProjectE#515]
A bucket of lava and a bucket of water have the same EMC value at default settings in version 1.2.0 in my current world. An empty bucket is correctly 768, a bucket of lava and a bucket of water are both 832, I believe this is incorrect due to the ease of an infinite water source?

**Comment by Tencao** [comment]
You're correct going by this at least. The water bucket emc value should be the same as the normal bucket, thanks for pointing that out.
http://tekkitclassic.wikia.com/wiki/EMC

**Comment by MaPePeR** [comment]
when i checked the last time the water bucket had the right default emc value.

This might be caused due to crafting recipes that yield a water bucket, that mess up the emc generation.

Which will hopefully be resolved when i finish implementing #376.

**Comment by sinkillerj** [comment]
Closing as this issue is related to the old mapper, it has now been replaced with the GraphMapper.
