### ISSUE TITLE
Suggestion: Add config option to be able to sync the transmutation tablet with NEI again

### ISSUE THREAD

**Issue by ThisisCanada98** [sinkillerj/ProjectE#517]
Having Nei integration with the tablet was an amazing idea and worked great, and now im having problems finding things I want because the lack of integration.

**Comment by sinkillerj** [comment]
This will not be returning, we simply have no access to things we need server side. In the future our own filtering will be improved.

**Comment by MaPePeR** [comment]
It should be possible to enable the NEI-aware-searching in singleplayer-only though, shouldn't it?
