### ISSUE TITLE
Autonomous Activator and ProjectE tools 

### ISSUE THREAD

**Issue by Mattabase** [sinkillerj/ProjectE#518]
1. When using the ProjectE tool right clicks in the AA it causes this spam in the server log.

2. If you have tool in the AA and you hit a ProjectE Keybind you time out. Server reports this. 

http://goo.gl/nnVS8p

Both part of the same log.

**Comment by williewillus** [comment]
Hmm it seems to be choking because we're sending a packet for the client player to aesthetically swing their arm.... TE should be ignoring all packets sent to the fakeplayer, so I don't really know if this is our issue
