### ISSUE TITLE
Watch of time + Condenser/collector

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [sinkillerj/ProjectE#520]
Currently, the Watch of flowing time speeds up Condensers and Collectors. This leads to the ability to quickly generate tons of EMC. 

Also to note, The Time torch from Torcherino also works on them.

**Comment by MaPePeR** [comment]
i thought this was working as intended?

**Comment by rmallo** [comment]
It's meant to be like that. EE and by proxy Project E was dubbed super-powerful for a reason.

**Comment by IAA-ShRaPNeL** [comment]
Ok then. I just think it's a bit too powerful.
