### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Ace199102840** [sinkillerj/ProjectE#522]
it would be amazing if there was a command that allowed you to view other players inventory bags  and possibly inventory  to check for people who grief/steal  and store the stuff into their alchemy bags. it would be an easy way to catch people who think they can get away with by hiding their stuff in the bags.

**Comment by Nova001Sol** [comment]
This would be awesome for servers, full support. I'd like to add to this, however. The command should also allow the user to add or remove (or at least remove) items from the bags, this to let them return stolen items on servers where stealing is not allowed, or to remove items that were cheated in somehow.

**Comment by Ace199102840** [comment]
ya i shoulda been more specific about that.  there should be a command that will open a player's bag and you have to specify the color , or maybe it will just say what colors they have been using so you know what bags are likely to have stuff in them. and be able to see and take/remove and add items. 
maybe something like , 

/peek_bag (screen name) (color)     this would be to open that inventory for that specific bag 
/peek_bag (screen name)                  this would just show what bags he has stored items in so that way you you dont have to check in every single color in case they haven't made a specific one and you dont have to fish for the correct color.  

in EE2  you could easily just swap their bags since they was attached by screen name and replace the name of the file with your name and take out the items. but i noticed that sinkillerj has the data stored in one file. . i cannot do this anymore since the bag data is stored completely different.  i had to use this trick to take back some stuff that a malevolent griefer  stole. but i cannot access his bags since technically my screen name is attached to my bag data instead of his, regardless of his inventory being mine.

sorry bout the wall of text xD  ( really passionate)

**Comment by Brycey92** [comment]
I also think this would be an incredibly helpful tool for administrating servers.

**Comment by tyler489** [comment]
Ee2 had a plugin /openalc

**Comment by Adkkid** [comment]
@sinkillerj @williewillus @MaPePeR @Lilylicious 
I dunno what the general etiquette is here on pinging everyone, but I could really, really use this enhancement. Being able to look into people's alchemical bags on a server is actually really important. In my case specifically, it's really crucial that we keep a constant watch on the players, and yet everyone has easy access to a place to hide banned items or other things that we need access to. We've run into problems with it before, and without this feature, we may have to cut the mod, which would suck, since it's a big part of the server.

**Comment by Brycey92** [comment]
I second @Adkkid's plea. My server could really use this feature, and the time and effort it would save on manually checking people's Alchemical bags would greatly outweigh the time it would take to implement it. Of course, it's a bit of your time to save a lot of my time, but I would really really appreciate it if one of you would work on this. Thanks!

**Comment by williewillus** [comment]
Okay. Consider this accepted for 1.9+
My time is split between school, Botania, and PE though, so the ETA for this is undefined. It'll happen though

**Comment by Brycey92** [comment]
I was actually wondering if this could be implemented or back-ported to 1.7.10 at some point in the undefined future? I and my server are stuck on 1.7.10 since most of the mods we use haven't even updated to 1.8.x

**Comment by Adkkid** [comment]
Actually, the same applies to me. We're probably not going to be updated to 1.8, let alone, 1.9 for quite some time. I know old versions definitely aren't a priority, and you have a lot else to do, but it would be awesome to get 1.7 support.

**Comment by sinkillerj** [comment]
Ill consider it for 1.7, but its also not terribly hard for a custom plugin to read the NBT from the player file.

**Comment by pupnewfster** [comment]
I think this can be closed as there is a showBag command in 1.12, and the version of mc this issue was made on is no longer being updated.
