### ISSUE TITLE
Feature Request - Multiple sites in Transmutation Tabe/Tablet

### ISSUE THREAD

**Issue by MSandro** [sinkillerj/ProjectE#527]
I think it would be great if there was the possibility to switchen in the transmutation table / Tablet between pages. Many mods add e.g. colored blocks. How much will not appear in the table, if you used the "Tome of Knowledge".

I hope some of the Devs can add this feature son.

**Comment by Hades99** [comment]
this is a good idea

**Comment by MaPePeR** [comment]
This can be closed. @sinkillerj
