### ISSUE TITLE
Alchemy Bags rarely loose all its content

### ISSUE THREAD

**Issue by accessdenied0** [sinkillerj/ProjectE#529]
Dear sinkillerj,

In referring to https://github.com/sinkillerj/ProjectE/issues/511 it happens very rare cases, mostly if I used the "Gem of eternal density" in my bags, that it looses all its content.

In my console wasn't any strange crash report at or around this time only the code: 
http://pastebin.com/VQxQNBaP

It seem to be an issue with Inventory Tweaks or the saving of the data isn't work correctly... I hope I could help to fix this issue.

access_denied

**Comment by sinkillerj** [comment]
Please do not create duplicate issues.

**Comment by accessdenied0** [comment]
With respect,

I did/do because the last time I left an issue on this project, I didn't get the impression that it got recognized. This little fresh reminder do not hurt anyone.

I'm happy now that I got at least now a proper response,

It doesn't happen again.

**Comment by williewillus** [comment]
Just some intel gathering for a hunch I have @accessdenied0, was this in single player?

**Comment by accessdenied0** [comment]
Dear @williewillus,

Yes it was. Because it is not in any changelog mentioned, I don't know it is fixed... It seems so, but I didn't tried it that much out, because I have the fear of lost all my mined-stuff again. -> No proper response.

access_denied
