### ISSUE TITLE
[Suggestion] Enchantment Support on Matter-tools

### ISSUE THREAD

**Issue by accessdenied0** [sinkillerj/ProjectE#533]
Dear sinkillerj,

Firstly: I want to apologize if my last response was to rude, it didn't meant to be unfriendly.
Secondly: I was searching if someone has already made this suggestion but I couldn't find one and hope this is the right spot.

My suggestion is that it is possible to get any Enchantments on matter-tolls (Black, Red and both ult. Red tools), or at least to get Silk-touch or Fortune at them. I don't know if this is already planed or someone else from your team had the idea already, but it would be a great addition in my point.

with respect,

access_denied

**Comment by carlobon** [comment]
I'm agree with you

**Comment by Ace199102840** [comment]
with NEI you can force an enchantment if you wanted it on there that badly.

**Comment by accessdenied0** [comment]
Dear Ace199102840,

Why? Do you cheat anything in Minecraft? Than you didn't need ProjectE at all... or play the game....
Anyway... it was after all a suggestion, and additionally you could make it a bit more expensive as a simple enchant, too... for instance a Netherstar for Silk-touch upgrade...

access_denied

**Comment by Ace199102840** [comment]
by that point most people would already have a red katar and a red morningstar if they are fighting the wither boss.  having an enchant on a pick that can mine more than one block at once is already a strong built in ability.  and you use that to upgrade red matter pick then to the morningstar which mass mines with no cost at all.... that in itself is pretty much creative mode.  being able to put fortune on it would be over kill.  there used to be an emc cost to using these abilities and these costs arnt even present right now.

**Comment by accessdenied0** [comment]
Dear Ace199102840,

You can't say that like that... people play different, like you have a different opinion. It may be a good idea to add a option to activate or deactivate "Enchantments" or "EMC costs per use" but last one is something COMPLETELY different.
And did I get you right that you are complaining about the fact that this mod is unbalanced? This is slightly hilarious... This is a rewrote from EE2 and now you can guess why EE2 was canceled. I do not say it isn't important to keep anything in a bit of balance but this mod is rewrote because people had fun with it... If you wish for more "balance" use EE3.

access_denied

**Comment by Ace199102840** [comment]
i haven't complained about the mod at all. i love the mod. i find it hilarious that youd suggest an already op pickaxe to have enchantments on it. what happens when you upgrade it to the red morning star? does the enchantments carry over?   if you want enchantment on a dark/red matter pick just use NEI. you can get rid of whatever you own that you think is a fair trade for such enchantments.  if you think its a nether star , then aquire a nether star and then delete it and cheat the enchantment onto the pickaxe. that is merely a suggestion. as i originally intended in my previous comment.

**Comment by accessdenied0** [comment]
Hi Ace199102840,

With all respect, either you are very rude or you don't know what you are writing.
Even If you don't complain about an "op pickaxe" (how you said), you seem not to understand that I just did a SUGGESTION. It is an opinion like yours and It doesn't hurt anyone to ask for a legit way to "enchant" a Matter Tool. Maybe it is on the Katar or Morningstar too much, but I don't see that the only possibility to make this as an option do hurt anyone. Do I see this wrong? (rhetorical question)

access_denied

**Comment by CraftingSnowMann** [comment]
Is it just me or would you two make a good couple? I'm kidding of course but with the way you two are fighting. LOTS OF IMPLYING HERE.

**Comment by accessdenied0** [comment]
@CraftingSnowMann besides it is out of topic, I didn't even know this is still a thing. Maybe you visit the forums for chit-chat.

**Comment by CraftingSnowMann** [comment]
I am sorry @accessdenied0 and @ace199102840 it was simply a joke and it meant no offense I was simply bored last night.

**Comment by pupnewfster** [comment]
Closing this as we do not intend on adding support for enchantments (In fact in 1.14+ we fixed the fact that enchantments could be applied via an anvil). If addons want to add support for enchantments or add extra tiers of matter that support enchantments then they are free to do so.
