### ISSUE TITLE
[Request] Is there a way to change the recipe for philosopher's stone and Trans table?

### ISSUE THREAD

**Issue by HappyBiscuit** [sinkillerj/ProjectE#537]
I would first like to say that I love this mod. It's one of my favorite mods that's out there. I feel that for me personally the recipe for making both the stone and the table is too easy.

I would like to know is there a way to change this? 

Looking to see if I can change Glowstone to tained Essence for the stone and remove the stone from the table recipe and replace it with Infused Ingots

Any help would be greatly appreciated, thanks!

**Comment by CubeWrench202** [comment]
If you know modding is very easy, but i won't explain u how because if you knew modding you should know how to change/add recipes. So you can go with Minetweaker i think!

**Comment by sinkillerj** [comment]
Minetweaker is what most packs use and I haven't heard of one issue resulting from it, give it a try =).
