### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#539]
i really enjoy this mod i loved EE2 alot and when i heard that this mod re-created EE2 i simply had to try it but i have some things i would like to suggest.

please add the functionality of red morning star where right clicking would break blocks in an area instead of having charged star do that.

 i noticed thaumcraft and natura wood and trees do not break with the katar

 gem of eternal density eats up useful items like the divine rod i know there is white list/black list
but it is annoying to have to setup one for every item the gem will eat, also you only have limited slots on what to list.

 enchants on red / dark matter tools ?. 

possible methods to enchant with EMC?.

config to select EMC generation rate on collectors and possibly collectors generate per tick instead of per second.
 
transmutation table/tablet GUI needs a bit of work since the second small circle on the left is now useless and possibly add pages because many mods add colored bricks and such which fill up the circle and you won't be able to find what you are looking for.

tall shot / wide shot and mega impact mode on the tools i really like these and how ee3 did the mode selection in a cool way so maybe something along these lines?.

+ x attack damage on tool tips? and also the red/dark matter sword and the katar are too expensive to be only dealing 4 hearts of damage (according to waila).

i find the straight crafting using vanilla crafting  tables is kinda boring so maybe a special way to craft things possibly infusion / magical crafting tables or something like it.

i noticed two dark matter and red matter furnaces exist in NEI and in the creative menu?

gem armor uses EMC from stars or fuel to replenish hunger / health because it is a bit op for it to be totally free. also please add the ability to make explosions and strike lightning as will as having a  fast swimming speed using gem armor also holding shift repels mob and deflects projectiles is a cool thing :P.

the 'G' key functionality on watch of the flowing time back in ee2 it would be great to see it here

philosopher's stone need more transmutation recipe and ability's  example you can turn cactus green into rose red and you can turn more blocks in the world,like bricks can become mossy bricks or cracked and also allow you to cycle the color  of wood planks, wool and stained clay

finally you can select mode on arch angles smite like target agro mobs only or targe peaceful mobs only or target players only.

**Comment by sinkillerj** [comment]
Some of these concerns are invalid such as damage, also as far as I know all watch of flowing time features are implemented. The rest of your suggestions will be kept in mind.
