### ISSUE TITLE
Shift + Left Click in Table/Tablet with a full inventory causes items to be deleted.

### ISSUE THREAD

**Issue by KindarConrath** [sinkillerj/ProjectE#540]
If you have a full inventory when using the Transmutation Table/Tablet and you try to shift+left click, it uses the EMC required to make a stack of whatever you are trying to craft, but the result gets deleted.  Suggest its either NOT used or the result is thrown on the ground.

**Comment by sinkillerj** [comment]
Should be a easy fix, thanks for the catch.

**Comment by williewillus** [comment]
Cannot reproduce anymore on 1.4.x, probably fixed.
