### ISSUE TITLE
Can't Continue Previous World

### ISSUE THREAD

**Issue by stephenmc608** [sinkillerj/ProjectE#541]
I upgraded from version 1.3.0 to 1.4.0 and now I can't load my world from before. I click load world, it begins to load, but then it just goes back to the title screen.

Log: https://gist.github.com/stephenmc608/a730945438baf36a9986

**Comment by Kolatra** [comment]
Some item is coming up with an ID of -1. Odd.

https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/emc/NormalizedSimpleStack.java#L64

**Comment by stephenmc608** [comment]
That's strange. Is there any easy way to check every items' ID, without checking every single config file?

**Comment by MaPePeR** [comment]
So, I did break stuff again :( 
Could you try if this is really only related to the old world or if it happens in new worlds too? 
That never happened to me in all my tests... And I did a lot.

**Comment by stephenmc608** [comment]
I just created a world, and it did the exact same thing: tried to log on, then went back to the main menu. I assume the log is the same, but here it is: https://gist.github.com/stephenmc608/37ef6e2d9d56126bb3bb

**Comment by MaPePeR** [comment]
The fix for this is probably returning `null` [here](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/emc/NormalizedSimpleStack.java#L37-L40), when `Item.itemRegistry.getIDForObject(stack.getItem())` returns -1.

Is this a public pack of some sort, so i can look at what Crafting Recipe causes this? (I don't feel like downloading all the mods from the log and recreating it myself)

**Comment by stephenmc608** [comment]
Unfortunately, it's a custom modpack that I put together myself. I haven't altered any recipes. I also have the modlist too. https://docs.google.com/spreadsheets/d/1oaedvjZy-hNaEYOASzpvi8yLxRA4o1zWA-e3KFaeFbo/edit#gid=840560105

**Comment by MaPePeR** [comment]
Could you try this version: https://github.com/MaPePeR/ProjectE/releases/tag/1.4.0_idProblem ?

**Comment by stephenmc608** [comment]
I just tried the new version and I was able to load my previous worlds and create new worlds. Thank you very much for the help!

**Comment by sinkillerj** [comment]
Reopening issue till this is implemented

**Comment by MaPePeR** [comment]
@stephenmc608 could you show us a log of a successful load of a world, so i can see the debugging messages and figure out which mod/crafting recipe caused the problems?

**Comment by stephenmc608** [comment]
I accidentally deleted my test instance with the fixed version of ProjectE. >.< I believe I saw Forestry recipes mentioned in the log file.

**Comment by MaPePeR** [comment]
Well - the update that came out just now still contains that log messages, so you can use that official version now :)

**Comment by stephenmc608** [comment]
Alright. Here is the log file using 1.4.1: https://gist.github.com/stephenmc608/e0d5d973a74e02147b05

**Comment by sinkillerj** [comment]
@stephenmc608 Thanks for helping us resolve this.
