### ISSUE TITLE
Wiki Needs Updating?

### ISSUE THREAD

**Issue by dh47** [sinkillerj/ProjectE#551]
Images are missing and needs updating?  Lets get to work?

**Comment by sinkillerj** [comment]
I'm gonna be honest here... I forgot that it even existed...

**Comment by dh47** [comment]
Eh fair enough.

**Comment by williewillus** [comment]
I've been revamping hardcore, any help would be great :D
https://github.com/sinkillerj/ProjectE/wiki/Contributor-Guidelines

**Comment by Kolatra** [comment]
@williewillus is working very hard on it.
