### ISSUE TITLE
[Bug?] Klein Star under max charge makes table have 0 EMC

### ISSUE THREAD

**Issue by KinamKrindar** [sinkillerj/ProjectE#554]
While that's FINE and dandy... unfortunately when the klein star has all of the EMC on it, and none is left in the table (having a star able to hold all EMC that the table's got in it), and you place that star on the left side, it sets the table's available EMC to 0.

The problem with this is that then the table thinks it has no EMC to be able to pull out. The only way I've been able to "get around" it currently, is to place the star in the "target item" slot on the right side, or burning the star. 

In EE2 (and as I'm just now getting into 1.7.10 mods, I'm not sure if previously this mod worked, and it just broke in this new update?), if you put a klein in the left side, the table could use the EMC off the star, so that you could still use the target spot in the table to grab what you're after.

**Comment by Nova001Sol** [comment]
Oh, it doesn't work like it did in EE2. The new method is as follows: Place a KS in targeting slot to drain, place it in the left side to charge. I too preferred the EE2 method, however, just placing in a KS and using the EMC from it to transmute.

**Comment by Brycey92** [comment]
Is this updated behavior reflected in any tooltips or wiki pages?

**Comment by williewillus** [comment]
The original project creator wasn't very stringent at all on adhering to exact EE2 behavior, so it may have been that way since the start of ProjectE.

**Comment by Brycey92** [comment]
Even still, ProjectE users, especially new users who are only recently switching from EE2 should have something to notify them of any behavior or usage changes. I believe there was an issue open about adding an ingame guidebook. That and the github wiki would most likely be the best places for this information.
