### ISSUE TITLE
NEI Magnet Mode + Black Hole Band w/ Alchemical Bag Dupe

### ISSUE THREAD

**Issue by Hollowfires** [sinkillerj/ProjectE#557]
Not sure what mod dev this falls under, but I thought I'd report it anyway.

NEI Version - NotEnoughItems-1.7.10-1.0.4.83-universal
ProjectE version - 1.4.1

What I've tried to reproduce the problem elsewhere:
Tried different magnets in the pack in standard inventory, dupe didn't occur.
Blackhole band in inventory does not dupe the item either.

Details:
From what I can tell when the NEI Magnet Mode is on and the blackhole band is placed in the Alchemical Bags from time to time items will dupe when they are sucked up by the magnet/black hole band at the same time. Depending on what you're doing (mining with a morningstar or Blood Magic pick) the duplication can cause severe amounts of lag for clients and servers alike.

Tested on a server.

Stack size does not matter it seems. 

http://puu.sh/gFNaS/e1743c89d9.png    Before duping

http://puu.sh/gFO8Y/d230f01149.png     After duping.

Works with Q and becomes ridiculous when Shift + Q is done. 

The items are physical/not an inventory tweaks glitch. 

If this issue has already been reported then feel free to close the discussion.

**Comment by sinkillerj** [comment]
NEI magnet mode is a cheat function, and I'm not sure there's much I can do about this.
