### ISSUE TITLE
[Request] Three requests regarding transmutation

### ISSUE THREAD

**Issue by Sourpowerpete** [sinkillerj/ProjectE#559]
I had three ideas regarding transmutation, one is for convenience to the players, and the other two are for map and modpack makers.

1. Right clicking the transmutation tablet search bar clears it, just like the NEI search bar.

2. A config option to disable dynamic EMC. I personally don't want to use this option, but I can see why some people would want to disable it for balance reasons, or because it can sometimes miscalculate values and go haywire.

3. A config option to change transmutation efficiency. So if the config option is set to 50%, everything would sell for 50% of the EMC value, but the "buying price" would still be the same. Anything that would have its value below 1 (like cobble and stone) would have its EMC value set to 0. Again, I personally don't want to use it, but it is a handy option.

**Comment by sinkillerj** [comment]
There are plans to allow static pregenerated EMC in the future.

Buy and sell prices will not be implemented in the near future, EMC augments however may be.

**Comment by Sourpowerpete** [comment]
And the first request?
