### ISSUE TITLE
Singleplayer world creation fails.

### ISSUE THREAD

**Issue by prodkid** [sinkillerj/ProjectE#564]
This occurs when making a single player world
[B#283]  [19:48:40] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[B#283]  [19:48:40] [Server thread/ERROR] [FML]: Caught exception from ProjectE
[B#283]  java.lang.NullPointerException
[B#283]  	at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:45) ~[EMCMapper.class:?]
[B#283]  	at moze_intel.projecte.PECore.serverStarting(PECore.java:127) ~[PECore.class:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[modpack.jar:?]
[B#283]  	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
[B#283]  	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[modpack.jar:?]
[B#283]  	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[modpack.jar:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
[B#283]  	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
[B#283]  	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:739) [Loader.class:?]
[B#283]  	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
[B#283]  	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94) [bsx.class:?]
[B#283]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
[B#283]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#283]  [19:48:40] [Server thread/ERROR] [FML]: A fatal exception occurred during the server starting event
[B#283]  java.lang.NullPointerException
[B#283]  	at moze_intel.projecte.emc.EMCMapper.map(EMCMapper.java:45) ~[EMCMapper.class:?]
[B#283]  	at moze_intel.projecte.PECore.serverStarting(PECore.java:127) ~[PECore.class:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[modpack.jar:?]
[B#283]  	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
[B#283]  	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
[B#283]  	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
[B#283]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_75]
[B#283]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
[B#283]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
[B#283]  	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) ~[LoadController.class:?]
[B#283]  	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:739) [Loader.class:?]
[B#283]  	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
[B#283]  	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94) [bsx.class:?]
[B#283]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
[B#283]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#283]  [19:48:40] [Server thread/INFO] [FML]: Applying holder lookups
[B#283]  [19:48:40] [Server thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[B#283]  [19:48:40] [Server thread/INFO] [FML]: Holder lookups applied
[B#283]  [19:48:40] [Server thread/INFO] [ProjectE]: Completed server-stop actions.
[B#283]  [19:48:40] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[B#283]  [19:48:40] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
[B#283]  [19:48:40] [Client thread/INFO] [STDOUT]: [enhancedbiomes.handlers.SeasonTickHandler:setFoliageColourMap:142]: Trying to change foliage colouriser
[B#283]  [19:48:40] [Client thread/INFO] [STDOUT]: [enhancedbiomes.handlers.SeasonTickHandler:setFoliageColourMap:145]: Set foliage colouriser to enhancedbiomes:textures/colormap/foliageSpring.png
[B#283]  [19:48:40] [Client thread/INFO] [STDOUT]: [enhancedbiomes.handlers.SeasonTickHandler:updateChunks:124]: Re-rendering for updated season

**Comment by sinkillerj** [comment]
@prodkid We are trying to figure out exactly what causes this right now, could you provide some additional info such as your mods list, or is this a premade pack you have simple added ProjectE to?

**Comment by prodkid** [comment]
Currently using it with http://www.technicpack.net/modpack/bullet-phases-rpg-pack.198747 with build 2.3. Current build is 2.2.2, so the list on that site isnt pushed yet until I make 2.3 recommended. I will create a list in a hour or so or you can try the pack yourself.

**Comment by prodkid** [comment]
Im live building the 2.3 pack so once i finish other aspects of pack I will focus back to this mod.

**Comment by sinkillerj** [comment]
Fixed in latest version, closing.
