### ISSUE TITLE
Honored player join message shows after death and respawn

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#565]
The custom "High alchemist joined the server" message for patrons/contributors shows when said person dies and respawns, without leaving the server. 
Presumably because EntityJoinWorld is called when respawning as a new entityplayermp is created.
Is there a specific reason we can't use FML's PlayerLoggedInEvent?

**Comment by williewillus** [comment]
Just tested, FML's event works as well
PR incoming to change the event to the FML one so it won't show the message every respawn
And maybe add a leaving message as well

**Comment by sinkillerj** [comment]
A leaving message seams a bit excessive.
