### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by NJM1564** [sinkillerj/ProjectE#571]
http://pastebin.com/8t2q64t6

**Comment by sinkillerj** [comment]
What were you attempting to do when this crash occurred?

**Comment by NJM1564** [comment]
I added PE to material energy^4.
Standing near my minechem stuff and I think I was opening the transmutation tablet.


I'm thinking back and there were a couple other crashes. 
A ticking memory error but that might just be my comp and a java.lang.IndexOutOfBoundsException that made no mention of any modish things. 
I'll add them in case they help.
http://pastebin.com/8Mv8taaa
http://pastebin.com/qRxJiVCX

I think I updated fluxed crystals somewhere in there to see if that was the problem.


There was also an odd instance where the redmatter hammer seemed to have vein mined a hunk of the loaded ae mining aria. Mining the coal, redstone, lapis, ores. Everything but the stone. And then it lagged out when picking up the matterballs.

**Comment by matthew-goodman** [comment]
i am also getting this crash every couple of hours. We are using the Natural Magic modpack. We have around 40-50 people so its near impossible to find out what was happening just before this. I can provide any access you need

Crash log provided

http://pastebin.com/39tHFXQq
http://pastebin.com/xq666CPu
http://pastebin.com/i06khyTh

sinkillerj. i was also speaking to you regarding the lag when saving the bag/tablet data. Could this be related?

Thanks
