### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by Ryokusitai** [sinkillerj/ProjectE#573]
I am sorry if I made you uncomfortable.
I'm Japanese.
And I am not terribly good at speaking English.

1. src/main/java/moze_intel/projecte/events/ToolTipEvent.java
Line 100
       long total = value * current.stackSize;
       long total = __(long)__ value * current.stackSize;

2.  src/main/java/moze_intel/projecte/api/ProjectEAPI.java
sendMessage argument
         [registeremc]
         [interdictionblacklist]
         [condensernbtcopy]
   but
src/main/java/moze_intel/projecte/utils/IMCHandler.java
 equalsIgnoreCase argument
         [registeremc]
         [interdictionblacklist]
         [__nbtwhitelist__]

**Comment by williewillus** [comment]
1. Why do you need that? value and stackSize are both int, and thus are auto converted to long on assignment. 

2. Fixed in next version https://github.com/sinkillerj/ProjectE/pull/578

**Comment by Ryokusitai** [comment]
Thanks for to fix 2.

About 1.
My ProjectE addons "PEAA" add 71,893,632Emc 's Item to ProjectE
When I stack 30 of these items, "Stack Emc" displayed "WAY TO MUCH".
but when I stack 64 of these items, "Stack Emc" displayed "306,225,152".
--------------------------------------------
I tried it eclips.

int a = 2000000000;
int b = 2;
long c = a * b;
long d = (long)a * b;
System.out.println(c + " : " + d);

<result>
-294967296 : 4000000000

**Comment by williewillus** [comment]
Yes, it's part of a bigger issue with how inconsistently emc is stored and retrieved that the team needs to work on together, I've opened an issue here: https://github.com/sinkillerj/ProjectE/issues/579
