### ISSUE TITLE
stone and red morningstar

### ISSUE THREAD

**Issue by partyanimal** [sinkillerj/ProjectE#575]
when i am using the red morningstar to mine i cant seem to mine stone directly but ores and dirt i can ?

**Comment by williewillus** [comment]
what is your mod list?

**Comment by jordanrooben** [comment]
I'm having a similar issue. Using ftb infinity with veinminer and project e added, I can clear ores and dirt with the morningstar, as well as large sections while charged, but right clicking on stone does nothing.

**Comment by williewillus** [comment]
Does this still happen?

**Comment by partyanimal** [comment]
no it works fine now
