### ISSUE TITLE
Crashbug 2

### ISSUE THREAD

**Issue by NJM1564** [sinkillerj/ProjectE#576]
Mining with morning star in loaded AE aria.
Pack Material energy^4

http://pastebin.com/duZvGmDU

**Comment by williewillus** [comment]
Does it happen when you're not mining as well?
The log mentions mine and blade, could you try fiddling around with that mod with a bag in your inv and see what exactly causes it? I'll try to repro too

**Comment by NJM1564** [comment]
It has happened when I was not mining as well. I've tested it several ways. With a old copy of the save and even with the level.dat copied over from save that was crashing. No idea what Is going on. Might just be my craputer.

**Comment by williewillus** [comment]
I'm pretty certain it's a mod conflict with Mine and blade 2, but not exactly sure what

**Comment by NJM1564** [comment]
The only thing I can think of might be that the black hole band is trying to draw items from the Mine and blade 2 slots.

**Comment by williewillus** [comment]
Nah the bhb only acts on items entering the inventory, not already there. Did you have a gem of eternal density by any chance?

**Comment by NJM1564** [comment]
Yah I did.
