### ISSUE TITLE
Custom EMC IMC not reimplemented

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#577]
@MaPePeR had someone ask about this in irc, will this be back soon?
https://github.com/sinkillerj/ProjectE/blob/4b7ac5ceb02d9cfe32cd5bb028b13201a41ea028/src/main/java/moze_intel/projecte/utils/IMCHandler.java#L47

**Comment by MaPePeR** [comment]
This needs changing, and I don't want to make the decision on how to implement this alone. We should discuss this before. 
IMC needs to die, though.

**Comment by sinkillerj** [comment]
+1 for IMC needs to die
