### ISSUE TITLE
[Major] Need to make EMC value size consistent

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#579]
It's an int in the mapper, doubles in TE's, and apparently a long when grabbed for tooltip (??)
We need to unify everything, and introduce a superinterface for ItemPE and TileEmc (maybe) that has unified set/getEmc methods.

I personally vote for doubles. Longs are more than big enough (9223372036854775807), but some of our machines need to use decimal values.

**Comment by MaPePeR** [comment]
I totally agree - but i don't think doubles are the way to go. 
We decided to use non-decimal types for EMC values in the past, i think: #328 #255  #149

Personally i just can't trust the precision of float/doubles.

**Comment by williewillus** [comment]
we use decimal values in emc currently though (collectors' generation seems to be float/double based)

**Comment by sinkillerj** [comment]
IMO we should stick to purely long which as far as I know should store the most EMC out of all the whole number types. As far as collectors and any other problem math we will have to look over them and see if we really need decimals, if we do we can always convert the output, it's still better than the mess we have atm.

**Comment by williewillus** [comment]
Discussion about this can go with the api, but it looks like we'll be maintaining status quo for compatibility's sake
