### ISSUE TITLE
Transfer the Project to an organization

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#597]
(No, not an april fools joke)
This is a dummy issue to address some suggestions I and other members have.

* Create a Github organization (a la [MinecraftForge](https://github.com/MinecraftForge) and [CoFH](https://github.com/CoFH)), make the four of us members of it, then transfer the repo over into it 
* Make up a fancy name (like CoFH - Cult of the Full Hub) for the organization because I'm not settling for "ProjectE Team" lol

* This will enable several things
   * Write access for all four of us
   * A unified "brand name" if we're going to be a full team, we should get official
   * Multiple projects under the same "namespace" (like having the API be a submodule, like how FML is a submodule of MinecraftForge)
 
* I know there have been some past concerns about write access so here I've stated the benefits of it and how we can keep things under control

* Benefits of write access
    * We can set up a Jenkins server and modify projects / make workflow changes without having to ask the repo owner all the time
    * We can do true real time collaboration (pulling and pushing to a branch) instead of cross-merging each other's forks over and over...
    * We can use tags and labels and get organized
    * I (and probably everyone else can attest) can develop more rapidly. Currently I have ~4-5 PR's awaiting merge and it's mixing me up when, for example, I add a functionality but forget that my localization pull hasnt been merged yet so I can't put a tooltip in, etc.)

* Rules of write access, to address past concerns
    * Can only merge into master with consent from 2+ members of the team unless it is a severely critical hotfix (in general, hotfixes should come from whoever wrote the feature, ex. I would do all pedestal hotfixes, or, whoever is most familiar with that area of the codebase)
    * Breaking changes or major feature changes need full consent of all team members
    * "Consent" = comment on the PR saying something like "I support"/"Agreed"/etc. - (IRC is not easily retrievable without recording tons of logs)
    * ALL trial-and-error development should be on branches, not master. When we get a Jenkins, the build status for master should always be sunny / all builds passing.
    * Workflow changes (Jenkins, modifying build.gradle, etc.) need to be thoroughly tested on a branch before going mainline
    * 2+ members of the team must suggest closing of an issue before it is closed, unless that issue is abuse, harassment, or painfully obvious to be a silly report (user-caused, none of the lines of the stacktrace have PE in it, etc.)
    * When closing issues, always "comment and close" - give a reason
    * All members of the team are expected hold all other members to these rules

Long live ProjectE!

Now let's get a team name going.
Potential names:
* Assembly of Alchemists (suggested by Kolatra)

**Comment by Kolatra** [comment]
I support this idea.

**Comment by williewillus** [comment]
~~How about "Assembly of the Alchemical Archamges"?~~
Nah too cheesy

**Comment by sinkillerj** [comment]
I am, and will always be, commuted to providing credit wherever possible, but a shared account I simply cannot support, I've seen too many projects go down because of one bad member.

As far as a build server I'd rather not do one at this time for the same reason that I no longer distribute or support dev builds, it adds several complications to the issue tracking process.

**Comment by williewillus** [comment]
This isn't about credit for us, it's about having a sense of organization. Notice how all the moderately big team mods (BuildCraft, CoFH, Forge, OpenBlocks, etc.) all have a team repo. It allows work to flow faster and takes the stress off of one person (you) having to gatekeep everything for us. In a sense, this is even more safe from "one bad member" because you have all the other members checking each other on a relatively equal field.

Continuous integration would highly automate our flow. Imagine, once we get it set up right, just tagging a commit on master as a release and Jenkins auto builds it and uploads to Curse for us, etc. Issues can more than be handled between the four of us provided we are able to use labels to categorize and organize.

Either way, the choice is yours as lead dev. I just hope you'll reconsider this some day down the road when you're tired of doing everything manually.

**Comment by MaPePeR** [comment]
These rules you talked about in the first post : is that something you can enforce through GitHub by configuring them or are these rules an organization sets for itself in words? 

Maybe I misunderstood you at first, because I thought these are organization-configurations. (like no commit to master and voting on PRs.) 

Nevertheless: an organisation would be great.

**Comment by williewillus** [comment]
Github has only rudimentary levels of power, I was thinking we could more than comfortably self enforce, if we trust each other as friends.
