### ISSUE TITLE
Setting and Reloading EMC through commands causes server-wide timeouts

### ISSUE THREAD

**Issue by Parker8283** [sinkillerj/ProjectE#600]
Whenever I use the setEMC or reloadEMC commands, they take forever to process and cause all people on the server to timeout, and we can't get back in for another 30s or so. Obviously, I don't think this exact case happens for everyone, but I do believe everyone experiences a bit of lag when this happens. I can only suspect that a lot of heavy logic is happening when either of these commands are run, and I hope it can be stripped down.

**Comment by Brycey92** [comment]
@sinkillerj, perhaps the commands can run their logic in a separate thread?

**Comment by Parker8283** [comment]
Or just the EMC mappers in general. I recall pahimar doing this for EE3, and it just seems silly to run it on the Server Thread if you don't have to, considering this does do a lot.
