### ISSUE TITLE
Repairing swords costs 3 covalence dust, not 2

### ISSUE THREAD

**Issue by Samario1** [sinkillerj/ProjectE#601]
![image](https://cloud.githubusercontent.com/assets/11773646/6967903/7676c7c2-d95a-11e4-8951-02daffd4f1d0.png)
note: Dutch for "Crafting"

**Comment by Nova001Sol** [comment]
Dat gebeurt ook met schoppen en schoffels. Maar is dit echt heel erg? Je bespaart er toch wel wat EMC mee. Maar een advies, doe dit alleen met erg beschadigde spullen die je niet makkelijk kan namaken, of spullen die erg krachtige betoveringen hebben. Steen is het niet echt waard, een keisteen-generator levert meer op dan je zo bespaart. Dit kan trouwens ook met het 2x2-rooster in je inventaris.

Translation: This also happens with shovels and hoes. But is it really that bad? You'll save some EMC anyway. But one advise, only do this with severely damaged stuff you can't easily recreate, or stuff with very powerful enchantments. Stone really isn't worth it, a cobblestone generator produces far more than you'll save this way. Also, you can do this using the 2x2 grid in your inventory.

**Comment by Samario1** [comment]
A) I'm not Dutch, the person I got the screenshot off is Dutch
B) I am aware that the 2x2 inventory option works
C) That's not the point - it SHOULD take two, not three

**Comment by williewillus** [comment]
Seems like all the covalence recipes require 3 dust, even the shovels
Working on a fix

**Comment by Samario1** [comment]
rereading Nova's comment...
D) no you won't save EMC, you'd be spending more as you're using more covalence dust
