### ISSUE TITLE
talisman of repair can't repair some things

### ISSUE THREAD

**Issue by nitsuga5124** [sinkillerj/ProjectE#602]
talisman of repeir have some things that cannot be repaired, like the chisel from chisel 2 mod, hammer and cutter from ic2, the charm of dislocation from draconic evolution, etc...

try to fix it (if its a bug)

the ic2 staff, in project e alpha can be repared, but in project e 1.4.2, not

**Comment by williewillus** [comment]
We check what can be repaired using vanilla method isRepairable()
We have no control over other mods' items and whether they implement true or false for this query.

**Comment by sinkillerj** [comment]
As willie said we respect isrepairable, otherwise we could break mods that use damage for other purposes. If you feel that a item should remove the norepair status you will need to contact the author of that mod. In the future perhaps we can make a override list.

**Comment by williewillus** [comment]
Request close: Works as Intended (checks vanilla isRepairable)
