### ISSUE TITLE
Mute 'whine' sound option?

### ISSUE THREAD

**Issue by Vaygrim** [sinkillerj/ProjectE#604]
Can we please get a config option to turn off the 'whine' that happens when you power up / power down stuff? It's one of the single most grating sounds and the primary reason why I've stopped using all of my Project E gear currently. I feel like I'm getting punished by that sound just for using stuff.

So .. maybe a mute option? Please?

**Comment by williewillus** [comment]
Aw boo the sounds were the best part of EE2 :(

But okay we'll look at adding this sometime

**Comment by Vaygrim** [comment]
I preferred the original textures of Project E over the EE2 textures. Those original EE2 textures are a poke in the eye compared to the nice new ones. Along that same lines I prefer the original sounds (NOTHING) over the EE2 "whine" of punishment. But since Project E apparently uses vanilla minecraft sounds that are 'pitched up' some, we can't just roll an 'empty sound' into the current resource pack with the original textures.

So.. it's config option or nothing. :)

**Comment by williewillus** [comment]
No, we use our own assets for the charge/uncharge/transmute sounds, they can be replaced (assets/projecte/sounds/item/{petransmute, peuncharge, pecharge}.ogg)

**Comment by Vaygrim** [comment]
Oh? Hmm some initial investigations into that seemed to indicate otherwise but we'll dig into things again. I'd still honestly like to see the original textures / sounds included in the mod, with a config option to switch. Cause the list of resource packs I'm going to have to include in my next mod pack update is going to jump drastically.

**Comment by sinkillerj** [comment]
Resource packs can be merged and there is no plan to make the alt textures a config at this time.

**Comment by williewillus** [comment]
Request close: Problem is user preference and can be solved with resource pack or adjusting volume sliders
