### ISSUE TITLE
Arcane ring

### ISSUE THREAD

**Issue by The-Beast** [sinkillerj/ProjectE#607]
Can you add it? It was my favourite ring in EE2. Oh, and is it possible to add a gem helmet with goggles of revealing?

**Comment by sinkillerj** [comment]
The gem helmet already works as goggles of revealing.

**Comment by The-Beast** [comment]
And what about arcane ring?

**Comment by sinkillerj** [comment]
This is a common request and will be kept in mind.

**Comment by Kolatra** [comment]
The class is there, just doesn't work yet. It's all commented out.

**Comment by williewillus** [comment]
Req close arcana implemented
