### ISSUE TITLE
items and block EMC thousand separator

### ISSUE THREAD

**Issue by 19colt87** [sinkillerj/ProjectE#608]
Items EMc and Stock EMC shows weairs ascii symbols instead of thousand separator " , "

![bez tytulu](https://cloud.githubusercontent.com/assets/8260726/6979369/1afb990c-d9e3-11e4-93fc-2385d34cc97a.png)

**Comment by Kolatra** [comment]
This may be an issue with the font/language being used

**Comment by 19colt87** [comment]
I use default minecraft font and english version of minecraft. i think problem is in TooltipsEvents section but i can wrong

**Comment by Xee1** [comment]
I don't have that problem in my instance, version 1.4.2. I have english language.

**Comment by 19colt87** [comment]
Problem solved. Its java issue. Im from poland and java have PL locale. I run minecraft with arguments -Duser.country=US -Duser.language=US andd all works fine...
