### ISSUE TITLE
Client crashs after used the Tome on a Server!

### ISSUE THREAD

**Issue by MSandro** [sinkillerj/ProjectE#616]
When I acces the Transmutation Table/Tablet after I used the Tome of Knowledge my Instance crashs!

Here is the crash-report:
https://onedrive.live.com/redir?resid=666547eb395d21fd!151931&authkey=!AE5ltHCXlPvhVpg&ithint=file%2ctxt

I use the version 1.4.2.

Sorry for my wrong english, I speak german.

**Comment by Kolatra** [comment]
You're using an old version of Mekanism, try updating it, and if it doesn't work, it's a bug on Mekanism's side. Go to http://github.com/aidancbrady/mekanism

**Comment by MSandro** [comment]
Thanks I try it

**Comment by MSandro** [comment]
The problem was not fixed by the update of Mekanism. :(

**Comment by Kolatra** [comment]
Please go to Mekanism's bug tracker and report it to them.

**Comment by MSandro** [comment]
Ok, but thanks for your help

**Comment by Kolatra** [comment]
No problem. :)
