### ISSUE TITLE
[Feature Request] Inequivalent Exchange

### ISSUE THREAD

**Issue by Brycey92** [sinkillerj/ProjectE#618]
From @zortag:
"The original EE2 had a "%cost" option for bypass abuses on servers (cobblegen in relay). evalutate to add it (ie: cost 10% = a 100emc item cost 100 to be taken from tablet but give 90 when burned), decimal are always rounded to the lower (ie: cobblestone = 1emc burned at 10% cost gives 0,9emc, so nothing is added to the tablet emc amount)"

This proposed feature would promote trade with other players on multiplayer servers, rather than them making everything out of EMC. There could be an optional global % cost, and overrides per-item or oredict entry.

**Comment by Kolatra** [comment]
Can you provide more info on this? I have looked and there was no option for this, it was most likely a server specific mod.

**Comment by Brycey92** [comment]
I haven't actually seen the config option zortag referenced, but the general concept remains the same. A percentage of EMC could be added to the cost when creating, or subtracted from the EMC received when destroying. The config value could either be that percent to add to the base value of 1.0, such as -0.1 or 0.1, or it could be a multiplier, such as 1.1 or 0.9.

**Comment by Kolatra** [comment]
I will talk to sinkillerj and we may consider something like this.

**Comment by zortag** [comment]
sorry for my late answer.
i actually have no 1.2.5 pack on my computer, so i can't check the config file.
i started making modpacks for personal use with that version but, except the big work to solve id conflicts, i don't remember much about 1.2.5 modpacking.
i remember i found that option, maybe it was a feature of any ee2 side mod. i used much customemc to add emc values to item not recognized by the main mod

**Comment by Shalashalska** [comment]
I implemented something like this in a fork I made a few months ago. It's quite simple really, just add a config option that sets static variables, which incoming EMC is multiplied by. About 20ish lines of code, and no effects if the default is set to 1, but very nice for people who want a major nerf to transmutation without removing it completely.

**Comment by MaPePeR** [comment]
I think, we would appreciate a pull request.

**Comment by Brycey92** [comment]
@williewillus Was this feature implemented or canceled? I see the PRs are closed, not merged, but that was over 2 years ago so I'm not sure if you implemented it yourselves in the mean time. Please let me know!

**Comment by williewillus** [comment]
this was implemented by sin in one of the 1.12 releases

**Comment by Brycey92** [comment]
Any possibility of a backport to 1.10?
