### ISSUE TITLE
Not enough

### ISSUE THREAD

**Issue by The-Beast** [sinkillerj/ProjectE#619]
So I've reached maximum of EMC in table. I wonder: "Why it's so small amount?"

**Comment by MaPePeR** [comment]
Probably because of the max size  of an int and to make Klein stars useful.

**Comment by Kolatra** [comment]
Our max is MAX_INT / 2 for some reason.

**Comment by MaPePeR** [comment]
That's a good choice, because it allows to add 2 values without overflow.

**Comment by sinkillerj** [comment]
Congratulations, you have too much EMC! =D

On the real talk subject this may be increased in the future as there is some planned EMC work, but for now you've hit the ceiling.
