### ISSUE TITLE
Urgent issue

### ISSUE THREAD

**Issue by Time6628** [sinkillerj/ProjectE#622]
I don't know what is causing this but my server won't startup
http://pastebin.com/N0R2suLQ

**Comment by williewillus** [comment]
Did the server ever crash / got shut down unexpectedly recently? One of ProjectE's files has been corrupted and can't be read.
If you really need to get back online, copy the ProjectE folder in the world save root to another location  as backup then delete the original

**Comment by Time6628** [comment]
Fixed it, thanks!
