### ISSUE TITLE
Items missing in LAN multiplayer

### ISSUE THREAD

**Issue by SprinkCal** [sinkillerj/ProjectE#627]
Whenever playing in a LAN world with friends everyone who is not host will lose all learned items and EMC in their transmutation Tablet/ in a Transmutation Table.

**Comment by MaPePeR** [comment]
Do your friends have minecraft accounts and are logged in?

**Comment by Sourpowerpete** [comment]
I've run into this situation as well, and if it's the same issue I'm having, they do have minecraft accounts and are logged in. My brother uses a condenser to avoid using the tablet because of this bug.

**Comment by sinkillerj** [comment]
It is generally best to run a dedicated Forge server, many mods break in LAN mode.

**Comment by Prophious** [comment]
i have the same issue.... the thing is we dont have enough computer power/memory/money to run a dedicated server..... so aside from that what can be done?
