### ISSUE TITLE
Problem with Interdiction Torch

### ISSUE THREAD

**Issue by grimuars** [sinkillerj/ProjectE#628]
After update to ProjectE-1.7.10-PE1.4.3, when Interdiction Torch is in the interdictionMode=true, it doesn't apply to all non-vanilla monsters (from LycanitesMobs, AbyssalCraft, Nevermine, etc., versions of these mods have not been changed)

When interdictionMode=false, everything all right.

**Comment by williewillus** [comment]
This will be fixed in https://github.com/sinkillerj/ProjectE/pull/620.
The reason was because the old check checked for EntityMob, instead of IMob. EntityMob is used by vanilla, but IMob is the generally accepted way for mobs to denote a hostile mob.

**Comment by Brycey92** [comment]
While we're at it, is there any way to prevent non-hostile NPCs from Custom NPCs from being affected by interdiction torches?

**Comment by williewillus** [comment]
Set interdiction mode to true? 
When the config is true only hostiles are repelled. Unless Custom NPC's entities are coded as hostile mobs, which would be their problem

**Comment by sinkillerj** [comment]
*table flip*

**Comment by williewillus** [comment]
┬─┬ノ( º _ ºノ)

**Comment by sinkillerj** [comment]
(づ｡◕‿‿◕｡)づ︵ ┻━┻

**Comment by williewillus** [comment]
Can be closed - #620 has been merged
