### ISSUE TITLE
EMC Values Disappearing with Update

### ISSUE THREAD

**Issue by Neith7** [sinkillerj/ProjectE#631]
This seems like it may be related to the issue recently posted by abraxas. I'm not 100% sure.

When Updating from Version 1.7.10-PE1.4.2 to Version 1.7.10-PE1.4.3 nothing has a EMC value, also something is wrong with the Transmutation Tablet.

Picture of what I mean: http://imgur.com/lWQrER1

fml-client-latest.log: http://paste.ubuntu.com/10778613/

Strangely when starting a save up the first time the items have a value again but if I save and quit and then start that same save the values are gone. The issue with the Tablet remains either way.

Version 1.7.10-PE1.4.3.1 fixes the EMC value problem, but I understand that's just a quick patch until you resolve the underlying issue, I should note the Tablet issue does still persists in 1.7.10-PE1.4.3.1.

I'm new to reporting problems like this so please let me know how I can help provide more information if you need it.

**Comment by williewillus** [comment]
Yes, it is the same issue. We've found the cause (MPS registering recipes very late in the loading process and interrupting our emc value generation code) but still working on a fix
