### ISSUE TITLE
Missing localisation in Transmutation Tablet

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#634]
Typo in String:

https://github.com/sinkillerj/ProjectE/blob/6d5c6b24aa1d08f93316ada361332864a1fcc220/src/main/java/moze_intel/projecte/gameObjs/gui/GUITransmute.java#L67

https://github.com/sinkillerj/ProjectE/blob/6d5c6b24aa1d08f93316ada361332864a1fcc220/src/main/java/moze_intel/projecte/gameObjs/gui/GUITransmuteTablet.java#L66

(Thanks to malice for pointing it out)

**Comment by williewillus** [comment]
Went ahead and fixed it in https://github.com/sinkillerj/ProjectE/pull/620

**Comment by williewillus** [comment]
Can be closed - #620  has been merged

**Comment by williewillus** [comment]
Bump to close, refactor was merged

**Comment by williewillus** [comment]
Bumpy bumpy bump
