### ISSUE TITLE
Replace ChatComponentText with ChatComponentTranslation

### ISSUE THREAD

**Issue by Adaptivity** [sinkillerj/ProjectE#635]
*ChatComponentText(StatCollector.translateToLocal* will not use different from English languages on servers. So, these messages will always use English localization on server (as I know). Not sure if ChatComponentTranslation fixes it but it should, I guess?

**Comment by williewillus** [comment]
Needs testing

**Comment by williewillus** [comment]
Update: Yes this is a legitimate issue which requires resolution. Fortunately the fix should be simple enough, but it'll come after the refactor gets pulled.
