### ISSUE TITLE
Setting unToolTips=True does not show the unlocalized name

### ISSUE THREAD

**Issue by Linkxgl** [sinkillerj/ProjectE#638]
I've set unToolTips=True, but I can't see the unlocalized names of anything in the tooltips (including vanilla ores/items).

Here's a link to the projecte config file:
http://www.pasteall.org/57786

PS: Tooltips are seen just by hovering over the item right? If not, someone please fill me in.

**Comment by sinkillerj** [comment]
Testing this in the latest version I have been unable to reproduce the issue, its possible that you have a duplicate config file somewhere and you are editing that dupe.

**Comment by Linkxgl** [comment]
I'm a little embarrassed to say this but - it turns out that I was editing the server config file and not the client version. I should have suspected that tooltips was client side.

Hopefully if anyone else has the same issue they can see this report.

As a side note, it'd be cool if there was documentation detailing that you can hold items and just type in the commands for this to work as well. I found that you could do this by searching through some reports.

Thanks a lot for Project E it's awesome (:

**Comment by sinkillerj** [comment]
Currently the best ProjectE specific documentation is here: https://github.com/sinkillerj/ProjectE/wiki

Its been abandoned for awhile but @williewillus has been working hard to improve it. If you feel it could use a commands page feel free to contribute. 

I have also been working on a in game help guide, alot of the wiki content will be adapted for that when it is complete.
