### ISSUE TITLE
Blacklist for repair talisman 

### ISSUE THREAD

**Issue by Time6628** [sinkillerj/ProjectE#639]
I've been experimenting and it appears as the repair tailiman will repair anything with damage. This includes things like Oxygen tanks from Galaticraft. Could you add a option in the config to blacklist certain items so they don't get repaired? 
Thanks!
-Time

**Comment by MaPePeR** [comment]
In recent versions the Repair Talisman checks for `Item.isRepairable()`...

**Comment by ErrorCraftLP** [comment]
See PR #298

**Comment by Time6628** [comment]
Cool beans :)
