### ISSUE TITLE
Crash Report TransmuteTabletInventory

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#653]
Im not 100% sure how this crash happens, I just know that it happens frequently.

http://pastebin.com/cdWQEVxR

**Comment by williewillus** [comment]
What pack and mod version is this? We've had lots of reports on this issue and want to pin this down

**Comment by Tencao** [comment]
This is a pack that I maintain, Tekkit Classic Reborn. 
The current mod version is 1.4.2
