### ISSUE TITLE
[Feature Request] EMC transformer

### ISSUE THREAD

**Issue by MSandro** [sinkillerj/ProjectE#660]
Could you add a block which converts EMC to RF and reverse? I think that would be very helpful!

Sorry for my bad English. I normally speak german.

**Comment by Parker8283** [comment]
If the mod isn't OP already, that would make it way to OP. I don't think that's within the scope of this mod, to be honest.

**Comment by Kolatra** [comment]
*poke poke* There is an addon to the mod that does this.

**Comment by MSandro** [comment]
Can you post a link for this addon please? Or can you tel me the name of them?

**Comment by Kolatra** [comment]
The name for it is Modern Alchemy, however it's on the Japanese forums and I can't find it at the moment.

**Comment by MSandro** [comment]
Ok, thank you.

**Comment by HallowedMonkey** [comment]
http://forum.minecraftuser.jp/viewtopic.php?f=13&t=19445

**Comment by MSandro** [comment]
Thanks

**Comment by HallowedMonkey** [comment]
Not a problem

**Comment by Kolatra** [comment]
It's a bit odd though, it generates a stupid amount of RF, but only outputs 100 per tick.

**Comment by HallowedMonkey** [comment]
True maybe there is a bug considering its still beta development

**Comment by MSandro** [comment]
Ok, I try the mod out

**Comment by Kolatra** [comment]
I hope so, because I love some ezpz power gen.

**Comment by HallowedMonkey** [comment]
Ya lord knows im tired of building HUGE reactors
