### ISSUE TITLE
Exceptions during EMC Remapping

### ISSUE THREAD

**Issue by zauberparacelsus** [sinkillerj/ProjectE#662]
I am occasionally seeing an apparent exception during EMC remapping, though I have yet to catch it: when I go to check the console, I don't see where it is because some other exception (dealing with tooltips) is occuring cyclicly.  The problem also occurs rarely: I have only seen it two or three times in the past two days.

In any case, when this happens, some items will temporarily lose their EMC values, and you will need to relog in order to restore them.

**Comment by williewillus** [comment]
Is there any way logs of this happening can be obtained?

**Comment by zauberparacelsus** [comment]
No, I didn't catch where the exception occurred.  If it happens again, I will post logs.  And make sure to clear the console before running the setEMC command.

**Comment by zauberparacelsus** [comment]
So far I have not been able to repro it today.  Either I was mistaken, or it's gone heisenbug.

**Comment by MaPePeR** [comment]
You could also try to run reloadEMC a bunch of times.

**Comment by sinkillerj** [comment]
Issue should no longer exist.
