### ISSUE TITLE
Watch of Flowing Time overrides doDaylightCycle gamerule

### ISSUE THREAD

**Issue by zauberparacelsus** [sinkillerj/ProjectE#663]
When the Watch of Flowing Time is set to fast forward or rewind, it overrides the doDaylightCycle gamerule, which normally causes the time of day to be frozen/paused.

I don't know if this was a design oversight or if it was deliberate, though I'm reporting it here so that the behavior is known.

**Comment by williewillus** [comment]
Oversight, quick fix will come in a few hours or so

**Comment by williewillus** [comment]
*quick fix commit
