### ISSUE TITLE
Red Morningstar mines non-ore when charged & right-clicked on vein

### ISSUE THREAD

**Issue by VeriTi** [sinkillerj/ProjectE#664]
After updating to 1.4.4 when I right-click an ore vein with a Red Morningstar, which is charged at least to level 1, it will try to mine "veins" of all types within radius, whether or not they are ores. This leads to disastrous effects, because e.g. if any stone was in the range of the click, it will attempt to mine all the stone around it. In SP this causes crashes or lots of lag if used inside a mine.

Illustration:
- Put an Iron Ore block (mid-air)
- Put five cobble to the right of it
- Put five dirt to the left of it
- Charge Morningstar to level 1 and right-click the Iron Ore block.

**Result:** Cobblestone, iron and dirt are all mined.

**Comment by williewillus** [comment]
I'll look at this later tonight, the code shuffle shouldn't have done that but welp :P

**Comment by williewillus** [comment]
Fixed
