### ISSUE TITLE
Red Matter Hammer doesn't work as usually

### ISSUE THREAD

**Issue by 41MS** [sinkillerj/ProjectE#665]
The Red Matter Hammer mines like a pickaxe when charged and uncharged with left mouse click.
Nothing Happens with right mouse click.

Version is 1.4.4

**Comment by williewillus** [comment]
Left clicking - mines like a pickaxe, the charge affects how fast it is. Press the mode switch key to change between the 3xlong/wide/tall shot modes. All left clicking is free

Right click functions *require EMC*. Make sure you have enough on you.

**Comment by williewillus** [comment]
Fixed by #666
