### ISSUE TITLE
Pickaxe no longer harvesting ore with rightclick

### ISSUE THREAD

**Issue by grinch843** [sinkillerj/ProjectE#671]
Just updated to 1.4.4 and noticed that the Red Matter and Dark Matter pickaxe no longer harvest ore when right clicking like in 1.4.3.

**Comment by MaPePeR** [comment]
in that version they need emc for that right click ability. That will be probably revoked in the next version though. (Need emc like destruction catalyst - have fuel or klein star in inventory)

**Comment by williewillus** [comment]
@MaPePeR  in ee2 the pickaxe didn't have vein mining. Only the morningstar did.

**Comment by williewillus** [comment]
I actually missed this when rewriting the tools. It'll be back next release

**Comment by williewillus** [comment]
I'll also reverify everything with ee2, hopefully that's the end of redactor issues

**Comment by williewillus** [comment]
Fixed
