### ISSUE TITLE
[Request] Gem armor special abilities

### ISSUE THREAD

**Issue by partytown** [sinkillerj/ProjectE#676]
The gem armor from projectE only has night vision, speed buff and flight which i find sad. i would love to see the old abilities like create thunder and explode and repell mobs etc. IDK if its still possible to add those things in 1.7 but i would really like to see that and i think it would make the gem armor worth while because right now there are way better armor options at least in my modpack.
Also maybe a config options to decrease/ increase damage resistance and damage done by the rm tools.

**Comment by williewillus** [comment]
Last time I checked we had those? Make sure you ready the offensive abilities

**Comment by partytown** [comment]
I have the latest version and the armor only has night vision on the helmet and step assist on the boots that you can toggle. The pants give passive speed but i havent seen anything else like shooting lightning out of your helmet like in the old EE2

**Comment by badtzmaru** [comment]
in ee2 you pressed V to activate the offensive abilities. is there a different key for this because that's not working at the moment.

**Comment by williewillus** [comment]
Yeah the abilities are only partially implemented at the moment. I'm working on completing them.

**Comment by williewillus** [comment]
can be closed - feature completed
