### ISSUE TITLE
[suggestion] EMC crafting mapping

### ISSUE THREAD

**Issue by nitsuga5124** [sinkillerj/ProjectE#679]
i dont know how to explain this, but i have a example:

the extrautilities transfer pipes: the slab have 0,5 emc and the mod doesn't have decimal emc, the craft cost 6 slabs with 0,5 emc, can you make this 6 slabs with 0,5 emc in to 3 emc +1 of the glass and 128 of the 2 redstone divided by 8?

PD: add emc to the potions pls

**Comment by MaPePeR** [comment]
Implementing this is one of my secret projects, for which I  did not have the time yet. 

Regarding Potions: I looked into them and the brewing system appears to be a lot of weird bitfield operations. Not sure how to do these in a good way, without just hardcoding everything. (hardcoding is probably the better option..)

**Comment by sinkillerj** [comment]
There will be no EMC values for potions in stock ProjectE.

**Comment by MaPePeR** [comment]
Does that mean, that you would not include a mapper for potions or that it would be disabled by default?

(That's probably a fault of the current mapper system: it activates all mappers that are available by default.)

**Comment by nitsuga5124** [comment]
maightby try to know the item are in the top of the brewing stand and add the emc value of the item in the top + the potion in the buttom x 3; or premade the emc values manually, (lazy work)

**Comment by nitsuga5124** [comment]
maightby try to know the item are in the top of the brewing stand and add the emc value of the item in the top + the potion in the buttom x 3; or premade the emc values manually, (lazy work)

**Comment by sinkillerj** [comment]
@MaPePeR That is correct, a potion mapper would not be accepted at this time. Maybe a device can be added in addons much like I plan for with enchanted books, but pure EMC to potion would be remarkably OP.

**Comment by hlaaftana** [comment]
Oh, so only that would be OP and nothing else about the mod?

**Comment by sinkillerj** [comment]
@hlaaftana You are welcome to add the EMC values for them to your own pack. Please try to keep your responses constructive.

**Comment by accessdenied0** [comment]
Hi there,

sorry bringing me on here but 0.X Values would be very nice (mostly because Glass Pane or Stone Slaps), can I hope this could be possibly a thing in the future, or is it to complicated?

access_denied

**Comment by MaPePeR** [comment]
#736 implements this. kind of.

**Comment by MaPePeR** [comment]
@sinkillerj the fraction-emc thing is now implemented.
