### ISSUE TITLE
EMC Allocation? Exception in file I/O causes Fatal error, server shutdown

### ISSUE THREAD

**Issue by cocopuffs99** [sinkillerj/ProjectE#680]
Hey Guys,

Not sure how to fix this but found an Exception in file I/O.

Here is the full log (error begins line 553): http://paste.atlauncher.com/view/043b337c
If you want me to reproduce it or anything just let me know;  I'm getting this when trying to load a newworld- I have loaded it multiple times (4x now) and on load it gets this area after preparing spawn then returns to the main menu (Fatal error, server shutdown).

**Comment by sinkillerj** [comment]
This crash appears to be caused by Not Enough Resources, not ProjectE.

**Comment by MaPePeR** [comment]
The exception you see there is normal (it says that in the line above the exception) 

The crash is caused by the exception at the bottom of the log. Neressources causes it with class not found.
