### ISSUE TITLE
Transmuting Mekanism items

### ISSUE THREAD

**Issue by hajile00** [sinkillerj/ProjectE#685]
In the older versions, I could search for "certus" and it would also render the Mekanism items fine. In the newest, I could only get to "ce" as it would crash with the "r" in. Removing the Mekanism items, except the ingots, has fixed this problem. I am just curious as to why as I use Mekanism a lot.

**Comment by Kolatra** [comment]
Crash log? Version of Project E and Mekanism?

**Comment by williewillus** [comment]
Mekanism has certus? 0.o..

**Comment by hajile00** [comment]
No, certus is Applied Energistics.

**Comment by sinkillerj** [comment]
Duplicate issue. We cant do anything about the Mekanism rendering crash, it is on their end.
