### ISSUE TITLE
Gold Horse Armor EMC Too Low?

### ISSUE THREAD

**Issue by Hysro** [sinkillerj/ProjectE#687]
I found that the Golden Horse Armor's EMC value is way way low (only ~1000 or so), and returns about 10x that when melted down to gold in the Tinker's Smeltery.  This can be infinitely looped quite easily.

**Comment by MaPePeR** [comment]
Wow. Nice catch. 

The problem with that is, that horse armor is a dungeon loot. There is no crafting recipe, so the amount of ingots needed for one horse armor is kind of arbitrary. 

The amount from Tinkers sounds more reasonable.
