### ISSUE TITLE
Energy Condensor MK2 Bugged

### ISSUE THREAD

**Issue by ThisisCanada98** [sinkillerj/ProjectE#689]
The Energy Condensor MK2  takes everything in as it should but when it comes to making the output it does not.

**Comment by ThisisCanada98** [comment]
It seems to only happen with automated input from ender io conduits.

**Comment by williewillus** [comment]
Could you describe your problem in more details (give me exact steps to reproduce)?

**Comment by ThisisCanada98** [comment]
I have my ender quarry going into a group of alchemical chests, those chests than have Ender IO conduits sending the chests contents into the Mk2 Energy condenser. It recieves the items and turn it into emc but when it gets enough emc for the item it just uses up the emc without creating it.

**Comment by williewillus** [comment]
Can no longer reproduce, PE 1.7.1, EnderIO 2.2.8
