### ISSUE TITLE
Loot ball spawns at the wrong location.

### ISSUE THREAD

**Issue by RoqueDeicide** [sinkillerj/ProjectE#694]
In previous versions of ProjectE loot ball spawn at the player's location which is very handy when using catalyst while flying in the void dimensions since the ball is then immediately picked up.

In 1.4.6 however loot balls spawn in the same manner as in old EE2 - at the location of the targeted block with a small impulse in random direction, which means that the balls tend to fall into the void.

I had to revert to the previous version for now because of this issue.

**Comment by williewillus** [comment]
@ devs I made it the EE2 way in 1.4.6. If we're spawning it directly on the player there is pretty much no need for lootballs. Make config option, leave it, or remove loot?

**Comment by williewillus** [comment]
The gameplay solution to this is to use a black hole band

**Comment by RoqueDeicide** [comment]
> Make config option, leave it, or remove loot?

What?

Having this as a config option would be the best, I don't like having magnet items when I'm already using the magnet mode.

**Comment by MaPePeR** [comment]
Fixed by #1013? I don't know.

**Comment by williewillus** [comment]
yeah
