### ISSUE TITLE
not real emc

### ISSUE THREAD

**Issue by SpikeVanHellsing** [sinkillerj/ProjectE#695]
i think i found a bug. i use a mouse with a scroll wheel and if i scroll over an item its emc value is added to the table/tablet but goes away when i exit the table/tablet. ProjectE Vers 1.7.10-PE1.4.6 forge 10.13.3.1403

**Comment by sinkillerj** [comment]
Duplicate of #318

**Comment by SpikeVanHellsing** [comment]
oh ok
