### ISSUE TITLE
IMPORTANT IMPORTANT IMPORTANT ( Not an issue but useful )

### ISSUE THREAD

**Issue by Carbon-Ghost** [sinkillerj/ProjectE#700]
SinKillerJ, here is a link to EE1 + required mods to use it, as you requested on Twitter : https://www.dropbox.com/sh/13ciznyr7gdj3h8/AADFmo9zJEtjFQQ9SxsSK9_ca?dl=0

Enjoy :D

**Comment by sinkillerj** [comment]
Thanks, this is the most complete copy I've gotten so far.

**Comment by Parker8283** [comment]
I've got a version that works with Forge that I could get to you on Monday. 3.57 iirc.

**Comment by Carbon-Ghost** [comment]
No problem sinkiller ;D ( crédits to Chocohead for still having them ).
