### ISSUE TITLE
Items disappearing transmutation tablet  & table

### ISSUE THREAD

**Issue by MrThomson** [sinkillerj/ProjectE#710]
Item sometime disappearing for the transmutation tablet  & table on servers

**Comment by williewillus** [comment]
Need more info. Is it because you don't have enough emc to transmute your target?
Any crashes or unusual things in the log? What were you doing before it happened?

**Comment by MrThomson** [comment]
I have over 200 Million EMC in my transmuting table

**Comment by MrThomson** [comment]
no crashs and just login in on my server today and when to get coal and it was like i have never teach it how to make some of the basic things i had teach early on 

--Note Custom Homemade Modpack-

**Comment by MrThomson** [comment]
I have some screenshot to screen that item are just gone https://imgur.com/a/2VJun and one of the front page of my tablet https://imgur.com/a/zQHyc

**Comment by williewillus** [comment]
Wait what is wrong all your item knowledge is still there in those screenshots

**Comment by MrThomson** [comment]
if you look at the first screenshot it show all the high powered stuff but something as basic and dirt & cobblestone and coal were lose today when i login to my server for my knowledge in the tablet and table

**Comment by MrThomson** [comment]
this bug dose not seems to be effecting vanilla items

**Comment by sinkillerj** [comment]
Not enough info and contradicting replies, closing.
