### ISSUE TITLE
Faithful 32x32 support for ProjectE

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#713]
There already is an Equivalent Exchange 2-Mod Support Pack for Faithful. 

Maybe we can contact the author and ask him/her if we are allowed to create a ProjectE-Mod Support Pack?

* [Faithful Mod Support Page](http://www.faithful32x32.com/modsupport.html)
* [Direct link to Faithful32_EquivalentExchange2_1.4.6.7.zip](http://www.faithful32x32.com/dl/mod/Faithful32_EquivalentExchange2_1.4.6.7.zip)

That would require us to stop renaming our assets, though.

Also: 
The magic_banana pack needs an update because our pickaxe texture now is named `pickaxe.png` instead of `pick.png`. [(commit)](https://github.com/sinkillerj/ProjectE/commit/a4ddf1ac2c714f5ef042d0d9fda99cc259bc3bdd)

**Comment by Xee1** [comment]
@MaPePeR see this: 
https://github.com/F32Organization/Faithful32-1.7.10
This is the official faithful mod support pack(you find that pack also in FTBLauncher)
The owner @DZCreeper is authorized from Vattic to do that if I remember correctly
ProjectE is full supported.

**Comment by MaPePeR** [comment]
Oh. I did not notice that. That's amazing. They also have the wrong filename for the pick though.

**Comment by Xee1** [comment]
I will fix that, I'm a collaborator. @MaPePeR

**Comment by MaPePeR** [comment]
Thanks <3
