### ISSUE TITLE
Musing about Transmutation and Alchemy Bag Inventory Wipes

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#715]
I'm just putting this here so other devs / people can look at it and so I can get it down before I forget.

AlchemicalBags is a completely static class. It does not use an object instance to store bag inventories - it stores things in a static `Map<String, Map<Byte, ItemStack[]>>`. This is fine for dedicated server-client environments, but I think it might possibly cause a race condition on the IntegratedServer-Client environment because both client and server threads are operating on the **same instance** of the data.

Here's how it goes in my head (for a bag, but I think the transmutation is the same, just even more rare)
* Lots of items are flowing into the bag via a Black Hole Band (for example). Each time an item enters the bag, the server thread calls AlchemicalBags.set() and AlchemicalBags.sync(). The former sets the aforementioned static map, updated with the latest changes. The latter dispatches the new data to the client.

* In the Dedicated Server and Client environment, the clientside simply accepts any sync packets and updates the clientside AlchemicalBags static map using set().

* In the Integrated Server / SSP environment, the server calls set() on the static map accessed by both the client and server threads. Then, the server sends a sync packet, which the client happily accepts and calls set() using the contained data on the SAME static map. Since this is the loopback interface, the packet should arrive really really really fast. But if it does go wonky for a moment, it could turn out like this:
    * Server thread calls set(), then calls sync(), sending a loopback packet to the clientside.
    * Packet lags for some reason or client thread lags. In the meantime, server thread has called set() again.
    * Client catches up and processes packet. It calls set() to update. But since AlchemicalBags is static, we're operating on the exact same object that the server thread just updated, and overwriting it with older data. 

* This is really rare since the loopback interface is blind fast, but I think it matches with reports of it happening on single player (how many of our data wipe bugs are SP vs MP?) and with BHB's or GOED's (where the bag is getting set() called on it extremely often).

**Comment by MaPePeR** [comment]
Wouldn't that scenario only remove new items from the bag instead of wiping it?

**Comment by Phyn** [comment]
The bag issues have little to no connection to the registry being shared. The existing code, some of it my code, that is wiping the bags is nothing more than a [patch](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/playerData/AlchemicalBags.java#L62-L66) to fix the outer map returning null on an existing player and causing an NPE crash. The only source of this I can reasonably identify is a faulty core mod making strange changes to the code or a mod of either type modifying the map.

**Comment by Heimdell** [comment]
Could it be possible that for some reason the `moze_intel.projecte.playerDataAlchemicalBags.loadFromNBT(...)` 
receives invalid or broken `NBTTagCompound` (with field `"player"` missing, for instance)?
There is no validation logic at all there.

P.S.: I had never encountered that bug, btw (I have last version released and carry my thaumcraft stuff in white bag).

**Comment by williewillus** [comment]
With the new save format, my points that I made here are kinda moot. Fingers crossed that the new saving fixes it all
