### ISSUE TITLE
things need changing/fixing and some suggestions

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#716]
the new implemented sound do not match the original EE2 sound. ex shove right click functionality dose not produce the sound from EE2 rather creates the sound meant for the destruction catalyst.

 mercurial eye takes no regard of what block being clicked at when in transmutation mode, in another word,if i have small patch of dirt surrounded by stone and i want to turn the dirt into wood the eye will transmute both of the dirt and stone regardless,as a pose  to how mercurial eye in EE2 did it,where it turned all the blocks of the same type you clicked on

 tools,armor,rings and the stones (life,body..etc) should NOT have an EMC value, just like in EE2 because having EMC value  makes them a target of the gem of eternal density and we don't want them to be eaten, and honestly if one can afford them then he can afford 4 seconds of crafting, it is not the end of the world if we cant condense them or transmute them

forth thing is the harvest goddess band  cant harvest fully grown nether wart

please set the limit of bonus ticks applied by watch of flowing to more than 256, or maybe even no limit at all since i didn't enjoy breaking the game enough using it with collectors :).Also the "G" function of the watch dose not stop arrows like it used to do in EE2 

the arch angel smite arrows damage need to be buffed 

tall , wide and deep shot mode is not implemented on the dark/red matter shove also mega impact mode on hammers and the morning star is missing as well

finally the aggressive gem armor mode, ex lighting strikes and explosions.. etc are not yet implemented despite a small claim in here https://github.com/sinkillerj/ProjectE/issues/676 saying that some are implemented, I tried every button and nothing happend 

the evaporation and freezing ability of the water and lava amulet plz :)

as for my suggestions i would love to see the ability to enchant matter tools , I know this is over suggested at this point but i would love some fortune with my OP mining tools

also please bring back some of the transmutation recipes of the old EE2, ex glass back into glass pains , rotten flesh + some stone = soul sand...etc 

finally thanks for the development of the awesome mod :)

**Comment by williewillus** [comment]
1. What sound does it make?
2. Okay, may look at in future.
3. @MaPePeR can we remove the values for them?
4. Got that implemented in a pull request #708 
5. Ehh, maybe. Did it repel arrows or speed them up?
6. If you can get me hard numbers on their EE2 damage I'll change it
7. iirc those modes weren't on the shovel... mega impact will come later
8. Can you describe their specific old behavior?
9. Haha...maybe ;)
10. Got a list of all of them?
11. Thank you for the feedback!

**Comment by MaPePeR** [comment]
As soon as you turn the rings on they don't have an emc value anymore because their metadata changes.

**Comment by blackdragonIV** [comment]
after looking through the original EE2 sound files i can not make a match for the sound the tools used when right clicking, the closest thing i got was the sound of flash.ogg from the mod files however the sound the tools make is the exact sound made when the tools are charged to max level
this sound applied to red morning star right click,shovels right click,pickase right click to mine an ore cluster, the current sound  used is for destruction catalyst.

as for the watch when "G" is activated the arrow coming toward you will come to a full stop (like if it hit a wall) once near you and fall harmless to the ground, however the gem armor (legging part) had the ability where mobs near you will become slower and if you sneak you will be able to repel enemy's away from you and DEFLECT arrows back

yes i made sure and the shovel dose have the tall,wide and long shot mode as seen here
http://imgbox.com/fB6fkSlh

this test was made with the tekkit modpack which features EE2 in it

as for the arrow damage i can not be specific because there is no mod to indicate damage dealt for MC 1.2.5 however the current arrows deal damage of about slightly drawn bow , maybe up to a half drawn bow damage should suffice (2 hearts i think)

as for the amulet they both had charge levels and the charge level determined the amount of lava will be placed when right clicking also pressing the "c" key with volcanite amulet will instantly evaporate all water near player (charge level will determine the range of effect) and pressing "c" with evertide amulet will instantly turn nearby water to ice and near by lava to obsidian (charge level also effect the range of the amulet effect)

one final note that the evertide amulet effect of the "c" key is not in EE2 however it was in the original EE and i see it would be nice to have it back

as for the recipe i cant not provide a list however they date back to the original EE mod and to EE2 for minecraft 1.0.0 if you can search their you might find them, however they might need changing a bit 

one last thing is the "R" functionality for destruction catalyst please

i have done all the test in tekkit modpack so all is the real stuff XD

**Comment by sinkillerj** [comment]
@blackdragonIV As far as EE1 content goes I have plans, but as a separate mod.

As for tool EMC we should probably have that as a config @MaPePeR .

**Comment by MaPePeR** [comment]
I think you can use setEMC to change the values. No additional config needed.

**Comment by sinkillerj** [comment]
@MaPePeR A overall toggle would be better, he is right about them lacking EMC in the original.

**Comment by mkire** [comment]
unless something's changed, the GoED doesn't eat tools from projectE (at least in my experience), I was worried about that the first time i used one and was surprised that it didn't. Being able to blacklist torches is useful, so definite improvement over the previous gem

**Comment by williewillus** [comment]
So many different and random things, both implemented and not implemented, are listed here. If OP still is concerned about this plethora of "issues", he or she should file SEPARATE and CONCISE tickets for each of them.

**Comment by blackdragonIV** [comment]
@williewillus i really don't see the need of opening 10 different issue tickets instead of  a single post just to get things out.

**Comment by sinkillerj** [comment]
@blackdragonIV The point of a issue tracker is to pinpoint and resolve specific issues, then mark them as resolved. With tickets consisting of multiple items we are unable to properly mark a issue as resolved until the entire list is resolved, this causes alot of confusion, duplicate issues in other tickets, and in general results in the issues not being resolved.
