### ISSUE TITLE
Putting EMC into transmutation table and then stacking it allows EMC duping

### ISSUE THREAD

**Issue by Heimdell** [sinkillerj/ProjectE#717]
How to reproduce:
1) take 2 transmutation table (later TT);
2) put one down;
3) put some emc in it;
4) break it with appropriate tool;
5) make sure the TTs are stacked;
6) place both down;
7) observe EMC in both;
8) ???
9) Gem Armor in 30 minutes.

Maybe, the TT should be like other machines, unstackable and with distinct EMC storage?

**Comment by sinkillerj** [comment]
EMC is bound to the player, not the tablet, as such the EMC value should be the same in both.
