### ISSUE TITLE
Typo in Relay MK2

### ISSUE THREAD

**Issue by Zoryn4163** [sinkillerj/ProjectE#718]
The internal/unlocalized/whichever (not overly familiar with terms) has a typo. 'Realy' instead of 'Relay'
See: ![img](http://i.gyazo.com/6777bbf66ec1bf58cfc444cd82ed2ad4.png)
Using: ProjectE-1.7.10-PE1.4.6

**Comment by Kolatra** [comment]
Okay, I am going to fix this, and the rest of the UNs that have spaces in them.

**Comment by sinkillerj** [comment]
Of all the possible typos that one has to be the funniest. 

![](http://www.perivision.net/wordpress/wp-content/uploads/2011/11/rageface-really.jpg)

**Comment by ErrorCraftLP** [comment]
Fixed in #720.
