### ISSUE TITLE
RE: EMERALD

### ISSUE THREAD

**Issue by Carbon-Ghost** [sinkillerj/ProjectE#722]
I have a problem with emerald value, I want to change it to 8192 ( like EE3 ), but the problem is if I change it, the transmutation of emerald to diamond will allow a dupe bug ;(

**Comment by MaPePeR** [comment]
then minetweak the recipe away ;)

**Comment by Carbon-Ghost** [comment]
The point is I tried but it doesn't work :c

**Comment by MaPePeR** [comment]
its a totally normal crafting recipe. there is nothing special about it...

**Comment by Carbon-Ghost** [comment]
But for some reasons it still doesn't work ;( Try by yourself, last time I tried it just output me zs.null error, and that's still ok compared to the time before where I crashed, so my suggestion, make a config option for blacklisting philosopher stone recipes ?

**Comment by sinkillerj** [comment]
We may want to move into making things like that and the collector fuels config files where you define a list of items.

**Comment by Carbon-Ghost** [comment]
If that means this will be fixed, thx ^.^

BTW : How are aggregators going ^.^ ?

**Comment by sinkillerj** [comment]
@Carbon-Ghost I have not had time to work on the EE1 mod yet, but it is still in my plans.

**Comment by Carbon-Ghost** [comment]
Kk ^-^
