### ISSUE TITLE
even more bugs

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#724]
i have been playing around with the amulets and the results are pretty funny 

http://oi62.tinypic.com/14e2ccn.jpg

http://oi60.tinypic.com/14kfh9v.jpg

when water / lava orb from the amulets as well as explosion lense from the hyperkinetic and catalytic lense is fired in a general direction that is NOT directly upward and if no blocks to impact with , the orb and lens will continue to fly until it is out of loaded chunks , however if player attempts to follow the orb / lens he would find the above , these lenses or orbs do NOT despawn  and closing the world and reloading it again dose not remove them either they just float there and do not move what so ever. 

also explosion from both lenses should create a creeper effect explosion particles and harm nearby mobs also they create the sound nova.ogg from ee2 music files rather than the standard creeper explosion sound

also the gem of eternal density is converting items at a very slow rate please speed it up 

finally gem of eternal density and blackhole band should trigger on automatically when dropped into an alchemical bag

also there is some issues with gem of eternal density when setting mode , for example setting it to iron mode give pe.gemdensity.mode_switch Iron Ingot

i am not sure but the command projecte_reloaadEMC fills my inventory with random items sometimes it filled it up with gold other time it filled it up with red matter other times it dose not give anything which makes it a very odd bug

**Comment by williewillus** [comment]
1. I'm going to make it so that those projectile automatically expire after about 20 seconds.
2. Okay, will check the sound
3. Uh? It converts at an item consumed per tick. Not sure what you're asking for.
4. Maybe
5. The message issue is resolved in #704 
6. No idea, @MaPePeR ?

**Comment by MaPePeR** [comment]
> i am not sure but the command projecte_reloaadEMC fills my inventory with random items sometimes it filled it up with gold other time it filled it up with red matter other times it dose not give anything which makes it a very odd bug

Thats probably the Gem of eternal densitys reaction to "emc cleared, but emc calculation not finished"

**Comment by blackdragonIV** [comment]
@williewillus 

here are some test result with ee2 and project e

i filled an alchemical bag fully with stone except one slot for the gem and let it run with a timer and here are the result 

EE2 

gem- 33.41 sec

void ring- 32.81 sec

project e

gem- 4 min 41.48 sec

i assume it is different  because how minecraft 1.7 handles ticks in compare how 1.2.5 do

**Comment by williewillus** [comment]
yeah, I care about matching ee2, but not enough to make the times exactly the same. That's just pedantic and we're not gonna waste time tweaking the rate, sorry :p

**Comment by blackdragonIV** [comment]
@williewillus 

lol
