### ISSUE TITLE
setEMC commands not working, 1.4.7

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#732]
In the most recent update, I've found that the commands, projecte_setEMC etc, no longer work. When used on the server, it simply returns "unknown command". This issue wasn't present in 1.4.6

**Comment by sinkillerj** [comment]
Please read the changelog, the commands have been unified. You now must type "/projecte setEMC"

**Comment by Tencao** [comment]
You may want to update the config file listing the commands, especially for existing custom emc configs.
