### ISSUE TITLE
IC2 and Talisman of Repair

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#734]
[B#301] [09:01:30] [Server thread/WARN] [IC2.Item]: Detected invalid armor damage application:
[B#301] java.lang.Throwable
[B#301] at ic2.core.item.armor.ItemArmorElectric.setDamage(ItemArmorElectric.java:149) [ItemArmorElectric.class:?]
[B#301] at net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:222) [add.class:?]
[B#301] at moze_intel.projecte.gameObjs.items.RepairTalisman.repairAllItems(RepairTalisman.java:86) [RepairTalisman.class:?]
[B#301] at moze_intel.projecte.gameObjs.items.RepairTalisman.func_77663_a(RepairTalisman.java:62) [RepairTalisman.class:?]
[B#301] at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:381) [add.class:?]
[B#301] at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:311) [yx.class:?]
[B#301] at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:538) [yz.class:?]
[B#301] at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) [sv.class:?]
[B#301] at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) [yz.class:?]
[B#301] at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) [mw.class:?]
[B#301] at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) [nh.class:?]
[B#301] at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) [jd.class:?]
[B#301] at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) [jd.class:?]
[B#301] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[B#301] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[B#301] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[B#301] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[B#301] at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) [bsx.class:?]
[B#301] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[B#301] at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

This apparently happens alot, and this is with the latest IC2, the latest Project E, and the latest Forge. Reason I report it here is it seems more of an issue with Repair Talisman trying to repair what it shouldn't

**Comment by Tencao** [comment]
A solution could be a simply blacklist option in the config for items it shouldn't try to repair

**Comment by sinkillerj** [comment]
We obey noRepair, they need to set it on their item.

**Comment by Tencao** [comment]
Ok thank you, I'll redirect this to the IC2 team.
