### ISSUE TITLE
Item duping bug w/ Resolute Ivy

### ISSUE THREAD

**Issue by SunnyTD** [sinkillerj/ProjectE#738]
How to reproduce: Craft volcanite amulet with resolute ivy in any crafting table. 

Problem: Creates 2 amulets. 

Screenshot: 
1) http://i.imgur.com/A2fT1d8.png
2) http://i.imgur.com/bP4mp1B.png

**Comment by sinkillerj** [comment]
Botania issue resolved in R1.6 175+: http://botaniamod.net/changelog.php

**Comment by SunnyTD** [comment]
I have Botania R1.6-190.
