### ISSUE TITLE
setEMC command can't be run from command blocks

### ISSUE THREAD

**Issue by bigjust12345** [sinkillerj/ProjectE#743]
Trying to run the setEMC command (or possible other commands, I have not tested) from a command block results in "You do not have permission to run this command". Being able to run the command from command blocks would mean command computers from computer craft would be able to also use the commands, which I would find useful for automation.

**Comment by williewillus** [comment]
this is because the PE commands are set to require a permission level of 4 (highest) while command blocks can only execute at level 2 (op) and lower. 

@devs should this be allowed?

**Comment by sinkillerj** [comment]
EMC is not meant to be changed on the fly, allowing command blocks to execute this would be pointless.
