### ISSUE TITLE
Crashed with Destruction Catalist

### ISSUE THREAD

**Issue by Heimdell** [sinkillerj/ProjectE#744]
Report: https://gist.github.com/Heimdell/c3144910c1b7f9589cce
Screenshot: 
![2015-05-24_12 41 23](https://cloud.githubusercontent.com/assets/1784505/7787392/7359bcd0-0212-11e5-8cb8-ffcdd77533ee.png)

The Klein star got drained completely (is THAT the issue?).

The version is 6 day old.

**Comment by williewillus** [comment]
It's caused by an oversight/fault in the comparator I use to sort the items before dropping the lootball. Fix incoming.

Has it happened more than once or just this time?

**Comment by Heimdell** [comment]
Many times while trying to dig this mesa mountain.
