### ISSUE TITLE
Transmutation Tablet Memory

### ISSUE THREAD

**Issue by illusive817** [sinkillerj/ProjectE#753]
Left a comment on a earlier bug report , but it was closed
several items are constantly getting lost? from the tablet memory 
they dont seem to be in any order or sequence. they could be vanila or mod items.

i have had to relearn many many items , is there a item cap or something?

**Comment by Parker8283** [comment]
You can still comment in closed bug reports. They can be reopened

**Comment by Parker8283** [comment]
EDIT: Ignore me, didn't realize that the issue was from before the ownership change.

**Comment by illusive817** [comment]
No worries , thanks

**Comment by MaPePeR** [comment]
Recent version?

**Comment by illusive817** [comment]
always

**Comment by illusive817** [comment]
i have occured throughout the different versions , but it seems to occur more often now

**Comment by sinkillerj** [comment]
We are aware of a issue regarding the transmutation table forgetting items when new ones are added and are investigating possible solutions at this time.

**Comment by sinkillerj** [comment]
Closing as saving code has been overhauled in the latest stable.

**Comment by Omniwrath** [comment]
I just encountered this bug with PE1.9.4 in the Project Ozone mod pack. It does seem that the items I learned earliest are being forgotten, but I lost a ton of items. I only have ~9 pages (in the ProjectE UI) of items saved now, where I'm certain I had far more pages earlier.

**Comment by s1mples** [comment]
Same problem.
ProjectE-1.7.10-PE1.9.4.jar
Project Ozone modpack.
Look like - more items u have a learned - more chances to forget after relog.
Where is stored list with known items? This storage can be a problem (limited/bugged)?

**Comment by NibNab** [comment]
Just had the same problem on FTB DoWhatYouWant modpack.
It seams I had access to all my items during the first use of the transmutation table but I wasn't able to pull them.
After closing and reopening the table, a lot of items learned during previous sessions where lost (but not items from the last session).
Relogging doesn't help...

**Comment by jeffrash** [comment]
Just had the same problem with 1.7.10 of Project Ozone modpack.
