### ISSUE TITLE
Lost tablet research on dimension change.

### ISSUE THREAD

**Issue by megamanzteam** [sinkillerj/ProjectE#757]
I have been playing on a Lan party world. I took a trip to the nether and came back and my tablet research was wiped. We are using ProjectE-1.7.10-PE1.4.7.jar. I know there is a current issue with lost research, but I don't recall any mentioning on dimension change. Hopefully this information might better help identify this issue.

**Comment by sinkillerj** [comment]
At this time LAN mode is not supported, to avoid issues please run a actual server jar, when configured correctly this does not provide much of a added performance hit.
