### ISSUE TITLE
Axe power crash to desktop

### ISSUE THREAD

**Issue by megamanzteam** [sinkillerj/ProjectE#758]
When using the dark matter, red matter and katar, right clicking any tree causes CTD. This happens mostly when there are a lot of trees together. MFR rubber trees do seem to cause an immediate crash, while dark oak does not. I will be able to upload a crash report later for you. using v1.4.7.

**Comment by williewillus** [comment]
Working for me on dark oaks in close vicinity. It'd be great if we could see a log! :)

**Comment by megamanzteam** [comment]
OK here is the crash log: http://pastebin.com/wE06YNuH
and a screen shot before testing: 
![2015-05-31_15 08 35](https://cloud.githubusercontent.com/assets/4212359/7903597/59685026-07a7-11e5-9cf8-678da894df75.png)
I am using the lowest power. When I do relog into the game there is no lootball or wood, but the leaves exist and decay as they consider the wood harvested.

Also just in case you need it the full log: https://www.dropbox.com/s/ml2rlwwuztmhcqc/fml-client-latest.log?dl=0 (sorry pastebin won't take such a large file)

**Comment by williewillus** [comment]
Ah, that. Fixed in the next release so bear with it until then. Sorry! :<

**Comment by williewillus** [comment]
Req close fixed in 1.5.0
