### ISSUE TITLE
[Suggestion] fire/water amulet improvement

### ISSUE THREAD

**Issue by megamanzteam** [sinkillerj/ProjectE#759]
Back in the old ee2 days the fire amulet when swimming in lava allowed you to see perfectly in lava without the flame effect or red fog. So may I suggest you checking out mariculture's code for their scuba mask. They make swimming in water nice and clear. I am sure you can do this for the water amulet and modify it to also work for lava.

**Comment by williewillus** [comment]
just tried in tekkit and there's no indication it ever did this
