### ISSUE TITLE
Gem of Eternal Density Dupe

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#765]
As a member on my server showed me yesterday, you can infinitely dupe with the gem of eternal density by constantly changing the mode from iron all the way up to red matter. Whether this is a miscalculation in emc values, or something else, I'm not sure, but he was easily able to turn stacks of diamonds into stacks of RM, which shouldn't normally be possible.

**Comment by williewillus** [comment]
I can't produce this, can you give me exact steps?

**Comment by sinkillerj** [comment]
Duplicate of #748 . Fixed in next version.
