### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by Krigeris** [sinkillerj/ProjectE#769]
Gem of eternal density does not work properly, deletes the contents of my alchemy bags and chests. It also removes important items like torches and such, you should just have it use a list of common mineable items to condense to prevent tools being lost.

Also the nova catalysts and nova catalysms do not work like they originally did in EE2. The loot balls used to spawn on the player, not the point of detonation. That way you could set up an obsidian room full of chests full of eternal densities and then detonate hundreds of catalysms and just let it all condense.

**Comment by sinkillerj** [comment]
The gem is intended behaviour, it has a blacklist if you need one.

**Comment by Krigeris** [comment]
The gem itself gets deleted, sorry for not clarifying

**Comment by sinkillerj** [comment]
Eek thats certainly not right

**Comment by williewillus** [comment]
Does this still happen? If so, what version, modpack, and steps to repro?

**Comment by MaPePeR** [comment]
Can be closed, i guess...
