### ISSUE TITLE
key bind and some other derps 

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#770]
*here are some stuff regarding keybind that i found implemented incorrectly

1-red katar AoE attack is activated with R key not C key

2-gem armor offensive abilities and the offensive activation buttons only work when no item held in hand which is not how it used to do in ee2 , you can do it with any item held as long as it is not EE related, example. pickaxe , shovels ,hammer, rings...etc

3-long, wide ,tall and mega impact modes as well as slay all / hostile modes  are changed using the C key not the G key

4-the arcana ring key binds also need a bit of tweaking , this is how the original EE2 keybinds worked

G activate ring

RIGHT CLICK fire projectile (if any)

R special function of ring

C the only extra key in ring of arcana which allow you to switch modes

**Comment by sinkillerj** [comment]
It's hard for us to fix issues when you spam the ticket with no punctuation, no capitalization, info on things that arent broken, and try to merge 50 issues into one. We try to address all issues to the best of our ability, but in order to do so we ask that you do try to follow certain standards when submitting issues.

**Comment by blackdragonIV** [comment]
@sinkillerj  sorry if it all seem juggled up i am just trying to report the issues. regarding things are not broken that i am reporting, i am just reporting these because i wanted to post everything without having to jump between ee2 client and project e modern minecraft client to test what is implemented differently or incorrectly ,because the loading time is absurd and i cant have both open at the same time my pc is not very powerful to handle that.

i will try to have a better post of the issues next time. once more i apologize for the mess

**Comment by blackdragonIV** [comment]
@sinkillerj  i updated the post, hopefully it is better and more clear on addressing the issues
