### ISSUE TITLE
Lost bag data

### ISSUE THREAD

**Issue by dogamusprime** [sinkillerj/ProjectE#771]
Installed latest version and lost bag data. Deleted all of my bag contents. I won't be responding to this. Just letting you know it happened.

**Comment by rancidgnome** [comment]
Using the blue Alchemical Bag, I twice lost all contents and then stopped using it. This was the first time that I experienced this bug and I have used your mod in a few packs with out any issues. I'm using PROJECTE-1.7.10-PE1.5.0 in the Resonant Rise 3 pack on the At launcher. I didn't see any log issued and the console log also was absent any information about this. I am using Fastcraft as well

**Comment by williewillus** [comment]
We've been trialing some new saving code for the past few weeks that looks to eliminate all these issues. Super sorry that you lost your data! Hopefully we can get the fix out very soon :)

**Comment by QAraignee** [comment]
Exactly the same problem as rancidgnome with my white alchemical bag- just letting you know, I saw that you're working on it :)

**Comment by sinkillerj** [comment]
Closing as saving code has been overhauled in the latest stable.
