### ISSUE TITLE
Offensive ability config ?

### ISSUE THREAD

**Issue by Carbon-Ghost** [sinkillerj/ProjectE#777]
Can we have a config for that as it kills servers PVP gameplay :/

Also, if possible, can you do something with the extreme extension of FOV when you use the boots ?

**Comment by abaw7** [comment]
I already requested this in the original pull request, guess @williewillus forgot though...

**Comment by williewillus** [comment]
I've been focusing on the bags these past few days, sorry! I'll see I i can get em in  tmrw

**Comment by Carbon-Ghost** [comment]
thx
