### ISSUE TITLE
Black Hole Band in DM Pedestal crash

### ISSUE THREAD

**Issue by Phyn** [sinkillerj/ProjectE#778]
The actual line number is lost in translation, but:
http://openeye.openmods.info/crashes/89b39f35de1f46d40b308aea2b56ded7

The exact conditions are the DM pedestal above a Black Hole Chest from TubeStuff while moving away from the chunk, but the storage may not matter. It crashed and left me in a crash loop.

**Comment by abalabahaha** [comment]
The Black Hole Chest was rather famous for occasionally corrupting chunks/servers... Not sure if it still happens.

**Comment by sinkillerj** [comment]
@abalabahaha ProjectE is a completely new code base, no code from EE2 is used, so no EE2 bugs are present.

**Comment by abalabahaha** [comment]
@sinkillerj The Black Hole Chest was never from EE2.

**Comment by williewillus** [comment]
Either way, I fixed the issue :p
