### ISSUE TITLE
Exception in reloademc thread

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#783]
http://pastebin.com/CJ1SigLS

Sometimes when I try to set, remove, or reload emc, I get this error at the end. The weird part is, if I do the command again, sometimes it just works straight away.

Any idea what causes it?  (look at the bottom for the error)

**Comment by sinkillerj** [comment]
I'm thinking about reworking the commands to be honest, the threading is just causing even more trouble. Thinking about redoing it so you set all your values and then type a command to lock them in, the threading would be removed and the server would lag a little, but EMC changes should be fairly rare, and the lag would only occur when you lock in.

**Comment by Tencao** [comment]
To be honest, half the time I still manually do it in the config, but when the servers running, and something is missing an emc value, it is nice to just quickly add it. I think the lock-in idea would work much better, since it is rare for me to do emc edits, despite how many I've done, and when I do, I usually do it in bulk

**Comment by sinkillerj** [comment]
Closing as threading is removed.
