### ISSUE TITLE
Viewport change on equipping Hurricane Boots (zooming)

### ISSUE THREAD

**Issue by boggensagg** [sinkillerj/ProjectE#785]
I am not sure if this is intended, but when I equip the Gem Armor boots my view port changes. It appears zoomed in. Almost like I was carrying a JABBA barrel dolly or an Extra Utilities Bedrockium ingot.

Is this intended? If so, could there be an option to disable this? It is extremely irritating.

**Comment by Carbon-Ghost** [comment]
Ikr ? Especially in MAX FOV, unfortunately, that's a vanilla feature, you can't change it normally ( like also the unintended feature that allows to be faster while holding boots ), well here are my solutions : 
- Set your FOV to 85, it will make it like the MAX FOV, just a tiny bit bigger but should be unnoticeable. 
- Project E dev, set the bonus speed like the thaumcraft boots ;)

**Comment by sinkillerj** [comment]
We can actually augment the FOV changes, and I plan to fix this.

**Comment by MaPePeR** [comment]
Wasn't this fixed by #690?

**Comment by sinkillerj** [comment]
@MaPePeR No... That is what broke it actually lol

**Comment by williewillus** [comment]
Yeah a simple fov event should fix this.
