### ISSUE TITLE
Transmutation Tablet will not learn "Septuple Compressed Cobblestone"

### ISSUE THREAD

**Issue by OmniSpecter** [sinkillerj/ProjectE#787]
I just setup an EMC farm, intending to use octuple compressed cobblestone as the base to create, and taught the tablet each level of compressed cobble, however I noticed it will not accept the septuple compressed cobblestone [metaID 754:6 from Extra Utilities] even though it has an EMC value. It learned all the others just fine though.

**Comment by Kolatra** [comment]
Two questions, what is the EMC value on the block, and are you possibly reaching the max EMC in the tablet?

**Comment by OmniSpecter** [comment]
The EMC value is 4,782,969 per block, and I'm not sure if there is a max EMC on the tablet, as I've seen Wyld on his twitch streams have a over one billion stored EMC on his tablet, and I'm currently only at about 54 million stored EMC. 

Might help to note as well that at the time, I was simply teaching the tablet the new items, I wasn't actually adding it yet, but even when I later tried adding the stone, it accepted the EMC, but still wouldn't teach the tablet the block itself. Though like I said originally, it accepted every other compressed version of cobblestone by Extra Utilities mod with no trouble.

**Comment by pupnewfster** [comment]
Closing this as it is no longer an issue.
