### ISSUE TITLE
Server crash with Project E

### ISSUE THREAD

**Issue by Ryan3138** [sinkillerj/ProjectE#793]
Recenty I made a RR3 server with Project E. I cannot figure out what keeps crashing the server. If you would spare one moment to tell me what a fool of a Took I am. The server only crashes when Project E is in. I have tried with version 1.5.0 and 1.6.0.

1.5.0: http://pastebin.com/bUN3HCJ6
1.6.0: http://pastebin.com/Ug3kNYak

**Comment by williewillus** [comment]
The first one I *might* know where is coming from; I don't think the second one is our fault.
Can I get a little more context, if you can? What projectE blocks, machines, or items are being used? With what other mods?

**Comment by Ryan3138** [comment]
No blocks have been placed form Project E. It crashes on load up. The mods in the pack should be in the pastebin. It does have fastcraft if that changes anything.

**Comment by Ryan3138** [comment]
1.5.0 is the mod version I am trying to get into the pack. 1.6.0 was a test to see if it would stop crashing.

**Comment by williewillus** [comment]
Is there an instance of the pack i could get (curse, technic, ftb, ATL, whatever) to test this?

**Comment by Ryan3138** [comment]
Resonant Rise 3.2.6.8 Server
Sharecode: Ktzh2i38

**Comment by williewillus** [comment]
thanks!

**Comment by williewillus** [comment]
It starts fine for me and I can enter a world fine on that sharecode :( (ProjectE 1.5.0)

**Comment by Ryan3138** [comment]
Interesting... I will try redownloading a fresh instance of the server.
Not to be offensive but you did use the server version to test right? It doesn't crash for client only for server.

**Comment by Ryan3138** [comment]
Appears a reinstall helped... So confused. I tried this before too.
