### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#794]
so here are some issues i found

ok first of all i did post some key bind issues on my previous ticket ,however it seems my post was not clear and i noticed  no one payed much attention about what i posted on that topic and nothing has been changed in the latest release, regardless i will post what really mattered about the binds here and if these were already planned to be implemented/ changed in the future then just ignore the key binds issues and thank you for understanding.

gem armor offensive abilities and the offensive activation buttons only work when no item held in hand which is not how it is suppose to be , you can do it with any item held as long as it is not project E related, example. pickaxe , shovels ,hammer, rings...etc

the arcana ring key binds also need a bit of tweaking , it should be very similar to normal rings and its quiet irritating and OCD hurting that it is not so it's functions are as follow.

G activate ring

RIGHT CLICK fire projectile (if any)

R special function of ring

C the only extra key in ring of arcana which allow you to switch modes

as for the other stuff.

the projectiles from ignition / swift wolf / arcana ring are effected by gravity, where they are not suppose to , also they are effected by the repulsion ability of arcana ring / swift wolf where they also should not be, in shorts they should have the same behavior as the explosive lenses

passive growth of crops is not working when switching to green ring mode in arcana ring, instead it becomes active when harvest mode is active which is odd, it should work when the ring is switched to green mode and is on the hot bar regardless of harvest mode (exactly like the harvest goddess band)

I noticed you can not place water / lava using the amulets with right click or with the projectiles where there is already lava / water source block or flowing block , might want to look into that.

the yellow arcana ring projectile should only strike lightning when activated , when not active it will only fling mobs backward and into the air

transmutation table is being funky about NBT and metadata 

![transmutation](https://cloud.githubusercontent.com/assets/7633717/8194894/ea3ccd8c-147e-11e5-96b8-671d9c5946c3.PNG)

dark matter shovel only have one charge level , should be two levels.

R key on harvest goddess band will use bone meal or emc to instant grow crops.
.
when activated with G the stones should preform their functions regardless of their position in the inventory, currently they only operate when on the hot bar

**Comment by williewillus** [comment]
Please do not repost the same issue over, and over, and over....
1. The keybinds will not change - that is a fundamental difference in how things are implemented in EE2 vs ProjectE. I'm sorry if it tickles your OCD - I myself am a nazi for following EE2 but this isn't one of the things that should or needs to change.
2. I made it so it's only empty hand so people don't accidentally blow up their house trying to use some other mod's item that has the same keybinding
3. Projectile gravity behavior noted
4. Amulets being looked at 
5. Lightning strike looked at
6. I don't know how you got that helmet in there, that usually is impossible
7. okay.
8. okay.
9. No, it's hotbar only. I checked in EE2.

From now on please separate your issues and make your posts concise - strip out all the fluff, get to the point, and please report one thing at a time.

**Comment by blackdragonIV** [comment]
@williewillus all right thank you the only reason i reposted the issue because i was not notified if some one did actually take a look so sorry about that.
