### ISSUE TITLE
[Suggestion/Enhancement] Custom EMC Mapping

### ISSUE THREAD

**Issue by accessdenied0** [sinkillerj/ProjectE#795]
Dear @sinkillerj,

I don't know if this could be ever be a thing, but I don't like the fact that It reloads every time any value immediately by the command "set_EMC", so it is possible to "store" all entries in a list and execute the entries by another command like "reload_EMC"? It would be very nice, because it reduce the reload "impact" on a singe one instead of a (possibly) hundred of times... 

I know the mod "Aeather-Craft" (> https://github.com/iconmaster5326/AetherCraft) had such method... sadly it is discontinued.

access_denied

**Comment by MaPePeR** [comment]
Already implemented.

See [pregenerated EMC](https://github.com/sinkillerj/ProjectE/wiki/Configuring-EMC-calculation#pregenerated-emc)

**Comment by accessdenied0** [comment]
Dear @MaPePeR,

Not what I meant. It is the same function like standard just with the change that you execute the command "setEMC" so frequently as you want, and it store it temporarily or save it in the  "custom_emc,cfg", <b>BUT</b> it reloads all the EMC-data only by the "reload_EMC" command.

access_denied

**Comment by MaPePeR** [comment]
You can very easily do that with the pregen-file.
just instead of the modified reload_EMC file you are requesting delete the pregen file.

**Comment by accessdenied0** [comment]
Dear @MaPePeR,

Excuse me? So far I read and understood this, it is over two edges... I don't want disable the calculation, I just want to adjust the reload of the calculation to a separate command. This would be way more user friendly and on the fly. It changes nothing, really. Just the impact by reload the complete map for ever single use... I don't understand really what do you mean... your solve of this problem is to deactivate the calculation, generate a separate file adjust this file and reactivate the whole thing again... is it not... laborious? I have to restart all over and over again if I want to make changes... or do I miss understand this now?

access_denied

**Comment by MaPePeR** [comment]
when you enable pregenerated emc the setEMC command will not trigger an emc calculation. (This is what you want). 
As long as the pregenerate-option is enabled and the file is present the setEMC command will just write your values to the custom_emc file (this is what you want)
When you are finished with using the setEMC command you can disable the pregenerate-option again and the new values will be calculated from all your previous setEMC commands.

> I don't want disable the calculation, I just want to adjust the reload of the calculation to a separate command.

As i understand it you want to disable the calculation for the setEMC command.


> your solve of this problem is to deactivate the calculation, generate a separate file adjust this file and reactivate the whole thing again

you don't have to generate or adjust the file by yourself. the first emc calculation with the option turned on will automatically generate the file.

> I have to restart all over and over again if I want to make changes...

No

**Comment by accessdenied0** [comment]
@MaPePeR,

I think you miss understood me. I <b> don't </b> want to disable the trigger from the "setEMC" command  to calculation I just want move them to "reloadEMC". And so far, If I disable or enable a option, it needs a restart, or is this here a special case?

access_denied

**Comment by MaPePeR** [comment]
For me moving A away from B is the same as removing A for B.

For me moving the calculation from setEMC to reloadEMC implies, that the calculation does not happen on setEMC. Which is the same as disabling it for setEMC.

> And so far, If I disable or enable a option, it needs a restart, or is this here a special case?

The `mapping.cfg` file is special and reloaded every time an emc calculation is supposed to happen (setEMC, removeEMC, reloadEMC all cause the file to be reloaded and trigger an emc calculation). 

if pregenerated is enabled the emc calculation does nothing but load the pregenerated file. 

reloadEMC does nothing but trigger calculation.

**Comment by MaPePeR** [comment]
The workflow i have in mind:

1.  Use `setEMC` and notice its very slow
1. Enable pregenerated EMC
1.  Use `setEMC` still slow because a calculation happens that is now written to the pregen file
1. Use `setEMC`. Is now very fast because the calculation does nothing but load the pregen file. The custom value is still written into the custom_emc file that is loaded on emc calculation
1. goto 4. until finished
1. All the values are not yet assigned because calculation did not yet happen
1. Disable pregenerated emc or delete the pregen file
1. The next reloadEMC/setEMC/removeEMC or game restart will triggger an emc calculation.
1. all the values are now present

**Comment by accessdenied0** [comment]
@MaPePeR,

Sorry... but... what?
"For me moving A away from B is the same as removing A for B." -- n-no it is not. A simple move of a code to another place can improve or adjust performance and function in general... It can never be the same...

and still... it is a work around... here mine:

1. Use setEMC to list your EMC's
2. Use reloadEMC to trigger the calculation
3. all the values are done.

is this more complicated than your ones?

but well, if you don't want to, I'm fine but this seems not logic...

**Comment by sinkillerj** [comment]
Short answer is I'm working on this.

**Comment by MaPePeR** [comment]
Your workflow requires someone to write/change code and wait for a new build to be public.

You can use my workflow right now. ;)

**Comment by accessdenied0** [comment]
@MaPePeR, Oh... now I'm dump... sorry I miss understand this in general. I'm Sorry. It was my mistake I guess.

**Comment by sinkillerj** [comment]
EMC commands will be changed to a lock in system where you first add your values and then type a command to reload EMC instead of it doing it automatically after each add. This has been planned for a couple weeks now. Please keep issues on topic.

**Comment by sinkillerj** [comment]
Now implemented.
