### ISSUE TITLE
Pull item from condenser

### ISSUE THREAD

**Issue by DrJedikiah** [sinkillerj/ProjectE#801]
Energy Condensers doesn't let pull items from in.

**Comment by williewillus** [comment]
Do you mean that items can't be pushed in (export bus, hopper, or pipe pointing in the condenser) or the condenser doesn't auto pull from adjacent inventories? The first should work.

**Comment by DrJedikiah** [comment]
Yes, i mean i can't pull items via export bus, etc. Only with storage bus, but it just let me to see them into network.

**Comment by abalabahaha** [comment]
You pull with an import bus, and shove with a export bus. Did you get those mixed up?

**Comment by DrJedikiah** [comment]
I was tried with  Itemduct but it didn't worked too :(

**Comment by sinkillerj** [comment]
I'm not sure what you are doing wrong, maybe you have a mod that modifies pipe behaviour, but whatever it is I firmly believe is unrelated to ProjectE. I have been unable to reproduce this issue on servers I play on that run up to date versions.

**Comment by williewillus** [comment]
Just a note that might clear things up - looking at the code, it only lets you extract if the item matches the lock slot. So if the lock has changed since that item was made you can't. Idk why that is though.

**Comment by sinkillerj** [comment]
@williewillus You wouldn't want to suck out items that are supposed to be consumed.
