### ISSUE TITLE
Tome of knowlage not working 

### ISSUE THREAD

**Issue by ares3800** [sinkillerj/ProjectE#802]
I can't insert the time of knowlage into the transmutation table. I have checked the config but there is nothing there about it other than how to craft. BTW I am using the natural magic pack on the AT Launcher

**Comment by Kolatra** [comment]
If the config value is false, there is no recipe, therefore no EMC value, and items that do not have an EMC value cannot be placed into the Transmutation Tablet.

**Comment by sinkillerj** [comment]
Thanks for reminding me, ill get this fixed after I merge willies unification pull.
