### ISSUE TITLE
NEI Integration for philosophers stone

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#806]
At the moment the capabilities of the philosophers stone are kind of a mystery.

**Comment by sinkillerj** [comment]
Are you suggesting that things such as world transmutations should be added?

**Comment by williewillus** [comment]
yeah idk what this means - I thought it was about [?] button support in the crafting interface at first :p

**Comment by sinkillerj** [comment]
NEI...addons? Adds ? button support for the stone. One of those addon mods.

**Comment by MaPePeR** [comment]
? Support would also be nice, but i was talking about world transmutations. So they show up as a recipe.

**Comment by MaPePeR** [comment]
#821 has been merged
