### ISSUE TITLE
Possible sync issue with tablet.

### ISSUE THREAD

**Issue by Koolguy007** [sinkillerj/ProjectE#811]
I've been having trouble with the transmutation tablet doing some strange things. Sometimes when I pull an item out from anywhere. except the top of the page, the item will transform into something else that was also showing on the current page. This can happen immediately or a few seconds after it's in my inventory.

Items pulled from a tablet use EMC, but when I reopen the tablet all the EMC is back. Inserting items into the tablet will add to the EMC, but after closing the items will reappear in my inventory and the EMC will be gone again. Again the table works fine, just the tablet is acting weird.

**Comment by williewillus** [comment]
Version?

**Comment by Koolguy007** [comment]
1.7.0A

**Comment by williewillus** [comment]
Hm, that's strange. There was a major cleanup in the transmutation interface after 1.7.0A so hopefully those might resolve these problems (which I personally haven't been having). Thanks for the report!

**Comment by williewillus** [comment]
@Koolguy007 if it's not too much hassle, does this issue still happen in 1.7.1?

**Comment by Koolguy007** [comment]
The problem seems to have been corrected. Good work guys. Loving the mod.

**Comment by williewillus** [comment]
Yay, thanks!
