### ISSUE TITLE
Alchemical Chest and Condensers render as Vanilla chest in inventory

### ISSUE THREAD

**Issue by sinkillerj** [sinkillerj/ProjectE#815]

**Comment by williewillus** [comment]
I've heard people on the minecraftforge channel say that fry has made an obj model of the vanilla chest, so maybe we could steal that and retexture it and use it for the inventory model. Though I have no idea (and there's no docs >.>) on how to use the OBJLoader

The only alternative would be hacksy stuff like reflecting into TEISR, or making a json model for the chest

**Comment by sinkillerj** [comment]
I will probably just make a json model unless someone beats me to a pull, its not terribly hard with the tools out there.

**Comment by williewillus** [comment]
kk

**Comment by starwarsmace** [comment]
I've actually used the .obj loader for items and blocks won't be much different. If you want I could help out on that...

**Comment by williewillus** [comment]
I went ahead and got this done ^^
