### ISSUE TITLE
Items that do not leave the crafting grid may cause EMC mapping issues

### ISSUE THREAD

**Issue by sinkillerj** [sinkillerj/ProjectE#818]
Due to the removal of a Vanilla method some EMC mapping code regarding items that do not leave the crafting grid had to be changed, please report any issues with items of that type here.

**Comment by MaPePeR** [comment]
@sinkillerj  i think this is resolved now... we tested this with the philo stone

**Comment by sinkillerj** [comment]
Gonna leave this open for now till 1.8 has been tested more by the general public.

**Comment by williewillus** [comment]
I think this is fine from my experience and no issues reported for months
