### ISSUE TITLE
Transmutation Table Bug (DNS Tech Pack)

### ISSUE THREAD

**Issue by iHackMC** [sinkillerj/ProjectE#830]
whenever i search or go beyond 15+ pages in the transmutation tablet i never get what i want, if i take out a xp bottle, i get a steam producer instead. the top 3 on the right always gives me a steam producer (power converters) no matter what they are or look like. everything else below it is desynced i.e search bottle and pull out a xp bottle when clicking on water bottle (both on right pane). Not sure if this issue has been addressed yet and if it is then dismiss this post.

-thanks

**Comment by williewillus** [comment]
1. mod version?
2. SP or MP?
3. Can you start the game, reproduce the error, then send me your latest FML log (the super long and detailed one, *not* latest.log.

**Comment by williewillus** [comment]
If in MP, if you can get your hands on fml-server-latest.log, send that as well.

**Comment by sinkillerj** [comment]
Some items are known to cause issues in the transmutation table and should be unlearned, this is a known issue that we currently do not have a good solution for. Examples include JABBA barrel upgrades and the QED. The bad item will generally be on the first page the desync occurs.
