### ISSUE TITLE
Transmutation table GUI showing duplicated items

### ISSUE THREAD

**Issue by kutschkem** [sinkillerj/ProjectE#832]
I don't know what exactly happened, but my transmutation table looks like this:

![image](https://cloud.githubusercontent.com/assets/1106888/8554910/0daf8902-24ed-11e5-8586-fe1d1bedf02b.png)

The issue persists beyond restarts, but when I learn a new item it is not duplicated. I am using version 1.7.1.

**Comment by williewillus** [comment]
Was this save ever loaded in 1.7.0A?

**Comment by kutschkem** [comment]
Apparently, I started with 1.5.0, and had 1.6.0 in between. I am not 100% sure I did or didn't have 1.7.0A, it didn't show up in my version history. Did you publish that one on Curse? If so, there is a chance that I had it in-between.

**Comment by williewillus** [comment]
yeah, some of the older versions had this issue (esp 1.7.0A).
So I think it's just older saves being loaded, especially since you said it hasn't been happening anymore.
You can either open up your player.dat, go to the PETransmutation tag, and remove the duplicate entries, or if I get around to it, I can add something to prune duplicates on load

**Comment by kutschkem** [comment]
Ok I was brave and did delete what I thought were duplicates without backup :-P I'll let you know tomorrow how it looks now.

**Comment by kutschkem** [comment]
Nope, interestingly enough, it doesn't work. The duplicated entries are restored upon load. There is also a migrated tag that is set to 1, what is that for?

**Comment by williewillus** [comment]
Migrated tells the loader that save data from ProjectE 1.6 and before was successfully migrated to a new save format. Removing it would make the save-loader load your old data and re-migrate it, so probably don't wanna do that :p 

As for the deletion, are you sure you deleted them? Here's how it would theoretically look: http://gyazo.com/bad1ff7e10c63eb6a7cc0a794330d501
Select the cardboard box above the duplicate entry then hit the delete button, then make sure to save changes before exiting. The tool shown is NBTExplorer http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

**Comment by kutschkem** [comment]
Yes that's what I did. And the second time I made extra-sure that I had saved, I reopened the file to check. In that picture you show a duplicated entry, that was just made-up for showing me, right?

**Comment by williewillus** [comment]
Hmm
Maybe the dupe entries are just dummies? Can you pull items out of both of them?

**Comment by williewillus** [comment]
fix merged

**Comment by Carbon-Ghost** [comment]
Btw small unrelated question but what mod adds the golden armor :D ?

**Comment by williewillus** [comment]
what? Gold Armor is vanilla mc, Gold Horse armor is also vanilla?
Please don't necro, also :p

**Comment by kutschkem** [comment]
That's ArmorOverlay if you mean the little shields that show armor.

**Comment by Carbon-Ghost** [comment]
@kutschkem ; That's what i wanted to know ;D

Is that how the mod is called ?

Also sorry for necro, just something I wanted to know ^^''

**Comment by kutschkem** [comment]
Here you go, this is what you actually want to know, the forum post:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293475-theoldones-simpleores-plugins-and-other-stuff

**Comment by Carbon-Ghost** [comment]
Thanks :D

**Comment by kutschkem** [comment]
Actually, I have to reopen this. Armors and Tools are still duplicated. Below a screenshot that shows the NBTTags for gold armor.
![image](https://cloud.githubusercontent.com/assets/1106888/8639964/dc794036-28e7-11e5-9c76-ee9e8f0cfcf6.png)

**Comment by williewillus** [comment]
is this in SP? if so you need to go to the player tag inside level.dat instead of your player.dat in playerdata/

**Comment by williewillus** [comment]
but 1.7.2 should have auto-duplicate removers

**Comment by kutschkem** [comment]
The duplicate removal seems to work, but only partially. For me, armors/tools as well as volcanite amulet, philosophers stone, diamond horse armor etc are still duplicated. "Normal" items are not duplicated, say wheat or ingots.
