### ISSUE TITLE
red matter pick  crash for 1.8  

### ISSUE THREAD

**Issue by anth2012** [sinkillerj/ProjectE#833]
a don't know if the mods im useing ats doin it but here the crash log http://pastebin.com/Tvw3Ai4z

**Comment by williewillus** [comment]
Resolved https://github.com/sinkillerj/ProjectE/commit/05f21ee4deecc231e4057e12fac17d08da66b262
Will be in next 1.8 release

**Comment by sinkillerj** [comment]
@williewillus Please do not close issues in the future until a fix is implemented in a public build.

**Comment by williewillus** [comment]
k
