### ISSUE TITLE
Divining Rod does not check metadata when reading furnace recipes

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#834]
Original title: All CoFH ore blocks show up in Divining Rod as 6528 EMC
Woohoo, my first self-report!
With Thermal Foundation 1.2.0b1, CoFH Core 3.0.3b2, and ProjectE 1.7.1, all Thermal Foundation ores show up as 6528 EMC. Reproduce: place floating ore block, right click with low divining rod.

Mainly for me to remember, but if anyone wants to ninja fix it be my guest.
We setup default values for these Oredict names in the OreDictionaryMapper

**Comment by williewillus** [comment]
Cause found: Divining rod doesn't check meta values when querying furnace recipes

**Comment by Carbon-Ghost** [comment]
Also pls, can we have a config for EMC values from ores ? I have copper ingots having an emc of 256 in my modpack for exemple ;P

**Comment by MaPePeR** [comment]
@Carbon-Ghost what are you talking about? Ores not having emc has nothing to do with copper emc value. 

The config to disable the blacklist for ore - emc is already present.

**Comment by Carbon-Ghost** [comment]
I was talking about divining rod values, for exemple if you loot at copper ore, it will give you the value of copper, but not the the changed value of copper if you changed it ;P

**Comment by MaPePeR** [comment]
The Divining rod uses the drop of the ore, so if you changed the emc value for copper it should report accordingly.

Make sure that you changed the emc value for all the different copper ore dictionarys

**Comment by Carbon-Ghost** [comment]
Normally changing one copper value changes all the others as I tested..

**Comment by MaPePeR** [comment]
I don't think so....

**Comment by Carbon-Ghost** [comment]
At least in my modpack every copper types have the same EMC ( 256 ).

**Comment by sinkillerj** [comment]
Lets keep this on topic please, if you have a unrelated issue open your issue, dont spam this one.
