### ISSUE TITLE
Better way of searching for items in the Transmutation Table

### ISSUE THREAD

**Issue by Koncrete** [sinkillerj/ProjectE#840]
Currently when I have a large amount of EMC and a lot of learned items and I try to get search for a diamond or something low value I either have to put something around that EMC value in or remove enough items to lower the emc closer...  Is there a better way of searching or can the table have left/right tabs to shuffle through?

Sorry if this is in the wrong section it is my first time on Github

**Comment by MaPePeR** [comment]
Pages already implemented a dozen versions ago. 

Update the mod.

**Comment by sinkillerj** [comment]
http://minecraft.curseforge.com/mc-mods/226410-projecte
