### ISSUE TITLE
Integration request: Applied Energistics 2

### ISSUE THREAD

**Issue by AlexPlus117** [sinkillerj/ProjectE#843]

**Comment by sinkillerj** [comment]
We will need further information to help you with this, what is the issue you are experiencing?

**Comment by AlexPlus117** [comment]
This is not an issue, but just a request of integration between ProjectE and AE2. I ask you if you can put please some EMC values to some Applied Energistics materials as most machines of this mod don't have a value.

**Comment by sinkillerj** [comment]
Duplicate of #844
