### ISSUE TITLE
[1.8] Crash on new world creation

### ISSUE THREAD

**Issue by GirafiStudios** [sinkillerj/ProjectE#856]
Well there is not much to say. Whenever you try to create a new world with the latest version of Project E for 1.8, it crashes. Looks like it's related to packet handling.

Crash log: http://pastebin.com/GKdwwz7G
Project E version: 1.8-PE1.0.1B
Minecraft Forge version: 11.14.3.1450

**Comment by GirafiStudios** [comment]
:+1:

**Comment by catzs** [comment]
To add on to this, disabling crafting mapping fixed the crash, and sometimes the game will load the world(random).
