### ISSUE TITLE
Can not pick up Transmutation Table with Philosopher stone anymore

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#863]

**Comment by williewillus** [comment]
That's because we got rid of the TileEntity on it entirely xD

**Comment by MaPePeR** [comment]
Yea, maybe we want to keep the Wrenchability for fast pickup.

**Comment by sinkillerj** [comment]
My vote is still to kill the wrench feature >,>

**Comment by MaPePeR** [comment]
Well - maybe remove the "Save NBT data of item"-thing. But the fast-pickup can be nice because we don't really set proper harvest materials for most of our blocks, i think.

I think you can also pickup Alchemical Chests with it, can't you?

**Comment by williewillus** [comment]
I also vote to kill the wrench thing lol
Yes, which means massively OP storage lol (bunch of chests in a bag in a bag in a bag, etc)

**Comment by Lilylicious** [comment]
Thought: Kill the wrench feature and make sure harvest materials are properly set to allow for tools to properly pick them up faster than default speed?
