### ISSUE TITLE
Drag to distribute items across slots not working in Transmutation-GUI

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#864]
I think this kind of indicates our GUI does something very wrong.

**Comment by williewillus** [comment]
Oh we just explicitly disable that (look in our container or slot classes :p). No idea why.

**Comment by MaPePeR** [comment]
... Then we should stop that :D 

i think all this code should probably be rewritten again now - also to fix the countless scrollwheel-issues and stuff. So try to make the inventory handling as vanilla as possible.

**Comment by sinkillerj** [comment]
Why would you ever need to do this?

**Comment by MaPePeR** [comment]
Cause its weird that it works in all inventories, but the transmutation tablet. :D

**Comment by williewillus** [comment]
@sinkillerj he meant the player inventory slots, you still can't (from his PR) nor need not drag in the actual tablet gui

**Comment by sinkillerj** [comment]
Ah roight, didn't know he meant the player inv.
