### ISSUE TITLE
Support for Aroma1997 recipes

### ISSUE THREAD

**Issue by catzs** [sinkillerj/ProjectE#869]
In the 1.8(and maybe 1.7) versions of ProjectE items created by aroma1997 via Aromic Crafting are unable to be taught and created by any ProjectE devices. Maybe hook into Aromic Crafting recipes??

**Comment by williewillus** [comment]
do they have emc values? if not, they can't be taught.

**Comment by catzs** [comment]
They don't, it was a suggestion for compatibility.

**Comment by williewillus** [comment]
inactivity + doable with custom values/custom jsons
