### ISSUE TITLE
Items should respect spawn protection and protection plugins

### ISSUE THREAD

**Issue by scj643** [sinkillerj/ProjectE#870]
A toggle to make items that bypass server protections not able to do it by dumbing down there effects or disabling them.

**Comment by williewillus** [comment]
there's already a config to disable items

as for the actual respecting spawn protection thing, that's being worked on.

**Comment by DZCreeper** [comment]
Is there any sort of standard for protection plugins on Forge? I know several existed for Bukkit/Cauldron but that can't be officially supported because officially it doesn't even exist anymore.

**Comment by williewillus** [comment]
The proper way for forge would just to be post block breaking events. Then it's up to cauldron to get the forge events, turn them into bukkit events and pass them to the plugins

**Comment by LemADEC** [comment]
MCPC/Cauldron author added hooks directly into Forge. There's no hack required for mods to add support, they just need to use those.

**Comment by scj643** [comment]
The point isn't to make it so they are compatible even though that should be done the point of this is to make it so that they act as if they were there normal counterparts for there tools that breaks one block at a time and shear stuff like normal items as a config option.

**Comment by williewillus** [comment]
This is being worked on.

**Comment by williewillus** [comment]
Now in master. please report any issues.
