### ISSUE TITLE
Arcana ring fire ability problem

### ISSUE THREAD

**Issue by Carbon-Ghost** [sinkillerj/ProjectE#871]
When you fire a Fiery orb at sand, it makes glass but the textures doesn't appear and the glass is just plain orange colored...

**Comment by williewillus** [comment]
Wat

**Comment by williewillus** [comment]
Screenshot?

**Comment by Carbon-Ghost** [comment]
![2015-07-24_16 03 24](https://cloud.githubusercontent.com/assets/10200094/8876093/c4f953da-321d-11e5-9234-d14f878e41e9.png)

**Comment by williewillus** [comment]
is that 1.7 or 1.8? I can't reproduce.

**Comment by Carbon-Ghost** [comment]
1.7.10, latest stable version :c

**Comment by williewillus** [comment]
if you do /setblock ~ ~ ~ glass (turn cheats on) does it look like that?

**Comment by williewillus** [comment]
or rather, when glass is made other ways does it look normal

**Comment by Carbon-Ghost** [comment]
Wait, nvm, don't think it's project E related, for some reasons, the other "normal" textures glass already in world we're also turned into weird glass...

**Comment by williewillus** [comment]
It's probably some sort of rendering issue, especially since the hud/popup says its glass

**Comment by Carbon-Ghost** [comment]
Yeah, but dunno what cause this though ;c ....
