### ISSUE TITLE
Dupe Glitch-Philosopher's stone

### ISSUE THREAD

**Issue by Dilman8110** [sinkillerj/ProjectE#873]
There's a way to get infinite philosopher's stone not from project e but its a different philosopher's stone and if you try to repair them in a crafting table ( with two damaged ones ) if you shift click it will fill your inventory with them so its little broken. Not to mention they have a emc of 2,000 so its something you want to fix soon.

**Comment by williewillus** [comment]
This is a very unclear bug report. I only have a rough idea of what you're trying to say.
If you can, please give DETAILED steps to reproduce. Example:

1. Install ProjectE and <X OTHER MOD>
2. Place PE PhilStone and XMOD's PhilStone together in the crafting table
3. Shift click result
4. Inventory is now filled.

Right now I don't even know what mod or item you're talking about.

**Comment by sinkillerj** [comment]
We cant help you with a Philosophers Stone that you clearly state is from a different mod, you also at no point state that ProjectE causes this dupe.
