### ISSUE TITLE
Config option B:pregenerate=true not fully working

### ISSUE THREAD

**Issue by Bogdan-G** [sinkillerj/ProjectE#876]
Hello.
mod version: PE1.7.3
MC 1.7.10, forge 1492.
https://github.com/sinkillerj/ProjectE/wiki/Configuring-EMC-calculation

On the wiki says that if the file is created pregenerated_emc.json, the calculations will not be made EMC and loaded from a file, but if you make any changes to the file pregenerated_emc.json, the conversion is still going to happen and creators a new file over the old one.

**Comment by MaPePeR** [comment]
Hmm... this should not happen...

it might be caused by a parsing error in the file. i will look into that.

**Comment by MaPePeR** [comment]
Its indeed caused by a syntax error in the file. If you just change values and don't break the parsing it will NOT overwrite the file.

**Comment by Bogdan-G** [comment]
@MaPePeR I removed some lines, retaining the commas and brackets.

**Comment by MaPePeR** [comment]
In my experiments i could not reproduce it without breaking the json.
