### ISSUE TITLE
Watch of Flowing Time - Bug

### ISSUE THREAD

**Issue by Xyrenthius** [sinkillerj/ProjectE#881]
Not sure if it is repeatable but if the game crashes while the watch of flowing time is on an active pedestal it will prevent you from canceling the effect of time fast forward on blocks in the area. Can be rather annoying to always have on.

**Comment by williewillus** [comment]
Just break the pedestal? The effect is applied from the pedestal's tile entity.

**Comment by Xyrenthius** [comment]
Did that and didn't cancel the effect so yea.

**Comment by williewillus** [comment]
place and break another block in its space. Also, the watch keeps acting if it's in your inventory :p
If you have the log from that crash that would help too. Not quite sure what the issue is
