### ISSUE TITLE
AoE mining bypass warded/forcefield/bedrock, config ?

### ISSUE THREAD

**Issue by Carbon-Ghost** [sinkillerj/ProjectE#882]
May we have a config for disabling AoE mining please ? It bypasses indestructible blocks ;c

Sorry if it's already there and I missed it, but haven't found it ^^

**Comment by MaPePeR** [comment]
Duplicate of #450  #508 #380 ?

**Comment by Carbon-Ghost** [comment]
Oops sorry nvm, didn't looked deep enough in issues ^^''

**Comment by Carbon-Ghost** [comment]
Nope, not that protection, I mean in mods, like thaumcraft and Advanced Repulsion System addon to IC2, if it's that I know those issues are open, but this is not plugin/towny/whatever related :/

**Comment by williewillus** [comment]
Different protection per se, but internally it's the same thing.

**Comment by Carbon-Ghost** [comment]
Maybe in the end the conclusion is the same, having config to remove AoE, but issue is different, as plugin protection and indestructible blocks are different ;)
