### ISSUE TITLE
Have to replace SWRG in bauble slot after entering the deep dark

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#893]

**Comment by sinkillerj** [comment]
This affects most items, and any dimension change, the deep dark is not the only dimension affected.

**Comment by MaPePeR** [comment]
Yea. i just saw it happening with the deep dark. i figured that would be the case - but always provide as much data as possible, right?

**Comment by williewillus** [comment]
Ah this is bc the dimension change event only resyncs the normal inventory.
looking at it, I also spotted a few ways the "syncing player capabilities from client to server and vice versa" thing in PlayerChecks could be improved, so I'll take this one and slip a minor refact in too :D
