### ISSUE TITLE
Some items lose their EMC value on relog

### ISSUE THREAD

**Issue by Silly511** [sinkillerj/ProjectE#897]
I have found a bug where some items such as the portal gun lose their EMC value when relogging. I have to use /projecte reloadEMC to fix it. This bug is really annoying because my transmutation tablet keeps de-leaning the portal gun, and I have to cheat it in, and re-lean it.

**Comment by MaPePeR** [comment]
This is a weird one and i'm unsure if we can do anything about it. It appears, that some mods add their crafting recipes after our emc mapping has occured:

```
[11:13:16] [Server thread/INFO]: CraftingMapper Statistics:
[11:13:16] [Server thread/INFO]: Found 196 Recipes of Type class net.minecraft.item.crafting.ShapelessRecipes
[11:13:16] [Server thread/INFO]: Found 469 Recipes of Type class net.minecraft.item.crafting.ShapedRecipes
[11:13:16] [Server thread/INFO]: Found 339 Recipes of Type class net.minecraftforge.oredict.ShapedOreRecipe
[11:13:16] [Server thread/INFO]: Found 43 Recipes of Type class tconstruct.library.crafting.ShapelessToolRecipe
[11:13:16] [Server thread/INFO]: Found 137 Recipes of Type class net.minecraftforge.oredict.ShapelessOreRecipe
[11:13:16] [Server thread/INFO]: Found 1 Recipes of Type class net.minecraft.item.crafting.RecipesMapExtending
```

First Mapping after starting the game:
```
CraftingMapper Statistics:
Found 196 Recipes of Type class net.minecraft.item.crafting.ShapelessRecipes
Found 469 Recipes of Type class net.minecraft.item.crafting.ShapedRecipes
Found 339 Recipes of Type class net.minecraftforge.oredict.ShapedOreRecipe
Found 43 Recipes of Type class tconstruct.library.crafting.ShapelessToolRecipe
Found 137 Recipes of Type class net.minecraftforge.oredict.ShapelessOreRecipe
Found 1 Recipes of Type class net.minecraft.item.crafting.RecipesMapExtending
```
Second Mapping after using `/projecte reloadEMC`
```
CraftingMapper Statistics:
Found 196 Recipes of Type class net.minecraft.item.crafting.ShapelessRecipes
Found 472 Recipes of Type class net.minecraft.item.crafting.ShapedRecipes
Found 339 Recipes of Type class net.minecraftforge.oredict.ShapedOreRecipe
Found 43 Recipes of Type class tconstruct.library.crafting.ShapelessToolRecipe
Found 137 Recipes of Type class net.minecraftforge.oredict.ShapelessOreRecipe
Found 1 Recipes of Type class net.minecraft.item.crafting.RecipesMapExtending
```

so there are 3 ShapedRecipes that were not there in the first run...

For now i would recommend you to: start the game. Enter a world. Open `config/ProjectE/mapping.cfg` and set `B:pregenerate=true`. Then use `/projecte reloadEMC`.

**Comment by Silly511** [comment]
Could you fix this by making the emc mapping happen as soon as you get to the main menu?

**Comment by MaPePeR** [comment]
that would be even earlier than what we do right now. 
It happens in `FMLServerStartingEvent` which is, i think, one of the latest events before you can actually play a world. thats after `preInit`, `init` and `postInit`...
maybe there is a later event - i don't know.

**Comment by Silly511** [comment]
Why in the world is portal gun registering their recipes when you load a world? I thought it was standard for mods to register their recipes in postInit.

**Comment by Silly511** [comment]
Also when I updated project e, tons of items lost their emc value. Even ones I had set with /projecte setEMC.

**Comment by MaPePeR** [comment]
From `#minecraftforge`
```
<Blubberbub> Hello, is there a startup event that happens after FMLServerStartingEvent? I have the problem that when I'm reading the CraftingManager-RecipeList it appears to be missing some recipes for some mods in FMLServerStarting
<heldplayer> FMLServerStarted?
<diesieben07> it is highly unlikely that mods register recipes after that.
<diesieben07> -.- why would anyone do that
<pig> That recipe is config dependent and is set by the server. That's why.
<diesieben07> still, meh
```

So there is `FMLServerStarted` which i will try right now.

**Comment by Silly511** [comment]
I just remembered why portal gun registers it's crafting recipes when you start a world. It's looks at the difficulty and changes the hardness of the recipe for portal gun. So I am guessing that you can't know the difficulty until you go into a world.

**Comment by Silly511** [comment]
If only portal gun is onpen source. Then you could find out exactly when portal gun is registering it's recipes and map the emc values right after portal gun.

**Comment by MaPePeR** [comment]
Not sure if we can actually fix this... 

About your other items loosing emc after an update: that should not really happen... there were no major changes to the emc mapping code i can remember in the latest versions...
Are you sure your custom_emc file is still present?

**Comment by Silly511** [comment]
My config files did not change. I also updated forge multipart so that was probably it.

**Comment by williewillus** [comment]
modders are essentially have to do recipes in preinit now (1.12)
