### ISSUE TITLE
Anti Matter Relay MK1 crashes when you put fuel without EMC in it.

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#898]
Was using shift-click.

https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/tiles/RelayMK1Tile.java#L236

http://pastebin.com/X2tEXC8E

From Tenaco. 
```
<Tencao_Desktop> If you load back in and try and access the relay, you instantly crash
```

**Comment by Tencao** [comment]
To add a bit more info, this was when I put Aeternalis Fuel in the relay when it didn't have an EMC value. Also to add, once you do this, you will not be able to access the relay without crashing until you destroy it

**Comment by williewillus** [comment]
Porblem isnt the TE, it's the shift click code not checking if it has a value, i think.

**Comment by MaPePeR** [comment]
so the shift click code should probably not check for emc, but for that "is item valid for slot"... right?

**Comment by williewillus** [comment]
Validity is determined by having a value :p

**Comment by williewillus** [comment]
Seems to be gone
