### ISSUE TITLE
Cooldown on projectiles

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#904]
This is mostly to prevent spam overload to bypass either protection plugins, or server overload handling all the place events. Adding a 1 second, or 0.5 second cooldown to projectiles shouldn't affect gameplay for players, and prevent people with the intent of abusing it. 

Main items that need this:
Ignition ring
Evertide Amulet
Volcanite Amulet
Philo Stone
Hyperkinetic Lens
Catalytic Lens
Ring of Arcana

**Comment by Lilylicious** [comment]
Basically what's been done for the pedestal, but for the projectiles.

**Comment by partytown** [comment]
you're right about that it wouldn't affect gameplay but if this is added i would like it to be a config option for how long if at all, because i and my friends and sure some other people like to just mess around with that stuff and if there would be a cooldown it wouldnt be as fun

**Comment by williewillus** [comment]
yeah the default is going to be 0 - no cooldown
