### ISSUE TITLE
[Suggestion] AE2 Transmutation Terminal

### ISSUE THREAD

**Issue by Silly511** [sinkillerj/ProjectE#907]
I was thinking project e could have support for ae2, by adding a transmutation terminal that would be just like the transmutation tablet except that instead of displaying the player's EMC it would display the total EMC of all the items in the network. There would also not be a burn slot.

**Comment by williewillus** [comment]
Something like a transmutation terminal beyond the scope of ProjectE itself.  However, fret not, people have been working on things like that! Mordenkainen is making something called Equivalent Energistics that bridges PE-AE and EE3-AE. Check it out: http://www.curse.com/mc-mods/minecraft/231853-equivalent-energistics
