### ISSUE TITLE
Project E Crash

### ISSUE THREAD

**Issue by Jumjac** [sinkillerj/ProjectE#909]
When i try starting my game it crash while loading
Here is the crash log: http://pastebin.com/j7wwUeNT

**Comment by MaPePeR** [comment]
Update your reika mods.

**Comment by Jumjac** [comment]
which one there is alot

**Comment by MaPePeR** [comment]
all of them to the most recent version.

**Comment by Jumjac** [comment]
okay only got some of them in the pack

**Comment by Jumjac** [comment]
Just download all the reika mods and it still crash

**Comment by MaPePeR** [comment]
well... you only need to update the ones you want to have... [but v8 of his mods should fix this...](https://www.reddit.com/r/feedthebeast/comments/3ghbxm/conflict_with_rotarycraft_projecte_and_equivalent/cty5ijh)

But apparently he has not released those yet... i thought he did.. sorry

**Comment by Jumjac** [comment]
So right now i can't use reika mods and project e together?

**Comment by MaPePeR** [comment]
yes

**Comment by Jumjac** [comment]
Okay Thanks for trying to help have a nice day
