### ISSUE TITLE
Condensor MK2 does not have an upper limit on internal emc storage

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#914]
so it will always consume the items and never 'fill up' - even if the output inventory is full.

I wonder what happens if that internal emc storages overflows or becomes Double.INFINITY...

**Comment by williewillus** [comment]
and here I was thinking all our TE's were capped at Integer.max_value lol

**Comment by MaPePeR** [comment]
the addEMC()-method might cap it - but it will still consume items. this is bad

**Comment by williewillus** [comment]
Ill review all of our tiles in the api additions pull
