### ISSUE TITLE
I can only view stone, cobblestone, and dirt in the Transmutation Table

### ISSUE THREAD

**Issue by Apex-Blizzard** [sinkillerj/ProjectE#915]
I don't know what happened. I updated all the mods in my pack and now those are the only 3 items i can search in the transmutation table and i have over 8 million EMC. Please help!

**Comment by williewillus** [comment]
ProjectE version and modlist please (and mudpack if you're using one)?

Make sure the searchbox is clear

**Comment by sinkillerj** [comment]
Do you happen to have a item in the center of the right side of your Transmutation Table? Remove it >,>

**Comment by Apex-Blizzard** [comment]
Thank you sinkiller! That fixed the issue :D
