### ISSUE TITLE
How can I add EMC values Botania items?

### ISSUE THREAD

**Issue by Apex-Blizzard** [sinkillerj/ProjectE#916]
More specifically livingrock, livingwood, and the petals. If you could, could you type the command for them? It would be much appreciated :D

**Comment by sinkillerj** [comment]
The command you are looking for is "/projecte setEMC 256" where 256 is the EMC value. Doing this with no other parameters will set the EMC value for whatever you are holding in your hand.

**Comment by Carbon-Ghost** [comment]
Small advice to avoid loops, stay equivalent to the raw values and don't use  mana as an excuse to have more EMC as you will ultimately create loops :p

**Comment by MaPePeR** [comment]
Be aware, that you cannot assign emc valeus to most of the botania flowers, because these use nbtdata. I hope the petestals use metadata.

**Comment by Apex-Blizzard** [comment]
Thank you all for the replies!
