### ISSUE TITLE
Condenser instantly condenses items on world load?

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#917]
Not sure if i understand [this](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/tiles/CondenserTile.java#L91-L94) and [this](https://github.com/sinkillerj/ProjectE/blob/30a6d0393da9f6bf834687ae7028381c7d31ba52/src/main/java/moze_intel/projecte/gameObjs/tiles/CondenserTile.java#L107-L114) code correctly, but i think that is what it does

**Comment by williewillus** [comment]
Definitely intended. 
Needed? idk. There must've been some intent for it in the past

**Comment by MaPePeR** [comment]
Remove it and see what breaks? :wink:
