### ISSUE TITLE
void ring lag when teleporting to unloaded areas and allows glitching

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#919]
simply try to TP usually result in server tick rate drop also it sometimes will allow to pass through blocks
and get stuck in ground/wall

**Comment by sinkillerj** [comment]
Not much can be done about this beyond increasing the chunk loading range in your server properties.

**Comment by blackdragonIV** [comment]
i forgot to say this was single player :/

**Comment by williewillus** [comment]
I'm tempted to call this invalid.... 
What the ring does, is asks if you are looking at a block. If that block is within 64 blocks (4 chunks MAX), teleport there.
In all other cases, simply teleport 32 blocks (2 chunks) in the direction you're facing.

In both those cases, an Ender pearl can travel the same distance or further (especially if you got a good high up spot to throw it). So blaming it on PE isn't really valid :p. Try doing the same with some pearls.

**Comment by williewillus** [comment]
As for the glitching into walls, I'll tweak that after all my current PR's are done. I've got too many of them.

**Comment by williewillus** [comment]
I improved the glitching as much as I can, it still is a bit (see ender pearls lol)

As for the teleport lag, I tried to protect against it by making a cooldown of 0.5 sec (10 ticks), so people can't spam it faster than that and lag out the server.
