### ISSUE TITLE
Localization project for Aether Addon

### ISSUE THREAD

**Issue by Adaptivity** [sinkillerj/ProjectE#920]
@sinkillerj not sure if you are going to open source it but if not please create a repository for localization files. Thanks in advance.

**Comment by sinkillerj** [comment]
Open source should be out within the week.

**Comment by Carbon-Ghost** [comment]
Wait what ? Aether ... ? Like the mod ?

**Comment by williewillus** [comment]
1. Yes, sin is releasing a small aether-PE crossover.
2. Please don't necro >.>

**Comment by sinkillerj** [comment]
Have at it: https://github.com/sinkillerj/ProjectE-Aether-Addon

**Comment by Carbon-Ghost** [comment]
Sorry, just was hyper excited :D
