### ISSUE TITLE
red/dark matter using emc from collectors while idle and RM furnace GUI

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#923]
simply while idle and not smelting rm/dm furnace will use emc from adjacent collectors to keep it running, the effect is the only a mk3 collector is enough to keep the furnace going while in ee2 the furnace used emc when it is smelting and a mk1 collector was more than enough 

also red matter furnace have out of place flame and smelting arrow placement in the gui

**Comment by williewillus** [comment]
First is known issue and fixed in apitweaks pull, second is also known but sin hasn't pulled the fix after 6 months ;p

**Comment by blackdragonIV** [comment]
ok then no need for this
