### ISSUE TITLE
Cannot transmute Lava to obsidian using philosopher stone

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#924]
Probably caused by [this](https://github.com/sinkillerj/ProjectE/commit/5a9165f7cdf839a48def12fb2c9c654204b0f3a0) commit from ages ago, that fixed another issue.

`#minecraftforge` claimed that the bug in `getMovingObjectPositionFromPlayer` was fixed in 1.8.

@williewillus could you take a look at that method in 1.8, so we maybe can get that fix into 1.7?

**Comment by williewillus** [comment]
dc08afa
