### ISSUE TITLE
left side of transmutation table

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#927]
it is made pointless since it is not functional so any plans on making it functional ? also it was the only effective method of charging a star directly via the table

**Comment by williewillus** [comment]
??? it is fully functional
as always, elaborate please. Make it an actual issue report

**Comment by blackdragonIV** [comment]
oh the issue is that placing an item in there dose not add its emc to the table, try placing an item or a filled star the emc will not show up on table

**Comment by MaPePeR** [comment]
i think he is expecting the same behaivior as EE3 and old EE2, where you could place items in the left slots that could then be used for transmutation

**Comment by blackdragonIV** [comment]
pretty much

**Comment by MaPePeR** [comment]
i don't think that is needed - the burn slot is much more easy and allows you to do everything you want

**Comment by blackdragonIV** [comment]
maybe but i dont think that burning a whole star full of emc just to get an item out is very convenient

**Comment by MaPePeR** [comment]
decharge in the lock slot

**Comment by blackdragonIV** [comment]
ok that works too

**Comment by denzuko** [comment]
blackdragonIV one thing to add, burning a charged star adds the value of the uncharged star _and_ the charge. Therefor one can just recover the uncharged star first before using up any other emc.
