### ISSUE TITLE
NEI Integration for Bag-Recoloring

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#929]
I don't think someone actually knows [this custom IRecipe](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/gameObjs/customRecipes/RecipesAlchemyBags.java)

**Comment by Lilylicious** [comment]
Planned solution: Will add it as a shapeless recipe in NEI that cycles between possible dyes and outputs. Also planning a bit of refactoring of the recipe codes to be more.. sensible. Multiple instances for each recipe for example.

**Comment by MaPePeR** [comment]
Yea, it would be great, if it would not create 16 recipes for each bag in NEI.

**Comment by williewillus** [comment]
not an issue in 1.12
