### ISSUE TITLE
Certain items have no value in 1.8

### ISSUE THREAD

**Issue by williewillus** [sinkillerj/ProjectE#943]
This is after merging all the PR's for what would be 1.7.10 branch's release 1.9 beta, maybe you can look at the CraftingMapper @MaPePeR and see what's wrong? Diamond pickaxe, our picks, and sticky pistons are some of the ones that don't have a value. Poke me on irc if you need more info

**Comment by MaPePeR** [comment]
@williewillus this is fixed now, isn't it?

**Comment by williewillus** [comment]
You poked a line of code and i don't remember if i fixed it yet, lemme check

**Comment by MaPePeR** [comment]
https://github.com/sinkillerj/ProjectE/commit/a506edfb4a4188887cbbcd4e349d5c18eb63f6bf
