### ISSUE TITLE
[Suggestion] Configurable Item -> EMC -> Item loss of EMC

### ISSUE THREAD

**Issue by 5830ification** [sinkillerj/ProjectE#947]
I'd like to suggest a configurable rate (defaults to 1.0) to which EMC is lost when breaking down items to EMC. This would greatly help to incorporate Project E in modpacks while maintaining balance a little bit better.

Example:
1 Diamond -> 8192 EMC
Burn the Diamond in a transmutation tablet -> you end up with _Configured rate_ * 8192 EMC

**Comment by sinkillerj** [comment]
Duplicate suggestion, planned for once buying and selling are split methods.
