### ISSUE TITLE
Update Forge

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#948]
Would like to be able to stick Tinkers Construct into my dev environment without needing to upgrade my branches temporarily.

Any reason we are not on recommended?

We are on `10.13.2.1291` recommended is `10.13.4.1448`

(I think its maven-version name is changed now, though. i think to get it you need `10.13.4.1448-1.7.10`)

**Comment by williewillus** [comment]
Seconded, we were concerned with fluids a while back but now that TE and Tinkers have both updated and they both have tons of  fluid handling I think we can too

**Comment by Parker8283** [comment]
It's -1.7.10 on the end because it's on the 1.7.10 branch of the repo.

**Comment by sinkillerj** [comment]
No.

**Comment by williewillus** [comment]
Why? The version we are using is years old...
