### ISSUE TITLE
Version 1.8.0+ Crashes with Reika's Chromaticraft

### ISSUE THREAD

**Issue by ShadowsVengeance** [sinkillerj/ProjectE#950]
I'm not sure if this is your side or his side, but it works fine with PE1.7.3.

Crash-Log: http://pastebin.com/rqcGgVPU

**Comment by williewillus** [comment]
Known issue, Reika's v8 mods will resolve this issue

**Comment by sinkillerj** [comment]
Duplicate issue, this is on Reika's side, he will need to update his mods to use the new API or remove the blocking code.

**Comment by williewillus** [comment]
@sinkillerj ninja'ed ;D
