### ISSUE TITLE
[1.9 beta] still flying with swiftwolf even when not in inventory

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#951]
simply take swiftwolf and fly then drop the ring to the ground. what you will get is you will still be flying and also you can leave it on the ground land and double jump and fly again, pretty much creative flight until the ring despawn or something

**Comment by blackdragonIV** [comment]
ok nvm arcana dose not seem to cause an issue however i just burned my swiftwolf and still flying >.>

**Comment by williewillus** [comment]
Are you sure you don't have an arcana or gem boots on as well? Those two provide unlimited free flight as long as you have them

**Comment by blackdragonIV** [comment]
nope no armor set try for yourself

**Comment by williewillus** [comment]
I got it, thanks.

**Comment by blackdragonIV** [comment]
np
