### ISSUE TITLE
Hurricane Boots - No option to re-enable EE2-like behavior

### ISSUE THREAD

**Issue by Omnipraesens** [sinkillerj/ProjectE#956]
I know the official decision is to have flight through the Gem Boots be creative flight, but for those of us who liked the old EE2 Hurricane Boots, can you please add a config option to allow EE2-style flight behaviour (as in, non-creative style flight) with the Gem Boots?

I really liked the EE2 Hurricane Boots' flight behaviour, and unfortunately have little knowledge of Java with which to implement the feature myself.

**Comment by williewillus** [comment]
It was originally implemented that way but then @sinkillerj requested (required ;)) it to be changed to creative flight. Is it okay I readd this as a config sin?

**Comment by sinkillerj** [comment]
Ill leave this one up to you, you normally hate extra configs lol. Regardless of which flight method is chosen the flight should be unified across all items that provide it.

**Comment by Carbon-Ghost** [comment]
But can we keep also current one, I kinda love being able to slowly gently glide across amplified mountains while retaking height with the creative flight if needed ^^

**Comment by Omnipraesens** [comment]
The solution I was proposing, in order to please all parties involved, would be to add  config switches to modify the flight behaviours of various items.

This would allow a unified default flight behaviour (same as the current, by default), while still allowing server owners and/or players with a specific personal preference to change the behaviour of individual items to their liking. 

As such, the default behaviour of the mod would not change whatsoever, and the addition of the config option would not affect those who do not actively choose to change the setting from default.

Please note, I fully understand how much work programming is (I am fluent in C++ and a couple other languages myself), and I would gladly submit the proposed changes in code myself if I had any experience with Java.

RE: Carbon-Ghost: If my suggestion is followed, the current behaviour would still remain the default. There would be no change in gameplay for players who do not enable the config option.

**Comment by Carbon-Ghost** [comment]
Oh kk :D I can try make a config, but I may break the mod a few times before I make a stable version, lol.

**Comment by williewillus** [comment]
@sinkillerj the boots used to have a "hold space to ascend and when you release you glide slowly"
And I think it should be able to be different than say the SWRG and Arcana. Why would anyone want to have the other two items if the boots provides the exact same thing?

I think just one config for the boots EE2 mode <-> creative flight is good

**Comment by williewillus** [comment]
I readded it alongside the creative flight - they don't interfere with each other.
Now, hold space for EE2 wheeeeee, double tap for standard creative flight

**Comment by Omnipraesens** [comment]
@williewillus I like that, a lot better than the hackish fix I was working on! 
I hope it gets accepted into master!

**Comment by sinkillerj** [comment]
If we are going to have dual function like that add a tooltip please.

**Comment by Carbon-Ghost** [comment]
Aow, I still prefered the hybrid previous one :P xD

I can try to config it, but I might break Project E a few times before figuring out what I am doing...

**Comment by williewillus** [comment]
What? I'm adding both of them together...

**Comment by Carbon-Ghost** [comment]
Yeah, but I liked being able to do vanilla jumps w/ slow fall and take some height using creative flight, not jetpack like :/

**Comment by williewillus** [comment]
you can still do that....

**Comment by Carbon-Ghost** [comment]
Yeah, but my jumps are not going to be 1 blocks ones, so it might be annoying in some cases ^^''°

**Comment by Omnipraesens** [comment]
Well, it's not like it would be exceptionally hard to add a config option (or hotkey, for that matter) to change between different flight behaviour modes. Just one or two lines in the config, and a couple if statements in the item implementation file (if I'm understanding how the code works, and not missing any necessary hooks, that is).

Perhaps a config option called gemBootsFlightType, accepting an integer value from 0-3, with a default of 0, where 0 is hybrid (creative + hold space to rise), 1 is creative-only, 2 is hold space to rise only, and 3 is disabled.

That's bound to please everyone, even if it does increase code complexity slightly.

**Comment by sinkillerj** [comment]
I'm still not sure why people are trying to overcomplicate the concept, nothing is changing. If you hold you go up like a jetpack, if you double tap you creative fly, there is no need for a config if willie can make that work, nor does one of the other get in the way of your particular flight style.

**Comment by williewillus** [comment]
^
