### ISSUE TITLE
config for activating offensive ability

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#957]
i am constantly finding it difficult having to cycle for an empty hand just to fire a lightning bolt from the gem armor , now i know this was a discussion from an old ticket i posted but i think i found a solution to satisfy both side

please add config option which will let player select if gem armor will activate when holding item or not provided that the held item is not from project E since similarity in key binds

**Comment by Carbon-Ghost** [comment]
Already implemented in latest version afaik :P check your config, I use it :P

**Comment by Carbon-Ghost** [comment]
I think, last time I touched configs, it was for the same reason, since then I haven't shot a lightning bolt.

**Comment by blackdragonIV** [comment]
no there is nothing i see about it in there

**Comment by Carbon-Ghost** [comment]
Wait, you seem to be right, nvm then.. But wait, lightning bolt is R right ? But does it requires EMC ? Doesn't works for me iirc...

**Comment by blackdragonIV** [comment]
1 yes it is R
2 no it dose not require EMC..... i think
3 you need to not hold an item (obviously)
4try pressing V to activate offensive abilites

**Comment by Carbon-Ghost** [comment]
Oh yeah forgot I deactivated them for not blowing up my house, herp derp xD

**Comment by williewillus** [comment]
You want a config for whether the activatation will not need empty hand or the actual ability?

**Comment by blackdragonIV** [comment]
both kinda like the original EE2 behavior

**Comment by williewillus** [comment]
okay

**Comment by blackdragonIV** [comment]
ok thanks :)

**Comment by Carbon-Ghost** [comment]
^^ nice, but will there be an actual config for disabling completely the offensive stuff ?

**Comment by williewillus** [comment]
sure

**Comment by Carbon-Ghost** [comment]
Last thing, may you add a config for disabling completely AoE mining on mining items ? So we can still keep the hammer, lens etc... and craft them for later items, but can't use them like the watch of the flowing time ^^

**Comment by Carbon-Ghost** [comment]
Sorry to necro, but just may you consider adding what I requested if possible please ? :O Similar to how works the watch of the flowing time when "disabled".
