### ISSUE TITLE
(Just a talk) IC2 Classics Update

### ISSUE THREAD

**Issue by Speiger** [sinkillerj/ProjectE#958]
@williewillus you want to update IC2 Classic to 1.8...

I personally do not want that, because i am still maintaining it...
Whyever you wanted to do that you should first tried to ping me that we could talk about that...
But for now i simply want you to stop that...

**Comment by sinkillerj** [comment]
Please keep discussion of this type to private messages or tweets, this is not the place.

**Comment by williewillus** [comment]
@Spieger
1. This repo is not the place. PM me on twitter.
2. It's for private use. I'm not releasing it.
