### ISSUE TITLE
[Feature Request] Ability to place Transmutation Tablet on walls

### ISSUE THREAD

**Issue by Silly511** [sinkillerj/ProjectE#959]

**Comment by Carbon-Ghost** [comment]
I mean why not xD Though, I'd rather keep them as slabs, :neutral_face:

**Comment by Silly511** [comment]
Why I wanted it is so I can place a transmutation tablet beside my ME terminal.

**Comment by sinkillerj** [comment]
If a addon author wants to do this they can feel free, but I dont see adding this to any official addon. Please look into this for further ME integration: http://forum.feed-the-beast.com/threads/1-7-10-equivalent-energistics-autocrafting-with-emc.95847/
