### ISSUE TITLE
MineTweaker integration for custom IRecipes

### ISSUE THREAD

**Issue by Thepiggy** [sinkillerj/ProjectE#960]
The philosophers stones crafting system was changed so now mods like minetweaker can no longer turn off the smelting crafting recipes... It mostly affects modpacks but still..

**Comment by sinkillerj** [comment]
Seams to me the most optimal solution would be a config on our side to completely disable the smelting function. Any objections @Lilylicious @williewillus ?

**Comment by Thepiggy** [comment]
Seems legit, I don't think many people do it anyway because you have to use coal and coal has good emc

**Comment by Lilylicious** [comment]
I'll take care of it, either fixing the minetweaker thing, a config or both.

**Comment by Lilylicious** [comment]
Taking it a step further, doing a full minetweaker integration. Planned features:

* Removing/adding hidden shapeless recipes
* Removing/adding klein star recipes
* Removing/adding AlchBag recolouring
* Removing/adding world transmutations
* Anything else that comes to mind

**Comment by sinkillerj** [comment]
Next version will have improved MineTweaker support, closing.
