### ISSUE TITLE
Can't Take Certain Items Out of Transmutation Tablet/Table

### ISSUE THREAD

**Issue by rux616** [sinkillerj/ProjectE#961]
Issue #137 was closed back in October 2014, but I am having this issue right now.

I run a small server using the Mad Pack 3 beta 3 modpack (which uses Fastcraft) and there are some items that when you click it, a copy of the item gets picked up by the mouse cursor, but then disappears almost instantly.  You appear to lose the EMC for that item, but if you close the transmutation interface and then go back in, the EMC reappears.  Also, if you shift-click for a stack of said item, the item appears in your inventory until you close the transmutation interface, then disappears.

It doesn't appear to happen as often if you narrow down your search, but there are times where even that doesn't work.  When that happens, it simply renders you unable to transmute that item.

If there's any way I can help, please let me know.

**Comment by Thepiggy** [comment]
that was happening to me too it seems to be a bug with every item that has () in the name

**Comment by rux616** [comment]
For me, it's more than just names with ().  I'm running into it quite a bit with items from the EnderIO mod, such as the Vibrant Alloy ingot.

**Comment by Thepiggy** [comment]
report every item that's doing it and I think they will fix it

**Comment by sinkillerj** [comment]
Please try the latest beta and see if it fixes these items.

**Comment by Thepiggy** [comment]
lol I'm testing with the latest beta and I love that if the stack emc of an item is to high it goes into full blown Obfuscated mode

**Comment by rux616** [comment]
Ok, upgrading to the 1.9.0 beta fixed it with all the items I am aware of having the issue.

@sinkillerj, would you like me to close this issue and report wonky items individually, or keep this issue open and add them here?

**Comment by sinkillerj** [comment]
For now we have all the info we need, however once the next beta is out another test would be appreciated, there are a few things we have to change.

**Comment by rux616** [comment]
Alrighty, I'll go ahead and close this for now, then. Thanks for the quick responses.
