### ISSUE TITLE
Small: EMC loss

### ISSUE THREAD

**Issue by Thepiggy** [sinkillerj/ProjectE#963]
This picture about sums it up:
![emclose](https://cloud.githubusercontent.com/assets/13069706/9426809/0425f8c4-4925-11e5-9f3d-07bb63ad4d48.png) if you shift click it will fill the emc tablet and you only lose a little, but you get to keep 32 red matter thingys, if you just pick up the red matter thingys and place them in it fills up the tablet but you lose all the red matter thingys..

**Comment by sinkillerj** [comment]
This is intended cap behaviour.

**Comment by Carbon-Ghost** [comment]
May you describe us what cap behaviour is and how it works ? Also why does the EMC tooltips sometimes have a thing in the middle of more than 3 digits and stack EMC is somtimes bugged in modpacks, but in mine it just works fine ? I have the same version...

**Comment by Thepiggy** [comment]
I don't think you understand the issue, if you shift click you get to keep 32 red matter furnaces, if you drop them in you lose all of them, also @Carbon-Ghost the stack emc is not bugged it's because my modpack has custom recipes that 1. make the red matter furnace the last furnace to craft (because of how op it is) and 2. make it's emc so high that when in a stack of 64 the number is to high and it does the things it's not a bug.

**Comment by Carbon-Ghost** [comment]
Well my modpack also have custom recipes, but everything works fine... The recipes changes almost all EMCs :P

**Comment by MaPePeR** [comment]
@Carbon-Ghost the "obfuscated" emc value indicates that its bigger than a max value - thats a feature that actually was fixed a few versions ago.
