### ISSUE TITLE
Can not unlearn anything which is learned by tome of knowledge 

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#970]

**Comment by sinkillerj** [comment]
This is a known limitation with all versions of ProjectE.

**Comment by williewillus** [comment]
This is because we use a cache to hold the tome knowledge. We should still have this cache there, but instead of redirecting all getKnowledges to just return the cache, just add all the things in the cache not already present in user knowledge to the user knowledge. Implementation details are tbd
