### ISSUE TITLE
(1.9B)morning star dose not follow DM/RM shovel on dirt

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#971]
simply morning star should follow a shovel behavior when right clicking on dirt, sand and gravel however when clicking on dirt with some stone/ores around the star would completely wipe both stone/ores and the dirt unlike the behavior with sand/gravel

**Comment by pupnewfster** [comment]
Closing as I do not believe this should happen after the tool internals rewrite in 1.14/1.15
