### ISSUE TITLE
[suggestion] rotating item when placed on pedestal

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#972]
cosmetic enhancement. simply items which are placed on the DM pedestal will behave kinda like the book on the top of enchanting table, they would rotate slowly and face a player when near them very cool cosmetic effect and honestly the simple just render an item on top like back in ee2 is really pale and boring

**Comment by williewillus** [comment]
i might backport the one from 1.8

**Comment by blackdragonIV** [comment]
oh so that already exist in 1.8? ok did not know and i guess there is no need since things are moving toward 1.8 anyway and would be just a waste of time to port the code back
