### ISSUE TITLE
[1.9 BETA] ProjectE conflicting with Morph flight.

### ISSUE THREAD

**Issue by joshjl303** [sinkillerj/ProjectE#975]
Version: ProjectE-1.7.10-PE1.9.0B

 The current beta release of ProjectE is conflicting with Morph flight in some way. I tested ProjectE-1.7.10-PE1.8.0 to see if it also conflicted and flight works with no problems. I wish I could give more info, hope this helps. 

Thanks for this wonderful mod, keep it up!

**Comment by mintcandle** [comment]
Can confirm it happens with:

Angel Ring from Extra Utilities
Flügel Tiara from Botania
/fly from Essentials

Seems like any item providing "double-tap-spacebar creative flight" doesn't work
