### ISSUE TITLE
emc pregen error

### ISSUE THREAD

**Issue by giuseppeM99** [sinkillerj/ProjectE#976]
the emc of the diamond block is incorret
"minecraft:diamond_block|0": 18432

**Comment by sinkillerj** [comment]
You are gonna have to give us more than that, why do you consider this value to be incorrect? 

As a diamond block is 9 diamonds this would indicate that you set the value of diamonds to be 2048 each, or that you changed the EMC value of the diamond block. I would advise checking your custom emc file and regenerating your pregen once you are happy with your new values.

**Comment by giuseppeM99** [comment]
i've regenerate the EMC value without any customEMC and in the pregenerated emc i've found some error
  "minecraft:diamond_block|0": 18432,
  "minecraft:jukebox|0": 2112,
  "minecraft:emerald_block|0": 18432,
  "minecraft:diamond|0": 8192,
as you can see the correct value of the diamond is 8192 but in a crafting table it comes 2048 like a gold ingot and the emerald value is wrong

**Comment by williewillus** [comment]
what version of projectE are you using?

**Comment by giuseppeM99** [comment]
1.7.10-PE1.8.0

**Comment by MaPePeR** [comment]
Did you delete your pregenerate-emc file before you redid the emc calculation?

What is the issue here? The values are weird - yes. but that is probably caused by weird crafting recipes for diamond_blocks and/or custom emc values...
