### ISSUE TITLE
Alchemical Bag/Gem of Eternal Density

### ISSUE THREAD

**Issue by thefnitalian** [sinkillerj/ProjectE#977]
http://paste.ee/p/i48Ut
Above is a copy of the log and the steps to recreate it is just to log in to a game.
I have tried the last three stable versions of ProjectE that all crashed. They do not crash when I log into any other saved game started within Infinity such as a test world. I have used NBT editor to erase the bag  and the gem and when I relog, the game magically remembers what my inventory was and crashes.

**Comment by sinkillerj** [comment]
What did you do before the crash occurred the first time? Logging into the game is not steps to reproduce.

**Comment by thefnitalian** [comment]
Monday it played normally. I decided to add the extra health enchanted mod and once I did that it crashed. I removed the mod and then when I relogged I started getting this error in the crash log.

**Comment by williewillus** [comment]
"magically remembers your inventory" this sounds like you might have some of the old bag save files from before ProjectE 1.7. That is probably why it seems to be restoring. If your player.dat does not have bag data then it is copied from your old pre-ProjectE 1.7 bag data

**Comment by williewillus** [comment]
Delete saves/<worldname>/ProjectE/<everything in the folder>

**Comment by thefnitalian** [comment]
http://paste.ee/p/8McWO
This is what I get now that I deleted saves/<worldname>/ProjectE/<everything in the folder>

**Comment by williewillus** [comment]
Can you upload your player.dat (level.dat if Singleplayer) somewhere and send the link here?

**Comment by thefnitalian** [comment]
Date: Thu, 27 Aug 2015 16:30:33 -0700

**Comment by thefnitalian** [comment]
it was the level.dat in the nbt editor that had the alchemist bag data that had to go. thank you for all your help

**Comment by williewillus** [comment]
Hm yeah, probably an item got saved incorrectly or partially and got a null-item itemstack into the bag for some reason. No prob!
