### ISSUE TITLE
Contents of Black Alchemy Bag disappear on load

### ISSUE THREAD

**Issue by papachabre** [sinkillerj/ProjectE#98]
I thought it was a fluke, but any time I fill my black Alchemy Bag with any items, the next time I load my game they have disappeared. I don't know if this is true for any other colors, but in my current game the white bag seems to be OK and in my previous one I used a brown bag with no problems.

Edit: Just tried in creative with each color of bag. Black bags are the only ones that exhibit this glitch for me.

**Comment by nayfaan** [comment]
still have this issue in the latest build with my yellow alchemical bag. not all is lost, but half of my items are lost, i had ores and crushed ores in the bag, all the crushed ores were lost but not the normal ores. crushed ores are from industrial craft 2 (IC2), it does not happen every time i restart though.
