### ISSUE TITLE
(suggestion) aesthetic overhaul to emc storage in rings and items and some extra uses

### ISSUE THREAD

**Issue by blackdragonIV** [sinkillerj/ProjectE#982]
my idea revolves around a lot of changes to how items use up emc when functioning

first of all is a change to how emc is used. items will now have a set limit to how much emc can stored which will be shown in tool tip (yes i know that something like this already exist but currently tools directly use how much emc they need to preform the action from the star/fuel and do not have their own internal buffer). ex swiftwolf can hold 5/5k emc in its internal storage and will use up that emc to perform its actions until the internal buffer is empty and it will then use up the largest possible fuel item to fill up its emc buffer but it will not void fuel by eating over the limit of how much it can carry emc from fuel, also stars will have priority over fuel items. also higher tier items will have more internal storage, ex arcana ring can hold 15/15k emc and ignition ring can hold 2/2k

a quick presentation of how much emc is currently stored inside the item  is something inspired by ender IO dark armor, items will now have 2 bars one will show the charge level while other will show how much current emc is inside the said tool.

a good aesthetic enhancement comes on gem of eternal density and void ring, the internal usage of both items will change depending on the target of the conversion like iron 256 and gold 1024... etc once the internal storage fills up the target item will be created

practical use for this is a change in crafting using these tools example

volcanite amulet will now use some emc from internal storage to create a ghost copy of a lava bucket when crafting with it, said ghost lava bucket will be in ore dictionary with a normal lava bucket  and can not be pulled from crafting table or dropped or anything. so now no worry about making lava buckets, other way is to create a lava bucket without adding redstone to the recipe just use internal emc storage

other uses may come in the future

**Comment by sinkillerj** [comment]
We will not be changing the core fundamentals of the mod.

**Comment by williewillus** [comment]
You need to be more clear what exactly it is you're suggesting (I still don't know after reading it twice), and for the love of god please only suggest one thing at a time. Be short and concise.

**Comment by sinkillerj** [comment]
He wants items to store EMC, which is frankly a no, thats what Klein stars are for, it makes no sense for a item to be able to store EMC without the required covalent foci shapes.

**Comment by Carbon-Ghost** [comment]
Sin, can we talk about fuel items ? I want my players to only use klein star for EMC ^^0'' Is it possible to have a config for that ? Because fuel items aren't really here if we exclude the collector "fuel upgrade", as the transmutation table is universal again ^^

**Comment by blackdragonIV** [comment]
well the idea is a small buffer for items which they use until it run out then they refill from fuel/star and the emc they hold can be used in crafting ex emc from volcanite amulet can be used as a lava bucket in crafting

@sinkillerj my idea is just adding an buffer for items and not to completely remove dependency on stars

**Comment by Carbon-Ghost** [comment]
If it's that they already have a small buffer, just saying :P

**Comment by blackdragonIV** [comment]
read the main post again that is what i am trying to say

**Comment by sinkillerj** [comment]
@Carbon-Ghost This will likely come with the changes in #891 

As for the internal buffer, this is purely technical, it is not in the scientific lore.

**Comment by williewillus** [comment]
Should probably remove the storedemc tooltip for those then (remove the hardcoded check for "StoredEmc" tag from here https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/events/ToolTipEvent.java#L214) which was there before I refacted to add IItemEmc, but just kept there in case of complaining ;p
