### ISSUE TITLE
matter ball

### ISSUE THREAD

**Issue by partyanimal** [sinkillerj/ProjectE#986]
so i am busy with a project but have a problem with the materballs created by the tools no mod can interact with the matter balls like the vacuumhopper from openblocks could you fix it so other mods could pick it up

**Comment by MaPePeR** [comment]
You can disable them in the ProjectE.cfg

**Comment by sinkillerj** [comment]
As Blub mentioned disabling them is the best way to allow mod interaction at this time, thanks to modern vanilla improvements, and improvements on our side, you should not see much of a performance drop.
