### ISSUE TITLE
Duping tools with enchantments 

### ISSUE THREAD

**Issue by Tencao** [sinkillerj/ProjectE#988]
As a player has reported to me, duping tools with enchants doesn't work. It asks for the tools emc + enchant emc, but it only outputs normal tools. On a side note, and maybe related to this, the reported tools duped by this would not repair. The repair part could be my doing, but I'm leaving it here incase it's related.

**Comment by sinkillerj** [comment]
I assume you mean transmutation. Beyond it asking for the enchanted EMC value to create a item this is intended behaviour.

**Comment by williewillus** [comment]
Enchantments are stored using NBT, so unless that item is on the NBT whitelist it won't get replicated.

That being said, if it's not whitelisted it's probably a bug that it's asking for a higher price anyways

**Comment by Tencao** [comment]
I meant duping through the condenser rather than the transmutation table/tablet. And for the record, as far as I know, this was tried with mostly vanilla tools.

**Comment by williewillus** [comment]
Same thing, the same NBT whitelist is checked for both

Vanilla tools aren't nbt whitelisted by default

**Comment by MaPePeR** [comment]
The problem is, that the condenser uses the "get EMC" method that adds extra emc based on NBT, but the item is not consumed. So if you put a full Klein star it might consume the EMC for the full star to create an empty one

**Comment by williewillus** [comment]
the overload for getEmc for itemstacks should check nbt whitelist before adding stuff like that

**Comment by MaPePeR** [comment]
No, the condenser should use a get emc that does not have this. 

This is like implicit  different prices for buy and sell: the condenser should use the "sell" price for an item, but uses the "buy" price that is increased because of enchants. (because we don't have that separated)

**Comment by KiritoKun223** [comment]
So to solve this problem, do you have to put an item into the NBT whitelist to copy it with enchantments or is that not possible in general?

**Comment by pupnewfster** [comment]
Assuming you are talking about 1.14+, there is a config option in processing.toml. If you set `persistent` to false for the `EnchantmentProcessor` it won't copy the enchantments but still give EMC for them, and if you set `enabled` to false it won't copy or give EMC for them.

**Comment by KiritoKun223** [comment]
Yeah I am on 1.12, was wondering how to properly get the NBT whitelist to work, I'd like to copy enchanted books etc, but can't get it to work atm
