### ISSUE TITLE
Katar EE2 feature parity

### ISSUE THREAD

**Issue by shobu9** [sinkillerj/ProjectE#993]
it's been a really asked feature, the katar should have more modes then https://dl.dropboxusercontent.com/u/15990261/ShareX/2015/09/2015-09-06_20-09-29.mp4

in the old version it used to have a cut tree only mod.

*add enchancement tag

**Comment by Mattabase** [comment]
Still wondering why the feature was removed? I mean it used to work just fine.

**Comment by williewillus** [comment]
I didn't know it didn't match EE2. Whenever I refactor or clean code I just keep everything as it was, so I'll try to correct this soon

**Comment by Mattabase** [comment]
Fair enough, also sorry if my last message came off as hostile. Tired Matta is Tired.

Glad to see it coming back. =)
