### ISSUE TITLE
tonight i have a big problem with MFR

### ISSUE THREAD

**Issue by danielkanjo** [sinkillerj/ProjectE#995]
when i was try to instal old school ee2 first issue what i have is MFR (minefactory reloaded) i can't load the world or create the world when i try it i get (internal server shut down) when i watch the log file it says

[FML/]: Fatal errors were detected during the transition from AVAILABLE to SERVER_ABOUT_TO_START. Loading cannot continue

[01:39:10] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[01:39:10] [Server thread/ERROR] [FML/]: Caught exception from MineFactoryReloaded|CompatThaumcraft

i tried all version of MFR but it won't work when i delete the MFR the all works fine :S
i treid to find i way to fix it but in the crash log nothing was writed :S

that what i wrote is from server lof file cause when he "crashed" minecraft i stil loaded i but i can't load any of my world and can't created any world... when i remove the MFR all works fine :S

**Comment by Lilylicious** [comment]
What about this issue is related to ProjectE?

**Comment by ZeronTheXeon** [comment]
...wat


Post your problem here:  www.minecraftforum.net/forums/support/modded-client-support

**Comment by denzuko** [comment]
Two things: 
  - Is there a pastebin of your related fml-client-latest.log from the crash?
  - Do you actually have ProjectE installed? EE2 and EE3 is not ProjectE.

**Comment by sinkillerj** [comment]
Leaving this open for now, but @danielkanjo please provide a full pastebin'd log as den suggested.

**Comment by williewillus** [comment]
It's been 10 days, closing this. Please comment if you have further details of how your crash relates to PE
