### ISSUE TITLE
Item with no value shift-clicked into AMR causes crash

### ISSUE THREAD

**Issue by hotrods20** [sinkillerj/ProjectE#996]
Accidentally shift-clicked an item with no EMC value into an Anti-Matter Relay MK3 and the game crashed with a can't divide by zero bug.
EDIT: Looked at code. It only checks if the EMCMapper has the item. It doesn't check if the EMC value is zero.

**Comment by williewillus** [comment]
what version, latest?

**Comment by hotrods20** [comment]
Yeah, using the latest as of this morning. Still happens.

**Comment by MaPePeR** [comment]
Can not reproduce this with current master. Also duplicate of #898
